# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\TissueJournal\LaboratoryCalculator\CalculatorWidget.ui'
#
# Created: Fri Jun 15 12:17:35 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CalculatorWidget(object):
    def setupUi(self, CalculatorWidget):
        CalculatorWidget.setObjectName(_fromUtf8("CalculatorWidget"))
        CalculatorWidget.resize(751, 310)
        self.gridLayout_2 = QtGui.QGridLayout(CalculatorWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tableView = CLaboratoryCalculatorTableView(CalculatorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.gridLayout_2.addWidget(self.tableView, 0, 0, 4, 1)
        self.lblMaxGroupValue = QtGui.QLabel(CalculatorWidget)
        self.lblMaxGroupValue.setObjectName(_fromUtf8("lblMaxGroupValue"))
        self.gridLayout_2.addWidget(self.lblMaxGroupValue, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 1, 1, 1)
        self.edtMaxGroupValue = CMaxGroupValueSpinBox(CalculatorWidget)
        self.edtMaxGroupValue.setMaximum(9999999)
        self.edtMaxGroupValue.setProperty("value", 100)
        self.edtMaxGroupValue.setObjectName(_fromUtf8("edtMaxGroupValue"))
        self.gridLayout_2.addWidget(self.edtMaxGroupValue, 1, 2, 1, 1)
        self.pnlButtons = QtGui.QWidget(CalculatorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pnlButtons.sizePolicy().hasHeightForWidth())
        self.pnlButtons.setSizePolicy(sizePolicy)
        self.pnlButtons.setObjectName(_fromUtf8("pnlButtons"))
        self.gridLayout = QtGui.QGridLayout(self.pnlButtons)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btnPlus = CControlButton(self.pnlButtons)
        self.btnPlus.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPlus.sizePolicy().hasHeightForWidth())
        self.btnPlus.setSizePolicy(sizePolicy)
        self.btnPlus.setObjectName(_fromUtf8("btnPlus"))
        self.gridLayout.addWidget(self.btnPlus, 1, 3, 2, 1)
        self.btnSix = CControlButton(self.pnlButtons)
        self.btnSix.setEnabled(False)
        self.btnSix.setObjectName(_fromUtf8("btnSix"))
        self.gridLayout.addWidget(self.btnSix, 2, 2, 1, 1)
        self.btnEight = CControlButton(self.pnlButtons)
        self.btnEight.setEnabled(False)
        self.btnEight.setObjectName(_fromUtf8("btnEight"))
        self.gridLayout.addWidget(self.btnEight, 1, 1, 1, 1)
        self.btnSeven = CControlButton(self.pnlButtons)
        self.btnSeven.setEnabled(False)
        self.btnSeven.setObjectName(_fromUtf8("btnSeven"))
        self.gridLayout.addWidget(self.btnSeven, 1, 0, 1, 1)
        self.btnThree = CControlButton(self.pnlButtons)
        self.btnThree.setEnabled(False)
        self.btnThree.setObjectName(_fromUtf8("btnThree"))
        self.gridLayout.addWidget(self.btnThree, 3, 2, 1, 1)
        self.btnTwo = CControlButton(self.pnlButtons)
        self.btnTwo.setEnabled(False)
        self.btnTwo.setObjectName(_fromUtf8("btnTwo"))
        self.gridLayout.addWidget(self.btnTwo, 3, 1, 1, 1)
        self.btnNine = CControlButton(self.pnlButtons)
        self.btnNine.setEnabled(False)
        self.btnNine.setObjectName(_fromUtf8("btnNine"))
        self.gridLayout.addWidget(self.btnNine, 1, 2, 1, 1)
        self.btnFour = CControlButton(self.pnlButtons)
        self.btnFour.setEnabled(False)
        self.btnFour.setObjectName(_fromUtf8("btnFour"))
        self.gridLayout.addWidget(self.btnFour, 2, 0, 1, 1)
        self.btnOne = CControlButton(self.pnlButtons)
        self.btnOne.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOne.sizePolicy().hasHeightForWidth())
        self.btnOne.setSizePolicy(sizePolicy)
        self.btnOne.setObjectName(_fromUtf8("btnOne"))
        self.gridLayout.addWidget(self.btnOne, 3, 0, 1, 1)
        self.btnFive = CControlButton(self.pnlButtons)
        self.btnFive.setEnabled(False)
        self.btnFive.setObjectName(_fromUtf8("btnFive"))
        self.gridLayout.addWidget(self.btnFive, 2, 1, 1, 1)
        self.btnZero = CControlButton(self.pnlButtons)
        self.btnZero.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnZero.sizePolicy().hasHeightForWidth())
        self.btnZero.setSizePolicy(sizePolicy)
        self.btnZero.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnZero.setAutoRaise(False)
        self.btnZero.setArrowType(QtCore.Qt.NoArrow)
        self.btnZero.setObjectName(_fromUtf8("btnZero"))
        self.gridLayout.addWidget(self.btnZero, 4, 0, 1, 2)
        self.btnReset = QtGui.QToolButton(self.pnlButtons)
        self.btnReset.setEnabled(True)
        self.btnReset.setObjectName(_fromUtf8("btnReset"))
        self.gridLayout.addWidget(self.btnReset, 4, 2, 1, 1)
        self.btnDiv = CControlButton(self.pnlButtons)
        self.btnDiv.setEnabled(False)
        self.btnDiv.setObjectName(_fromUtf8("btnDiv"))
        self.gridLayout.addWidget(self.btnDiv, 0, 1, 1, 1)
        self.btnMultiply = CControlButton(self.pnlButtons)
        self.btnMultiply.setEnabled(False)
        self.btnMultiply.setObjectName(_fromUtf8("btnMultiply"))
        self.gridLayout.addWidget(self.btnMultiply, 0, 2, 1, 1)
        self.btnMinus = CControlButton(self.pnlButtons)
        self.btnMinus.setEnabled(False)
        self.btnMinus.setObjectName(_fromUtf8("btnMinus"))
        self.gridLayout.addWidget(self.btnMinus, 0, 3, 1, 1)
        self.btnEnter = QtGui.QToolButton(self.pnlButtons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEnter.sizePolicy().hasHeightForWidth())
        self.btnEnter.setSizePolicy(sizePolicy)
        self.btnEnter.setObjectName(_fromUtf8("btnEnter"))
        self.gridLayout.addWidget(self.btnEnter, 3, 3, 2, 1)
        self.btnCancel = QtGui.QToolButton(self.pnlButtons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCancel.sizePolicy().hasHeightForWidth())
        self.btnCancel.setSizePolicy(sizePolicy)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.gridLayout.addWidget(self.btnCancel, 6, 0, 1, 4)
        self.btnResetAdditional = QtGui.QToolButton(self.pnlButtons)
        self.btnResetAdditional.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResetAdditional.sizePolicy().hasHeightForWidth())
        self.btnResetAdditional.setSizePolicy(sizePolicy)
        self.btnResetAdditional.setObjectName(_fromUtf8("btnResetAdditional"))
        self.gridLayout.addWidget(self.btnResetAdditional, 7, 0, 1, 4)
        self.gridLayout_2.addWidget(self.pnlButtons, 0, 1, 1, 2)
        self.lblRounding = QtGui.QLabel(CalculatorWidget)
        self.lblRounding.setObjectName(_fromUtf8("lblRounding"))
        self.gridLayout_2.addWidget(self.lblRounding, 2, 1, 1, 1)
        self.edtRounding = QtGui.QSpinBox(CalculatorWidget)
        self.edtRounding.setMaximum(9)
        self.edtRounding.setObjectName(_fromUtf8("edtRounding"))
        self.gridLayout_2.addWidget(self.edtRounding, 2, 2, 1, 1)

        self.retranslateUi(CalculatorWidget)
        QtCore.QMetaObject.connectSlotsByName(CalculatorWidget)
        CalculatorWidget.setTabOrder(self.tableView, self.btnDiv)
        CalculatorWidget.setTabOrder(self.btnDiv, self.btnMultiply)
        CalculatorWidget.setTabOrder(self.btnMultiply, self.btnMinus)
        CalculatorWidget.setTabOrder(self.btnMinus, self.btnSeven)
        CalculatorWidget.setTabOrder(self.btnSeven, self.btnEight)
        CalculatorWidget.setTabOrder(self.btnEight, self.btnNine)
        CalculatorWidget.setTabOrder(self.btnNine, self.btnPlus)
        CalculatorWidget.setTabOrder(self.btnPlus, self.btnFour)
        CalculatorWidget.setTabOrder(self.btnFour, self.btnFive)
        CalculatorWidget.setTabOrder(self.btnFive, self.btnSix)
        CalculatorWidget.setTabOrder(self.btnSix, self.btnOne)
        CalculatorWidget.setTabOrder(self.btnOne, self.btnTwo)
        CalculatorWidget.setTabOrder(self.btnTwo, self.btnThree)
        CalculatorWidget.setTabOrder(self.btnThree, self.btnEnter)
        CalculatorWidget.setTabOrder(self.btnEnter, self.btnZero)
        CalculatorWidget.setTabOrder(self.btnZero, self.btnReset)
        CalculatorWidget.setTabOrder(self.btnReset, self.btnCancel)
        CalculatorWidget.setTabOrder(self.btnCancel, self.edtMaxGroupValue)

    def retranslateUi(self, CalculatorWidget):
        CalculatorWidget.setWindowTitle(QtGui.QApplication.translate("CalculatorWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMaxGroupValue.setText(QtGui.QApplication.translate("CalculatorWidget", "Групповой предел: ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPlus.setText(QtGui.QApplication.translate("CalculatorWidget", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPlus.setShortcut(QtGui.QApplication.translate("CalculatorWidget", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSix.setText(QtGui.QApplication.translate("CalculatorWidget", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSix.setShortcut(QtGui.QApplication.translate("CalculatorWidget", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEight.setText(QtGui.QApplication.translate("CalculatorWidget", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEight.setShortcut(QtGui.QApplication.translate("CalculatorWidget", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSeven.setText(QtGui.QApplication.translate("CalculatorWidget", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSeven.setShortcut(QtGui.QApplication.translate("CalculatorWidget", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.btnThree.setText(QtGui.QApplication.translate("CalculatorWidget", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.btnThree.setShortcut(QtGui.QApplication.translate("CalculatorWidget", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTwo.setText(QtGui.QApplication.translate("CalculatorWidget", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTwo.setShortcut(QtGui.QApplication.translate("CalculatorWidget", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNine.setText(QtGui.QApplication.translate("CalculatorWidget", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNine.setShortcut(QtGui.QApplication.translate("CalculatorWidget", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFour.setText(QtGui.QApplication.translate("CalculatorWidget", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFour.setShortcut(QtGui.QApplication.translate("CalculatorWidget", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOne.setText(QtGui.QApplication.translate("CalculatorWidget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOne.setShortcut(QtGui.QApplication.translate("CalculatorWidget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFive.setText(QtGui.QApplication.translate("CalculatorWidget", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFive.setShortcut(QtGui.QApplication.translate("CalculatorWidget", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.btnZero.setText(QtGui.QApplication.translate("CalculatorWidget", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.btnZero.setShortcut(QtGui.QApplication.translate("CalculatorWidget", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReset.setText(QtGui.QApplication.translate("CalculatorWidget", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReset.setShortcut(QtGui.QApplication.translate("CalculatorWidget", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDiv.setText(QtGui.QApplication.translate("CalculatorWidget", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDiv.setShortcut(QtGui.QApplication.translate("CalculatorWidget", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMultiply.setText(QtGui.QApplication.translate("CalculatorWidget", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMultiply.setShortcut(QtGui.QApplication.translate("CalculatorWidget", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMinus.setText(QtGui.QApplication.translate("CalculatorWidget", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMinus.setShortcut(QtGui.QApplication.translate("CalculatorWidget", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEnter.setText(QtGui.QApplication.translate("CalculatorWidget", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEnter.setShortcut(QtGui.QApplication.translate("CalculatorWidget", "Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setText(QtGui.QApplication.translate("CalculatorWidget", "Отменить", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setShortcut(QtGui.QApplication.translate("CalculatorWidget", "Backspace", None, QtGui.QApplication.UnicodeUTF8))
        self.btnResetAdditional.setText(QtGui.QApplication.translate("CalculatorWidget", "Отменить назначения", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRounding.setText(QtGui.QApplication.translate("CalculatorWidget", "Округление", None, QtGui.QApplication.UnicodeUTF8))

from TissueJournal.LaboratoryCalculator.LaboratoryCalculatorTable import CLaboratoryCalculatorTableView
from TissueJournal.LaboratoryCalculator.Utils import CControlButton, CMaxGroupValueSpinBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    CalculatorWidget = QtGui.QWidget()
    ui = Ui_CalculatorWidget()
    ui.setupUi(CalculatorWidget)
    CalculatorWidget.show()
    sys.exit(app.exec_())

