# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AttachedClients.ui'
#
# Created: Tue Aug 25 12:57:23 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AttachedClientsDialog(object):
    def setupUi(self, AttachedClientsDialog):
        AttachedClientsDialog.setObjectName(_fromUtf8("AttachedClientsDialog"))
        AttachedClientsDialog.setWindowModality(QtCore.Qt.NonModal)
        AttachedClientsDialog.resize(919, 562)
        AttachedClientsDialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        AttachedClientsDialog.setAcceptDrops(False)
        AttachedClientsDialog.setToolTip(_fromUtf8(""))
        AttachedClientsDialog.setAutoFillBackground(True)
        self.gridLayout_2 = QtGui.QGridLayout(AttachedClientsDialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblResult = QtGui.QTableView(AttachedClientsDialog)
        self.tblResult.setSortingEnabled(True)
        self.tblResult.setObjectName(_fromUtf8("tblResult"))
        self.gridLayout_2.addWidget(self.tblResult, 1, 0, 1, 1)
        self.gbInit = QtGui.QGroupBox(AttachedClientsDialog)
        self.gbInit.setObjectName(_fromUtf8("gbInit"))
        self.gridLayout = QtGui.QGridLayout(self.gbInit)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblReportDate = QtGui.QLabel(self.gbInit)
        self.lblReportDate.setObjectName(_fromUtf8("lblReportDate"))
        self.gridLayout.addWidget(self.lblReportDate, 1, 0, 1, 1)
        self.lblCodeSMO = QtGui.QLabel(self.gbInit)
        self.lblCodeSMO.setEnabled(False)
        self.lblCodeSMO.setObjectName(_fromUtf8("lblCodeSMO"))
        self.gridLayout.addWidget(self.lblCodeSMO, 4, 1, 1, 1)
        self.gbExportType = QtGui.QGroupBox(self.gbInit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbExportType.sizePolicy().hasHeightForWidth())
        self.gbExportType.setSizePolicy(sizePolicy)
        self.gbExportType.setObjectName(_fromUtf8("gbExportType"))
        self.verticalLayout = QtGui.QVBoxLayout(self.gbExportType)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.rbMIAC = QtGui.QRadioButton(self.gbExportType)
        self.rbMIAC.setChecked(True)
        self.rbMIAC.setObjectName(_fromUtf8("rbMIAC"))
        self.verticalLayout.addWidget(self.rbMIAC)
        self.rbSMO = QtGui.QRadioButton(self.gbExportType)
        self.rbSMO.setObjectName(_fromUtf8("rbSMO"))
        self.verticalLayout.addWidget(self.rbSMO)
        self.gridLayout.addWidget(self.gbExportType, 4, 0, 3, 1)
        self.groupBox = QtGui.QGroupBox(self.gbInit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.rbRegAndLoc = QtGui.QRadioButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbRegAndLoc.sizePolicy().hasHeightForWidth())
        self.rbRegAndLoc.setSizePolicy(sizePolicy)
        self.rbRegAndLoc.setChecked(True)
        self.rbRegAndLoc.setObjectName(_fromUtf8("rbRegAndLoc"))
        self.verticalLayout_2.addWidget(self.rbRegAndLoc)
        self.rbOnlyReg = QtGui.QRadioButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbOnlyReg.sizePolicy().hasHeightForWidth())
        self.rbOnlyReg.setSizePolicy(sizePolicy)
        self.rbOnlyReg.setObjectName(_fromUtf8("rbOnlyReg"))
        self.verticalLayout_2.addWidget(self.rbOnlyReg)
        self.rbOnlyLoc = QtGui.QRadioButton(self.groupBox)
        self.rbOnlyLoc.setObjectName(_fromUtf8("rbOnlyLoc"))
        self.verticalLayout_2.addWidget(self.rbOnlyLoc)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 2)
        self.edtReportDate = CDateEdit(self.gbInit)
        self.edtReportDate.setCalendarPopup(True)
        self.edtReportDate.setObjectName(_fromUtf8("edtReportDate"))
        self.gridLayout.addWidget(self.edtReportDate, 1, 1, 1, 2)
        self.cmbSMO = QtGui.QComboBox(self.gbInit)
        self.cmbSMO.setEnabled(False)
        self.cmbSMO.setObjectName(_fromUtf8("cmbSMO"))
        self.gridLayout.addWidget(self.cmbSMO, 4, 2, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(self.gbInit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblOrgStructure.setSizePolicy(sizePolicy)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 2, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(self.gbInit)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 0, 1, 1, 2)
        self.chkCorrectRecords = QtGui.QCheckBox(self.gbInit)
        self.chkCorrectRecords.setEnabled(False)
        self.chkCorrectRecords.setObjectName(_fromUtf8("chkCorrectRecords"))
        self.gridLayout.addWidget(self.chkCorrectRecords, 5, 1, 1, 2)
        self.chkExternalArea = QtGui.QCheckBox(self.gbInit)
        self.chkExternalArea.setObjectName(_fromUtf8("chkExternalArea"))
        self.gridLayout.addWidget(self.chkExternalArea, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gbInit, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnRetrieve = QtGui.QPushButton(AttachedClientsDialog)
        self.btnRetrieve.setObjectName(_fromUtf8("btnRetrieve"))
        self.horizontalLayout.addWidget(self.btnRetrieve)
        self.btnSave = QtGui.QPushButton(AttachedClientsDialog)
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.horizontalLayout.addWidget(self.btnSave)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btnClose = QtGui.QPushButton(AttachedClientsDialog)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.horizontalLayout.addWidget(self.btnClose)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.retranslateUi(AttachedClientsDialog)
        QtCore.QObject.connect(self.rbSMO, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblCodeSMO.setEnabled)
        QtCore.QObject.connect(self.rbSMO, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbSMO.setEnabled)
        QtCore.QObject.connect(self.rbSMO, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkCorrectRecords.setEnabled)
        QtCore.QObject.connect(self.rbSMO, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkExternalArea.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(AttachedClientsDialog)

    def retranslateUi(self, AttachedClientsDialog):
        AttachedClientsDialog.setWindowTitle(_translate("AttachedClientsDialog", "Экспорт приписанного населения", None))
        self.gbInit.setTitle(_translate("AttachedClientsDialog", "Параметры экспорта", None))
        self.lblReportDate.setText(_translate("AttachedClientsDialog", "Дата", None))
        self.lblCodeSMO.setText(_translate("AttachedClientsDialog", "Код СМО", None))
        self.gbExportType.setTitle(_translate("AttachedClientsDialog", "Тип экспорта", None))
        self.rbMIAC.setText(_translate("AttachedClientsDialog", "Экспорт в МИАЦ", None))
        self.rbSMO.setText(_translate("AttachedClientsDialog", "Экспорт в СМО", None))
        self.groupBox.setTitle(_translate("AttachedClientsDialog", "Заполнять адрес при экспорте", None))
        self.rbRegAndLoc.setText(_translate("AttachedClientsDialog", "по типу прикрепления", None))
        self.rbOnlyReg.setText(_translate("AttachedClientsDialog", "только по регистрации", None))
        self.rbOnlyLoc.setText(_translate("AttachedClientsDialog", "только по проживанию", None))
        self.lblOrgStructure.setText(_translate("AttachedClientsDialog", "Подразделение", None))
        self.chkCorrectRecords.setText(_translate("AttachedClientsDialog", "только подтвержденные в МИАЦ/ТФОМС", None))
        self.chkExternalArea.setText(_translate("AttachedClientsDialog", "Инокраевые пациенты", None))
        self.btnRetrieve.setText(_translate("AttachedClientsDialog", "Создать отчёт", None))
        self.btnSave.setText(_translate("AttachedClientsDialog", "Сохранить", None))
        self.btnClose.setText(_translate("AttachedClientsDialog", "Закрыть", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.DateEdit import CDateEdit
