# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TemplateEdit.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TemplateEdit(object):
    def setupUi(self, TemplateEdit):
        TemplateEdit.setObjectName(_fromUtf8("TemplateEdit"))
        TemplateEdit.resize(794, 204)
        self.gridLayout = QtGui.QGridLayout(TemplateEdit)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line = QtGui.QFrame(TemplateEdit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 9, 4, 1)
        self.edtAmbTimeRange12 = CTimeRangeEdit(TemplateEdit)
        self.edtAmbTimeRange12.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbTimeRange12.sizePolicy().hasHeightForWidth())
        self.edtAmbTimeRange12.setSizePolicy(sizePolicy)
        self.edtAmbTimeRange12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.edtAmbTimeRange12.setMaxLength(13)
        self.edtAmbTimeRange12.setObjectName(_fromUtf8("edtAmbTimeRange12"))
        self.gridLayout.addWidget(self.edtAmbTimeRange12, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 52, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.edtAmbOffice1 = QtGui.QLineEdit(TemplateEdit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbOffice1.sizePolicy().hasHeightForWidth())
        self.edtAmbOffice1.setSizePolicy(sizePolicy)
        self.edtAmbOffice1.setMaxLength(8)
        self.edtAmbOffice1.setObjectName(_fromUtf8("edtAmbOffice1"))
        self.gridLayout.addWidget(self.edtAmbOffice1, 2, 1, 1, 1)
        self.lblHomeHours = QtGui.QLabel(TemplateEdit)
        self.lblHomeHours.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHomeHours.setObjectName(_fromUtf8("lblHomeHours"))
        self.gridLayout.addWidget(self.lblHomeHours, 1, 10, 1, 1)
        self.edtHomeTimeRange1 = CTimeRangeEdit(TemplateEdit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHomeTimeRange1.sizePolicy().hasHeightForWidth())
        self.edtHomeTimeRange1.setSizePolicy(sizePolicy)
        self.edtHomeTimeRange1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.edtHomeTimeRange1.setMaxLength(13)
        self.edtHomeTimeRange1.setObjectName(_fromUtf8("edtHomeTimeRange1"))
        self.gridLayout.addWidget(self.edtHomeTimeRange1, 2, 10, 1, 1)
        self.lblAmbHours = QtGui.QLabel(TemplateEdit)
        self.lblAmbHours.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAmbHours.setObjectName(_fromUtf8("lblAmbHours"))
        self.gridLayout.addWidget(self.lblAmbHours, 1, 0, 1, 1)
        self.edtAmbTimeRange1 = CTimeRangeEdit(TemplateEdit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbTimeRange1.sizePolicy().hasHeightForWidth())
        self.edtAmbTimeRange1.setSizePolicy(sizePolicy)
        self.edtAmbTimeRange1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.edtAmbTimeRange1.setMaxLength(13)
        self.edtAmbTimeRange1.setObjectName(_fromUtf8("edtAmbTimeRange1"))
        self.gridLayout.addWidget(self.edtAmbTimeRange1, 2, 0, 1, 1)
        self.lblHomePlan = QtGui.QLabel(TemplateEdit)
        self.lblHomePlan.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHomePlan.setObjectName(_fromUtf8("lblHomePlan"))
        self.gridLayout.addWidget(self.lblHomePlan, 1, 11, 1, 1)
        self.edtHomePlan12 = QtGui.QSpinBox(TemplateEdit)
        self.edtHomePlan12.setEnabled(True)
        self.edtHomePlan12.setMaximum(9999)
        self.edtHomePlan12.setObjectName(_fromUtf8("edtHomePlan12"))
        self.gridLayout.addWidget(self.edtHomePlan12, 3, 11, 1, 1)
        self.edtAmbPlan1 = QtGui.QSpinBox(TemplateEdit)
        self.edtAmbPlan1.setMaximum(9999)
        self.edtAmbPlan1.setObjectName(_fromUtf8("edtAmbPlan1"))
        self.gridLayout.addWidget(self.edtAmbPlan1, 2, 2, 1, 1)
        self.lblAmbCab = QtGui.QLabel(TemplateEdit)
        self.lblAmbCab.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAmbCab.setObjectName(_fromUtf8("lblAmbCab"))
        self.gridLayout.addWidget(self.lblAmbCab, 1, 1, 1, 1)
        self.edtAmbInterPlan1 = QtGui.QSpinBox(TemplateEdit)
        self.edtAmbInterPlan1.setEnabled(True)
        self.edtAmbInterPlan1.setMaximum(9999)
        self.edtAmbInterPlan1.setObjectName(_fromUtf8("edtAmbInterPlan1"))
        self.gridLayout.addWidget(self.edtAmbInterPlan1, 4, 2, 1, 1)
        self.edtAmbOfficeInter = QtGui.QLineEdit(TemplateEdit)
        self.edtAmbOfficeInter.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbOfficeInter.sizePolicy().hasHeightForWidth())
        self.edtAmbOfficeInter.setSizePolicy(sizePolicy)
        self.edtAmbOfficeInter.setMaxLength(8)
        self.edtAmbOfficeInter.setObjectName(_fromUtf8("edtAmbOfficeInter"))
        self.gridLayout.addWidget(self.edtAmbOfficeInter, 4, 1, 1, 1)
        self.label = QtGui.QLabel(TemplateEdit)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.edtHomeTimeRange12 = CTimeRangeEdit(TemplateEdit)
        self.edtHomeTimeRange12.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHomeTimeRange12.sizePolicy().hasHeightForWidth())
        self.edtHomeTimeRange12.setSizePolicy(sizePolicy)
        self.edtHomeTimeRange12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.edtHomeTimeRange12.setMaxLength(13)
        self.edtHomeTimeRange12.setObjectName(_fromUtf8("edtHomeTimeRange12"))
        self.gridLayout.addWidget(self.edtHomeTimeRange12, 3, 10, 1, 1)
        self.lblHome = QtGui.QLabel(TemplateEdit)
        self.lblHome.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHome.setObjectName(_fromUtf8("lblHome"))
        self.gridLayout.addWidget(self.lblHome, 0, 10, 1, 1)
        self.lblAmb = QtGui.QLabel(TemplateEdit)
        self.lblAmb.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAmb.setObjectName(_fromUtf8("lblAmb"))
        self.gridLayout.addWidget(self.lblAmb, 0, 0, 1, 2)
        self.lblAmbPlan = QtGui.QLabel(TemplateEdit)
        self.lblAmbPlan.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAmbPlan.setObjectName(_fromUtf8("lblAmbPlan"))
        self.gridLayout.addWidget(self.lblAmbPlan, 1, 2, 1, 1)
        self.edtHomePlan1 = QtGui.QSpinBox(TemplateEdit)
        self.edtHomePlan1.setMaximum(9999)
        self.edtHomePlan1.setObjectName(_fromUtf8("edtHomePlan1"))
        self.gridLayout.addWidget(self.edtHomePlan1, 2, 11, 1, 1)
        self.edtAmbPlan12 = QtGui.QSpinBox(TemplateEdit)
        self.edtAmbPlan12.setEnabled(True)
        self.edtAmbPlan12.setMaximum(9999)
        self.edtAmbPlan12.setObjectName(_fromUtf8("edtAmbPlan12"))
        self.gridLayout.addWidget(self.edtAmbPlan12, 3, 2, 1, 1)
        self.edtAmbOffice12 = QtGui.QLineEdit(TemplateEdit)
        self.edtAmbOffice12.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbOffice12.sizePolicy().hasHeightForWidth())
        self.edtAmbOffice12.setSizePolicy(sizePolicy)
        self.edtAmbOffice12.setMaxLength(8)
        self.edtAmbOffice12.setObjectName(_fromUtf8("edtAmbOffice12"))
        self.gridLayout.addWidget(self.edtAmbOffice12, 3, 1, 1, 1)
        self.btnAmbColor1 = CColorPicker(TemplateEdit)
        self.btnAmbColor1.setText(_fromUtf8(""))
        self.btnAmbColor1.setObjectName(_fromUtf8("btnAmbColor1"))
        self.gridLayout.addWidget(self.btnAmbColor1, 2, 4, 1, 4)
        self.btnAmbColor2 = CColorPicker(TemplateEdit)
        self.btnAmbColor2.setText(_fromUtf8(""))
        self.btnAmbColor2.setObjectName(_fromUtf8("btnAmbColor2"))
        self.gridLayout.addWidget(self.btnAmbColor2, 3, 4, 1, 4)
        self.btnAmbColorInter = CColorPicker(TemplateEdit)
        self.btnAmbColorInter.setEnabled(True)
        self.btnAmbColorInter.setText(_fromUtf8(""))
        self.btnAmbColorInter.setObjectName(_fromUtf8("btnAmbColorInter"))
        self.gridLayout.addWidget(self.btnAmbColorInter, 4, 4, 1, 4)
        self.lblAmbInterval = QtGui.QLabel(TemplateEdit)
        self.lblAmbInterval.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAmbInterval.setObjectName(_fromUtf8("lblAmbInterval"))
        self.gridLayout.addWidget(self.lblAmbInterval, 1, 3, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.edtAmbInterval1 = QtGui.QSpinBox(TemplateEdit)
        self.edtAmbInterval1.setMinimum(0)
        self.edtAmbInterval1.setMaximum(9999)
        self.edtAmbInterval1.setProperty("value", 0)
        self.edtAmbInterval1.setObjectName(_fromUtf8("edtAmbInterval1"))
        self.horizontalLayout_3.addWidget(self.edtAmbInterval1)
        self.lblAmbInterval1 = QtGui.QLabel(TemplateEdit)
        self.lblAmbInterval1.setObjectName(_fromUtf8("lblAmbInterval1"))
        self.horizontalLayout_3.addWidget(self.lblAmbInterval1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 3, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtAmbInterval12 = QtGui.QSpinBox(TemplateEdit)
        self.edtAmbInterval12.setEnabled(True)
        self.edtAmbInterval12.setMinimum(0)
        self.edtAmbInterval12.setMaximum(9999)
        self.edtAmbInterval12.setProperty("value", 0)
        self.edtAmbInterval12.setObjectName(_fromUtf8("edtAmbInterval12"))
        self.horizontalLayout.addWidget(self.edtAmbInterval12)
        self.lblAmbInterval2 = QtGui.QLabel(TemplateEdit)
        self.lblAmbInterval2.setEnabled(True)
        self.lblAmbInterval2.setObjectName(_fromUtf8("lblAmbInterval2"))
        self.horizontalLayout.addWidget(self.lblAmbInterval2)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 3, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.edtAmbInterInterval1 = QtGui.QSpinBox(TemplateEdit)
        self.edtAmbInterInterval1.setEnabled(True)
        self.edtAmbInterInterval1.setMinimum(0)
        self.edtAmbInterInterval1.setMaximum(9999)
        self.edtAmbInterInterval1.setObjectName(_fromUtf8("edtAmbInterInterval1"))
        self.horizontalLayout_2.addWidget(self.edtAmbInterInterval1)
        self.lblAmbInterInterval1 = QtGui.QLabel(TemplateEdit)
        self.lblAmbInterInterval1.setEnabled(True)
        self.lblAmbInterInterval1.setObjectName(_fromUtf8("lblAmbInterInterval1"))
        self.horizontalLayout_2.addWidget(self.lblAmbInterInterval1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 3, 1, 1)
        self.label_2 = QtGui.QLabel(TemplateEdit)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 12, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.edtHomeInterval12 = QtGui.QSpinBox(TemplateEdit)
        self.edtHomeInterval12.setMaximum(9999)
        self.edtHomeInterval12.setObjectName(_fromUtf8("edtHomeInterval12"))
        self.horizontalLayout_4.addWidget(self.edtHomeInterval12)
        self.lblHomeInterval12 = QtGui.QLabel(TemplateEdit)
        self.lblHomeInterval12.setObjectName(_fromUtf8("lblHomeInterval12"))
        self.horizontalLayout_4.addWidget(self.lblHomeInterval12)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 12, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.edtHomeInterval1 = QtGui.QSpinBox(TemplateEdit)
        self.edtHomeInterval1.setMaximum(9999)
        self.edtHomeInterval1.setObjectName(_fromUtf8("edtHomeInterval1"))
        self.horizontalLayout_5.addWidget(self.edtHomeInterval1)
        self.lblHomeInterval1 = QtGui.QLabel(TemplateEdit)
        self.lblHomeInterval1.setObjectName(_fromUtf8("lblHomeInterval1"))
        self.horizontalLayout_5.addWidget(self.lblHomeInterval1)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 12, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(TemplateEdit)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 7, 11, 1, 2)
        self.chkNotExternalSystem1 = QtGui.QCheckBox(TemplateEdit)
        self.chkNotExternalSystem1.setText(_fromUtf8(""))
        self.chkNotExternalSystem1.setObjectName(_fromUtf8("chkNotExternalSystem1"))
        self.gridLayout.addWidget(self.chkNotExternalSystem1, 2, 8, 1, 1)
        self.chkNotExternalSystem12 = QtGui.QCheckBox(TemplateEdit)
        self.chkNotExternalSystem12.setText(_fromUtf8(""))
        self.chkNotExternalSystem12.setObjectName(_fromUtf8("chkNotExternalSystem12"))
        self.gridLayout.addWidget(self.chkNotExternalSystem12, 3, 8, 1, 1)
        self.lblNotExternalSystem = QtGui.QLabel(TemplateEdit)
        self.lblNotExternalSystem.setObjectName(_fromUtf8("lblNotExternalSystem"))
        self.gridLayout.addWidget(self.lblNotExternalSystem, 1, 8, 1, 1)
        self.chkInterNotExternalSystem1 = QtGui.QCheckBox(TemplateEdit)
        self.chkInterNotExternalSystem1.setText(_fromUtf8(""))
        self.chkInterNotExternalSystem1.setObjectName(_fromUtf8("chkInterNotExternalSystem1"))
        self.gridLayout.addWidget(self.chkInterNotExternalSystem1, 4, 8, 1, 1)
        self.lblHomeHours.setBuddy(self.edtHomeTimeRange1)
        self.lblAmbHours.setBuddy(self.edtAmbTimeRange1)
        self.lblHomePlan.setBuddy(self.edtHomePlan1)
        self.lblAmbCab.setBuddy(self.edtAmbOffice1)
        self.lblAmbPlan.setBuddy(self.edtAmbPlan1)

        self.retranslateUi(TemplateEdit)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TemplateEdit.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TemplateEdit.reject)
        QtCore.QMetaObject.connectSlotsByName(TemplateEdit)
        TemplateEdit.setTabOrder(self.edtAmbTimeRange1, self.edtAmbOffice1)
        TemplateEdit.setTabOrder(self.edtAmbOffice1, self.edtAmbPlan1)
        TemplateEdit.setTabOrder(self.edtAmbPlan1, self.edtAmbInterval1)
        TemplateEdit.setTabOrder(self.edtAmbInterval1, self.btnAmbColor1)
        TemplateEdit.setTabOrder(self.btnAmbColor1, self.chkNotExternalSystem1)
        TemplateEdit.setTabOrder(self.chkNotExternalSystem1, self.edtHomeTimeRange1)
        TemplateEdit.setTabOrder(self.edtHomeTimeRange1, self.edtHomePlan1)
        TemplateEdit.setTabOrder(self.edtHomePlan1, self.edtHomeInterval1)
        TemplateEdit.setTabOrder(self.edtHomeInterval1, self.edtAmbTimeRange12)
        TemplateEdit.setTabOrder(self.edtAmbTimeRange12, self.edtAmbOffice12)
        TemplateEdit.setTabOrder(self.edtAmbOffice12, self.edtAmbPlan12)
        TemplateEdit.setTabOrder(self.edtAmbPlan12, self.edtAmbInterval12)
        TemplateEdit.setTabOrder(self.edtAmbInterval12, self.btnAmbColor2)
        TemplateEdit.setTabOrder(self.btnAmbColor2, self.chkNotExternalSystem12)
        TemplateEdit.setTabOrder(self.chkNotExternalSystem12, self.edtHomeTimeRange12)
        TemplateEdit.setTabOrder(self.edtHomeTimeRange12, self.edtHomePlan12)
        TemplateEdit.setTabOrder(self.edtHomePlan12, self.edtHomeInterval12)
        TemplateEdit.setTabOrder(self.edtHomeInterval12, self.edtAmbOfficeInter)
        TemplateEdit.setTabOrder(self.edtAmbOfficeInter, self.edtAmbInterPlan1)
        TemplateEdit.setTabOrder(self.edtAmbInterPlan1, self.edtAmbInterInterval1)
        TemplateEdit.setTabOrder(self.edtAmbInterInterval1, self.btnAmbColorInter)
        TemplateEdit.setTabOrder(self.btnAmbColorInter, self.chkInterNotExternalSystem1)
        TemplateEdit.setTabOrder(self.chkInterNotExternalSystem1, self.buttonBox)

    def retranslateUi(self, TemplateEdit):
        TemplateEdit.setWindowTitle(_translate("TemplateEdit", "Редактор периодов", None))
        self.lblHomeHours.setText(_translate("TemplateEdit", "Часы", None))
        self.lblAmbHours.setText(_translate("TemplateEdit", "Часы", None))
        self.lblHomePlan.setText(_translate("TemplateEdit", "План", None))
        self.lblAmbCab.setText(_translate("TemplateEdit", "Кабинет", None))
        self.label.setText(_translate("TemplateEdit", "Вне очереди:", None))
        self.lblHome.setText(_translate("TemplateEdit", "Вызовы на дом", None))
        self.lblAmb.setText(_translate("TemplateEdit", "Амбулаторный приём", None))
        self.lblAmbPlan.setText(_translate("TemplateEdit", "План", None))
        self.lblAmbInterval.setText(_translate("TemplateEdit", "Интервал", None))
        self.lblAmbInterval1.setText(_translate("TemplateEdit", "мин.", None))
        self.lblAmbInterval2.setText(_translate("TemplateEdit", "мин.", None))
        self.lblAmbInterInterval1.setText(_translate("TemplateEdit", "мин.", None))
        self.label_2.setText(_translate("TemplateEdit", "Интервал", None))
        self.lblHomeInterval12.setText(_translate("TemplateEdit", "мин.", None))
        self.lblHomeInterval1.setText(_translate("TemplateEdit", "мин.", None))
        self.chkNotExternalSystem1.setToolTip(_translate("TemplateEdit", "<html><head/><body><p>Данный период недоступен для использования через внешние системы</p></body></html>", None))
        self.chkNotExternalSystem12.setToolTip(_translate("TemplateEdit", "<html><head/><body><p>Данный период недоступен для использования через внешние системы</p></body></html>", None))
        self.lblNotExternalSystem.setToolTip(_translate("TemplateEdit", "<html><head/><body><p>Данный период недоступен для использования через внешние системы</p></body></html>", None))
        self.lblNotExternalSystem.setText(_translate("TemplateEdit", "ВС", None))

from library.CColorPicker import CColorPicker
from library.TimeEdit import CTimeRangeEdit
