# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Timeline\TimelineDialog.ui'
#
# Created: Wed May 29 14:08:21 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TimelineDialog(object):
    def setupUi(self, TimelineDialog):
        TimelineDialog.setObjectName(_fromUtf8("TimelineDialog"))
        TimelineDialog.resize(999, 402)
        self.gridlayout = QtGui.QGridLayout(TimelineDialog)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.splitter_2 = QtGui.QSplitter(TimelineDialog)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.calendar = CCalendarWidget(self.splitter)
        self.calendar.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendar.setGridVisible(False)
        self.calendar.setObjectName(_fromUtf8("calendar"))
        self.treeOrgStructure = QtGui.QTreeView(self.splitter)
        self.treeOrgStructure.setObjectName(_fromUtf8("treeOrgStructure"))
        self.tblPersonnel = CTableView(self.splitter)
        self.tblPersonnel.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblPersonnel.setObjectName(_fromUtf8("tblPersonnel"))
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.vboxlayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.vboxlayout.setContentsMargins(0, -1, -1, -1)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.tblTimeTable = CTimeTable(self.layoutWidget)
        self.tblTimeTable.setObjectName(_fromUtf8("tblTimeTable"))
        self.vboxlayout.addWidget(self.tblTimeTable)
        self.frame = QtGui.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridlayout1 = QtGui.QGridLayout(self.frame)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.lblNumDays = QtGui.QLabel(self.frame)
        self.lblNumDays.setObjectName(_fromUtf8("lblNumDays"))
        self.gridlayout1.addWidget(self.lblNumDays, 0, 0, 1, 1)
        self.lblShowNumDays = QtGui.QLabel(self.frame)
        self.lblShowNumDays.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowNumDays.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowNumDays.setObjectName(_fromUtf8("lblShowNumDays"))
        self.gridlayout1.addWidget(self.lblShowNumDays, 0, 1, 1, 1)
        self.lblHourLoad = QtGui.QLabel(self.frame)
        self.lblHourLoad.setObjectName(_fromUtf8("lblHourLoad"))
        self.gridlayout1.addWidget(self.lblHourLoad, 0, 2, 1, 1)
        self.lblShowHourLoad = QtGui.QLabel(self.frame)
        self.lblShowHourLoad.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowHourLoad.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowHourLoad.setObjectName(_fromUtf8("lblShowHourLoad"))
        self.gridlayout1.addWidget(self.lblShowHourLoad, 0, 3, 1, 1)
        self.lblLoad = QtGui.QLabel(self.frame)
        self.lblLoad.setObjectName(_fromUtf8("lblLoad"))
        self.gridlayout1.addWidget(self.lblLoad, 0, 4, 1, 1)
        self.lblShowLoad = QtGui.QLabel(self.frame)
        self.lblShowLoad.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowLoad.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowLoad.setObjectName(_fromUtf8("lblShowLoad"))
        self.gridlayout1.addWidget(self.lblShowLoad, 0, 5, 1, 1)
        self.lblExec = QtGui.QLabel(self.frame)
        self.lblExec.setObjectName(_fromUtf8("lblExec"))
        self.gridlayout1.addWidget(self.lblExec, 0, 6, 1, 1)
        self.lblShowExec = QtGui.QLabel(self.frame)
        self.lblShowExec.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowExec.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowExec.setObjectName(_fromUtf8("lblShowExec"))
        self.gridlayout1.addWidget(self.lblShowExec, 0, 7, 1, 1)
        spacerItem = QtGui.QSpacerItem(41, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem, 0, 8, 1, 1)
        self.lblAbsenceDays = QtGui.QLabel(self.frame)
        self.lblAbsenceDays.setObjectName(_fromUtf8("lblAbsenceDays"))
        self.gridlayout1.addWidget(self.lblAbsenceDays, 1, 0, 1, 1)
        self.lblShowAbsenceDays = QtGui.QLabel(self.frame)
        self.lblShowAbsenceDays.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowAbsenceDays.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowAbsenceDays.setObjectName(_fromUtf8("lblShowAbsenceDays"))
        self.gridlayout1.addWidget(self.lblShowAbsenceDays, 1, 1, 1, 1)
        self.lblServHourLoad = QtGui.QLabel(self.frame)
        self.lblServHourLoad.setObjectName(_fromUtf8("lblServHourLoad"))
        self.gridlayout1.addWidget(self.lblServHourLoad, 1, 2, 1, 1)
        self.lblShowServHourLoad = QtGui.QLabel(self.frame)
        self.lblShowServHourLoad.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowServHourLoad.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowServHourLoad.setObjectName(_fromUtf8("lblShowServHourLoad"))
        self.gridlayout1.addWidget(self.lblShowServHourLoad, 1, 3, 1, 1)
        self.lblServLoad = QtGui.QLabel(self.frame)
        self.lblServLoad.setObjectName(_fromUtf8("lblServLoad"))
        self.gridlayout1.addWidget(self.lblServLoad, 1, 4, 1, 1)
        self.lblShowServLoad = QtGui.QLabel(self.frame)
        self.lblShowServLoad.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowServLoad.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowServLoad.setObjectName(_fromUtf8("lblShowServLoad"))
        self.gridlayout1.addWidget(self.lblShowServLoad, 1, 5, 1, 1)
        self.lblServExec = QtGui.QLabel(self.frame)
        self.lblServExec.setObjectName(_fromUtf8("lblServExec"))
        self.gridlayout1.addWidget(self.lblServExec, 1, 6, 1, 1)
        self.lblShowServExec = QtGui.QLabel(self.frame)
        self.lblShowServExec.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowServExec.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowServExec.setObjectName(_fromUtf8("lblShowServExec"))
        self.gridlayout1.addWidget(self.lblShowServExec, 1, 7, 1, 1)
        self.lblAmbDays = QtGui.QLabel(self.frame)
        self.lblAmbDays.setObjectName(_fromUtf8("lblAmbDays"))
        self.gridlayout1.addWidget(self.lblAmbDays, 2, 0, 1, 1)
        self.lblShowAmbDays = QtGui.QLabel(self.frame)
        self.lblShowAmbDays.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowAmbDays.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowAmbDays.setObjectName(_fromUtf8("lblShowAmbDays"))
        self.gridlayout1.addWidget(self.lblShowAmbDays, 2, 1, 1, 1)
        self.lblAmbHourLoad = QtGui.QLabel(self.frame)
        self.lblAmbHourLoad.setObjectName(_fromUtf8("lblAmbHourLoad"))
        self.gridlayout1.addWidget(self.lblAmbHourLoad, 2, 2, 1, 1)
        self.lblShowAmbHourLoad = QtGui.QLabel(self.frame)
        self.lblShowAmbHourLoad.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowAmbHourLoad.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowAmbHourLoad.setObjectName(_fromUtf8("lblShowAmbHourLoad"))
        self.gridlayout1.addWidget(self.lblShowAmbHourLoad, 2, 3, 1, 1)
        self.lblAmbLoad = QtGui.QLabel(self.frame)
        self.lblAmbLoad.setObjectName(_fromUtf8("lblAmbLoad"))
        self.gridlayout1.addWidget(self.lblAmbLoad, 2, 4, 1, 1)
        self.lblShowAmbLoad = QtGui.QLabel(self.frame)
        self.lblShowAmbLoad.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowAmbLoad.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowAmbLoad.setObjectName(_fromUtf8("lblShowAmbLoad"))
        self.gridlayout1.addWidget(self.lblShowAmbLoad, 2, 5, 1, 1)
        self.lblAmbExec = QtGui.QLabel(self.frame)
        self.lblAmbExec.setObjectName(_fromUtf8("lblAmbExec"))
        self.gridlayout1.addWidget(self.lblAmbExec, 2, 6, 1, 1)
        self.lblShowAmbExec = QtGui.QLabel(self.frame)
        self.lblShowAmbExec.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowAmbExec.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowAmbExec.setObjectName(_fromUtf8("lblShowAmbExec"))
        self.gridlayout1.addWidget(self.lblShowAmbExec, 2, 7, 1, 1)
        self.lblHomeDays = QtGui.QLabel(self.frame)
        self.lblHomeDays.setObjectName(_fromUtf8("lblHomeDays"))
        self.gridlayout1.addWidget(self.lblHomeDays, 3, 0, 1, 1)
        self.lblShowHomeDays = QtGui.QLabel(self.frame)
        self.lblShowHomeDays.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowHomeDays.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowHomeDays.setObjectName(_fromUtf8("lblShowHomeDays"))
        self.gridlayout1.addWidget(self.lblShowHomeDays, 3, 1, 1, 1)
        self.lblHomeHourLoad = QtGui.QLabel(self.frame)
        self.lblHomeHourLoad.setObjectName(_fromUtf8("lblHomeHourLoad"))
        self.gridlayout1.addWidget(self.lblHomeHourLoad, 3, 2, 1, 1)
        self.lblShowHomeHourLoad = QtGui.QLabel(self.frame)
        self.lblShowHomeHourLoad.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowHomeHourLoad.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowHomeHourLoad.setObjectName(_fromUtf8("lblShowHomeHourLoad"))
        self.gridlayout1.addWidget(self.lblShowHomeHourLoad, 3, 3, 1, 1)
        self.lblHomeLoad = QtGui.QLabel(self.frame)
        self.lblHomeLoad.setObjectName(_fromUtf8("lblHomeLoad"))
        self.gridlayout1.addWidget(self.lblHomeLoad, 3, 4, 1, 1)
        self.lblShowHomeLoad = QtGui.QLabel(self.frame)
        self.lblShowHomeLoad.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowHomeLoad.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowHomeLoad.setObjectName(_fromUtf8("lblShowHomeLoad"))
        self.gridlayout1.addWidget(self.lblShowHomeLoad, 3, 5, 1, 1)
        self.lblHomeExec = QtGui.QLabel(self.frame)
        self.lblHomeExec.setObjectName(_fromUtf8("lblHomeExec"))
        self.gridlayout1.addWidget(self.lblHomeExec, 3, 6, 1, 1)
        self.lblShowHomeExec = QtGui.QLabel(self.frame)
        self.lblShowHomeExec.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowHomeExec.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowHomeExec.setObjectName(_fromUtf8("lblShowHomeExec"))
        self.gridlayout1.addWidget(self.lblShowHomeExec, 3, 7, 1, 1)
        self.lblExpDays = QtGui.QLabel(self.frame)
        self.lblExpDays.setObjectName(_fromUtf8("lblExpDays"))
        self.gridlayout1.addWidget(self.lblExpDays, 4, 0, 1, 1)
        self.lblShowExpDays = QtGui.QLabel(self.frame)
        self.lblShowExpDays.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowExpDays.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowExpDays.setObjectName(_fromUtf8("lblShowExpDays"))
        self.gridlayout1.addWidget(self.lblShowExpDays, 4, 1, 1, 1)
        self.lblExpHourLoad = QtGui.QLabel(self.frame)
        self.lblExpHourLoad.setObjectName(_fromUtf8("lblExpHourLoad"))
        self.gridlayout1.addWidget(self.lblExpHourLoad, 4, 2, 1, 1)
        self.lblShowExpHourLoad = QtGui.QLabel(self.frame)
        self.lblShowExpHourLoad.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowExpHourLoad.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowExpHourLoad.setObjectName(_fromUtf8("lblShowExpHourLoad"))
        self.gridlayout1.addWidget(self.lblShowExpHourLoad, 4, 3, 1, 1)
        self.lblExpLoad = QtGui.QLabel(self.frame)
        self.lblExpLoad.setObjectName(_fromUtf8("lblExpLoad"))
        self.gridlayout1.addWidget(self.lblExpLoad, 4, 4, 1, 1)
        self.lblShowExpLoad = QtGui.QLabel(self.frame)
        self.lblShowExpLoad.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowExpLoad.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowExpLoad.setObjectName(_fromUtf8("lblShowExpLoad"))
        self.gridlayout1.addWidget(self.lblShowExpLoad, 4, 5, 1, 1)
        self.lblExpExec = QtGui.QLabel(self.frame)
        self.lblExpExec.setObjectName(_fromUtf8("lblExpExec"))
        self.gridlayout1.addWidget(self.lblExpExec, 4, 6, 1, 1)
        self.lblShowExpExec = QtGui.QLabel(self.frame)
        self.lblShowExpExec.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowExpExec.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowExpExec.setObjectName(_fromUtf8("lblShowExpExec"))
        self.gridlayout1.addWidget(self.lblShowExpExec, 4, 7, 1, 1)
        self.vboxlayout.addWidget(self.frame)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.btnFill = QtGui.QPushButton(self.layoutWidget)
        self.btnFill.setObjectName(_fromUtf8("btnFill"))
        self.hboxlayout.addWidget(self.btnFill)
        self.btnCalc = QtGui.QPushButton(self.layoutWidget)
        self.btnCalc.setObjectName(_fromUtf8("btnCalc"))
        self.hboxlayout.addWidget(self.btnCalc)
        self.btnPrint = QtGui.QPushButton(self.layoutWidget)
        self.btnPrint.setObjectName(_fromUtf8("btnPrint"))
        self.hboxlayout.addWidget(self.btnPrint)
        self.btnDubl = QtGui.QPushButton(self.layoutWidget)
        self.btnDubl.setObjectName(_fromUtf8("btnDubl"))
        self.hboxlayout.addWidget(self.btnDubl)
        self.btnSum = QtGui.QPushButton(self.layoutWidget)
        self.btnSum.setObjectName(_fromUtf8("btnSum"))
        self.hboxlayout.addWidget(self.btnSum)
        self.btnFact = QtGui.QPushButton(self.layoutWidget)
        self.btnFact.setObjectName(_fromUtf8("btnFact"))
        self.hboxlayout.addWidget(self.btnFact)
        self.tblAbsence = QtGui.QPushButton(self.layoutWidget)
        self.tblAbsence.setObjectName(_fromUtf8("tblAbsence"))
        self.hboxlayout.addWidget(self.tblAbsence)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.btnOk = QtGui.QPushButton(self.layoutWidget)
        self.btnOk.setObjectName(_fromUtf8("btnOk"))
        self.hboxlayout.addWidget(self.btnOk)
        self.btnCancel = QtGui.QPushButton(self.layoutWidget)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.hboxlayout.addWidget(self.btnCancel)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.gridlayout.addWidget(self.splitter_2, 0, 0, 1, 1)

        self.retranslateUi(TimelineDialog)
        QtCore.QObject.connect(self.btnOk, QtCore.SIGNAL(_fromUtf8("clicked()")), TimelineDialog.accept)
        QtCore.QObject.connect(self.btnCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), TimelineDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(TimelineDialog)
        TimelineDialog.setTabOrder(self.calendar, self.treeOrgStructure)
        TimelineDialog.setTabOrder(self.treeOrgStructure, self.tblPersonnel)
        TimelineDialog.setTabOrder(self.tblPersonnel, self.tblTimeTable)
        TimelineDialog.setTabOrder(self.tblTimeTable, self.btnFill)
        TimelineDialog.setTabOrder(self.btnFill, self.btnCalc)
        TimelineDialog.setTabOrder(self.btnCalc, self.btnPrint)
        TimelineDialog.setTabOrder(self.btnPrint, self.btnOk)

    def retranslateUi(self, TimelineDialog):
        TimelineDialog.setWindowTitle(_translate("TimelineDialog", "График", None))
        self.lblNumDays.setText(_translate("TimelineDialog", "Количество дней:", None))
        self.lblShowNumDays.setText(_translate("TimelineDialog", "0", None))
        self.lblHourLoad.setText(_translate("TimelineDialog", "Среднечасовая нагрузка:", None))
        self.lblShowHourLoad.setText(_translate("TimelineDialog", "0", None))
        self.lblLoad.setText(_translate("TimelineDialog", "Средняя подушевая нагрузка:", None))
        self.lblShowLoad.setText(_translate("TimelineDialog", "0", None))
        self.lblExec.setText(_translate("TimelineDialog", "Выполнение плана:", None))
        self.lblShowExec.setText(_translate("TimelineDialog", "0", None))
        self.lblAbsenceDays.setText(_translate("TimelineDialog", "Дней с отсутствием:", None))
        self.lblShowAbsenceDays.setText(_translate("TimelineDialog", "0", None))
        self.lblServHourLoad.setText(_translate("TimelineDialog", "на обслуживании", None))
        self.lblShowServHourLoad.setText(_translate("TimelineDialog", "0", None))
        self.lblServLoad.setText(_translate("TimelineDialog", "на обслуживании", None))
        self.lblShowServLoad.setText(_translate("TimelineDialog", "0", None))
        self.lblServExec.setText(_translate("TimelineDialog", "на обслуживании", None))
        self.lblShowServExec.setText(_translate("TimelineDialog", "0", None))
        self.lblAmbDays.setText(_translate("TimelineDialog", "Дней на приёме:", None))
        self.lblShowAmbDays.setText(_translate("TimelineDialog", "0", None))
        self.lblAmbHourLoad.setText(_translate("TimelineDialog", "СН на приёме:", None))
        self.lblShowAmbHourLoad.setText(_translate("TimelineDialog", "0", None))
        self.lblAmbLoad.setText(_translate("TimelineDialog", "СПН на приёме:", None))
        self.lblShowAmbLoad.setText(_translate("TimelineDialog", "0", None))
        self.lblAmbExec.setText(_translate("TimelineDialog", "ВП на приёме:", None))
        self.lblShowAmbExec.setText(_translate("TimelineDialog", "0", None))
        self.lblHomeDays.setText(_translate("TimelineDialog", "Дней на вызовах:", None))
        self.lblShowHomeDays.setText(_translate("TimelineDialog", "0", None))
        self.lblHomeHourLoad.setText(_translate("TimelineDialog", "СН на вызовах:", None))
        self.lblShowHomeHourLoad.setText(_translate("TimelineDialog", "0", None))
        self.lblHomeLoad.setText(_translate("TimelineDialog", "СПН на вызовах:", None))
        self.lblShowHomeLoad.setText(_translate("TimelineDialog", "0", None))
        self.lblHomeExec.setText(_translate("TimelineDialog", "ВП на вызовах:", None))
        self.lblShowHomeExec.setText(_translate("TimelineDialog", "0", None))
        self.lblExpDays.setText(_translate("TimelineDialog", "Дней на КЭР:", None))
        self.lblShowExpDays.setText(_translate("TimelineDialog", "0", None))
        self.lblExpHourLoad.setText(_translate("TimelineDialog", "СН на КЭР:", None))
        self.lblShowExpHourLoad.setText(_translate("TimelineDialog", "0", None))
        self.lblExpLoad.setText(_translate("TimelineDialog", "СПН на КЭР:", None))
        self.lblShowExpLoad.setText(_translate("TimelineDialog", "0", None))
        self.lblExpExec.setText(_translate("TimelineDialog", "ВП на КЭР:", None))
        self.lblShowExpExec.setText(_translate("TimelineDialog", "0", None))
        self.btnFill.setText(_translate("TimelineDialog", "Заполнить (F9)", None))
        self.btnFill.setShortcut(_translate("TimelineDialog", "F9", None))
        self.btnCalc.setText(_translate("TimelineDialog", "Посещения", None))
        self.btnPrint.setText(_translate("TimelineDialog", "Печатать (F6)", None))
        self.btnPrint.setShortcut(_translate("TimelineDialog", "F6", None))
        self.btnDubl.setText(_translate("TimelineDialog", "Копировать с предыдущего месяца", None))
        self.btnSum.setText(_translate("TimelineDialog", "Заполнить общее время", None))
        self.btnFact.setText(_translate("TimelineDialog", "Заполнить фактическое время", None))
        self.tblAbsence.setText(_translate("TimelineDialog", "Отсутствие", None))
        self.btnOk.setText(_translate("TimelineDialog", "Ок", None))
        self.btnCancel.setText(_translate("TimelineDialog", "Отменить", None))

from TimeTable import CTimeTable
from library.TableView import CTableView
from library.calendar import CCalendarWidget
