# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\Timeline\TemplateDialogMany.ui'
#
# Created: Fri Jun 15 12:16:59 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_TemplateDialogMany(object):
    def setupUi(self, TemplateDialogMany):
        TemplateDialogMany.setObjectName(_fromUtf8("TemplateDialogMany"))
        TemplateDialogMany.resize(617, 657)
        self.gridLayout = QtGui.QGridLayout(TemplateDialogMany)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.dateRangeLayout = QtGui.QHBoxLayout()
        self.dateRangeLayout.setSpacing(4)
        self.dateRangeLayout.setObjectName(_fromUtf8("dateRangeLayout"))
        self.lblBegDate = QtGui.QLabel(TemplateDialogMany)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.dateRangeLayout.addWidget(self.lblBegDate)
        self.edtBegDate = CDateEdit(TemplateDialogMany)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.dateRangeLayout.addWidget(self.edtBegDate)
        self.lblEndDate = QtGui.QLabel(TemplateDialogMany)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.dateRangeLayout.addWidget(self.lblEndDate)
        self.edtEndDate = CDateEdit(TemplateDialogMany)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.dateRangeLayout.addWidget(self.edtEndDate)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.dateRangeLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.dateRangeLayout, 0, 0, 1, 3)
        self.rbSingle = QtGui.QRadioButton(TemplateDialogMany)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbSingle.sizePolicy().hasHeightForWidth())
        self.rbSingle.setSizePolicy(sizePolicy)
        self.rbSingle.setObjectName(_fromUtf8("rbSingle"))
        self.gridLayout.addWidget(self.rbSingle, 1, 0, 1, 1)
        self.grbOnePlan = QtGui.QGroupBox(TemplateDialogMany)
        self.grbOnePlan.setObjectName(_fromUtf8("grbOnePlan"))
        self.gridLayout_6 = QtGui.QGridLayout(self.grbOnePlan)
        self.gridLayout_6.setMargin(4)
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lblAmb = QtGui.QLabel(self.grbOnePlan)
        self.lblAmb.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lblAmb.setWordWrap(True)
        self.lblAmb.setObjectName(_fromUtf8("lblAmb"))
        self.gridLayout_6.addWidget(self.lblAmb, 0, 0, 1, 3)
        self.lblHome = QtGui.QLabel(self.grbOnePlan)
        self.lblHome.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lblHome.setWordWrap(True)
        self.lblHome.setObjectName(_fromUtf8("lblHome"))
        self.gridLayout_6.addWidget(self.lblHome, 0, 3, 1, 1)
        self.lblReasonOfAbsence1 = QtGui.QLabel(self.grbOnePlan)
        self.lblReasonOfAbsence1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lblReasonOfAbsence1.setObjectName(_fromUtf8("lblReasonOfAbsence1"))
        self.gridLayout_6.addWidget(self.lblReasonOfAbsence1, 0, 5, 1, 1)
        self.label_1 = QtGui.QLabel(self.grbOnePlan)
        self.label_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.gridLayout_6.addWidget(self.label_1, 1, 0, 1, 1)
        self.edtAmbTimeRange1 = CTimeRangeEdit(self.grbOnePlan)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbTimeRange1.sizePolicy().hasHeightForWidth())
        self.edtAmbTimeRange1.setSizePolicy(sizePolicy)
        self.edtAmbTimeRange1.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtAmbTimeRange1.setMaxLength(13)
        self.edtAmbTimeRange1.setObjectName(_fromUtf8("edtAmbTimeRange1"))
        self.gridLayout_6.addWidget(self.edtAmbTimeRange1, 1, 1, 1, 1)
        self.edtHomeTimeRange1 = CTimeRangeEdit(self.grbOnePlan)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHomeTimeRange1.sizePolicy().hasHeightForWidth())
        self.edtHomeTimeRange1.setSizePolicy(sizePolicy)
        self.edtHomeTimeRange1.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtHomeTimeRange1.setMaxLength(13)
        self.edtHomeTimeRange1.setObjectName(_fromUtf8("edtHomeTimeRange1"))
        self.gridLayout_6.addWidget(self.edtHomeTimeRange1, 1, 3, 1, 1)
        self.cmbReasonOfAbsence1 = CRBComboBox(self.grbOnePlan)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReasonOfAbsence1.sizePolicy().hasHeightForWidth())
        self.cmbReasonOfAbsence1.setSizePolicy(sizePolicy)
        self.cmbReasonOfAbsence1.setObjectName(_fromUtf8("cmbReasonOfAbsence1"))
        self.gridLayout_6.addWidget(self.cmbReasonOfAbsence1, 1, 5, 1, 1)
        self.label_2 = QtGui.QLabel(self.grbOnePlan)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 2, 0, 1, 1)
        self.edtAmbTimeRange12 = CTimeRangeEdit(self.grbOnePlan)
        self.edtAmbTimeRange12.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbTimeRange12.sizePolicy().hasHeightForWidth())
        self.edtAmbTimeRange12.setSizePolicy(sizePolicy)
        self.edtAmbTimeRange12.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtAmbTimeRange12.setMaxLength(13)
        self.edtAmbTimeRange12.setObjectName(_fromUtf8("edtAmbTimeRange12"))
        self.gridLayout_6.addWidget(self.edtAmbTimeRange12, 2, 1, 1, 1)
        self.edtHomeTimeRange12 = CTimeRangeEdit(self.grbOnePlan)
        self.edtHomeTimeRange12.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHomeTimeRange12.sizePolicy().hasHeightForWidth())
        self.edtHomeTimeRange12.setSizePolicy(sizePolicy)
        self.edtHomeTimeRange12.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtHomeTimeRange12.setMaxLength(13)
        self.edtHomeTimeRange12.setObjectName(_fromUtf8("edtHomeTimeRange12"))
        self.gridLayout_6.addWidget(self.edtHomeTimeRange12, 2, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(147, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 2, 5, 1, 1)
        self.gridLayout.addWidget(self.grbOnePlan, 1, 1, 1, 2)
        self.rbDual = QtGui.QRadioButton(TemplateDialogMany)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbDual.sizePolicy().hasHeightForWidth())
        self.rbDual.setSizePolicy(sizePolicy)
        self.rbDual.setChecked(True)
        self.rbDual.setObjectName(_fromUtf8("rbDual"))
        self.gridLayout.addWidget(self.rbDual, 2, 0, 1, 1)
        self.grbOddEvenPlan = QtGui.QGroupBox(TemplateDialogMany)
        self.grbOddEvenPlan.setObjectName(_fromUtf8("grbOddEvenPlan"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grbOddEvenPlan)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.grbOddEvenPlan)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.edtAmbTimeRange2 = CTimeRangeEdit(self.grbOddEvenPlan)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbTimeRange2.sizePolicy().hasHeightForWidth())
        self.edtAmbTimeRange2.setSizePolicy(sizePolicy)
        self.edtAmbTimeRange2.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtAmbTimeRange2.setMaxLength(13)
        self.edtAmbTimeRange2.setObjectName(_fromUtf8("edtAmbTimeRange2"))
        self.gridLayout_2.addWidget(self.edtAmbTimeRange2, 0, 1, 1, 1)
        self.edtHomeTimeRange2 = CTimeRangeEdit(self.grbOddEvenPlan)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHomeTimeRange2.sizePolicy().hasHeightForWidth())
        self.edtHomeTimeRange2.setSizePolicy(sizePolicy)
        self.edtHomeTimeRange2.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtHomeTimeRange2.setMaxLength(13)
        self.edtHomeTimeRange2.setObjectName(_fromUtf8("edtHomeTimeRange2"))
        self.gridLayout_2.addWidget(self.edtHomeTimeRange2, 0, 2, 1, 1)
        self.cmbReasonOfAbsence2 = CRBComboBox(self.grbOddEvenPlan)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReasonOfAbsence2.sizePolicy().hasHeightForWidth())
        self.cmbReasonOfAbsence2.setSizePolicy(sizePolicy)
        self.cmbReasonOfAbsence2.setObjectName(_fromUtf8("cmbReasonOfAbsence2"))
        self.gridLayout_2.addWidget(self.cmbReasonOfAbsence2, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.grbOddEvenPlan)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.edtAmbTimeRange22 = CTimeRangeEdit(self.grbOddEvenPlan)
        self.edtAmbTimeRange22.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbTimeRange22.sizePolicy().hasHeightForWidth())
        self.edtAmbTimeRange22.setSizePolicy(sizePolicy)
        self.edtAmbTimeRange22.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtAmbTimeRange22.setMaxLength(13)
        self.edtAmbTimeRange22.setObjectName(_fromUtf8("edtAmbTimeRange22"))
        self.gridLayout_2.addWidget(self.edtAmbTimeRange22, 1, 1, 1, 1)
        self.edtHomeTimeRange22 = CTimeRangeEdit(self.grbOddEvenPlan)
        self.edtHomeTimeRange22.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHomeTimeRange22.sizePolicy().hasHeightForWidth())
        self.edtHomeTimeRange22.setSizePolicy(sizePolicy)
        self.edtHomeTimeRange22.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtHomeTimeRange22.setMaxLength(13)
        self.edtHomeTimeRange22.setObjectName(_fromUtf8("edtHomeTimeRange22"))
        self.gridLayout_2.addWidget(self.edtHomeTimeRange22, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.grbOddEvenPlan, 2, 1, 1, 2)
        self.rbNed = QtGui.QRadioButton(TemplateDialogMany)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbNed.sizePolicy().hasHeightForWidth())
        self.rbNed.setSizePolicy(sizePolicy)
        self.rbNed.setChecked(False)
        self.rbNed.setObjectName(_fromUtf8("rbNed"))
        self.gridLayout.addWidget(self.rbNed, 3, 0, 1, 1)
        self.grbWeekPlan1 = QtGui.QGroupBox(TemplateDialogMany)
        self.grbWeekPlan1.setTitle(_fromUtf8(""))
        self.grbWeekPlan1.setObjectName(_fromUtf8("grbWeekPlan1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grbWeekPlan1)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.grbWeekPlan1)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.edtAmbTimeRange3 = CTimeRangeEdit(self.grbWeekPlan1)
        self.edtAmbTimeRange3.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbTimeRange3.sizePolicy().hasHeightForWidth())
        self.edtAmbTimeRange3.setSizePolicy(sizePolicy)
        self.edtAmbTimeRange3.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtAmbTimeRange3.setMaxLength(13)
        self.edtAmbTimeRange3.setObjectName(_fromUtf8("edtAmbTimeRange3"))
        self.gridLayout_3.addWidget(self.edtAmbTimeRange3, 0, 1, 1, 1)
        self.edtHomeTimeRange3 = CTimeRangeEdit(self.grbWeekPlan1)
        self.edtHomeTimeRange3.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHomeTimeRange3.sizePolicy().hasHeightForWidth())
        self.edtHomeTimeRange3.setSizePolicy(sizePolicy)
        self.edtHomeTimeRange3.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtHomeTimeRange3.setMaxLength(13)
        self.edtHomeTimeRange3.setObjectName(_fromUtf8("edtHomeTimeRange3"))
        self.gridLayout_3.addWidget(self.edtHomeTimeRange3, 0, 2, 1, 1)
        self.cmbReasonOfAbsence3 = CRBComboBox(self.grbWeekPlan1)
        self.cmbReasonOfAbsence3.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReasonOfAbsence3.sizePolicy().hasHeightForWidth())
        self.cmbReasonOfAbsence3.setSizePolicy(sizePolicy)
        self.cmbReasonOfAbsence3.setObjectName(_fromUtf8("cmbReasonOfAbsence3"))
        self.gridLayout_3.addWidget(self.cmbReasonOfAbsence3, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.grbWeekPlan1)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.edtAmbTimeRange32 = CTimeRangeEdit(self.grbWeekPlan1)
        self.edtAmbTimeRange32.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbTimeRange32.sizePolicy().hasHeightForWidth())
        self.edtAmbTimeRange32.setSizePolicy(sizePolicy)
        self.edtAmbTimeRange32.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtAmbTimeRange32.setMaxLength(13)
        self.edtAmbTimeRange32.setObjectName(_fromUtf8("edtAmbTimeRange32"))
        self.gridLayout_3.addWidget(self.edtAmbTimeRange32, 1, 1, 1, 1)
        self.edtHomeTimeRange32 = CTimeRangeEdit(self.grbWeekPlan1)
        self.edtHomeTimeRange32.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHomeTimeRange32.sizePolicy().hasHeightForWidth())
        self.edtHomeTimeRange32.setSizePolicy(sizePolicy)
        self.edtHomeTimeRange32.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtHomeTimeRange32.setMaxLength(13)
        self.edtHomeTimeRange32.setObjectName(_fromUtf8("edtHomeTimeRange32"))
        self.gridLayout_3.addWidget(self.edtHomeTimeRange32, 1, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.grbWeekPlan1, 3, 1, 1, 2)
        self.grbWeekPlan2 = QtGui.QGroupBox(TemplateDialogMany)
        self.grbWeekPlan2.setTitle(_fromUtf8(""))
        self.grbWeekPlan2.setObjectName(_fromUtf8("grbWeekPlan2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.grbWeekPlan2)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_7 = QtGui.QLabel(self.grbWeekPlan2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.edtAmbTimeRange4 = CTimeRangeEdit(self.grbWeekPlan2)
        self.edtAmbTimeRange4.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbTimeRange4.sizePolicy().hasHeightForWidth())
        self.edtAmbTimeRange4.setSizePolicy(sizePolicy)
        self.edtAmbTimeRange4.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtAmbTimeRange4.setMaxLength(13)
        self.edtAmbTimeRange4.setObjectName(_fromUtf8("edtAmbTimeRange4"))
        self.gridLayout_4.addWidget(self.edtAmbTimeRange4, 0, 1, 1, 1)
        self.edtHomeTimeRange4 = CTimeRangeEdit(self.grbWeekPlan2)
        self.edtHomeTimeRange4.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHomeTimeRange4.sizePolicy().hasHeightForWidth())
        self.edtHomeTimeRange4.setSizePolicy(sizePolicy)
        self.edtHomeTimeRange4.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtHomeTimeRange4.setMaxLength(13)
        self.edtHomeTimeRange4.setObjectName(_fromUtf8("edtHomeTimeRange4"))
        self.gridLayout_4.addWidget(self.edtHomeTimeRange4, 0, 2, 1, 1)
        self.cmbReasonOfAbsence4 = CRBComboBox(self.grbWeekPlan2)
        self.cmbReasonOfAbsence4.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReasonOfAbsence4.sizePolicy().hasHeightForWidth())
        self.cmbReasonOfAbsence4.setSizePolicy(sizePolicy)
        self.cmbReasonOfAbsence4.setObjectName(_fromUtf8("cmbReasonOfAbsence4"))
        self.gridLayout_4.addWidget(self.cmbReasonOfAbsence4, 0, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.grbWeekPlan2)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.edtAmbTimeRange42 = CTimeRangeEdit(self.grbWeekPlan2)
        self.edtAmbTimeRange42.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbTimeRange42.sizePolicy().hasHeightForWidth())
        self.edtAmbTimeRange42.setSizePolicy(sizePolicy)
        self.edtAmbTimeRange42.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtAmbTimeRange42.setMaxLength(13)
        self.edtAmbTimeRange42.setObjectName(_fromUtf8("edtAmbTimeRange42"))
        self.gridLayout_4.addWidget(self.edtAmbTimeRange42, 1, 1, 1, 1)
        self.edtHomeTimeRange42 = CTimeRangeEdit(self.grbWeekPlan2)
        self.edtHomeTimeRange42.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHomeTimeRange42.sizePolicy().hasHeightForWidth())
        self.edtHomeTimeRange42.setSizePolicy(sizePolicy)
        self.edtHomeTimeRange42.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtHomeTimeRange42.setMaxLength(13)
        self.edtHomeTimeRange42.setObjectName(_fromUtf8("edtHomeTimeRange42"))
        self.gridLayout_4.addWidget(self.edtHomeTimeRange42, 1, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.grbWeekPlan2, 4, 1, 1, 2)
        self.grbWeekPlan3 = QtGui.QGroupBox(TemplateDialogMany)
        self.grbWeekPlan3.setTitle(_fromUtf8(""))
        self.grbWeekPlan3.setObjectName(_fromUtf8("grbWeekPlan3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.grbWeekPlan3)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_9 = QtGui.QLabel(self.grbWeekPlan3)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.edtAmbTimeRange5 = CTimeRangeEdit(self.grbWeekPlan3)
        self.edtAmbTimeRange5.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbTimeRange5.sizePolicy().hasHeightForWidth())
        self.edtAmbTimeRange5.setSizePolicy(sizePolicy)
        self.edtAmbTimeRange5.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtAmbTimeRange5.setMaxLength(13)
        self.edtAmbTimeRange5.setObjectName(_fromUtf8("edtAmbTimeRange5"))
        self.gridLayout_5.addWidget(self.edtAmbTimeRange5, 0, 1, 1, 1)
        self.edtHomeTimeRange5 = CTimeRangeEdit(self.grbWeekPlan3)
        self.edtHomeTimeRange5.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHomeTimeRange5.sizePolicy().hasHeightForWidth())
        self.edtHomeTimeRange5.setSizePolicy(sizePolicy)
        self.edtHomeTimeRange5.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtHomeTimeRange5.setMaxLength(13)
        self.edtHomeTimeRange5.setObjectName(_fromUtf8("edtHomeTimeRange5"))
        self.gridLayout_5.addWidget(self.edtHomeTimeRange5, 0, 2, 1, 1)
        self.cmbReasonOfAbsence5 = CRBComboBox(self.grbWeekPlan3)
        self.cmbReasonOfAbsence5.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReasonOfAbsence5.sizePolicy().hasHeightForWidth())
        self.cmbReasonOfAbsence5.setSizePolicy(sizePolicy)
        self.cmbReasonOfAbsence5.setObjectName(_fromUtf8("cmbReasonOfAbsence5"))
        self.gridLayout_5.addWidget(self.cmbReasonOfAbsence5, 0, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.grbWeekPlan3)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.edtAmbTimeRange52 = CTimeRangeEdit(self.grbWeekPlan3)
        self.edtAmbTimeRange52.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbTimeRange52.sizePolicy().hasHeightForWidth())
        self.edtAmbTimeRange52.setSizePolicy(sizePolicy)
        self.edtAmbTimeRange52.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtAmbTimeRange52.setMaxLength(13)
        self.edtAmbTimeRange52.setObjectName(_fromUtf8("edtAmbTimeRange52"))
        self.gridLayout_5.addWidget(self.edtAmbTimeRange52, 1, 1, 1, 1)
        self.edtHomeTimeRange52 = CTimeRangeEdit(self.grbWeekPlan3)
        self.edtHomeTimeRange52.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHomeTimeRange52.sizePolicy().hasHeightForWidth())
        self.edtHomeTimeRange52.setSizePolicy(sizePolicy)
        self.edtHomeTimeRange52.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtHomeTimeRange52.setMaxLength(13)
        self.edtHomeTimeRange52.setObjectName(_fromUtf8("edtHomeTimeRange52"))
        self.gridLayout_5.addWidget(self.edtHomeTimeRange52, 1, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.grbWeekPlan3, 5, 1, 1, 2)
        self.chkFillRedDays = QtGui.QCheckBox(TemplateDialogMany)
        self.chkFillRedDays.setObjectName(_fromUtf8("chkFillRedDays"))
        self.gridLayout.addWidget(self.chkFillRedDays, 8, 0, 1, 2)
        self.chkAmbSecondPeriod = QtGui.QCheckBox(TemplateDialogMany)
        self.chkAmbSecondPeriod.setObjectName(_fromUtf8("chkAmbSecondPeriod"))
        self.gridLayout.addWidget(self.chkAmbSecondPeriod, 9, 0, 1, 2)
        self.chkHomeSecondPeriod = QtGui.QCheckBox(TemplateDialogMany)
        self.chkHomeSecondPeriod.setObjectName(_fromUtf8("chkHomeSecondPeriod"))
        self.gridLayout.addWidget(self.chkHomeSecondPeriod, 10, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(TemplateDialogMany)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 11, 2, 1, 1)
        self.grbWeekPlan4 = QtGui.QGroupBox(TemplateDialogMany)
        self.grbWeekPlan4.setTitle(_fromUtf8(""))
        self.grbWeekPlan4.setObjectName(_fromUtf8("grbWeekPlan4"))
        self.gridLayout_8 = QtGui.QGridLayout(self.grbWeekPlan4)
        self.gridLayout_8.setMargin(4)
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_13 = QtGui.QLabel(self.grbWeekPlan4)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_8.addWidget(self.label_13, 0, 0, 1, 1)
        self.edtAmbTimeRange6 = CTimeRangeEdit(self.grbWeekPlan4)
        self.edtAmbTimeRange6.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbTimeRange6.sizePolicy().hasHeightForWidth())
        self.edtAmbTimeRange6.setSizePolicy(sizePolicy)
        self.edtAmbTimeRange6.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtAmbTimeRange6.setMaxLength(13)
        self.edtAmbTimeRange6.setObjectName(_fromUtf8("edtAmbTimeRange6"))
        self.gridLayout_8.addWidget(self.edtAmbTimeRange6, 0, 1, 1, 1)
        self.edtHomeTimeRange6 = CTimeRangeEdit(self.grbWeekPlan4)
        self.edtHomeTimeRange6.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHomeTimeRange6.sizePolicy().hasHeightForWidth())
        self.edtHomeTimeRange6.setSizePolicy(sizePolicy)
        self.edtHomeTimeRange6.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtHomeTimeRange6.setMaxLength(13)
        self.edtHomeTimeRange6.setObjectName(_fromUtf8("edtHomeTimeRange6"))
        self.gridLayout_8.addWidget(self.edtHomeTimeRange6, 0, 2, 1, 1)
        self.cmbReasonOfAbsence6 = CRBComboBox(self.grbWeekPlan4)
        self.cmbReasonOfAbsence6.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReasonOfAbsence6.sizePolicy().hasHeightForWidth())
        self.cmbReasonOfAbsence6.setSizePolicy(sizePolicy)
        self.cmbReasonOfAbsence6.setObjectName(_fromUtf8("cmbReasonOfAbsence6"))
        self.gridLayout_8.addWidget(self.cmbReasonOfAbsence6, 0, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.grbWeekPlan4)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_8.addWidget(self.label_14, 1, 0, 1, 1)
        self.edtAmbTimeRange62 = CTimeRangeEdit(self.grbWeekPlan4)
        self.edtAmbTimeRange62.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbTimeRange62.sizePolicy().hasHeightForWidth())
        self.edtAmbTimeRange62.setSizePolicy(sizePolicy)
        self.edtAmbTimeRange62.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtAmbTimeRange62.setMaxLength(13)
        self.edtAmbTimeRange62.setObjectName(_fromUtf8("edtAmbTimeRange62"))
        self.gridLayout_8.addWidget(self.edtAmbTimeRange62, 1, 1, 1, 1)
        self.edtHomeTimeRange62 = CTimeRangeEdit(self.grbWeekPlan4)
        self.edtHomeTimeRange62.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHomeTimeRange62.sizePolicy().hasHeightForWidth())
        self.edtHomeTimeRange62.setSizePolicy(sizePolicy)
        self.edtHomeTimeRange62.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtHomeTimeRange62.setMaxLength(13)
        self.edtHomeTimeRange62.setObjectName(_fromUtf8("edtHomeTimeRange62"))
        self.gridLayout_8.addWidget(self.edtHomeTimeRange62, 1, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem6, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.grbWeekPlan4, 6, 1, 1, 2)
        self.grbWeekPlan5 = QtGui.QGroupBox(TemplateDialogMany)
        self.grbWeekPlan5.setTitle(_fromUtf8(""))
        self.grbWeekPlan5.setObjectName(_fromUtf8("grbWeekPlan5"))
        self.gridLayout_7 = QtGui.QGridLayout(self.grbWeekPlan5)
        self.gridLayout_7.setMargin(4)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_11 = QtGui.QLabel(self.grbWeekPlan5)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_7.addWidget(self.label_11, 0, 0, 1, 1)
        self.edtAmbTimeRange7 = CTimeRangeEdit(self.grbWeekPlan5)
        self.edtAmbTimeRange7.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbTimeRange7.sizePolicy().hasHeightForWidth())
        self.edtAmbTimeRange7.setSizePolicy(sizePolicy)
        self.edtAmbTimeRange7.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtAmbTimeRange7.setMaxLength(13)
        self.edtAmbTimeRange7.setObjectName(_fromUtf8("edtAmbTimeRange7"))
        self.gridLayout_7.addWidget(self.edtAmbTimeRange7, 0, 1, 1, 1)
        self.edtHomeTimeRange7 = CTimeRangeEdit(self.grbWeekPlan5)
        self.edtHomeTimeRange7.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHomeTimeRange7.sizePolicy().hasHeightForWidth())
        self.edtHomeTimeRange7.setSizePolicy(sizePolicy)
        self.edtHomeTimeRange7.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtHomeTimeRange7.setMaxLength(13)
        self.edtHomeTimeRange7.setObjectName(_fromUtf8("edtHomeTimeRange7"))
        self.gridLayout_7.addWidget(self.edtHomeTimeRange7, 0, 2, 1, 1)
        self.cmbReasonOfAbsence7 = CRBComboBox(self.grbWeekPlan5)
        self.cmbReasonOfAbsence7.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReasonOfAbsence7.sizePolicy().hasHeightForWidth())
        self.cmbReasonOfAbsence7.setSizePolicy(sizePolicy)
        self.cmbReasonOfAbsence7.setObjectName(_fromUtf8("cmbReasonOfAbsence7"))
        self.gridLayout_7.addWidget(self.cmbReasonOfAbsence7, 0, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.grbWeekPlan5)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_7.addWidget(self.label_12, 1, 0, 1, 1)
        self.edtAmbTimeRange72 = CTimeRangeEdit(self.grbWeekPlan5)
        self.edtAmbTimeRange72.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmbTimeRange72.sizePolicy().hasHeightForWidth())
        self.edtAmbTimeRange72.setSizePolicy(sizePolicy)
        self.edtAmbTimeRange72.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtAmbTimeRange72.setMaxLength(13)
        self.edtAmbTimeRange72.setObjectName(_fromUtf8("edtAmbTimeRange72"))
        self.gridLayout_7.addWidget(self.edtAmbTimeRange72, 1, 1, 1, 1)
        self.edtHomeTimeRange72 = CTimeRangeEdit(self.grbWeekPlan5)
        self.edtHomeTimeRange72.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHomeTimeRange72.sizePolicy().hasHeightForWidth())
        self.edtHomeTimeRange72.setSizePolicy(sizePolicy)
        self.edtHomeTimeRange72.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtHomeTimeRange72.setMaxLength(13)
        self.edtHomeTimeRange72.setObjectName(_fromUtf8("edtHomeTimeRange72"))
        self.gridLayout_7.addWidget(self.edtHomeTimeRange72, 1, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem7, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.grbWeekPlan5, 7, 1, 1, 2)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndDate.setBuddy(self.edtEndDate)

        self.retranslateUi(TemplateDialogMany)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TemplateDialogMany.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TemplateDialogMany.reject)
        QtCore.QObject.connect(self.rbSingle, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtAmbTimeRange2.setDisabled)
        QtCore.QObject.connect(self.rbSingle, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtHomeTimeRange2.setDisabled)
        QtCore.QObject.connect(self.rbSingle, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbReasonOfAbsence2.setDisabled)
        QtCore.QObject.connect(self.rbNed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtAmbTimeRange3.setEnabled)
        QtCore.QObject.connect(self.rbNed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtAmbTimeRange4.setEnabled)
        QtCore.QObject.connect(self.rbNed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtAmbTimeRange5.setEnabled)
        QtCore.QObject.connect(self.rbNed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtHomeTimeRange3.setEnabled)
        QtCore.QObject.connect(self.rbNed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtHomeTimeRange4.setEnabled)
        QtCore.QObject.connect(self.rbNed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtHomeTimeRange5.setEnabled)
        QtCore.QObject.connect(self.rbNed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbReasonOfAbsence3.setEnabled)
        QtCore.QObject.connect(self.rbNed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbReasonOfAbsence4.setEnabled)
        QtCore.QObject.connect(self.rbNed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbReasonOfAbsence5.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(TemplateDialogMany)
        TemplateDialogMany.setTabOrder(self.edtBegDate, self.edtEndDate)
        TemplateDialogMany.setTabOrder(self.edtEndDate, self.rbSingle)
        TemplateDialogMany.setTabOrder(self.rbSingle, self.rbDual)
        TemplateDialogMany.setTabOrder(self.rbDual, self.rbNed)
        TemplateDialogMany.setTabOrder(self.rbNed, self.edtAmbTimeRange1)
        TemplateDialogMany.setTabOrder(self.edtAmbTimeRange1, self.edtHomeTimeRange1)
        TemplateDialogMany.setTabOrder(self.edtHomeTimeRange1, self.cmbReasonOfAbsence1)
        TemplateDialogMany.setTabOrder(self.cmbReasonOfAbsence1, self.edtAmbTimeRange12)
        TemplateDialogMany.setTabOrder(self.edtAmbTimeRange12, self.edtHomeTimeRange12)
        TemplateDialogMany.setTabOrder(self.edtHomeTimeRange12, self.edtAmbTimeRange2)
        TemplateDialogMany.setTabOrder(self.edtAmbTimeRange2, self.edtHomeTimeRange2)
        TemplateDialogMany.setTabOrder(self.edtHomeTimeRange2, self.cmbReasonOfAbsence2)
        TemplateDialogMany.setTabOrder(self.cmbReasonOfAbsence2, self.edtAmbTimeRange22)
        TemplateDialogMany.setTabOrder(self.edtAmbTimeRange22, self.edtHomeTimeRange22)
        TemplateDialogMany.setTabOrder(self.edtHomeTimeRange22, self.edtAmbTimeRange3)
        TemplateDialogMany.setTabOrder(self.edtAmbTimeRange3, self.edtHomeTimeRange3)
        TemplateDialogMany.setTabOrder(self.edtHomeTimeRange3, self.cmbReasonOfAbsence3)
        TemplateDialogMany.setTabOrder(self.cmbReasonOfAbsence3, self.edtAmbTimeRange32)
        TemplateDialogMany.setTabOrder(self.edtAmbTimeRange32, self.edtHomeTimeRange32)
        TemplateDialogMany.setTabOrder(self.edtHomeTimeRange32, self.edtAmbTimeRange4)
        TemplateDialogMany.setTabOrder(self.edtAmbTimeRange4, self.edtHomeTimeRange4)
        TemplateDialogMany.setTabOrder(self.edtHomeTimeRange4, self.cmbReasonOfAbsence4)
        TemplateDialogMany.setTabOrder(self.cmbReasonOfAbsence4, self.edtAmbTimeRange42)
        TemplateDialogMany.setTabOrder(self.edtAmbTimeRange42, self.edtHomeTimeRange42)
        TemplateDialogMany.setTabOrder(self.edtHomeTimeRange42, self.edtAmbTimeRange5)
        TemplateDialogMany.setTabOrder(self.edtAmbTimeRange5, self.edtHomeTimeRange5)
        TemplateDialogMany.setTabOrder(self.edtHomeTimeRange5, self.cmbReasonOfAbsence5)
        TemplateDialogMany.setTabOrder(self.cmbReasonOfAbsence5, self.edtAmbTimeRange52)
        TemplateDialogMany.setTabOrder(self.edtAmbTimeRange52, self.edtHomeTimeRange52)
        TemplateDialogMany.setTabOrder(self.edtHomeTimeRange52, self.edtAmbTimeRange6)
        TemplateDialogMany.setTabOrder(self.edtAmbTimeRange6, self.edtHomeTimeRange6)
        TemplateDialogMany.setTabOrder(self.edtHomeTimeRange6, self.cmbReasonOfAbsence6)
        TemplateDialogMany.setTabOrder(self.cmbReasonOfAbsence6, self.edtAmbTimeRange62)
        TemplateDialogMany.setTabOrder(self.edtAmbTimeRange62, self.edtHomeTimeRange62)
        TemplateDialogMany.setTabOrder(self.edtHomeTimeRange62, self.edtAmbTimeRange7)
        TemplateDialogMany.setTabOrder(self.edtAmbTimeRange7, self.edtHomeTimeRange7)
        TemplateDialogMany.setTabOrder(self.edtHomeTimeRange7, self.cmbReasonOfAbsence7)
        TemplateDialogMany.setTabOrder(self.cmbReasonOfAbsence7, self.edtAmbTimeRange72)
        TemplateDialogMany.setTabOrder(self.edtAmbTimeRange72, self.edtHomeTimeRange72)
        TemplateDialogMany.setTabOrder(self.edtHomeTimeRange72, self.chkFillRedDays)
        TemplateDialogMany.setTabOrder(self.chkFillRedDays, self.chkAmbSecondPeriod)
        TemplateDialogMany.setTabOrder(self.chkAmbSecondPeriod, self.chkHomeSecondPeriod)
        TemplateDialogMany.setTabOrder(self.chkHomeSecondPeriod, self.buttonBox)

    def retranslateUi(self, TemplateDialogMany):
        TemplateDialogMany.setWindowTitle(QtGui.QApplication.translate("TemplateDialogMany", "Шаблон планировщика", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBegDate.setText(QtGui.QApplication.translate("TemplateDialogMany", "В период &с", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndDate.setText(QtGui.QApplication.translate("TemplateDialogMany", "&По", None, QtGui.QApplication.UnicodeUTF8))
        self.rbSingle.setText(QtGui.QApplication.translate("TemplateDialogMany", "&Один план", None, QtGui.QApplication.UnicodeUTF8))
        self.grbOnePlan.setTitle(QtGui.QApplication.translate("TemplateDialogMany", "Нечётный день", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAmb.setText(QtGui.QApplication.translate("TemplateDialogMany", "Амбулаторный приём", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHome.setText(QtGui.QApplication.translate("TemplateDialogMany", "Вызовы на дом", None, QtGui.QApplication.UnicodeUTF8))
        self.lblReasonOfAbsence1.setText(QtGui.QApplication.translate("TemplateDialogMany", "Причина отсутствия", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1.setText(QtGui.QApplication.translate("TemplateDialogMany", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TemplateDialogMany", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.rbDual.setText(QtGui.QApplication.translate("TemplateDialogMany", "&Нечет/чёт", None, QtGui.QApplication.UnicodeUTF8))
        self.grbOddEvenPlan.setTitle(QtGui.QApplication.translate("TemplateDialogMany", "Чётный день", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("TemplateDialogMany", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("TemplateDialogMany", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.rbNed.setText(QtGui.QApplication.translate("TemplateDialogMany", "Не&деля", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("TemplateDialogMany", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("TemplateDialogMany", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("TemplateDialogMany", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("TemplateDialogMany", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("TemplateDialogMany", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("TemplateDialogMany", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFillRedDays.setText(QtGui.QApplication.translate("TemplateDialogMany", "&Заполнять выходные дни", None, QtGui.QApplication.UnicodeUTF8))
        self.chkAmbSecondPeriod.setText(QtGui.QApplication.translate("TemplateDialogMany", "&Ввод второго периода приема", None, QtGui.QApplication.UnicodeUTF8))
        self.chkHomeSecondPeriod.setText(QtGui.QApplication.translate("TemplateDialogMany", "&Ввод второго периода вызовов", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("TemplateDialogMany", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("TemplateDialogMany", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("TemplateDialogMany", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("TemplateDialogMany", "2", None, QtGui.QApplication.UnicodeUTF8))

from library.crbcombobox import CRBComboBox
from library.DateEdit import CDateEdit
from library.TimeEdit import CTimeRangeEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TemplateDialogMany = QtGui.QDialog()
    ui = Ui_TemplateDialogMany()
    ui.setupUi(TemplateDialogMany)
    TemplateDialogMany.show()
    sys.exit(app.exec_())

