# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CustomizableRegistryWidget.ui'
#
# Created: Tue Jun 24 18:42:01 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CustomizableRegistryWidget(object):
    def setupUi(self, CustomizableRegistryWidget):
        CustomizableRegistryWidget.setObjectName(_fromUtf8("CustomizableRegistryWidget"))
        CustomizableRegistryWidget.resize(724, 255)
        CustomizableRegistryWidget.setStyleSheet(_fromUtf8("QToolBox {font: bold 12px}"))
        self.gridLayout_2 = QtGui.QGridLayout(CustomizableRegistryWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(CustomizableRegistryWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabView = QtGui.QWidget()
        self.tabView.setObjectName(_fromUtf8("tabView"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tabView)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tblView = CTableView(self.tabView)
        self.tblView.setObjectName(_fromUtf8("tblView"))
        self.gridLayout_9.addWidget(self.tblView, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.quickFilterLayout = QtGui.QHBoxLayout()
        self.quickFilterLayout.setObjectName(_fromUtf8("quickFilterLayout"))
        self.horizontalLayout.addLayout(self.quickFilterLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnBegin = QtGui.QPushButton(self.tabView)
        self.btnBegin.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btnBegin.setObjectName(_fromUtf8("btnBegin"))
        self.horizontalLayout.addWidget(self.btnBegin)
        self.btnPrevious = QtGui.QPushButton(self.tabView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPrevious.sizePolicy().hasHeightForWidth())
        self.btnPrevious.setSizePolicy(sizePolicy)
        self.btnPrevious.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btnPrevious.setObjectName(_fromUtf8("btnPrevious"))
        self.horizontalLayout.addWidget(self.btnPrevious)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.sbCurrentPage = QtGui.QSpinBox(self.tabView)
        self.sbCurrentPage.setMinimum(1)
        self.sbCurrentPage.setObjectName(_fromUtf8("sbCurrentPage"))
        self.horizontalLayout.addWidget(self.sbCurrentPage)
        self.lblSlashOfPage = QtGui.QLabel(self.tabView)
        self.lblSlashOfPage.setObjectName(_fromUtf8("lblSlashOfPage"))
        self.horizontalLayout.addWidget(self.lblSlashOfPage)
        self.lblTotalPages = QtGui.QLabel(self.tabView)
        self.lblTotalPages.setObjectName(_fromUtf8("lblTotalPages"))
        self.horizontalLayout.addWidget(self.lblTotalPages)
        self.lblPage = QtGui.QLabel(self.tabView)
        self.lblPage.setObjectName(_fromUtf8("lblPage"))
        self.horizontalLayout.addWidget(self.lblPage)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.lblElementsCountInfo = QtGui.QLabel(self.tabView)
        self.lblElementsCountInfo.setObjectName(_fromUtf8("lblElementsCountInfo"))
        self.horizontalLayout.addWidget(self.lblElementsCountInfo)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btnNext = QtGui.QPushButton(self.tabView)
        self.btnNext.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btnNext.setObjectName(_fromUtf8("btnNext"))
        self.horizontalLayout.addWidget(self.btnNext)
        self.btnEnd = QtGui.QPushButton(self.tabView)
        self.btnEnd.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btnEnd.setObjectName(_fromUtf8("btnEnd"))
        self.horizontalLayout.addWidget(self.btnEnd)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.btnReset = QtGui.QPushButton(self.tabView)
        self.btnReset.setObjectName(_fromUtf8("btnReset"))
        self.horizontalLayout.addWidget(self.btnReset)
        self.btnUpdate = QtGui.QPushButton(self.tabView)
        self.btnUpdate.setObjectName(_fromUtf8("btnUpdate"))
        self.horizontalLayout.addWidget(self.btnUpdate)
        self.gridLayout_9.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabView, _fromUtf8(""))
        self.tabFilters = QtGui.QWidget()
        self.tabFilters.setObjectName(_fromUtf8("tabFilters"))
        self.gridLayout = QtGui.QGridLayout(self.tabFilters)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gbFilters = QtGui.QGroupBox(self.tabFilters)
        self.gbFilters.setObjectName(_fromUtf8("gbFilters"))
        self.gridLayout_10 = QtGui.QGridLayout(self.gbFilters)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.tvFilterItem = CTableView(self.gbFilters)
        self.tvFilterItem.setObjectName(_fromUtf8("tvFilterItem"))
        self.gridLayout_10.addWidget(self.tvFilterItem, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gbFilters, 0, 0, 1, 1)
        self.gbView = QtGui.QGroupBox(self.tabFilters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbView.sizePolicy().hasHeightForWidth())
        self.gbView.setSizePolicy(sizePolicy)
        self.gbView.setObjectName(_fromUtf8("gbView"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gbView)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tvViewSettings = QtGui.QTreeView(self.gbView)
        self.tvViewSettings.setObjectName(_fromUtf8("tvViewSettings"))
        self.gridLayout_3.addWidget(self.tvViewSettings, 0, 0, 1, 2)
        self.cmbSavedSettings = QtGui.QComboBox(self.gbView)
        self.cmbSavedSettings.setEditable(True)
        self.cmbSavedSettings.setObjectName(_fromUtf8("cmbSavedSettings"))
        self.gridLayout_3.addWidget(self.cmbSavedSettings, 1, 0, 1, 2)
        self.btnSaveSettings = QtGui.QPushButton(self.gbView)
        self.btnSaveSettings.setObjectName(_fromUtf8("btnSaveSettings"))
        self.gridLayout_3.addWidget(self.btnSaveSettings, 2, 0, 1, 1)
        self.btnDelSettings = QtGui.QPushButton(self.gbView)
        self.btnDelSettings.setObjectName(_fromUtf8("btnDelSettings"))
        self.gridLayout_3.addWidget(self.btnDelSettings, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.gbView, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tabFilters, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(CustomizableRegistryWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CustomizableRegistryWidget)

    def retranslateUi(self, CustomizableRegistryWidget):
        CustomizableRegistryWidget.setWindowTitle(_translate("CustomizableRegistryWidget", "Form", None))
        self.btnBegin.setText(_translate("CustomizableRegistryWidget", "<<", None))
        self.btnPrevious.setText(_translate("CustomizableRegistryWidget", "<", None))
        self.lblSlashOfPage.setText(_translate("CustomizableRegistryWidget", "/", None))
        self.lblTotalPages.setText(_translate("CustomizableRegistryWidget", "1", None))
        self.lblPage.setText(_translate("CustomizableRegistryWidget", "Страница", None))
        self.lblElementsCountInfo.setText(_translate("CustomizableRegistryWidget", "(1 - 250 из 250)", None))
        self.btnNext.setText(_translate("CustomizableRegistryWidget", ">", None))
        self.btnEnd.setText(_translate("CustomizableRegistryWidget", ">>", None))
        self.btnReset.setText(_translate("CustomizableRegistryWidget", "Сбросить", None))
        self.btnUpdate.setText(_translate("CustomizableRegistryWidget", "Обновить", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabView), _translate("CustomizableRegistryWidget", "Картотека", None))
        self.gbFilters.setTitle(_translate("CustomizableRegistryWidget", "Фильтры", None))
        self.gbView.setTitle(_translate("CustomizableRegistryWidget", "Отображение", None))
        self.btnSaveSettings.setText(_translate("CustomizableRegistryWidget", "Сохранить", None))
        self.btnDelSettings.setText(_translate("CustomizableRegistryWidget", "Удалить", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFilters), _translate("CustomizableRegistryWidget", "Фильтры и отображение", None))

from library.TableView import CTableView
import s11main_rc
