# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\Registry\FreeQueueDockContent.ui'
#
# Created: Fri Jun 15 12:16:40 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(284, 741)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setMargin(2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblBegDate = QtGui.QLabel(Form)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.edtBegDate = CDateEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(31, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        self.chkEnableTime = QtGui.QCheckBox(Form)
        self.chkEnableTime.setObjectName(_fromUtf8("chkEnableTime"))
        self.gridLayout.addWidget(self.chkEnableTime, 1, 0, 1, 1)
        self.edtBegTime = QtGui.QTimeEdit(Form)
        self.edtBegTime.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegTime.sizePolicy().hasHeightForWidth())
        self.edtBegTime.setSizePolicy(sizePolicy)
        self.edtBegTime.setCalendarPopup(False)
        self.edtBegTime.setTime(QtCore.QTime(0, 0, 0))
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.gridLayout.addWidget(self.edtBegTime, 1, 1, 1, 1)
        self.lblEndTime = QtGui.QLabel(Form)
        self.lblEndTime.setObjectName(_fromUtf8("lblEndTime"))
        self.gridLayout.addWidget(self.lblEndTime, 1, 2, 1, 1)
        self.edtEndTime = QtGui.QTimeEdit(Form)
        self.edtEndTime.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndTime.sizePolicy().hasHeightForWidth())
        self.edtEndTime.setSizePolicy(sizePolicy)
        self.edtEndTime.setTime(QtCore.QTime(23, 59, 0))
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.gridLayout.addWidget(self.edtEndTime, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(74, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 5, 1, 2)
        self.grpBox = QtGui.QWidget(Form)
        self.grpBox.setObjectName(_fromUtf8("grpBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.grpBox)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(self.grpBox)
        self.splitter.setLineWidth(1)
        self.splitter.setMidLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(True)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.treeOrgStructure = CTreeView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.treeOrgStructure.sizePolicy().hasHeightForWidth())
        self.treeOrgStructure.setSizePolicy(sizePolicy)
        self.treeOrgStructure.setObjectName(_fromUtf8("treeOrgStructure"))
        self.treeOrgPersonnel = CTreeView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.treeOrgPersonnel.sizePolicy().hasHeightForWidth())
        self.treeOrgPersonnel.setSizePolicy(sizePolicy)
        self.treeOrgPersonnel.setObjectName(_fromUtf8("treeOrgPersonnel"))
        self.tblAmbQueue = CFreeQueueTableView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.tblAmbQueue.sizePolicy().hasHeightForWidth())
        self.tblAmbQueue.setSizePolicy(sizePolicy)
        self.tblAmbQueue.setObjectName(_fromUtf8("tblAmbQueue"))
        self.verticalLayout.addWidget(self.splitter)
        self.gridLayout.addWidget(self.grpBox, 2, 0, 1, 7)
        self.lblQueueItemsCount = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblQueueItemsCount.sizePolicy().hasHeightForWidth())
        self.lblQueueItemsCount.setSizePolicy(sizePolicy)
        self.lblQueueItemsCount.setScaledContents(False)
        self.lblQueueItemsCount.setObjectName(_fromUtf8("lblQueueItemsCount"))
        self.gridLayout.addWidget(self.lblQueueItemsCount, 3, 0, 1, 3)
        self.btnSetToday = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetToday.sizePolicy().hasHeightForWidth())
        self.btnSetToday.setSizePolicy(sizePolicy)
        self.btnSetToday.setFlat(False)
        self.btnSetToday.setObjectName(_fromUtf8("btnSetToday"))
        self.gridLayout.addWidget(self.btnSetToday, 0, 3, 1, 1)
        self.lblReservedOrder = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblReservedOrder.setFont(font)
        self.lblReservedOrder.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.lblReservedOrder.setText(_fromUtf8(""))
        self.lblReservedOrder.setObjectName(_fromUtf8("lblReservedOrder"))
        self.gridLayout.addWidget(self.lblReservedOrder, 3, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 6, 1, 1)
        self.edtCountTickets = QtGui.QSpinBox(Form)
        self.edtCountTickets.setMinimum(1)
        self.edtCountTickets.setMaximum(9)
        self.edtCountTickets.setObjectName(_fromUtf8("edtCountTickets"))
        self.gridLayout.addWidget(self.edtCountTickets, 1, 4, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 4, 1, 1)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndTime.setBuddy(self.edtEndTime)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.chkEnableTime, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtBegTime.setEnabled)
        QtCore.QObject.connect(self.chkEnableTime, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtEndTime.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.edtBegDate, self.chkEnableTime)
        Form.setTabOrder(self.chkEnableTime, self.edtBegTime)
        Form.setTabOrder(self.edtBegTime, self.edtEndTime)
        Form.setTabOrder(self.edtEndTime, self.treeOrgStructure)
        Form.setTabOrder(self.treeOrgStructure, self.treeOrgPersonnel)
        Form.setTabOrder(self.treeOrgPersonnel, self.tblAmbQueue)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBegDate.setText(QtGui.QApplication.translate("Form", "Дата", None, QtGui.QApplication.UnicodeUTF8))
        self.chkEnableTime.setText(QtGui.QApplication.translate("Form", "Время С", None, QtGui.QApplication.UnicodeUTF8))
        self.edtBegTime.setDisplayFormat(QtGui.QApplication.translate("Form", "HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndTime.setText(QtGui.QApplication.translate("Form", "&По", None, QtGui.QApplication.UnicodeUTF8))
        self.edtEndTime.setDisplayFormat(QtGui.QApplication.translate("Form", "HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.lblQueueItemsCount.setText(QtGui.QApplication.translate("Form", "Список пуст", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetToday.setText(QtGui.QApplication.translate("Form", "Сегодня", None, QtGui.QApplication.UnicodeUTF8))

from FreeQueueTableView import CFreeQueueTableView
from library.TreeView import CTreeView
from library.DateEdit import CDateEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

