# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\Registry\RegisterOfficeRegistry.ui'
#
# Created: Fri Jun 15 12:17:27 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1083, 979)
        self.gridLayout_19 = QtGui.QGridLayout(Form)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.tabMain = QtGui.QTabWidget(Form)
        self.tabMain.setEnabled(True)
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.tabRegistry = QtGui.QWidget()
        self.tabRegistry.setObjectName(_fromUtf8("tabRegistry"))
        self.gridlayout = QtGui.QGridLayout(self.tabRegistry)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.splitterRegistry = QtGui.QSplitter(self.tabRegistry)
        self.splitterRegistry.setOrientation(QtCore.Qt.Vertical)
        self.splitterRegistry.setChildrenCollapsible(False)
        self.splitterRegistry.setObjectName(_fromUtf8("splitterRegistry"))
        self.txtClientInfoBrowser = CTextBrowser(self.splitterRegistry)
        self.txtClientInfoBrowser.setMinimumSize(QtCore.QSize(0, 100))
        self.txtClientInfoBrowser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtClientInfoBrowser.setReadOnly(True)
        self.txtClientInfoBrowser.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.frameRegistry = QtGui.QFrame(self.splitterRegistry)
        self.frameRegistry.setFrameShadow(QtGui.QFrame.Raised)
        self.frameRegistry.setObjectName(_fromUtf8("frameRegistry"))
        self.gridLayout_20 = QtGui.QGridLayout(self.frameRegistry)
        self.gridLayout_20.setMargin(0)
        self.gridLayout_20.setSpacing(4)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.splitter_10 = QtGui.QSplitter(self.frameRegistry)
        self.splitter_10.setOrientation(QtCore.Qt.Vertical)
        self.splitter_10.setObjectName(_fromUtf8("splitter_10"))
        self.tblClients = CClientsTableView(self.splitter_10)
        self.tblClients.setObjectName(_fromUtf8("tblClients"))
        self.tabBeforeRecord = QtGui.QTabWidget(self.splitter_10)
        self.tabBeforeRecord.setObjectName(_fromUtf8("tabBeforeRecord"))
        self.tabBeforeRecordClient = QtGui.QWidget()
        self.tabBeforeRecordClient.setObjectName(_fromUtf8("tabBeforeRecordClient"))
        self.gridLayout_21 = QtGui.QGridLayout(self.tabBeforeRecordClient)
        self.gridLayout_21.setMargin(4)
        self.gridLayout_21.setSpacing(4)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.tblQueue = CTableView(self.tabBeforeRecordClient)
        self.tblQueue.setObjectName(_fromUtf8("tblQueue"))
        self.gridLayout_21.addWidget(self.tblQueue, 0, 0, 1, 1)
        self.tabBeforeRecord.addTab(self.tabBeforeRecordClient, _fromUtf8(""))
        self.tabVisitBeforeRecordClient = QtGui.QWidget()
        self.tabVisitBeforeRecordClient.setObjectName(_fromUtf8("tabVisitBeforeRecordClient"))
        self.gridLayout_22 = QtGui.QGridLayout(self.tabVisitBeforeRecordClient)
        self.gridLayout_22.setMargin(4)
        self.gridLayout_22.setSpacing(4)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.tblVisitByQueue = CTableView(self.tabVisitBeforeRecordClient)
        self.tblVisitByQueue.setObjectName(_fromUtf8("tblVisitByQueue"))
        self.gridLayout_22.addWidget(self.tblVisitByQueue, 0, 0, 1, 1)
        self.tabBeforeRecord.addTab(self.tabVisitBeforeRecordClient, _fromUtf8(""))
        self.gridLayout_20.addWidget(self.splitter_10, 0, 0, 1, 4)
        self.groupBox = QtGui.QGroupBox(self.frameRegistry)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(190, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(190, 16777215))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridlayout1 = QtGui.QGridLayout(self.groupBox)
        self.gridlayout1.setMargin(2)
        self.gridlayout1.setSpacing(2)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.buttonBox = QtGui.QDialogButtonBox(self.groupBox)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout1.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.tabFilter = QtGui.QTabWidget(self.groupBox)
        self.tabFilter.setTabPosition(QtGui.QTabWidget.North)
        self.tabFilter.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabFilter.setObjectName(_fromUtf8("tabFilter"))
        self.tabFind = QtGui.QWidget()
        self.tabFind.setObjectName(_fromUtf8("tabFind"))
        self.gridLayout_18 = QtGui.QGridLayout(self.tabFind)
        self.gridLayout_18.setMargin(1)
        self.gridLayout_18.setSpacing(1)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.chkFilterId = QtGui.QCheckBox(self.tabFind)
        self.chkFilterId.setObjectName(_fromUtf8("chkFilterId"))
        self.gridLayout_18.addWidget(self.chkFilterId, 0, 0, 1, 2)
        self.edtFilterId = QtGui.QLineEdit(self.tabFind)
        self.edtFilterId.setEnabled(False)
        self.edtFilterId.setMaxLength(16)
        self.edtFilterId.setObjectName(_fromUtf8("edtFilterId"))
        self.gridLayout_18.addWidget(self.edtFilterId, 2, 0, 1, 7)
        self.chkFilterLastName = QtGui.QCheckBox(self.tabFind)
        self.chkFilterLastName.setObjectName(_fromUtf8("chkFilterLastName"))
        self.gridLayout_18.addWidget(self.chkFilterLastName, 3, 0, 1, 7)
        self.edtFilterLastName = QtGui.QLineEdit(self.tabFind)
        self.edtFilterLastName.setEnabled(False)
        self.edtFilterLastName.setObjectName(_fromUtf8("edtFilterLastName"))
        self.gridLayout_18.addWidget(self.edtFilterLastName, 4, 0, 1, 7)
        self.chkFilterFirstName = QtGui.QCheckBox(self.tabFind)
        self.chkFilterFirstName.setObjectName(_fromUtf8("chkFilterFirstName"))
        self.gridLayout_18.addWidget(self.chkFilterFirstName, 5, 0, 1, 7)
        self.edtFilterFirstName = QtGui.QLineEdit(self.tabFind)
        self.edtFilterFirstName.setEnabled(False)
        self.edtFilterFirstName.setObjectName(_fromUtf8("edtFilterFirstName"))
        self.gridLayout_18.addWidget(self.edtFilterFirstName, 6, 0, 1, 7)
        self.chkFilterPatrName = QtGui.QCheckBox(self.tabFind)
        self.chkFilterPatrName.setObjectName(_fromUtf8("chkFilterPatrName"))
        self.gridLayout_18.addWidget(self.chkFilterPatrName, 7, 0, 1, 7)
        self.edtFilterPatrName = QtGui.QLineEdit(self.tabFind)
        self.edtFilterPatrName.setEnabled(False)
        self.edtFilterPatrName.setObjectName(_fromUtf8("edtFilterPatrName"))
        self.gridLayout_18.addWidget(self.edtFilterPatrName, 8, 0, 1, 7)
        self.chkFilterBirthDay = QtGui.QCheckBox(self.tabFind)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterBirthDay.sizePolicy().hasHeightForWidth())
        self.chkFilterBirthDay.setSizePolicy(sizePolicy)
        self.chkFilterBirthDay.setObjectName(_fromUtf8("chkFilterBirthDay"))
        self.gridLayout_18.addWidget(self.chkFilterBirthDay, 9, 0, 1, 3)
        self.edtFilterBirthDay = CDateEdit(self.tabFind)
        self.edtFilterBirthDay.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterBirthDay.sizePolicy().hasHeightForWidth())
        self.edtFilterBirthDay.setSizePolicy(sizePolicy)
        self.edtFilterBirthDay.setCalendarPopup(True)
        self.edtFilterBirthDay.setObjectName(_fromUtf8("edtFilterBirthDay"))
        self.gridLayout_18.addWidget(self.edtFilterBirthDay, 9, 3, 1, 4)
        self.chkFilterSex = QtGui.QCheckBox(self.tabFind)
        self.chkFilterSex.setObjectName(_fromUtf8("chkFilterSex"))
        self.gridLayout_18.addWidget(self.chkFilterSex, 10, 0, 1, 3)
        self.cmbFilterSex = QtGui.QComboBox(self.tabFind)
        self.cmbFilterSex.setEnabled(False)
        self.cmbFilterSex.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cmbFilterSex.setObjectName(_fromUtf8("cmbFilterSex"))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.cmbFilterSex.setItemText(0, _fromUtf8(""))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.gridLayout_18.addWidget(self.cmbFilterSex, 10, 3, 1, 2)
        spacerItem = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem, 10, 5, 1, 2)
        self.chkFilterSNILS = QtGui.QCheckBox(self.tabFind)
        self.chkFilterSNILS.setObjectName(_fromUtf8("chkFilterSNILS"))
        self.gridLayout_18.addWidget(self.chkFilterSNILS, 12, 0, 1, 3)
        self.chkFilterDocument = QtGui.QCheckBox(self.tabFind)
        self.chkFilterDocument.setObjectName(_fromUtf8("chkFilterDocument"))
        self.gridLayout_18.addWidget(self.chkFilterDocument, 15, 0, 1, 3)
        self.cmbFilterDocumentType = CRBComboBox(self.tabFind)
        self.cmbFilterDocumentType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterDocumentType.sizePolicy().hasHeightForWidth())
        self.cmbFilterDocumentType.setSizePolicy(sizePolicy)
        self.cmbFilterDocumentType.setMinimumSize(QtCore.QSize(100, 0))
        self.cmbFilterDocumentType.setObjectName(_fromUtf8("cmbFilterDocumentType"))
        self.gridLayout_18.addWidget(self.cmbFilterDocumentType, 15, 3, 1, 4)
        self.edtFilterDocumentSerial = QtGui.QLineEdit(self.tabFind)
        self.edtFilterDocumentSerial.setEnabled(False)
        self.edtFilterDocumentSerial.setObjectName(_fromUtf8("edtFilterDocumentSerial"))
        self.gridLayout_18.addWidget(self.edtFilterDocumentSerial, 16, 0, 1, 3)
        self.edtFilterDocumentNumber = QtGui.QLineEdit(self.tabFind)
        self.edtFilterDocumentNumber.setEnabled(False)
        self.edtFilterDocumentNumber.setObjectName(_fromUtf8("edtFilterDocumentNumber"))
        self.gridLayout_18.addWidget(self.edtFilterDocumentNumber, 16, 3, 1, 4)
        self.chkFilterPolicy = QtGui.QCheckBox(self.tabFind)
        self.chkFilterPolicy.setObjectName(_fromUtf8("chkFilterPolicy"))
        self.gridLayout_18.addWidget(self.chkFilterPolicy, 17, 0, 1, 7)
        self.cmbFilterPolicyInsurer = CInsurerComboBox(self.tabFind)
        self.cmbFilterPolicyInsurer.setEnabled(False)
        self.cmbFilterPolicyInsurer.setObjectName(_fromUtf8("cmbFilterPolicyInsurer"))
        self.gridLayout_18.addWidget(self.cmbFilterPolicyInsurer, 19, 0, 1, 7)
        self.edtFilterPolicySerial = CPolicySerialEdit(self.tabFind)
        self.edtFilterPolicySerial.setEnabled(False)
        self.edtFilterPolicySerial.setObjectName(_fromUtf8("edtFilterPolicySerial"))
        self.gridLayout_18.addWidget(self.edtFilterPolicySerial, 20, 0, 1, 3)
        self.edtFilterPolicyNumber = QtGui.QLineEdit(self.tabFind)
        self.edtFilterPolicyNumber.setEnabled(False)
        self.edtFilterPolicyNumber.setObjectName(_fromUtf8("edtFilterPolicyNumber"))
        self.gridLayout_18.addWidget(self.edtFilterPolicyNumber, 20, 3, 1, 4)
        self.chkFilterAddress = QtGui.QCheckBox(self.tabFind)
        self.chkFilterAddress.setObjectName(_fromUtf8("chkFilterAddress"))
        self.gridLayout_18.addWidget(self.chkFilterAddress, 21, 0, 1, 3)
        self.cmbFilterAddressType = QtGui.QComboBox(self.tabFind)
        self.cmbFilterAddressType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressType.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressType.setSizePolicy(sizePolicy)
        self.cmbFilterAddressType.setObjectName(_fromUtf8("cmbFilterAddressType"))
        self.cmbFilterAddressType.addItem(_fromUtf8(""))
        self.cmbFilterAddressType.addItem(_fromUtf8(""))
        self.gridLayout_18.addWidget(self.cmbFilterAddressType, 21, 3, 1, 4)
        self.cmbFilterAddressCity = CKLADRComboBox(self.tabFind)
        self.cmbFilterAddressCity.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressCity.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressCity.setSizePolicy(sizePolicy)
        self.cmbFilterAddressCity.setObjectName(_fromUtf8("cmbFilterAddressCity"))
        self.gridLayout_18.addWidget(self.cmbFilterAddressCity, 22, 0, 1, 7)
        self.cmbFilterAddressStreet = CStreetComboBox(self.tabFind)
        self.cmbFilterAddressStreet.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressStreet.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressStreet.setSizePolicy(sizePolicy)
        self.cmbFilterAddressStreet.setObjectName(_fromUtf8("cmbFilterAddressStreet"))
        self.gridLayout_18.addWidget(self.cmbFilterAddressStreet, 23, 0, 1, 7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lblFilterAddressHouse = QtGui.QLabel(self.tabFind)
        self.lblFilterAddressHouse.setEnabled(False)
        self.lblFilterAddressHouse.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblFilterAddressHouse.setObjectName(_fromUtf8("lblFilterAddressHouse"))
        self.horizontalLayout_5.addWidget(self.lblFilterAddressHouse)
        self.edtFilterAddressHouse = QtGui.QLineEdit(self.tabFind)
        self.edtFilterAddressHouse.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterAddressHouse.sizePolicy().hasHeightForWidth())
        self.edtFilterAddressHouse.setSizePolicy(sizePolicy)
        self.edtFilterAddressHouse.setObjectName(_fromUtf8("edtFilterAddressHouse"))
        self.horizontalLayout_5.addWidget(self.edtFilterAddressHouse)
        self.lblFilterAddressCorpus = QtGui.QLabel(self.tabFind)
        self.lblFilterAddressCorpus.setEnabled(False)
        self.lblFilterAddressCorpus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFilterAddressCorpus.setObjectName(_fromUtf8("lblFilterAddressCorpus"))
        self.horizontalLayout_5.addWidget(self.lblFilterAddressCorpus)
        self.edtFilterAddressCorpus = QtGui.QLineEdit(self.tabFind)
        self.edtFilterAddressCorpus.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterAddressCorpus.sizePolicy().hasHeightForWidth())
        self.edtFilterAddressCorpus.setSizePolicy(sizePolicy)
        self.edtFilterAddressCorpus.setObjectName(_fromUtf8("edtFilterAddressCorpus"))
        self.horizontalLayout_5.addWidget(self.edtFilterAddressCorpus)
        self.lblFilterAddressFlat = QtGui.QLabel(self.tabFind)
        self.lblFilterAddressFlat.setEnabled(False)
        self.lblFilterAddressFlat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFilterAddressFlat.setObjectName(_fromUtf8("lblFilterAddressFlat"))
        self.horizontalLayout_5.addWidget(self.lblFilterAddressFlat)
        self.edtFilterAddressFlat = QtGui.QLineEdit(self.tabFind)
        self.edtFilterAddressFlat.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterAddressFlat.sizePolicy().hasHeightForWidth())
        self.edtFilterAddressFlat.setSizePolicy(sizePolicy)
        self.edtFilterAddressFlat.setObjectName(_fromUtf8("edtFilterAddressFlat"))
        self.horizontalLayout_5.addWidget(self.edtFilterAddressFlat)
        self.gridLayout_18.addLayout(self.horizontalLayout_5, 24, 0, 1, 7)
        self.chkFilterWorkOrganisation = QtGui.QCheckBox(self.tabFind)
        self.chkFilterWorkOrganisation.setObjectName(_fromUtf8("chkFilterWorkOrganisation"))
        self.gridLayout_18.addWidget(self.chkFilterWorkOrganisation, 25, 0, 1, 6)
        self.cmbWorkOrganisation = COrgComboBox(self.tabFind)
        self.cmbWorkOrganisation.setEnabled(False)
        self.cmbWorkOrganisation.setObjectName(_fromUtf8("cmbWorkOrganisation"))
        self.gridLayout_18.addWidget(self.cmbWorkOrganisation, 26, 0, 1, 6)
        self.btnSelectWorkOrganisation = QtGui.QToolButton(self.tabFind)
        self.btnSelectWorkOrganisation.setEnabled(False)
        self.btnSelectWorkOrganisation.setObjectName(_fromUtf8("btnSelectWorkOrganisation"))
        self.gridLayout_18.addWidget(self.btnSelectWorkOrganisation, 26, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem1, 27, 0, 1, 1)
        self.edtFilterSNILS = QtGui.QLineEdit(self.tabFind)
        self.edtFilterSNILS.setEnabled(False)
        self.edtFilterSNILS.setObjectName(_fromUtf8("edtFilterSNILS"))
        self.gridLayout_18.addWidget(self.edtFilterSNILS, 12, 3, 1, 4)
        self.cmbFilterAccountingSystem = CRBComboBox(self.tabFind)
        self.cmbFilterAccountingSystem.setEnabled(False)
        self.cmbFilterAccountingSystem.setObjectName(_fromUtf8("cmbFilterAccountingSystem"))
        self.gridLayout_18.addWidget(self.cmbFilterAccountingSystem, 0, 2, 1, 5)
        self.edtFilterContact = QtGui.QLineEdit(self.tabFind)
        self.edtFilterContact.setEnabled(False)
        self.edtFilterContact.setObjectName(_fromUtf8("edtFilterContact"))
        self.gridLayout_18.addWidget(self.edtFilterContact, 11, 3, 1, 4)
        self.chkFilterContact = QtGui.QCheckBox(self.tabFind)
        self.chkFilterContact.setObjectName(_fromUtf8("chkFilterContact"))
        self.gridLayout_18.addWidget(self.chkFilterContact, 11, 0, 1, 3)
        self.cmbFilterPolicyType = CRBComboBox(self.tabFind)
        self.cmbFilterPolicyType.setEnabled(False)
        self.cmbFilterPolicyType.setObjectName(_fromUtf8("cmbFilterPolicyType"))
        self.gridLayout_18.addWidget(self.cmbFilterPolicyType, 18, 0, 1, 7)
        self.tabFilter.addTab(self.tabFind, _fromUtf8(""))
        self.tabFindEx = QtGui.QWidget()
        self.tabFindEx.setObjectName(_fromUtf8("tabFindEx"))
        self.gridLayout_17 = QtGui.QGridLayout(self.tabFindEx)
        self.gridLayout_17.setMargin(1)
        self.gridLayout_17.setSpacing(1)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.chkFilterCreatePerson = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterCreatePerson.setObjectName(_fromUtf8("chkFilterCreatePerson"))
        self.gridLayout_17.addWidget(self.chkFilterCreatePerson, 0, 0, 1, 4)
        self.cmbFilterCreatePerson = CPersonComboBoxEx(self.tabFindEx)
        self.cmbFilterCreatePerson.setEnabled(False)
        self.cmbFilterCreatePerson.setObjectName(_fromUtf8("cmbFilterCreatePerson"))
        self.gridLayout_17.addWidget(self.cmbFilterCreatePerson, 1, 0, 1, 4)
        self.chkFilterCreateDate = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterCreateDate.setObjectName(_fromUtf8("chkFilterCreateDate"))
        self.gridLayout_17.addWidget(self.chkFilterCreateDate, 2, 0, 1, 4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.edtFilterBegCreateDate = CDateEdit(self.tabFindEx)
        self.edtFilterBegCreateDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterBegCreateDate.sizePolicy().hasHeightForWidth())
        self.edtFilterBegCreateDate.setSizePolicy(sizePolicy)
        self.edtFilterBegCreateDate.setMinimumSize(QtCore.QSize(0, 0))
        self.edtFilterBegCreateDate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtFilterBegCreateDate.setCalendarPopup(True)
        self.edtFilterBegCreateDate.setObjectName(_fromUtf8("edtFilterBegCreateDate"))
        self.horizontalLayout_3.addWidget(self.edtFilterBegCreateDate)
        self.edtFilterEndCreateDate = CDateEdit(self.tabFindEx)
        self.edtFilterEndCreateDate.setEnabled(False)
        self.edtFilterEndCreateDate.setMinimumSize(QtCore.QSize(0, 0))
        self.edtFilterEndCreateDate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtFilterEndCreateDate.setCalendarPopup(True)
        self.edtFilterEndCreateDate.setObjectName(_fromUtf8("edtFilterEndCreateDate"))
        self.horizontalLayout_3.addWidget(self.edtFilterEndCreateDate)
        self.gridLayout_17.addLayout(self.horizontalLayout_3, 3, 0, 1, 4)
        self.chkFilterModifyPerson = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterModifyPerson.setObjectName(_fromUtf8("chkFilterModifyPerson"))
        self.gridLayout_17.addWidget(self.chkFilterModifyPerson, 4, 0, 1, 4)
        self.cmbFilterModifyPerson = CPersonComboBoxEx(self.tabFindEx)
        self.cmbFilterModifyPerson.setEnabled(False)
        self.cmbFilterModifyPerson.setObjectName(_fromUtf8("cmbFilterModifyPerson"))
        self.gridLayout_17.addWidget(self.cmbFilterModifyPerson, 5, 0, 1, 4)
        self.chkFilterModifyDate = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterModifyDate.setObjectName(_fromUtf8("chkFilterModifyDate"))
        self.gridLayout_17.addWidget(self.chkFilterModifyDate, 6, 0, 1, 4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.edtFilterBegModifyDate = CDateEdit(self.tabFindEx)
        self.edtFilterBegModifyDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterBegModifyDate.sizePolicy().hasHeightForWidth())
        self.edtFilterBegModifyDate.setSizePolicy(sizePolicy)
        self.edtFilterBegModifyDate.setMinimumSize(QtCore.QSize(0, 0))
        self.edtFilterBegModifyDate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtFilterBegModifyDate.setCalendarPopup(True)
        self.edtFilterBegModifyDate.setObjectName(_fromUtf8("edtFilterBegModifyDate"))
        self.horizontalLayout_2.addWidget(self.edtFilterBegModifyDate)
        self.edtFilterEndModifyDate = CDateEdit(self.tabFindEx)
        self.edtFilterEndModifyDate.setEnabled(False)
        self.edtFilterEndModifyDate.setMinimumSize(QtCore.QSize(0, 0))
        self.edtFilterEndModifyDate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtFilterEndModifyDate.setCalendarPopup(True)
        self.edtFilterEndModifyDate.setObjectName(_fromUtf8("edtFilterEndModifyDate"))
        self.horizontalLayout_2.addWidget(self.edtFilterEndModifyDate)
        self.gridLayout_17.addLayout(self.horizontalLayout_2, 7, 0, 1, 4)
        self.chkFilterAge = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterAge.setObjectName(_fromUtf8("chkFilterAge"))
        self.gridLayout_17.addWidget(self.chkFilterAge, 8, 0, 1, 1)
        self.edtFilterBegAge = QtGui.QSpinBox(self.tabFindEx)
        self.edtFilterBegAge.setEnabled(False)
        self.edtFilterBegAge.setMaximum(150)
        self.edtFilterBegAge.setObjectName(_fromUtf8("edtFilterBegAge"))
        self.gridLayout_17.addWidget(self.edtFilterBegAge, 8, 1, 1, 2)
        self.cmbFilterBegAge = QtGui.QComboBox(self.tabFindEx)
        self.cmbFilterBegAge.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterBegAge.sizePolicy().hasHeightForWidth())
        self.cmbFilterBegAge.setSizePolicy(sizePolicy)
        self.cmbFilterBegAge.setObjectName(_fromUtf8("cmbFilterBegAge"))
        self.cmbFilterBegAge.addItem(_fromUtf8(""))
        self.cmbFilterBegAge.addItem(_fromUtf8(""))
        self.cmbFilterBegAge.addItem(_fromUtf8(""))
        self.cmbFilterBegAge.addItem(_fromUtf8(""))
        self.gridLayout_17.addWidget(self.cmbFilterBegAge, 8, 3, 1, 1)
        self.edtFilterEndAge = QtGui.QSpinBox(self.tabFindEx)
        self.edtFilterEndAge.setEnabled(False)
        self.edtFilterEndAge.setMaximum(150)
        self.edtFilterEndAge.setProperty("value", 150)
        self.edtFilterEndAge.setObjectName(_fromUtf8("edtFilterEndAge"))
        self.gridLayout_17.addWidget(self.edtFilterEndAge, 9, 1, 1, 2)
        self.cmbFilterEndAge = QtGui.QComboBox(self.tabFindEx)
        self.cmbFilterEndAge.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterEndAge.sizePolicy().hasHeightForWidth())
        self.cmbFilterEndAge.setSizePolicy(sizePolicy)
        self.cmbFilterEndAge.setObjectName(_fromUtf8("cmbFilterEndAge"))
        self.cmbFilterEndAge.addItem(_fromUtf8(""))
        self.cmbFilterEndAge.addItem(_fromUtf8(""))
        self.cmbFilterEndAge.addItem(_fromUtf8(""))
        self.cmbFilterEndAge.addItem(_fromUtf8(""))
        self.gridLayout_17.addWidget(self.cmbFilterEndAge, 9, 3, 1, 1)
        self.chkFilterAddressOrgStructure = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterAddressOrgStructure.setObjectName(_fromUtf8("chkFilterAddressOrgStructure"))
        self.gridLayout_17.addWidget(self.chkFilterAddressOrgStructure, 10, 0, 1, 2)
        self.cmbFilterAddressOrgStructure = COrgStructureComboBox(self.tabFindEx)
        self.cmbFilterAddressOrgStructure.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressOrgStructure.setSizePolicy(sizePolicy)
        self.cmbFilterAddressOrgStructure.setObjectName(_fromUtf8("cmbFilterAddressOrgStructure"))
        self.gridLayout_17.addWidget(self.cmbFilterAddressOrgStructure, 12, 0, 1, 4)
        self.chkFilterAddressIsEmpty = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterAddressIsEmpty.setObjectName(_fromUtf8("chkFilterAddressIsEmpty"))
        self.gridLayout_17.addWidget(self.chkFilterAddressIsEmpty, 16, 0, 1, 4)
        self.chkFilterAttach = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterAttach.setObjectName(_fromUtf8("chkFilterAttach"))
        self.gridLayout_17.addWidget(self.chkFilterAttach, 19, 0, 1, 4)
        self.cmbFilterAttachOrganisation = CPolyclinicComboBox(self.tabFindEx)
        self.cmbFilterAttachOrganisation.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAttachOrganisation.sizePolicy().hasHeightForWidth())
        self.cmbFilterAttachOrganisation.setSizePolicy(sizePolicy)
        self.cmbFilterAttachOrganisation.setObjectName(_fromUtf8("cmbFilterAttachOrganisation"))
        self.gridLayout_17.addWidget(self.cmbFilterAttachOrganisation, 20, 0, 1, 4)
        self.chkFilterAttachNonBase = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterAttachNonBase.setObjectName(_fromUtf8("chkFilterAttachNonBase"))
        self.gridLayout_17.addWidget(self.chkFilterAttachNonBase, 21, 0, 1, 4)
        self.chkFilterTempInvalid = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterTempInvalid.setObjectName(_fromUtf8("chkFilterTempInvalid"))
        self.gridLayout_17.addWidget(self.chkFilterTempInvalid, 22, 0, 1, 4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.edtFilterBegTempInvalid = CDateEdit(self.tabFindEx)
        self.edtFilterBegTempInvalid.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterBegTempInvalid.sizePolicy().hasHeightForWidth())
        self.edtFilterBegTempInvalid.setSizePolicy(sizePolicy)
        self.edtFilterBegTempInvalid.setMinimumSize(QtCore.QSize(0, 0))
        self.edtFilterBegTempInvalid.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtFilterBegTempInvalid.setCalendarPopup(True)
        self.edtFilterBegTempInvalid.setObjectName(_fromUtf8("edtFilterBegTempInvalid"))
        self.horizontalLayout_4.addWidget(self.edtFilterBegTempInvalid)
        self.edtFilterEndTempInvalid = CDateEdit(self.tabFindEx)
        self.edtFilterEndTempInvalid.setEnabled(False)
        self.edtFilterEndTempInvalid.setMinimumSize(QtCore.QSize(0, 0))
        self.edtFilterEndTempInvalid.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtFilterEndTempInvalid.setCalendarPopup(True)
        self.edtFilterEndTempInvalid.setObjectName(_fromUtf8("edtFilterEndTempInvalid"))
        self.horizontalLayout_4.addWidget(self.edtFilterEndTempInvalid)
        self.gridLayout_17.addLayout(self.horizontalLayout_4, 23, 0, 1, 4)
        self.chkFilterRPFUnconfirmed = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterRPFUnconfirmed.setObjectName(_fromUtf8("chkFilterRPFUnconfirmed"))
        self.gridLayout_17.addWidget(self.chkFilterRPFUnconfirmed, 24, 0, 1, 4)
        self.chkFilterRPFConfirmed = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterRPFConfirmed.setObjectName(_fromUtf8("chkFilterRPFConfirmed"))
        self.gridLayout_17.addWidget(self.chkFilterRPFConfirmed, 25, 0, 1, 4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtFilterBegRPFConfirmed = CDateEdit(self.tabFindEx)
        self.edtFilterBegRPFConfirmed.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterBegRPFConfirmed.sizePolicy().hasHeightForWidth())
        self.edtFilterBegRPFConfirmed.setSizePolicy(sizePolicy)
        self.edtFilterBegRPFConfirmed.setMinimumSize(QtCore.QSize(0, 0))
        self.edtFilterBegRPFConfirmed.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtFilterBegRPFConfirmed.setCalendarPopup(True)
        self.edtFilterBegRPFConfirmed.setObjectName(_fromUtf8("edtFilterBegRPFConfirmed"))
        self.horizontalLayout.addWidget(self.edtFilterBegRPFConfirmed)
        self.edtFilterEndRPFConfirmed = CDateEdit(self.tabFindEx)
        self.edtFilterEndRPFConfirmed.setEnabled(False)
        self.edtFilterEndRPFConfirmed.setMinimumSize(QtCore.QSize(0, 0))
        self.edtFilterEndRPFConfirmed.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtFilterEndRPFConfirmed.setCalendarPopup(True)
        self.edtFilterEndRPFConfirmed.setObjectName(_fromUtf8("edtFilterEndRPFConfirmed"))
        self.horizontalLayout.addWidget(self.edtFilterEndRPFConfirmed)
        self.gridLayout_17.addLayout(self.horizontalLayout, 26, 0, 1, 4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem2, 27, 0, 1, 1)
        self.cmbFilterAddressOrgStructureType = QtGui.QComboBox(self.tabFindEx)
        self.cmbFilterAddressOrgStructureType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressOrgStructureType.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressOrgStructureType.setSizePolicy(sizePolicy)
        self.cmbFilterAddressOrgStructureType.setObjectName(_fromUtf8("cmbFilterAddressOrgStructureType"))
        self.cmbFilterAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbFilterAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbFilterAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbFilterAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbFilterAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbFilterAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbFilterAddressOrgStructureType.addItem(_fromUtf8(""))
        self.gridLayout_17.addWidget(self.cmbFilterAddressOrgStructureType, 11, 0, 1, 4)
        self.cmbFilterStatusBeds = QtGui.QComboBox(self.tabFindEx)
        self.cmbFilterStatusBeds.setEnabled(False)
        self.cmbFilterStatusBeds.setObjectName(_fromUtf8("cmbFilterStatusBeds"))
        self.cmbFilterStatusBeds.addItem(_fromUtf8(""))
        self.cmbFilterStatusBeds.addItem(_fromUtf8(""))
        self.cmbFilterStatusBeds.addItem(_fromUtf8(""))
        self.cmbFilterStatusBeds.addItem(_fromUtf8(""))
        self.gridLayout_17.addWidget(self.cmbFilterStatusBeds, 14, 0, 1, 4)
        self.cmbFilterOrgStructureBeds = COrgStructureComboBox(self.tabFindEx)
        self.cmbFilterOrgStructureBeds.setEnabled(False)
        self.cmbFilterOrgStructureBeds.setObjectName(_fromUtf8("cmbFilterOrgStructureBeds"))
        self.gridLayout_17.addWidget(self.cmbFilterOrgStructureBeds, 15, 0, 1, 4)
        self.chkFilterBeds = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterBeds.setObjectName(_fromUtf8("chkFilterBeds"))
        self.gridLayout_17.addWidget(self.chkFilterBeds, 13, 0, 1, 4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.chkFilterAttachType = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterAttachType.setObjectName(_fromUtf8("chkFilterAttachType"))
        self.horizontalLayout_6.addWidget(self.chkFilterAttachType)
        self.cmbFilterAttachTypeProperty = QtGui.QComboBox(self.tabFindEx)
        self.cmbFilterAttachTypeProperty.setEnabled(False)
        self.cmbFilterAttachTypeProperty.setObjectName(_fromUtf8("cmbFilterAttachTypeProperty"))
        self.horizontalLayout_6.addWidget(self.cmbFilterAttachTypeProperty)
        self.gridLayout_17.addLayout(self.horizontalLayout_6, 17, 0, 1, 4)
        self.cmbFilterAttachType = QtGui.QComboBox(self.tabFindEx)
        self.cmbFilterAttachType.setEnabled(False)
        self.cmbFilterAttachType.setObjectName(_fromUtf8("cmbFilterAttachType"))
        self.gridLayout_17.addWidget(self.cmbFilterAttachType, 18, 0, 1, 4)
        self.tabFilter.addTab(self.tabFindEx, _fromUtf8(""))
        self.gridlayout1.addWidget(self.tabFilter, 1, 0, 1, 1)
        self.gridLayout_20.addWidget(self.groupBox, 0, 4, 3, 1)
        self.lblClientsCount = QtGui.QLabel(self.frameRegistry)
        self.lblClientsCount.setObjectName(_fromUtf8("lblClientsCount"))
        self.gridLayout_20.addWidget(self.lblClientsCount, 1, 0, 1, 4)
        self.btnEdit = QtGui.QPushButton(self.frameRegistry)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEdit.sizePolicy().hasHeightForWidth())
        self.btnEdit.setSizePolicy(sizePolicy)
        self.btnEdit.setObjectName(_fromUtf8("btnEdit"))
        self.gridLayout_20.addWidget(self.btnEdit, 2, 0, 1, 1)
        self.btnPrint = QtGui.QPushButton(self.frameRegistry)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPrint.sizePolicy().hasHeightForWidth())
        self.btnPrint.setSizePolicy(sizePolicy)
        self.btnPrint.setObjectName(_fromUtf8("btnPrint"))
        self.gridLayout_20.addWidget(self.btnPrint, 2, 1, 1, 1)
        self.btnFilter = QtGui.QPushButton(self.frameRegistry)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFilter.sizePolicy().hasHeightForWidth())
        self.btnFilter.setSizePolicy(sizePolicy)
        self.btnFilter.setObjectName(_fromUtf8("btnFilter"))
        self.gridLayout_20.addWidget(self.btnFilter, 2, 2, 1, 1)
        self.btnNew = QtGui.QPushButton(self.frameRegistry)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNew.sizePolicy().hasHeightForWidth())
        self.btnNew.setSizePolicy(sizePolicy)
        self.btnNew.setObjectName(_fromUtf8("btnNew"))
        self.gridLayout_20.addWidget(self.btnNew, 2, 3, 1, 1)
        self.gridlayout.addWidget(self.splitterRegistry, 0, 0, 1, 1)
        self.tabMain.addTab(self.tabRegistry, _fromUtf8(""))
        self.gridLayout_19.addWidget(self.tabMain, 0, 0, 1, 1)
        self.lblFilterAddressHouse.setBuddy(self.edtFilterAddressHouse)
        self.lblFilterAddressCorpus.setBuddy(self.edtFilterAddressCorpus)
        self.lblFilterAddressFlat.setBuddy(self.edtFilterAddressFlat)

        self.retranslateUi(Form)
        self.tabMain.setCurrentIndex(0)
        self.tabBeforeRecord.setCurrentIndex(0)
        self.tabFilter.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tabMain, self.txtClientInfoBrowser)
        Form.setTabOrder(self.txtClientInfoBrowser, self.tblClients)
        Form.setTabOrder(self.tblClients, self.tabFilter)
        Form.setTabOrder(self.tabFilter, self.chkFilterId)
        Form.setTabOrder(self.chkFilterId, self.cmbFilterAccountingSystem)
        Form.setTabOrder(self.cmbFilterAccountingSystem, self.edtFilterId)
        Form.setTabOrder(self.edtFilterId, self.chkFilterLastName)
        Form.setTabOrder(self.chkFilterLastName, self.edtFilterLastName)
        Form.setTabOrder(self.edtFilterLastName, self.chkFilterFirstName)
        Form.setTabOrder(self.chkFilterFirstName, self.edtFilterFirstName)
        Form.setTabOrder(self.edtFilterFirstName, self.chkFilterPatrName)
        Form.setTabOrder(self.chkFilterPatrName, self.edtFilterPatrName)
        Form.setTabOrder(self.edtFilterPatrName, self.chkFilterBirthDay)
        Form.setTabOrder(self.chkFilterBirthDay, self.edtFilterBirthDay)
        Form.setTabOrder(self.edtFilterBirthDay, self.chkFilterSex)
        Form.setTabOrder(self.chkFilterSex, self.cmbFilterSex)
        Form.setTabOrder(self.cmbFilterSex, self.edtFilterContact)
        Form.setTabOrder(self.edtFilterContact, self.chkFilterContact)
        Form.setTabOrder(self.chkFilterContact, self.chkFilterSNILS)
        Form.setTabOrder(self.chkFilterSNILS, self.edtFilterSNILS)
        Form.setTabOrder(self.edtFilterSNILS, self.chkFilterDocument)
        Form.setTabOrder(self.chkFilterDocument, self.cmbFilterDocumentType)
        Form.setTabOrder(self.cmbFilterDocumentType, self.edtFilterDocumentSerial)
        Form.setTabOrder(self.edtFilterDocumentSerial, self.edtFilterDocumentNumber)
        Form.setTabOrder(self.edtFilterDocumentNumber, self.chkFilterPolicy)
        Form.setTabOrder(self.chkFilterPolicy, self.cmbFilterPolicyType)
        Form.setTabOrder(self.cmbFilterPolicyType, self.cmbFilterPolicyInsurer)
        Form.setTabOrder(self.cmbFilterPolicyInsurer, self.edtFilterPolicySerial)
        Form.setTabOrder(self.edtFilterPolicySerial, self.edtFilterPolicyNumber)
        Form.setTabOrder(self.edtFilterPolicyNumber, self.chkFilterAddress)
        Form.setTabOrder(self.chkFilterAddress, self.cmbFilterAddressType)
        Form.setTabOrder(self.cmbFilterAddressType, self.cmbFilterAddressCity)
        Form.setTabOrder(self.cmbFilterAddressCity, self.cmbFilterAddressStreet)
        Form.setTabOrder(self.cmbFilterAddressStreet, self.edtFilterAddressHouse)
        Form.setTabOrder(self.edtFilterAddressHouse, self.edtFilterAddressCorpus)
        Form.setTabOrder(self.edtFilterAddressCorpus, self.edtFilterAddressFlat)
        Form.setTabOrder(self.edtFilterAddressFlat, self.chkFilterWorkOrganisation)
        Form.setTabOrder(self.chkFilterWorkOrganisation, self.cmbWorkOrganisation)
        Form.setTabOrder(self.cmbWorkOrganisation, self.btnSelectWorkOrganisation)
        Form.setTabOrder(self.btnSelectWorkOrganisation, self.chkFilterCreatePerson)
        Form.setTabOrder(self.chkFilterCreatePerson, self.cmbFilterCreatePerson)
        Form.setTabOrder(self.cmbFilterCreatePerson, self.chkFilterCreateDate)
        Form.setTabOrder(self.chkFilterCreateDate, self.edtFilterBegCreateDate)
        Form.setTabOrder(self.edtFilterBegCreateDate, self.edtFilterEndCreateDate)
        Form.setTabOrder(self.edtFilterEndCreateDate, self.chkFilterModifyPerson)
        Form.setTabOrder(self.chkFilterModifyPerson, self.cmbFilterModifyPerson)
        Form.setTabOrder(self.cmbFilterModifyPerson, self.chkFilterModifyDate)
        Form.setTabOrder(self.chkFilterModifyDate, self.edtFilterBegModifyDate)
        Form.setTabOrder(self.edtFilterBegModifyDate, self.edtFilterEndModifyDate)
        Form.setTabOrder(self.edtFilterEndModifyDate, self.chkFilterAge)
        Form.setTabOrder(self.chkFilterAge, self.edtFilterBegAge)
        Form.setTabOrder(self.edtFilterBegAge, self.cmbFilterBegAge)
        Form.setTabOrder(self.cmbFilterBegAge, self.edtFilterEndAge)
        Form.setTabOrder(self.edtFilterEndAge, self.cmbFilterEndAge)
        Form.setTabOrder(self.cmbFilterEndAge, self.chkFilterAddressOrgStructure)
        Form.setTabOrder(self.chkFilterAddressOrgStructure, self.cmbFilterAddressOrgStructureType)
        Form.setTabOrder(self.cmbFilterAddressOrgStructureType, self.cmbFilterAddressOrgStructure)
        Form.setTabOrder(self.cmbFilterAddressOrgStructure, self.chkFilterBeds)
        Form.setTabOrder(self.chkFilterBeds, self.cmbFilterStatusBeds)
        Form.setTabOrder(self.cmbFilterStatusBeds, self.cmbFilterOrgStructureBeds)
        Form.setTabOrder(self.cmbFilterOrgStructureBeds, self.chkFilterAddressIsEmpty)
        Form.setTabOrder(self.chkFilterAddressIsEmpty, self.chkFilterAttach)
        Form.setTabOrder(self.chkFilterAttach, self.cmbFilterAttachOrganisation)
        Form.setTabOrder(self.cmbFilterAttachOrganisation, self.chkFilterAttachNonBase)
        Form.setTabOrder(self.chkFilterAttachNonBase, self.chkFilterTempInvalid)
        Form.setTabOrder(self.chkFilterTempInvalid, self.edtFilterBegTempInvalid)
        Form.setTabOrder(self.edtFilterBegTempInvalid, self.edtFilterEndTempInvalid)
        Form.setTabOrder(self.edtFilterEndTempInvalid, self.chkFilterRPFUnconfirmed)
        Form.setTabOrder(self.chkFilterRPFUnconfirmed, self.chkFilterRPFConfirmed)
        Form.setTabOrder(self.chkFilterRPFConfirmed, self.edtFilterBegRPFConfirmed)
        Form.setTabOrder(self.edtFilterBegRPFConfirmed, self.edtFilterEndRPFConfirmed)
        Form.setTabOrder(self.edtFilterEndRPFConfirmed, self.buttonBox)
        Form.setTabOrder(self.buttonBox, self.btnEdit)
        Form.setTabOrder(self.btnEdit, self.btnPrint)
        Form.setTabOrder(self.btnPrint, self.btnFilter)
        Form.setTabOrder(self.btnFilter, self.btnNew)
        Form.setTabOrder(self.btnNew, self.tabBeforeRecord)
        Form.setTabOrder(self.tabBeforeRecord, self.tblQueue)
        Form.setTabOrder(self.tblQueue, self.tblVisitByQueue)
        Form.setTabOrder(self.tblVisitByQueue, self.chkFilterAttachType)
        Form.setTabOrder(self.chkFilterAttachType, self.cmbFilterAttachTypeProperty)
        Form.setTabOrder(self.cmbFilterAttachTypeProperty, self.cmbFilterAttachType)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.txtClientInfoBrowser.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Tahoma\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabBeforeRecord.setTabText(self.tabBeforeRecord.indexOf(self.tabBeforeRecordClient), QtGui.QApplication.translate("Form", "Предварительная запись", None, QtGui.QApplication.UnicodeUTF8))
        self.tabBeforeRecord.setTabText(self.tabBeforeRecord.indexOf(self.tabVisitBeforeRecordClient), QtGui.QApplication.translate("Form", "Выполнение записи", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Фильтр", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterId.setText(QtGui.QApplication.translate("Form", "Код", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterLastName.setText(QtGui.QApplication.translate("Form", "Фамилия", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterFirstName.setText(QtGui.QApplication.translate("Form", "Имя", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterPatrName.setText(QtGui.QApplication.translate("Form", "Отчество", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterBirthDay.setText(QtGui.QApplication.translate("Form", "Дата рожд", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterSex.setText(QtGui.QApplication.translate("Form", "Пол", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterSex.setItemText(1, QtGui.QApplication.translate("Form", "М", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterSex.setItemText(2, QtGui.QApplication.translate("Form", "Ж", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterSNILS.setText(QtGui.QApplication.translate("Form", "СНИЛС", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterDocument.setText(QtGui.QApplication.translate("Form", "Документ", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterPolicy.setText(QtGui.QApplication.translate("Form", "Полис", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterAddress.setText(QtGui.QApplication.translate("Form", "Адрес", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterAddressType.setItemText(0, QtGui.QApplication.translate("Form", "Регистрации", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterAddressType.setItemText(1, QtGui.QApplication.translate("Form", "Проживания", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFilterAddressHouse.setText(QtGui.QApplication.translate("Form", "Дом", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFilterAddressCorpus.setText(QtGui.QApplication.translate("Form", "Корп", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFilterAddressFlat.setText(QtGui.QApplication.translate("Form", "Кв", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterWorkOrganisation.setText(QtGui.QApplication.translate("Form", "Занятость", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelectWorkOrganisation.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.edtFilterSNILS.setInputMask(QtGui.QApplication.translate("Form", "999-999-999 99; ", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterContact.setText(QtGui.QApplication.translate("Form", "Контакт", None, QtGui.QApplication.UnicodeUTF8))
        self.tabFilter.setTabText(self.tabFilter.indexOf(self.tabFind), QtGui.QApplication.translate("Form", "&Поиск", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterCreatePerson.setText(QtGui.QApplication.translate("Form", "Автор", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterCreateDate.setText(QtGui.QApplication.translate("Form", "Дата создания", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterModifyPerson.setText(QtGui.QApplication.translate("Form", "Автор последнего изменения", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterModifyDate.setText(QtGui.QApplication.translate("Form", "Дата последнего изменения", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterAge.setText(QtGui.QApplication.translate("Form", "Возраст", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterBegAge.setItemText(0, QtGui.QApplication.translate("Form", "Лет", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterBegAge.setItemText(1, QtGui.QApplication.translate("Form", "Мес", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterBegAge.setItemText(2, QtGui.QApplication.translate("Form", "Нед", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterBegAge.setItemText(3, QtGui.QApplication.translate("Form", "Дней", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterEndAge.setItemText(0, QtGui.QApplication.translate("Form", "Лет", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterEndAge.setItemText(1, QtGui.QApplication.translate("Form", "Мес", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterEndAge.setItemText(2, QtGui.QApplication.translate("Form", "Нед", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterEndAge.setItemText(3, QtGui.QApplication.translate("Form", "Дней", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterAddressOrgStructure.setText(QtGui.QApplication.translate("Form", "По участку", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterAddressIsEmpty.setText(QtGui.QApplication.translate("Form", "Адрес пуст", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterAttach.setText(QtGui.QApplication.translate("Form", "Прикрепление к ЛПУ", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterAttachNonBase.setText(QtGui.QApplication.translate("Form", "Любое ЛПУ кроме базового", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterTempInvalid.setText(QtGui.QApplication.translate("Form", "Период ВУТ", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterRPFUnconfirmed.setText(QtGui.QApplication.translate("Form", "Неподтверждённые РПФ", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterRPFConfirmed.setText(QtGui.QApplication.translate("Form", "Период подтверждения РПФ", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterAddressOrgStructureType.setItemText(0, QtGui.QApplication.translate("Form", "Регистрация", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterAddressOrgStructureType.setItemText(1, QtGui.QApplication.translate("Form", "Проживание", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterAddressOrgStructureType.setItemText(2, QtGui.QApplication.translate("Form", "Регистрация или проживание", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterAddressOrgStructureType.setItemText(3, QtGui.QApplication.translate("Form", "Прикрепление", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterAddressOrgStructureType.setItemText(4, QtGui.QApplication.translate("Form", "Регистрация или прикрепление", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterAddressOrgStructureType.setItemText(5, QtGui.QApplication.translate("Form", "Проживание или прикрепление", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterAddressOrgStructureType.setItemText(6, QtGui.QApplication.translate("Form", "Регистрация, проживание или прикрепление", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterStatusBeds.setItemText(0, QtGui.QApplication.translate("Form", "не задано", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterStatusBeds.setItemText(1, QtGui.QApplication.translate("Form", "на лечении", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterStatusBeds.setItemText(2, QtGui.QApplication.translate("Form", "на выписке", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterStatusBeds.setItemText(3, QtGui.QApplication.translate("Form", "в очереди", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterBeds.setText(QtGui.QApplication.translate("Form", "По койкам", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterAttachType.setText(QtGui.QApplication.translate("Form", "Прикрепление", None, QtGui.QApplication.UnicodeUTF8))
        self.tabFilter.setTabText(self.tabFilter.indexOf(self.tabFindEx), QtGui.QApplication.translate("Form", "&Расширенный поиск", None, QtGui.QApplication.UnicodeUTF8))
        self.lblClientsCount.setText(QtGui.QApplication.translate("Form", "Список пуст", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEdit.setText(QtGui.QApplication.translate("Form", "Редактировать (F4)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEdit.setShortcut(QtGui.QApplication.translate("Form", "F4", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPrint.setText(QtGui.QApplication.translate("Form", "Печать (F6)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFilter.setText(QtGui.QApplication.translate("Form", "Фильтр (F7)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFilter.setShortcut(QtGui.QApplication.translate("Form", "F7", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNew.setText(QtGui.QApplication.translate("Form", "Регистрация (F9)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNew.setShortcut(QtGui.QApplication.translate("Form", "F9", None, QtGui.QApplication.UnicodeUTF8))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabRegistry), QtGui.QApplication.translate("Form", "&Картотека", None, QtGui.QApplication.UnicodeUTF8))

from Orgs.OrgComboBox import CPolyclinicComboBox, COrgComboBox, CInsurerComboBox
from library.crbcombobox import CRBComboBox
from Registry.RegistryTable import CClientsTableView
from KLADR.kladrComboxes import CKLADRComboBox, CStreetComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.TextBrowser import CTextBrowser
from library.TableView import CTableView
from PolicySerialEdit import CPolicySerialEdit
from library.DateEdit import CDateEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

