# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\Stock\Invoice.ui'
#
# Created: Fri Jun 15 12:17:09 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_InvoiceDialog(object):
    def setupUi(self, InvoiceDialog):
        InvoiceDialog.setObjectName(_fromUtf8("InvoiceDialog"))
        InvoiceDialog.resize(542, 452)
        self.gridLayout = QtGui.QGridLayout(InvoiceDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblDate = QtGui.QLabel(InvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDate.sizePolicy().hasHeightForWidth())
        self.lblDate.setSizePolicy(sizePolicy)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout.addWidget(self.lblDate, 0, 0, 1, 1)
        self.edtDate = CDateEdit(InvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDate.sizePolicy().hasHeightForWidth())
        self.edtDate.setSizePolicy(sizePolicy)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.gridLayout.addWidget(self.edtDate, 0, 1, 1, 1)
        self.edtTime = QtGui.QTimeEdit(InvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTime.sizePolicy().hasHeightForWidth())
        self.edtTime.setSizePolicy(sizePolicy)
        self.edtTime.setObjectName(_fromUtf8("edtTime"))
        self.gridLayout.addWidget(self.edtTime, 0, 2, 1, 1)
        self.lblSupplier = QtGui.QLabel(InvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSupplier.sizePolicy().hasHeightForWidth())
        self.lblSupplier.setSizePolicy(sizePolicy)
        self.lblSupplier.setObjectName(_fromUtf8("lblSupplier"))
        self.gridLayout.addWidget(self.lblSupplier, 1, 0, 1, 1)
        self.cmbSupplier = CStorageComboBox(InvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSupplier.sizePolicy().hasHeightForWidth())
        self.cmbSupplier.setSizePolicy(sizePolicy)
        self.cmbSupplier.setObjectName(_fromUtf8("cmbSupplier"))
        self.gridLayout.addWidget(self.cmbSupplier, 1, 1, 1, 3)
        self.lblReceiver = QtGui.QLabel(InvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblReceiver.sizePolicy().hasHeightForWidth())
        self.lblReceiver.setSizePolicy(sizePolicy)
        self.lblReceiver.setObjectName(_fromUtf8("lblReceiver"))
        self.gridLayout.addWidget(self.lblReceiver, 3, 0, 1, 1)
        self.cmbReceiver = CStorageComboBox(InvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReceiver.sizePolicy().hasHeightForWidth())
        self.cmbReceiver.setSizePolicy(sizePolicy)
        self.cmbReceiver.setObjectName(_fromUtf8("cmbReceiver"))
        self.gridLayout.addWidget(self.cmbReceiver, 3, 1, 1, 3)
        self.lblNote = QtGui.QLabel(InvoiceDialog)
        self.lblNote.setObjectName(_fromUtf8("lblNote"))
        self.gridLayout.addWidget(self.lblNote, 5, 0, 1, 1)
        self.edtNote = QtGui.QLineEdit(InvoiceDialog)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout.addWidget(self.edtNote, 5, 1, 1, 3)
        self.tblItems = CInDocTableView(InvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblItems.sizePolicy().hasHeightForWidth())
        self.tblItems.setSizePolicy(sizePolicy)
        self.tblItems.setObjectName(_fromUtf8("tblItems"))
        self.gridLayout.addWidget(self.tblItems, 6, 0, 1, 4)
        self.buttonBox = QtGui.QDialogButtonBox(InvoiceDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 7, 0, 1, 4)
        self.lblSupplierPerson = QtGui.QLabel(InvoiceDialog)
        self.lblSupplierPerson.setObjectName(_fromUtf8("lblSupplierPerson"))
        self.gridLayout.addWidget(self.lblSupplierPerson, 2, 0, 1, 1)
        self.cmbSupplierPerson = CPersonComboBoxEx(InvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSupplierPerson.sizePolicy().hasHeightForWidth())
        self.cmbSupplierPerson.setSizePolicy(sizePolicy)
        self.cmbSupplierPerson.setObjectName(_fromUtf8("cmbSupplierPerson"))
        self.gridLayout.addWidget(self.cmbSupplierPerson, 2, 1, 1, 3)
        self.cmbReceiverPerson = CPersonComboBoxEx(InvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReceiverPerson.sizePolicy().hasHeightForWidth())
        self.cmbReceiverPerson.setSizePolicy(sizePolicy)
        self.cmbReceiverPerson.setObjectName(_fromUtf8("cmbReceiverPerson"))
        self.gridLayout.addWidget(self.cmbReceiverPerson, 4, 1, 1, 3)
        self.lblReceiverPerson = QtGui.QLabel(InvoiceDialog)
        self.lblReceiverPerson.setObjectName(_fromUtf8("lblReceiverPerson"))
        self.gridLayout.addWidget(self.lblReceiverPerson, 4, 0, 1, 1)
        self.lblDate.setBuddy(self.edtDate)
        self.lblSupplier.setBuddy(self.cmbSupplier)
        self.lblReceiver.setBuddy(self.cmbReceiver)
        self.lblNote.setBuddy(self.edtNote)
        self.lblSupplierPerson.setBuddy(self.cmbSupplierPerson)
        self.lblReceiverPerson.setBuddy(self.cmbReceiverPerson)

        self.retranslateUi(InvoiceDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), InvoiceDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), InvoiceDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(InvoiceDialog)
        InvoiceDialog.setTabOrder(self.edtDate, self.edtTime)
        InvoiceDialog.setTabOrder(self.edtTime, self.cmbSupplier)
        InvoiceDialog.setTabOrder(self.cmbSupplier, self.cmbSupplierPerson)
        InvoiceDialog.setTabOrder(self.cmbSupplierPerson, self.cmbReceiver)
        InvoiceDialog.setTabOrder(self.cmbReceiver, self.cmbReceiverPerson)
        InvoiceDialog.setTabOrder(self.cmbReceiverPerson, self.edtNote)
        InvoiceDialog.setTabOrder(self.edtNote, self.tblItems)
        InvoiceDialog.setTabOrder(self.tblItems, self.buttonBox)

    def retranslateUi(self, InvoiceDialog):
        InvoiceDialog.setWindowTitle(QtGui.QApplication.translate("InvoiceDialog", "Накладная на передачу ЛСиИМН", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDate.setText(QtGui.QApplication.translate("InvoiceDialog", "Дата", None, QtGui.QApplication.UnicodeUTF8))
        self.edtTime.setDisplayFormat(QtGui.QApplication.translate("InvoiceDialog", "HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSupplier.setText(QtGui.QApplication.translate("InvoiceDialog", "Поставщик", None, QtGui.QApplication.UnicodeUTF8))
        self.lblReceiver.setText(QtGui.QApplication.translate("InvoiceDialog", "Получатель", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNote.setText(QtGui.QApplication.translate("InvoiceDialog", "Примечания", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSupplierPerson.setText(QtGui.QApplication.translate("InvoiceDialog", "Ответственный", None, QtGui.QApplication.UnicodeUTF8))
        self.lblReceiverPerson.setText(QtGui.QApplication.translate("InvoiceDialog", "Ответственный", None, QtGui.QApplication.UnicodeUTF8))

from library.InDocTable import CInDocTableView
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from Orgs.OrgStructComboBoxes import CStorageComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    InvoiceDialog = QtGui.QDialog()
    ui = Ui_InvoiceDialog()
    ui.setupUi(InvoiceDialog)
    InvoiceDialog.show()
    sys.exit(app.exec_())

