# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\Stock\NomenclatureComboBoxPopup.ui'
#
# Created: Fri Jun 15 12:17:20 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_NomenclatureComboBoxPopup(object):
    def setupUi(self, NomenclatureComboBoxPopup):
        NomenclatureComboBoxPopup.setObjectName(_fromUtf8("NomenclatureComboBoxPopup"))
        NomenclatureComboBoxPopup.resize(400, 251)
        self.gridlayout = QtGui.QGridLayout(NomenclatureComboBoxPopup)
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(0)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.tabWidget = QtGui.QTabWidget(NomenclatureComboBoxPopup)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabNomenclature = QtGui.QWidget()
        self.tabNomenclature.setObjectName(_fromUtf8("tabNomenclature"))
        self.vboxlayout = QtGui.QVBoxLayout(self.tabNomenclature)
        self.vboxlayout.setSpacing(4)
        self.vboxlayout.setMargin(4)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.tblNomenclature = CTableView(self.tabNomenclature)
        self.tblNomenclature.setObjectName(_fromUtf8("tblNomenclature"))
        self.vboxlayout.addWidget(self.tblNomenclature)
        self.tabWidget.addTab(self.tabNomenclature, _fromUtf8(""))
        self.tabSearch = QtGui.QWidget()
        self.tabSearch.setObjectName(_fromUtf8("tabSearch"))
        self.gridLayout = QtGui.QGridLayout(self.tabSearch)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblClass = QtGui.QLabel(self.tabSearch)
        self.lblClass.setObjectName(_fromUtf8("lblClass"))
        self.gridLayout.addWidget(self.lblClass, 0, 0, 1, 1)
        self.cmbClass = CRBComboBox(self.tabSearch)
        self.cmbClass.setObjectName(_fromUtf8("cmbClass"))
        self.gridLayout.addWidget(self.cmbClass, 0, 1, 1, 2)
        self.lblKind = QtGui.QLabel(self.tabSearch)
        self.lblKind.setObjectName(_fromUtf8("lblKind"))
        self.gridLayout.addWidget(self.lblKind, 1, 0, 1, 1)
        self.cmbKind = CRBComboBox(self.tabSearch)
        self.cmbKind.setObjectName(_fromUtf8("cmbKind"))
        self.gridLayout.addWidget(self.cmbKind, 1, 1, 1, 2)
        self.lblType = QtGui.QLabel(self.tabSearch)
        self.lblType.setObjectName(_fromUtf8("lblType"))
        self.gridLayout.addWidget(self.lblType, 2, 0, 1, 1)
        self.cmbType = CRBComboBox(self.tabSearch)
        self.cmbType.setObjectName(_fromUtf8("cmbType"))
        self.gridLayout.addWidget(self.cmbType, 2, 1, 1, 2)
        self.lblCode = QtGui.QLabel(self.tabSearch)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout.addWidget(self.lblCode, 3, 0, 1, 1)
        self.edtCode = QtGui.QLineEdit(self.tabSearch)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout.addWidget(self.edtCode, 3, 1, 1, 2)
        self.lblName = QtGui.QLabel(self.tabSearch)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 4, 0, 1, 1)
        self.edtName = QtGui.QLineEdit(self.tabSearch)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 4, 1, 1, 2)
        self.chkIncludeAnalogies = QtGui.QCheckBox(self.tabSearch)
        self.chkIncludeAnalogies.setObjectName(_fromUtf8("chkIncludeAnalogies"))
        self.gridLayout.addWidget(self.chkIncludeAnalogies, 7, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(178, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 9, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 9, 2, 1, 1)
        self.edtProducer = QtGui.QLineEdit(self.tabSearch)
        self.edtProducer.setObjectName(_fromUtf8("edtProducer"))
        self.gridLayout.addWidget(self.edtProducer, 5, 1, 1, 2)
        self.lblProducer = QtGui.QLabel(self.tabSearch)
        self.lblProducer.setObjectName(_fromUtf8("lblProducer"))
        self.gridLayout.addWidget(self.lblProducer, 5, 0, 1, 1)
        self.lblATC = QtGui.QLabel(self.tabSearch)
        self.lblATC.setObjectName(_fromUtf8("lblATC"))
        self.gridLayout.addWidget(self.lblATC, 6, 0, 1, 1)
        self.edtATC = QtGui.QLineEdit(self.tabSearch)
        self.edtATC.setObjectName(_fromUtf8("edtATC"))
        self.gridLayout.addWidget(self.edtATC, 6, 1, 1, 2)
        self.tabWidget.addTab(self.tabSearch, _fromUtf8(""))
        self.gridlayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.lblClass.setBuddy(self.cmbClass)
        self.lblKind.setBuddy(self.cmbKind)
        self.lblType.setBuddy(self.cmbType)
        self.lblCode.setBuddy(self.edtCode)
        self.lblName.setBuddy(self.edtName)
        self.lblProducer.setBuddy(self.edtProducer)
        self.lblATC.setBuddy(self.edtATC)

        self.retranslateUi(NomenclatureComboBoxPopup)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NomenclatureComboBoxPopup)
        NomenclatureComboBoxPopup.setTabOrder(self.tabWidget, self.tblNomenclature)
        NomenclatureComboBoxPopup.setTabOrder(self.tblNomenclature, self.cmbClass)
        NomenclatureComboBoxPopup.setTabOrder(self.cmbClass, self.cmbKind)
        NomenclatureComboBoxPopup.setTabOrder(self.cmbKind, self.cmbType)
        NomenclatureComboBoxPopup.setTabOrder(self.cmbType, self.edtCode)
        NomenclatureComboBoxPopup.setTabOrder(self.edtCode, self.edtName)
        NomenclatureComboBoxPopup.setTabOrder(self.edtName, self.edtProducer)
        NomenclatureComboBoxPopup.setTabOrder(self.edtProducer, self.edtATC)
        NomenclatureComboBoxPopup.setTabOrder(self.edtATC, self.chkIncludeAnalogies)
        NomenclatureComboBoxPopup.setTabOrder(self.chkIncludeAnalogies, self.buttonBox)

    def retranslateUi(self, NomenclatureComboBoxPopup):
        NomenclatureComboBoxPopup.setWindowTitle(QtGui.QApplication.translate("NomenclatureComboBoxPopup", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNomenclature), QtGui.QApplication.translate("NomenclatureComboBoxPopup", "&Номенклатура", None, QtGui.QApplication.UnicodeUTF8))
        self.lblClass.setText(QtGui.QApplication.translate("NomenclatureComboBoxPopup", "&Класс", None, QtGui.QApplication.UnicodeUTF8))
        self.lblKind.setText(QtGui.QApplication.translate("NomenclatureComboBoxPopup", "&Вид", None, QtGui.QApplication.UnicodeUTF8))
        self.lblType.setText(QtGui.QApplication.translate("NomenclatureComboBoxPopup", "&Тип", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCode.setText(QtGui.QApplication.translate("NomenclatureComboBoxPopup", "&Код", None, QtGui.QApplication.UnicodeUTF8))
        self.lblName.setText(QtGui.QApplication.translate("NomenclatureComboBoxPopup", "&Наименование", None, QtGui.QApplication.UnicodeUTF8))
        self.chkIncludeAnalogies.setText(QtGui.QApplication.translate("NomenclatureComboBoxPopup", "Включая аналоги", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProducer.setText(QtGui.QApplication.translate("NomenclatureComboBoxPopup", "&Производитель", None, QtGui.QApplication.UnicodeUTF8))
        self.lblATC.setText(QtGui.QApplication.translate("NomenclatureComboBoxPopup", "Код &АТХ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), QtGui.QApplication.translate("NomenclatureComboBoxPopup", "&Поиск", None, QtGui.QApplication.UnicodeUTF8))

from library.crbcombobox import CRBComboBox
from library.TableView import CTableView

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    NomenclatureComboBoxPopup = QtGui.QWidget()
    ui = Ui_NomenclatureComboBoxPopup()
    ui.setupUi(NomenclatureComboBoxPopup)
    NomenclatureComboBoxPopup.show()
    sys.exit(app.exec_())

