# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\Stock\Production.ui'
#
# Created: Fri Jun 15 12:17:09 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ProductionDialog(object):
    def setupUi(self, ProductionDialog):
        ProductionDialog.setObjectName(_fromUtf8("ProductionDialog"))
        ProductionDialog.resize(546, 477)
        self.gridLayout = QtGui.QGridLayout(ProductionDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblDate = QtGui.QLabel(ProductionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDate.sizePolicy().hasHeightForWidth())
        self.lblDate.setSizePolicy(sizePolicy)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout.addWidget(self.lblDate, 0, 0, 1, 1)
        self.edtDate = CDateEdit(ProductionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDate.sizePolicy().hasHeightForWidth())
        self.edtDate.setSizePolicy(sizePolicy)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.gridLayout.addWidget(self.edtDate, 0, 1, 1, 1)
        self.edtTime = QtGui.QTimeEdit(ProductionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTime.sizePolicy().hasHeightForWidth())
        self.edtTime.setSizePolicy(sizePolicy)
        self.edtTime.setObjectName(_fromUtf8("edtTime"))
        self.gridLayout.addWidget(self.edtTime, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(311, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.lblSupplier = QtGui.QLabel(ProductionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSupplier.sizePolicy().hasHeightForWidth())
        self.lblSupplier.setSizePolicy(sizePolicy)
        self.lblSupplier.setObjectName(_fromUtf8("lblSupplier"))
        self.gridLayout.addWidget(self.lblSupplier, 2, 0, 1, 1)
        self.cmbSupplier = CStorageComboBox(ProductionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSupplier.sizePolicy().hasHeightForWidth())
        self.cmbSupplier.setSizePolicy(sizePolicy)
        self.cmbSupplier.setObjectName(_fromUtf8("cmbSupplier"))
        self.gridLayout.addWidget(self.cmbSupplier, 2, 1, 1, 3)
        self.lblNote = QtGui.QLabel(ProductionDialog)
        self.lblNote.setObjectName(_fromUtf8("lblNote"))
        self.gridLayout.addWidget(self.lblNote, 4, 0, 1, 1)
        self.edtNote = QtGui.QLineEdit(ProductionDialog)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout.addWidget(self.edtNote, 4, 1, 1, 3)
        self.splitter = QtGui.QSplitter(ProductionDialog)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.groupBoxIn = QtGui.QGroupBox(self.splitter)
        self.groupBoxIn.setObjectName(_fromUtf8("groupBoxIn"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBoxIn)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tblInItems = CInDocTableView(self.groupBoxIn)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblInItems.sizePolicy().hasHeightForWidth())
        self.tblInItems.setSizePolicy(sizePolicy)
        self.tblInItems.setObjectName(_fromUtf8("tblInItems"))
        self.verticalLayout_2.addWidget(self.tblInItems)
        self.groupBoxOut = QtGui.QGroupBox(self.splitter)
        self.groupBoxOut.setObjectName(_fromUtf8("groupBoxOut"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBoxOut)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tblOutItems = CInDocTableView(self.groupBoxOut)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblOutItems.sizePolicy().hasHeightForWidth())
        self.tblOutItems.setSizePolicy(sizePolicy)
        self.tblOutItems.setObjectName(_fromUtf8("tblOutItems"))
        self.verticalLayout.addWidget(self.tblOutItems)
        self.gridLayout.addWidget(self.splitter, 5, 0, 1, 4)
        self.buttonBox = QtGui.QDialogButtonBox(ProductionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 6, 0, 1, 4)
        self.cmbSupplierPerson = CPersonComboBoxEx(ProductionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSupplierPerson.sizePolicy().hasHeightForWidth())
        self.cmbSupplierPerson.setSizePolicy(sizePolicy)
        self.cmbSupplierPerson.setObjectName(_fromUtf8("cmbSupplierPerson"))
        self.gridLayout.addWidget(self.cmbSupplierPerson, 3, 1, 1, 3)
        self.lblSupplierPerson = QtGui.QLabel(ProductionDialog)
        self.lblSupplierPerson.setObjectName(_fromUtf8("lblSupplierPerson"))
        self.gridLayout.addWidget(self.lblSupplierPerson, 3, 0, 1, 1)
        self.lblDate.setBuddy(self.edtDate)
        self.lblSupplier.setBuddy(self.cmbSupplier)
        self.lblNote.setBuddy(self.edtNote)
        self.lblSupplierPerson.setBuddy(self.cmbSupplierPerson)

        self.retranslateUi(ProductionDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ProductionDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ProductionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ProductionDialog)
        ProductionDialog.setTabOrder(self.edtDate, self.edtTime)
        ProductionDialog.setTabOrder(self.edtTime, self.cmbSupplier)
        ProductionDialog.setTabOrder(self.cmbSupplier, self.cmbSupplierPerson)
        ProductionDialog.setTabOrder(self.cmbSupplierPerson, self.edtNote)
        ProductionDialog.setTabOrder(self.edtNote, self.tblInItems)
        ProductionDialog.setTabOrder(self.tblInItems, self.tblOutItems)
        ProductionDialog.setTabOrder(self.tblOutItems, self.buttonBox)

    def retranslateUi(self, ProductionDialog):
        ProductionDialog.setWindowTitle(QtGui.QApplication.translate("ProductionDialog", "Производство ЛСиИМН", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDate.setText(QtGui.QApplication.translate("ProductionDialog", "Дата", None, QtGui.QApplication.UnicodeUTF8))
        self.edtTime.setDisplayFormat(QtGui.QApplication.translate("ProductionDialog", "HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSupplier.setText(QtGui.QApplication.translate("ProductionDialog", "Подразденение", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNote.setText(QtGui.QApplication.translate("ProductionDialog", "Примечания", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxIn.setTitle(QtGui.QApplication.translate("ProductionDialog", "Исходные материалы", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxOut.setTitle(QtGui.QApplication.translate("ProductionDialog", "Результат ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSupplierPerson.setText(QtGui.QApplication.translate("ProductionDialog", "Ответственный", None, QtGui.QApplication.UnicodeUTF8))

from library.InDocTable import CInDocTableView
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from Orgs.OrgStructComboBoxes import CStorageComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ProductionDialog = QtGui.QDialog()
    ui = Ui_ProductionDialog()
    ui.setupUi(ProductionDialog)
    ProductionDialog.show()
    sys.exit(app.exec_())

