# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\Stock\StockDialog.ui'
#
# Created: Fri Jun 15 12:17:06 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(611, 555)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMotion = QtGui.QWidget()
        self.tabMotion.setObjectName(_fromUtf8("tabMotion"))
        self.gridLayout = QtGui.QGridLayout(self.tabMotion)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitterMotions = QtGui.QSplitter(self.tabMotion)
        self.splitterMotions.setOrientation(QtCore.Qt.Horizontal)
        self.splitterMotions.setObjectName(_fromUtf8("splitterMotions"))
        self.groupBox = QtGui.QGroupBox(self.splitterMotions)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setMargin(2)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblMotionsFilterBegDate = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMotionsFilterBegDate.sizePolicy().hasHeightForWidth())
        self.lblMotionsFilterBegDate.setSizePolicy(sizePolicy)
        self.lblMotionsFilterBegDate.setObjectName(_fromUtf8("lblMotionsFilterBegDate"))
        self.gridLayout_2.addWidget(self.lblMotionsFilterBegDate, 0, 0, 1, 1)
        self.edtMotionsFilterBegDate = CDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMotionsFilterBegDate.sizePolicy().hasHeightForWidth())
        self.edtMotionsFilterBegDate.setSizePolicy(sizePolicy)
        self.edtMotionsFilterBegDate.setObjectName(_fromUtf8("edtMotionsFilterBegDate"))
        self.gridLayout_2.addWidget(self.edtMotionsFilterBegDate, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(92, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.edtMotionsFilterEndDate = CDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMotionsFilterEndDate.sizePolicy().hasHeightForWidth())
        self.edtMotionsFilterEndDate.setSizePolicy(sizePolicy)
        self.edtMotionsFilterEndDate.setObjectName(_fromUtf8("edtMotionsFilterEndDate"))
        self.gridLayout_2.addWidget(self.edtMotionsFilterEndDate, 1, 1, 1, 1)
        self.lblMotionsFilterEndDate = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMotionsFilterEndDate.sizePolicy().hasHeightForWidth())
        self.lblMotionsFilterEndDate.setSizePolicy(sizePolicy)
        self.lblMotionsFilterEndDate.setObjectName(_fromUtf8("lblMotionsFilterEndDate"))
        self.gridLayout_2.addWidget(self.lblMotionsFilterEndDate, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(92, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        self.lblMotionsFilterSupplier = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMotionsFilterSupplier.sizePolicy().hasHeightForWidth())
        self.lblMotionsFilterSupplier.setSizePolicy(sizePolicy)
        self.lblMotionsFilterSupplier.setObjectName(_fromUtf8("lblMotionsFilterSupplier"))
        self.gridLayout_2.addWidget(self.lblMotionsFilterSupplier, 2, 0, 1, 1)
        self.cmbMotionsFilterSupplier = CStorageComboBox(self.groupBox)
        self.cmbMotionsFilterSupplier.setObjectName(_fromUtf8("cmbMotionsFilterSupplier"))
        self.gridLayout_2.addWidget(self.cmbMotionsFilterSupplier, 2, 1, 1, 2)
        self.lblMotionsFilterReceiver = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMotionsFilterReceiver.sizePolicy().hasHeightForWidth())
        self.lblMotionsFilterReceiver.setSizePolicy(sizePolicy)
        self.lblMotionsFilterReceiver.setObjectName(_fromUtf8("lblMotionsFilterReceiver"))
        self.gridLayout_2.addWidget(self.lblMotionsFilterReceiver, 3, 0, 1, 1)
        self.cmbMotionsFilterReceiver = CStorageComboBox(self.groupBox)
        self.cmbMotionsFilterReceiver.setObjectName(_fromUtf8("cmbMotionsFilterReceiver"))
        self.gridLayout_2.addWidget(self.cmbMotionsFilterReceiver, 3, 1, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 265, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 8, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.bbxMotionsFilter = CApplyResetDialogButtonBox(self.groupBox)
        self.bbxMotionsFilter.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.bbxMotionsFilter.setObjectName(_fromUtf8("bbxMotionsFilter"))
        self.horizontalLayout_2.addWidget(self.bbxMotionsFilter)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 9, 0, 1, 3)
        self.cmbMotionsFilterNomenclature = CNomenclatureComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMotionsFilterNomenclature.sizePolicy().hasHeightForWidth())
        self.cmbMotionsFilterNomenclature.setSizePolicy(sizePolicy)
        self.cmbMotionsFilterNomenclature.setObjectName(_fromUtf8("cmbMotionsFilterNomenclature"))
        self.gridLayout_2.addWidget(self.cmbMotionsFilterNomenclature, 5, 1, 1, 2)
        self.lblMotionsFilterFinance = QtGui.QLabel(self.groupBox)
        self.lblMotionsFilterFinance.setObjectName(_fromUtf8("lblMotionsFilterFinance"))
        self.gridLayout_2.addWidget(self.lblMotionsFilterFinance, 6, 0, 1, 1)
        self.cmbMotionsFilterFinance = CRBComboBox(self.groupBox)
        self.cmbMotionsFilterFinance.setObjectName(_fromUtf8("cmbMotionsFilterFinance"))
        self.gridLayout_2.addWidget(self.cmbMotionsFilterFinance, 6, 1, 1, 2)
        self.lblMotionsFilterNomenclature = QtGui.QLabel(self.groupBox)
        self.lblMotionsFilterNomenclature.setObjectName(_fromUtf8("lblMotionsFilterNomenclature"))
        self.gridLayout_2.addWidget(self.lblMotionsFilterNomenclature, 5, 0, 1, 1)
        self.edtMotionsFilterNote = QtGui.QLineEdit(self.groupBox)
        self.edtMotionsFilterNote.setObjectName(_fromUtf8("edtMotionsFilterNote"))
        self.gridLayout_2.addWidget(self.edtMotionsFilterNote, 4, 1, 1, 2)
        self.lblMotionsFilterNote = QtGui.QLabel(self.groupBox)
        self.lblMotionsFilterNote.setObjectName(_fromUtf8("lblMotionsFilterNote"))
        self.gridLayout_2.addWidget(self.lblMotionsFilterNote, 4, 0, 1, 1)
        self.pnlMotions = QtGui.QWidget(self.splitterMotions)
        self.pnlMotions.setObjectName(_fromUtf8("pnlMotions"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pnlMotions)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tblMotions = CTableView(self.pnlMotions)
        self.tblMotions.setObjectName(_fromUtf8("tblMotions"))
        self.verticalLayout_2.addWidget(self.tblMotions)
        self.lblMotions = QtGui.QLabel(self.pnlMotions)
        self.lblMotions.setText(_fromUtf8(""))
        self.lblMotions.setObjectName(_fromUtf8("lblMotions"))
        self.verticalLayout_2.addWidget(self.lblMotions)
        self.gridLayout.addWidget(self.splitterMotions, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabMotion, _fromUtf8(""))
        self.tabRemaining = QtGui.QWidget()
        self.tabRemaining.setObjectName(_fromUtf8("tabRemaining"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabRemaining)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitterRemainings = QtGui.QSplitter(self.tabRemaining)
        self.splitterRemainings.setOrientation(QtCore.Qt.Horizontal)
        self.splitterRemainings.setObjectName(_fromUtf8("splitterRemainings"))
        self.grpRemaining = QtGui.QGroupBox(self.splitterRemainings)
        self.grpRemaining.setObjectName(_fromUtf8("grpRemaining"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grpRemaining)
        self.gridLayout_3.setMargin(2)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblRemainingsFilterDate = QtGui.QLabel(self.grpRemaining)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRemainingsFilterDate.sizePolicy().hasHeightForWidth())
        self.lblRemainingsFilterDate.setSizePolicy(sizePolicy)
        self.lblRemainingsFilterDate.setObjectName(_fromUtf8("lblRemainingsFilterDate"))
        self.gridLayout_3.addWidget(self.lblRemainingsFilterDate, 0, 0, 1, 1)
        self.edtRemainingsFilterDate = CDateEdit(self.grpRemaining)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtRemainingsFilterDate.sizePolicy().hasHeightForWidth())
        self.edtRemainingsFilterDate.setSizePolicy(sizePolicy)
        self.edtRemainingsFilterDate.setObjectName(_fromUtf8("edtRemainingsFilterDate"))
        self.gridLayout_3.addWidget(self.edtRemainingsFilterDate, 0, 1, 1, 1)
        self.lblRemainingsFilterNomenclature = QtGui.QLabel(self.grpRemaining)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRemainingsFilterNomenclature.sizePolicy().hasHeightForWidth())
        self.lblRemainingsFilterNomenclature.setSizePolicy(sizePolicy)
        self.lblRemainingsFilterNomenclature.setObjectName(_fromUtf8("lblRemainingsFilterNomenclature"))
        self.gridLayout_3.addWidget(self.lblRemainingsFilterNomenclature, 2, 0, 1, 1)
        self.cmbRemainingsFilterNomenclature = CNomenclatureComboBox(self.grpRemaining)
        self.cmbRemainingsFilterNomenclature.setObjectName(_fromUtf8("cmbRemainingsFilterNomenclature"))
        self.gridLayout_3.addWidget(self.cmbRemainingsFilterNomenclature, 2, 1, 1, 3)
        spacerItem4 = QtGui.QSpacerItem(20, 265, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 9, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 2, 1, 2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.bbxRemainingsFilter = CApplyResetDialogButtonBox(self.grpRemaining)
        self.bbxRemainingsFilter.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.bbxRemainingsFilter.setObjectName(_fromUtf8("bbxRemainingsFilter"))
        self.horizontalLayout_3.addWidget(self.bbxRemainingsFilter)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 10, 0, 1, 4)
        self.cmbRemainingsFilterStorage = CStorageComboBox(self.grpRemaining)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRemainingsFilterStorage.sizePolicy().hasHeightForWidth())
        self.cmbRemainingsFilterStorage.setSizePolicy(sizePolicy)
        self.cmbRemainingsFilterStorage.setObjectName(_fromUtf8("cmbRemainingsFilterStorage"))
        self.gridLayout_3.addWidget(self.cmbRemainingsFilterStorage, 1, 1, 1, 3)
        self.lblRemainingsFilterStorage = QtGui.QLabel(self.grpRemaining)
        self.lblRemainingsFilterStorage.setObjectName(_fromUtf8("lblRemainingsFilterStorage"))
        self.gridLayout_3.addWidget(self.lblRemainingsFilterStorage, 1, 0, 1, 1)
        self.cmbRemainingsFilterFinance = CRBComboBox(self.grpRemaining)
        self.cmbRemainingsFilterFinance.setObjectName(_fromUtf8("cmbRemainingsFilterFinance"))
        self.gridLayout_3.addWidget(self.cmbRemainingsFilterFinance, 6, 1, 1, 3)
        self.lblRemainingsFilterFinance = QtGui.QLabel(self.grpRemaining)
        self.lblRemainingsFilterFinance.setObjectName(_fromUtf8("lblRemainingsFilterFinance"))
        self.gridLayout_3.addWidget(self.lblRemainingsFilterFinance, 6, 0, 1, 1)
        self.chkRemainingsFilterConstrainedQnt = QtGui.QCheckBox(self.grpRemaining)
        self.chkRemainingsFilterConstrainedQnt.setObjectName(_fromUtf8("chkRemainingsFilterConstrainedQnt"))
        self.gridLayout_3.addWidget(self.chkRemainingsFilterConstrainedQnt, 7, 1, 1, 3)
        self.chkRemainingsFilterOrderQnt = QtGui.QCheckBox(self.grpRemaining)
        self.chkRemainingsFilterOrderQnt.setObjectName(_fromUtf8("chkRemainingsFilterOrderQnt"))
        self.gridLayout_3.addWidget(self.chkRemainingsFilterOrderQnt, 8, 1, 1, 3)
        self.lblRemainingsFilterBatch = QtGui.QLabel(self.grpRemaining)
        self.lblRemainingsFilterBatch.setEnabled(False)
        self.lblRemainingsFilterBatch.setObjectName(_fromUtf8("lblRemainingsFilterBatch"))
        self.gridLayout_3.addWidget(self.lblRemainingsFilterBatch, 4, 0, 1, 1)
        self.edtRemainingsFilterBatch = QtGui.QLineEdit(self.grpRemaining)
        self.edtRemainingsFilterBatch.setEnabled(False)
        self.edtRemainingsFilterBatch.setObjectName(_fromUtf8("edtRemainingsFilterBatch"))
        self.gridLayout_3.addWidget(self.edtRemainingsFilterBatch, 4, 1, 1, 3)
        self.lblRemainingsFilterBegShelfTime = QtGui.QLabel(self.grpRemaining)
        self.lblRemainingsFilterBegShelfTime.setEnabled(False)
        self.lblRemainingsFilterBegShelfTime.setObjectName(_fromUtf8("lblRemainingsFilterBegShelfTime"))
        self.gridLayout_3.addWidget(self.lblRemainingsFilterBegShelfTime, 5, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtRemainingsFilterBegShelfTime = CDateEdit(self.grpRemaining)
        self.edtRemainingsFilterBegShelfTime.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtRemainingsFilterBegShelfTime.sizePolicy().hasHeightForWidth())
        self.edtRemainingsFilterBegShelfTime.setSizePolicy(sizePolicy)
        self.edtRemainingsFilterBegShelfTime.setObjectName(_fromUtf8("edtRemainingsFilterBegShelfTime"))
        self.horizontalLayout.addWidget(self.edtRemainingsFilterBegShelfTime)
        self.lblRemainingsFilterEndShelfTime = QtGui.QLabel(self.grpRemaining)
        self.lblRemainingsFilterEndShelfTime.setEnabled(False)
        self.lblRemainingsFilterEndShelfTime.setObjectName(_fromUtf8("lblRemainingsFilterEndShelfTime"))
        self.horizontalLayout.addWidget(self.lblRemainingsFilterEndShelfTime)
        self.edtRemainingsFilterEndShelfTime = CDateEdit(self.grpRemaining)
        self.edtRemainingsFilterEndShelfTime.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtRemainingsFilterEndShelfTime.sizePolicy().hasHeightForWidth())
        self.edtRemainingsFilterEndShelfTime.setSizePolicy(sizePolicy)
        self.edtRemainingsFilterEndShelfTime.setObjectName(_fromUtf8("edtRemainingsFilterEndShelfTime"))
        self.horizontalLayout.addWidget(self.edtRemainingsFilterEndShelfTime)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.gridLayout_3.addLayout(self.horizontalLayout, 5, 1, 1, 3)
        self.chkRemainingsFilterGroupByBatch = QtGui.QCheckBox(self.grpRemaining)
        self.chkRemainingsFilterGroupByBatch.setObjectName(_fromUtf8("chkRemainingsFilterGroupByBatch"))
        self.gridLayout_3.addWidget(self.chkRemainingsFilterGroupByBatch, 3, 1, 1, 3)
        self.tblRemainings = CInDocTableView(self.splitterRemainings)
        self.tblRemainings.setObjectName(_fromUtf8("tblRemainings"))
        self.gridLayout_4.addWidget(self.splitterRemainings, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tabRemaining, _fromUtf8(""))
        self.tabMyRequisitions = QtGui.QWidget()
        self.tabMyRequisitions.setObjectName(_fromUtf8("tabMyRequisitions"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabMyRequisitions)
        self.gridLayout_6.setMargin(4)
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.splitterMRs = QtGui.QSplitter(self.tabMyRequisitions)
        self.splitterMRs.setOrientation(QtCore.Qt.Horizontal)
        self.splitterMRs.setChildrenCollapsible(False)
        self.splitterMRs.setObjectName(_fromUtf8("splitterMRs"))
        self.grpMRFilter = QtGui.QGroupBox(self.splitterMRs)
        self.grpMRFilter.setObjectName(_fromUtf8("grpMRFilter"))
        self.gridLayout_5 = QtGui.QGridLayout(self.grpMRFilter)
        self.gridLayout_5.setMargin(2)
        self.gridLayout_5.setSpacing(2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lblMRsFilterBegDate = QtGui.QLabel(self.grpMRFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMRsFilterBegDate.sizePolicy().hasHeightForWidth())
        self.lblMRsFilterBegDate.setSizePolicy(sizePolicy)
        self.lblMRsFilterBegDate.setObjectName(_fromUtf8("lblMRsFilterBegDate"))
        self.gridLayout_5.addWidget(self.lblMRsFilterBegDate, 1, 0, 1, 1)
        self.edtMRsFilterBegDate = CDateEdit(self.grpMRFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMRsFilterBegDate.sizePolicy().hasHeightForWidth())
        self.edtMRsFilterBegDate.setSizePolicy(sizePolicy)
        self.edtMRsFilterBegDate.setObjectName(_fromUtf8("edtMRsFilterBegDate"))
        self.gridLayout_5.addWidget(self.edtMRsFilterBegDate, 1, 1, 1, 1)
        self.lblMRsFilterEndDate = QtGui.QLabel(self.grpMRFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMRsFilterEndDate.sizePolicy().hasHeightForWidth())
        self.lblMRsFilterEndDate.setSizePolicy(sizePolicy)
        self.lblMRsFilterEndDate.setObjectName(_fromUtf8("lblMRsFilterEndDate"))
        self.gridLayout_5.addWidget(self.lblMRsFilterEndDate, 2, 0, 1, 1)
        self.edtMRsFilterEndDate = CDateEdit(self.grpMRFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMRsFilterEndDate.sizePolicy().hasHeightForWidth())
        self.edtMRsFilterEndDate.setSizePolicy(sizePolicy)
        self.edtMRsFilterEndDate.setObjectName(_fromUtf8("edtMRsFilterEndDate"))
        self.gridLayout_5.addWidget(self.edtMRsFilterEndDate, 2, 1, 1, 1)
        self.lblMRsFilterOrgStructure = QtGui.QLabel(self.grpMRFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMRsFilterOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblMRsFilterOrgStructure.setSizePolicy(sizePolicy)
        self.lblMRsFilterOrgStructure.setObjectName(_fromUtf8("lblMRsFilterOrgStructure"))
        self.gridLayout_5.addWidget(self.lblMRsFilterOrgStructure, 5, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 265, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem8, 8, 0, 1, 1)
        self.edtMRsFilterBegDeadlineDate = CDateEdit(self.grpMRFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMRsFilterBegDeadlineDate.sizePolicy().hasHeightForWidth())
        self.edtMRsFilterBegDeadlineDate.setSizePolicy(sizePolicy)
        self.edtMRsFilterBegDeadlineDate.setObjectName(_fromUtf8("edtMRsFilterBegDeadlineDate"))
        self.gridLayout_5.addWidget(self.edtMRsFilterBegDeadlineDate, 3, 1, 1, 1)
        self.edtMRsFilterEndDeadlineDate = CDateEdit(self.grpMRFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMRsFilterEndDeadlineDate.sizePolicy().hasHeightForWidth())
        self.edtMRsFilterEndDeadlineDate.setSizePolicy(sizePolicy)
        self.edtMRsFilterEndDeadlineDate.setObjectName(_fromUtf8("edtMRsFilterEndDeadlineDate"))
        self.gridLayout_5.addWidget(self.edtMRsFilterEndDeadlineDate, 4, 1, 1, 1)
        self.lblMRsFilterBegDeadlineDate = QtGui.QLabel(self.grpMRFilter)
        self.lblMRsFilterBegDeadlineDate.setObjectName(_fromUtf8("lblMRsFilterBegDeadlineDate"))
        self.gridLayout_5.addWidget(self.lblMRsFilterBegDeadlineDate, 3, 0, 1, 1)
        self.lblMRsFilterEndDeadlineDate = QtGui.QLabel(self.grpMRFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMRsFilterEndDeadlineDate.sizePolicy().hasHeightForWidth())
        self.lblMRsFilterEndDeadlineDate.setSizePolicy(sizePolicy)
        self.lblMRsFilterEndDeadlineDate.setObjectName(_fromUtf8("lblMRsFilterEndDeadlineDate"))
        self.gridLayout_5.addWidget(self.lblMRsFilterEndDeadlineDate, 4, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 1, 2, 1, 1)
        self.edtMRsFilterEndDeadlineTime = QtGui.QTimeEdit(self.grpMRFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMRsFilterEndDeadlineTime.sizePolicy().hasHeightForWidth())
        self.edtMRsFilterEndDeadlineTime.setSizePolicy(sizePolicy)
        self.edtMRsFilterEndDeadlineTime.setCalendarPopup(False)
        self.edtMRsFilterEndDeadlineTime.setObjectName(_fromUtf8("edtMRsFilterEndDeadlineTime"))
        self.gridLayout_5.addWidget(self.edtMRsFilterEndDeadlineTime, 4, 2, 1, 1)
        self.edtMRsFilterBegDeadlineTime = QtGui.QTimeEdit(self.grpMRFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMRsFilterBegDeadlineTime.sizePolicy().hasHeightForWidth())
        self.edtMRsFilterBegDeadlineTime.setSizePolicy(sizePolicy)
        self.edtMRsFilterBegDeadlineTime.setCalendarPopup(False)
        self.edtMRsFilterBegDeadlineTime.setObjectName(_fromUtf8("edtMRsFilterBegDeadlineTime"))
        self.gridLayout_5.addWidget(self.edtMRsFilterBegDeadlineTime, 3, 2, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem10, 2, 2, 1, 1)
        self.lblMRsFilterNomenclature = QtGui.QLabel(self.grpMRFilter)
        self.lblMRsFilterNomenclature.setObjectName(_fromUtf8("lblMRsFilterNomenclature"))
        self.gridLayout_5.addWidget(self.lblMRsFilterNomenclature, 6, 0, 1, 1)
        self.cmbMRsFilterNomenclature = CNomenclatureComboBox(self.grpMRFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMRsFilterNomenclature.sizePolicy().hasHeightForWidth())
        self.cmbMRsFilterNomenclature.setSizePolicy(sizePolicy)
        self.cmbMRsFilterNomenclature.setObjectName(_fromUtf8("cmbMRsFilterNomenclature"))
        self.gridLayout_5.addWidget(self.cmbMRsFilterNomenclature, 6, 1, 1, 2)
        self.cmbMRsFilterOrgStructure = CStorageComboBox(self.grpMRFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMRsFilterOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbMRsFilterOrgStructure.setSizePolicy(sizePolicy)
        self.cmbMRsFilterOrgStructure.setObjectName(_fromUtf8("cmbMRsFilterOrgStructure"))
        self.gridLayout_5.addWidget(self.cmbMRsFilterOrgStructure, 5, 1, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.bbxMRsFilter = CApplyResetDialogButtonBox(self.grpMRFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bbxMRsFilter.sizePolicy().hasHeightForWidth())
        self.bbxMRsFilter.setSizePolicy(sizePolicy)
        self.bbxMRsFilter.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.bbxMRsFilter.setObjectName(_fromUtf8("bbxMRsFilter"))
        self.horizontalLayout_4.addWidget(self.bbxMRsFilter)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 9, 0, 1, 3)
        self.chkMRsFilterOnlyActive = QtGui.QCheckBox(self.grpMRFilter)
        self.chkMRsFilterOnlyActive.setChecked(True)
        self.chkMRsFilterOnlyActive.setObjectName(_fromUtf8("chkMRsFilterOnlyActive"))
        self.gridLayout_5.addWidget(self.chkMRsFilterOnlyActive, 0, 1, 1, 2)
        self.pnlMRs = QtGui.QWidget(self.splitterMRs)
        self.pnlMRs.setObjectName(_fromUtf8("pnlMRs"))
        self.gridLayout_10 = QtGui.QGridLayout(self.pnlMRs)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setSpacing(4)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.splitterMRsContent = QtGui.QSplitter(self.pnlMRs)
        self.splitterMRsContent.setOrientation(QtCore.Qt.Vertical)
        self.splitterMRsContent.setChildrenCollapsible(False)
        self.splitterMRsContent.setObjectName(_fromUtf8("splitterMRsContent"))
        self.tblMRs = CTableView(self.splitterMRsContent)
        self.tblMRs.setObjectName(_fromUtf8("tblMRs"))
        self.tblMRContent = CTableView(self.splitterMRsContent)
        self.tblMRContent.setObjectName(_fromUtf8("tblMRContent"))
        self.gridLayout_10.addWidget(self.splitterMRsContent, 0, 0, 1, 1)
        self.lblMRs = QtGui.QLabel(self.pnlMRs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMRs.sizePolicy().hasHeightForWidth())
        self.lblMRs.setSizePolicy(sizePolicy)
        self.lblMRs.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblMRs.setFrameShadow(QtGui.QFrame.Plain)
        self.lblMRs.setText(_fromUtf8(""))
        self.lblMRs.setObjectName(_fromUtf8("lblMRs"))
        self.gridLayout_10.addWidget(self.lblMRs, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.splitterMRs, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabMyRequisitions, _fromUtf8(""))
        self.tabRequirementsToMe = QtGui.QWidget()
        self.tabRequirementsToMe.setObjectName(_fromUtf8("tabRequirementsToMe"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabRequirementsToMe)
        self.gridLayout_8.setMargin(4)
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.splitterRTMs = QtGui.QSplitter(self.tabRequirementsToMe)
        self.splitterRTMs.setOrientation(QtCore.Qt.Horizontal)
        self.splitterRTMs.setChildrenCollapsible(False)
        self.splitterRTMs.setObjectName(_fromUtf8("splitterRTMs"))
        self.grpRTMs = QtGui.QGroupBox(self.splitterRTMs)
        self.grpRTMs.setObjectName(_fromUtf8("grpRTMs"))
        self.gridLayout_7 = QtGui.QGridLayout(self.grpRTMs)
        self.gridLayout_7.setMargin(2)
        self.gridLayout_7.setSpacing(2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lblRTMsFilterBegDate = QtGui.QLabel(self.grpRTMs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRTMsFilterBegDate.sizePolicy().hasHeightForWidth())
        self.lblRTMsFilterBegDate.setSizePolicy(sizePolicy)
        self.lblRTMsFilterBegDate.setObjectName(_fromUtf8("lblRTMsFilterBegDate"))
        self.gridLayout_7.addWidget(self.lblRTMsFilterBegDate, 1, 1, 1, 1)
        self.edtRTMsFilterBegDate = CDateEdit(self.grpRTMs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtRTMsFilterBegDate.sizePolicy().hasHeightForWidth())
        self.edtRTMsFilterBegDate.setSizePolicy(sizePolicy)
        self.edtRTMsFilterBegDate.setObjectName(_fromUtf8("edtRTMsFilterBegDate"))
        self.gridLayout_7.addWidget(self.edtRTMsFilterBegDate, 1, 2, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(102, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem12, 1, 3, 1, 1)
        self.lblRTMsFilterEndDate = QtGui.QLabel(self.grpRTMs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRTMsFilterEndDate.sizePolicy().hasHeightForWidth())
        self.lblRTMsFilterEndDate.setSizePolicy(sizePolicy)
        self.lblRTMsFilterEndDate.setObjectName(_fromUtf8("lblRTMsFilterEndDate"))
        self.gridLayout_7.addWidget(self.lblRTMsFilterEndDate, 2, 1, 1, 1)
        self.edtRTMsFilterEndDate = CDateEdit(self.grpRTMs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtRTMsFilterEndDate.sizePolicy().hasHeightForWidth())
        self.edtRTMsFilterEndDate.setSizePolicy(sizePolicy)
        self.edtRTMsFilterEndDate.setObjectName(_fromUtf8("edtRTMsFilterEndDate"))
        self.gridLayout_7.addWidget(self.edtRTMsFilterEndDate, 2, 2, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(102, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem13, 2, 3, 1, 1)
        self.lblRTMsFilterBegDeadlineDate = QtGui.QLabel(self.grpRTMs)
        self.lblRTMsFilterBegDeadlineDate.setObjectName(_fromUtf8("lblRTMsFilterBegDeadlineDate"))
        self.gridLayout_7.addWidget(self.lblRTMsFilterBegDeadlineDate, 3, 1, 1, 1)
        self.edtRTMsFilterBegDeadlineDate = CDateEdit(self.grpRTMs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtRTMsFilterBegDeadlineDate.sizePolicy().hasHeightForWidth())
        self.edtRTMsFilterBegDeadlineDate.setSizePolicy(sizePolicy)
        self.edtRTMsFilterBegDeadlineDate.setObjectName(_fromUtf8("edtRTMsFilterBegDeadlineDate"))
        self.gridLayout_7.addWidget(self.edtRTMsFilterBegDeadlineDate, 3, 2, 1, 1)
        self.edtRTMsFilterBegDeadlineTime = QtGui.QTimeEdit(self.grpRTMs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtRTMsFilterBegDeadlineTime.sizePolicy().hasHeightForWidth())
        self.edtRTMsFilterBegDeadlineTime.setSizePolicy(sizePolicy)
        self.edtRTMsFilterBegDeadlineTime.setObjectName(_fromUtf8("edtRTMsFilterBegDeadlineTime"))
        self.gridLayout_7.addWidget(self.edtRTMsFilterBegDeadlineTime, 3, 3, 1, 1)
        self.lblRTMsFilterEndDeadlineDate = QtGui.QLabel(self.grpRTMs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRTMsFilterEndDeadlineDate.sizePolicy().hasHeightForWidth())
        self.lblRTMsFilterEndDeadlineDate.setSizePolicy(sizePolicy)
        self.lblRTMsFilterEndDeadlineDate.setObjectName(_fromUtf8("lblRTMsFilterEndDeadlineDate"))
        self.gridLayout_7.addWidget(self.lblRTMsFilterEndDeadlineDate, 4, 1, 1, 1)
        self.edtRTMsFilterEndDeadlineDate = CDateEdit(self.grpRTMs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtRTMsFilterEndDeadlineDate.sizePolicy().hasHeightForWidth())
        self.edtRTMsFilterEndDeadlineDate.setSizePolicy(sizePolicy)
        self.edtRTMsFilterEndDeadlineDate.setObjectName(_fromUtf8("edtRTMsFilterEndDeadlineDate"))
        self.gridLayout_7.addWidget(self.edtRTMsFilterEndDeadlineDate, 4, 2, 1, 1)
        self.edtRTMsFilterEndDeadlineTime = QtGui.QTimeEdit(self.grpRTMs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtRTMsFilterEndDeadlineTime.sizePolicy().hasHeightForWidth())
        self.edtRTMsFilterEndDeadlineTime.setSizePolicy(sizePolicy)
        self.edtRTMsFilterEndDeadlineTime.setObjectName(_fromUtf8("edtRTMsFilterEndDeadlineTime"))
        self.gridLayout_7.addWidget(self.edtRTMsFilterEndDeadlineTime, 4, 3, 1, 1)
        self.lblRTMsFilterOrgStructure = QtGui.QLabel(self.grpRTMs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRTMsFilterOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblRTMsFilterOrgStructure.setSizePolicy(sizePolicy)
        self.lblRTMsFilterOrgStructure.setObjectName(_fromUtf8("lblRTMsFilterOrgStructure"))
        self.gridLayout_7.addWidget(self.lblRTMsFilterOrgStructure, 5, 1, 1, 1)
        self.cmbRTMsFilterOrgStructure = CStorageComboBox(self.grpRTMs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRTMsFilterOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbRTMsFilterOrgStructure.setSizePolicy(sizePolicy)
        self.cmbRTMsFilterOrgStructure.setObjectName(_fromUtf8("cmbRTMsFilterOrgStructure"))
        self.gridLayout_7.addWidget(self.cmbRTMsFilterOrgStructure, 5, 2, 1, 2)
        self.lblRTMsFilterNomenclature = QtGui.QLabel(self.grpRTMs)
        self.lblRTMsFilterNomenclature.setObjectName(_fromUtf8("lblRTMsFilterNomenclature"))
        self.gridLayout_7.addWidget(self.lblRTMsFilterNomenclature, 6, 1, 1, 1)
        self.cmbRTMsFilterNomenclature = CNomenclatureComboBox(self.grpRTMs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRTMsFilterNomenclature.sizePolicy().hasHeightForWidth())
        self.cmbRTMsFilterNomenclature.setSizePolicy(sizePolicy)
        self.cmbRTMsFilterNomenclature.setObjectName(_fromUtf8("cmbRTMsFilterNomenclature"))
        self.gridLayout_7.addWidget(self.cmbRTMsFilterNomenclature, 6, 2, 1, 2)
        spacerItem14 = QtGui.QSpacerItem(20, 265, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem14, 7, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.bbxRTMsFilter = CApplyResetDialogButtonBox(self.grpRTMs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bbxRTMsFilter.sizePolicy().hasHeightForWidth())
        self.bbxRTMsFilter.setSizePolicy(sizePolicy)
        self.bbxRTMsFilter.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.bbxRTMsFilter.setObjectName(_fromUtf8("bbxRTMsFilter"))
        self.horizontalLayout_5.addWidget(self.bbxRTMsFilter)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 8, 1, 1, 3)
        self.chkRTMsFilterOnlyActive = QtGui.QCheckBox(self.grpRTMs)
        self.chkRTMsFilterOnlyActive.setChecked(True)
        self.chkRTMsFilterOnlyActive.setObjectName(_fromUtf8("chkRTMsFilterOnlyActive"))
        self.gridLayout_7.addWidget(self.chkRTMsFilterOnlyActive, 0, 2, 1, 2)
        self.pnlRTMs = QtGui.QWidget(self.splitterRTMs)
        self.pnlRTMs.setObjectName(_fromUtf8("pnlRTMs"))
        self.gridLayout_9 = QtGui.QGridLayout(self.pnlRTMs)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setHorizontalSpacing(0)
        self.gridLayout_9.setVerticalSpacing(4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.splitterRTMsContent = QtGui.QSplitter(self.pnlRTMs)
        self.splitterRTMsContent.setOrientation(QtCore.Qt.Vertical)
        self.splitterRTMsContent.setChildrenCollapsible(False)
        self.splitterRTMsContent.setObjectName(_fromUtf8("splitterRTMsContent"))
        self.tblRTMs = CTableView(self.splitterRTMsContent)
        self.tblRTMs.setObjectName(_fromUtf8("tblRTMs"))
        self.tblRTMContent = CTableView(self.splitterRTMsContent)
        self.tblRTMContent.setObjectName(_fromUtf8("tblRTMContent"))
        self.gridLayout_9.addWidget(self.splitterRTMsContent, 0, 0, 1, 1)
        self.lblRTMs = QtGui.QLabel(self.pnlRTMs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRTMs.sizePolicy().hasHeightForWidth())
        self.lblRTMs.setSizePolicy(sizePolicy)
        self.lblRTMs.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblRTMs.setFrameShadow(QtGui.QFrame.Plain)
        self.lblRTMs.setText(_fromUtf8(""))
        self.lblRTMs.setObjectName(_fromUtf8("lblRTMs"))
        self.gridLayout_9.addWidget(self.lblRTMs, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.splitterRTMs, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabRequirementsToMe, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.lblMotionsFilterBegDate.setBuddy(self.edtMotionsFilterBegDate)
        self.lblMotionsFilterEndDate.setBuddy(self.edtMotionsFilterEndDate)
        self.lblMotionsFilterSupplier.setBuddy(self.cmbMotionsFilterSupplier)
        self.lblMotionsFilterReceiver.setBuddy(self.cmbMotionsFilterReceiver)
        self.lblMotionsFilterFinance.setBuddy(self.cmbMotionsFilterFinance)
        self.lblMotionsFilterNomenclature.setBuddy(self.cmbMotionsFilterNomenclature)
        self.lblMotionsFilterNote.setBuddy(self.edtMotionsFilterNote)
        self.lblRemainingsFilterDate.setBuddy(self.edtRemainingsFilterDate)
        self.lblRemainingsFilterNomenclature.setBuddy(self.cmbRemainingsFilterNomenclature)
        self.lblRemainingsFilterStorage.setBuddy(self.cmbRemainingsFilterStorage)
        self.lblRemainingsFilterFinance.setBuddy(self.cmbRemainingsFilterFinance)
        self.lblRemainingsFilterBatch.setBuddy(self.edtRemainingsFilterBatch)
        self.lblRemainingsFilterBegShelfTime.setBuddy(self.edtRemainingsFilterBegShelfTime)
        self.lblRemainingsFilterEndShelfTime.setBuddy(self.edtRemainingsFilterEndShelfTime)
        self.lblMRsFilterBegDate.setBuddy(self.edtMRsFilterBegDate)
        self.lblMRsFilterEndDate.setBuddy(self.edtMRsFilterEndDate)
        self.lblMRsFilterOrgStructure.setBuddy(self.cmbMRsFilterOrgStructure)
        self.lblMRsFilterBegDeadlineDate.setBuddy(self.edtMRsFilterBegDeadlineDate)
        self.lblMRsFilterEndDeadlineDate.setBuddy(self.edtMRsFilterEndDeadlineDate)
        self.lblMRsFilterNomenclature.setBuddy(self.cmbMRsFilterNomenclature)
        self.lblRTMsFilterBegDate.setBuddy(self.edtRTMsFilterBegDate)
        self.lblRTMsFilterEndDate.setBuddy(self.edtRTMsFilterEndDate)
        self.lblRTMsFilterBegDeadlineDate.setBuddy(self.edtRTMsFilterBegDeadlineDate)
        self.lblRTMsFilterEndDeadlineDate.setBuddy(self.edtRTMsFilterEndDeadlineDate)
        self.lblRTMsFilterOrgStructure.setBuddy(self.cmbRTMsFilterOrgStructure)
        self.lblRTMsFilterNomenclature.setBuddy(self.cmbRTMsFilterNomenclature)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.edtMotionsFilterBegDate)
        Dialog.setTabOrder(self.edtMotionsFilterBegDate, self.edtMotionsFilterEndDate)
        Dialog.setTabOrder(self.edtMotionsFilterEndDate, self.cmbMotionsFilterSupplier)
        Dialog.setTabOrder(self.cmbMotionsFilterSupplier, self.cmbMotionsFilterReceiver)
        Dialog.setTabOrder(self.cmbMotionsFilterReceiver, self.edtMotionsFilterNote)
        Dialog.setTabOrder(self.edtMotionsFilterNote, self.cmbMotionsFilterNomenclature)
        Dialog.setTabOrder(self.cmbMotionsFilterNomenclature, self.cmbMotionsFilterFinance)
        Dialog.setTabOrder(self.cmbMotionsFilterFinance, self.bbxMotionsFilter)
        Dialog.setTabOrder(self.bbxMotionsFilter, self.tblMotions)
        Dialog.setTabOrder(self.tblMotions, self.edtRemainingsFilterDate)
        Dialog.setTabOrder(self.edtRemainingsFilterDate, self.cmbRemainingsFilterStorage)
        Dialog.setTabOrder(self.cmbRemainingsFilterStorage, self.cmbRemainingsFilterNomenclature)
        Dialog.setTabOrder(self.cmbRemainingsFilterNomenclature, self.chkRemainingsFilterGroupByBatch)
        Dialog.setTabOrder(self.chkRemainingsFilterGroupByBatch, self.edtRemainingsFilterBatch)
        Dialog.setTabOrder(self.edtRemainingsFilterBatch, self.edtRemainingsFilterBegShelfTime)
        Dialog.setTabOrder(self.edtRemainingsFilterBegShelfTime, self.edtRemainingsFilterEndShelfTime)
        Dialog.setTabOrder(self.edtRemainingsFilterEndShelfTime, self.cmbRemainingsFilterFinance)
        Dialog.setTabOrder(self.cmbRemainingsFilterFinance, self.chkRemainingsFilterConstrainedQnt)
        Dialog.setTabOrder(self.chkRemainingsFilterConstrainedQnt, self.chkRemainingsFilterOrderQnt)
        Dialog.setTabOrder(self.chkRemainingsFilterOrderQnt, self.bbxRemainingsFilter)
        Dialog.setTabOrder(self.bbxRemainingsFilter, self.tblRemainings)
        Dialog.setTabOrder(self.tblRemainings, self.chkMRsFilterOnlyActive)
        Dialog.setTabOrder(self.chkMRsFilterOnlyActive, self.edtMRsFilterBegDate)
        Dialog.setTabOrder(self.edtMRsFilterBegDate, self.edtMRsFilterEndDate)
        Dialog.setTabOrder(self.edtMRsFilterEndDate, self.edtMRsFilterBegDeadlineDate)
        Dialog.setTabOrder(self.edtMRsFilterBegDeadlineDate, self.edtMRsFilterBegDeadlineTime)
        Dialog.setTabOrder(self.edtMRsFilterBegDeadlineTime, self.edtMRsFilterEndDeadlineDate)
        Dialog.setTabOrder(self.edtMRsFilterEndDeadlineDate, self.edtMRsFilterEndDeadlineTime)
        Dialog.setTabOrder(self.edtMRsFilterEndDeadlineTime, self.cmbMRsFilterOrgStructure)
        Dialog.setTabOrder(self.cmbMRsFilterOrgStructure, self.cmbMRsFilterNomenclature)
        Dialog.setTabOrder(self.cmbMRsFilterNomenclature, self.bbxMRsFilter)
        Dialog.setTabOrder(self.bbxMRsFilter, self.tblMRs)
        Dialog.setTabOrder(self.tblMRs, self.tblMRContent)
        Dialog.setTabOrder(self.tblMRContent, self.chkRTMsFilterOnlyActive)
        Dialog.setTabOrder(self.chkRTMsFilterOnlyActive, self.edtRTMsFilterBegDate)
        Dialog.setTabOrder(self.edtRTMsFilterBegDate, self.edtRTMsFilterEndDate)
        Dialog.setTabOrder(self.edtRTMsFilterEndDate, self.edtRTMsFilterBegDeadlineDate)
        Dialog.setTabOrder(self.edtRTMsFilterBegDeadlineDate, self.edtRTMsFilterBegDeadlineTime)
        Dialog.setTabOrder(self.edtRTMsFilterBegDeadlineTime, self.edtRTMsFilterEndDeadlineDate)
        Dialog.setTabOrder(self.edtRTMsFilterEndDeadlineDate, self.edtRTMsFilterEndDeadlineTime)
        Dialog.setTabOrder(self.edtRTMsFilterEndDeadlineTime, self.cmbRTMsFilterOrgStructure)
        Dialog.setTabOrder(self.cmbRTMsFilterOrgStructure, self.cmbRTMsFilterNomenclature)
        Dialog.setTabOrder(self.cmbRTMsFilterNomenclature, self.bbxRTMsFilter)
        Dialog.setTabOrder(self.bbxRTMsFilter, self.tblRTMs)
        Dialog.setTabOrder(self.tblRTMs, self.tblRTMContent)
        Dialog.setTabOrder(self.tblRTMContent, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Склад ЛСиИМН", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Фильтр", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMotionsFilterBegDate.setText(QtGui.QApplication.translate("Dialog", "&С", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMotionsFilterEndDate.setText(QtGui.QApplication.translate("Dialog", "По", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMotionsFilterSupplier.setText(QtGui.QApplication.translate("Dialog", "&Источник", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMotionsFilterReceiver.setText(QtGui.QApplication.translate("Dialog", "&Получатель", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMotionsFilterFinance.setText(QtGui.QApplication.translate("Dialog", "Тип &финансирования", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMotionsFilterNomenclature.setText(QtGui.QApplication.translate("Dialog", "&Номенклатура", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMotionsFilterNote.setText(QtGui.QApplication.translate("Dialog", "Примечание", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMotion), QtGui.QApplication.translate("Dialog", "Движение", None, QtGui.QApplication.UnicodeUTF8))
        self.grpRemaining.setTitle(QtGui.QApplication.translate("Dialog", "Фильтр", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRemainingsFilterDate.setText(QtGui.QApplication.translate("Dialog", "На дату", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRemainingsFilterNomenclature.setText(QtGui.QApplication.translate("Dialog", "&Номенклатура", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRemainingsFilterStorage.setText(QtGui.QApplication.translate("Dialog", "&Склад", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRemainingsFilterFinance.setText(QtGui.QApplication.translate("Dialog", "Тип &финансирования", None, QtGui.QApplication.UnicodeUTF8))
        self.chkRemainingsFilterConstrainedQnt.setText(QtGui.QApplication.translate("Dialog", "Запас ниже точки заказа", None, QtGui.QApplication.UnicodeUTF8))
        self.chkRemainingsFilterOrderQnt.setText(QtGui.QApplication.translate("Dialog", "Запас ниже гантированного", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRemainingsFilterBatch.setText(QtGui.QApplication.translate("Dialog", "&Партия", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRemainingsFilterBegShelfTime.setText(QtGui.QApplication.translate("Dialog", "&Годен с", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRemainingsFilterEndShelfTime.setText(QtGui.QApplication.translate("Dialog", "по ", None, QtGui.QApplication.UnicodeUTF8))
        self.chkRemainingsFilterGroupByBatch.setText(QtGui.QApplication.translate("Dialog", "Разделять по партиям и годности", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRemaining), QtGui.QApplication.translate("Dialog", "Остатки", None, QtGui.QApplication.UnicodeUTF8))
        self.grpMRFilter.setTitle(QtGui.QApplication.translate("Dialog", "Фильтр", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMRsFilterBegDate.setText(QtGui.QApplication.translate("Dialog", "В период с", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMRsFilterEndDate.setText(QtGui.QApplication.translate("Dialog", "По", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMRsFilterOrgStructure.setText(QtGui.QApplication.translate("Dialog", "&Получатель", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMRsFilterBegDeadlineDate.setText(QtGui.QApplication.translate("Dialog", "В срок с", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMRsFilterEndDeadlineDate.setText(QtGui.QApplication.translate("Dialog", "По", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMRsFilterEndDeadlineTime.setDisplayFormat(QtGui.QApplication.translate("Dialog", "HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMRsFilterBegDeadlineTime.setDisplayFormat(QtGui.QApplication.translate("Dialog", "HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMRsFilterNomenclature.setText(QtGui.QApplication.translate("Dialog", "&Номенклатура", None, QtGui.QApplication.UnicodeUTF8))
        self.chkMRsFilterOnlyActive.setText(QtGui.QApplication.translate("Dialog", "Только действующие", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMyRequisitions), QtGui.QApplication.translate("Dialog", "Мои требования", None, QtGui.QApplication.UnicodeUTF8))
        self.grpRTMs.setTitle(QtGui.QApplication.translate("Dialog", "Фильтр", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRTMsFilterBegDate.setText(QtGui.QApplication.translate("Dialog", "В период с", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRTMsFilterEndDate.setText(QtGui.QApplication.translate("Dialog", "По", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRTMsFilterBegDeadlineDate.setText(QtGui.QApplication.translate("Dialog", "В срок с", None, QtGui.QApplication.UnicodeUTF8))
        self.edtRTMsFilterBegDeadlineTime.setDisplayFormat(QtGui.QApplication.translate("Dialog", "HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRTMsFilterEndDeadlineDate.setText(QtGui.QApplication.translate("Dialog", "По", None, QtGui.QApplication.UnicodeUTF8))
        self.edtRTMsFilterEndDeadlineTime.setDisplayFormat(QtGui.QApplication.translate("Dialog", "HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRTMsFilterOrgStructure.setText(QtGui.QApplication.translate("Dialog", "&Заказчик", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRTMsFilterNomenclature.setText(QtGui.QApplication.translate("Dialog", "&Номенклатура", None, QtGui.QApplication.UnicodeUTF8))
        self.chkRTMsFilterOnlyActive.setText(QtGui.QApplication.translate("Dialog", "Только действующие", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRequirementsToMe), QtGui.QApplication.translate("Dialog", "Требования ко мне", None, QtGui.QApplication.UnicodeUTF8))

from library.crbcombobox import CRBComboBox
from library.InDocTable import CInDocTableView
from library.DialogButtonBox import CApplyResetDialogButtonBox
from Stock.NomenclatureComboBox import CNomenclatureComboBox
from Orgs.OrgStructComboBoxes import CStorageComboBox
from library.TableView import CTableView
from library.DateEdit import CDateEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

