# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\Exchange\ExportActionResult_Wizard_1.ui'
#
# Created: Fri Jun 15 12:15:08 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ExportActionResult_Wizard_1(object):
    def setupUi(self, ExportActionResult_Wizard_1):
        ExportActionResult_Wizard_1.setObjectName(_fromUtf8("ExportActionResult_Wizard_1"))
        ExportActionResult_Wizard_1.resize(640, 504)
        self.gridLayout = QtGui.QGridLayout(ExportActionResult_Wizard_1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.treeContracts = QtGui.QTreeView(ExportActionResult_Wizard_1)
        self.treeContracts.setObjectName(_fromUtf8("treeContracts"))
        self.gridLayout.addWidget(self.treeContracts, 5, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(ExportActionResult_Wizard_1)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabFilter = QtGui.QTabWidget(self.groupBox)
        self.tabFilter.setObjectName(_fromUtf8("tabFilter"))
        self.tabEvent = QtGui.QWidget()
        self.tabEvent.setObjectName(_fromUtf8("tabEvent"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabEvent)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.chkEventPurpose = QtGui.QCheckBox(self.tabEvent)
        self.chkEventPurpose.setObjectName(_fromUtf8("chkEventPurpose"))
        self.gridLayout_2.addWidget(self.chkEventPurpose, 6, 0, 1, 1)
        self.chkEventType = QtGui.QCheckBox(self.tabEvent)
        self.chkEventType.setObjectName(_fromUtf8("chkEventType"))
        self.gridLayout_2.addWidget(self.chkEventType, 8, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 12, 0, 1, 1)
        self.cmbEventPurpose = CRBComboBox(self.tabEvent)
        self.cmbEventPurpose.setEnabled(False)
        self.cmbEventPurpose.setObjectName(_fromUtf8("cmbEventPurpose"))
        self.gridLayout_2.addWidget(self.cmbEventPurpose, 7, 0, 1, 1)
        self.cmbEventType = CRBComboBox(self.tabEvent)
        self.cmbEventType.setEnabled(False)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout_2.addWidget(self.cmbEventType, 9, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.edtEventExecBegDate = CDateEdit(self.tabEvent)
        self.edtEventExecBegDate.setEnabled(False)
        self.edtEventExecBegDate.setObjectName(_fromUtf8("edtEventExecBegDate"))
        self.horizontalLayout_3.addWidget(self.edtEventExecBegDate)
        self.edtEventExecEndDate = CDateEdit(self.tabEvent)
        self.edtEventExecEndDate.setEnabled(False)
        self.edtEventExecEndDate.setObjectName(_fromUtf8("edtEventExecEndDate"))
        self.horizontalLayout_3.addWidget(self.edtEventExecEndDate)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.chkEventExecDate = QtGui.QCheckBox(self.tabEvent)
        self.chkEventExecDate.setObjectName(_fromUtf8("chkEventExecDate"))
        self.gridLayout_2.addWidget(self.chkEventExecDate, 0, 0, 1, 1)
        self.chkEventSetDate = QtGui.QCheckBox(self.tabEvent)
        self.chkEventSetDate.setObjectName(_fromUtf8("chkEventSetDate"))
        self.gridLayout_2.addWidget(self.chkEventSetDate, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.edtEventSetBegDate = CDateEdit(self.tabEvent)
        self.edtEventSetBegDate.setEnabled(False)
        self.edtEventSetBegDate.setObjectName(_fromUtf8("edtEventSetBegDate"))
        self.horizontalLayout_4.addWidget(self.edtEventSetBegDate)
        self.edtEventSetEndDate = CDateEdit(self.tabEvent)
        self.edtEventSetEndDate.setEnabled(False)
        self.edtEventSetEndDate.setObjectName(_fromUtf8("edtEventSetEndDate"))
        self.horizontalLayout_4.addWidget(self.edtEventSetEndDate)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.cmbEventLPU = CPolyclinicComboBox(self.tabEvent)
        self.cmbEventLPU.setEnabled(False)
        self.cmbEventLPU.setObjectName(_fromUtf8("cmbEventLPU"))
        self.gridLayout_2.addWidget(self.cmbEventLPU, 11, 0, 1, 1)
        self.chkEventLPU = QtGui.QCheckBox(self.tabEvent)
        self.chkEventLPU.setObjectName(_fromUtf8("chkEventLPU"))
        self.gridLayout_2.addWidget(self.chkEventLPU, 10, 0, 1, 1)
        self.tabFilter.addTab(self.tabEvent, _fromUtf8(""))
        self.tabAction = QtGui.QWidget()
        self.tabAction.setObjectName(_fromUtf8("tabAction"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabAction)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.chkActionDate = QtGui.QCheckBox(self.tabAction)
        self.chkActionDate.setObjectName(_fromUtf8("chkActionDate"))
        self.verticalLayout_3.addWidget(self.chkActionDate)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.edtActionBegDate = CDateEdit(self.tabAction)
        self.edtActionBegDate.setEnabled(False)
        self.edtActionBegDate.setObjectName(_fromUtf8("edtActionBegDate"))
        self.horizontalLayout_2.addWidget(self.edtActionBegDate)
        self.edtActionEndDate = CDateEdit(self.tabAction)
        self.edtActionEndDate.setEnabled(False)
        self.edtActionEndDate.setObjectName(_fromUtf8("edtActionEndDate"))
        self.horizontalLayout_2.addWidget(self.edtActionEndDate)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.chkActionStatus = QtGui.QCheckBox(self.tabAction)
        self.chkActionStatus.setObjectName(_fromUtf8("chkActionStatus"))
        self.verticalLayout_3.addWidget(self.chkActionStatus)
        self.cmbActionStatus = QtGui.QComboBox(self.tabAction)
        self.cmbActionStatus.setEnabled(False)
        self.cmbActionStatus.setObjectName(_fromUtf8("cmbActionStatus"))
        self.cmbActionStatus.addItem(_fromUtf8(""))
        self.cmbActionStatus.addItem(_fromUtf8(""))
        self.cmbActionStatus.addItem(_fromUtf8(""))
        self.cmbActionStatus.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.cmbActionStatus)
        self.chkActionSetPerson = QtGui.QCheckBox(self.tabAction)
        self.chkActionSetPerson.setObjectName(_fromUtf8("chkActionSetPerson"))
        self.verticalLayout_3.addWidget(self.chkActionSetPerson)
        self.cmbActionSetPerson = CPersonComboBoxEx(self.tabAction)
        self.cmbActionSetPerson.setEnabled(False)
        self.cmbActionSetPerson.setObjectName(_fromUtf8("cmbActionSetPerson"))
        self.verticalLayout_3.addWidget(self.cmbActionSetPerson)
        self.chkActionClass = QtGui.QCheckBox(self.tabAction)
        self.chkActionClass.setObjectName(_fromUtf8("chkActionClass"))
        self.verticalLayout_3.addWidget(self.chkActionClass)
        self.cmbActionClass = QtGui.QComboBox(self.tabAction)
        self.cmbActionClass.setEnabled(False)
        self.cmbActionClass.setObjectName(_fromUtf8("cmbActionClass"))
        self.cmbActionClass.addItem(_fromUtf8(""))
        self.cmbActionClass.addItem(_fromUtf8(""))
        self.cmbActionClass.addItem(_fromUtf8(""))
        self.cmbActionClass.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.cmbActionClass)
        self.chkActionType = QtGui.QCheckBox(self.tabAction)
        self.chkActionType.setObjectName(_fromUtf8("chkActionType"))
        self.verticalLayout_3.addWidget(self.chkActionType)
        self.cmbActionType = CActionTypeComboBox(self.tabAction)
        self.cmbActionType.setEnabled(False)
        self.cmbActionType.setObjectName(_fromUtf8("cmbActionType"))
        self.verticalLayout_3.addWidget(self.cmbActionType)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.tabFilter.addTab(self.tabAction, _fromUtf8(""))
        self.tabAdditional = QtGui.QWidget()
        self.tabAdditional.setObjectName(_fromUtf8("tabAdditional"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabAdditional)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.tabAdditional)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.chkIncludeClientEventInfo = QtGui.QCheckBox(self.tabAdditional)
        self.chkIncludeClientEventInfo.setObjectName(_fromUtf8("chkIncludeClientEventInfo"))
        self.verticalLayout_4.addWidget(self.chkIncludeClientEventInfo)
        self.chkIncludeClientWorkInfo = QtGui.QCheckBox(self.tabAdditional)
        self.chkIncludeClientWorkInfo.setObjectName(_fromUtf8("chkIncludeClientWorkInfo"))
        self.verticalLayout_4.addWidget(self.chkIncludeClientWorkInfo)
        self.chkIncludeClientAddressInfo = QtGui.QCheckBox(self.tabAdditional)
        self.chkIncludeClientAddressInfo.setObjectName(_fromUtf8("chkIncludeClientAddressInfo"))
        self.verticalLayout_4.addWidget(self.chkIncludeClientAddressInfo)
        self.chkIncludeClientDocumentInfo = QtGui.QCheckBox(self.tabAdditional)
        self.chkIncludeClientDocumentInfo.setObjectName(_fromUtf8("chkIncludeClientDocumentInfo"))
        self.verticalLayout_4.addWidget(self.chkIncludeClientDocumentInfo)
        self.chkIncludeClientContactInfo = QtGui.QCheckBox(self.tabAdditional)
        self.chkIncludeClientContactInfo.setObjectName(_fromUtf8("chkIncludeClientContactInfo"))
        self.verticalLayout_4.addWidget(self.chkIncludeClientContactInfo)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.tabFilter.addTab(self.tabAdditional, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabFilter)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btnResetFilter = QtGui.QPushButton(self.groupBox)
        self.btnResetFilter.setObjectName(_fromUtf8("btnResetFilter"))
        self.horizontalLayout.addWidget(self.btnResetFilter)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout.addLayout(self.verticalLayout, 5, 1, 1, 1)

        self.retranslateUi(ExportActionResult_Wizard_1)
        self.tabFilter.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ExportActionResult_Wizard_1)
        ExportActionResult_Wizard_1.setTabOrder(self.treeContracts, self.tabFilter)
        ExportActionResult_Wizard_1.setTabOrder(self.tabFilter, self.chkEventExecDate)
        ExportActionResult_Wizard_1.setTabOrder(self.chkEventExecDate, self.edtEventExecBegDate)
        ExportActionResult_Wizard_1.setTabOrder(self.edtEventExecBegDate, self.edtEventExecEndDate)
        ExportActionResult_Wizard_1.setTabOrder(self.edtEventExecEndDate, self.chkEventSetDate)
        ExportActionResult_Wizard_1.setTabOrder(self.chkEventSetDate, self.edtEventSetBegDate)
        ExportActionResult_Wizard_1.setTabOrder(self.edtEventSetBegDate, self.edtEventSetEndDate)
        ExportActionResult_Wizard_1.setTabOrder(self.edtEventSetEndDate, self.chkEventPurpose)
        ExportActionResult_Wizard_1.setTabOrder(self.chkEventPurpose, self.cmbEventPurpose)
        ExportActionResult_Wizard_1.setTabOrder(self.cmbEventPurpose, self.chkEventType)
        ExportActionResult_Wizard_1.setTabOrder(self.chkEventType, self.cmbEventType)
        ExportActionResult_Wizard_1.setTabOrder(self.cmbEventType, self.chkEventLPU)
        ExportActionResult_Wizard_1.setTabOrder(self.chkEventLPU, self.cmbEventLPU)
        ExportActionResult_Wizard_1.setTabOrder(self.cmbEventLPU, self.btnResetFilter)
        ExportActionResult_Wizard_1.setTabOrder(self.btnResetFilter, self.chkActionDate)
        ExportActionResult_Wizard_1.setTabOrder(self.chkActionDate, self.edtActionBegDate)
        ExportActionResult_Wizard_1.setTabOrder(self.edtActionBegDate, self.edtActionEndDate)
        ExportActionResult_Wizard_1.setTabOrder(self.edtActionEndDate, self.chkActionStatus)
        ExportActionResult_Wizard_1.setTabOrder(self.chkActionStatus, self.cmbActionStatus)
        ExportActionResult_Wizard_1.setTabOrder(self.cmbActionStatus, self.chkActionSetPerson)
        ExportActionResult_Wizard_1.setTabOrder(self.chkActionSetPerson, self.cmbActionSetPerson)
        ExportActionResult_Wizard_1.setTabOrder(self.cmbActionSetPerson, self.chkActionClass)
        ExportActionResult_Wizard_1.setTabOrder(self.chkActionClass, self.cmbActionClass)
        ExportActionResult_Wizard_1.setTabOrder(self.cmbActionClass, self.chkActionType)
        ExportActionResult_Wizard_1.setTabOrder(self.chkActionType, self.cmbActionType)
        ExportActionResult_Wizard_1.setTabOrder(self.cmbActionType, self.chkIncludeClientEventInfo)
        ExportActionResult_Wizard_1.setTabOrder(self.chkIncludeClientEventInfo, self.chkIncludeClientWorkInfo)
        ExportActionResult_Wizard_1.setTabOrder(self.chkIncludeClientWorkInfo, self.chkIncludeClientAddressInfo)
        ExportActionResult_Wizard_1.setTabOrder(self.chkIncludeClientAddressInfo, self.chkIncludeClientDocumentInfo)
        ExportActionResult_Wizard_1.setTabOrder(self.chkIncludeClientDocumentInfo, self.chkIncludeClientContactInfo)

    def retranslateUi(self, ExportActionResult_Wizard_1):
        ExportActionResult_Wizard_1.setWindowTitle(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Экспорт результатов действий", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Фильтр", None, QtGui.QApplication.UnicodeUTF8))
        self.chkEventPurpose.setText(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Назначение", None, QtGui.QApplication.UnicodeUTF8))
        self.chkEventType.setText(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Тип события", None, QtGui.QApplication.UnicodeUTF8))
        self.chkEventExecDate.setText(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Период выполнения", None, QtGui.QApplication.UnicodeUTF8))
        self.chkEventSetDate.setText(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Период назначения", None, QtGui.QApplication.UnicodeUTF8))
        self.chkEventLPU.setText(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Подразделение", None, QtGui.QApplication.UnicodeUTF8))
        self.tabFilter.setTabText(self.tabFilter.indexOf(self.tabEvent), QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Событие", None, QtGui.QApplication.UnicodeUTF8))
        self.chkActionDate.setText(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Период", None, QtGui.QApplication.UnicodeUTF8))
        self.chkActionStatus.setText(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Состояние", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbActionStatus.setItemText(0, QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Начато", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbActionStatus.setItemText(1, QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Ожидание", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbActionStatus.setItemText(2, QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Закончено", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbActionStatus.setItemText(3, QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Отменено", None, QtGui.QApplication.UnicodeUTF8))
        self.chkActionSetPerson.setText(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Назначил", None, QtGui.QApplication.UnicodeUTF8))
        self.chkActionClass.setText(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Класс действия", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbActionClass.setItemText(0, QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Статус", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbActionClass.setItemText(1, QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Диагностика", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbActionClass.setItemText(2, QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Лечение", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbActionClass.setItemText(3, QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Прочие мероприятия", None, QtGui.QApplication.UnicodeUTF8))
        self.chkActionType.setText(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Тип действия", None, QtGui.QApplication.UnicodeUTF8))
        self.tabFilter.setTabText(self.tabFilter.indexOf(self.tabAction), QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Действие", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Для пациента выгружать данные о:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkIncludeClientEventInfo.setText(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Событии", None, QtGui.QApplication.UnicodeUTF8))
        self.chkIncludeClientWorkInfo.setText(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Занятости", None, QtGui.QApplication.UnicodeUTF8))
        self.chkIncludeClientAddressInfo.setText(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Адресе", None, QtGui.QApplication.UnicodeUTF8))
        self.chkIncludeClientDocumentInfo.setText(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Документе удост. личность", None, QtGui.QApplication.UnicodeUTF8))
        self.chkIncludeClientContactInfo.setText(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Контактах", None, QtGui.QApplication.UnicodeUTF8))
        self.tabFilter.setTabText(self.tabFilter.indexOf(self.tabAdditional), QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Дополнительно", None, QtGui.QApplication.UnicodeUTF8))
        self.btnResetFilter.setText(QtGui.QApplication.translate("ExportActionResult_Wizard_1", "Сброс", None, QtGui.QApplication.UnicodeUTF8))

from Orgs.OrgComboBox import CPolyclinicComboBox
from Events.ActionTypeComboBox import CActionTypeComboBox
from library.crbcombobox import CRBComboBox
from library.DateEdit import CDateEdit
from Orgs.PersonComboBoxEx import CPersonComboBoxEx

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ExportActionResult_Wizard_1 = QtGui.QDialog()
    ui = Ui_ExportActionResult_Wizard_1()
    ui.setupUi(ExportActionResult_Wizard_1)
    ExportActionResult_Wizard_1.show()
    sys.exit(app.exec_())

