# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExportToDbfDialog.ui'
#
# Created: Thu Oct 24 15:28:59 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ExportToDbfDialog(object):
    def setupUi(self, ExportToDbfDialog):
        ExportToDbfDialog.setObjectName(_fromUtf8("ExportToDbfDialog"))
        ExportToDbfDialog.resize(495, 504)
        self.gridLayout = QtGui.QGridLayout(ExportToDbfDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pbFiles = CProgressBar(ExportToDbfDialog)
        self.pbFiles.setProperty("value", 0)
        self.pbFiles.setAlignment(QtCore.Qt.AlignCenter)
        self.pbFiles.setTextVisible(True)
        self.pbFiles.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.pbFiles.setObjectName(_fromUtf8("pbFiles"))
        self.gridLayout.addWidget(self.pbFiles, 0, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(ExportToDbfDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabParameters = QtGui.QWidget()
        self.tabParameters.setObjectName(_fromUtf8("tabParameters"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabParameters)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.grpOutFileName = QtGui.QGroupBox(self.tabParameters)
        self.grpOutFileName.setObjectName(_fromUtf8("grpOutFileName"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.grpOutFileName)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtOutPath = QtGui.QLineEdit(self.grpOutFileName)
        self.edtOutPath.setEnabled(True)
        self.edtOutPath.setReadOnly(True)
        self.edtOutPath.setObjectName(_fromUtf8("edtOutPath"))
        self.horizontalLayout.addWidget(self.edtOutPath)
        self.btnBrowse = QtGui.QPushButton(self.grpOutFileName)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBrowse.sizePolicy().hasHeightForWidth())
        self.btnBrowse.setSizePolicy(sizePolicy)
        self.btnBrowse.setMaximumSize(QtCore.QSize(27, 27))
        self.btnBrowse.setBaseSize(QtCore.QSize(27, 27))
        self.btnBrowse.setObjectName(_fromUtf8("btnBrowse"))
        self.horizontalLayout.addWidget(self.btnBrowse)
        self.chkMakeArchive = QtGui.QCheckBox(self.grpOutFileName)
        self.chkMakeArchive.setObjectName(_fromUtf8("chkMakeArchive"))
        self.horizontalLayout.addWidget(self.chkMakeArchive)
        self.gridLayout_4.addWidget(self.grpOutFileName, 0, 0, 1, 1)
        self.gbExportTemplates = QtGui.QGroupBox(self.tabParameters)
        self.gbExportTemplates.setObjectName(_fromUtf8("gbExportTemplates"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gbExportTemplates)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.rbTemplateIndividual = QtGui.QRadioButton(self.gbExportTemplates)
        self.rbTemplateIndividual.setChecked(True)
        self.rbTemplateIndividual.setObjectName(_fromUtf8("rbTemplateIndividual"))
        self.gridLayout_2.addWidget(self.rbTemplateIndividual, 0, 0, 1, 1)
        self.cmbCodec = QtGui.QComboBox(self.gbExportTemplates)
        self.cmbCodec.setObjectName(_fromUtf8("cmbCodec"))
        self.cmbCodec.addItem(_fromUtf8(""))
        self.cmbCodec.addItem(_fromUtf8(""))
        self.cmbCodec.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbCodec, 2, 1, 1, 1)
        self.lblCodec = QtGui.QLabel(self.gbExportTemplates)
        self.lblCodec.setObjectName(_fromUtf8("lblCodec"))
        self.gridLayout_2.addWidget(self.lblCodec, 2, 0, 1, 1)
        self.cmbExportTemplates = QtGui.QComboBox(self.gbExportTemplates)
        self.cmbExportTemplates.setObjectName(_fromUtf8("cmbExportTemplates"))
        self.cmbExportTemplates.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbExportTemplates, 1, 0, 1, 2)
        self.rbTemplateGroups = QtGui.QRadioButton(self.gbExportTemplates)
        self.rbTemplateGroups.setObjectName(_fromUtf8("rbTemplateGroups"))
        self.gridLayout_2.addWidget(self.rbTemplateGroups, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.gbExportTemplates, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tabParameters)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.saTemplateParams = QtGui.QScrollArea(self.groupBox)
        self.saTemplateParams.setWidgetResizable(True)
        self.saTemplateParams.setObjectName(_fromUtf8("saTemplateParams"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 431, 181))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.paramNamesLayout = QtGui.QVBoxLayout()
        self.paramNamesLayout.setContentsMargins(-1, -1, 6, -1)
        self.paramNamesLayout.setObjectName(_fromUtf8("paramNamesLayout"))
        self.gridLayout_3.addLayout(self.paramNamesLayout, 0, 0, 1, 1)
        self.paramValuesLayout = QtGui.QVBoxLayout()
        self.paramValuesLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.paramValuesLayout.setObjectName(_fromUtf8("paramValuesLayout"))
        self.gridLayout_3.addLayout(self.paramValuesLayout, 0, 1, 1, 1)
        self.saTemplateParams.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.saTemplateParams)
        self.gridLayout_4.addWidget(self.groupBox, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabParameters, _fromUtf8(""))
        self.tabLog = QtGui.QWidget()
        self.tabLog.setObjectName(_fromUtf8("tabLog"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabLog)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.textLogs = QtGui.QTextEdit(self.tabLog)
        self.textLogs.setObjectName(_fromUtf8("textLogs"))
        self.gridLayout_5.addWidget(self.textLogs, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabLog, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 3)
        self.btnExport = QtGui.QPushButton(ExportToDbfDialog)
        self.btnExport.setObjectName(_fromUtf8("btnExport"))
        self.gridLayout.addWidget(self.btnExport, 0, 0, 1, 1)
        self.btnClose = QtGui.QPushButton(ExportToDbfDialog)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.gridLayout.addWidget(self.btnClose, 0, 2, 1, 1)
        self.pbRecords = CProgressBar(ExportToDbfDialog)
        self.pbRecords.setProperty("value", 0)
        self.pbRecords.setAlignment(QtCore.Qt.AlignCenter)
        self.pbRecords.setTextVisible(True)
        self.pbRecords.setObjectName(_fromUtf8("pbRecords"))
        self.gridLayout.addWidget(self.pbRecords, 1, 0, 1, 3)

        self.retranslateUi(ExportToDbfDialog)
        self.tabWidget.setCurrentIndex(0)
        self.cmbExportTemplates.setCurrentIndex(0)
        QtCore.QObject.connect(self.btnClose, QtCore.SIGNAL(_fromUtf8("clicked()")), ExportToDbfDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ExportToDbfDialog)

    def retranslateUi(self, ExportToDbfDialog):
        ExportToDbfDialog.setWindowTitle(_translate("ExportToDbfDialog", "ExportToDbfDialog", None))
        self.pbFiles.setFormat(_translate("ExportToDbfDialog", "Обработано шаблонов %v/%m", None))
        self.grpOutFileName.setTitle(_translate("ExportToDbfDialog", "Путь выгрузки:", None))
        self.edtOutPath.setText(_translate("ExportToDbfDialog", "<Не указан>", None))
        self.btnBrowse.setText(_translate("ExportToDbfDialog", "...", None))
        self.chkMakeArchive.setText(_translate("ExportToDbfDialog", "создать архив", None))
        self.gbExportTemplates.setTitle(_translate("ExportToDbfDialog", "Шаблоны выгрузки", None))
        self.rbTemplateIndividual.setText(_translate("ExportToDbfDialog", "Индивидуальные отчеты", None))
        self.cmbCodec.setItemText(0, _translate("ExportToDbfDialog", "utf-8", None))
        self.cmbCodec.setItemText(1, _translate("ExportToDbfDialog", "cp1251", None))
        self.cmbCodec.setItemText(2, _translate("ExportToDbfDialog", "cp866", None))
        self.lblCodec.setText(_translate("ExportToDbfDialog", "Кодировка файлов с шаблонами:", None))
        self.cmbExportTemplates.setItemText(0, _translate("ExportToDbfDialog", "<Не задано>", None))
        self.rbTemplateGroups.setText(_translate("ExportToDbfDialog", "Группы отчетов", None))
        self.groupBox.setTitle(_translate("ExportToDbfDialog", "Параметры шаблона", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabParameters), _translate("ExportToDbfDialog", "Параметры", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLog), _translate("ExportToDbfDialog", "Лог", None))
        self.btnExport.setText(_translate("ExportToDbfDialog", "Экспорт", None))
        self.btnClose.setText(_translate("ExportToDbfDialog", "Закрыть", None))
        self.pbRecords.setFormat(_translate("ExportToDbfDialog", "Обработано записей %v/%m", None))

from library.ProgressBar import CProgressBar
