# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\Exchange\ImportTariffsINFIS.ui'
#
# Created: Fri Jun 15 12:16:33 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(641, 637)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.edtFileName = QtGui.QLineEdit(Dialog)
        self.edtFileName.setText(_fromUtf8(""))
        self.edtFileName.setReadOnly(True)
        self.edtFileName.setObjectName(_fromUtf8("edtFileName"))
        self.gridLayout_2.addWidget(self.edtFileName, 0, 1, 1, 8)
        self.gbDublicates = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbDublicates.sizePolicy().hasHeightForWidth())
        self.gbDublicates.setSizePolicy(sizePolicy)
        self.gbDublicates.setObjectName(_fromUtf8("gbDublicates"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gbDublicates)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.chkUpdate = QtGui.QRadioButton(self.gbDublicates)
        self.chkUpdate.setChecked(True)
        self.chkUpdate.setObjectName(_fromUtf8("chkUpdate"))
        self.verticalLayout_4.addWidget(self.chkUpdate)
        self.chkSkip = QtGui.QRadioButton(self.gbDublicates)
        self.chkSkip.setObjectName(_fromUtf8("chkSkip"))
        self.verticalLayout_4.addWidget(self.chkSkip)
        self.chkAskUser = QtGui.QRadioButton(self.gbDublicates)
        self.chkAskUser.setObjectName(_fromUtf8("chkAskUser"))
        self.verticalLayout_4.addWidget(self.chkAskUser)
        self.gridLayout_2.addWidget(self.gbDublicates, 5, 0, 1, 2)
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_2.addWidget(self.progressBar, 6, 0, 1, 11)
        self.log = QtGui.QTextBrowser(Dialog)
        self.log.setObjectName(_fromUtf8("log"))
        self.gridLayout_2.addWidget(self.log, 7, 0, 1, 11)
        self.btnImport = QtGui.QPushButton(Dialog)
        self.btnImport.setObjectName(_fromUtf8("btnImport"))
        self.gridLayout_2.addWidget(self.btnImport, 8, 0, 1, 2)
        self.gbPeriod = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbPeriod.sizePolicy().hasHeightForWidth())
        self.gbPeriod.setSizePolicy(sizePolicy)
        self.gbPeriod.setObjectName(_fromUtf8("gbPeriod"))
        self.formLayout = QtGui.QFormLayout(self.gbPeriod)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lblBegDate = QtGui.QLabel(self.gbPeriod)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblBegDate)
        self.edtBegDate = CDateEdit(self.gbPeriod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.edtBegDate)
        self.lblEndDate = QtGui.QLabel(self.gbPeriod)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblEndDate)
        self.edtEndDate = CDateEdit(self.gbPeriod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.edtEndDate)
        self.gridLayout_2.addWidget(self.gbPeriod, 5, 2, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chkLoadMature = QtGui.QCheckBox(Dialog)
        self.chkLoadMature.setChecked(True)
        self.chkLoadMature.setObjectName(_fromUtf8("chkLoadMature"))
        self.verticalLayout.addWidget(self.chkLoadMature)
        self.chkLoadChildren = QtGui.QCheckBox(Dialog)
        self.chkLoadChildren.setChecked(True)
        self.chkLoadChildren.setObjectName(_fromUtf8("chkLoadChildren"))
        self.verticalLayout.addWidget(self.chkLoadChildren)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.chkLoadMes = QtGui.QCheckBox(Dialog)
        self.chkLoadMes.setObjectName(_fromUtf8("chkLoadMes"))
        self.verticalLayout.addWidget(self.chkLoadMes)
        self.chkLoadService = QtGui.QCheckBox(Dialog)
        self.chkLoadService.setObjectName(_fromUtf8("chkLoadService"))
        self.verticalLayout.addWidget(self.chkLoadService)
        self.chkLoadVisit = QtGui.QCheckBox(Dialog)
        self.chkLoadVisit.setObjectName(_fromUtf8("chkLoadVisit"))
        self.verticalLayout.addWidget(self.chkLoadVisit)
        self.gridLayout_2.addLayout(self.verticalLayout, 5, 3, 1, 8)
        self.btnView = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnView.sizePolicy().hasHeightForWidth())
        self.btnView.setSizePolicy(sizePolicy)
        self.btnView.setObjectName(_fromUtf8("btnView"))
        self.gridLayout_2.addWidget(self.btnView, 0, 10, 1, 1)
        self.btnClose = QtGui.QPushButton(Dialog)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.gridLayout_2.addWidget(self.btnClose, 8, 10, 1, 1)
        self.labelNum = QtGui.QLabel(Dialog)
        self.labelNum.setObjectName(_fromUtf8("labelNum"))
        self.gridLayout_2.addWidget(self.labelNum, 8, 8, 1, 1)
        self.btnSelectFile = QtGui.QToolButton(Dialog)
        self.btnSelectFile.setObjectName(_fromUtf8("btnSelectFile"))
        self.gridLayout_2.addWidget(self.btnSelectFile, 0, 9, 1, 1)
        self.gbRefBooks = QtGui.QGroupBox(Dialog)
        self.gbRefBooks.setObjectName(_fromUtf8("gbRefBooks"))
        self.gridLayout = QtGui.QGridLayout(self.gbRefBooks)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblRbProfile = QtGui.QLabel(self.gbRefBooks)
        self.lblRbProfile.setObjectName(_fromUtf8("lblRbProfile"))
        self.gridLayout.addWidget(self.lblRbProfile, 0, 0, 1, 1)
        self.edtRbProfileFileName = QtGui.QLineEdit(self.gbRefBooks)
        self.edtRbProfileFileName.setObjectName(_fromUtf8("edtRbProfileFileName"))
        self.gridLayout.addWidget(self.edtRbProfileFileName, 0, 1, 1, 1)
        self.btnViewRbProfile = QtGui.QPushButton(self.gbRefBooks)
        self.btnViewRbProfile.setEnabled(False)
        self.btnViewRbProfile.setObjectName(_fromUtf8("btnViewRbProfile"))
        self.gridLayout.addWidget(self.btnViewRbProfile, 0, 6, 1, 1)
        self.lblRbLoadedInfo = QtGui.QLabel(self.gbRefBooks)
        self.lblRbLoadedInfo.setText(_fromUtf8(""))
        self.lblRbLoadedInfo.setObjectName(_fromUtf8("lblRbLoadedInfo"))
        self.gridLayout.addWidget(self.lblRbLoadedInfo, 2, 0, 1, 7)
        self.btnLoadRbProfile = QtGui.QPushButton(self.gbRefBooks)
        self.btnLoadRbProfile.setEnabled(False)
        self.btnLoadRbProfile.setObjectName(_fromUtf8("btnLoadRbProfile"))
        self.gridLayout.addWidget(self.btnLoadRbProfile, 0, 3, 1, 1)
        self.btnSelectFileRbProfile = QtGui.QToolButton(self.gbRefBooks)
        self.btnSelectFileRbProfile.setObjectName(_fromUtf8("btnSelectFileRbProfile"))
        self.gridLayout.addWidget(self.btnSelectFileRbProfile, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.gbRefBooks, 1, 0, 1, 11)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.chkUpdate, self.chkSkip)
        Dialog.setTabOrder(self.chkSkip, self.chkAskUser)
        Dialog.setTabOrder(self.chkAskUser, self.edtBegDate)
        Dialog.setTabOrder(self.edtBegDate, self.edtEndDate)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Загрузка тарифов из ИНФИС", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "импортировать из", None, QtGui.QApplication.UnicodeUTF8))
        self.gbDublicates.setTitle(QtGui.QApplication.translate("Dialog", "Совпадающие записи", None, QtGui.QApplication.UnicodeUTF8))
        self.chkUpdate.setText(QtGui.QApplication.translate("Dialog", "Обновить", None, QtGui.QApplication.UnicodeUTF8))
        self.chkSkip.setText(QtGui.QApplication.translate("Dialog", "Пропустить", None, QtGui.QApplication.UnicodeUTF8))
        self.chkAskUser.setText(QtGui.QApplication.translate("Dialog", "Спросить у пользователя", None, QtGui.QApplication.UnicodeUTF8))
        self.btnImport.setText(QtGui.QApplication.translate("Dialog", "начать импортирование", None, QtGui.QApplication.UnicodeUTF8))
        self.gbPeriod.setTitle(QtGui.QApplication.translate("Dialog", "Период", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBegDate.setText(QtGui.QApplication.translate("Dialog", "с", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndDate.setText(QtGui.QApplication.translate("Dialog", "по", None, QtGui.QApplication.UnicodeUTF8))
        self.chkLoadMature.setText(QtGui.QApplication.translate("Dialog", "Загружать взрослые", None, QtGui.QApplication.UnicodeUTF8))
        self.chkLoadChildren.setText(QtGui.QApplication.translate("Dialog", "Загружать детские", None, QtGui.QApplication.UnicodeUTF8))
        self.chkLoadMes.setText(QtGui.QApplication.translate("Dialog", "Загружать МЭС", None, QtGui.QApplication.UnicodeUTF8))
        self.chkLoadService.setText(QtGui.QApplication.translate("Dialog", "Загружать услуги", None, QtGui.QApplication.UnicodeUTF8))
        self.chkLoadVisit.setText(QtGui.QApplication.translate("Dialog", "Загружать посещения", None, QtGui.QApplication.UnicodeUTF8))
        self.btnView.setText(QtGui.QApplication.translate("Dialog", "Просмотр", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClose.setText(QtGui.QApplication.translate("Dialog", "закрыть", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNum.setText(QtGui.QApplication.translate("Dialog", "всего записей в источнике:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelectFile.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.gbRefBooks.setTitle(QtGui.QApplication.translate("Dialog", "Справочники для определения типа тарификации", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRbProfile.setText(QtGui.QApplication.translate("Dialog", "Справочник профилей", None, QtGui.QApplication.UnicodeUTF8))
        self.btnViewRbProfile.setText(QtGui.QApplication.translate("Dialog", "Просмотр", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoadRbProfile.setText(QtGui.QApplication.translate("Dialog", "Загрузить", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelectFileRbProfile.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))

from library.DateEdit import CDateEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

