# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\Exchange\ImportFromSailDialog.ui'
#
# Created: Fri Jun 15 12:17:07 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ImportFromSailDialog(object):
    def setupUi(self, ImportFromSailDialog):
        ImportFromSailDialog.setObjectName(_fromUtf8("ImportFromSailDialog"))
        ImportFromSailDialog.resize(510, 503)
        self.gridLayout_3 = QtGui.QGridLayout(ImportFromSailDialog)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.grpImportOrgStructure = QtGui.QGroupBox(ImportFromSailDialog)
        self.grpImportOrgStructure.setCheckable(True)
        self.grpImportOrgStructure.setChecked(False)
        self.grpImportOrgStructure.setObjectName(_fromUtf8("grpImportOrgStructure"))
        self.gridLayout = QtGui.QGridLayout(self.grpImportOrgStructure)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edtFileNameOrgStructure = QtGui.QLineEdit(self.grpImportOrgStructure)
        self.edtFileNameOrgStructure.setObjectName(_fromUtf8("edtFileNameOrgStructure"))
        self.gridLayout.addWidget(self.edtFileNameOrgStructure, 2, 0, 1, 1)
        self.btnSelectFileOrgStructure = QtGui.QToolButton(self.grpImportOrgStructure)
        self.btnSelectFileOrgStructure.setObjectName(_fromUtf8("btnSelectFileOrgStructure"))
        self.gridLayout.addWidget(self.btnSelectFileOrgStructure, 2, 1, 1, 1)
        self.btnViewOrgStructure = QtGui.QPushButton(self.grpImportOrgStructure)
        self.btnViewOrgStructure.setObjectName(_fromUtf8("btnViewOrgStructure"))
        self.gridLayout.addWidget(self.btnViewOrgStructure, 2, 2, 1, 1)
        self.chkTypeOrgStructure = QtGui.QCheckBox(self.grpImportOrgStructure)
        self.chkTypeOrgStructure.setObjectName(_fromUtf8("chkTypeOrgStructure"))
        self.gridLayout.addWidget(self.chkTypeOrgStructure, 3, 0, 1, 1)
        self.chkHasHospitalBeds = QtGui.QCheckBox(self.grpImportOrgStructure)
        self.chkHasHospitalBeds.setObjectName(_fromUtf8("chkHasHospitalBeds"))
        self.gridLayout.addWidget(self.chkHasHospitalBeds, 3, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.grpImportOrgStructure)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.cmbOrgStructureCodeType = QtGui.QComboBox(self.grpImportOrgStructure)
        self.cmbOrgStructureCodeType.setObjectName(_fromUtf8("cmbOrgStructureCodeType"))
        self.cmbOrgStructureCodeType.addItem(_fromUtf8(""))
        self.cmbOrgStructureCodeType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbOrgStructureCodeType, 1, 1, 1, 2)
        self.chkUpdateOrgStructure = QtGui.QCheckBox(self.grpImportOrgStructure)
        self.chkUpdateOrgStructure.setObjectName(_fromUtf8("chkUpdateOrgStructure"))
        self.gridLayout.addWidget(self.chkUpdateOrgStructure, 0, 1, 1, 1)
        self.chkAttachOrgStructure = QtGui.QCheckBox(self.grpImportOrgStructure)
        self.chkAttachOrgStructure.setObjectName(_fromUtf8("chkAttachOrgStructure"))
        self.gridLayout.addWidget(self.chkAttachOrgStructure, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.grpImportOrgStructure)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.grpImportOrgStructure, 0, 0, 1, 3)
        self.grpImportPerson = QtGui.QGroupBox(ImportFromSailDialog)
        self.grpImportPerson.setCheckable(True)
        self.grpImportPerson.setChecked(False)
        self.grpImportPerson.setObjectName(_fromUtf8("grpImportPerson"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpImportPerson)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.edtFileNamePerson = QtGui.QLineEdit(self.grpImportPerson)
        self.edtFileNamePerson.setObjectName(_fromUtf8("edtFileNamePerson"))
        self.gridLayout_2.addWidget(self.edtFileNamePerson, 4, 0, 1, 1)
        self.btnSelectFilePerson = QtGui.QToolButton(self.grpImportPerson)
        self.btnSelectFilePerson.setObjectName(_fromUtf8("btnSelectFilePerson"))
        self.gridLayout_2.addWidget(self.btnSelectFilePerson, 4, 1, 1, 1)
        self.btnViewPerson = QtGui.QPushButton(self.grpImportPerson)
        self.btnViewPerson.setObjectName(_fromUtf8("btnViewPerson"))
        self.gridLayout_2.addWidget(self.btnViewPerson, 4, 2, 1, 1)
        self.cmbSpecialityCodeType = QtGui.QComboBox(self.grpImportPerson)
        self.cmbSpecialityCodeType.setObjectName(_fromUtf8("cmbSpecialityCodeType"))
        self.cmbSpecialityCodeType.addItem(_fromUtf8(""))
        self.cmbSpecialityCodeType.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbSpecialityCodeType, 2, 1, 1, 2)
        self.label = QtGui.QLabel(self.grpImportPerson)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.grpImportPerson)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.cmbPostCodeType = QtGui.QComboBox(self.grpImportPerson)
        self.cmbPostCodeType.setObjectName(_fromUtf8("cmbPostCodeType"))
        self.cmbPostCodeType.addItem(_fromUtf8(""))
        self.cmbPostCodeType.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbPostCodeType, 3, 1, 1, 2)
        self.cmbOrgstructureId = QtGui.QComboBox(self.grpImportPerson)
        self.cmbOrgstructureId.setObjectName(_fromUtf8("cmbOrgstructureId"))
        self.cmbOrgstructureId.addItem(_fromUtf8(""))
        self.cmbOrgstructureId.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbOrgstructureId, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.grpImportPerson)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.grpImportPerson, 1, 0, 2, 3)
        self.prbImport = QtGui.QProgressBar(ImportFromSailDialog)
        self.prbImport.setProperty("value", 24)
        self.prbImport.setOrientation(QtCore.Qt.Horizontal)
        self.prbImport.setObjectName(_fromUtf8("prbImport"))
        self.gridLayout_3.addWidget(self.prbImport, 3, 0, 1, 3)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.btnImport = QtGui.QPushButton(ImportFromSailDialog)
        self.btnImport.setObjectName(_fromUtf8("btnImport"))
        self.hboxlayout.addWidget(self.btnImport)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.btnClose = QtGui.QPushButton(ImportFromSailDialog)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.hboxlayout.addWidget(self.btnClose)
        self.gridLayout_3.addLayout(self.hboxlayout, 7, 0, 1, 3)
        self.stat = QtGui.QLabel(ImportFromSailDialog)
        self.stat.setText(_fromUtf8(""))
        self.stat.setObjectName(_fromUtf8("stat"))
        self.gridLayout_3.addWidget(self.stat, 6, 0, 1, 3)
        self.log = QtGui.QTextBrowser(ImportFromSailDialog)
        self.log.setObjectName(_fromUtf8("log"))
        self.gridLayout_3.addWidget(self.log, 4, 0, 1, 3)

        self.retranslateUi(ImportFromSailDialog)
        QtCore.QMetaObject.connectSlotsByName(ImportFromSailDialog)

    def retranslateUi(self, ImportFromSailDialog):
        ImportFromSailDialog.setWindowTitle(QtGui.QApplication.translate("ImportFromSailDialog", "Импорт из ИС \"Парус\"", None, QtGui.QApplication.UnicodeUTF8))
        self.grpImportOrgStructure.setTitle(QtGui.QApplication.translate("ImportFromSailDialog", "Подразделение", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelectFileOrgStructure.setText(QtGui.QApplication.translate("ImportFromSailDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnViewOrgStructure.setText(QtGui.QApplication.translate("ImportFromSailDialog", "Просмотреть", None, QtGui.QApplication.UnicodeUTF8))
        self.chkTypeOrgStructure.setText(QtGui.QApplication.translate("ImportFromSailDialog", "Заполнять тип подразделения", None, QtGui.QApplication.UnicodeUTF8))
        self.chkHasHospitalBeds.setText(QtGui.QApplication.translate("ImportFromSailDialog", "Заполнять \"Имеет койки\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ImportFromSailDialog", "Интерпретировать код подразделения как", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOrgStructureCodeType.setItemText(0, QtGui.QApplication.translate("ImportFromSailDialog", "Код основной", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOrgStructureCodeType.setItemText(1, QtGui.QApplication.translate("ImportFromSailDialog", "Код по бухгалтерии", None, QtGui.QApplication.UnicodeUTF8))
        self.chkUpdateOrgStructure.setText(QtGui.QApplication.translate("ImportFromSailDialog", "Обновлять", None, QtGui.QApplication.UnicodeUTF8))
        self.chkAttachOrgStructure.setText(QtGui.QApplication.translate("ImportFromSailDialog", "Добавлять", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ImportFromSailDialog", "Режим импорта", None, QtGui.QApplication.UnicodeUTF8))
        self.grpImportPerson.setTitle(QtGui.QApplication.translate("ImportFromSailDialog", "Персонал", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelectFilePerson.setText(QtGui.QApplication.translate("ImportFromSailDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnViewPerson.setText(QtGui.QApplication.translate("ImportFromSailDialog", "Просмотреть", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSpecialityCodeType.setItemText(0, QtGui.QApplication.translate("ImportFromSailDialog", "Код ОКСО", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSpecialityCodeType.setItemText(1, QtGui.QApplication.translate("ImportFromSailDialog", "Региональный код", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ImportFromSailDialog", "Интерпретировать поле SPECIALITY как", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ImportFromSailDialog", "Интерпретировать поле POST_ID как", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPostCodeType.setItemText(0, QtGui.QApplication.translate("ImportFromSailDialog", "Код ОКДП", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPostCodeType.setItemText(1, QtGui.QApplication.translate("ImportFromSailDialog", "Региональный код", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOrgstructureId.setItemText(0, QtGui.QApplication.translate("ImportFromSailDialog", "Да", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOrgstructureId.setItemText(1, QtGui.QApplication.translate("ImportFromSailDialog", "Нет", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ImportFromSailDialog", "Код подразделения является идентификатором", None, QtGui.QApplication.UnicodeUTF8))
        self.btnImport.setText(QtGui.QApplication.translate("ImportFromSailDialog", "начать импортирование", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClose.setText(QtGui.QApplication.translate("ImportFromSailDialog", "закрыть", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ImportFromSailDialog = QtGui.QDialog()
    ui = Ui_ImportFromSailDialog()
    ui.setupUi(ImportFromSailDialog)
    ImportFromSailDialog.show()
    sys.exit(app.exec_())

