# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\Accounting\CashBookDialog.ui'
#
# Created: Fri Jun 15 12:16:58 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CashBookDialog(object):
    def setupUi(self, CashBookDialog):
        CashBookDialog.setObjectName(_fromUtf8("CashBookDialog"))
        CashBookDialog.resize(718, 676)
        CashBookDialog.setSizeGripEnabled(True)
        self.verticalLayout_2 = QtGui.QVBoxLayout(CashBookDialog)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(CashBookDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabBook = QtGui.QWidget()
        self.tabBook.setObjectName(_fromUtf8("tabBook"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabBook)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitterBook = QtGui.QSplitter(self.tabBook)
        self.splitterBook.setOrientation(QtCore.Qt.Horizontal)
        self.splitterBook.setChildrenCollapsible(False)
        self.splitterBook.setObjectName(_fromUtf8("splitterBook"))
        self.grpBookFilter = QtGui.QGroupBox(self.splitterBook)
        self.grpBookFilter.setObjectName(_fromUtf8("grpBookFilter"))
        self.gridLayout = QtGui.QGridLayout(self.grpBookFilter)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblFilterBegDate = QtGui.QLabel(self.grpBookFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFilterBegDate.sizePolicy().hasHeightForWidth())
        self.lblFilterBegDate.setSizePolicy(sizePolicy)
        self.lblFilterBegDate.setObjectName(_fromUtf8("lblFilterBegDate"))
        self.gridLayout.addWidget(self.lblFilterBegDate, 0, 0, 1, 1)
        self.edtFilterBegDate = CDateEdit(self.grpBookFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterBegDate.sizePolicy().hasHeightForWidth())
        self.edtFilterBegDate.setSizePolicy(sizePolicy)
        self.edtFilterBegDate.setObjectName(_fromUtf8("edtFilterBegDate"))
        self.gridLayout.addWidget(self.edtFilterBegDate, 0, 1, 1, 1)
        self.lblFilterEndDate = QtGui.QLabel(self.grpBookFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFilterEndDate.sizePolicy().hasHeightForWidth())
        self.lblFilterEndDate.setSizePolicy(sizePolicy)
        self.lblFilterEndDate.setObjectName(_fromUtf8("lblFilterEndDate"))
        self.gridLayout.addWidget(self.lblFilterEndDate, 1, 0, 1, 1)
        self.edtFilterEndDate = CDateEdit(self.grpBookFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterEndDate.sizePolicy().hasHeightForWidth())
        self.edtFilterEndDate.setSizePolicy(sizePolicy)
        self.edtFilterEndDate.setObjectName(_fromUtf8("edtFilterEndDate"))
        self.gridLayout.addWidget(self.edtFilterEndDate, 1, 1, 1, 1)
        self.lblFilterCashBox = QtGui.QLabel(self.grpBookFilter)
        self.lblFilterCashBox.setObjectName(_fromUtf8("lblFilterCashBox"))
        self.gridLayout.addWidget(self.lblFilterCashBox, 2, 0, 1, 1)
        self.edtFilterCashBox = QtGui.QLineEdit(self.grpBookFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterCashBox.sizePolicy().hasHeightForWidth())
        self.edtFilterCashBox.setSizePolicy(sizePolicy)
        self.edtFilterCashBox.setObjectName(_fromUtf8("edtFilterCashBox"))
        self.gridLayout.addWidget(self.edtFilterCashBox, 2, 1, 1, 1)
        self.lblFilterCashKeeper = QtGui.QLabel(self.grpBookFilter)
        self.lblFilterCashKeeper.setObjectName(_fromUtf8("lblFilterCashKeeper"))
        self.gridLayout.addWidget(self.lblFilterCashKeeper, 3, 0, 1, 1)
        self.cmbFilterCashKeeper = CPersonComboBoxEx(self.grpBookFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterCashKeeper.sizePolicy().hasHeightForWidth())
        self.cmbFilterCashKeeper.setSizePolicy(sizePolicy)
        self.cmbFilterCashKeeper.setObjectName(_fromUtf8("cmbFilterCashKeeper"))
        self.gridLayout.addWidget(self.cmbFilterCashKeeper, 3, 1, 1, 1)
        self.lblFilterCashOperation = QtGui.QLabel(self.grpBookFilter)
        self.lblFilterCashOperation.setObjectName(_fromUtf8("lblFilterCashOperation"))
        self.gridLayout.addWidget(self.lblFilterCashOperation, 4, 0, 1, 1)
        self.cmbFilterCashOperation = CRBComboBox(self.grpBookFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterCashOperation.sizePolicy().hasHeightForWidth())
        self.cmbFilterCashOperation.setSizePolicy(sizePolicy)
        self.cmbFilterCashOperation.setObjectName(_fromUtf8("cmbFilterCashOperation"))
        self.gridLayout.addWidget(self.cmbFilterCashOperation, 4, 1, 1, 1)
        self.lblFilterEventPurpose = QtGui.QLabel(self.grpBookFilter)
        self.lblFilterEventPurpose.setObjectName(_fromUtf8("lblFilterEventPurpose"))
        self.gridLayout.addWidget(self.lblFilterEventPurpose, 5, 0, 1, 1)
        self.cmbFilterEventPurpose = CRBComboBox(self.grpBookFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterEventPurpose.sizePolicy().hasHeightForWidth())
        self.cmbFilterEventPurpose.setSizePolicy(sizePolicy)
        self.cmbFilterEventPurpose.setObjectName(_fromUtf8("cmbFilterEventPurpose"))
        self.gridLayout.addWidget(self.cmbFilterEventPurpose, 5, 1, 1, 1)
        self.lblFilterEventType = QtGui.QLabel(self.grpBookFilter)
        self.lblFilterEventType.setObjectName(_fromUtf8("lblFilterEventType"))
        self.gridLayout.addWidget(self.lblFilterEventType, 6, 0, 1, 1)
        self.cmbFilterEventType = CRBComboBox(self.grpBookFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterEventType.sizePolicy().hasHeightForWidth())
        self.cmbFilterEventType.setSizePolicy(sizePolicy)
        self.cmbFilterEventType.setObjectName(_fromUtf8("cmbFilterEventType"))
        self.gridLayout.addWidget(self.cmbFilterEventType, 6, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bbxFilter = QtGui.QDialogButtonBox(self.grpBookFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bbxFilter.sizePolicy().hasHeightForWidth())
        self.bbxFilter.setSizePolicy(sizePolicy)
        self.bbxFilter.setOrientation(QtCore.Qt.Horizontal)
        self.bbxFilter.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.bbxFilter.setCenterButtons(False)
        self.bbxFilter.setObjectName(_fromUtf8("bbxFilter"))
        self.horizontalLayout.addWidget(self.bbxFilter)
        self.gridLayout.addLayout(self.horizontalLayout, 12, 0, 1, 2)
        self.cmbFilterPerson = CPersonComboBoxEx(self.grpBookFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterPerson.sizePolicy().hasHeightForWidth())
        self.cmbFilterPerson.setSizePolicy(sizePolicy)
        self.cmbFilterPerson.setObjectName(_fromUtf8("cmbFilterPerson"))
        self.gridLayout.addWidget(self.cmbFilterPerson, 9, 1, 1, 1)
        self.cmbFilterOrgStructure = COrgStructureComboBox(self.grpBookFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbFilterOrgStructure.setSizePolicy(sizePolicy)
        self.cmbFilterOrgStructure.setObjectName(_fromUtf8("cmbFilterOrgStructure"))
        self.gridLayout.addWidget(self.cmbFilterOrgStructure, 8, 1, 1, 1)
        self.lblFilterOrgStructure = QtGui.QLabel(self.grpBookFilter)
        self.lblFilterOrgStructure.setObjectName(_fromUtf8("lblFilterOrgStructure"))
        self.gridLayout.addWidget(self.lblFilterOrgStructure, 8, 0, 1, 1)
        self.lblFilterPerson = QtGui.QLabel(self.grpBookFilter)
        self.lblFilterPerson.setObjectName(_fromUtf8("lblFilterPerson"))
        self.gridLayout.addWidget(self.lblFilterPerson, 9, 0, 1, 1)
        self.widget = QtGui.QWidget(self.splitterBook)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tblCashItems = CTableView(self.widget)
        self.tblCashItems.setObjectName(_fromUtf8("tblCashItems"))
        self.verticalLayout.addWidget(self.tblCashItems)
        self.groupAccount = QtGui.QGroupBox(self.widget)
        self.groupAccount.setObjectName(_fromUtf8("groupAccount"))
        self._2 = QtGui.QHBoxLayout(self.groupAccount)
        self._2.setSpacing(4)
        self._2.setMargin(4)
        self._2.setObjectName(_fromUtf8("_2"))
        self.lblCashItemsCount = QtGui.QLabel(self.groupAccount)
        self.lblCashItemsCount.setObjectName(_fromUtf8("lblCashItemsCount"))
        self._2.addWidget(self.lblCashItemsCount)
        self.edtCashItemsCount = QtGui.QLineEdit(self.groupAccount)
        self.edtCashItemsCount.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edtCashItemsCount.setAlignment(QtCore.Qt.AlignRight)
        self.edtCashItemsCount.setReadOnly(True)
        self.edtCashItemsCount.setObjectName(_fromUtf8("edtCashItemsCount"))
        self._2.addWidget(self.edtCashItemsCount)
        self.lblIncome = QtGui.QLabel(self.groupAccount)
        self.lblIncome.setObjectName(_fromUtf8("lblIncome"))
        self._2.addWidget(self.lblIncome)
        self.edtIncome = QtGui.QLineEdit(self.groupAccount)
        self.edtIncome.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edtIncome.setAlignment(QtCore.Qt.AlignRight)
        self.edtIncome.setReadOnly(True)
        self.edtIncome.setObjectName(_fromUtf8("edtIncome"))
        self._2.addWidget(self.edtIncome)
        self.lblOutcome = QtGui.QLabel(self.groupAccount)
        self.lblOutcome.setObjectName(_fromUtf8("lblOutcome"))
        self._2.addWidget(self.lblOutcome)
        self.edtOutcome = QtGui.QLineEdit(self.groupAccount)
        self.edtOutcome.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edtOutcome.setAlignment(QtCore.Qt.AlignRight)
        self.edtOutcome.setReadOnly(True)
        self.edtOutcome.setObjectName(_fromUtf8("edtOutcome"))
        self._2.addWidget(self.edtOutcome)
        self.verticalLayout.addWidget(self.groupAccount)
        self.gridLayout_2.addWidget(self.splitterBook, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabBook, _fromUtf8(""))
        self.tabPayment = QtGui.QWidget()
        self.tabPayment.setObjectName(_fromUtf8("tabPayment"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabPayment)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitterPayment = QtGui.QSplitter(self.tabPayment)
        self.splitterPayment.setOrientation(QtCore.Qt.Horizontal)
        self.splitterPayment.setChildrenCollapsible(False)
        self.splitterPayment.setObjectName(_fromUtf8("splitterPayment"))
        self.grpPaymentFilter = QtGui.QGroupBox(self.splitterPayment)
        self.grpPaymentFilter.setObjectName(_fromUtf8("grpPaymentFilter"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grpPaymentFilter)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.edtPaymentFilterBirthDay = CDateEdit(self.grpPaymentFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPaymentFilterBirthDay.sizePolicy().hasHeightForWidth())
        self.edtPaymentFilterBirthDay.setSizePolicy(sizePolicy)
        self.edtPaymentFilterBirthDay.setObjectName(_fromUtf8("edtPaymentFilterBirthDay"))
        self.gridLayout_3.addWidget(self.edtPaymentFilterBirthDay, 6, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 13, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.bbxPaymentFilter = QtGui.QDialogButtonBox(self.grpPaymentFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bbxPaymentFilter.sizePolicy().hasHeightForWidth())
        self.bbxPaymentFilter.setSizePolicy(sizePolicy)
        self.bbxPaymentFilter.setOrientation(QtCore.Qt.Horizontal)
        self.bbxPaymentFilter.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.bbxPaymentFilter.setCenterButtons(False)
        self.bbxPaymentFilter.setObjectName(_fromUtf8("bbxPaymentFilter"))
        self.horizontalLayout_2.addWidget(self.bbxPaymentFilter)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 14, 0, 1, 2)
        self.lblPaymentFilterAccountingSystem = QtGui.QLabel(self.grpPaymentFilter)
        self.lblPaymentFilterAccountingSystem.setObjectName(_fromUtf8("lblPaymentFilterAccountingSystem"))
        self.gridLayout_3.addWidget(self.lblPaymentFilterAccountingSystem, 0, 0, 1, 1)
        self.cmbPaymentFilterAccountingSystem = CRBComboBox(self.grpPaymentFilter)
        self.cmbPaymentFilterAccountingSystem.setEnabled(False)
        self.cmbPaymentFilterAccountingSystem.setObjectName(_fromUtf8("cmbPaymentFilterAccountingSystem"))
        self.gridLayout_3.addWidget(self.cmbPaymentFilterAccountingSystem, 0, 1, 1, 1)
        self.lblPaymentFilterClientCode = QtGui.QLabel(self.grpPaymentFilter)
        self.lblPaymentFilterClientCode.setObjectName(_fromUtf8("lblPaymentFilterClientCode"))
        self.gridLayout_3.addWidget(self.lblPaymentFilterClientCode, 1, 0, 1, 1)
        self.edtPaymentFilterClientCode = QtGui.QLineEdit(self.grpPaymentFilter)
        self.edtPaymentFilterClientCode.setObjectName(_fromUtf8("edtPaymentFilterClientCode"))
        self.gridLayout_3.addWidget(self.edtPaymentFilterClientCode, 1, 1, 1, 1)
        self.lblPaymentFilterPatrName = QtGui.QLabel(self.grpPaymentFilter)
        self.lblPaymentFilterPatrName.setObjectName(_fromUtf8("lblPaymentFilterPatrName"))
        self.gridLayout_3.addWidget(self.lblPaymentFilterPatrName, 5, 0, 1, 1)
        self.edtPaymentFilterPatrName = QtGui.QLineEdit(self.grpPaymentFilter)
        self.edtPaymentFilterPatrName.setObjectName(_fromUtf8("edtPaymentFilterPatrName"))
        self.gridLayout_3.addWidget(self.edtPaymentFilterPatrName, 5, 1, 1, 1)
        self.lblPaymentFilterFirstName = QtGui.QLabel(self.grpPaymentFilter)
        self.lblPaymentFilterFirstName.setObjectName(_fromUtf8("lblPaymentFilterFirstName"))
        self.gridLayout_3.addWidget(self.lblPaymentFilterFirstName, 4, 0, 1, 1)
        self.edtPaymentFilterFirstName = QtGui.QLineEdit(self.grpPaymentFilter)
        self.edtPaymentFilterFirstName.setObjectName(_fromUtf8("edtPaymentFilterFirstName"))
        self.gridLayout_3.addWidget(self.edtPaymentFilterFirstName, 4, 1, 1, 1)
        self.edtPaymentFilterLastName = QtGui.QLineEdit(self.grpPaymentFilter)
        self.edtPaymentFilterLastName.setObjectName(_fromUtf8("edtPaymentFilterLastName"))
        self.gridLayout_3.addWidget(self.edtPaymentFilterLastName, 3, 1, 1, 1)
        self.lblPaymentFilterLastName = QtGui.QLabel(self.grpPaymentFilter)
        self.lblPaymentFilterLastName.setObjectName(_fromUtf8("lblPaymentFilterLastName"))
        self.gridLayout_3.addWidget(self.lblPaymentFilterLastName, 3, 0, 1, 1)
        self.lblPaymentFilterBirthDay = QtGui.QLabel(self.grpPaymentFilter)
        self.lblPaymentFilterBirthDay.setObjectName(_fromUtf8("lblPaymentFilterBirthDay"))
        self.gridLayout_3.addWidget(self.lblPaymentFilterBirthDay, 6, 0, 1, 1)
        self.line = QtGui.QFrame(self.grpPaymentFilter)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 8, 0, 1, 2)
        self.lblPaymentFilterEventId = QtGui.QLabel(self.grpPaymentFilter)
        self.lblPaymentFilterEventId.setObjectName(_fromUtf8("lblPaymentFilterEventId"))
        self.gridLayout_3.addWidget(self.lblPaymentFilterEventId, 11, 0, 1, 1)
        self.lblPaymentFilterExternalEventId = QtGui.QLabel(self.grpPaymentFilter)
        self.lblPaymentFilterExternalEventId.setObjectName(_fromUtf8("lblPaymentFilterExternalEventId"))
        self.gridLayout_3.addWidget(self.lblPaymentFilterExternalEventId, 12, 0, 1, 1)
        self.edtPaymentFilterEventId = QtGui.QLineEdit(self.grpPaymentFilter)
        self.edtPaymentFilterEventId.setObjectName(_fromUtf8("edtPaymentFilterEventId"))
        self.gridLayout_3.addWidget(self.edtPaymentFilterEventId, 11, 1, 1, 1)
        self.edtPaymentFilterExternalEventId = QtGui.QLineEdit(self.grpPaymentFilter)
        self.edtPaymentFilterExternalEventId.setObjectName(_fromUtf8("edtPaymentFilterExternalEventId"))
        self.gridLayout_3.addWidget(self.edtPaymentFilterExternalEventId, 12, 1, 1, 1)
        self.cmbPaymentFilterSex = QtGui.QComboBox(self.grpPaymentFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPaymentFilterSex.sizePolicy().hasHeightForWidth())
        self.cmbPaymentFilterSex.setSizePolicy(sizePolicy)
        self.cmbPaymentFilterSex.setObjectName(_fromUtf8("cmbPaymentFilterSex"))
        self.cmbPaymentFilterSex.addItem(_fromUtf8(""))
        self.cmbPaymentFilterSex.setItemText(0, _fromUtf8(""))
        self.cmbPaymentFilterSex.addItem(_fromUtf8(""))
        self.cmbPaymentFilterSex.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbPaymentFilterSex, 7, 1, 1, 1)
        self.lblPaymentFilterSex = QtGui.QLabel(self.grpPaymentFilter)
        self.lblPaymentFilterSex.setObjectName(_fromUtf8("lblPaymentFilterSex"))
        self.gridLayout_3.addWidget(self.lblPaymentFilterSex, 7, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.splitterPayment)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.txtClientInfoBrowser = CTextBrowser(self.splitter)
        self.txtClientInfoBrowser.setMinimumSize(QtCore.QSize(0, 100))
        self.txtClientInfoBrowser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtClientInfoBrowser.setReadOnly(True)
        self.txtClientInfoBrowser.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.tblClients = CTableView(self.splitter)
        self.tblClients.setObjectName(_fromUtf8("tblClients"))
        self.tblEvents = CTableView(self.splitter)
        self.tblEvents.setObjectName(_fromUtf8("tblEvents"))
        self.gridLayout_4.addWidget(self.splitterPayment, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabPayment, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(CashBookDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.lblFilterBegDate.setBuddy(self.edtFilterBegDate)
        self.lblFilterEndDate.setBuddy(self.edtFilterEndDate)
        self.lblFilterCashBox.setBuddy(self.edtFilterCashBox)
        self.lblFilterCashKeeper.setBuddy(self.cmbFilterCashKeeper)
        self.lblFilterCashOperation.setBuddy(self.cmbFilterCashOperation)
        self.lblFilterEventPurpose.setBuddy(self.cmbFilterEventPurpose)
        self.lblFilterEventType.setBuddy(self.cmbFilterEventType)
        self.lblFilterOrgStructure.setBuddy(self.cmbFilterOrgStructure)
        self.lblFilterPerson.setBuddy(self.cmbFilterPerson)
        self.lblCashItemsCount.setBuddy(self.edtCashItemsCount)
        self.lblIncome.setBuddy(self.edtIncome)
        self.lblOutcome.setBuddy(self.edtOutcome)
        self.lblPaymentFilterAccountingSystem.setBuddy(self.cmbPaymentFilterAccountingSystem)
        self.lblPaymentFilterClientCode.setBuddy(self.edtPaymentFilterClientCode)
        self.lblPaymentFilterPatrName.setBuddy(self.edtPaymentFilterPatrName)
        self.lblPaymentFilterFirstName.setBuddy(self.edtPaymentFilterFirstName)
        self.lblPaymentFilterLastName.setBuddy(self.edtPaymentFilterLastName)
        self.lblPaymentFilterBirthDay.setBuddy(self.edtPaymentFilterBirthDay)
        self.lblPaymentFilterEventId.setBuddy(self.edtPaymentFilterEventId)
        self.lblPaymentFilterExternalEventId.setBuddy(self.edtPaymentFilterExternalEventId)

        self.retranslateUi(CashBookDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CashBookDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CashBookDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CashBookDialog)
        CashBookDialog.setTabOrder(self.tabWidget, self.edtFilterBegDate)
        CashBookDialog.setTabOrder(self.edtFilterBegDate, self.edtFilterEndDate)
        CashBookDialog.setTabOrder(self.edtFilterEndDate, self.edtFilterCashBox)
        CashBookDialog.setTabOrder(self.edtFilterCashBox, self.cmbFilterCashKeeper)
        CashBookDialog.setTabOrder(self.cmbFilterCashKeeper, self.cmbFilterCashOperation)
        CashBookDialog.setTabOrder(self.cmbFilterCashOperation, self.cmbFilterEventPurpose)
        CashBookDialog.setTabOrder(self.cmbFilterEventPurpose, self.cmbFilterEventType)
        CashBookDialog.setTabOrder(self.cmbFilterEventType, self.cmbFilterOrgStructure)
        CashBookDialog.setTabOrder(self.cmbFilterOrgStructure, self.cmbFilterPerson)
        CashBookDialog.setTabOrder(self.cmbFilterPerson, self.bbxFilter)
        CashBookDialog.setTabOrder(self.bbxFilter, self.tblCashItems)
        CashBookDialog.setTabOrder(self.tblCashItems, self.cmbPaymentFilterAccountingSystem)
        CashBookDialog.setTabOrder(self.cmbPaymentFilterAccountingSystem, self.edtPaymentFilterClientCode)
        CashBookDialog.setTabOrder(self.edtPaymentFilterClientCode, self.edtPaymentFilterLastName)
        CashBookDialog.setTabOrder(self.edtPaymentFilterLastName, self.edtPaymentFilterFirstName)
        CashBookDialog.setTabOrder(self.edtPaymentFilterFirstName, self.edtPaymentFilterPatrName)
        CashBookDialog.setTabOrder(self.edtPaymentFilterPatrName, self.edtPaymentFilterBirthDay)
        CashBookDialog.setTabOrder(self.edtPaymentFilterBirthDay, self.cmbPaymentFilterSex)
        CashBookDialog.setTabOrder(self.cmbPaymentFilterSex, self.edtPaymentFilterEventId)
        CashBookDialog.setTabOrder(self.edtPaymentFilterEventId, self.edtPaymentFilterExternalEventId)
        CashBookDialog.setTabOrder(self.edtPaymentFilterExternalEventId, self.bbxPaymentFilter)
        CashBookDialog.setTabOrder(self.bbxPaymentFilter, self.txtClientInfoBrowser)
        CashBookDialog.setTabOrder(self.txtClientInfoBrowser, self.tblClients)
        CashBookDialog.setTabOrder(self.tblClients, self.tblEvents)
        CashBookDialog.setTabOrder(self.tblEvents, self.buttonBox)

    def retranslateUi(self, CashBookDialog):
        CashBookDialog.setWindowTitle(QtGui.QApplication.translate("CashBookDialog", "Журнал кассовых операций", None, QtGui.QApplication.UnicodeUTF8))
        self.grpBookFilter.setTitle(QtGui.QApplication.translate("CashBookDialog", "Фильтр", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFilterBegDate.setText(QtGui.QApplication.translate("CashBookDialog", "&С", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFilterEndDate.setText(QtGui.QApplication.translate("CashBookDialog", "&По", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFilterCashBox.setText(QtGui.QApplication.translate("CashBookDialog", "&Касса", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFilterCashKeeper.setText(QtGui.QApplication.translate("CashBookDialog", "Касси&р", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFilterCashOperation.setText(QtGui.QApplication.translate("CashBookDialog", "Кассовая &операция", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFilterEventPurpose.setText(QtGui.QApplication.translate("CashBookDialog", "&Назначение обращения", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFilterEventType.setText(QtGui.QApplication.translate("CashBookDialog", "&Тип обращения", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFilterOrgStructure.setText(QtGui.QApplication.translate("CashBookDialog", "&Подразделение", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFilterPerson.setText(QtGui.QApplication.translate("CashBookDialog", "&Врач", None, QtGui.QApplication.UnicodeUTF8))
        self.groupAccount.setTitle(QtGui.QApplication.translate("CashBookDialog", "Итого", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCashItemsCount.setText(QtGui.QApplication.translate("CashBookDialog", "Позиций", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIncome.setText(QtGui.QApplication.translate("CashBookDialog", "Приход", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOutcome.setText(QtGui.QApplication.translate("CashBookDialog", "Расход", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBook), QtGui.QApplication.translate("CashBookDialog", "Журнал", None, QtGui.QApplication.UnicodeUTF8))
        self.grpPaymentFilter.setTitle(QtGui.QApplication.translate("CashBookDialog", "Фильтр", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPaymentFilterAccountingSystem.setText(QtGui.QApplication.translate("CashBookDialog", "Тип идентификатора", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPaymentFilterClientCode.setText(QtGui.QApplication.translate("CashBookDialog", "Код пациента", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPaymentFilterPatrName.setText(QtGui.QApplication.translate("CashBookDialog", "Отчество", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPaymentFilterFirstName.setText(QtGui.QApplication.translate("CashBookDialog", "Имя", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPaymentFilterLastName.setText(QtGui.QApplication.translate("CashBookDialog", "Фамилия", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPaymentFilterBirthDay.setText(QtGui.QApplication.translate("CashBookDialog", "Дата рождения", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPaymentFilterEventId.setText(QtGui.QApplication.translate("CashBookDialog", "Код события", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPaymentFilterExternalEventId.setText(QtGui.QApplication.translate("CashBookDialog", "Внешний код события", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPaymentFilterSex.setItemText(1, QtGui.QApplication.translate("CashBookDialog", "М", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPaymentFilterSex.setItemText(2, QtGui.QApplication.translate("CashBookDialog", "Ж", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPaymentFilterSex.setText(QtGui.QApplication.translate("CashBookDialog", "Пол", None, QtGui.QApplication.UnicodeUTF8))
        self.txtClientInfoBrowser.setHtml(QtGui.QApplication.translate("CashBookDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Tahoma\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPayment), QtGui.QApplication.translate("CashBookDialog", "Расчёт", None, QtGui.QApplication.UnicodeUTF8))

from library.crbcombobox import CRBComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.TextBrowser import CTextBrowser
from library.TableView import CTableView
from library.DateEdit import CDateEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    CashBookDialog = QtGui.QDialog()
    ui = Ui_CashBookDialog()
    ui.setupUi(CashBookDialog)
    CashBookDialog.show()
    sys.exit(app.exec_())

