# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F001.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_F001Dialog(object):
    def setupUi(self, F001Dialog):
        F001Dialog.setObjectName(_fromUtf8("F001Dialog"))
        F001Dialog.resize(1140, 582)
        self.verticalLayout = QtGui.QVBoxLayout(F001Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.sptTopLevel = QtGui.QSplitter(F001Dialog)
        self.sptTopLevel.setOrientation(QtCore.Qt.Vertical)
        self.sptTopLevel.setObjectName(_fromUtf8("sptTopLevel"))
        self.txtClientInfoBrowser = CTextBrowser(self.sptTopLevel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtClientInfoBrowser.sizePolicy().hasHeightForWidth())
        self.txtClientInfoBrowser.setSizePolicy(sizePolicy)
        self.txtClientInfoBrowser.setMinimumSize(QtCore.QSize(0, 100))
        self.txtClientInfoBrowser.setMaximumSize(QtCore.QSize(16777215, 130))
        self.txtClientInfoBrowser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.tabWidget = QtGui.QTabWidget(self.sptTopLevel)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabToken = QtGui.QWidget()
        self.tabToken.setObjectName(_fromUtf8("tabToken"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabToken)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.scrollArea = QtGui.QScrollArea(self.tabToken)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1088, 947))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter_3 = QtGui.QSplitter(self.scrollAreaWidgetContents)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.splitter_2 = QtGui.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.grpBase = QtGui.QGroupBox(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpBase.sizePolicy().hasHeightForWidth())
        self.grpBase.setSizePolicy(sizePolicy)
        self.grpBase.setObjectName(_fromUtf8("grpBase"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpBase)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cmbClientPolicy = CClientPolicyComboBox(self.grpBase)
        self.cmbClientPolicy.setObjectName(_fromUtf8("cmbClientPolicy"))
        self.gridLayout_2.addWidget(self.cmbClientPolicy, 3, 1, 1, 1)
        self.chkExposeConfirmed = QtGui.QCheckBox(self.grpBase)
        self.chkExposeConfirmed.setObjectName(_fromUtf8("chkExposeConfirmed"))
        self.gridLayout_2.addWidget(self.chkExposeConfirmed, 2, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 12, 0, 1, 1)
        self.chkZNOFirst = QtGui.QCheckBox(self.grpBase)
        self.chkZNOFirst.setObjectName(_fromUtf8("chkZNOFirst"))
        self.gridLayout_2.addWidget(self.chkZNOFirst, 14, 0, 1, 2)
        self.cmbGoal = CRBComboBox(self.grpBase)
        self.cmbGoal.setObjectName(_fromUtf8("cmbGoal"))
        self.gridLayout_2.addWidget(self.cmbGoal, 11, 1, 1, 1)
        self.lblGoal = QtGui.QLabel(self.grpBase)
        self.lblGoal.setObjectName(_fromUtf8("lblGoal"))
        self.gridLayout_2.addWidget(self.lblGoal, 11, 0, 1, 1)
        self.lblSetPerson = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSetPerson.sizePolicy().hasHeightForWidth())
        self.lblSetPerson.setSizePolicy(sizePolicy)
        self.lblSetPerson.setObjectName(_fromUtf8("lblSetPerson"))
        self.gridLayout_2.addWidget(self.lblSetPerson, 6, 0, 1, 1)
        self.cmbResult = CRBComboBox(self.grpBase)
        self.cmbResult.setObjectName(_fromUtf8("cmbResult"))
        self.gridLayout_2.addWidget(self.cmbResult, 9, 1, 1, 1)
        self.lblBegDate = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDate.sizePolicy().hasHeightForWidth())
        self.lblBegDate.setSizePolicy(sizePolicy)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout_2.addWidget(self.lblBegDate, 7, 0, 1, 1)
        self.lblEndDate = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDate.sizePolicy().hasHeightForWidth())
        self.lblEndDate.setSizePolicy(sizePolicy)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout_2.addWidget(self.lblEndDate, 8, 0, 1, 1)
        self.cmbSetPerson = CPersonComboBoxEx(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSetPerson.sizePolicy().hasHeightForWidth())
        self.cmbSetPerson.setSizePolicy(sizePolicy)
        self.cmbSetPerson.setObjectName(_fromUtf8("cmbSetPerson"))
        self.gridLayout_2.addWidget(self.cmbSetPerson, 6, 1, 1, 1)
        self.cmbContract = CContractComboBox(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbContract.sizePolicy().hasHeightForWidth())
        self.cmbContract.setSizePolicy(sizePolicy)
        self.cmbContract.setFrame(True)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.cmbContract.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbContract, 0, 0, 1, 2)
        self.chkZNOMorph = QtGui.QCheckBox(self.grpBase)
        self.chkZNOMorph.setObjectName(_fromUtf8("chkZNOMorph"))
        self.gridLayout_2.addWidget(self.chkZNOMorph, 15, 0, 1, 2)
        self.lblClientPolicy = QtGui.QLabel(self.grpBase)
        self.lblClientPolicy.setObjectName(_fromUtf8("lblClientPolicy"))
        self.gridLayout_2.addWidget(self.lblClientPolicy, 3, 0, 1, 1)
        self.lblResult = QtGui.QLabel(self.grpBase)
        self.lblResult.setObjectName(_fromUtf8("lblResult"))
        self.gridLayout_2.addWidget(self.lblResult, 9, 0, 1, 1)
        self.frmEndDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmEndDateTime.sizePolicy().hasHeightForWidth())
        self.frmEndDateTime.setSizePolicy(sizePolicy)
        self.frmEndDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmEndDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmEndDateTime.setLineWidth(0)
        self.frmEndDateTime.setObjectName(_fromUtf8("frmEndDateTime"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frmEndDateTime)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.edtEndDate = CDateEdit(self.frmEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout_4.addWidget(self.edtEndDate)
        self.edtEndTime = QtGui.QTimeEdit(self.frmEndDateTime)
        self.edtEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.horizontalLayout_4.addWidget(self.edtEndTime)
        self.gridLayout_2.addWidget(self.frmEndDateTime, 8, 1, 1, 1)
        self.frmNextDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmNextDateTime.sizePolicy().hasHeightForWidth())
        self.frmNextDateTime.setSizePolicy(sizePolicy)
        self.frmNextDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmNextDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmNextDateTime.setLineWidth(0)
        self.frmNextDateTime.setObjectName(_fromUtf8("frmNextDateTime"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frmNextDateTime)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout_2.addWidget(self.frmNextDateTime, 12, 1, 1, 1)
        self.grpTakenTissue = QtGui.QGroupBox(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpTakenTissue.sizePolicy().hasHeightForWidth())
        self.grpTakenTissue.setSizePolicy(sizePolicy)
        self.grpTakenTissue.setObjectName(_fromUtf8("grpTakenTissue"))
        self.gridLayout = QtGui.QGridLayout(self.grpTakenTissue)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblTissueType = QtGui.QLabel(self.grpTakenTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueType.sizePolicy().hasHeightForWidth())
        self.lblTissueType.setSizePolicy(sizePolicy)
        self.lblTissueType.setMinimumSize(QtCore.QSize(0, 20))
        self.lblTissueType.setObjectName(_fromUtf8("lblTissueType"))
        self.gridLayout.addWidget(self.lblTissueType, 0, 0, 1, 1)
        self.cmbTissueType = CRBComboBox(self.grpTakenTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTissueType.sizePolicy().hasHeightForWidth())
        self.cmbTissueType.setSizePolicy(sizePolicy)
        self.cmbTissueType.setObjectName(_fromUtf8("cmbTissueType"))
        self.gridLayout.addWidget(self.cmbTissueType, 0, 1, 1, 3)
        self.pnlDatetime = QtGui.QWidget(self.grpTakenTissue)
        self.pnlDatetime.setObjectName(_fromUtf8("pnlDatetime"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.pnlDatetime)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.edtTissueDate = CDateEdit(self.pnlDatetime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTissueDate.sizePolicy().hasHeightForWidth())
        self.edtTissueDate.setSizePolicy(sizePolicy)
        self.edtTissueDate.setCalendarPopup(True)
        self.edtTissueDate.setObjectName(_fromUtf8("edtTissueDate"))
        self.horizontalLayout_7.addWidget(self.edtTissueDate)
        self.edtTissueTime = QtGui.QTimeEdit(self.pnlDatetime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTissueTime.sizePolicy().hasHeightForWidth())
        self.edtTissueTime.setSizePolicy(sizePolicy)
        self.edtTissueTime.setObjectName(_fromUtf8("edtTissueTime"))
        self.horizontalLayout_7.addWidget(self.edtTissueTime)
        self.gridLayout.addWidget(self.pnlDatetime, 1, 1, 1, 1)
        self.pnlWTF = QtGui.QWidget(self.grpTakenTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pnlWTF.sizePolicy().hasHeightForWidth())
        self.pnlWTF.setSizePolicy(sizePolicy)
        self.pnlWTF.setObjectName(_fromUtf8("pnlWTF"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.pnlWTF)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.edtTissueAmount = QtGui.QSpinBox(self.pnlWTF)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTissueAmount.sizePolicy().hasHeightForWidth())
        self.edtTissueAmount.setSizePolicy(sizePolicy)
        self.edtTissueAmount.setMaximum(999999)
        self.edtTissueAmount.setObjectName(_fromUtf8("edtTissueAmount"))
        self.horizontalLayout_6.addWidget(self.edtTissueAmount)
        self.lblTissueUnit = QtGui.QLabel(self.pnlWTF)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueUnit.sizePolicy().hasHeightForWidth())
        self.lblTissueUnit.setSizePolicy(sizePolicy)
        self.lblTissueUnit.setMinimumSize(QtCore.QSize(0, 20))
        self.lblTissueUnit.setObjectName(_fromUtf8("lblTissueUnit"))
        self.horizontalLayout_6.addWidget(self.lblTissueUnit)
        self.cmbTissueUnit = CRBComboBox(self.pnlWTF)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTissueUnit.sizePolicy().hasHeightForWidth())
        self.cmbTissueUnit.setSizePolicy(sizePolicy)
        self.cmbTissueUnit.setObjectName(_fromUtf8("cmbTissueUnit"))
        self.horizontalLayout_6.addWidget(self.cmbTissueUnit)
        self.gridLayout.addWidget(self.pnlWTF, 5, 1, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.edtTissueNote = QtGui.QLineEdit(self.grpTakenTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTissueNote.sizePolicy().hasHeightForWidth())
        self.edtTissueNote.setSizePolicy(sizePolicy)
        self.edtTissueNote.setObjectName(_fromUtf8("edtTissueNote"))
        self.gridLayout.addWidget(self.edtTissueNote, 8, 1, 1, 3)
        self.edtTissueNumber = QtGui.QLineEdit(self.grpTakenTissue)
        self.edtTissueNumber.setReadOnly(True)
        self.edtTissueNumber.setObjectName(_fromUtf8("edtTissueNumber"))
        self.gridLayout.addWidget(self.edtTissueNumber, 7, 1, 1, 3)
        self.lblTissueNumber = QtGui.QLabel(self.grpTakenTissue)
        self.lblTissueNumber.setObjectName(_fromUtf8("lblTissueNumber"))
        self.gridLayout.addWidget(self.lblTissueNumber, 7, 0, 1, 1)
        self.lblTissueExternalId = QtGui.QLabel(self.grpTakenTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueExternalId.sizePolicy().hasHeightForWidth())
        self.lblTissueExternalId.setSizePolicy(sizePolicy)
        self.lblTissueExternalId.setMinimumSize(QtCore.QSize(0, 20))
        self.lblTissueExternalId.setObjectName(_fromUtf8("lblTissueExternalId"))
        self.gridLayout.addWidget(self.lblTissueExternalId, 6, 0, 1, 1)
        self.edtTissueExternalId = QtGui.QLineEdit(self.grpTakenTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTissueExternalId.sizePolicy().hasHeightForWidth())
        self.edtTissueExternalId.setSizePolicy(sizePolicy)
        self.edtTissueExternalId.setReadOnly(False)
        self.edtTissueExternalId.setObjectName(_fromUtf8("edtTissueExternalId"))
        self.gridLayout.addWidget(self.edtTissueExternalId, 6, 1, 1, 3)
        self.lblTissyeExecPerson = QtGui.QLabel(self.grpTakenTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissyeExecPerson.sizePolicy().hasHeightForWidth())
        self.lblTissyeExecPerson.setSizePolicy(sizePolicy)
        self.lblTissyeExecPerson.setMinimumSize(QtCore.QSize(0, 20))
        self.lblTissyeExecPerson.setObjectName(_fromUtf8("lblTissyeExecPerson"))
        self.gridLayout.addWidget(self.lblTissyeExecPerson, 2, 0, 1, 1)
        self.cmbTissueExecPerson = CPersonComboBoxEx(self.grpTakenTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTissueExecPerson.sizePolicy().hasHeightForWidth())
        self.cmbTissueExecPerson.setSizePolicy(sizePolicy)
        self.cmbTissueExecPerson.setObjectName(_fromUtf8("cmbTissueExecPerson"))
        self.gridLayout.addWidget(self.cmbTissueExecPerson, 2, 1, 1, 3)
        self.lblTissueAmount = QtGui.QLabel(self.grpTakenTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueAmount.sizePolicy().hasHeightForWidth())
        self.lblTissueAmount.setSizePolicy(sizePolicy)
        self.lblTissueAmount.setMinimumSize(QtCore.QSize(0, 20))
        self.lblTissueAmount.setObjectName(_fromUtf8("lblTissueAmount"))
        self.gridLayout.addWidget(self.lblTissueAmount, 5, 0, 1, 1)
        self.lblTissueNote = QtGui.QLabel(self.grpTakenTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueNote.sizePolicy().hasHeightForWidth())
        self.lblTissueNote.setSizePolicy(sizePolicy)
        self.lblTissueNote.setMinimumSize(QtCore.QSize(0, 20))
        self.lblTissueNote.setObjectName(_fromUtf8("lblTissueNote"))
        self.gridLayout.addWidget(self.lblTissueNote, 8, 0, 1, 1)
        self.lblTissueDateTime = QtGui.QLabel(self.grpTakenTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueDateTime.sizePolicy().hasHeightForWidth())
        self.lblTissueDateTime.setSizePolicy(sizePolicy)
        self.lblTissueDateTime.setMinimumSize(QtCore.QSize(0, 20))
        self.lblTissueDateTime.setObjectName(_fromUtf8("lblTissueDateTime"))
        self.gridLayout.addWidget(self.lblTissueDateTime, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.grpTakenTissue, 13, 0, 1, 2)
        self.frmBegDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmBegDateTime.sizePolicy().hasHeightForWidth())
        self.frmBegDateTime.setSizePolicy(sizePolicy)
        self.frmBegDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmBegDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmBegDateTime.setLineWidth(0)
        self.frmBegDateTime.setObjectName(_fromUtf8("frmBegDateTime"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frmBegDateTime)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.edtBegDate = CDateEdit(self.frmBegDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout_3.addWidget(self.edtBegDate)
        self.edtBegTime = QtGui.QTimeEdit(self.frmBegDateTime)
        self.edtBegTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.horizontalLayout_3.addWidget(self.edtBegTime)
        self.gridLayout_2.addWidget(self.frmBegDateTime, 7, 1, 1, 1)
        self.chkIsClosed = QtGui.QCheckBox(self.grpBase)
        self.chkIsClosed.setObjectName(_fromUtf8("chkIsClosed"))
        self.gridLayout_2.addWidget(self.chkIsClosed, 1, 0, 1, 2)
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.grpActionSearch = QtGui.QWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpActionSearch.sizePolicy().hasHeightForWidth())
        self.grpActionSearch.setSizePolicy(sizePolicy)
        self.grpActionSearch.setObjectName(_fromUtf8("grpActionSearch"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.grpActionSearch)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblFindByCode = QtGui.QLabel(self.grpActionSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFindByCode.sizePolicy().hasHeightForWidth())
        self.lblFindByCode.setSizePolicy(sizePolicy)
        self.lblFindByCode.setObjectName(_fromUtf8("lblFindByCode"))
        self.horizontalLayout_2.addWidget(self.lblFindByCode)
        self.edtFindByCode = QtGui.QLineEdit(self.grpActionSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFindByCode.sizePolicy().hasHeightForWidth())
        self.edtFindByCode.setSizePolicy(sizePolicy)
        self.edtFindByCode.setObjectName(_fromUtf8("edtFindByCode"))
        self.horizontalLayout_2.addWidget(self.edtFindByCode)
        self.btnAdd = QtGui.QPushButton(self.grpActionSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAdd.sizePolicy().hasHeightForWidth())
        self.btnAdd.setSizePolicy(sizePolicy)
        self.btnAdd.setMinimumSize(QtCore.QSize(100, 0))
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.btnSelectAll = QtGui.QPushButton(self.grpActionSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectAll.sizePolicy().hasHeightForWidth())
        self.btnSelectAll.setSizePolicy(sizePolicy)
        self.btnSelectAll.setMinimumSize(QtCore.QSize(100, 0))
        self.btnSelectAll.setObjectName(_fromUtf8("btnSelectAll"))
        self.horizontalLayout_2.addWidget(self.btnSelectAll)
        self.btnClearSelection = QtGui.QPushButton(self.grpActionSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClearSelection.sizePolicy().hasHeightForWidth())
        self.btnClearSelection.setSizePolicy(sizePolicy)
        self.btnClearSelection.setMinimumSize(QtCore.QSize(0, 0))
        self.btnClearSelection.setObjectName(_fromUtf8("btnClearSelection"))
        self.horizontalLayout_2.addWidget(self.btnClearSelection)
        self.gridLayout_3.addWidget(self.grpActionSearch, 1, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.treeActionTypeGroups = CActionTypeTreeView(self.splitter)
        self.treeActionTypeGroups.setObjectName(_fromUtf8("treeActionTypeGroups"))
        self.tblActionTypes = CTableView(self.splitter)
        self.tblActionTypes.setObjectName(_fromUtf8("tblActionTypes"))
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.lblSelectedCount = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSelectedCount.sizePolicy().hasHeightForWidth())
        self.lblSelectedCount.setSizePolicy(sizePolicy)
        self.lblSelectedCount.setText(_fromUtf8(""))
        self.lblSelectedCount.setObjectName(_fromUtf8("lblSelectedCount"))
        self.gridLayout_3.addWidget(self.lblSelectedCount, 2, 0, 1, 1)
        self.grpFinalDiagnostics = QtGui.QGroupBox(self.splitter_3)
        self.grpFinalDiagnostics.setObjectName(_fromUtf8("grpFinalDiagnostics"))
        self.gridLayout_7 = QtGui.QGridLayout(self.grpFinalDiagnostics)
        self.gridLayout_7.setMargin(2)
        self.gridLayout_7.setSpacing(1)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tblFinalDiagnostics = CInDocTableView(self.grpFinalDiagnostics)
        self.tblFinalDiagnostics.setMinimumSize(QtCore.QSize(0, 200))
        self.tblFinalDiagnostics.setObjectName(_fromUtf8("tblFinalDiagnostics"))
        self.gridLayout_7.addWidget(self.tblFinalDiagnostics, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.splitter_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabToken, _fromUtf8(""))
        self.tabActions = CActionsPage()
        self.tabActions.setObjectName(_fromUtf8("tabActions"))
        self.tabWidget.addTab(self.tabActions, _fromUtf8(""))
        self.tabSummaryActionTable = QtGui.QWidget()
        self.tabSummaryActionTable.setObjectName(_fromUtf8("tabSummaryActionTable"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabSummaryActionTable)
        self.gridLayout_8.setMargin(4)
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tabSummaryActionTable)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 96, 212))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tblActions = CInDocTableView(self.scrollAreaWidgetContents_2)
        self.tblActions.setMinimumSize(QtCore.QSize(0, 200))
        self.tblActions.setObjectName(_fromUtf8("tblActions"))
        self.verticalLayout_3.addWidget(self.tblActions)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_8.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabSummaryActionTable, _fromUtf8(""))
        self.tabCash = CEventCashPage()
        self.tabCash.setObjectName(_fromUtf8("tabCash"))
        self.tabWidget.addTab(self.tabCash, _fromUtf8(""))
        self.tabNotes = CEventNotesPage()
        self.tabNotes.setObjectName(_fromUtf8("tabNotes"))
        self.tabWidget.addTab(self.tabNotes, _fromUtf8(""))
        self.verticalLayout.addWidget(self.sptTopLevel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblProlongateEvent = QtGui.QLabel(F001Dialog)
        self.lblProlongateEvent.setText(_fromUtf8(""))
        self.lblProlongateEvent.setObjectName(_fromUtf8("lblProlongateEvent"))
        self.horizontalLayout.addWidget(self.lblProlongateEvent)
        self.lblValueExternalId = QtGui.QLabel(F001Dialog)
        self.lblValueExternalId.setText(_fromUtf8(""))
        self.lblValueExternalId.setObjectName(_fromUtf8("lblValueExternalId"))
        self.horizontalLayout.addWidget(self.lblValueExternalId)
        self.buttonBox = QtGui.QDialogButtonBox(F001Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.statusBar = QtGui.QStatusBar(F001Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.verticalLayout.addWidget(self.statusBar)
        self.lblGoal.setBuddy(self.cmbGoal)
        self.lblSetPerson.setBuddy(self.cmbSetPerson)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblResult.setBuddy(self.cmbResult)
        self.lblTissueType.setBuddy(self.cmbTissueType)
        self.lblTissueUnit.setBuddy(self.cmbTissueUnit)
        self.lblTissueNumber.setBuddy(self.edtTissueNumber)
        self.lblTissueExternalId.setBuddy(self.edtTissueExternalId)
        self.lblTissyeExecPerson.setBuddy(self.cmbTissueExecPerson)
        self.lblTissueAmount.setBuddy(self.edtTissueAmount)
        self.lblTissueNote.setBuddy(self.edtTissueNote)
        self.lblTissueDateTime.setBuddy(self.edtTissueDate)

        self.retranslateUi(F001Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), F001Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), F001Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(F001Dialog)
        F001Dialog.setTabOrder(self.tabWidget, self.buttonBox)
        F001Dialog.setTabOrder(self.buttonBox, self.scrollArea)
        F001Dialog.setTabOrder(self.scrollArea, self.cmbContract)
        F001Dialog.setTabOrder(self.cmbContract, self.chkIsClosed)
        F001Dialog.setTabOrder(self.chkIsClosed, self.chkExposeConfirmed)
        F001Dialog.setTabOrder(self.chkExposeConfirmed, self.cmbClientPolicy)
        F001Dialog.setTabOrder(self.cmbClientPolicy, self.cmbSetPerson)
        F001Dialog.setTabOrder(self.cmbSetPerson, self.edtBegDate)
        F001Dialog.setTabOrder(self.edtBegDate, self.edtBegTime)
        F001Dialog.setTabOrder(self.edtBegTime, self.edtEndDate)
        F001Dialog.setTabOrder(self.edtEndDate, self.edtEndTime)
        F001Dialog.setTabOrder(self.edtEndTime, self.cmbResult)
        F001Dialog.setTabOrder(self.cmbResult, self.cmbGoal)
        F001Dialog.setTabOrder(self.cmbGoal, self.cmbTissueType)
        F001Dialog.setTabOrder(self.cmbTissueType, self.edtTissueDate)
        F001Dialog.setTabOrder(self.edtTissueDate, self.edtTissueTime)
        F001Dialog.setTabOrder(self.edtTissueTime, self.cmbTissueExecPerson)
        F001Dialog.setTabOrder(self.cmbTissueExecPerson, self.edtTissueAmount)
        F001Dialog.setTabOrder(self.edtTissueAmount, self.cmbTissueUnit)
        F001Dialog.setTabOrder(self.cmbTissueUnit, self.edtTissueExternalId)
        F001Dialog.setTabOrder(self.edtTissueExternalId, self.edtTissueNumber)
        F001Dialog.setTabOrder(self.edtTissueNumber, self.edtTissueNote)
        F001Dialog.setTabOrder(self.edtTissueNote, self.chkZNOFirst)
        F001Dialog.setTabOrder(self.chkZNOFirst, self.chkZNOMorph)
        F001Dialog.setTabOrder(self.chkZNOMorph, self.treeActionTypeGroups)
        F001Dialog.setTabOrder(self.treeActionTypeGroups, self.tblActionTypes)
        F001Dialog.setTabOrder(self.tblActionTypes, self.edtFindByCode)
        F001Dialog.setTabOrder(self.edtFindByCode, self.btnAdd)
        F001Dialog.setTabOrder(self.btnAdd, self.btnSelectAll)
        F001Dialog.setTabOrder(self.btnSelectAll, self.btnClearSelection)
        F001Dialog.setTabOrder(self.btnClearSelection, self.tblFinalDiagnostics)
        F001Dialog.setTabOrder(self.tblFinalDiagnostics, self.tblActions)
        F001Dialog.setTabOrder(self.tblActions, self.scrollArea_2)

    def retranslateUi(self, F001Dialog):
        F001Dialog.setWindowTitle(_translate("F001Dialog", "Dialog", None))
        self.txtClientInfoBrowser.setWhatsThis(_translate("F001Dialog", "Описание пациента", None))
        self.txtClientInfoBrowser.setHtml(_translate("F001Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>", None))
        self.grpBase.setTitle(_translate("F001Dialog", "&ф.001", None))
        self.chkExposeConfirmed.setText(_translate("F001Dialog", "Добавить к выставлению", None))
        self.chkZNOFirst.setToolTip(_translate("F001Dialog", "ЗНО установлен впервые", None))
        self.chkZNOFirst.setText(_translate("F001Dialog", "ЗНО уст. впервые", None))
        self.lblGoal.setText(_translate("F001Dialog", "Цель", None))
        self.lblSetPerson.setText(_translate("F001Dialog", "Назначил", None))
        self.lblBegDate.setText(_translate("F001Dialog", "Назначено", None))
        self.lblEndDate.setText(_translate("F001Dialog", "Выполнено", None))
        self.cmbContract.setWhatsThis(_translate("F001Dialog", "номер, дата и основание договора в рамках которого производится осмотр", None))
        self.cmbContract.setItemText(0, _translate("F001Dialog", "Договор", None))
        self.chkZNOMorph.setToolTip(_translate("F001Dialog", "ЗНО потдверждён морфологически", None))
        self.chkZNOMorph.setText(_translate("F001Dialog", "ЗНО подтв. морф-ки", None))
        self.lblClientPolicy.setText(_translate("F001Dialog", "Полис пациента", None))
        self.lblResult.setText(_translate("F001Dialog", "Результат", None))
        self.edtEndDate.setWhatsThis(_translate("F001Dialog", "дата окончания осмотра", None))
        self.edtEndTime.setDisplayFormat(_translate("F001Dialog", "HH:mm", None))
        self.grpTakenTissue.setTitle(_translate("F001Dialog", "Забор биоматериала", None))
        self.lblTissueType.setText(_translate("F001Dialog", "Тип биоматериала", None))
        self.edtTissueTime.setDisplayFormat(_translate("F001Dialog", "HH:mm", None))
        self.lblTissueUnit.setText(_translate("F001Dialog", "Ед. изм.", None))
        self.lblTissueNumber.setText(_translate("F001Dialog", "Номер", None))
        self.lblTissueExternalId.setText(_translate("F001Dialog", "&Идентификатор", None))
        self.lblTissyeExecPerson.setText(_translate("F001Dialog", "Исполнитель", None))
        self.lblTissueAmount.setText(_translate("F001Dialog", "Количество", None))
        self.lblTissueNote.setText(_translate("F001Dialog", "Примечание", None))
        self.lblTissueDateTime.setText(_translate("F001Dialog", "Дата и время", None))
        self.edtBegDate.setWhatsThis(_translate("F001Dialog", "дата начала осмотра", None))
        self.edtBegTime.setDisplayFormat(_translate("F001Dialog", "HH:mm", None))
        self.chkIsClosed.setText(_translate("F001Dialog", "Карта заполнена", None))
        self.lblFindByCode.setText(_translate("F001Dialog", "Поиск по коду или наименованию", None))
        self.btnAdd.setText(_translate("F001Dialog", "Добавить", None))
        self.btnSelectAll.setText(_translate("F001Dialog", "Выбрать все", None))
        self.btnClearSelection.setText(_translate("F001Dialog", "Очистить выбор", None))
        self.grpFinalDiagnostics.setTitle(_translate("F001Dialog", "Диагнозы", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabToken), _translate("F001Dialog", "Стат.&учёт", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabActions), _translate("F001Dialog", "У&слуги", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSummaryActionTable), _translate("F001Dialog", "&Таблица услуг", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCash), _translate("F001Dialog", "Оплата", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNotes), _translate("F001Dialog", "Приме&чания", None))
        self.statusBar.setToolTip(_translate("F001Dialog", "A status bar", None))
        self.statusBar.setWhatsThis(_translate("F001Dialog", "A status bar.", None))

from Events.ActionTypeComboBox import CActionTypeTreeView
from Events.ActionsPage import CActionsPage
from Events.ClientPolicyComboBox import CClientPolicyComboBox
from Events.EventCashPage import CEventCashPage
from Events.EventNotesPage import CEventNotesPage
from Orgs.OrgComboBox import CContractComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
from library.TableView import CTableView
from library.TextBrowser import CTextBrowser
from library.crbcombobox import CRBComboBox
