# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeathReportSetup.ui'
#
# Created: Tue Nov 06 16:57:41 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DeathReportSetupDialog(object):
    def setupUi(self, DeathReportSetupDialog):
        DeathReportSetupDialog.setObjectName(_fromUtf8("DeathReportSetupDialog"))
        DeathReportSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        DeathReportSetupDialog.resize(376, 380)
        DeathReportSetupDialog.setSizeGripEnabled(True)
        self.gridlayout = QtGui.QGridLayout(DeathReportSetupDialog)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.cmbSocStatusClass = CSocStatusComboBox(DeathReportSetupDialog)
        self.cmbSocStatusClass.setObjectName(_fromUtf8("cmbSocStatusClass"))
        self.gridlayout.addWidget(self.cmbSocStatusClass, 10, 1, 1, 2)
        self.frmMKB = QtGui.QFrame(DeathReportSetupDialog)
        self.frmMKB.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMKB.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMKB.setObjectName(_fromUtf8("frmMKB"))
        self._2 = QtGui.QGridLayout(self.frmMKB)
        self._2.setMargin(0)
        self._2.setHorizontalSpacing(4)
        self._2.setVerticalSpacing(0)
        self._2.setObjectName(_fromUtf8("_2"))
        self.cmbMKBFilter = QtGui.QComboBox(self.frmMKB)
        self.cmbMKBFilter.setObjectName(_fromUtf8("cmbMKBFilter"))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self._2.addWidget(self.cmbMKBFilter, 0, 0, 1, 1)
        self.edtMKBFrom = CICDCodeEdit(self.frmMKB)
        self.edtMKBFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBFrom.sizePolicy().hasHeightForWidth())
        self.edtMKBFrom.setSizePolicy(sizePolicy)
        self.edtMKBFrom.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBFrom.setMaxLength(6)
        self.edtMKBFrom.setObjectName(_fromUtf8("edtMKBFrom"))
        self._2.addWidget(self.edtMKBFrom, 0, 1, 1, 1)
        self.edtMKBTo = CICDCodeEdit(self.frmMKB)
        self.edtMKBTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBTo.sizePolicy().hasHeightForWidth())
        self.edtMKBTo.setSizePolicy(sizePolicy)
        self.edtMKBTo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBTo.setMaxLength(6)
        self.edtMKBTo.setObjectName(_fromUtf8("edtMKBTo"))
        self._2.addWidget(self.edtMKBTo, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem, 0, 3, 1, 1)
        self.gridlayout.addWidget(self.frmMKB, 3, 1, 1, 2)
        self.lblFoundation = QtGui.QLabel(DeathReportSetupDialog)
        self.lblFoundation.setObjectName(_fromUtf8("lblFoundation"))
        self.gridlayout.addWidget(self.lblFoundation, 7, 0, 1, 1)
        self.lblSocStatusClass = QtGui.QLabel(DeathReportSetupDialog)
        self.lblSocStatusClass.setObjectName(_fromUtf8("lblSocStatusClass"))
        self.gridlayout.addWidget(self.lblSocStatusClass, 10, 0, 1, 1)
        self.lblPlace = QtGui.QLabel(DeathReportSetupDialog)
        self.lblPlace.setObjectName(_fromUtf8("lblPlace"))
        self.gridlayout.addWidget(self.lblPlace, 4, 0, 1, 1)
        self.cmbCause = CStrComboBox(DeathReportSetupDialog)
        self.cmbCause.setObjectName(_fromUtf8("cmbCause"))
        self.gridlayout.addWidget(self.cmbCause, 5, 1, 1, 2)
        self.lblMKB = QtGui.QLabel(DeathReportSetupDialog)
        self.lblMKB.setObjectName(_fromUtf8("lblMKB"))
        self.gridlayout.addWidget(self.lblMKB, 3, 0, 1, 1)
        self.cmbBusyness = QtGui.QComboBox(DeathReportSetupDialog)
        self.cmbBusyness.setObjectName(_fromUtf8("cmbBusyness"))
        self.cmbBusyness.addItem(_fromUtf8(""))
        self.cmbBusyness.addItem(_fromUtf8(""))
        self.cmbBusyness.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbBusyness, 2, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.edtBegDate = CDateEdit(DeathReportSetupDialog)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridlayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.lblBegDate = QtGui.QLabel(DeathReportSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridlayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.lblEndDate = QtGui.QLabel(DeathReportSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridlayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(DeathReportSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 13, 0, 1, 3)
        self.edtEndDate = CDateEdit(DeathReportSetupDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridlayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem2, 1, 2, 1, 1)
        self.cmbSocStatusType = CRBComboBox(DeathReportSetupDialog)
        self.cmbSocStatusType.setObjectName(_fromUtf8("cmbSocStatusType"))
        self.gridlayout.addWidget(self.cmbSocStatusType, 11, 1, 1, 2)
        self.lblFoundBy = QtGui.QLabel(DeathReportSetupDialog)
        self.lblFoundBy.setObjectName(_fromUtf8("lblFoundBy"))
        self.gridlayout.addWidget(self.lblFoundBy, 6, 0, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(DeathReportSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridlayout.addWidget(self.lblOrgStructure, 9, 0, 1, 1)
        self.cmbAttachmentOrgStructureId = COrgStructureComboBox(DeathReportSetupDialog)
        self.cmbAttachmentOrgStructureId.setObjectName(_fromUtf8("cmbAttachmentOrgStructureId"))
        self.gridlayout.addWidget(self.cmbAttachmentOrgStructureId, 9, 1, 1, 2)
        self.lblCause = QtGui.QLabel(DeathReportSetupDialog)
        self.lblCause.setObjectName(_fromUtf8("lblCause"))
        self.gridlayout.addWidget(self.lblCause, 5, 0, 1, 1)
        self.cmbFoundation = CStrComboBox(DeathReportSetupDialog)
        self.cmbFoundation.setObjectName(_fromUtf8("cmbFoundation"))
        self.gridlayout.addWidget(self.cmbFoundation, 7, 1, 1, 2)
        self.cmbPlace = CStrComboBox(DeathReportSetupDialog)
        self.cmbPlace.setObjectName(_fromUtf8("cmbPlace"))
        self.gridlayout.addWidget(self.cmbPlace, 4, 1, 1, 2)
        self.lblBusyness = QtGui.QLabel(DeathReportSetupDialog)
        self.lblBusyness.setObjectName(_fromUtf8("lblBusyness"))
        self.gridlayout.addWidget(self.lblBusyness, 2, 0, 1, 1)
        self.cmbFoundBy = CStrComboBox(DeathReportSetupDialog)
        self.cmbFoundBy.setObjectName(_fromUtf8("cmbFoundBy"))
        self.gridlayout.addWidget(self.cmbFoundBy, 6, 1, 1, 2)
        self.lblSocStatusType = QtGui.QLabel(DeathReportSetupDialog)
        self.lblSocStatusType.setObjectName(_fromUtf8("lblSocStatusType"))
        self.gridlayout.addWidget(self.lblSocStatusType, 11, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(129, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem3, 12, 0, 1, 1)
        self.lblFoundation.setBuddy(self.cmbFoundation)
        self.lblPlace.setBuddy(self.cmbPlace)
        self.lblMKB.setBuddy(self.cmbMKBFilter)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblFoundBy.setBuddy(self.cmbFoundBy)
        self.lblCause.setBuddy(self.cmbCause)
        self.lblBusyness.setBuddy(self.cmbBusyness)

        self.retranslateUi(DeathReportSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DeathReportSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DeathReportSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(DeathReportSetupDialog)
        DeathReportSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        DeathReportSetupDialog.setTabOrder(self.edtEndDate, self.cmbBusyness)
        DeathReportSetupDialog.setTabOrder(self.cmbBusyness, self.cmbMKBFilter)
        DeathReportSetupDialog.setTabOrder(self.cmbMKBFilter, self.edtMKBFrom)
        DeathReportSetupDialog.setTabOrder(self.edtMKBFrom, self.edtMKBTo)
        DeathReportSetupDialog.setTabOrder(self.edtMKBTo, self.cmbPlace)
        DeathReportSetupDialog.setTabOrder(self.cmbPlace, self.cmbCause)
        DeathReportSetupDialog.setTabOrder(self.cmbCause, self.cmbFoundBy)
        DeathReportSetupDialog.setTabOrder(self.cmbFoundBy, self.cmbFoundation)
        DeathReportSetupDialog.setTabOrder(self.cmbFoundation, self.buttonBox)

    def retranslateUi(self, DeathReportSetupDialog):
        DeathReportSetupDialog.setWindowTitle(QtGui.QApplication.translate("DeathReportSetupDialog", "параметры отчёта", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMKBFilter.setItemText(0, QtGui.QApplication.translate("DeathReportSetupDialog", "Игнор.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMKBFilter.setItemText(1, QtGui.QApplication.translate("DeathReportSetupDialog", "Интервал", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMKBFrom.setInputMask(QtGui.QApplication.translate("DeathReportSetupDialog", "a00.00; ", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMKBFrom.setText(QtGui.QApplication.translate("DeathReportSetupDialog", "A.", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMKBTo.setInputMask(QtGui.QApplication.translate("DeathReportSetupDialog", "a00.00; ", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMKBTo.setText(QtGui.QApplication.translate("DeathReportSetupDialog", "Z99.9", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFoundation.setText(QtGui.QApplication.translate("DeathReportSetupDialog", "Основание", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSocStatusClass.setText(QtGui.QApplication.translate("DeathReportSetupDialog", "Класс соц.статуса", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPlace.setText(QtGui.QApplication.translate("DeathReportSetupDialog", "Смерть последовала", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMKB.setText(QtGui.QApplication.translate("DeathReportSetupDialog", "Коды диагнозов по &МКБ", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbBusyness.setItemText(0, QtGui.QApplication.translate("DeathReportSetupDialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbBusyness.setItemText(1, QtGui.QApplication.translate("DeathReportSetupDialog", "указана", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbBusyness.setItemText(2, QtGui.QApplication.translate("DeathReportSetupDialog", "не указана", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBegDate.setText(QtGui.QApplication.translate("DeathReportSetupDialog", "Дата начала периода", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndDate.setText(QtGui.QApplication.translate("DeathReportSetupDialog", "Дата окончания периода", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFoundBy.setText(QtGui.QApplication.translate("DeathReportSetupDialog", "Причина установлена", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOrgStructure.setText(QtGui.QApplication.translate("DeathReportSetupDialog", "Подразделение", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCause.setText(QtGui.QApplication.translate("DeathReportSetupDialog", "Смерть произошла", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBusyness.setText(QtGui.QApplication.translate("DeathReportSetupDialog", "Занятость", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSocStatusType.setText(QtGui.QApplication.translate("DeathReportSetupDialog", "Тип соц.статуса", None, QtGui.QApplication.UnicodeUTF8))

from library.crbcombobox import CRBComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.StrComboBox import CStrComboBox
from library.ICDCodeEdit import CICDCodeEdit
from Registry.SocStatusComboBox import CSocStatusComboBox
from library.DateEdit import CDateEdit
