# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\Reports\MUOMSOF.ui'
#
# Created: Fri Jun 15 12:16:15 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MUOMSOFSetupDialog(object):
    def setupUi(self, MUOMSOFSetupDialog):
        MUOMSOFSetupDialog.setObjectName(_fromUtf8("MUOMSOFSetupDialog"))
        MUOMSOFSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        MUOMSOFSetupDialog.resize(339, 354)
        MUOMSOFSetupDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(MUOMSOFSetupDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblBegDate = QtGui.QLabel(MUOMSOFSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.edtBegDate = CDateEdit(MUOMSOFSetupDialog)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.lblEndDate = QtGui.QLabel(MUOMSOFSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.edtEndDate = CDateEdit(MUOMSOFSetupDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.lblEventPurpose = QtGui.QLabel(MUOMSOFSetupDialog)
        self.lblEventPurpose.setObjectName(_fromUtf8("lblEventPurpose"))
        self.gridLayout.addWidget(self.lblEventPurpose, 2, 0, 1, 1)
        self.cmbEventPurpose = CRBComboBox(MUOMSOFSetupDialog)
        self.cmbEventPurpose.setObjectName(_fromUtf8("cmbEventPurpose"))
        self.gridLayout.addWidget(self.cmbEventPurpose, 2, 1, 1, 2)
        self.lblEventType = QtGui.QLabel(MUOMSOFSetupDialog)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridLayout.addWidget(self.lblEventType, 3, 0, 1, 1)
        self.cmbEventType = CRBComboBox(MUOMSOFSetupDialog)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout.addWidget(self.cmbEventType, 3, 1, 1, 2)
        self.lblOrgStructure = QtGui.QLabel(MUOMSOFSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 4, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(MUOMSOFSetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 4, 1, 1, 2)
        self.lblSpeciality = QtGui.QLabel(MUOMSOFSetupDialog)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridLayout.addWidget(self.lblSpeciality, 5, 0, 1, 1)
        self.cmbSpeciality = CRBComboBox(MUOMSOFSetupDialog)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 5, 1, 1, 2)
        self.lblPerson = QtGui.QLabel(MUOMSOFSetupDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 6, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(MUOMSOFSetupDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 6, 1, 1, 2)
        self.lblContract = QtGui.QLabel(MUOMSOFSetupDialog)
        self.lblContract.setObjectName(_fromUtf8("lblContract"))
        self.gridLayout.addWidget(self.lblContract, 7, 0, 1, 1)
        self.cmbInsurer = CInsurerComboBox(MUOMSOFSetupDialog)
        self.cmbInsurer.setObjectName(_fromUtf8("cmbInsurer"))
        self.gridLayout.addWidget(self.cmbInsurer, 8, 1, 1, 2)
        self.lblInsurer = QtGui.QLabel(MUOMSOFSetupDialog)
        self.lblInsurer.setObjectName(_fromUtf8("lblInsurer"))
        self.gridLayout.addWidget(self.lblInsurer, 8, 0, 1, 1)
        self.lblGroupType = QtGui.QLabel(MUOMSOFSetupDialog)
        self.lblGroupType.setObjectName(_fromUtf8("lblGroupType"))
        self.gridLayout.addWidget(self.lblGroupType, 11, 0, 1, 1)
        self.cmbGroupType = QtGui.QComboBox(MUOMSOFSetupDialog)
        self.cmbGroupType.setObjectName(_fromUtf8("cmbGroupType"))
        self.cmbGroupType.addItem(_fromUtf8(""))
        self.cmbGroupType.addItem(_fromUtf8(""))
        self.cmbGroupType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbGroupType, 11, 1, 1, 2)
        self.cmbContracts = CContractComboBox(MUOMSOFSetupDialog)
        self.cmbContracts.setObjectName(_fromUtf8("cmbContracts"))
        self.gridLayout.addWidget(self.cmbContracts, 7, 1, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(MUOMSOFSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 13, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(21, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 12, 0, 1, 1)
        self.lblSex = QtGui.QLabel(MUOMSOFSetupDialog)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout.addWidget(self.lblSex, 9, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(MUOMSOFSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 9, 1, 1, 1)
        self.lblAge = QtGui.QLabel(MUOMSOFSetupDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout.addWidget(self.lblAge, 10, 0, 1, 1)
        self.frmAge = QtGui.QFrame(MUOMSOFSetupDialog)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self._2 = QtGui.QHBoxLayout(self.frmAge)
        self._2.setSpacing(4)
        self._2.setMargin(0)
        self._2.setObjectName(_fromUtf8("_2"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self._2.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self._2.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self._2.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self._2.addWidget(self.lblAgeYears)
        spacerItem3 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem3)
        self.gridLayout.addWidget(self.frmAge, 10, 1, 1, 2)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblEventPurpose.setBuddy(self.cmbEventPurpose)
        self.lblEventType.setBuddy(self.cmbEventType)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblSpeciality.setBuddy(self.cmbSpeciality)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblContract.setBuddy(self.cmbContracts)
        self.lblInsurer.setBuddy(self.cmbInsurer)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblAge.setBuddy(self.edtAgeFrom)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)

        self.retranslateUi(MUOMSOFSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MUOMSOFSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MUOMSOFSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(MUOMSOFSetupDialog)
        MUOMSOFSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        MUOMSOFSetupDialog.setTabOrder(self.edtEndDate, self.cmbEventPurpose)
        MUOMSOFSetupDialog.setTabOrder(self.cmbEventPurpose, self.cmbEventType)
        MUOMSOFSetupDialog.setTabOrder(self.cmbEventType, self.cmbOrgStructure)
        MUOMSOFSetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbSpeciality)
        MUOMSOFSetupDialog.setTabOrder(self.cmbSpeciality, self.cmbPerson)
        MUOMSOFSetupDialog.setTabOrder(self.cmbPerson, self.cmbContracts)
        MUOMSOFSetupDialog.setTabOrder(self.cmbContracts, self.cmbInsurer)
        MUOMSOFSetupDialog.setTabOrder(self.cmbInsurer, self.cmbSex)
        MUOMSOFSetupDialog.setTabOrder(self.cmbSex, self.edtAgeFrom)
        MUOMSOFSetupDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        MUOMSOFSetupDialog.setTabOrder(self.edtAgeTo, self.cmbGroupType)
        MUOMSOFSetupDialog.setTabOrder(self.cmbGroupType, self.buttonBox)

    def retranslateUi(self, MUOMSOFSetupDialog):
        MUOMSOFSetupDialog.setWindowTitle(QtGui.QApplication.translate("MUOMSOFSetupDialog", "параметры отчёта", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBegDate.setText(QtGui.QApplication.translate("MUOMSOFSetupDialog", "Дата &начала периода", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndDate.setText(QtGui.QApplication.translate("MUOMSOFSetupDialog", "Дата &окончания периода", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEventPurpose.setText(QtGui.QApplication.translate("MUOMSOFSetupDialog", "&Назначение обращения", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEventType.setText(QtGui.QApplication.translate("MUOMSOFSetupDialog", "&Тип обращения", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOrgStructure.setText(QtGui.QApplication.translate("MUOMSOFSetupDialog", "&Подразделение", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSpeciality.setText(QtGui.QApplication.translate("MUOMSOFSetupDialog", "&Специальность", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSpeciality.setWhatsThis(QtGui.QApplication.translate("MUOMSOFSetupDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPerson.setText(QtGui.QApplication.translate("MUOMSOFSetupDialog", "&Врач", None, QtGui.QApplication.UnicodeUTF8))
        self.lblContract.setText(QtGui.QApplication.translate("MUOMSOFSetupDialog", "Договор", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInsurer.setText(QtGui.QApplication.translate("MUOMSOFSetupDialog", "СМО", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGroupType.setText(QtGui.QApplication.translate("MUOMSOFSetupDialog", "Группировать", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbGroupType.setItemText(0, QtGui.QApplication.translate("MUOMSOFSetupDialog", "Не группировать", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbGroupType.setItemText(1, QtGui.QApplication.translate("MUOMSOFSetupDialog", "По профилю события", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbGroupType.setItemText(2, QtGui.QApplication.translate("MUOMSOFSetupDialog", "По типу события", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSex.setText(QtGui.QApplication.translate("MUOMSOFSetupDialog", "По&л", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSex.setItemText(1, QtGui.QApplication.translate("MUOMSOFSetupDialog", "М", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSex.setItemText(2, QtGui.QApplication.translate("MUOMSOFSetupDialog", "Ж", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAge.setText(QtGui.QApplication.translate("MUOMSOFSetupDialog", "Во&зраст с", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAgeTo.setText(QtGui.QApplication.translate("MUOMSOFSetupDialog", "по", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAgeYears.setText(QtGui.QApplication.translate("MUOMSOFSetupDialog", "лет", None, QtGui.QApplication.UnicodeUTF8))

from Orgs.OrgComboBox import CInsurerComboBox
from library.crbcombobox import CRBComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Accounting.ContractComboBox import CContractComboBox
from library.DateEdit import CDateEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MUOMSOFSetupDialog = QtGui.QDialog()
    ui = Ui_MUOMSOFSetupDialog()
    ui.setupUi(MUOMSOFSetupDialog)
    MUOMSOFSetupDialog.show()
    sys.exit(app.exec_())

