# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PopulationStructureSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PopulationStructureSetupDialog(object):
    def setupUi(self, PopulationStructureSetupDialog):
        PopulationStructureSetupDialog.setObjectName(_fromUtf8("PopulationStructureSetupDialog"))
        PopulationStructureSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PopulationStructureSetupDialog.resize(442, 271)
        PopulationStructureSetupDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(PopulationStructureSetupDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(PopulationStructureSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 8, 2, 1, 2)
        self.lblSocStatusClass = QtGui.QLabel(PopulationStructureSetupDialog)
        self.lblSocStatusClass.setObjectName(_fromUtf8("lblSocStatusClass"))
        self.gridLayout.addWidget(self.lblSocStatusClass, 4, 0, 1, 1)
        self.frmAge = QtGui.QFrame(PopulationStructureSetupDialog)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self.hboxlayout = QtGui.QHBoxLayout(self.frmAge)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self.hboxlayout.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self.hboxlayout.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self.hboxlayout.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self.hboxlayout.addWidget(self.lblAgeYears)
        spacerItem = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.frmAge, 1, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 2, 1, 1)
        self.lblEndDate = QtGui.QLabel(PopulationStructureSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 0, 0, 1, 1)
        self.edtEndDate = CDateEdit(PopulationStructureSetupDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(61, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 1)
        self.lblAge = QtGui.QLabel(PopulationStructureSetupDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout.addWidget(self.lblAge, 1, 0, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(PopulationStructureSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 2, 0, 1, 1)
        self.lblAddressOrgStructureType = QtGui.QLabel(PopulationStructureSetupDialog)
        self.lblAddressOrgStructureType.setObjectName(_fromUtf8("lblAddressOrgStructureType"))
        self.gridLayout.addWidget(self.lblAddressOrgStructureType, 3, 0, 1, 1)
        self.cmbAddressOrgStructureType = QtGui.QComboBox(PopulationStructureSetupDialog)
        self.cmbAddressOrgStructureType.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAddressOrgStructureType.sizePolicy().hasHeightForWidth())
        self.cmbAddressOrgStructureType.setSizePolicy(sizePolicy)
        self.cmbAddressOrgStructureType.setObjectName(_fromUtf8("cmbAddressOrgStructureType"))
        self.cmbAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbAddressOrgStructureType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbAddressOrgStructureType, 3, 1, 1, 3)
        self.chkDetalizeByHouses = QtGui.QCheckBox(PopulationStructureSetupDialog)
        self.chkDetalizeByHouses.setObjectName(_fromUtf8("chkDetalizeByHouses"))
        self.gridLayout.addWidget(self.chkDetalizeByHouses, 6, 1, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 8, 0, 1, 2)
        self.cmbSocStatusType = CRBComboBox(PopulationStructureSetupDialog)
        self.cmbSocStatusType.setObjectName(_fromUtf8("cmbSocStatusType"))
        self.gridLayout.addWidget(self.cmbSocStatusType, 5, 1, 1, 1)
        self.cmbSocStatusClass = CSocStatusComboBox(PopulationStructureSetupDialog)
        self.cmbSocStatusClass.setObjectName(_fromUtf8("cmbSocStatusClass"))
        self.gridLayout.addWidget(self.cmbSocStatusClass, 4, 1, 1, 1)
        self.lblSocStatusType = QtGui.QLabel(PopulationStructureSetupDialog)
        self.lblSocStatusType.setObjectName(_fromUtf8("lblSocStatusType"))
        self.gridLayout.addWidget(self.lblSocStatusType, 5, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(PopulationStructureSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbOrgStructure.setSizePolicy(sizePolicy)
        self.cmbOrgStructure.setMinimumSize(QtCore.QSize(107, 0))
        self.cmbOrgStructure.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 2, 1, 1, 3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 6, 3, 1, 1)
        self.lblSocStatusClass.setBuddy(self.cmbSocStatusClass)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblAge.setBuddy(self.edtAgeFrom)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblAddressOrgStructureType.setBuddy(self.cmbAddressOrgStructureType)
        self.lblSocStatusType.setBuddy(self.cmbSocStatusType)

        self.retranslateUi(PopulationStructureSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PopulationStructureSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PopulationStructureSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PopulationStructureSetupDialog)
        PopulationStructureSetupDialog.setTabOrder(self.edtEndDate, self.edtAgeFrom)
        PopulationStructureSetupDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        PopulationStructureSetupDialog.setTabOrder(self.edtAgeTo, self.cmbOrgStructure)
        PopulationStructureSetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbAddressOrgStructureType)

    def retranslateUi(self, PopulationStructureSetupDialog):
        PopulationStructureSetupDialog.setWindowTitle(_translate("PopulationStructureSetupDialog", "параметры отчёта", None))
        self.lblSocStatusClass.setText(_translate("PopulationStructureSetupDialog", "Класс соц.статуса", None))
        self.lblAgeTo.setText(_translate("PopulationStructureSetupDialog", "по", None))
        self.lblAgeYears.setText(_translate("PopulationStructureSetupDialog", "лет", None))
        self.lblEndDate.setText(_translate("PopulationStructureSetupDialog", "&Дата", None))
        self.lblAge.setText(_translate("PopulationStructureSetupDialog", "Во&зраст с", None))
        self.lblOrgStructure.setText(_translate("PopulationStructureSetupDialog", "&Подразделение", None))
        self.lblAddressOrgStructureType.setText(_translate("PopulationStructureSetupDialog", "Адрес", None))
        self.cmbAddressOrgStructureType.setItemText(0, _translate("PopulationStructureSetupDialog", "Регистрация", None))
        self.cmbAddressOrgStructureType.setItemText(1, _translate("PopulationStructureSetupDialog", "Проживание", None))
        self.cmbAddressOrgStructureType.setItemText(2, _translate("PopulationStructureSetupDialog", "Регистрация или проживание", None))
        self.cmbAddressOrgStructureType.setItemText(3, _translate("PopulationStructureSetupDialog", "Прикрепление", None))
        self.cmbAddressOrgStructureType.setItemText(4, _translate("PopulationStructureSetupDialog", "Регистрация или прикрепление", None))
        self.cmbAddressOrgStructureType.setItemText(5, _translate("PopulationStructureSetupDialog", "Проживание или прикрепление", None))
        self.cmbAddressOrgStructureType.setItemText(6, _translate("PopulationStructureSetupDialog", "Регистрация, проживание или прикрепление", None))
        self.chkDetalizeByHouses.setText(_translate("PopulationStructureSetupDialog", "Детализация по домам", None))
        self.lblSocStatusType.setText(_translate("PopulationStructureSetupDialog", "Тип соц.статуса", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Registry.SocStatusComboBox import CSocStatusComboBox
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
