# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PreRecordDoctorsDialog.ui'
#
# Created: Thu Oct 18 21:15:18 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PreRecordDoctorsDialog(object):
    def setupUi(self, PreRecordDoctorsDialog):
        PreRecordDoctorsDialog.setObjectName(_fromUtf8("PreRecordDoctorsDialog"))
        PreRecordDoctorsDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PreRecordDoctorsDialog.resize(504, 208)
        PreRecordDoctorsDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(PreRecordDoctorsDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edtBegDate = CDateEdit(PreRecordDoctorsDialog)
        self.edtBegDate.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.chkShowWithoutOverTime = QtGui.QCheckBox(PreRecordDoctorsDialog)
        self.chkShowWithoutOverTime.setObjectName(_fromUtf8("chkShowWithoutOverTime"))
        self.gridLayout.addWidget(self.chkShowWithoutOverTime, 5, 0, 1, 1)
        self.lblPerson = QtGui.QLabel(PreRecordDoctorsDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(PreRecordDoctorsDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.cmbSpeciality = CRBComboBox(PreRecordDoctorsDialog)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 3, 1, 1, 4)
        self.lblOrgStructure = QtGui.QLabel(PreRecordDoctorsDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 2, 0, 1, 1)
        self.chkPeriodBeforeRecord = QtGui.QCheckBox(PreRecordDoctorsDialog)
        self.chkPeriodBeforeRecord.setChecked(False)
        self.chkPeriodBeforeRecord.setObjectName(_fromUtf8("chkPeriodBeforeRecord"))
        self.gridLayout.addWidget(self.chkPeriodBeforeRecord, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(19, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.edtEndDate = CDateEdit(PreRecordDoctorsDialog)
        self.edtEndDate.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 0, 3, 1, 1)
        self.chkPeriodRecord = QtGui.QCheckBox(PreRecordDoctorsDialog)
        self.chkPeriodRecord.setChecked(True)
        self.chkPeriodRecord.setObjectName(_fromUtf8("chkPeriodRecord"))
        self.gridLayout.addWidget(self.chkPeriodRecord, 0, 0, 1, 1)
        self.edtBegDateRecord = CDateEdit(PreRecordDoctorsDialog)
        self.edtBegDateRecord.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDateRecord.sizePolicy().hasHeightForWidth())
        self.edtBegDateRecord.setSizePolicy(sizePolicy)
        self.edtBegDateRecord.setCalendarPopup(True)
        self.edtBegDateRecord.setObjectName(_fromUtf8("edtBegDateRecord"))
        self.gridLayout.addWidget(self.edtBegDateRecord, 1, 1, 1, 1)
        self.lblEndDate = QtGui.QLabel(PreRecordDoctorsDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 0, 2, 1, 1)
        self.lblSpeciality = QtGui.QLabel(PreRecordDoctorsDialog)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridLayout.addWidget(self.lblSpeciality, 3, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(PreRecordDoctorsDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 2, 1, 1, 4)
        self.cmbPerson = CPersonComboBoxEx(PreRecordDoctorsDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 4, 1, 1, 4)
        spacerItem1 = QtGui.QSpacerItem(21, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(PreRecordDoctorsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 9, 0, 1, 5)
        self.edtEndDateRecord = CDateEdit(PreRecordDoctorsDialog)
        self.edtEndDateRecord.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDateRecord.sizePolicy().hasHeightForWidth())
        self.edtEndDateRecord.setSizePolicy(sizePolicy)
        self.edtEndDateRecord.setCalendarPopup(True)
        self.edtEndDateRecord.setObjectName(_fromUtf8("edtEndDateRecord"))
        self.gridLayout.addWidget(self.edtEndDateRecord, 1, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(19, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 4, 1, 1)
        self.chkIgnoreRehabilitation = QtGui.QCheckBox(PreRecordDoctorsDialog)
        self.chkIgnoreRehabilitation.setObjectName(_fromUtf8("chkIgnoreRehabilitation"))
        self.gridLayout.addWidget(self.chkIgnoreRehabilitation, 6, 0, 1, 1)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblSpeciality.setBuddy(self.cmbSpeciality)

        self.retranslateUi(PreRecordDoctorsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PreRecordDoctorsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PreRecordDoctorsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreRecordDoctorsDialog)
        PreRecordDoctorsDialog.setTabOrder(self.chkPeriodRecord, self.edtBegDate)
        PreRecordDoctorsDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        PreRecordDoctorsDialog.setTabOrder(self.edtEndDate, self.chkPeriodBeforeRecord)
        PreRecordDoctorsDialog.setTabOrder(self.chkPeriodBeforeRecord, self.edtBegDateRecord)
        PreRecordDoctorsDialog.setTabOrder(self.edtBegDateRecord, self.edtEndDateRecord)
        PreRecordDoctorsDialog.setTabOrder(self.edtEndDateRecord, self.cmbOrgStructure)
        PreRecordDoctorsDialog.setTabOrder(self.cmbOrgStructure, self.cmbSpeciality)
        PreRecordDoctorsDialog.setTabOrder(self.cmbSpeciality, self.cmbPerson)
        PreRecordDoctorsDialog.setTabOrder(self.cmbPerson, self.buttonBox)

    def retranslateUi(self, PreRecordDoctorsDialog):
        PreRecordDoctorsDialog.setWindowTitle(QtGui.QApplication.translate("PreRecordDoctorsDialog", "параметры отчёта", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowWithoutOverTime.setText(QtGui.QApplication.translate("PreRecordDoctorsDialog", "Не выводить пациентов сверх очереди", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPerson.setText(QtGui.QApplication.translate("PreRecordDoctorsDialog", "&Врач", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PreRecordDoctorsDialog", "по", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSpeciality.setWhatsThis(QtGui.QApplication.translate("PreRecordDoctorsDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOrgStructure.setText(QtGui.QApplication.translate("PreRecordDoctorsDialog", "&Подразделение", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPeriodBeforeRecord.setText(QtGui.QApplication.translate("PreRecordDoctorsDialog", "Период предварительной записи с", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPeriodRecord.setText(QtGui.QApplication.translate("PreRecordDoctorsDialog", "Период постановки в очередь с", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndDate.setText(QtGui.QApplication.translate("PreRecordDoctorsDialog", "по", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSpeciality.setText(QtGui.QApplication.translate("PreRecordDoctorsDialog", "&Специальность", None, QtGui.QApplication.UnicodeUTF8))
        self.chkIgnoreRehabilitation.setText(QtGui.QApplication.translate("PreRecordDoctorsDialog", "Не учитывать реабилитационное отделение", None, QtGui.QApplication.UnicodeUTF8))

from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.crbcombobox import CRBComboBox
from library.DateEdit import CDateEdit
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
