# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PreRecordSpecialityDialog.ui'
#
# Created: Thu Oct 18 21:33:18 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PreRecordSpecialityDialog(object):
    def setupUi(self, PreRecordSpecialityDialog):
        PreRecordSpecialityDialog.setObjectName(_fromUtf8("PreRecordSpecialityDialog"))
        PreRecordSpecialityDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PreRecordSpecialityDialog.resize(504, 308)
        PreRecordSpecialityDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(PreRecordSpecialityDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblEndDate = QtGui.QLabel(PreRecordSpecialityDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDate.sizePolicy().hasHeightForWidth())
        self.lblEndDate.setSizePolicy(sizePolicy)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 0, 2, 1, 1)
        self.edtEndDate = CDateEdit(PreRecordSpecialityDialog)
        self.edtEndDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(19, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.lblPerson = QtGui.QLabel(PreRecordSpecialityDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 4, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(PreRecordSpecialityDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 2, 1, 1, 4)
        self.edtEndDateRecord = CDateEdit(PreRecordSpecialityDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDateRecord.sizePolicy().hasHeightForWidth())
        self.edtEndDateRecord.setSizePolicy(sizePolicy)
        self.edtEndDateRecord.setCalendarPopup(True)
        self.edtEndDateRecord.setObjectName(_fromUtf8("edtEndDateRecord"))
        self.gridLayout.addWidget(self.edtEndDateRecord, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(19, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 1)
        self.lblSpeciality = QtGui.QLabel(PreRecordSpecialityDialog)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridLayout.addWidget(self.lblSpeciality, 3, 0, 1, 1)
        self.edtBegDate = CDateEdit(PreRecordSpecialityDialog)
        self.edtBegDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.lblDetail = QtGui.QLabel(PreRecordSpecialityDialog)
        self.lblDetail.setObjectName(_fromUtf8("lblDetail"))
        self.gridLayout.addWidget(self.lblDetail, 5, 0, 1, 1)
        self.cmbAcceptanceType = QtGui.QComboBox(PreRecordSpecialityDialog)
        self.cmbAcceptanceType.setObjectName(_fromUtf8("cmbAcceptanceType"))
        self.cmbAcceptanceType.addItem(_fromUtf8(""))
        self.cmbAcceptanceType.addItem(_fromUtf8(""))
        self.cmbAcceptanceType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbAcceptanceType, 7, 1, 1, 4)
        self.cmbSpeciality = CRBComboBox(PreRecordSpecialityDialog)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 3, 1, 1, 4)
        self.lblOrgStructure = QtGui.QLabel(PreRecordSpecialityDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 2, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(PreRecordSpecialityDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 4, 1, 1, 4)
        self.chkShowWithoutOverTime = QtGui.QCheckBox(PreRecordSpecialityDialog)
        self.chkShowWithoutOverTime.setObjectName(_fromUtf8("chkShowWithoutOverTime"))
        self.gridLayout.addWidget(self.chkShowWithoutOverTime, 8, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(21, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 10, 0, 1, 1)
        self.edtBegDateRecord = CDateEdit(PreRecordSpecialityDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDateRecord.sizePolicy().hasHeightForWidth())
        self.edtBegDateRecord.setSizePolicy(sizePolicy)
        self.edtBegDateRecord.setCalendarPopup(True)
        self.edtBegDateRecord.setObjectName(_fromUtf8("edtBegDateRecord"))
        self.gridLayout.addWidget(self.edtBegDateRecord, 1, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(PreRecordSpecialityDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 11, 0, 1, 5)
        self.chkPeriodBeforeRecord = QtGui.QCheckBox(PreRecordSpecialityDialog)
        self.chkPeriodBeforeRecord.setChecked(True)
        self.chkPeriodBeforeRecord.setObjectName(_fromUtf8("chkPeriodBeforeRecord"))
        self.gridLayout.addWidget(self.chkPeriodBeforeRecord, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(PreRecordSpecialityDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.chkPeriodRecord = QtGui.QCheckBox(PreRecordSpecialityDialog)
        self.chkPeriodRecord.setObjectName(_fromUtf8("chkPeriodRecord"))
        self.gridLayout.addWidget(self.chkPeriodRecord, 0, 0, 1, 1)
        self.chkDetailOnPerson = QtGui.QCheckBox(PreRecordSpecialityDialog)
        self.chkDetailOnPerson.setObjectName(_fromUtf8("chkDetailOnPerson"))
        self.gridLayout.addWidget(self.chkDetailOnPerson, 6, 1, 1, 4)
        self.chkDetailOnOrgStructure = QtGui.QCheckBox(PreRecordSpecialityDialog)
        self.chkDetailOnOrgStructure.setObjectName(_fromUtf8("chkDetailOnOrgStructure"))
        self.gridLayout.addWidget(self.chkDetailOnOrgStructure, 5, 1, 1, 4)
        self.chkIgnoreRehabilitation = QtGui.QCheckBox(PreRecordSpecialityDialog)
        self.chkIgnoreRehabilitation.setObjectName(_fromUtf8("chkIgnoreRehabilitation"))
        self.gridLayout.addWidget(self.chkIgnoreRehabilitation, 9, 0, 1, 1)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblSpeciality.setBuddy(self.cmbSpeciality)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)

        self.retranslateUi(PreRecordSpecialityDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PreRecordSpecialityDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PreRecordSpecialityDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreRecordSpecialityDialog)
        PreRecordSpecialityDialog.setTabOrder(self.chkPeriodRecord, self.edtBegDate)
        PreRecordSpecialityDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        PreRecordSpecialityDialog.setTabOrder(self.edtEndDate, self.chkPeriodBeforeRecord)
        PreRecordSpecialityDialog.setTabOrder(self.chkPeriodBeforeRecord, self.edtBegDateRecord)
        PreRecordSpecialityDialog.setTabOrder(self.edtBegDateRecord, self.edtEndDateRecord)
        PreRecordSpecialityDialog.setTabOrder(self.edtEndDateRecord, self.cmbOrgStructure)
        PreRecordSpecialityDialog.setTabOrder(self.cmbOrgStructure, self.cmbSpeciality)
        PreRecordSpecialityDialog.setTabOrder(self.cmbSpeciality, self.cmbPerson)
        PreRecordSpecialityDialog.setTabOrder(self.cmbPerson, self.chkDetailOnOrgStructure)
        PreRecordSpecialityDialog.setTabOrder(self.chkDetailOnOrgStructure, self.chkDetailOnPerson)
        PreRecordSpecialityDialog.setTabOrder(self.chkDetailOnPerson, self.buttonBox)

    def retranslateUi(self, PreRecordSpecialityDialog):
        PreRecordSpecialityDialog.setWindowTitle(QtGui.QApplication.translate("PreRecordSpecialityDialog", "параметры отчёта", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndDate.setText(QtGui.QApplication.translate("PreRecordSpecialityDialog", "по", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPerson.setText(QtGui.QApplication.translate("PreRecordSpecialityDialog", "&Врач", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSpeciality.setText(QtGui.QApplication.translate("PreRecordSpecialityDialog", "&Специальность", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDetail.setText(QtGui.QApplication.translate("PreRecordSpecialityDialog", "Детализировать", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbAcceptanceType.setItemText(0, QtGui.QApplication.translate("PreRecordSpecialityDialog", "все", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbAcceptanceType.setItemText(1, QtGui.QApplication.translate("PreRecordSpecialityDialog", "амбулаторно", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbAcceptanceType.setItemText(2, QtGui.QApplication.translate("PreRecordSpecialityDialog", "на дому", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSpeciality.setWhatsThis(QtGui.QApplication.translate("PreRecordSpecialityDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOrgStructure.setText(QtGui.QApplication.translate("PreRecordSpecialityDialog", "&Подразделение", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowWithoutOverTime.setText(QtGui.QApplication.translate("PreRecordSpecialityDialog", "Не выводить пациентов сверх очереди", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPeriodBeforeRecord.setText(QtGui.QApplication.translate("PreRecordSpecialityDialog", "Период предварительной записи с", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PreRecordSpecialityDialog", "по", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPeriodRecord.setText(QtGui.QApplication.translate("PreRecordSpecialityDialog", "Период постановки в очередь с", None, QtGui.QApplication.UnicodeUTF8))
        self.chkDetailOnPerson.setText(QtGui.QApplication.translate("PreRecordSpecialityDialog", "по врачам", None, QtGui.QApplication.UnicodeUTF8))
        self.chkDetailOnOrgStructure.setText(QtGui.QApplication.translate("PreRecordSpecialityDialog", "по подразделениям", None, QtGui.QApplication.UnicodeUTF8))
        self.chkIgnoreRehabilitation.setText(QtGui.QApplication.translate("PreRecordSpecialityDialog", "Не учитывать реабилитационное отделение", None, QtGui.QApplication.UnicodeUTF8))

from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.crbcombobox import CRBComboBox
from library.DateEdit import CDateEdit
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
