# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReportPersonSickListSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportPersonSickListSetupDialog(object):
    def setupUi(self, ReportPersonSickListSetupDialog):
        ReportPersonSickListSetupDialog.setObjectName(_fromUtf8("ReportPersonSickListSetupDialog"))
        ReportPersonSickListSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ReportPersonSickListSetupDialog.resize(423, 686)
        ReportPersonSickListSetupDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(ReportPersonSickListSetupDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frmMKB = QtGui.QFrame(ReportPersonSickListSetupDialog)
        self.frmMKB.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMKB.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMKB.setObjectName(_fromUtf8("frmMKB"))
        self.gridlayout = QtGui.QGridLayout(self.frmMKB)
        self.gridlayout.setMargin(0)
        self.gridlayout.setHorizontalSpacing(4)
        self.gridlayout.setVerticalSpacing(0)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.cmbMKBFilter = QtGui.QComboBox(self.frmMKB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMKBFilter.sizePolicy().hasHeightForWidth())
        self.cmbMKBFilter.setSizePolicy(sizePolicy)
        self.cmbMKBFilter.setObjectName(_fromUtf8("cmbMKBFilter"))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbMKBFilter, 0, 0, 1, 1)
        self.edtMKBFrom = CICDCodeEdit(self.frmMKB)
        self.edtMKBFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBFrom.sizePolicy().hasHeightForWidth())
        self.edtMKBFrom.setSizePolicy(sizePolicy)
        self.edtMKBFrom.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBFrom.setMaxLength(6)
        self.edtMKBFrom.setObjectName(_fromUtf8("edtMKBFrom"))
        self.gridlayout.addWidget(self.edtMKBFrom, 0, 1, 1, 1)
        self.edtMKBTo = CICDCodeEdit(self.frmMKB)
        self.edtMKBTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBTo.sizePolicy().hasHeightForWidth())
        self.edtMKBTo.setSizePolicy(sizePolicy)
        self.edtMKBTo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBTo.setMaxLength(6)
        self.edtMKBTo.setObjectName(_fromUtf8("edtMKBTo"))
        self.gridlayout.addWidget(self.edtMKBTo, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.frmMKB, 15, 1, 1, 4)
        self.frmMKBEx = QtGui.QFrame(ReportPersonSickListSetupDialog)
        self.frmMKBEx.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMKBEx.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMKBEx.setObjectName(_fromUtf8("frmMKBEx"))
        self.gridlayout1 = QtGui.QGridLayout(self.frmMKBEx)
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setHorizontalSpacing(4)
        self.gridlayout1.setVerticalSpacing(0)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.cmbMKBExFilter = QtGui.QComboBox(self.frmMKBEx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMKBExFilter.sizePolicy().hasHeightForWidth())
        self.cmbMKBExFilter.setSizePolicy(sizePolicy)
        self.cmbMKBExFilter.setObjectName(_fromUtf8("cmbMKBExFilter"))
        self.cmbMKBExFilter.addItem(_fromUtf8(""))
        self.cmbMKBExFilter.addItem(_fromUtf8(""))
        self.gridlayout1.addWidget(self.cmbMKBExFilter, 0, 0, 1, 1)
        self.edtMKBExFrom = CICDCodeEdit(self.frmMKBEx)
        self.edtMKBExFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBExFrom.sizePolicy().hasHeightForWidth())
        self.edtMKBExFrom.setSizePolicy(sizePolicy)
        self.edtMKBExFrom.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBExFrom.setMaxLength(6)
        self.edtMKBExFrom.setObjectName(_fromUtf8("edtMKBExFrom"))
        self.gridlayout1.addWidget(self.edtMKBExFrom, 0, 1, 1, 1)
        self.edtMKBExTo = CICDCodeEdit(self.frmMKBEx)
        self.edtMKBExTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBExTo.sizePolicy().hasHeightForWidth())
        self.edtMKBExTo.setSizePolicy(sizePolicy)
        self.edtMKBExTo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBExTo.setMaxLength(6)
        self.edtMKBExTo.setObjectName(_fromUtf8("edtMKBExTo"))
        self.gridlayout1.addWidget(self.edtMKBExTo, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.frmMKBEx, 16, 1, 2, 4)
        self.frmAge = QtGui.QFrame(ReportPersonSickListSetupDialog)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self.hboxlayout = QtGui.QHBoxLayout(self.frmAge)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self.hboxlayout.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self.hboxlayout.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self.hboxlayout.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self.hboxlayout.addWidget(self.lblAgeYears)
        spacerItem2 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem2)
        self.gridLayout.addWidget(self.frmAge, 10, 1, 1, 4)
        self.cmbLocality = QtGui.QComboBox(ReportPersonSickListSetupDialog)
        self.cmbLocality.setObjectName(_fromUtf8("cmbLocality"))
        self.cmbLocality.addItem(_fromUtf8(""))
        self.cmbLocality.addItem(_fromUtf8(""))
        self.cmbLocality.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbLocality, 24, 1, 1, 4)
        spacerItem3 = QtGui.QSpacerItem(129, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 25, 0, 1, 1)
        self.cmbSocStatusType = CRBComboBox(ReportPersonSickListSetupDialog)
        self.cmbSocStatusType.setObjectName(_fromUtf8("cmbSocStatusType"))
        self.gridLayout.addWidget(self.cmbSocStatusType, 12, 1, 1, 4)
        self.chkAccountAccomp = QtGui.QCheckBox(ReportPersonSickListSetupDialog)
        self.chkAccountAccomp.setObjectName(_fromUtf8("chkAccountAccomp"))
        self.gridLayout.addWidget(self.chkAccountAccomp, 20, 1, 1, 4)
        self.cmbSocStatusClass = CSocStatusComboBox(ReportPersonSickListSetupDialog)
        self.cmbSocStatusClass.setObjectName(_fromUtf8("cmbSocStatusClass"))
        self.gridLayout.addWidget(self.cmbSocStatusClass, 11, 1, 1, 4)
        spacerItem4 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 3, 1, 2)
        self.lblOrgStructure = QtGui.QLabel(ReportPersonSickListSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 5, 0, 1, 1)
        self.lblSocStatusType = QtGui.QLabel(ReportPersonSickListSetupDialog)
        self.lblSocStatusType.setObjectName(_fromUtf8("lblSocStatusType"))
        self.gridLayout.addWidget(self.lblSocStatusType, 12, 0, 1, 1)
        self.chkOnlyFirstTime = QtGui.QCheckBox(ReportPersonSickListSetupDialog)
        self.chkOnlyFirstTime.setObjectName(_fromUtf8("chkOnlyFirstTime"))
        self.gridLayout.addWidget(self.chkOnlyFirstTime, 19, 1, 1, 4)
        self.lblLocality = QtGui.QLabel(ReportPersonSickListSetupDialog)
        self.lblLocality.setObjectName(_fromUtf8("lblLocality"))
        self.gridLayout.addWidget(self.lblLocality, 24, 0, 1, 1)
        self.lblMKB = QtGui.QLabel(ReportPersonSickListSetupDialog)
        self.lblMKB.setObjectName(_fromUtf8("lblMKB"))
        self.gridLayout.addWidget(self.lblMKB, 15, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ReportPersonSickListSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 26, 0, 1, 5)
        self.lblSex = QtGui.QLabel(ReportPersonSickListSetupDialog)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout.addWidget(self.lblSex, 9, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(ReportPersonSickListSetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 5, 1, 1, 4)
        self.cmbTraumaType = CRBComboBox(ReportPersonSickListSetupDialog)
        self.cmbTraumaType.setEnabled(False)
        self.cmbTraumaType.setObjectName(_fromUtf8("cmbTraumaType"))
        self.gridLayout.addWidget(self.cmbTraumaType, 23, 1, 1, 4)
        self.lblArea = QtGui.QLabel(ReportPersonSickListSetupDialog)
        self.lblArea.setObjectName(_fromUtf8("lblArea"))
        self.gridLayout.addWidget(self.lblArea, 14, 0, 1, 1)
        self.lblMKBEx = QtGui.QLabel(ReportPersonSickListSetupDialog)
        self.lblMKBEx.setObjectName(_fromUtf8("lblMKBEx"))
        self.gridLayout.addWidget(self.lblMKBEx, 16, 0, 1, 1)
        self.lblPerson = QtGui.QLabel(ReportPersonSickListSetupDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 7, 0, 1, 1)
        self.lblSocStatusClass = QtGui.QLabel(ReportPersonSickListSetupDialog)
        self.lblSocStatusClass.setObjectName(_fromUtf8("lblSocStatusClass"))
        self.gridLayout.addWidget(self.lblSocStatusClass, 11, 0, 1, 1)
        self.cmbWorkOrganisation = COrgComboBox(ReportPersonSickListSetupDialog)
        self.cmbWorkOrganisation.setObjectName(_fromUtf8("cmbWorkOrganisation"))
        self.gridLayout.addWidget(self.cmbWorkOrganisation, 8, 1, 1, 3)
        self.chkArea = QtGui.QCheckBox(ReportPersonSickListSetupDialog)
        self.chkArea.setObjectName(_fromUtf8("chkArea"))
        self.gridLayout.addWidget(self.chkArea, 13, 1, 1, 4)
        self.btnSelectWorkOrganisation = QtGui.QToolButton(ReportPersonSickListSetupDialog)
        self.btnSelectWorkOrganisation.setArrowType(QtCore.Qt.NoArrow)
        self.btnSelectWorkOrganisation.setObjectName(_fromUtf8("btnSelectWorkOrganisation"))
        self.gridLayout.addWidget(self.btnSelectWorkOrganisation, 8, 4, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(ReportPersonSickListSetupDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPerson, 7, 1, 1, 4)
        self.cmbEventType = CRBComboBox(ReportPersonSickListSetupDialog)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout.addWidget(self.cmbEventType, 4, 1, 1, 4)
        self.lblEventPurpose = QtGui.QLabel(ReportPersonSickListSetupDialog)
        self.lblEventPurpose.setObjectName(_fromUtf8("lblEventPurpose"))
        self.gridLayout.addWidget(self.lblEventPurpose, 3, 0, 1, 1)
        self.chkTraumaType = QtGui.QCheckBox(ReportPersonSickListSetupDialog)
        self.chkTraumaType.setObjectName(_fromUtf8("chkTraumaType"))
        self.gridLayout.addWidget(self.chkTraumaType, 22, 0, 1, 1)
        self.lblSpeciality = QtGui.QLabel(ReportPersonSickListSetupDialog)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridLayout.addWidget(self.lblSpeciality, 6, 0, 1, 1)
        self.cmbArea = COrgStructureComboBox(ReportPersonSickListSetupDialog)
        self.cmbArea.setEnabled(False)
        self.cmbArea.setObjectName(_fromUtf8("cmbArea"))
        self.gridLayout.addWidget(self.cmbArea, 14, 1, 1, 4)
        self.lblEventType = QtGui.QLabel(ReportPersonSickListSetupDialog)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridLayout.addWidget(self.lblEventType, 4, 0, 1, 1)
        self.cmbEventPurpose = CRBMultiComboBox(ReportPersonSickListSetupDialog)
        self.cmbEventPurpose.setObjectName(_fromUtf8("cmbEventPurpose"))
        self.gridLayout.addWidget(self.cmbEventPurpose, 3, 1, 1, 4)
        self.lblEndDate = QtGui.QLabel(ReportPersonSickListSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.cmbSpeciality = CRBComboBox(ReportPersonSickListSetupDialog)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 6, 1, 1, 4)
        self.cmbCharacterClass = QtGui.QComboBox(ReportPersonSickListSetupDialog)
        self.cmbCharacterClass.setObjectName(_fromUtf8("cmbCharacterClass"))
        self.cmbCharacterClass.addItem(_fromUtf8(""))
        self.cmbCharacterClass.addItem(_fromUtf8(""))
        self.cmbCharacterClass.addItem(_fromUtf8(""))
        self.cmbCharacterClass.addItem(_fromUtf8(""))
        self.cmbCharacterClass.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbCharacterClass, 18, 1, 1, 4)
        self.lblWorkOrganisation = QtGui.QLabel(ReportPersonSickListSetupDialog)
        self.lblWorkOrganisation.setObjectName(_fromUtf8("lblWorkOrganisation"))
        self.gridLayout.addWidget(self.lblWorkOrganisation, 8, 0, 1, 1)
        self.chkTraumaTypeAny = QtGui.QCheckBox(ReportPersonSickListSetupDialog)
        self.chkTraumaTypeAny.setEnabled(False)
        self.chkTraumaTypeAny.setObjectName(_fromUtf8("chkTraumaTypeAny"))
        self.gridLayout.addWidget(self.chkTraumaTypeAny, 22, 1, 1, 4)
        self.edtEndDate = CDateEdit(ReportPersonSickListSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 1, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 3, 1, 2)
        self.lblBegDate = QtGui.QLabel(ReportPersonSickListSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.edtBegDate = CDateEdit(ReportPersonSickListSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 2)
        self.lblDiseaseCharacter = QtGui.QLabel(ReportPersonSickListSetupDialog)
        self.lblDiseaseCharacter.setObjectName(_fromUtf8("lblDiseaseCharacter"))
        self.gridLayout.addWidget(self.lblDiseaseCharacter, 17, 0, 2, 1)
        self.cmbSex = QtGui.QComboBox(ReportPersonSickListSetupDialog)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 9, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(141, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 9, 2, 1, 3)
        self.lblAge = QtGui.QLabel(ReportPersonSickListSetupDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout.addWidget(self.lblAge, 10, 0, 1, 1)
        self.chkVisitEmergency = QtGui.QCheckBox(ReportPersonSickListSetupDialog)
        self.chkVisitEmergency.setObjectName(_fromUtf8("chkVisitEmergency"))
        self.gridLayout.addWidget(self.chkVisitEmergency, 21, 1, 1, 1)
        self.chkPeriod = QtGui.QCheckBox(ReportPersonSickListSetupDialog)
        self.chkPeriod.setObjectName(_fromUtf8("chkPeriod"))
        self.gridLayout.addWidget(self.chkPeriod, 2, 0, 1, 1)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblLocality.setBuddy(self.cmbLocality)
        self.lblMKB.setBuddy(self.cmbMKBFilter)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblArea.setBuddy(self.cmbArea)
        self.lblMKBEx.setBuddy(self.cmbMKBExFilter)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblEventPurpose.setBuddy(self.cmbEventPurpose)
        self.lblSpeciality.setBuddy(self.cmbSpeciality)
        self.lblEventType.setBuddy(self.cmbEventType)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblWorkOrganisation.setBuddy(self.cmbWorkOrganisation)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblDiseaseCharacter.setBuddy(self.cmbCharacterClass)
        self.lblAge.setBuddy(self.edtAgeFrom)

        self.retranslateUi(ReportPersonSickListSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportPersonSickListSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportPersonSickListSetupDialog.reject)
        QtCore.QObject.connect(self.chkArea, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbArea.setEnabled)
        QtCore.QObject.connect(self.chkTraumaType, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbTraumaType.setEnabled)
        QtCore.QObject.connect(self.chkTraumaType, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkTraumaTypeAny.setEnabled)
        QtCore.QObject.connect(self.chkTraumaTypeAny, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbTraumaType.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(ReportPersonSickListSetupDialog)
        ReportPersonSickListSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ReportPersonSickListSetupDialog.setTabOrder(self.edtEndDate, self.cmbEventPurpose)
        ReportPersonSickListSetupDialog.setTabOrder(self.cmbEventPurpose, self.cmbEventType)
        ReportPersonSickListSetupDialog.setTabOrder(self.cmbEventType, self.cmbOrgStructure)
        ReportPersonSickListSetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbSpeciality)
        ReportPersonSickListSetupDialog.setTabOrder(self.cmbSpeciality, self.cmbPerson)
        ReportPersonSickListSetupDialog.setTabOrder(self.cmbPerson, self.cmbWorkOrganisation)
        ReportPersonSickListSetupDialog.setTabOrder(self.cmbWorkOrganisation, self.btnSelectWorkOrganisation)
        ReportPersonSickListSetupDialog.setTabOrder(self.btnSelectWorkOrganisation, self.cmbSex)
        ReportPersonSickListSetupDialog.setTabOrder(self.cmbSex, self.edtAgeFrom)
        ReportPersonSickListSetupDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        ReportPersonSickListSetupDialog.setTabOrder(self.edtAgeTo, self.chkArea)
        ReportPersonSickListSetupDialog.setTabOrder(self.chkArea, self.cmbArea)
        ReportPersonSickListSetupDialog.setTabOrder(self.cmbArea, self.cmbMKBFilter)
        ReportPersonSickListSetupDialog.setTabOrder(self.cmbMKBFilter, self.edtMKBFrom)
        ReportPersonSickListSetupDialog.setTabOrder(self.edtMKBFrom, self.edtMKBTo)
        ReportPersonSickListSetupDialog.setTabOrder(self.edtMKBTo, self.cmbMKBExFilter)
        ReportPersonSickListSetupDialog.setTabOrder(self.cmbMKBExFilter, self.edtMKBExFrom)
        ReportPersonSickListSetupDialog.setTabOrder(self.edtMKBExFrom, self.edtMKBExTo)
        ReportPersonSickListSetupDialog.setTabOrder(self.edtMKBExTo, self.cmbCharacterClass)
        ReportPersonSickListSetupDialog.setTabOrder(self.cmbCharacterClass, self.chkOnlyFirstTime)
        ReportPersonSickListSetupDialog.setTabOrder(self.chkOnlyFirstTime, self.chkAccountAccomp)
        ReportPersonSickListSetupDialog.setTabOrder(self.chkAccountAccomp, self.chkTraumaType)
        ReportPersonSickListSetupDialog.setTabOrder(self.chkTraumaType, self.chkTraumaTypeAny)
        ReportPersonSickListSetupDialog.setTabOrder(self.chkTraumaTypeAny, self.cmbTraumaType)
        ReportPersonSickListSetupDialog.setTabOrder(self.cmbTraumaType, self.cmbLocality)
        ReportPersonSickListSetupDialog.setTabOrder(self.cmbLocality, self.buttonBox)

    def retranslateUi(self, ReportPersonSickListSetupDialog):
        ReportPersonSickListSetupDialog.setWindowTitle(_translate("ReportPersonSickListSetupDialog", "параметры отчёта", None))
        self.cmbMKBFilter.setItemText(0, _translate("ReportPersonSickListSetupDialog", "Игнор.", None))
        self.cmbMKBFilter.setItemText(1, _translate("ReportPersonSickListSetupDialog", "Интервал", None))
        self.edtMKBFrom.setInputMask(_translate("ReportPersonSickListSetupDialog", "a00.00; ", None))
        self.edtMKBFrom.setText(_translate("ReportPersonSickListSetupDialog", "A.", None))
        self.edtMKBTo.setInputMask(_translate("ReportPersonSickListSetupDialog", "a00.00; ", None))
        self.edtMKBTo.setText(_translate("ReportPersonSickListSetupDialog", "Z99.9", None))
        self.cmbMKBExFilter.setItemText(0, _translate("ReportPersonSickListSetupDialog", "Игнор.", None))
        self.cmbMKBExFilter.setItemText(1, _translate("ReportPersonSickListSetupDialog", "Интервал", None))
        self.edtMKBExFrom.setInputMask(_translate("ReportPersonSickListSetupDialog", "a00.00; ", None))
        self.edtMKBExFrom.setText(_translate("ReportPersonSickListSetupDialog", "A.", None))
        self.edtMKBExTo.setInputMask(_translate("ReportPersonSickListSetupDialog", "a00.00; ", None))
        self.edtMKBExTo.setText(_translate("ReportPersonSickListSetupDialog", "Z99.9", None))
        self.lblAgeTo.setText(_translate("ReportPersonSickListSetupDialog", "по", None))
        self.lblAgeYears.setText(_translate("ReportPersonSickListSetupDialog", "лет", None))
        self.cmbLocality.setItemText(0, _translate("ReportPersonSickListSetupDialog", "Не учитывать", None))
        self.cmbLocality.setItemText(1, _translate("ReportPersonSickListSetupDialog", "Городские жители", None))
        self.cmbLocality.setItemText(2, _translate("ReportPersonSickListSetupDialog", "Сельские жители", None))
        self.chkAccountAccomp.setText(_translate("ReportPersonSickListSetupDialog", "Учитывать сопутствующие", None))
        self.lblOrgStructure.setText(_translate("ReportPersonSickListSetupDialog", "&Подразделение", None))
        self.lblSocStatusType.setText(_translate("ReportPersonSickListSetupDialog", "Тип соц.статуса", None))
        self.chkOnlyFirstTime.setText(_translate("ReportPersonSickListSetupDialog", "Только впервые выявленные", None))
        self.lblLocality.setText(_translate("ReportPersonSickListSetupDialog", "Местность", None))
        self.lblMKB.setText(_translate("ReportPersonSickListSetupDialog", "Коды диагнозов по &МКБ", None))
        self.lblSex.setText(_translate("ReportPersonSickListSetupDialog", "По&л", None))
        self.lblArea.setText(_translate("ReportPersonSickListSetupDialog", "Те&рритория", None))
        self.lblMKBEx.setText(_translate("ReportPersonSickListSetupDialog", "В сочетании с", None))
        self.lblPerson.setText(_translate("ReportPersonSickListSetupDialog", "&Врач", None))
        self.lblSocStatusClass.setText(_translate("ReportPersonSickListSetupDialog", "Класс соц.статуса", None))
        self.chkArea.setText(_translate("ReportPersonSickListSetupDialog", "Учитывать адрес", None))
        self.btnSelectWorkOrganisation.setText(_translate("ReportPersonSickListSetupDialog", "...", None))
        self.cmbPerson.setWhatsThis(_translate("ReportPersonSickListSetupDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None))
        self.cmbPerson.setItemText(0, _translate("ReportPersonSickListSetupDialog", "Врач", None))
        self.cmbEventType.setWhatsThis(_translate("ReportPersonSickListSetupDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None))
        self.lblEventPurpose.setText(_translate("ReportPersonSickListSetupDialog", "&Назначение обращения", None))
        self.chkTraumaType.setText(_translate("ReportPersonSickListSetupDialog", "Тип травмы", None))
        self.lblSpeciality.setText(_translate("ReportPersonSickListSetupDialog", "&Специальность", None))
        self.lblEventType.setText(_translate("ReportPersonSickListSetupDialog", "&Тип обращения", None))
        self.cmbEventPurpose.setWhatsThis(_translate("ReportPersonSickListSetupDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None))
        self.lblEndDate.setText(_translate("ReportPersonSickListSetupDialog", "Дата &окончания периода", None))
        self.cmbSpeciality.setWhatsThis(_translate("ReportPersonSickListSetupDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None))
        self.cmbCharacterClass.setWhatsThis(_translate("ReportPersonSickListSetupDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None))
        self.cmbCharacterClass.setItemText(0, _translate("ReportPersonSickListSetupDialog", "Любой", None))
        self.cmbCharacterClass.setItemText(1, _translate("ReportPersonSickListSetupDialog", "Острый", None))
        self.cmbCharacterClass.setItemText(2, _translate("ReportPersonSickListSetupDialog", "Хронический", None))
        self.cmbCharacterClass.setItemText(3, _translate("ReportPersonSickListSetupDialog", "Острый или хронический", None))
        self.cmbCharacterClass.setItemText(4, _translate("ReportPersonSickListSetupDialog", "Фактор", None))
        self.lblWorkOrganisation.setText(_translate("ReportPersonSickListSetupDialog", "Занятость", None))
        self.chkTraumaTypeAny.setText(_translate("ReportPersonSickListSetupDialog", "Любой", None))
        self.lblBegDate.setText(_translate("ReportPersonSickListSetupDialog", "Дата &начала периода", None))
        self.lblDiseaseCharacter.setText(_translate("ReportPersonSickListSetupDialog", "&Характер", None))
        self.cmbSex.setItemText(1, _translate("ReportPersonSickListSetupDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("ReportPersonSickListSetupDialog", "Ж", None))
        self.lblAge.setText(_translate("ReportPersonSickListSetupDialog", "Во&зраст с", None))
        self.chkVisitEmergency.setText(_translate("ReportPersonSickListSetupDialog", "Учитывать посещения СМП", None))
        self.chkPeriod.setText(_translate("ReportPersonSickListSetupDialog", "За период", None))

from Orgs.OrgComboBox import COrgComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Registry.SocStatusComboBox import CSocStatusComboBox
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEdit
from library.crbcombobox import CRBComboBox, CRBMultiComboBox
