# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReportClientActionsSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportClientActionsSetupDialog(object):
    def setupUi(self, ReportClientActionsSetupDialog):
        ReportClientActionsSetupDialog.setObjectName(_fromUtf8("ReportClientActionsSetupDialog"))
        ReportClientActionsSetupDialog.resize(577, 676)
        self.gridLayout = QtGui.QGridLayout(ReportClientActionsSetupDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.grpClient = QtGui.QGroupBox(ReportClientActionsSetupDialog)
        self.grpClient.setFlat(False)
        self.grpClient.setCheckable(False)
        self.grpClient.setChecked(False)
        self.grpClient.setObjectName(_fromUtf8("grpClient"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpClient)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblLastName = QtGui.QLabel(self.grpClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLastName.sizePolicy().hasHeightForWidth())
        self.lblLastName.setSizePolicy(sizePolicy)
        self.lblLastName.setObjectName(_fromUtf8("lblLastName"))
        self.gridLayout_2.addWidget(self.lblLastName, 1, 0, 1, 1)
        self.edtLastName = QtGui.QLineEdit(self.grpClient)
        self.edtLastName.setObjectName(_fromUtf8("edtLastName"))
        self.gridLayout_2.addWidget(self.edtLastName, 1, 1, 1, 7)
        self.lblFirstName = QtGui.QLabel(self.grpClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFirstName.sizePolicy().hasHeightForWidth())
        self.lblFirstName.setSizePolicy(sizePolicy)
        self.lblFirstName.setObjectName(_fromUtf8("lblFirstName"))
        self.gridLayout_2.addWidget(self.lblFirstName, 2, 0, 1, 1)
        self.edtFirstName = QtGui.QLineEdit(self.grpClient)
        self.edtFirstName.setObjectName(_fromUtf8("edtFirstName"))
        self.gridLayout_2.addWidget(self.edtFirstName, 2, 1, 1, 7)
        self.lblPatrName = QtGui.QLabel(self.grpClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPatrName.sizePolicy().hasHeightForWidth())
        self.lblPatrName.setSizePolicy(sizePolicy)
        self.lblPatrName.setObjectName(_fromUtf8("lblPatrName"))
        self.gridLayout_2.addWidget(self.lblPatrName, 3, 0, 1, 1)
        self.edtPatrName = QtGui.QLineEdit(self.grpClient)
        self.edtPatrName.setObjectName(_fromUtf8("edtPatrName"))
        self.gridLayout_2.addWidget(self.edtPatrName, 3, 1, 1, 7)
        self.lblBirthDate = QtGui.QLabel(self.grpClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBirthDate.sizePolicy().hasHeightForWidth())
        self.lblBirthDate.setSizePolicy(sizePolicy)
        self.lblBirthDate.setObjectName(_fromUtf8("lblBirthDate"))
        self.gridLayout_2.addWidget(self.lblBirthDate, 4, 0, 1, 1)
        self.edtBirthDate = CDateEdit(self.grpClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBirthDate.sizePolicy().hasHeightForWidth())
        self.edtBirthDate.setSizePolicy(sizePolicy)
        self.edtBirthDate.setCalendarPopup(True)
        self.edtBirthDate.setObjectName(_fromUtf8("edtBirthDate"))
        self.gridLayout_2.addWidget(self.edtBirthDate, 4, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(221, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 2, 1, 6)
        self.lblDocument = QtGui.QLabel(self.grpClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDocument.sizePolicy().hasHeightForWidth())
        self.lblDocument.setSizePolicy(sizePolicy)
        self.lblDocument.setObjectName(_fromUtf8("lblDocument"))
        self.gridLayout_2.addWidget(self.lblDocument, 5, 0, 1, 1)
        self.cmbDocType = CRBComboBox(self.grpClient)
        self.cmbDocType.setObjectName(_fromUtf8("cmbDocType"))
        self.gridLayout_2.addWidget(self.cmbDocType, 5, 1, 1, 1)
        self.lblSerial = QtGui.QLabel(self.grpClient)
        self.lblSerial.setObjectName(_fromUtf8("lblSerial"))
        self.gridLayout_2.addWidget(self.lblSerial, 5, 2, 1, 1)
        self.edtLeftSerial = QtGui.QLineEdit(self.grpClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtLeftSerial.sizePolicy().hasHeightForWidth())
        self.edtLeftSerial.setSizePolicy(sizePolicy)
        self.edtLeftSerial.setObjectName(_fromUtf8("edtLeftSerial"))
        self.gridLayout_2.addWidget(self.edtLeftSerial, 5, 3, 1, 1)
        self.edtRightSerial = QtGui.QLineEdit(self.grpClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtRightSerial.sizePolicy().hasHeightForWidth())
        self.edtRightSerial.setSizePolicy(sizePolicy)
        self.edtRightSerial.setObjectName(_fromUtf8("edtRightSerial"))
        self.gridLayout_2.addWidget(self.edtRightSerial, 5, 4, 1, 1)
        self.lblNumber = QtGui.QLabel(self.grpClient)
        self.lblNumber.setObjectName(_fromUtf8("lblNumber"))
        self.gridLayout_2.addWidget(self.lblNumber, 5, 5, 1, 1)
        self.edtNumber = QtGui.QLineEdit(self.grpClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtNumber.sizePolicy().hasHeightForWidth())
        self.edtNumber.setSizePolicy(sizePolicy)
        self.edtNumber.setObjectName(_fromUtf8("edtNumber"))
        self.gridLayout_2.addWidget(self.edtNumber, 5, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(1, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 5, 7, 1, 1)
        self.lblCompulsoryPolicy = QtGui.QLabel(self.grpClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCompulsoryPolicy.sizePolicy().hasHeightForWidth())
        self.lblCompulsoryPolicy.setSizePolicy(sizePolicy)
        self.lblCompulsoryPolicy.setObjectName(_fromUtf8("lblCompulsoryPolicy"))
        self.gridLayout_2.addWidget(self.lblCompulsoryPolicy, 6, 0, 1, 1)
        self.cmbPolicyType = CRBComboBox(self.grpClient)
        self.cmbPolicyType.setObjectName(_fromUtf8("cmbPolicyType"))
        self.gridLayout_2.addWidget(self.cmbPolicyType, 6, 1, 1, 1)
        self.lblCompulsoryPolisSerial = QtGui.QLabel(self.grpClient)
        self.lblCompulsoryPolisSerial.setObjectName(_fromUtf8("lblCompulsoryPolisSerial"))
        self.gridLayout_2.addWidget(self.lblCompulsoryPolisSerial, 6, 2, 1, 1)
        self.edtPolicySerial = CPolicySerialEdit(self.grpClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPolicySerial.sizePolicy().hasHeightForWidth())
        self.edtPolicySerial.setSizePolicy(sizePolicy)
        self.edtPolicySerial.setObjectName(_fromUtf8("edtPolicySerial"))
        self.gridLayout_2.addWidget(self.edtPolicySerial, 6, 3, 1, 2)
        self.lblCompulsoryPolisNumber = QtGui.QLabel(self.grpClient)
        self.lblCompulsoryPolisNumber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCompulsoryPolisNumber.setObjectName(_fromUtf8("lblCompulsoryPolisNumber"))
        self.gridLayout_2.addWidget(self.lblCompulsoryPolisNumber, 6, 5, 1, 1)
        self.edtPolicyNumber = QtGui.QLineEdit(self.grpClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPolicyNumber.sizePolicy().hasHeightForWidth())
        self.edtPolicyNumber.setSizePolicy(sizePolicy)
        self.edtPolicyNumber.setObjectName(_fromUtf8("edtPolicyNumber"))
        self.gridLayout_2.addWidget(self.edtPolicyNumber, 6, 6, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(1, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 6, 7, 1, 1)
        self.lblCompulsoryPolisCompany = QtGui.QLabel(self.grpClient)
        self.lblCompulsoryPolisCompany.setObjectName(_fromUtf8("lblCompulsoryPolisCompany"))
        self.gridLayout_2.addWidget(self.lblCompulsoryPolisCompany, 7, 2, 1, 1)
        self.cmbPolicyCompany = CInsurerComboBox(self.grpClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPolicyCompany.sizePolicy().hasHeightForWidth())
        self.cmbPolicyCompany.setSizePolicy(sizePolicy)
        self.cmbPolicyCompany.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.cmbPolicyCompany.setObjectName(_fromUtf8("cmbPolicyCompany"))
        self.gridLayout_2.addWidget(self.cmbPolicyCompany, 7, 3, 1, 4)
        spacerItem3 = QtGui.QSpacerItem(1, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 7, 7, 1, 1)
        self.lblContact = QtGui.QLabel(self.grpClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblContact.sizePolicy().hasHeightForWidth())
        self.lblContact.setSizePolicy(sizePolicy)
        self.lblContact.setObjectName(_fromUtf8("lblContact"))
        self.gridLayout_2.addWidget(self.lblContact, 8, 0, 1, 1)
        self.edtContact = QtGui.QLineEdit(self.grpClient)
        self.edtContact.setObjectName(_fromUtf8("edtContact"))
        self.gridLayout_2.addWidget(self.edtContact, 8, 1, 1, 7)
        self.chkClientCode = QtGui.QCheckBox(self.grpClient)
        self.chkClientCode.setObjectName(_fromUtf8("chkClientCode"))
        self.gridLayout_2.addWidget(self.chkClientCode, 0, 0, 1, 1)
        self.edtClientCode = QtGui.QLineEdit(self.grpClient)
        self.edtClientCode.setEnabled(False)
        self.edtClientCode.setObjectName(_fromUtf8("edtClientCode"))
        self.gridLayout_2.addWidget(self.edtClientCode, 0, 1, 1, 3)
        self.cmbAccountingSystem = CRBComboBox(self.grpClient)
        self.cmbAccountingSystem.setEnabled(False)
        self.cmbAccountingSystem.setObjectName(_fromUtf8("cmbAccountingSystem"))
        self.gridLayout_2.addWidget(self.cmbAccountingSystem, 0, 4, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 6, 1, 2)
        self.gridLayout.addWidget(self.grpClient, 3, 0, 1, 5)
        self.lblActionDateType = QtGui.QLabel(ReportClientActionsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblActionDateType.sizePolicy().hasHeightForWidth())
        self.lblActionDateType.setSizePolicy(sizePolicy)
        self.lblActionDateType.setObjectName(_fromUtf8("lblActionDateType"))
        self.gridLayout.addWidget(self.lblActionDateType, 4, 0, 1, 1)
        self.cmbActionDateType = QtGui.QComboBox(ReportClientActionsSetupDialog)
        self.cmbActionDateType.setObjectName(_fromUtf8("cmbActionDateType"))
        self.cmbActionDateType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbActionDateType, 4, 1, 1, 3)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 4, 4, 1, 1)
        self.lblDate = QtGui.QLabel(ReportClientActionsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDate.sizePolicy().hasHeightForWidth())
        self.lblDate.setSizePolicy(sizePolicy)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout.addWidget(self.lblDate, 5, 0, 1, 1)
        self.edtBegDate = CDateEdit(ReportClientActionsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 5, 1, 1, 2)
        self.edtEndDate = CDateEdit(ReportClientActionsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 5, 3, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 5, 4, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ReportClientActionsSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 10, 0, 1, 5)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 9, 3, 1, 1)
        self.lblContract = QtGui.QLabel(ReportClientActionsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblContract.sizePolicy().hasHeightForWidth())
        self.lblContract.setSizePolicy(sizePolicy)
        self.lblContract.setObjectName(_fromUtf8("lblContract"))
        self.gridLayout.addWidget(self.lblContract, 7, 0, 1, 1)
        self.cmbContract = CContractComboBox(ReportClientActionsSetupDialog)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.gridLayout.addWidget(self.cmbContract, 7, 1, 1, 4)
        self.lblFinance = QtGui.QLabel(ReportClientActionsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFinance.sizePolicy().hasHeightForWidth())
        self.lblFinance.setSizePolicy(sizePolicy)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout.addWidget(self.lblFinance, 6, 0, 1, 1)
        self.lblResultType = QtGui.QLabel(ReportClientActionsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblResultType.sizePolicy().hasHeightForWidth())
        self.lblResultType.setSizePolicy(sizePolicy)
        self.lblResultType.setObjectName(_fromUtf8("lblResultType"))
        self.gridLayout.addWidget(self.lblResultType, 0, 0, 1, 1)
        self.cmbResultType = QtGui.QComboBox(ReportClientActionsSetupDialog)
        self.cmbResultType.setObjectName(_fromUtf8("cmbResultType"))
        self.cmbResultType.addItem(_fromUtf8(""))
        self.cmbResultType.addItem(_fromUtf8(""))
        self.cmbResultType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbResultType, 0, 1, 1, 3)
        self.chkDetailDateAndPersonCode = QtGui.QCheckBox(ReportClientActionsSetupDialog)
        self.chkDetailDateAndPersonCode.setObjectName(_fromUtf8("chkDetailDateAndPersonCode"))
        self.gridLayout.addWidget(self.chkDetailDateAndPersonCode, 1, 0, 1, 4)
        self.chkOnlyAccounting = QtGui.QCheckBox(ReportClientActionsSetupDialog)
        self.chkOnlyAccounting.setObjectName(_fromUtf8("chkOnlyAccounting"))
        self.gridLayout.addWidget(self.chkOnlyAccounting, 2, 0, 1, 3)
        self.lblOrgStructure = QtGui.QLabel(ReportClientActionsSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 8, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(ReportClientActionsSetupDialog)
        self.cmbOrgStructure.setEnabled(True)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 8, 1, 1, 4)
        self.cmbFinance = CRBComboBox(ReportClientActionsSetupDialog)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout.addWidget(self.cmbFinance, 6, 1, 1, 4)
        self.lblLastName.setBuddy(self.edtLastName)
        self.lblFirstName.setBuddy(self.edtFirstName)
        self.lblCompulsoryPolicy.setBuddy(self.edtPolicySerial)
        self.lblCompulsoryPolisSerial.setBuddy(self.edtPolicySerial)
        self.lblCompulsoryPolisNumber.setBuddy(self.edtPolicyNumber)
        self.lblCompulsoryPolisCompany.setBuddy(self.cmbPolicyCompany)

        self.retranslateUi(ReportClientActionsSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportClientActionsSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportClientActionsSetupDialog.reject)
        QtCore.QObject.connect(self.chkClientCode, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtClientCode.setEnabled)
        QtCore.QObject.connect(self.chkClientCode, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbAccountingSystem.setEnabled)
        QtCore.QObject.connect(self.chkClientCode, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtLastName.setDisabled)
        QtCore.QObject.connect(self.chkClientCode, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtFirstName.setDisabled)
        QtCore.QObject.connect(self.chkClientCode, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtPatrName.setDisabled)
        QtCore.QObject.connect(self.chkClientCode, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtBirthDate.setDisabled)
        QtCore.QObject.connect(self.chkClientCode, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbDocType.setDisabled)
        QtCore.QObject.connect(self.chkClientCode, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtLeftSerial.setDisabled)
        QtCore.QObject.connect(self.chkClientCode, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtRightSerial.setDisabled)
        QtCore.QObject.connect(self.chkClientCode, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtNumber.setDisabled)
        QtCore.QObject.connect(self.chkClientCode, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbPolicyType.setDisabled)
        QtCore.QObject.connect(self.chkClientCode, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtPolicySerial.setDisabled)
        QtCore.QObject.connect(self.chkClientCode, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtPolicyNumber.setDisabled)
        QtCore.QObject.connect(self.chkClientCode, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbPolicyCompany.setDisabled)
        QtCore.QObject.connect(self.chkClientCode, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtContact.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(ReportClientActionsSetupDialog)
        ReportClientActionsSetupDialog.setTabOrder(self.cmbResultType, self.chkClientCode)
        ReportClientActionsSetupDialog.setTabOrder(self.chkClientCode, self.edtClientCode)
        ReportClientActionsSetupDialog.setTabOrder(self.edtClientCode, self.cmbAccountingSystem)
        ReportClientActionsSetupDialog.setTabOrder(self.cmbAccountingSystem, self.edtLastName)
        ReportClientActionsSetupDialog.setTabOrder(self.edtLastName, self.edtFirstName)
        ReportClientActionsSetupDialog.setTabOrder(self.edtFirstName, self.edtPatrName)
        ReportClientActionsSetupDialog.setTabOrder(self.edtPatrName, self.edtBirthDate)
        ReportClientActionsSetupDialog.setTabOrder(self.edtBirthDate, self.cmbDocType)
        ReportClientActionsSetupDialog.setTabOrder(self.cmbDocType, self.edtLeftSerial)
        ReportClientActionsSetupDialog.setTabOrder(self.edtLeftSerial, self.edtRightSerial)
        ReportClientActionsSetupDialog.setTabOrder(self.edtRightSerial, self.edtNumber)
        ReportClientActionsSetupDialog.setTabOrder(self.edtNumber, self.cmbPolicyType)
        ReportClientActionsSetupDialog.setTabOrder(self.cmbPolicyType, self.edtPolicySerial)
        ReportClientActionsSetupDialog.setTabOrder(self.edtPolicySerial, self.edtPolicyNumber)
        ReportClientActionsSetupDialog.setTabOrder(self.edtPolicyNumber, self.cmbPolicyCompany)
        ReportClientActionsSetupDialog.setTabOrder(self.cmbPolicyCompany, self.edtContact)
        ReportClientActionsSetupDialog.setTabOrder(self.edtContact, self.cmbActionDateType)
        ReportClientActionsSetupDialog.setTabOrder(self.cmbActionDateType, self.edtBegDate)
        ReportClientActionsSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ReportClientActionsSetupDialog.setTabOrder(self.edtEndDate, self.cmbFinance)
        ReportClientActionsSetupDialog.setTabOrder(self.cmbFinance, self.cmbContract)
        ReportClientActionsSetupDialog.setTabOrder(self.cmbContract, self.buttonBox)

    def retranslateUi(self, ReportClientActionsSetupDialog):
        ReportClientActionsSetupDialog.setWindowTitle(_translate("ReportClientActionsSetupDialog", "Dialog", None))
        self.grpClient.setTitle(_translate("ReportClientActionsSetupDialog", "Пациент", None))
        self.lblLastName.setText(_translate("ReportClientActionsSetupDialog", "Фамилия", None))
        self.lblFirstName.setText(_translate("ReportClientActionsSetupDialog", "Имя", None))
        self.lblPatrName.setText(_translate("ReportClientActionsSetupDialog", "Отчество", None))
        self.lblBirthDate.setText(_translate("ReportClientActionsSetupDialog", "Дата рождения", None))
        self.edtBirthDate.setDisplayFormat(_translate("ReportClientActionsSetupDialog", "dd.MM.yyyy", None))
        self.lblDocument.setText(_translate("ReportClientActionsSetupDialog", "Документ", None))
        self.lblSerial.setText(_translate("ReportClientActionsSetupDialog", "Серия", None))
        self.lblNumber.setText(_translate("ReportClientActionsSetupDialog", "Номер", None))
        self.lblCompulsoryPolicy.setText(_translate("ReportClientActionsSetupDialog", "Полис", None))
        self.lblCompulsoryPolisSerial.setText(_translate("ReportClientActionsSetupDialog", "Серия", None))
        self.lblCompulsoryPolisNumber.setText(_translate("ReportClientActionsSetupDialog", "Номер", None))
        self.lblCompulsoryPolisCompany.setText(_translate("ReportClientActionsSetupDialog", "СМО", None))
        self.lblContact.setText(_translate("ReportClientActionsSetupDialog", "Контакт", None))
        self.chkClientCode.setText(_translate("ReportClientActionsSetupDialog", "Код", None))
        self.lblActionDateType.setText(_translate("ReportClientActionsSetupDialog", "Тип даты действия", None))
        self.cmbActionDateType.setItemText(0, _translate("ReportClientActionsSetupDialog", "Возможные типы дат", None))
        self.lblDate.setText(_translate("ReportClientActionsSetupDialog", "Период", None))
        self.lblContract.setText(_translate("ReportClientActionsSetupDialog", "Контракт", None))
        self.lblFinance.setText(_translate("ReportClientActionsSetupDialog", "Тип финансирования", None))
        self.lblResultType.setText(_translate("ReportClientActionsSetupDialog", "Результат", None))
        self.cmbResultType.setItemText(0, _translate("ReportClientActionsSetupDialog", "Отчет", None))
        self.cmbResultType.setItemText(1, _translate("ReportClientActionsSetupDialog", "Реестр", None))
        self.cmbResultType.setItemText(2, _translate("ReportClientActionsSetupDialog", "Реестр услуг с датами выполнения", None))
        self.chkDetailDateAndPersonCode.setText(_translate("ReportClientActionsSetupDialog", "Выводить дату оказания и исполнителя услуги", None))
        self.chkOnlyAccounting.setText(_translate("ReportClientActionsSetupDialog", "Только по счетам", None))
        self.lblOrgStructure.setText(_translate("ReportClientActionsSetupDialog", "Подразделение", None))

from Accounting.ContractComboBox import CContractComboBox
from Orgs.OrgComboBox import CInsurerComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Registry.PolicySerialEdit import CPolicySerialEdit
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
