# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReportF30Setup.ui'
#
# Created: Mon Nov  2 15:09:35 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportF30SetupDialog(object):
    def setupUi(self, ReportF30SetupDialog):
        ReportF30SetupDialog.setObjectName(_fromUtf8("ReportF30SetupDialog"))
        ReportF30SetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ReportF30SetupDialog.resize(736, 837)
        ReportF30SetupDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(ReportF30SetupDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblSocStatusClass = QtGui.QLabel(ReportF30SetupDialog)
        self.lblSocStatusClass.setObjectName(_fromUtf8("lblSocStatusClass"))
        self.gridLayout.addWidget(self.lblSocStatusClass, 14, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(61, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.chkDetailChildren = QtGui.QCheckBox(ReportF30SetupDialog)
        self.chkDetailChildren.setObjectName(_fromUtf8("chkDetailChildren"))
        self.gridLayout.addWidget(self.chkDetailChildren, 4, 2, 1, 2)
        self.lblSex = QtGui.QLabel(ReportF30SetupDialog)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout.addWidget(self.lblSex, 12, 0, 1, 2)
        self.chkDivideWeekdays = QtGui.QCheckBox(ReportF30SetupDialog)
        self.chkDivideWeekdays.setObjectName(_fromUtf8("chkDivideWeekdays"))
        self.gridLayout.addWidget(self.chkDivideWeekdays, 3, 2, 1, 2)
        self.lblEndDate = QtGui.QLabel(ReportF30SetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 2)
        self.cmbSex = QtGui.QComboBox(ReportF30SetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 12, 2, 1, 2)
        self.cmbOrgStructure = COrgStructureComboBox(ReportF30SetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 11, 2, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(61, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 1)
        self.cmbPrimary = QtGui.QComboBox(ReportF30SetupDialog)
        self.cmbPrimary.setObjectName(_fromUtf8("cmbPrimary"))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPrimary, 8, 2, 1, 2)
        self.lblSocStatusType = QtGui.QLabel(ReportF30SetupDialog)
        self.lblSocStatusType.setObjectName(_fromUtf8("lblSocStatusType"))
        self.gridLayout.addWidget(self.lblSocStatusType, 15, 0, 1, 2)
        self.cmbVisitPayStatus = QtGui.QComboBox(ReportF30SetupDialog)
        self.cmbVisitPayStatus.setObjectName(_fromUtf8("cmbVisitPayStatus"))
        self.cmbVisitPayStatus.addItem(_fromUtf8(""))
        self.cmbVisitPayStatus.addItem(_fromUtf8(""))
        self.cmbVisitPayStatus.addItem(_fromUtf8(""))
        self.cmbVisitPayStatus.addItem(_fromUtf8(""))
        self.cmbVisitPayStatus.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbVisitPayStatus, 21, 2, 1, 2)
        self.cmbTypeFinance = CRBComboBox(ReportF30SetupDialog)
        self.cmbTypeFinance.setObjectName(_fromUtf8("cmbTypeFinance"))
        self.gridLayout.addWidget(self.cmbTypeFinance, 16, 2, 1, 2)
        self.cmbInsurer = CInsurerComboBox(ReportF30SetupDialog)
        self.cmbInsurer.setObjectName(_fromUtf8("cmbInsurer"))
        self.gridLayout.addWidget(self.cmbInsurer, 20, 2, 1, 2)
        self.edtBegDate = QtGui.QDateEdit(ReportF30SetupDialog)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 2, 1, 2)
        self.lblAge = QtGui.QLabel(ReportF30SetupDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout.addWidget(self.lblAge, 13, 0, 1, 2)
        self.cmbEventPurpose = CRBComboBox(ReportF30SetupDialog)
        self.cmbEventPurpose.setObjectName(_fromUtf8("cmbEventPurpose"))
        self.gridLayout.addWidget(self.cmbEventPurpose, 9, 2, 1, 2)
        self.lblEventPurpose = QtGui.QLabel(ReportF30SetupDialog)
        self.lblEventPurpose.setObjectName(_fromUtf8("lblEventPurpose"))
        self.gridLayout.addWidget(self.lblEventPurpose, 9, 0, 1, 2)
        self.frmAge = QtGui.QFrame(ReportF30SetupDialog)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self._2 = QtGui.QHBoxLayout(self.frmAge)
        self._2.setSpacing(4)
        self._2.setMargin(0)
        self._2.setObjectName(_fromUtf8("_2"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self._2.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self._2.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self._2.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self._2.addWidget(self.lblAgeYears)
        spacerItem2 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem2)
        self.gridLayout.addWidget(self.frmAge, 13, 2, 1, 2)
        self.gbEventDatetimeParams = QtGui.QGroupBox(ReportF30SetupDialog)
        self.gbEventDatetimeParams.setCheckable(True)
        self.gbEventDatetimeParams.setChecked(False)
        self.gbEventDatetimeParams.setObjectName(_fromUtf8("gbEventDatetimeParams"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gbEventDatetimeParams)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.gbEventDatetimeParams)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.edtEventBegDatetime = QtGui.QDateTimeEdit(self.gbEventDatetimeParams)
        self.edtEventBegDatetime.setObjectName(_fromUtf8("edtEventBegDatetime"))
        self.gridLayout_2.addWidget(self.edtEventBegDatetime, 0, 1, 1, 1)
        self.edtEventEndDatetime = QtGui.QDateTimeEdit(self.gbEventDatetimeParams)
        self.edtEventEndDatetime.setObjectName(_fromUtf8("edtEventEndDatetime"))
        self.gridLayout_2.addWidget(self.edtEventEndDatetime, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.gbEventDatetimeParams, 2, 0, 1, 5)
        self.lblTariff = QtGui.QLabel(ReportF30SetupDialog)
        self.lblTariff.setObjectName(_fromUtf8("lblTariff"))
        self.gridLayout.addWidget(self.lblTariff, 17, 0, 1, 1)
        self.edtEndDate = QtGui.QDateEdit(ReportF30SetupDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 2, 1, 2)
        self.lblInsurer = QtGui.QLabel(ReportF30SetupDialog)
        self.lblInsurer.setObjectName(_fromUtf8("lblInsurer"))
        self.gridLayout.addWidget(self.lblInsurer, 20, 0, 1, 1)
        self.chkVisitDisp = QtGui.QCheckBox(ReportF30SetupDialog)
        self.chkVisitDisp.setObjectName(_fromUtf8("chkVisitDisp"))
        self.gridLayout.addWidget(self.chkVisitDisp, 7, 2, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(ReportF30SetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 24, 0, 1, 4)
        self.cmbSocStatusClass = CSocStatusComboBox(ReportF30SetupDialog)
        self.cmbSocStatusClass.setObjectName(_fromUtf8("cmbSocStatusClass"))
        self.gridLayout.addWidget(self.cmbSocStatusClass, 14, 2, 1, 2)
        self.lblBegDate = QtGui.QLabel(ReportF30SetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 23, 0, 1, 2)
        self.chkVisitEmergency = QtGui.QCheckBox(ReportF30SetupDialog)
        self.chkVisitEmergency.setObjectName(_fromUtf8("chkVisitEmergency"))
        self.gridLayout.addWidget(self.chkVisitEmergency, 6, 2, 1, 2)
        self.lblOrgStructure = QtGui.QLabel(ReportF30SetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 11, 0, 1, 2)
        self.lblEventType = QtGui.QLabel(ReportF30SetupDialog)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridLayout.addWidget(self.lblEventType, 10, 0, 1, 2)
        self.lblTypeFinance = QtGui.QLabel(ReportF30SetupDialog)
        self.lblTypeFinance.setObjectName(_fromUtf8("lblTypeFinance"))
        self.gridLayout.addWidget(self.lblTypeFinance, 16, 0, 1, 2)
        self.cmbSocStatusType = CRBComboBox(ReportF30SetupDialog)
        self.cmbSocStatusType.setObjectName(_fromUtf8("cmbSocStatusType"))
        self.gridLayout.addWidget(self.cmbSocStatusType, 15, 2, 1, 2)
        self.cmbTariff = QtGui.QComboBox(ReportF30SetupDialog)
        self.cmbTariff.setObjectName(_fromUtf8("cmbTariff"))
        self.cmbTariff.addItem(_fromUtf8(""))
        self.cmbTariff.addItem(_fromUtf8(""))
        self.cmbTariff.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbTariff, 17, 2, 1, 1)
        self.cmbEventType = CRBComboBox(ReportF30SetupDialog)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout.addWidget(self.cmbEventType, 10, 2, 1, 2)
        self.cmbGrouping = QtGui.QComboBox(ReportF30SetupDialog)
        self.cmbGrouping.setObjectName(_fromUtf8("cmbGrouping"))
        self.cmbGrouping.addItem(_fromUtf8(""))
        self.cmbGrouping.addItem(_fromUtf8(""))
        self.cmbGrouping.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbGrouping, 22, 2, 1, 2)
        self.chkVisitHospital = QtGui.QCheckBox(ReportF30SetupDialog)
        self.chkVisitHospital.setObjectName(_fromUtf8("chkVisitHospital"))
        self.gridLayout.addWidget(self.chkVisitHospital, 5, 2, 1, 2)
        self.lblGrouping = QtGui.QLabel(ReportF30SetupDialog)
        self.lblGrouping.setObjectName(_fromUtf8("lblGrouping"))
        self.gridLayout.addWidget(self.lblGrouping, 22, 0, 1, 2)
        self.label = QtGui.QLabel(ReportF30SetupDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 8, 0, 1, 2)
        self.lblVisitPayStatus = QtGui.QLabel(ReportF30SetupDialog)
        self.lblVisitPayStatus.setObjectName(_fromUtf8("lblVisitPayStatus"))
        self.gridLayout.addWidget(self.lblVisitPayStatus, 21, 0, 1, 2)
        self.lblSocStatusClass.setBuddy(self.cmbSocStatusClass)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblSocStatusType.setBuddy(self.cmbSocStatusType)
        self.lblAge.setBuddy(self.edtAgeFrom)
        self.lblEventPurpose.setBuddy(self.cmbEventPurpose)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblEventType.setBuddy(self.cmbEventType)

        self.retranslateUi(ReportF30SetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportF30SetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportF30SetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ReportF30SetupDialog)
        ReportF30SetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ReportF30SetupDialog.setTabOrder(self.edtEndDate, self.gbEventDatetimeParams)
        ReportF30SetupDialog.setTabOrder(self.gbEventDatetimeParams, self.chkDivideWeekdays)
        ReportF30SetupDialog.setTabOrder(self.chkDivideWeekdays, self.chkDetailChildren)
        ReportF30SetupDialog.setTabOrder(self.chkDetailChildren, self.chkVisitHospital)
        ReportF30SetupDialog.setTabOrder(self.chkVisitHospital, self.chkVisitEmergency)
        ReportF30SetupDialog.setTabOrder(self.chkVisitEmergency, self.cmbPrimary)
        ReportF30SetupDialog.setTabOrder(self.cmbPrimary, self.cmbEventPurpose)
        ReportF30SetupDialog.setTabOrder(self.cmbEventPurpose, self.cmbEventType)
        ReportF30SetupDialog.setTabOrder(self.cmbEventType, self.cmbOrgStructure)
        ReportF30SetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbSex)
        ReportF30SetupDialog.setTabOrder(self.cmbSex, self.edtAgeFrom)
        ReportF30SetupDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        ReportF30SetupDialog.setTabOrder(self.edtAgeTo, self.cmbSocStatusClass)
        ReportF30SetupDialog.setTabOrder(self.cmbSocStatusClass, self.cmbSocStatusType)
        ReportF30SetupDialog.setTabOrder(self.cmbSocStatusType, self.cmbTypeFinance)
        ReportF30SetupDialog.setTabOrder(self.cmbTypeFinance, self.cmbTariff)
        ReportF30SetupDialog.setTabOrder(self.cmbTariff, self.cmbInsurer)
        ReportF30SetupDialog.setTabOrder(self.cmbInsurer, self.cmbVisitPayStatus)
        ReportF30SetupDialog.setTabOrder(self.cmbVisitPayStatus, self.cmbGrouping)
        ReportF30SetupDialog.setTabOrder(self.cmbGrouping, self.buttonBox)

    def retranslateUi(self, ReportF30SetupDialog):
        ReportF30SetupDialog.setWindowTitle(_translate("ReportF30SetupDialog", "параметры отчёта", None))
        self.lblSocStatusClass.setText(_translate("ReportF30SetupDialog", "Класс соц.статуса", None))
        self.chkDetailChildren.setText(_translate("ReportF30SetupDialog", "Детализация по подросткам", None))
        self.lblSex.setText(_translate("ReportF30SetupDialog", "По&л", None))
        self.chkDivideWeekdays.setText(_translate("ReportF30SetupDialog", "Разделять рабочие и выходные", None))
        self.lblEndDate.setText(_translate("ReportF30SetupDialog", "Дата окончания периода", None))
        self.cmbSex.setItemText(1, _translate("ReportF30SetupDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("ReportF30SetupDialog", "Ж", None))
        self.cmbPrimary.setItemText(0, _translate("ReportF30SetupDialog", "Не заполнять", None))
        self.cmbPrimary.setItemText(1, _translate("ReportF30SetupDialog", "Первичный", None))
        self.cmbPrimary.setItemText(2, _translate("ReportF30SetupDialog", "Повторный", None))
        self.cmbPrimary.setItemText(3, _translate("ReportF30SetupDialog", "Активное посещение", None))
        self.cmbPrimary.setItemText(4, _translate("ReportF30SetupDialog", "Перевозка", None))
        self.cmbPrimary.setItemText(5, _translate("ReportF30SetupDialog", "Амбулаторно", None))
        self.lblSocStatusType.setText(_translate("ReportF30SetupDialog", "Тип соц.статуса", None))
        self.cmbVisitPayStatus.setItemText(0, _translate("ReportF30SetupDialog", "не задано", None))
        self.cmbVisitPayStatus.setItemText(1, _translate("ReportF30SetupDialog", "не выставлено", None))
        self.cmbVisitPayStatus.setItemText(2, _translate("ReportF30SetupDialog", "выставлено", None))
        self.cmbVisitPayStatus.setItemText(3, _translate("ReportF30SetupDialog", "отказано", None))
        self.cmbVisitPayStatus.setItemText(4, _translate("ReportF30SetupDialog", "оплачено", None))
        self.lblAge.setText(_translate("ReportF30SetupDialog", "Во&зраст с", None))
        self.lblEventPurpose.setText(_translate("ReportF30SetupDialog", "&Назначение обращения", None))
        self.lblAgeTo.setText(_translate("ReportF30SetupDialog", "по", None))
        self.lblAgeYears.setText(_translate("ReportF30SetupDialog", "лет", None))
        self.gbEventDatetimeParams.setTitle(_translate("ReportF30SetupDialog", "Дата и время создания обращения", None))
        self.label_3.setText(_translate("ReportF30SetupDialog", "Интервал дат и времени (с, по):", None))
        self.lblTariff.setText(_translate("ReportF30SetupDialog", "Тарификация", None))
        self.lblInsurer.setText(_translate("ReportF30SetupDialog", "СМО", None))
        self.chkVisitDisp.setText(_translate("ReportF30SetupDialog", "Учитывать посещения по диспансеризации", None))
        self.lblBegDate.setText(_translate("ReportF30SetupDialog", "Дата начала периода", None))
        self.chkVisitEmergency.setText(_translate("ReportF30SetupDialog", "Учитывать посещения СМП", None))
        self.lblOrgStructure.setText(_translate("ReportF30SetupDialog", "Подразделение", None))
        self.lblEventType.setText(_translate("ReportF30SetupDialog", "&Тип обращения", None))
        self.lblTypeFinance.setText(_translate("ReportF30SetupDialog", "Тип финансирования", None))
        self.cmbTariff.setItemText(0, _translate("ReportF30SetupDialog", "не учитывать", None))
        self.cmbTariff.setItemText(1, _translate("ReportF30SetupDialog", "тарифицированные", None))
        self.cmbTariff.setItemText(2, _translate("ReportF30SetupDialog", "не тарифицированные", None))
        self.cmbGrouping.setItemText(0, _translate("ReportF30SetupDialog", "по специальности", None))
        self.cmbGrouping.setItemText(1, _translate("ReportF30SetupDialog", "по должности", None))
        self.cmbGrouping.setItemText(2, _translate("ReportF30SetupDialog", "по отделению", None))
        self.chkVisitHospital.setText(_translate("ReportF30SetupDialog", "Учитывать посещения ДС", None))
        self.lblGrouping.setText(_translate("ReportF30SetupDialog", "Группировка", None))
        self.label.setText(_translate("ReportF30SetupDialog", "Признак первичности", None))
        self.lblVisitPayStatus.setText(_translate("ReportF30SetupDialog", "Флаг финансирования", None))

from Orgs.OrgComboBox import CInsurerComboBox
from library.crbcombobox import CRBComboBox
from Registry.SocStatusComboBox import CSocStatusComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
