# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReportSetup.ui'
#
# Created: Fri Apr 18 02:21:40 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportSetupDialog(object):
    def setupUi(self, ReportSetupDialog):
        ReportSetupDialog.setObjectName(_fromUtf8("ReportSetupDialog"))
        ReportSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ReportSetupDialog.resize(572, 668)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ReportSetupDialog.sizePolicy().hasHeightForWidth())
        ReportSetupDialog.setSizePolicy(sizePolicy)
        ReportSetupDialog.setSizeGripEnabled(True)
        ReportSetupDialog.setModal(True)
        self.gridLayout = QtGui.QGridLayout(ReportSetupDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblBegDate = QtGui.QLabel(ReportSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.lblEndPayDate = QtGui.QLabel(ReportSetupDialog)
        self.lblEndPayDate.setObjectName(_fromUtf8("lblEndPayDate"))
        self.gridLayout.addWidget(self.lblEndPayDate, 9, 4, 1, 1)
        self.chkOnlyPermanentAttach = QtGui.QCheckBox(ReportSetupDialog)
        self.chkOnlyPermanentAttach.setObjectName(_fromUtf8("chkOnlyPermanentAttach"))
        self.gridLayout.addWidget(self.chkOnlyPermanentAttach, 5, 1, 1, 9)
        self.edtBegPayDate = CDateEdit(ReportSetupDialog)
        self.edtBegPayDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegPayDate.sizePolicy().hasHeightForWidth())
        self.edtBegPayDate.setSizePolicy(sizePolicy)
        self.edtBegPayDate.setCalendarPopup(True)
        self.edtBegPayDate.setObjectName(_fromUtf8("edtBegPayDate"))
        self.gridLayout.addWidget(self.edtBegPayDate, 9, 1, 1, 3)
        self.cmbMKBFilter = QtGui.QComboBox(ReportSetupDialog)
        self.cmbMKBFilter.setObjectName(_fromUtf8("cmbMKBFilter"))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbMKBFilter, 27, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(81, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 24, 8, 1, 2)
        self.chkOnlyPayedEvents = QtGui.QCheckBox(ReportSetupDialog)
        self.chkOnlyPayedEvents.setObjectName(_fromUtf8("chkOnlyPayedEvents"))
        self.gridLayout.addWidget(self.chkOnlyPayedEvents, 7, 1, 1, 9)
        self.frmAge = QtGui.QFrame(ReportSetupDialog)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self.hboxlayout = QtGui.QHBoxLayout(self.frmAge)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self.hboxlayout.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAgeTo.sizePolicy().hasHeightForWidth())
        self.lblAgeTo.setSizePolicy(sizePolicy)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self.hboxlayout.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self.hboxlayout.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self.hboxlayout.addWidget(self.lblAgeYears)
        self.gridLayout.addWidget(self.frmAge, 21, 1, 1, 5)
        self.lblWorkOrganisation = QtGui.QLabel(ReportSetupDialog)
        self.lblWorkOrganisation.setObjectName(_fromUtf8("lblWorkOrganisation"))
        self.gridLayout.addWidget(self.lblWorkOrganisation, 19, 0, 1, 1)
        self.cmbActionType = CActionTypeComboBox(ReportSetupDialog)
        self.cmbActionType.setObjectName(_fromUtf8("cmbActionType"))
        self.gridLayout.addWidget(self.cmbActionType, 24, 1, 1, 7)
        self.lblAge = QtGui.QLabel(ReportSetupDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout.addWidget(self.lblAge, 21, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(ReportSetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 13, 1, 1, 9)
        self.edtEndPayDate = CDateEdit(ReportSetupDialog)
        self.edtEndPayDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndPayDate.sizePolicy().hasHeightForWidth())
        self.edtEndPayDate.setSizePolicy(sizePolicy)
        self.edtEndPayDate.setCalendarPopup(True)
        self.edtEndPayDate.setObjectName(_fromUtf8("edtEndPayDate"))
        self.gridLayout.addWidget(self.edtEndPayDate, 9, 6, 1, 1)
        self.lblInsurer = QtGui.QLabel(ReportSetupDialog)
        self.lblInsurer.setObjectName(_fromUtf8("lblInsurer"))
        self.gridLayout.addWidget(self.lblInsurer, 12, 0, 1, 1)
        self.lblEndDate = QtGui.QLabel(ReportSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.lblActionTypeClass = QtGui.QLabel(ReportSetupDialog)
        self.lblActionTypeClass.setObjectName(_fromUtf8("lblActionTypeClass"))
        self.gridLayout.addWidget(self.lblActionTypeClass, 23, 0, 1, 1)
        self.cmbStage = CRBComboBox(ReportSetupDialog)
        self.cmbStage.setObjectName(_fromUtf8("cmbStage"))
        self.gridLayout.addWidget(self.cmbStage, 4, 1, 1, 9)
        self.chkDiagnosisType = QtGui.QCheckBox(ReportSetupDialog)
        self.chkDiagnosisType.setObjectName(_fromUtf8("chkDiagnosisType"))
        self.gridLayout.addWidget(self.chkDiagnosisType, 8, 1, 1, 9)
        self.lblSpeciality = QtGui.QLabel(ReportSetupDialog)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridLayout.addWidget(self.lblSpeciality, 14, 0, 1, 1)
        self.cmbInsurer = CInsurerComboBox(ReportSetupDialog)
        self.cmbInsurer.setObjectName(_fromUtf8("cmbInsurer"))
        self.gridLayout.addWidget(self.cmbInsurer, 12, 1, 1, 9)
        spacerItem1 = QtGui.QSpacerItem(141, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 20, 2, 1, 8)
        self.lblWorkType = QtGui.QLabel(ReportSetupDialog)
        self.lblWorkType.setObjectName(_fromUtf8("lblWorkType"))
        self.gridLayout.addWidget(self.lblWorkType, 17, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(61, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 4, 1, 6)
        self.lblBegPayDate = QtGui.QLabel(ReportSetupDialog)
        self.lblBegPayDate.setObjectName(_fromUtf8("lblBegPayDate"))
        self.gridLayout.addWidget(self.lblBegPayDate, 9, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ReportSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 31, 0, 1, 10)
        self.lblActionType = QtGui.QLabel(ReportSetupDialog)
        self.lblActionType.setObjectName(_fromUtf8("lblActionType"))
        self.gridLayout.addWidget(self.lblActionType, 24, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(428, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 30, 0, 1, 10)
        self.chkActionClass = QtGui.QCheckBox(ReportSetupDialog)
        self.chkActionClass.setObjectName(_fromUtf8("chkActionClass"))
        self.gridLayout.addWidget(self.chkActionClass, 22, 0, 1, 10)
        self.lblOrgStructure = QtGui.QLabel(ReportSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 13, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 21, 6, 1, 4)
        self.btnSelectWorkOrganisation = QtGui.QToolButton(ReportSetupDialog)
        self.btnSelectWorkOrganisation.setObjectName(_fromUtf8("btnSelectWorkOrganisation"))
        self.gridLayout.addWidget(self.btnSelectWorkOrganisation, 19, 9, 1, 1)
        self.edtMKBTo = CICDCodeEdit(ReportSetupDialog)
        self.edtMKBTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBTo.sizePolicy().hasHeightForWidth())
        self.edtMKBTo.setSizePolicy(sizePolicy)
        self.edtMKBTo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBTo.setMaxLength(6)
        self.edtMKBTo.setObjectName(_fromUtf8("edtMKBTo"))
        self.gridLayout.addWidget(self.edtMKBTo, 27, 5, 1, 2)
        self.lblFinance = QtGui.QLabel(ReportSetupDialog)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout.addWidget(self.lblFinance, 25, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(ReportSetupDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 16, 1, 1, 9)
        self.cmbFinance = CRBComboBox(ReportSetupDialog)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout.addWidget(self.cmbFinance, 25, 1, 1, 7)
        self.lblStage = QtGui.QLabel(ReportSetupDialog)
        self.lblStage.setObjectName(_fromUtf8("lblStage"))
        self.gridLayout.addWidget(self.lblStage, 4, 0, 1, 1)
        self.lblSex = QtGui.QLabel(ReportSetupDialog)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout.addWidget(self.lblSex, 20, 0, 1, 1)
        self.edtBegDate = CDateEdit(ReportSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 3)
        self.lblEventType = QtGui.QLabel(ReportSetupDialog)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridLayout.addWidget(self.lblEventType, 2, 0, 1, 1)
        self.lblPerson = QtGui.QLabel(ReportSetupDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 16, 0, 1, 1)
        self.lblOwnership = QtGui.QLabel(ReportSetupDialog)
        self.lblOwnership.setObjectName(_fromUtf8("lblOwnership"))
        self.gridLayout.addWidget(self.lblOwnership, 18, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(61, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 4, 1, 6)
        self.lblMKBFilter = QtGui.QLabel(ReportSetupDialog)
        self.lblMKBFilter.setObjectName(_fromUtf8("lblMKBFilter"))
        self.gridLayout.addWidget(self.lblMKBFilter, 27, 0, 1, 1)
        self.cmbEventType = CRBComboBox(ReportSetupDialog)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout.addWidget(self.cmbEventType, 2, 1, 1, 9)
        self.edtMKBFrom = CICDCodeEdit(ReportSetupDialog)
        self.edtMKBFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBFrom.sizePolicy().hasHeightForWidth())
        self.edtMKBFrom.setSizePolicy(sizePolicy)
        self.edtMKBFrom.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBFrom.setMaxLength(6)
        self.edtMKBFrom.setObjectName(_fromUtf8("edtMKBFrom"))
        self.gridLayout.addWidget(self.edtMKBFrom, 27, 3, 1, 2)
        self.cmbWorkType = QtGui.QComboBox(ReportSetupDialog)
        self.cmbWorkType.setObjectName(_fromUtf8("cmbWorkType"))
        self.gridLayout.addWidget(self.cmbWorkType, 17, 1, 1, 9)
        self.chkDetailPerson = QtGui.QCheckBox(ReportSetupDialog)
        self.chkDetailPerson.setObjectName(_fromUtf8("chkDetailPerson"))
        self.gridLayout.addWidget(self.chkDetailPerson, 15, 0, 1, 10)
        spacerItem6 = QtGui.QSpacerItem(117, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 27, 7, 1, 3)
        self.lblContract = QtGui.QLabel(ReportSetupDialog)
        self.lblContract.setObjectName(_fromUtf8("lblContract"))
        self.gridLayout.addWidget(self.lblContract, 26, 0, 1, 1)
        self.cmbContract = CContractComboBox(ReportSetupDialog)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.gridLayout.addWidget(self.cmbContract, 26, 1, 1, 7)
        self.cmbActionTypeClass = QtGui.QComboBox(ReportSetupDialog)
        self.cmbActionTypeClass.setObjectName(_fromUtf8("cmbActionTypeClass"))
        self.cmbActionTypeClass.addItem(_fromUtf8(""))
        self.cmbActionTypeClass.addItem(_fromUtf8(""))
        self.cmbActionTypeClass.addItem(_fromUtf8(""))
        self.cmbActionTypeClass.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbActionTypeClass, 23, 1, 1, 7)
        self.cmbSex = QtGui.QComboBox(ReportSetupDialog)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 20, 1, 1, 1)
        self.edtEndDate = CDateEdit(ReportSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 1, 1, 3)
        self.cmbOwnership = QtGui.QComboBox(ReportSetupDialog)
        self.cmbOwnership.setObjectName(_fromUtf8("cmbOwnership"))
        self.cmbOwnership.addItem(_fromUtf8(""))
        self.cmbOwnership.setItemText(0, _fromUtf8(""))
        self.cmbOwnership.addItem(_fromUtf8(""))
        self.cmbOwnership.addItem(_fromUtf8(""))
        self.cmbOwnership.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbOwnership, 18, 1, 1, 9)
        spacerItem7 = QtGui.QSpacerItem(31, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 23, 8, 1, 2)
        self.cmbSpeciality = CRBComboBox(ReportSetupDialog)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 14, 1, 1, 9)
        self.cmbWorkOrganisation = COrgComboBox(ReportSetupDialog)
        self.cmbWorkOrganisation.setObjectName(_fromUtf8("cmbWorkOrganisation"))
        self.gridLayout.addWidget(self.cmbWorkOrganisation, 19, 1, 1, 8)
        self.chkOnlyNotPayedEvents = QtGui.QCheckBox(ReportSetupDialog)
        self.chkOnlyNotPayedEvents.setObjectName(_fromUtf8("chkOnlyNotPayedEvents"))
        self.gridLayout.addWidget(self.chkOnlyNotPayedEvents, 8, 0, 1, 1)
        self.chkOnlyEmployee = QtGui.QCheckBox(ReportSetupDialog)
        self.chkOnlyEmployee.setObjectName(_fromUtf8("chkOnlyEmployee"))
        self.gridLayout.addWidget(self.chkOnlyEmployee, 5, 0, 1, 1)
        self.chkGroupByClients = QtGui.QCheckBox(ReportSetupDialog)
        self.chkGroupByClients.setObjectName(_fromUtf8("chkGroupByClients"))
        self.gridLayout.addWidget(self.chkGroupByClients, 7, 0, 1, 1)
        self.cmbEventPurpose = CRBComboBox(ReportSetupDialog)
        self.cmbEventPurpose.setObjectName(_fromUtf8("cmbEventPurpose"))
        self.gridLayout.addWidget(self.cmbEventPurpose, 3, 1, 1, 9)
        self.lblEventPurpose = QtGui.QLabel(ReportSetupDialog)
        self.lblEventPurpose.setObjectName(_fromUtf8("lblEventPurpose"))
        self.gridLayout.addWidget(self.lblEventPurpose, 3, 0, 1, 1)
        self.btnBrowseSourceDataFile = QtGui.QToolButton(ReportSetupDialog)
        self.btnBrowseSourceDataFile.setEnabled(False)
        self.btnBrowseSourceDataFile.setObjectName(_fromUtf8("btnBrowseSourceDataFile"))
        self.gridLayout.addWidget(self.btnBrowseSourceDataFile, 28, 9, 1, 1)
        self.edtSourceDataFileName = QtGui.QLineEdit(ReportSetupDialog)
        self.edtSourceDataFileName.setEnabled(False)
        self.edtSourceDataFileName.setObjectName(_fromUtf8("edtSourceDataFileName"))
        self.gridLayout.addWidget(self.edtSourceDataFileName, 28, 1, 1, 8)
        self.chkIsDataFromFile = QtGui.QCheckBox(ReportSetupDialog)
        self.chkIsDataFromFile.setObjectName(_fromUtf8("chkIsDataFromFile"))
        self.gridLayout.addWidget(self.chkIsDataFromFile, 28, 0, 1, 1)
        self.lblOrgStrucutreAttachType = QtGui.QLabel(ReportSetupDialog)
        self.lblOrgStrucutreAttachType.setObjectName(_fromUtf8("lblOrgStrucutreAttachType"))
        self.gridLayout.addWidget(self.lblOrgStrucutreAttachType, 29, 0, 1, 1)
        self.cmbOrgStructureAttachType = COrgStructureComboBox(ReportSetupDialog)
        self.cmbOrgStructureAttachType.setObjectName(_fromUtf8("cmbOrgStructureAttachType"))
        self.gridLayout.addWidget(self.cmbOrgStructureAttachType, 29, 1, 1, 7)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndPayDate.setBuddy(self.edtEndPayDate)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblAge.setBuddy(self.edtAgeFrom)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblActionTypeClass.setBuddy(self.cmbActionTypeClass)
        self.lblWorkType.setBuddy(self.cmbWorkType)
        self.lblBegPayDate.setBuddy(self.edtBegPayDate)
        self.lblActionType.setBuddy(self.cmbActionType)
        self.lblStage.setBuddy(self.cmbStage)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblEventType.setBuddy(self.cmbEventType)
        self.lblOwnership.setBuddy(self.cmbOwnership)
        self.lblMKBFilter.setBuddy(self.cmbMKBFilter)
        self.lblEventPurpose.setBuddy(self.cmbEventPurpose)

        self.retranslateUi(ReportSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportSetupDialog.reject)
        QtCore.QObject.connect(self.chkOnlyPayedEvents, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegPayDate.setEnabled)
        QtCore.QObject.connect(self.chkOnlyPayedEvents, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndPayDate.setEnabled)
        QtCore.QObject.connect(self.chkDetailPerson, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbPerson.setDisabled)
        QtCore.QObject.connect(self.chkActionClass, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbActionTypeClass.setDisabled)
        QtCore.QObject.connect(self.chkActionClass, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbActionType.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(ReportSetupDialog)
        ReportSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ReportSetupDialog.setTabOrder(self.edtEndDate, self.cmbEventType)
        ReportSetupDialog.setTabOrder(self.cmbEventType, self.cmbStage)
        ReportSetupDialog.setTabOrder(self.cmbStage, self.chkOnlyPermanentAttach)
        ReportSetupDialog.setTabOrder(self.chkOnlyPermanentAttach, self.chkOnlyPayedEvents)
        ReportSetupDialog.setTabOrder(self.chkOnlyPayedEvents, self.edtBegPayDate)
        ReportSetupDialog.setTabOrder(self.edtBegPayDate, self.cmbInsurer)
        ReportSetupDialog.setTabOrder(self.cmbInsurer, self.cmbOrgStructure)
        ReportSetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbSpeciality)
        ReportSetupDialog.setTabOrder(self.cmbSpeciality, self.chkDetailPerson)
        ReportSetupDialog.setTabOrder(self.chkDetailPerson, self.cmbPerson)
        ReportSetupDialog.setTabOrder(self.cmbPerson, self.cmbWorkType)
        ReportSetupDialog.setTabOrder(self.cmbWorkType, self.cmbOwnership)
        ReportSetupDialog.setTabOrder(self.cmbOwnership, self.cmbWorkOrganisation)
        ReportSetupDialog.setTabOrder(self.cmbWorkOrganisation, self.btnSelectWorkOrganisation)
        ReportSetupDialog.setTabOrder(self.btnSelectWorkOrganisation, self.cmbSex)
        ReportSetupDialog.setTabOrder(self.cmbSex, self.edtAgeFrom)
        ReportSetupDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        ReportSetupDialog.setTabOrder(self.edtAgeTo, self.chkActionClass)
        ReportSetupDialog.setTabOrder(self.chkActionClass, self.cmbActionTypeClass)
        ReportSetupDialog.setTabOrder(self.cmbActionTypeClass, self.cmbActionType)
        ReportSetupDialog.setTabOrder(self.cmbActionType, self.cmbFinance)
        ReportSetupDialog.setTabOrder(self.cmbFinance, self.cmbMKBFilter)
        ReportSetupDialog.setTabOrder(self.cmbMKBFilter, self.edtMKBFrom)
        ReportSetupDialog.setTabOrder(self.edtMKBFrom, self.edtMKBTo)
        ReportSetupDialog.setTabOrder(self.edtMKBTo, self.buttonBox)

    def retranslateUi(self, ReportSetupDialog):
        ReportSetupDialog.setWindowTitle(_translate("ReportSetupDialog", "параметры отчёта", None))
        self.lblBegDate.setText(_translate("ReportSetupDialog", "Дата &начала периода", None))
        self.lblEndPayDate.setText(_translate("ReportSetupDialog", "по", None))
        self.chkOnlyPermanentAttach.setText(_translate("ReportSetupDialog", "&Прикреплённые к базовому ЛПУ", None))
        self.cmbMKBFilter.setItemText(0, _translate("ReportSetupDialog", "Игнор.", None))
        self.cmbMKBFilter.setItemText(1, _translate("ReportSetupDialog", "Интервал", None))
        self.chkOnlyPayedEvents.setText(_translate("ReportSetupDialog", "Только опла&ченные", None))
        self.lblAgeTo.setText(_translate("ReportSetupDialog", "по", None))
        self.lblAgeYears.setText(_translate("ReportSetupDialog", "лет", None))
        self.lblWorkOrganisation.setText(_translate("ReportSetupDialog", "Место работы", None))
        self.lblAge.setText(_translate("ReportSetupDialog", "Возраст с", None))
        self.lblInsurer.setText(_translate("ReportSetupDialog", "СМО", None))
        self.lblEndDate.setText(_translate("ReportSetupDialog", "Дата &окончания периода", None))
        self.lblActionTypeClass.setText(_translate("ReportSetupDialog", "Кла&сс", None))
        self.chkDiagnosisType.setText(_translate("ReportSetupDialog", "Учитывать сопуствующие диагнозы", None))
        self.lblSpeciality.setText(_translate("ReportSetupDialog", "Специальность", None))
        self.lblWorkType.setText(_translate("ReportSetupDialog", "По ОКВЭД", None))
        self.lblBegPayDate.setText(_translate("ReportSetupDialog", "Оплачено в период с", None))
        self.lblActionType.setText(_translate("ReportSetupDialog", "&Мероприятие", None))
        self.chkActionClass.setText(_translate("ReportSetupDialog", "Не учитывать класс", None))
        self.lblOrgStructure.setText(_translate("ReportSetupDialog", "Подразделение", None))
        self.btnSelectWorkOrganisation.setText(_translate("ReportSetupDialog", "...", None))
        self.edtMKBTo.setInputMask(_translate("ReportSetupDialog", "a00.00; ", None))
        self.edtMKBTo.setText(_translate("ReportSetupDialog", "Z99.9", None))
        self.lblFinance.setText(_translate("ReportSetupDialog", "Тип финанисирования", None))
        self.lblStage.setText(_translate("ReportSetupDialog", "Стадия", None))
        self.lblSex.setText(_translate("ReportSetupDialog", "По&л", None))
        self.lblEventType.setText(_translate("ReportSetupDialog", "&Тип обращения", None))
        self.lblPerson.setText(_translate("ReportSetupDialog", "Врач", None))
        self.lblOwnership.setText(_translate("ReportSetupDialog", "Собственность", None))
        self.lblMKBFilter.setText(_translate("ReportSetupDialog", "Коды диагнозов по &МКБ", None))
        self.edtMKBFrom.setInputMask(_translate("ReportSetupDialog", "a00.00; ", None))
        self.edtMKBFrom.setText(_translate("ReportSetupDialog", "A.", None))
        self.chkDetailPerson.setText(_translate("ReportSetupDialog", "Детализировать по врачам", None))
        self.lblContract.setText(_translate("ReportSetupDialog", "Договор", None))
        self.cmbActionTypeClass.setItemText(0, _translate("ReportSetupDialog", "Статус", None))
        self.cmbActionTypeClass.setItemText(1, _translate("ReportSetupDialog", "Диагностика", None))
        self.cmbActionTypeClass.setItemText(2, _translate("ReportSetupDialog", "Лечение", None))
        self.cmbActionTypeClass.setItemText(3, _translate("ReportSetupDialog", "Прочие мероприятия", None))
        self.cmbSex.setItemText(1, _translate("ReportSetupDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("ReportSetupDialog", "Ж", None))
        self.cmbOwnership.setItemText(1, _translate("ReportSetupDialog", "Бюджетная", None))
        self.cmbOwnership.setItemText(2, _translate("ReportSetupDialog", "Частная", None))
        self.cmbOwnership.setItemText(3, _translate("ReportSetupDialog", "Смешенная", None))
        self.chkOnlyNotPayedEvents.setText(_translate("ReportSetupDialog", "Не оплаченные услуги", None))
        self.chkOnlyEmployee.setText(_translate("ReportSetupDialog", "Сотрудник", None))
        self.chkGroupByClients.setText(_translate("ReportSetupDialog", "Группировать по пациентам", None))
        self.lblEventPurpose.setText(_translate("ReportSetupDialog", "Назначение обращения", None))
        self.btnBrowseSourceDataFile.setText(_translate("ReportSetupDialog", "...", None))
        self.chkIsDataFromFile.setText(_translate("ReportSetupDialog", "Исходные данные из файла", None))
        self.lblOrgStrucutreAttachType.setText(_translate("ReportSetupDialog", "Подразделение прикрепления", None))

from Orgs.OrgComboBox import COrgComboBox, CInsurerComboBox
from Events.ActionTypeComboBox import CActionTypeComboBox
from library.crbcombobox import CRBComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.ICDCodeEdit import CICDCodeEdit
from Accounting.ContractComboBox import CContractComboBox
from library.DateEdit import CDateEdit
