# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\Reports\ReportF12_D_3_MSetup.ui'
#
# Created: Fri Jun 15 12:15:54 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ReportF12_D_3_MSetupDialog(object):
    def setupUi(self, ReportF12_D_3_MSetupDialog):
        ReportF12_D_3_MSetupDialog.setObjectName(_fromUtf8("ReportF12_D_3_MSetupDialog"))
        ReportF12_D_3_MSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ReportF12_D_3_MSetupDialog.resize(496, 420)
        ReportF12_D_3_MSetupDialog.setSizeGripEnabled(True)
        ReportF12_D_3_MSetupDialog.setModal(True)
        self.gridLayout_3 = QtGui.QGridLayout(ReportF12_D_3_MSetupDialog)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblBegDate = QtGui.QLabel(ReportF12_D_3_MSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDate.sizePolicy().hasHeightForWidth())
        self.lblBegDate.setSizePolicy(sizePolicy)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout_3.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.edtBegDate = CDateEdit(ReportF12_D_3_MSetupDialog)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout_3.addWidget(self.edtBegDate, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(261, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 2, 1, 1)
        self.lblEndDate = QtGui.QLabel(ReportF12_D_3_MSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDate.sizePolicy().hasHeightForWidth())
        self.lblEndDate.setSizePolicy(sizePolicy)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout_3.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.edtEndDate = CDateEdit(ReportF12_D_3_MSetupDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout_3.addWidget(self.edtEndDate, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(261, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 2, 1, 1)
        self.lblEventType = QtGui.QLabel(ReportF12_D_3_MSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventType.sizePolicy().hasHeightForWidth())
        self.lblEventType.setSizePolicy(sizePolicy)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridLayout_3.addWidget(self.lblEventType, 2, 0, 1, 1)
        self.cmbEventType = CRBComboBox(ReportF12_D_3_MSetupDialog)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout_3.addWidget(self.cmbEventType, 2, 1, 1, 2)
        self.chkOnlyPermanentAttach = QtGui.QCheckBox(ReportF12_D_3_MSetupDialog)
        self.chkOnlyPermanentAttach.setObjectName(_fromUtf8("chkOnlyPermanentAttach"))
        self.gridLayout_3.addWidget(self.chkOnlyPermanentAttach, 3, 1, 1, 2)
        self.chkOnlyPayedEvents = QtGui.QCheckBox(ReportF12_D_3_MSetupDialog)
        self.chkOnlyPayedEvents.setObjectName(_fromUtf8("chkOnlyPayedEvents"))
        self.gridLayout_3.addWidget(self.chkOnlyPayedEvents, 4, 1, 1, 2)
        self.gbTable1000 = QtGui.QGroupBox(ReportF12_D_3_MSetupDialog)
        self.gbTable1000.setObjectName(_fromUtf8("gbTable1000"))
        self.gridLayout = QtGui.QGridLayout(self.gbTable1000)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.gbTable1000)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.lblTotalText = QtGui.QLabel(self.gbTable1000)
        self.lblTotalText.setObjectName(_fromUtf8("lblTotalText"))
        self.gridLayout.addWidget(self.lblTotalText, 1, 0, 1, 1)
        self.sbCol3 = QtGui.QSpinBox(self.gbTable1000)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCol3.sizePolicy().hasHeightForWidth())
        self.sbCol3.setSizePolicy(sizePolicy)
        self.sbCol3.setMaximum(99999)
        self.sbCol3.setObjectName(_fromUtf8("sbCol3"))
        self.gridLayout.addWidget(self.sbCol3, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gbTable1000)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.sbCol4 = QtGui.QSpinBox(self.gbTable1000)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCol4.sizePolicy().hasHeightForWidth())
        self.sbCol4.setSizePolicy(sizePolicy)
        self.sbCol4.setMaximum(99999)
        self.sbCol4.setObjectName(_fromUtf8("sbCol4"))
        self.gridLayout.addWidget(self.sbCol4, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gbTable1000)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.gbTable1000)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.sbCol5 = QtGui.QSpinBox(self.gbTable1000)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCol5.sizePolicy().hasHeightForWidth())
        self.sbCol5.setSizePolicy(sizePolicy)
        self.sbCol5.setMaximum(99999)
        self.sbCol5.setObjectName(_fromUtf8("sbCol5"))
        self.gridLayout.addWidget(self.sbCol5, 4, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gbTable1000)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.sbCol6 = QtGui.QSpinBox(self.gbTable1000)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCol6.sizePolicy().hasHeightForWidth())
        self.sbCol6.setSizePolicy(sizePolicy)
        self.sbCol6.setMaximum(99999)
        self.sbCol6.setObjectName(_fromUtf8("sbCol6"))
        self.gridLayout.addWidget(self.sbCol6, 5, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gbTable1000)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.sbCol7 = QtGui.QSpinBox(self.gbTable1000)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCol7.sizePolicy().hasHeightForWidth())
        self.sbCol7.setSizePolicy(sizePolicy)
        self.sbCol7.setMaximum(99999)
        self.sbCol7.setObjectName(_fromUtf8("sbCol7"))
        self.gridLayout.addWidget(self.sbCol7, 6, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gbTable1000)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.sbCol8 = QtGui.QSpinBox(self.gbTable1000)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCol8.sizePolicy().hasHeightForWidth())
        self.sbCol8.setSizePolicy(sizePolicy)
        self.sbCol8.setMaximum(99999)
        self.sbCol8.setObjectName(_fromUtf8("sbCol8"))
        self.gridLayout.addWidget(self.sbCol8, 7, 1, 1, 1)
        self.gridLayout_3.addWidget(self.gbTable1000, 5, 0, 1, 3)
        self.gbTable2000 = QtGui.QGroupBox(ReportF12_D_3_MSetupDialog)
        self.gbTable2000.setObjectName(_fromUtf8("gbTable2000"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gbTable2000)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblTable2000Col3 = QtGui.QLabel(self.gbTable2000)
        self.lblTable2000Col3.setObjectName(_fromUtf8("lblTable2000Col3"))
        self.gridLayout_2.addWidget(self.lblTable2000Col3, 0, 0, 1, 1)
        self.sbTable2000Col3 = QtGui.QSpinBox(self.gbTable2000)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbTable2000Col3.sizePolicy().hasHeightForWidth())
        self.sbTable2000Col3.setSizePolicy(sizePolicy)
        self.sbTable2000Col3.setMinimumSize(QtCore.QSize(0, 0))
        self.sbTable2000Col3.setMaximum(99999)
        self.sbTable2000Col3.setObjectName(_fromUtf8("sbTable2000Col3"))
        self.gridLayout_2.addWidget(self.sbTable2000Col3, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.gbTable2000, 6, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 7, 0, 1, 3)
        self.buttonBox = QtGui.QDialogButtonBox(ReportF12_D_3_MSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 8, 0, 1, 3)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblEventType.setBuddy(self.cmbEventType)
        self.lblTotalText.setBuddy(self.sbCol3)
        self.label_2.setBuddy(self.sbCol4)
        self.label_3.setBuddy(self.sbCol5)
        self.label_5.setBuddy(self.sbCol6)
        self.label_6.setBuddy(self.sbCol7)
        self.label_7.setBuddy(self.sbCol8)

        self.retranslateUi(ReportF12_D_3_MSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportF12_D_3_MSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportF12_D_3_MSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ReportF12_D_3_MSetupDialog)
        ReportF12_D_3_MSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ReportF12_D_3_MSetupDialog.setTabOrder(self.edtEndDate, self.cmbEventType)
        ReportF12_D_3_MSetupDialog.setTabOrder(self.cmbEventType, self.chkOnlyPermanentAttach)
        ReportF12_D_3_MSetupDialog.setTabOrder(self.chkOnlyPermanentAttach, self.chkOnlyPayedEvents)
        ReportF12_D_3_MSetupDialog.setTabOrder(self.chkOnlyPayedEvents, self.sbCol3)
        ReportF12_D_3_MSetupDialog.setTabOrder(self.sbCol3, self.sbCol4)
        ReportF12_D_3_MSetupDialog.setTabOrder(self.sbCol4, self.sbCol5)
        ReportF12_D_3_MSetupDialog.setTabOrder(self.sbCol5, self.sbCol6)
        ReportF12_D_3_MSetupDialog.setTabOrder(self.sbCol6, self.sbCol7)
        ReportF12_D_3_MSetupDialog.setTabOrder(self.sbCol7, self.sbCol8)
        ReportF12_D_3_MSetupDialog.setTabOrder(self.sbCol8, self.sbTable2000Col3)
        ReportF12_D_3_MSetupDialog.setTabOrder(self.sbTable2000Col3, self.buttonBox)

    def retranslateUi(self, ReportF12_D_3_MSetupDialog):
        ReportF12_D_3_MSetupDialog.setWindowTitle(QtGui.QApplication.translate("ReportF12_D_3_MSetupDialog", "параметры отчёта", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBegDate.setText(QtGui.QApplication.translate("ReportF12_D_3_MSetupDialog", "Дата &начала периода", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndDate.setText(QtGui.QApplication.translate("ReportF12_D_3_MSetupDialog", "Дата &окончания периода", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEventType.setText(QtGui.QApplication.translate("ReportF12_D_3_MSetupDialog", "&Тип обращения", None, QtGui.QApplication.UnicodeUTF8))
        self.chkOnlyPermanentAttach.setText(QtGui.QApplication.translate("ReportF12_D_3_MSetupDialog", "&Прикреплённые к базовому ЛПУ", None, QtGui.QApplication.UnicodeUTF8))
        self.chkOnlyPayedEvents.setText(QtGui.QApplication.translate("ReportF12_D_3_MSetupDialog", "Только опла&ченные", None, QtGui.QApplication.UnicodeUTF8))
        self.gbTable1000.setTitle(QtGui.QApplication.translate("ReportF12_D_3_MSetupDialog", "Таблица 1000", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ReportF12_D_3_MSetupDialog", "Число учреждений здравоохранения, осуществляющих дополнительную диспансеризацию:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTotalText.setText(QtGui.QApplication.translate("ReportF12_D_3_MSetupDialog", "(3) Всего", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ReportF12_D_3_MSetupDialog", "(4) в полном объеме собственными силами ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ReportF12_D_3_MSetupDialog", "на договорной основе в связи с отсутствием:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ReportF12_D_3_MSetupDialog", "(5) необходимого диагностического оборудования ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ReportF12_D_3_MSetupDialog", "(6) необходимых специалистов", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ReportF12_D_3_MSetupDialog", "(7) необходимых специалистов и диагностического оборудования ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ReportF12_D_3_MSetupDialog", "(8) число организаций, прикрепленных к учреждениям здравоохранения для\n"
"прохождения дополнительной диспансеризации ", None, QtGui.QApplication.UnicodeUTF8))
        self.gbTable2000.setTitle(QtGui.QApplication.translate("ReportF12_D_3_MSetupDialog", "Таблица 2000", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTable2000Col3.setText(QtGui.QApplication.translate("ReportF12_D_3_MSetupDialog", "(3) Число граждан, подлежащих дополнительной диспасеризации", None, QtGui.QApplication.UnicodeUTF8))

from library.crbcombobox import CRBComboBox
from library.DateEdit import CDateEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ReportF12_D_3_MSetupDialog = QtGui.QDialog()
    ui = Ui_ReportF12_D_3_MSetupDialog()
    ui.setupUi(ReportF12_D_3_MSetupDialog)
    ReportF12_D_3_MSetupDialog.show()
    sys.exit(app.exec_())

