# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/shutov/s11/Reports/ReportDDStudentsInfoSetup.ui'
#
# Created: Thu Oct 18 15:44:58 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ReportDDStudentsInfoSetupDialog(object):
    def setupUi(self, ReportDDStudentsInfoSetupDialog):
        ReportDDStudentsInfoSetupDialog.setObjectName(_fromUtf8("ReportDDStudentsInfoSetupDialog"))
        ReportDDStudentsInfoSetupDialog.resize(468, 460)
        self.layoutWidget = QtGui.QWidget(ReportDDStudentsInfoSetupDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 446, 443))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.chkPodtver = QtGui.QCheckBox(self.layoutWidget)
        self.chkPodtver.setObjectName(_fromUtf8("chkPodtver"))
        self.gridLayout.addWidget(self.chkPodtver, 4, 0, 1, 3)
        self.lblEndDatePodtver = QtGui.QLabel(self.layoutWidget)
        self.lblEndDatePodtver.setEnabled(False)
        self.lblEndDatePodtver.setObjectName(_fromUtf8("lblEndDatePodtver"))
        self.gridLayout.addWidget(self.lblEndDatePodtver, 7, 0, 1, 4)
        self.edtEndDatePodtver = CDateEdit(self.layoutWidget)
        self.edtEndDatePodtver.setEnabled(False)
        self.edtEndDatePodtver.setObjectName(_fromUtf8("edtEndDatePodtver"))
        self.gridLayout.addWidget(self.edtEndDatePodtver, 7, 4, 1, 3)
        self.lblBegDatePodtver = QtGui.QLabel(self.layoutWidget)
        self.lblBegDatePodtver.setEnabled(False)
        self.lblBegDatePodtver.setObjectName(_fromUtf8("lblBegDatePodtver"))
        self.gridLayout.addWidget(self.lblBegDatePodtver, 6, 0, 1, 3)
        self.edtBegDatePodtver = CDateEdit(self.layoutWidget)
        self.edtBegDatePodtver.setEnabled(False)
        self.edtBegDatePodtver.setObjectName(_fromUtf8("edtBegDatePodtver"))
        self.gridLayout.addWidget(self.edtBegDatePodtver, 6, 4, 1, 3)
        self.lblAge = QtGui.QLabel(self.layoutWidget)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout.addWidget(self.lblAge, 3, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(self.layoutWidget)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPerson, 10, 3, 1, 4)
        self.cmbOrgStructure = COrgStructureComboBox(self.layoutWidget)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 9, 3, 1, 4)
        self.cmbRefuseType = CRBComboBox(self.layoutWidget)
        self.cmbRefuseType.setEnabled(False)
        self.cmbRefuseType.setObjectName(_fromUtf8("cmbRefuseType"))
        self.gridLayout.addWidget(self.cmbRefuseType, 8, 4, 1, 3)
        self.lblEndDate = QtGui.QLabel(self.layoutWidget)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 3)
        self.lblPerson = QtGui.QLabel(self.layoutWidget)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 10, 0, 1, 1)
        self.cmbWorkOrganisation = COrgComboBox(self.layoutWidget)
        self.cmbWorkOrganisation.setEnabled(True)
        self.cmbWorkOrganisation.setObjectName(_fromUtf8("cmbWorkOrganisation"))
        self.gridLayout.addWidget(self.cmbWorkOrganisation, 11, 3, 1, 3)
        self.lblPodtver = QtGui.QLabel(self.layoutWidget)
        self.lblPodtver.setEnabled(False)
        self.lblPodtver.setObjectName(_fromUtf8("lblPodtver"))
        self.gridLayout.addWidget(self.lblPodtver, 5, 0, 1, 1)
        self.lblSex = QtGui.QLabel(self.layoutWidget)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout.addWidget(self.lblSex, 2, 0, 1, 1)
        self.btnSelectWorkOrganisation = QtGui.QToolButton(self.layoutWidget)
        self.btnSelectWorkOrganisation.setEnabled(True)
        self.btnSelectWorkOrganisation.setObjectName(_fromUtf8("btnSelectWorkOrganisation"))
        self.gridLayout.addWidget(self.btnSelectWorkOrganisation, 11, 6, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 12, 5, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 13, 3, 1, 3)
        self.frmAge_2 = QtGui.QFrame(self.layoutWidget)
        self.frmAge_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge_2.setObjectName(_fromUtf8("frmAge_2"))
        self._2 = QtGui.QHBoxLayout(self.frmAge_2)
        self._2.setSpacing(4)
        self._2.setMargin(0)
        self._2.setObjectName(_fromUtf8("_2"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self._2.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge_2)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self._2.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self._2.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge_2)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self._2.addWidget(self.lblAgeYears)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem1)
        self.gridLayout.addWidget(self.frmAge_2, 3, 3, 1, 4)
        self.lblRefuseType = QtGui.QLabel(self.layoutWidget)
        self.lblRefuseType.setEnabled(False)
        self.lblRefuseType.setObjectName(_fromUtf8("lblRefuseType"))
        self.gridLayout.addWidget(self.lblRefuseType, 8, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(self.layoutWidget)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 2, 3, 1, 4)
        self.edtEndDate = CDateEdit(self.layoutWidget)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 3, 1, 4)
        self.edtBegDate = CDateEdit(self.layoutWidget)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 3, 1, 4)
        self.cmbPodtver = QtGui.QComboBox(self.layoutWidget)
        self.cmbPodtver.setEnabled(False)
        self.cmbPodtver.setObjectName(_fromUtf8("cmbPodtver"))
        self.gridLayout.addWidget(self.cmbPodtver, 5, 4, 1, 3)
        self.lblWorkOrganisation = QtGui.QLabel(self.layoutWidget)
        self.lblWorkOrganisation.setObjectName(_fromUtf8("lblWorkOrganisation"))
        self.gridLayout.addWidget(self.lblWorkOrganisation, 11, 0, 1, 2)
        self.lblBegDate = QtGui.QLabel(self.layoutWidget)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 3)
        self.lblOrgStructure = QtGui.QLabel(self.layoutWidget)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 9, 0, 1, 3)
        self.lblEndDatePodtver.setBuddy(self.edtEndDatePodtver)
        self.lblBegDatePodtver.setBuddy(self.edtBegDatePodtver)
        self.lblAge.setBuddy(self.edtAgeFrom)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblPodtver.setBuddy(self.cmbPodtver)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblRefuseType.setBuddy(self.cmbRefuseType)
        self.lblWorkOrganisation.setBuddy(self.cmbWorkOrganisation)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)

        self.retranslateUi(ReportDDStudentsInfoSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportDDStudentsInfoSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportDDStudentsInfoSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ReportDDStudentsInfoSetupDialog)
        ReportDDStudentsInfoSetupDialog.setTabOrder(self.buttonBox, self.edtBegDate)
        ReportDDStudentsInfoSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ReportDDStudentsInfoSetupDialog.setTabOrder(self.edtEndDate, self.cmbSex)
        ReportDDStudentsInfoSetupDialog.setTabOrder(self.cmbSex, self.edtAgeFrom)
        ReportDDStudentsInfoSetupDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        ReportDDStudentsInfoSetupDialog.setTabOrder(self.edtAgeTo, self.chkPodtver)
        ReportDDStudentsInfoSetupDialog.setTabOrder(self.chkPodtver, self.cmbPodtver)
        ReportDDStudentsInfoSetupDialog.setTabOrder(self.cmbPodtver, self.edtBegDatePodtver)
        ReportDDStudentsInfoSetupDialog.setTabOrder(self.edtBegDatePodtver, self.edtEndDatePodtver)
        ReportDDStudentsInfoSetupDialog.setTabOrder(self.edtEndDatePodtver, self.cmbRefuseType)
        ReportDDStudentsInfoSetupDialog.setTabOrder(self.cmbRefuseType, self.cmbOrgStructure)
        ReportDDStudentsInfoSetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbPerson)
        ReportDDStudentsInfoSetupDialog.setTabOrder(self.cmbPerson, self.cmbWorkOrganisation)
        ReportDDStudentsInfoSetupDialog.setTabOrder(self.cmbWorkOrganisation, self.btnSelectWorkOrganisation)

    def retranslateUi(self, ReportDDStudentsInfoSetupDialog):
        ReportDDStudentsInfoSetupDialog.setWindowTitle(QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPodtver.setText(QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "Подтверждение оп&латы", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndDatePodtver.setText(QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "Окончание периода подтверждени&я:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBegDatePodtver.setText(QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "Начало пер&иода подтверждения:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAge.setText(QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "Возраст с", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPerson.setItemText(0, QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "Врач", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndDate.setText(QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "Дата окончания периода", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPerson.setText(QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "&Врач", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPodtver.setText(QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "Тип подтве&рждения:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSex.setText(QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "Пол", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelectWorkOrganisation.setText(QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAgeTo.setText(QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "по", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAgeYears.setText(QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "лет", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRefuseType.setText(QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "При&чина отказа:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSex.setItemText(1, QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "М", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSex.setItemText(2, QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "Ж", None, QtGui.QApplication.UnicodeUTF8))
        self.lblWorkOrganisation.setText(QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "Учебное заведение", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBegDate.setText(QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "Дата начала периода", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOrgStructure.setText(QtGui.QApplication.translate("ReportDDStudentsInfoSetupDialog", "&Подразделение", None, QtGui.QApplication.UnicodeUTF8))

from Orgs.OrgComboBox import COrgComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.crbcombobox import CRBComboBox
from library.DateEdit import CDateEdit
from Orgs.OrgStructComboBoxes import COrgStructureComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ReportDDStudentsInfoSetupDialog = QtGui.QDialog()
    ui = Ui_ReportDDStudentsInfoSetupDialog()
    ui.setupUi(ReportDDStudentsInfoSetupDialog)
    ReportDDStudentsInfoSetupDialog.show()
    sys.exit(app.exec_())

