# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReportAcuteInfectionsSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportAcuteInfectionsSetupDialog(object):
    def setupUi(self, ReportAcuteInfectionsSetupDialog):
        ReportAcuteInfectionsSetupDialog.setObjectName(_fromUtf8("ReportAcuteInfectionsSetupDialog"))
        ReportAcuteInfectionsSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ReportAcuteInfectionsSetupDialog.resize(884, 866)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ReportAcuteInfectionsSetupDialog.sizePolicy().hasHeightForWidth())
        ReportAcuteInfectionsSetupDialog.setSizePolicy(sizePolicy)
        ReportAcuteInfectionsSetupDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(ReportAcuteInfectionsSetupDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblSex = QtGui.QLabel(ReportAcuteInfectionsSetupDialog)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.horizontalLayout_4.addWidget(self.lblSex)
        self.cmbSex = QtGui.QComboBox(ReportAcuteInfectionsSetupDialog)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.cmbSex)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_4, 11, 3, 1, 2)
        self.cmbPerson = CPersonComboBoxEx(ReportAcuteInfectionsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPerson.sizePolicy().hasHeightForWidth())
        self.cmbPerson.setSizePolicy(sizePolicy)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPerson, 7, 1, 1, 2)
        self.lblEventType = QtGui.QLabel(ReportAcuteInfectionsSetupDialog)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridLayout.addWidget(self.lblEventType, 7, 3, 1, 1)
        self.lblTemplate = QtGui.QLabel(ReportAcuteInfectionsSetupDialog)
        self.lblTemplate.setObjectName(_fromUtf8("lblTemplate"))
        self.gridLayout.addWidget(self.lblTemplate, 1, 3, 1, 1)
        self.cmbCategory = QtGui.QComboBox(ReportAcuteInfectionsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCategory.sizePolicy().hasHeightForWidth())
        self.cmbCategory.setSizePolicy(sizePolicy)
        self.cmbCategory.setObjectName(_fromUtf8("cmbCategory"))
        self.cmbCategory.addItem(_fromUtf8(""))
        self.cmbCategory.addItem(_fromUtf8(""))
        self.cmbCategory.addItem(_fromUtf8(""))
        self.cmbCategory.addItem(_fromUtf8(""))
        self.cmbCategory.addItem(_fromUtf8(""))
        self.cmbCategory.addItem(_fromUtf8(""))
        self.cmbCategory.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbCategory, 1, 1, 1, 2)
        self.frmAge = QtGui.QFrame(ReportAcuteInfectionsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAge.sizePolicy().hasHeightForWidth())
        self.frmAge.setSizePolicy(sizePolicy)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self.hboxlayout = QtGui.QHBoxLayout(self.frmAge)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.label = QtGui.QLabel(self.frmAge)
        self.label.setObjectName(_fromUtf8("label"))
        self.hboxlayout.addWidget(self.label)
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self.hboxlayout.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self.hboxlayout.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self.hboxlayout.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self.hboxlayout.addWidget(self.lblAgeYears)
        self.chkOnlyChilds = QtGui.QCheckBox(self.frmAge)
        self.chkOnlyChilds.setObjectName(_fromUtf8("chkOnlyChilds"))
        self.hboxlayout.addWidget(self.chkOnlyChilds)
        self.gridLayout.addWidget(self.frmAge, 11, 0, 1, 3)
        self.cmbTemplate = QtGui.QComboBox(ReportAcuteInfectionsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTemplate.sizePolicy().hasHeightForWidth())
        self.cmbTemplate.setSizePolicy(sizePolicy)
        self.cmbTemplate.setObjectName(_fromUtf8("cmbTemplate"))
        self.cmbTemplate.addItem(_fromUtf8(""))
        self.cmbTemplate.addItem(_fromUtf8(""))
        self.cmbTemplate.addItem(_fromUtf8(""))
        self.cmbTemplate.addItem(_fromUtf8(""))
        self.cmbTemplate.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbTemplate, 1, 4, 1, 1)
        self.cmbEventType = CRBComboBox(ReportAcuteInfectionsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEventType.sizePolicy().hasHeightForWidth())
        self.cmbEventType.setSizePolicy(sizePolicy)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout.addWidget(self.cmbEventType, 7, 4, 1, 1)
        self.lblLocality = QtGui.QLabel(ReportAcuteInfectionsSetupDialog)
        self.lblLocality.setObjectName(_fromUtf8("lblLocality"))
        self.gridLayout.addWidget(self.lblLocality, 18, 0, 1, 1)
        self.chkVisitEmergency = QtGui.QCheckBox(ReportAcuteInfectionsSetupDialog)
        self.chkVisitEmergency.setObjectName(_fromUtf8("chkVisitEmergency"))
        self.gridLayout.addWidget(self.chkVisitEmergency, 17, 0, 1, 3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblSocStatusClass = QtGui.QLabel(ReportAcuteInfectionsSetupDialog)
        self.lblSocStatusClass.setObjectName(_fromUtf8("lblSocStatusClass"))
        self.horizontalLayout_3.addWidget(self.lblSocStatusClass)
        self.cmbSocStatusClass = CSocStatusComboBox(ReportAcuteInfectionsSetupDialog)
        self.cmbSocStatusClass.setObjectName(_fromUtf8("cmbSocStatusClass"))
        self.horizontalLayout_3.addWidget(self.cmbSocStatusClass)
        self.gridLayout.addLayout(self.horizontalLayout_3, 15, 0, 1, 3)
        self.chkArea = QtGui.QCheckBox(ReportAcuteInfectionsSetupDialog)
        self.chkArea.setObjectName(_fromUtf8("chkArea"))
        self.gridLayout.addWidget(self.chkArea, 19, 0, 1, 2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblSocStatusType = QtGui.QLabel(ReportAcuteInfectionsSetupDialog)
        self.lblSocStatusType.setObjectName(_fromUtf8("lblSocStatusType"))
        self.horizontalLayout_2.addWidget(self.lblSocStatusType)
        self.cmbSocStatusType = CRBComboBox(ReportAcuteInfectionsSetupDialog)
        self.cmbSocStatusType.setObjectName(_fromUtf8("cmbSocStatusType"))
        self.horizontalLayout_2.addWidget(self.cmbSocStatusType)
        self.gridLayout.addLayout(self.horizontalLayout_2, 15, 3, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(ReportAcuteInfectionsSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 23, 0, 1, 5)
        self.lblHurt = QtGui.QLabel(ReportAcuteInfectionsSetupDialog)
        self.lblHurt.setObjectName(_fromUtf8("lblHurt"))
        self.gridLayout.addWidget(self.lblHurt, 5, 3, 1, 1)
        self.cmbSpecialityPerson = CRBComboBox(ReportAcuteInfectionsSetupDialog)
        self.cmbSpecialityPerson.setObjectName(_fromUtf8("cmbSpecialityPerson"))
        self.gridLayout.addWidget(self.cmbSpecialityPerson, 6, 4, 1, 1)
        self.cmbEventPurpose = CRBMultiComboBox(ReportAcuteInfectionsSetupDialog)
        self.cmbEventPurpose.setObjectName(_fromUtf8("cmbEventPurpose"))
        self.gridLayout.addWidget(self.cmbEventPurpose, 5, 1, 1, 2)
        self.cmbArea = COrgStructureComboBox(ReportAcuteInfectionsSetupDialog)
        self.cmbArea.setEnabled(False)
        self.cmbArea.setObjectName(_fromUtf8("cmbArea"))
        self.gridLayout.addWidget(self.cmbArea, 19, 3, 1, 2)
        self.lblOrgStructure = QtGui.QLabel(ReportAcuteInfectionsSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 6, 0, 1, 1)
        self.lblEventPurpose = QtGui.QLabel(ReportAcuteInfectionsSetupDialog)
        self.lblEventPurpose.setObjectName(_fromUtf8("lblEventPurpose"))
        self.gridLayout.addWidget(self.lblEventPurpose, 5, 0, 1, 1)
        self.cmbLocality = QtGui.QComboBox(ReportAcuteInfectionsSetupDialog)
        self.cmbLocality.setObjectName(_fromUtf8("cmbLocality"))
        self.cmbLocality.addItem(_fromUtf8(""))
        self.cmbLocality.addItem(_fromUtf8(""))
        self.cmbLocality.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbLocality, 18, 1, 1, 2)
        self.lblPerson = QtGui.QLabel(ReportAcuteInfectionsSetupDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 7, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 22, 2, 1, 1)
        self.cmbHurt = CRBComboBox(ReportAcuteInfectionsSetupDialog)
        self.cmbHurt.setObjectName(_fromUtf8("cmbHurt"))
        self.gridLayout.addWidget(self.cmbHurt, 5, 4, 1, 1)
        self.chkOnlyPermanentAttach = QtGui.QCheckBox(ReportAcuteInfectionsSetupDialog)
        self.chkOnlyPermanentAttach.setObjectName(_fromUtf8("chkOnlyPermanentAttach"))
        self.gridLayout.addWidget(self.chkOnlyPermanentAttach, 17, 3, 1, 2)
        self.cmbOrgStructure = COrgStructureComboBox(ReportAcuteInfectionsSetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 6, 1, 1, 2)
        self.lblSpecialityPerson = QtGui.QLabel(ReportAcuteInfectionsSetupDialog)
        self.lblSpecialityPerson.setObjectName(_fromUtf8("lblSpecialityPerson"))
        self.gridLayout.addWidget(self.lblSpecialityPerson, 6, 3, 1, 1)
        self.lblCategory = QtGui.QLabel(ReportAcuteInfectionsSetupDialog)
        self.lblCategory.setObjectName(_fromUtf8("lblCategory"))
        self.gridLayout.addWidget(self.lblCategory, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(ReportAcuteInfectionsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frmMKBEx = QtGui.QFrame(self.groupBox)
        self.frmMKBEx.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMKBEx.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMKBEx.setObjectName(_fromUtf8("frmMKBEx"))
        self._2 = QtGui.QGridLayout(self.frmMKBEx)
        self._2.setMargin(0)
        self._2.setHorizontalSpacing(4)
        self._2.setVerticalSpacing(0)
        self._2.setObjectName(_fromUtf8("_2"))
        self.cmbMKBExFilter = QtGui.QComboBox(self.frmMKBEx)
        self.cmbMKBExFilter.setObjectName(_fromUtf8("cmbMKBExFilter"))
        self.cmbMKBExFilter.addItem(_fromUtf8(""))
        self.cmbMKBExFilter.addItem(_fromUtf8(""))
        self._2.addWidget(self.cmbMKBExFilter, 1, 4, 1, 1)
        self.edtMKBExFrom = CICDCodeEdit(self.frmMKBEx)
        self.edtMKBExFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBExFrom.sizePolicy().hasHeightForWidth())
        self.edtMKBExFrom.setSizePolicy(sizePolicy)
        self.edtMKBExFrom.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBExFrom.setMaxLength(6)
        self.edtMKBExFrom.setObjectName(_fromUtf8("edtMKBExFrom"))
        self._2.addWidget(self.edtMKBExFrom, 1, 5, 1, 1)
        self.edtMKBExTo = CICDCodeEdit(self.frmMKBEx)
        self.edtMKBExTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBExTo.sizePolicy().hasHeightForWidth())
        self.edtMKBExTo.setSizePolicy(sizePolicy)
        self.edtMKBExTo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBExTo.setMaxLength(6)
        self.edtMKBExTo.setObjectName(_fromUtf8("edtMKBExTo"))
        self._2.addWidget(self.edtMKBExTo, 1, 6, 1, 1)
        self.lblMKBEx = QtGui.QLabel(self.frmMKBEx)
        self.lblMKBEx.setObjectName(_fromUtf8("lblMKBEx"))
        self._2.addWidget(self.lblMKBEx, 1, 3, 1, 1)
        self.gridLayout_3.addWidget(self.frmMKBEx, 0, 3, 1, 1)
        self.frmMKB = QtGui.QFrame(self.groupBox)
        self.frmMKB.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMKB.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMKB.setObjectName(_fromUtf8("frmMKB"))
        self.gridlayout = QtGui.QGridLayout(self.frmMKB)
        self.gridlayout.setMargin(0)
        self.gridlayout.setHorizontalSpacing(4)
        self.gridlayout.setVerticalSpacing(0)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.lblMKB = QtGui.QLabel(self.frmMKB)
        self.lblMKB.setObjectName(_fromUtf8("lblMKB"))
        self.gridlayout.addWidget(self.lblMKB, 0, 0, 1, 1)
        self.edtMKBFrom = CICDCodeEdit(self.frmMKB)
        self.edtMKBFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBFrom.sizePolicy().hasHeightForWidth())
        self.edtMKBFrom.setSizePolicy(sizePolicy)
        self.edtMKBFrom.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBFrom.setMaxLength(6)
        self.edtMKBFrom.setObjectName(_fromUtf8("edtMKBFrom"))
        self.gridlayout.addWidget(self.edtMKBFrom, 0, 2, 1, 1)
        self.edtMKBTo = CICDCodeEdit(self.frmMKB)
        self.edtMKBTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBTo.sizePolicy().hasHeightForWidth())
        self.edtMKBTo.setSizePolicy(sizePolicy)
        self.edtMKBTo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBTo.setMaxLength(6)
        self.edtMKBTo.setObjectName(_fromUtf8("edtMKBTo"))
        self.gridlayout.addWidget(self.edtMKBTo, 0, 3, 1, 1)
        self.cmbMKBFilter = QtGui.QComboBox(self.frmMKB)
        self.cmbMKBFilter.setObjectName(_fromUtf8("cmbMKBFilter"))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbMKBFilter, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frmMKB, 0, 0, 1, 3)
        self.cmbIsPrimary = QtGui.QComboBox(self.groupBox)
        self.cmbIsPrimary.setObjectName(_fromUtf8("cmbIsPrimary"))
        self.cmbIsPrimary.addItem(_fromUtf8(""))
        self.cmbIsPrimary.setItemText(0, _fromUtf8(""))
        self.cmbIsPrimary.addItem(_fromUtf8(""))
        self.cmbIsPrimary.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbIsPrimary, 2, 1, 1, 1)
        self.chkNotNullTraumaType = QtGui.QCheckBox(self.groupBox)
        self.chkNotNullTraumaType.setObjectName(_fromUtf8("chkNotNullTraumaType"))
        self.gridLayout_3.addWidget(self.chkNotNullTraumaType, 4, 3, 1, 1)
        self.lblIsPrimary = QtGui.QLabel(self.groupBox)
        self.lblIsPrimary.setObjectName(_fromUtf8("lblIsPrimary"))
        self.gridLayout_3.addWidget(self.lblIsPrimary, 2, 0, 1, 1)
        self.chkOnlyFirstTime = QtGui.QCheckBox(self.groupBox)
        self.chkOnlyFirstTime.setObjectName(_fromUtf8("chkOnlyFirstTime"))
        self.gridLayout_3.addWidget(self.chkOnlyFirstTime, 4, 0, 1, 1)
        self.chkRegisteredInPeriod = QtGui.QCheckBox(self.groupBox)
        self.chkRegisteredInPeriod.setObjectName(_fromUtf8("chkRegisteredInPeriod"))
        self.gridLayout_3.addWidget(self.chkRegisteredInPeriod, 3, 0, 1, 1)
        self.chkNotConsiderDigitsAfterDot = QtGui.QCheckBox(self.groupBox)
        self.chkNotConsiderDigitsAfterDot.setObjectName(_fromUtf8("chkNotConsiderDigitsAfterDot"))
        self.gridLayout_3.addWidget(self.chkNotConsiderDigitsAfterDot, 2, 3, 1, 1)
        self.chkAccountAccomp = QtGui.QCheckBox(self.groupBox)
        self.chkAccountAccomp.setObjectName(_fromUtf8("chkAccountAccomp"))
        self.gridLayout_3.addWidget(self.chkAccountAccomp, 3, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 14, 0, 1, 5)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.edtBegDate = CDateEdit(ReportAcuteInfectionsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout_4.addWidget(self.edtBegDate, 0, 2, 1, 1)
        self.edtEndDate = CDateEdit(ReportAcuteInfectionsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout_4.addWidget(self.edtEndDate, 0, 4, 1, 1)
        self.label_4 = QtGui.QLabel(ReportAcuteInfectionsSetupDialog)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 0, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 3, 1, 1, 2)
        self.label_2 = QtGui.QLabel(ReportAcuteInfectionsSetupDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.chkCreateDate = QtGui.QCheckBox(ReportAcuteInfectionsSetupDialog)
        self.chkCreateDate.setObjectName(_fromUtf8("chkCreateDate"))
        self.gridLayout.addWidget(self.chkCreateDate, 3, 3, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.edtCreateBegDate = CDateEdit(ReportAcuteInfectionsSetupDialog)
        self.edtCreateBegDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtCreateBegDate.sizePolicy().hasHeightForWidth())
        self.edtCreateBegDate.setSizePolicy(sizePolicy)
        self.edtCreateBegDate.setCalendarPopup(True)
        self.edtCreateBegDate.setObjectName(_fromUtf8("edtCreateBegDate"))
        self.gridLayout_5.addWidget(self.edtCreateBegDate, 1, 2, 1, 1)
        self.edtCreateEndDate = CDateEdit(ReportAcuteInfectionsSetupDialog)
        self.edtCreateEndDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtCreateEndDate.sizePolicy().hasHeightForWidth())
        self.edtCreateEndDate.setSizePolicy(sizePolicy)
        self.edtCreateEndDate.setCalendarPopup(True)
        self.edtCreateEndDate.setObjectName(_fromUtf8("edtCreateEndDate"))
        self.gridLayout_5.addWidget(self.edtCreateEndDate, 1, 4, 1, 1)
        self.lblCreateDate = QtGui.QLabel(ReportAcuteInfectionsSetupDialog)
        self.lblCreateDate.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCreateDate.setObjectName(_fromUtf8("lblCreateDate"))
        self.gridLayout_5.addWidget(self.lblCreateDate, 1, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 3, 4, 1, 1)
        self.gbFilterAddress = QtGui.QGroupBox(ReportAcuteInfectionsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbFilterAddress.sizePolicy().hasHeightForWidth())
        self.gbFilterAddress.setSizePolicy(sizePolicy)
        self.gbFilterAddress.setCheckable(True)
        self.gbFilterAddress.setChecked(True)
        self.gbFilterAddress.setObjectName(_fromUtf8("gbFilterAddress"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gbFilterAddress)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lblFilterAddressHouse = QtGui.QLabel(self.gbFilterAddress)
        self.lblFilterAddressHouse.setEnabled(False)
        self.lblFilterAddressHouse.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblFilterAddressHouse.setObjectName(_fromUtf8("lblFilterAddressHouse"))
        self.horizontalLayout_6.addWidget(self.lblFilterAddressHouse)
        self.edtFilterAddressHouse = QtGui.QLineEdit(self.gbFilterAddress)
        self.edtFilterAddressHouse.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterAddressHouse.sizePolicy().hasHeightForWidth())
        self.edtFilterAddressHouse.setSizePolicy(sizePolicy)
        self.edtFilterAddressHouse.setObjectName(_fromUtf8("edtFilterAddressHouse"))
        self.horizontalLayout_6.addWidget(self.edtFilterAddressHouse)
        self.lblFilterAddressCorpus = QtGui.QLabel(self.gbFilterAddress)
        self.lblFilterAddressCorpus.setEnabled(False)
        self.lblFilterAddressCorpus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFilterAddressCorpus.setObjectName(_fromUtf8("lblFilterAddressCorpus"))
        self.horizontalLayout_6.addWidget(self.lblFilterAddressCorpus)
        self.edtFilterAddressCorpus = QtGui.QLineEdit(self.gbFilterAddress)
        self.edtFilterAddressCorpus.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterAddressCorpus.sizePolicy().hasHeightForWidth())
        self.edtFilterAddressCorpus.setSizePolicy(sizePolicy)
        self.edtFilterAddressCorpus.setObjectName(_fromUtf8("edtFilterAddressCorpus"))
        self.horizontalLayout_6.addWidget(self.edtFilterAddressCorpus)
        self.lblFilterAddressFlat = QtGui.QLabel(self.gbFilterAddress)
        self.lblFilterAddressFlat.setEnabled(False)
        self.lblFilterAddressFlat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFilterAddressFlat.setObjectName(_fromUtf8("lblFilterAddressFlat"))
        self.horizontalLayout_6.addWidget(self.lblFilterAddressFlat)
        self.edtFilterAddressFlat = QtGui.QLineEdit(self.gbFilterAddress)
        self.edtFilterAddressFlat.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterAddressFlat.sizePolicy().hasHeightForWidth())
        self.edtFilterAddressFlat.setSizePolicy(sizePolicy)
        self.edtFilterAddressFlat.setObjectName(_fromUtf8("edtFilterAddressFlat"))
        self.horizontalLayout_6.addWidget(self.edtFilterAddressFlat)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.cmbFilterAddressStreet = CStreetComboBox(self.gbFilterAddress)
        self.cmbFilterAddressStreet.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressStreet.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressStreet.setSizePolicy(sizePolicy)
        self.cmbFilterAddressStreet.setEditable(True)
        self.cmbFilterAddressStreet.setObjectName(_fromUtf8("cmbFilterAddressStreet"))
        self.gridLayout_2.addWidget(self.cmbFilterAddressStreet, 2, 0, 1, 1)
        self.cmbFilterAddressCity = CKLADRComboBox(self.gbFilterAddress)
        self.cmbFilterAddressCity.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressCity.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressCity.setSizePolicy(sizePolicy)
        self.cmbFilterAddressCity.setEditable(True)
        self.cmbFilterAddressCity.setObjectName(_fromUtf8("cmbFilterAddressCity"))
        self.gridLayout_2.addWidget(self.cmbFilterAddressCity, 1, 0, 1, 1)
        self.cmbFilterAddressType = QtGui.QComboBox(self.gbFilterAddress)
        self.cmbFilterAddressType.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressType.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressType.setSizePolicy(sizePolicy)
        self.cmbFilterAddressType.setEditable(True)
        self.cmbFilterAddressType.setObjectName(_fromUtf8("cmbFilterAddressType"))
        self.cmbFilterAddressType.addItem(_fromUtf8(""))
        self.cmbFilterAddressType.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbFilterAddressType, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gbFilterAddress, 21, 0, 1, 5)
        self.frmAge_2 = QtGui.QFrame(ReportAcuteInfectionsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAge_2.sizePolicy().hasHeightForWidth())
        self.frmAge_2.setSizePolicy(sizePolicy)
        self.frmAge_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge_2.setObjectName(_fromUtf8("frmAge_2"))
        self._8 = QtGui.QHBoxLayout(self.frmAge_2)
        self._8.setMargin(0)
        self._8.setSpacing(4)
        self._8.setObjectName(_fromUtf8("_8"))
        self.chkBirthYear = QtGui.QCheckBox(self.frmAge_2)
        self.chkBirthYear.setObjectName(_fromUtf8("chkBirthYear"))
        self._8.addWidget(self.chkBirthYear)
        self.edtBegBirthYear = QtGui.QSpinBox(self.frmAge_2)
        self.edtBegBirthYear.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegBirthYear.sizePolicy().hasHeightForWidth())
        self.edtBegBirthYear.setSizePolicy(sizePolicy)
        self.edtBegBirthYear.setMinimum(1900)
        self.edtBegBirthYear.setMaximum(2100)
        self.edtBegBirthYear.setObjectName(_fromUtf8("edtBegBirthYear"))
        self._8.addWidget(self.edtBegBirthYear)
        self.lblAgeTo_3 = QtGui.QLabel(self.frmAge_2)
        self.lblAgeTo_3.setObjectName(_fromUtf8("lblAgeTo_3"))
        self._8.addWidget(self.lblAgeTo_3)
        self.edtEndBirthYear = QtGui.QSpinBox(self.frmAge_2)
        self.edtEndBirthYear.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndBirthYear.sizePolicy().hasHeightForWidth())
        self.edtEndBirthYear.setSizePolicy(sizePolicy)
        self.edtEndBirthYear.setMinimum(1900)
        self.edtEndBirthYear.setMaximum(2100)
        self.edtEndBirthYear.setObjectName(_fromUtf8("edtEndBirthYear"))
        self._8.addWidget(self.edtEndBirthYear)
        self.lblAgeYears_3 = QtGui.QLabel(self.frmAge_2)
        self.lblAgeYears_3.setObjectName(_fromUtf8("lblAgeYears_3"))
        self._8.addWidget(self.lblAgeYears_3)
        self.gridLayout.addWidget(self.frmAge_2, 12, 0, 1, 3)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblEventType.setBuddy(self.cmbEventType)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblLocality.setBuddy(self.cmbLocality)
        self.lblSocStatusClass.setBuddy(self.cmbSocStatusClass)
        self.lblSocStatusType.setBuddy(self.cmbSocStatusType)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblEventPurpose.setBuddy(self.cmbEventPurpose)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblMKBEx.setBuddy(self.cmbMKBExFilter)
        self.lblMKB.setBuddy(self.cmbMKBFilter)
        self.lblFilterAddressHouse.setBuddy(self.edtFilterAddressHouse)
        self.lblFilterAddressCorpus.setBuddy(self.edtFilterAddressCorpus)
        self.lblFilterAddressFlat.setBuddy(self.edtFilterAddressFlat)

        self.retranslateUi(ReportAcuteInfectionsSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportAcuteInfectionsSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportAcuteInfectionsSetupDialog.reject)
        QtCore.QObject.connect(self.chkArea, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbArea.setEnabled)
        QtCore.QObject.connect(self.chkCreateDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtCreateBegDate.setEnabled)
        QtCore.QObject.connect(self.chkCreateDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtCreateEndDate.setEnabled)
        QtCore.QObject.connect(self.chkBirthYear, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegBirthYear.setEnabled)
        QtCore.QObject.connect(self.chkBirthYear, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndBirthYear.setEnabled)
        QtCore.QObject.connect(self.chkBirthYear, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtAgeTo.setDisabled)
        QtCore.QObject.connect(self.chkBirthYear, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtAgeFrom.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(ReportAcuteInfectionsSetupDialog)
        ReportAcuteInfectionsSetupDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        ReportAcuteInfectionsSetupDialog.setTabOrder(self.edtAgeTo, self.cmbSocStatusClass)
        ReportAcuteInfectionsSetupDialog.setTabOrder(self.cmbSocStatusClass, self.edtFilterAddressHouse)
        ReportAcuteInfectionsSetupDialog.setTabOrder(self.edtFilterAddressHouse, self.edtFilterAddressCorpus)
        ReportAcuteInfectionsSetupDialog.setTabOrder(self.edtFilterAddressCorpus, self.edtFilterAddressFlat)

    def retranslateUi(self, ReportAcuteInfectionsSetupDialog):
        ReportAcuteInfectionsSetupDialog.setWindowTitle(_translate("ReportAcuteInfectionsSetupDialog", "параметры отчёта", None))
        self.lblSex.setText(_translate("ReportAcuteInfectionsSetupDialog", "По&л", None))
        self.cmbSex.setItemText(1, _translate("ReportAcuteInfectionsSetupDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("ReportAcuteInfectionsSetupDialog", "Ж", None))
        self.cmbPerson.setItemText(0, _translate("ReportAcuteInfectionsSetupDialog", "Врач", None))
        self.lblEventType.setText(_translate("ReportAcuteInfectionsSetupDialog", "&Тип обращения", None))
        self.lblTemplate.setText(_translate("ReportAcuteInfectionsSetupDialog", "Образец:", None))
        self.cmbCategory.setItemText(0, _translate("ReportAcuteInfectionsSetupDialog", "Дети", None))
        self.cmbCategory.setItemText(1, _translate("ReportAcuteInfectionsSetupDialog", "Дети до 1 года", None))
        self.cmbCategory.setItemText(2, _translate("ReportAcuteInfectionsSetupDialog", "Подростки", None))
        self.cmbCategory.setItemText(3, _translate("ReportAcuteInfectionsSetupDialog", "Взрослые", None))
        self.cmbCategory.setItemText(4, _translate("ReportAcuteInfectionsSetupDialog", "Пожилые", None))
        self.cmbCategory.setItemText(5, _translate("ReportAcuteInfectionsSetupDialog", "Вкладыш-2008", None))
        self.cmbCategory.setItemText(6, _translate("ReportAcuteInfectionsSetupDialog", "Взрослые 4000", None))
        self.label.setText(_translate("ReportAcuteInfectionsSetupDialog", "Возраст с", None))
        self.lblAgeTo.setText(_translate("ReportAcuteInfectionsSetupDialog", "по", None))
        self.lblAgeYears.setText(_translate("ReportAcuteInfectionsSetupDialog", "лет", None))
        self.chkOnlyChilds.setText(_translate("ReportAcuteInfectionsSetupDialog", "Только дети", None))
        self.cmbTemplate.setItemText(0, _translate("ReportAcuteInfectionsSetupDialog", "Старый", None))
        self.cmbTemplate.setItemText(1, _translate("ReportAcuteInfectionsSetupDialog", "2013 года", None))
        self.cmbTemplate.setItemText(2, _translate("ReportAcuteInfectionsSetupDialog", "2014 года", None))
        self.cmbTemplate.setItemText(3, _translate("ReportAcuteInfectionsSetupDialog", "2015 года", None))
        self.cmbTemplate.setItemText(4, _translate("ReportAcuteInfectionsSetupDialog", "2016 года", None))
        self.lblLocality.setText(_translate("ReportAcuteInfectionsSetupDialog", "Местность", None))
        self.chkVisitEmergency.setText(_translate("ReportAcuteInfectionsSetupDialog", "Учитывать посещения СМП", None))
        self.lblSocStatusClass.setText(_translate("ReportAcuteInfectionsSetupDialog", "Класс соц.статуса", None))
        self.chkArea.setText(_translate("ReportAcuteInfectionsSetupDialog", "Учитывать территорию подразделения:", None))
        self.lblSocStatusType.setText(_translate("ReportAcuteInfectionsSetupDialog", "Тип соц.статуса", None))
        self.lblHurt.setText(_translate("ReportAcuteInfectionsSetupDialog", "Тип вредности", None))
        self.lblOrgStructure.setText(_translate("ReportAcuteInfectionsSetupDialog", "&Подразделение", None))
        self.lblEventPurpose.setText(_translate("ReportAcuteInfectionsSetupDialog", "&Назначение обращения", None))
        self.cmbLocality.setItemText(0, _translate("ReportAcuteInfectionsSetupDialog", "Не учитывать", None))
        self.cmbLocality.setItemText(1, _translate("ReportAcuteInfectionsSetupDialog", "Городские жители", None))
        self.cmbLocality.setItemText(2, _translate("ReportAcuteInfectionsSetupDialog", "Сельские жители", None))
        self.lblPerson.setText(_translate("ReportAcuteInfectionsSetupDialog", "&Врач", None))
        self.chkOnlyPermanentAttach.setText(_translate("ReportAcuteInfectionsSetupDialog", "Учитывать только прикрепленных к ЛПУ", None))
        self.lblSpecialityPerson.setText(_translate("ReportAcuteInfectionsSetupDialog", "Тип специальности врача", None))
        self.lblCategory.setText(_translate("ReportAcuteInfectionsSetupDialog", "Категория:", None))
        self.groupBox.setTitle(_translate("ReportAcuteInfectionsSetupDialog", "Диагнозы", None))
        self.cmbMKBExFilter.setItemText(0, _translate("ReportAcuteInfectionsSetupDialog", "Игнор.", None))
        self.cmbMKBExFilter.setItemText(1, _translate("ReportAcuteInfectionsSetupDialog", "Интервал", None))
        self.edtMKBExFrom.setInputMask(_translate("ReportAcuteInfectionsSetupDialog", "a00.00; ", None))
        self.edtMKBExFrom.setText(_translate("ReportAcuteInfectionsSetupDialog", "A.", None))
        self.edtMKBExTo.setInputMask(_translate("ReportAcuteInfectionsSetupDialog", "a00.00; ", None))
        self.edtMKBExTo.setText(_translate("ReportAcuteInfectionsSetupDialog", "Z99.9", None))
        self.lblMKBEx.setText(_translate("ReportAcuteInfectionsSetupDialog", "В сочетании с", None))
        self.lblMKB.setText(_translate("ReportAcuteInfectionsSetupDialog", "Коды диагнозов по &МКБ", None))
        self.edtMKBFrom.setInputMask(_translate("ReportAcuteInfectionsSetupDialog", "a00.00; ", None))
        self.edtMKBFrom.setText(_translate("ReportAcuteInfectionsSetupDialog", "A.", None))
        self.edtMKBTo.setInputMask(_translate("ReportAcuteInfectionsSetupDialog", "a00.00; ", None))
        self.edtMKBTo.setText(_translate("ReportAcuteInfectionsSetupDialog", "Z99.9", None))
        self.cmbMKBFilter.setItemText(0, _translate("ReportAcuteInfectionsSetupDialog", "Игнор.", None))
        self.cmbMKBFilter.setItemText(1, _translate("ReportAcuteInfectionsSetupDialog", "Интервал", None))
        self.cmbIsPrimary.setItemText(1, _translate("ReportAcuteInfectionsSetupDialog", "Первичный", None))
        self.cmbIsPrimary.setItemText(2, _translate("ReportAcuteInfectionsSetupDialog", "Повторный", None))
        self.chkNotNullTraumaType.setText(_translate("ReportAcuteInfectionsSetupDialog", "Тип травмы указан", None))
        self.lblIsPrimary.setText(_translate("ReportAcuteInfectionsSetupDialog", "Признак первичности", None))
        self.chkOnlyFirstTime.setToolTip(_translate("ReportAcuteInfectionsSetupDialog", "Значение может отличаться от значения \"впервые\" ф.12", None))
        self.chkOnlyFirstTime.setText(_translate("ReportAcuteInfectionsSetupDialog", "Зарегистрированные в период впервые", None))
        self.chkRegisteredInPeriod.setText(_translate("ReportAcuteInfectionsSetupDialog", "Зарегистрированные в период", None))
        self.chkNotConsiderDigitsAfterDot.setText(_translate("ReportAcuteInfectionsSetupDialog", "Не учитывать знаки после точки в МКБ", None))
        self.chkAccountAccomp.setText(_translate("ReportAcuteInfectionsSetupDialog", "Учитывать сопутствующие", None))
        self.label_4.setText(_translate("ReportAcuteInfectionsSetupDialog", "--", None))
        self.label_2.setText(_translate("ReportAcuteInfectionsSetupDialog", "Период", None))
        self.chkCreateDate.setText(_translate("ReportAcuteInfectionsSetupDialog", "Период создания записи", None))
        self.lblCreateDate.setText(_translate("ReportAcuteInfectionsSetupDialog", "--", None))
        self.gbFilterAddress.setTitle(_translate("ReportAcuteInfectionsSetupDialog", "Адрес", None))
        self.lblFilterAddressHouse.setText(_translate("ReportAcuteInfectionsSetupDialog", "Дом", None))
        self.lblFilterAddressCorpus.setText(_translate("ReportAcuteInfectionsSetupDialog", "Корп", None))
        self.lblFilterAddressFlat.setText(_translate("ReportAcuteInfectionsSetupDialog", "Кв", None))
        self.cmbFilterAddressType.setItemText(0, _translate("ReportAcuteInfectionsSetupDialog", "Регистрации", None))
        self.cmbFilterAddressType.setItemText(1, _translate("ReportAcuteInfectionsSetupDialog", "Проживания", None))
        self.chkBirthYear.setText(_translate("ReportAcuteInfectionsSetupDialog", "Год рождения", None))
        self.lblAgeTo_3.setText(_translate("ReportAcuteInfectionsSetupDialog", "по", None))
        self.lblAgeYears_3.setText(_translate("ReportAcuteInfectionsSetupDialog", "лет", None))

from KLADR.kladrComboxes import CKLADRComboBox, CStreetComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Registry.SocStatusComboBox import CSocStatusComboBox
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEdit
from library.crbcombobox import CRBComboBox, CRBMultiComboBox
