# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReportListLeavedClient.ui'
#
# Created: Tue Jun 09 17:02:05 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportListLeavedClient(object):
    def setupUi(self, ReportListLeavedClient):
        ReportListLeavedClient.setObjectName(_fromUtf8("ReportListLeavedClient"))
        ReportListLeavedClient.resize(413, 549)
        self.gridLayout = QtGui.QGridLayout(ReportListLeavedClient)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.grpFilterColumns = QtGui.QGroupBox(ReportListLeavedClient)
        self.grpFilterColumns.setObjectName(_fromUtf8("grpFilterColumns"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpFilterColumns)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.chkOrderEvent = QtGui.QCheckBox(self.grpFilterColumns)
        self.chkOrderEvent.setChecked(True)
        self.chkOrderEvent.setObjectName(_fromUtf8("chkOrderEvent"))
        self.gridLayout_2.addWidget(self.chkOrderEvent, 6, 0, 1, 1)
        self.chkOrgReceived = QtGui.QCheckBox(self.grpFilterColumns)
        self.chkOrgReceived.setChecked(True)
        self.chkOrgReceived.setObjectName(_fromUtf8("chkOrgReceived"))
        self.gridLayout_2.addWidget(self.chkOrgReceived, 4, 0, 1, 1)
        self.chkAddress = QtGui.QCheckBox(self.grpFilterColumns)
        self.chkAddress.setChecked(True)
        self.chkAddress.setObjectName(_fromUtf8("chkAddress"))
        self.gridLayout_2.addWidget(self.chkAddress, 2, 0, 1, 1)
        self.chkFIO = QtGui.QCheckBox(self.grpFilterColumns)
        self.chkFIO.setChecked(True)
        self.chkFIO.setObjectName(_fromUtf8("chkFIO"))
        self.gridLayout_2.addWidget(self.chkFIO, 0, 0, 1, 1)
        self.chkExternalId = QtGui.QCheckBox(self.grpFilterColumns)
        self.chkExternalId.setChecked(True)
        self.chkExternalId.setObjectName(_fromUtf8("chkExternalId"))
        self.gridLayout_2.addWidget(self.chkExternalId, 1, 0, 1, 1)
        self.chkDiagnosis = QtGui.QCheckBox(self.grpFilterColumns)
        self.chkDiagnosis.setChecked(True)
        self.chkDiagnosis.setObjectName(_fromUtf8("chkDiagnosis"))
        self.gridLayout_2.addWidget(self.chkDiagnosis, 8, 0, 1, 1)
        self.chkSetDate = QtGui.QCheckBox(self.grpFilterColumns)
        self.chkSetDate.setChecked(True)
        self.chkSetDate.setObjectName(_fromUtf8("chkSetDate"))
        self.gridLayout_2.addWidget(self.chkSetDate, 9, 0, 1, 1)
        self.chkMovingDate = QtGui.QCheckBox(self.grpFilterColumns)
        self.chkMovingDate.setChecked(True)
        self.chkMovingDate.setObjectName(_fromUtf8("chkMovingDate"))
        self.gridLayout_2.addWidget(self.chkMovingDate, 0, 1, 1, 1)
        self.chkLeavedDate = QtGui.QCheckBox(self.grpFilterColumns)
        self.chkLeavedDate.setChecked(True)
        self.chkLeavedDate.setObjectName(_fromUtf8("chkLeavedDate"))
        self.gridLayout_2.addWidget(self.chkLeavedDate, 1, 1, 1, 1)
        self.chkProfile = QtGui.QCheckBox(self.grpFilterColumns)
        self.chkProfile.setChecked(True)
        self.chkProfile.setObjectName(_fromUtf8("chkProfile"))
        self.gridLayout_2.addWidget(self.chkProfile, 2, 1, 1, 1)
        self.chkOperation = QtGui.QCheckBox(self.grpFilterColumns)
        self.chkOperation.setChecked(True)
        self.chkOperation.setObjectName(_fromUtf8("chkOperation"))
        self.gridLayout_2.addWidget(self.chkOperation, 4, 1, 1, 1)
        self.chkDays = QtGui.QCheckBox(self.grpFilterColumns)
        self.chkDays.setChecked(True)
        self.chkDays.setObjectName(_fromUtf8("chkDays"))
        self.gridLayout_2.addWidget(self.chkDays, 6, 1, 1, 1)
        self.chkResult = QtGui.QCheckBox(self.grpFilterColumns)
        self.chkResult.setChecked(True)
        self.chkResult.setObjectName(_fromUtf8("chkResult"))
        self.gridLayout_2.addWidget(self.chkResult, 8, 1, 1, 1)
        self.gridLayout.addWidget(self.grpFilterColumns, 13, 0, 1, 4)
        self.chkOrgStructure = QtGui.QCheckBox(ReportListLeavedClient)
        self.chkOrgStructure.setObjectName(_fromUtf8("chkOrgStructure"))
        self.gridLayout.addWidget(self.chkOrgStructure, 8, 0, 1, 1)
        self.edtBegDate = CDateEdit(ReportListLeavedClient)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(ReportListLeavedClient)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.lblEndDate = QtGui.QLabel(ReportListLeavedClient)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 2, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ReportListLeavedClient)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 14, 0, 1, 4)
        self.lblBegDate = QtGui.QLabel(ReportListLeavedClient)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 2)
        self.label = QtGui.QLabel(ReportListLeavedClient)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 12, 0, 1, 1)
        self.edtEndDate = CDateEdit(ReportListLeavedClient)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 2, 2, 1, 1)
        self.cmbEventType = CRBComboBox(ReportListLeavedClient)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout.addWidget(self.cmbEventType, 4, 2, 1, 2)
        self.chkEventType = QtGui.QCheckBox(ReportListLeavedClient)
        self.chkEventType.setObjectName(_fromUtf8("chkEventType"))
        self.gridLayout.addWidget(self.chkEventType, 4, 0, 1, 1)
        self.lstEventType = CRBListBox(ReportListLeavedClient)
        self.lstEventType.setObjectName(_fromUtf8("lstEventType"))
        self.gridLayout.addWidget(self.lstEventType, 5, 0, 1, 4)
        self.lstOrgStructure = CRBListBox(ReportListLeavedClient)
        self.lstOrgStructure.setObjectName(_fromUtf8("lstOrgStructure"))
        self.gridLayout.addWidget(self.lstOrgStructure, 9, 0, 1, 4)
        self.cmbHospitalization = QtGui.QComboBox(ReportListLeavedClient)
        self.cmbHospitalization.setObjectName(_fromUtf8("cmbHospitalization"))
        self.cmbHospitalization.addItem(_fromUtf8(""))
        self.cmbHospitalization.addItem(_fromUtf8(""))
        self.cmbHospitalization.addItem(_fromUtf8(""))
        self.cmbHospitalization.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbHospitalization, 6, 2, 1, 2)
        self.cmbOrgStructure = COrgStructureComboBox(ReportListLeavedClient)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 8, 2, 1, 2)
        self.cmbTypeRegistry = QtGui.QComboBox(ReportListLeavedClient)
        self.cmbTypeRegistry.setObjectName(_fromUtf8("cmbTypeRegistry"))
        self.cmbTypeRegistry.addItem(_fromUtf8(""))
        self.cmbTypeRegistry.addItem(_fromUtf8(""))
        self.cmbTypeRegistry.addItem(_fromUtf8(""))
        self.cmbTypeRegistry.addItem(_fromUtf8(""))
        self.cmbTypeRegistry.addItem(_fromUtf8(""))
        self.cmbTypeRegistry.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbTypeRegistry, 12, 2, 1, 2)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblBegDate.setBuddy(self.edtBegDate)

        self.retranslateUi(ReportListLeavedClient)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportListLeavedClient.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportListLeavedClient.reject)
        QtCore.QMetaObject.connectSlotsByName(ReportListLeavedClient)

    def retranslateUi(self, ReportListLeavedClient):
        ReportListLeavedClient.setWindowTitle(_translate("ReportListLeavedClient", "Dialog", None))
        self.grpFilterColumns.setTitle(_translate("ReportListLeavedClient", "Отчет строится по столбцам", None))
        self.chkOrderEvent.setText(_translate("ReportListLeavedClient", "Порядок оказания помощи", None))
        self.chkOrgReceived.setText(_translate("ReportListLeavedClient", "Кем направлен", None))
        self.chkAddress.setText(_translate("ReportListLeavedClient", "Адрес", None))
        self.chkFIO.setText(_translate("ReportListLeavedClient", "ФИО", None))
        self.chkExternalId.setText(_translate("ReportListLeavedClient", "№ Истории болезни", None))
        self.chkDiagnosis.setText(_translate("ReportListLeavedClient", "Диагноз", None))
        self.chkSetDate.setText(_translate("ReportListLeavedClient", "Дата поступления", None))
        self.chkMovingDate.setText(_translate("ReportListLeavedClient", "Дата поступления в отделение", None))
        self.chkLeavedDate.setText(_translate("ReportListLeavedClient", "Дата выписки", None))
        self.chkProfile.setText(_translate("ReportListLeavedClient", "Профиль", None))
        self.chkOperation.setText(_translate("ReportListLeavedClient", "Код операции", None))
        self.chkDays.setText(_translate("ReportListLeavedClient", "Проведено койко-дней", None))
        self.chkResult.setText(_translate("ReportListLeavedClient", "Исход", None))
        self.chkOrgStructure.setText(_translate("ReportListLeavedClient", "Подразделение", None))
        self.label_2.setText(_translate("ReportListLeavedClient", "Тип госпитализации", None))
        self.lblEndDate.setText(_translate("ReportListLeavedClient", "Дата &окончания периода", None))
        self.lblBegDate.setText(_translate("ReportListLeavedClient", "Дата &начала периода", None))
        self.label.setText(_translate("ReportListLeavedClient", "Категория пациентов", None))
        self.chkEventType.setText(_translate("ReportListLeavedClient", "Тип обращения", None))
        self.cmbHospitalization.setItemText(0, _translate("ReportListLeavedClient", "не задано", None))
        self.cmbHospitalization.setItemText(1, _translate("ReportListLeavedClient", "Круглосуточная", None))
        self.cmbHospitalization.setItemText(2, _translate("ReportListLeavedClient", "Дневная", None))
        self.cmbHospitalization.setItemText(3, _translate("ReportListLeavedClient", "Отказ", None))
        self.cmbTypeRegistry.setItemText(0, _translate("ReportListLeavedClient", "Все", None))
        self.cmbTypeRegistry.setItemText(1, _translate("ReportListLeavedClient", "Иностранцы", None))
        self.cmbTypeRegistry.setItemText(2, _translate("ReportListLeavedClient", "Иностранцы с регистрацией", None))
        self.cmbTypeRegistry.setItemText(3, _translate("ReportListLeavedClient", "Жители Санкт-Петербурга", None))
        self.cmbTypeRegistry.setItemText(4, _translate("ReportListLeavedClient", "Жители Лен. области", None))
        self.cmbTypeRegistry.setItemText(5, _translate("ReportListLeavedClient", "Иногородние", None))

from library.RBListBox import CRBListBox
from library.crbcombobox import CRBComboBox
from library.DateEdit import CDateEdit
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
