# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TempInvalidSetup.ui'
#
# Created: Tue Dec 23 15:10:32 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TempInvalidSetupDialog(object):
    def setupUi(self, TempInvalidSetupDialog):
        TempInvalidSetupDialog.setObjectName(_fromUtf8("TempInvalidSetupDialog"))
        TempInvalidSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        TempInvalidSetupDialog.resize(346, 420)
        TempInvalidSetupDialog.setSizeGripEnabled(True)
        self.gridlayout = QtGui.QGridLayout(TempInvalidSetupDialog)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.lblDuration = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblDuration.setObjectName(_fromUtf8("lblDuration"))
        self.gridlayout.addWidget(self.lblDuration, 8, 0, 2, 1)
        self.frmDuration = QtGui.QFrame(TempInvalidSetupDialog)
        self.frmDuration.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmDuration.setFrameShadow(QtGui.QFrame.Raised)
        self.frmDuration.setObjectName(_fromUtf8("frmDuration"))
        self.hboxlayout = QtGui.QHBoxLayout(self.frmDuration)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.edtDurationFrom = QtGui.QSpinBox(self.frmDuration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDurationFrom.sizePolicy().hasHeightForWidth())
        self.edtDurationFrom.setSizePolicy(sizePolicy)
        self.edtDurationFrom.setMaximum(366)
        self.edtDurationFrom.setObjectName(_fromUtf8("edtDurationFrom"))
        self.hboxlayout.addWidget(self.edtDurationFrom)
        self.lblDurationTo = QtGui.QLabel(self.frmDuration)
        self.lblDurationTo.setObjectName(_fromUtf8("lblDurationTo"))
        self.hboxlayout.addWidget(self.lblDurationTo)
        self.edtDurationTo = QtGui.QSpinBox(self.frmDuration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDurationTo.sizePolicy().hasHeightForWidth())
        self.edtDurationTo.setSizePolicy(sizePolicy)
        self.edtDurationTo.setMaximum(366)
        self.edtDurationTo.setObjectName(_fromUtf8("edtDurationTo"))
        self.hboxlayout.addWidget(self.edtDurationTo)
        self.lblDurationDays = QtGui.QLabel(self.frmDuration)
        self.lblDurationDays.setObjectName(_fromUtf8("lblDurationDays"))
        self.hboxlayout.addWidget(self.lblDurationDays)
        spacerItem = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.gridlayout.addWidget(self.frmDuration, 8, 1, 1, 2)
        self.frmSex = QtGui.QFrame(TempInvalidSetupDialog)
        self.frmSex.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmSex.setFrameShadow(QtGui.QFrame.Raised)
        self.frmSex.setObjectName(_fromUtf8("frmSex"))
        self.hboxlayout1 = QtGui.QHBoxLayout(self.frmSex)
        self.hboxlayout1.setSpacing(4)
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.cmbSex = QtGui.QComboBox(self.frmSex)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.hboxlayout1.addWidget(self.cmbSex)
        spacerItem1 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.gridlayout.addWidget(self.frmSex, 9, 1, 2, 2)
        self.frmAge = QtGui.QFrame(TempInvalidSetupDialog)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self.hboxlayout2 = QtGui.QHBoxLayout(self.frmAge)
        self.hboxlayout2.setSpacing(4)
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self.hboxlayout2.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self.hboxlayout2.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self.hboxlayout2.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self.hboxlayout2.addWidget(self.lblAgeYears)
        spacerItem2 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem2)
        self.gridlayout.addWidget(self.frmAge, 11, 1, 1, 2)
        self.frmMKB = QtGui.QFrame(TempInvalidSetupDialog)
        self.frmMKB.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMKB.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMKB.setObjectName(_fromUtf8("frmMKB"))
        self.gridlayout1 = QtGui.QGridLayout(self.frmMKB)
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setHorizontalSpacing(4)
        self.gridlayout1.setVerticalSpacing(0)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.cmbMKBFilter = QtGui.QComboBox(self.frmMKB)
        self.cmbMKBFilter.setObjectName(_fromUtf8("cmbMKBFilter"))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.gridlayout1.addWidget(self.cmbMKBFilter, 0, 0, 1, 1)
        self.edtMKBFrom = CICDCodeEdit(self.frmMKB)
        self.edtMKBFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBFrom.sizePolicy().hasHeightForWidth())
        self.edtMKBFrom.setSizePolicy(sizePolicy)
        self.edtMKBFrom.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBFrom.setMaxLength(6)
        self.edtMKBFrom.setObjectName(_fromUtf8("edtMKBFrom"))
        self.gridlayout1.addWidget(self.edtMKBFrom, 0, 1, 1, 1)
        self.edtMKBTo = CICDCodeEdit(self.frmMKB)
        self.edtMKBTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBTo.sizePolicy().hasHeightForWidth())
        self.edtMKBTo.setSizePolicy(sizePolicy)
        self.edtMKBTo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBTo.setMaxLength(6)
        self.edtMKBTo.setObjectName(_fromUtf8("edtMKBTo"))
        self.gridlayout1.addWidget(self.edtMKBTo, 0, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem3, 0, 3, 1, 1)
        self.gridlayout.addWidget(self.frmMKB, 15, 1, 1, 2)
        self.edtBegDate = CDateEdit(TempInvalidSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridlayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.lblDocType = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblDocType.setObjectName(_fromUtf8("lblDocType"))
        self.gridlayout.addWidget(self.lblDocType, 3, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem4, 1, 2, 1, 1)
        self.edtEndDate = CDateEdit(TempInvalidSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridlayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        self.lblEndDate = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridlayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem5, 0, 2, 1, 1)
        self.lblBegDate = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridlayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.cmbDoctype = CRBComboBox(TempInvalidSetupDialog)
        self.cmbDoctype.setObjectName(_fromUtf8("cmbDoctype"))
        self.gridlayout.addWidget(self.cmbDoctype, 3, 1, 1, 2)
        self.lblTempInvalidReason = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblTempInvalidReason.setObjectName(_fromUtf8("lblTempInvalidReason"))
        self.gridlayout.addWidget(self.lblTempInvalidReason, 4, 0, 1, 1)
        self.cmbReason = CRBComboBox(TempInvalidSetupDialog)
        self.cmbReason.setObjectName(_fromUtf8("cmbReason"))
        self.gridlayout.addWidget(self.cmbReason, 4, 1, 1, 2)
        self.chkOnlyClosed = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkOnlyClosed.setChecked(True)
        self.chkOnlyClosed.setObjectName(_fromUtf8("chkOnlyClosed"))
        self.gridlayout.addWidget(self.chkOnlyClosed, 5, 1, 1, 2)
        self.lblOrgStructure = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridlayout.addWidget(self.lblOrgStructure, 6, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(TempInvalidSetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridlayout.addWidget(self.cmbOrgStructure, 6, 1, 1, 2)
        self.lblPerson = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridlayout.addWidget(self.lblPerson, 7, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(TempInvalidSetupDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbPerson, 7, 1, 1, 2)
        self.lblSex = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridlayout.addWidget(self.lblSex, 10, 0, 1, 1)
        self.lblAge = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridlayout.addWidget(self.lblAge, 11, 0, 1, 1)
        self.lblMKB = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblMKB.setObjectName(_fromUtf8("lblMKB"))
        self.gridlayout.addWidget(self.lblMKB, 15, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(21, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem6, 18, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(TempInvalidSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 19, 0, 1, 3)
        self.lblInsuranceOfficeMark = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblInsuranceOfficeMark.setObjectName(_fromUtf8("lblInsuranceOfficeMark"))
        self.gridlayout.addWidget(self.lblInsuranceOfficeMark, 16, 0, 1, 1)
        self.cmbInsuranceOfficeMark = QtGui.QComboBox(TempInvalidSetupDialog)
        self.cmbInsuranceOfficeMark.setObjectName(_fromUtf8("cmbInsuranceOfficeMark"))
        self.cmbInsuranceOfficeMark.addItem(_fromUtf8(""))
        self.cmbInsuranceOfficeMark.setItemText(0, _fromUtf8(""))
        self.cmbInsuranceOfficeMark.addItem(_fromUtf8(""))
        self.cmbInsuranceOfficeMark.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbInsuranceOfficeMark, 16, 1, 1, 2)
        self.chkByPeriod = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkByPeriod.setObjectName(_fromUtf8("chkByPeriod"))
        self.gridlayout.addWidget(self.chkByPeriod, 2, 1, 1, 2)
        self.cmbSocStatusClass = CSocStatusComboBox(TempInvalidSetupDialog)
        self.cmbSocStatusClass.setObjectName(_fromUtf8("cmbSocStatusClass"))
        self.gridlayout.addWidget(self.cmbSocStatusClass, 12, 1, 1, 2)
        self.lblSocStatusClass = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblSocStatusClass.setObjectName(_fromUtf8("lblSocStatusClass"))
        self.gridlayout.addWidget(self.lblSocStatusClass, 12, 0, 1, 1)
        self.lblSocStatusType = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblSocStatusType.setObjectName(_fromUtf8("lblSocStatusType"))
        self.gridlayout.addWidget(self.lblSocStatusType, 14, 0, 1, 1)
        self.cmbSocStatusType = CRBComboBox(TempInvalidSetupDialog)
        self.cmbSocStatusType.setObjectName(_fromUtf8("cmbSocStatusType"))
        self.gridlayout.addWidget(self.cmbSocStatusType, 14, 1, 1, 2)
        self.chkOldForm = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkOldForm.setObjectName(_fromUtf8("chkOldForm"))
        self.gridlayout.addWidget(self.chkOldForm, 17, 0, 1, 2)
        self.lblDuration.setBuddy(self.edtDurationFrom)
        self.lblDurationTo.setBuddy(self.edtDurationTo)
        self.lblDurationDays.setBuddy(self.edtDurationTo)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblDocType.setBuddy(self.cmbDoctype)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblTempInvalidReason.setBuddy(self.cmbReason)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblAge.setBuddy(self.edtAgeFrom)
        self.lblMKB.setBuddy(self.cmbMKBFilter)
        self.lblInsuranceOfficeMark.setBuddy(self.cmbInsuranceOfficeMark)
        self.lblSocStatusClass.setBuddy(self.cmbSocStatusClass)
        self.lblSocStatusType.setBuddy(self.cmbSocStatusType)

        self.retranslateUi(TempInvalidSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TempInvalidSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TempInvalidSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(TempInvalidSetupDialog)
        TempInvalidSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        TempInvalidSetupDialog.setTabOrder(self.edtEndDate, self.chkByPeriod)
        TempInvalidSetupDialog.setTabOrder(self.chkByPeriod, self.cmbDoctype)
        TempInvalidSetupDialog.setTabOrder(self.cmbDoctype, self.cmbReason)
        TempInvalidSetupDialog.setTabOrder(self.cmbReason, self.chkOnlyClosed)
        TempInvalidSetupDialog.setTabOrder(self.chkOnlyClosed, self.cmbOrgStructure)
        TempInvalidSetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbPerson)
        TempInvalidSetupDialog.setTabOrder(self.cmbPerson, self.edtDurationFrom)
        TempInvalidSetupDialog.setTabOrder(self.edtDurationFrom, self.edtDurationTo)
        TempInvalidSetupDialog.setTabOrder(self.edtDurationTo, self.cmbSex)
        TempInvalidSetupDialog.setTabOrder(self.cmbSex, self.edtAgeFrom)
        TempInvalidSetupDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        TempInvalidSetupDialog.setTabOrder(self.edtAgeTo, self.cmbSocStatusClass)
        TempInvalidSetupDialog.setTabOrder(self.cmbSocStatusClass, self.cmbSocStatusType)
        TempInvalidSetupDialog.setTabOrder(self.cmbSocStatusType, self.cmbMKBFilter)
        TempInvalidSetupDialog.setTabOrder(self.cmbMKBFilter, self.edtMKBFrom)
        TempInvalidSetupDialog.setTabOrder(self.edtMKBFrom, self.edtMKBTo)
        TempInvalidSetupDialog.setTabOrder(self.edtMKBTo, self.cmbInsuranceOfficeMark)
        TempInvalidSetupDialog.setTabOrder(self.cmbInsuranceOfficeMark, self.buttonBox)

    def retranslateUi(self, TempInvalidSetupDialog):
        TempInvalidSetupDialog.setWindowTitle(_translate("TempInvalidSetupDialog", "параметры отчёта", None))
        self.lblDuration.setText(_translate("TempInvalidSetupDialog", "&Длительность с", None))
        self.lblDurationTo.setText(_translate("TempInvalidSetupDialog", "по", None))
        self.lblDurationDays.setText(_translate("TempInvalidSetupDialog", "дней", None))
        self.cmbSex.setItemText(1, _translate("TempInvalidSetupDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("TempInvalidSetupDialog", "Ж", None))
        self.lblAgeTo.setText(_translate("TempInvalidSetupDialog", "по", None))
        self.lblAgeYears.setText(_translate("TempInvalidSetupDialog", "лет", None))
        self.cmbMKBFilter.setItemText(0, _translate("TempInvalidSetupDialog", "Игнор.", None))
        self.cmbMKBFilter.setItemText(1, _translate("TempInvalidSetupDialog", "Интервал", None))
        self.cmbMKBFilter.setItemText(2, _translate("TempInvalidSetupDialog", "Без диагноза", None))
        self.edtMKBFrom.setInputMask(_translate("TempInvalidSetupDialog", "a00.00; ", None))
        self.edtMKBFrom.setText(_translate("TempInvalidSetupDialog", "A.", None))
        self.edtMKBTo.setInputMask(_translate("TempInvalidSetupDialog", "a00.00; ", None))
        self.edtMKBTo.setText(_translate("TempInvalidSetupDialog", "Z99.9", None))
        self.edtBegDate.setDisplayFormat(_translate("TempInvalidSetupDialog", "dd.MM.yyyy", None))
        self.lblDocType.setText(_translate("TempInvalidSetupDialog", "Тип &документа", None))
        self.edtEndDate.setDisplayFormat(_translate("TempInvalidSetupDialog", "dd.MM.yyyy", None))
        self.lblEndDate.setText(_translate("TempInvalidSetupDialog", "Дата &окончания периода", None))
        self.lblBegDate.setText(_translate("TempInvalidSetupDialog", "Дата &начала периода", None))
        self.lblTempInvalidReason.setText(_translate("TempInvalidSetupDialog", "При&чина", None))
        self.chkOnlyClosed.setText(_translate("TempInvalidSetupDialog", "&Только &закрытые", None))
        self.lblOrgStructure.setText(_translate("TempInvalidSetupDialog", "&Подразделение", None))
        self.lblPerson.setText(_translate("TempInvalidSetupDialog", "&Врач", None))
        self.cmbPerson.setItemText(0, _translate("TempInvalidSetupDialog", "Врач", None))
        self.lblSex.setText(_translate("TempInvalidSetupDialog", "По&л", None))
        self.lblAge.setText(_translate("TempInvalidSetupDialog", "Во&зраст с", None))
        self.lblMKB.setText(_translate("TempInvalidSetupDialog", "Коды диагнозов по &МКБ", None))
        self.lblInsuranceOfficeMark.setText(_translate("TempInvalidSetupDialog", "&Отметка страхового стола", None))
        self.cmbInsuranceOfficeMark.setItemText(1, _translate("TempInvalidSetupDialog", "без отметки", None))
        self.cmbInsuranceOfficeMark.setItemText(2, _translate("TempInvalidSetupDialog", "с отметкой", None))
        self.chkByPeriod.setToolTip(_translate("TempInvalidSetupDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">Если отметка <span style=\" font-weight:600;\">стоит</span>, то для отчёта <br />выбираются документы ВУТ с <span style=\" font-weight:600;\">периодом, </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-weight:600;\">пересекающимя с периодом отчёта</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">Если отметка <span style=\" font-weight:600;\">снята</span>, то для отчёта </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">выбираются документы ВУТ </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><span style=\" font-weight:600;\">закрытые в периоде отчёта</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p></body></html>", None))
        self.chkByPeriod.setText(_translate("TempInvalidSetupDialog", "Отчёт по периоду случая", None))
        self.lblSocStatusClass.setText(_translate("TempInvalidSetupDialog", "Класс соц.статуса", None))
        self.lblSocStatusType.setText(_translate("TempInvalidSetupDialog", "Тип соц.статуса", None))
        self.chkOldForm.setText(_translate("TempInvalidSetupDialog", "Страя форма отчета", None))

from library.crbcombobox import CRBComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.ICDCodeEdit import CICDCodeEdit
from Registry.SocStatusComboBox import CSocStatusComboBox
from library.DateEdit import CDateEdit
