# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JobTicketEditor2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_JobTicketEditorDialog(object):
    def setupUi(self, JobTicketEditorDialog):
        JobTicketEditorDialog.setObjectName(_fromUtf8("JobTicketEditorDialog"))
        JobTicketEditorDialog.resize(1299, 734)
        JobTicketEditorDialog.setSizeGripEnabled(False)
        self.verticalLayout = QtGui.QVBoxLayout(JobTicketEditorDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(JobTicketEditorDialog)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.txtClientInfoBrowser = CTextBrowser(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtClientInfoBrowser.sizePolicy().hasHeightForWidth())
        self.txtClientInfoBrowser.setSizePolicy(sizePolicy)
        self.txtClientInfoBrowser.setMinimumSize(QtCore.QSize(0, 100))
        self.txtClientInfoBrowser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtClientInfoBrowser.setReadOnly(True)
        self.txtClientInfoBrowser.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.grpMain = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpMain.sizePolicy().hasHeightForWidth())
        self.grpMain.setSizePolicy(sizePolicy)
        self.grpMain.setObjectName(_fromUtf8("grpMain"))
        self.gridLayout = QtGui.QGridLayout(self.grpMain)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblJobTypeValue = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblJobTypeValue.sizePolicy().hasHeightForWidth())
        self.lblJobTypeValue.setSizePolicy(sizePolicy)
        self.lblJobTypeValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblJobTypeValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblJobTypeValue.setObjectName(_fromUtf8("lblJobTypeValue"))
        self.gridLayout.addWidget(self.lblJobTypeValue, 2, 1, 1, 1)
        self.edtEndTime = QtGui.QTimeEdit(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndTime.sizePolicy().hasHeightForWidth())
        self.edtEndTime.setSizePolicy(sizePolicy)
        self.edtEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtEndTime.setCurrentSectionIndex(0)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.gridLayout.addWidget(self.edtEndTime, 1, 4, 1, 1)
        self.lblJobType = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblJobType.sizePolicy().hasHeightForWidth())
        self.lblJobType.setSizePolicy(sizePolicy)
        self.lblJobType.setObjectName(_fromUtf8("lblJobType"))
        self.gridLayout.addWidget(self.lblJobType, 2, 0, 1, 1)
        self.btnSetEndDateTime = QtGui.QToolButton(self.grpMain)
        self.btnSetEndDateTime.setArrowType(QtCore.Qt.LeftArrow)
        self.btnSetEndDateTime.setObjectName(_fromUtf8("btnSetEndDateTime"))
        self.gridLayout.addWidget(self.btnSetEndDateTime, 1, 5, 1, 1)
        self.edtBegTime = QtGui.QTimeEdit(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegTime.sizePolicy().hasHeightForWidth())
        self.edtBegTime.setSizePolicy(sizePolicy)
        self.edtBegTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtBegTime.setCurrentSectionIndex(0)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.gridLayout.addWidget(self.edtBegTime, 0, 4, 1, 1)
        self.lblEndDatetime = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDatetime.sizePolicy().hasHeightForWidth())
        self.lblEndDatetime.setSizePolicy(sizePolicy)
        self.lblEndDatetime.setObjectName(_fromUtf8("lblEndDatetime"))
        self.gridLayout.addWidget(self.lblEndDatetime, 1, 2, 1, 1)
        self.lblOrgStructureValue = QtGui.QLabel(self.grpMain)
        self.lblOrgStructureValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblOrgStructureValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblOrgStructureValue.setObjectName(_fromUtf8("lblOrgStructureValue"))
        self.gridLayout.addWidget(self.lblOrgStructureValue, 1, 1, 1, 1)
        self.lblBegDateTime = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDateTime.sizePolicy().hasHeightForWidth())
        self.lblBegDateTime.setSizePolicy(sizePolicy)
        self.lblBegDateTime.setObjectName(_fromUtf8("lblBegDateTime"))
        self.gridLayout.addWidget(self.lblBegDateTime, 0, 2, 1, 1)
        self.lblDatetimeValue = QtGui.QLabel(self.grpMain)
        self.lblDatetimeValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblDatetimeValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblDatetimeValue.setObjectName(_fromUtf8("lblDatetimeValue"))
        self.gridLayout.addWidget(self.lblDatetimeValue, 0, 1, 1, 1)
        self.btnSetBegDateTime = QtGui.QToolButton(self.grpMain)
        self.btnSetBegDateTime.setArrowType(QtCore.Qt.LeftArrow)
        self.btnSetBegDateTime.setObjectName(_fromUtf8("btnSetBegDateTime"))
        self.gridLayout.addWidget(self.btnSetBegDateTime, 0, 5, 1, 1)
        self.lblDatetime = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDatetime.sizePolicy().hasHeightForWidth())
        self.lblDatetime.setSizePolicy(sizePolicy)
        self.lblDatetime.setObjectName(_fromUtf8("lblDatetime"))
        self.gridLayout.addWidget(self.lblDatetime, 0, 0, 1, 1)
        self.edtBegDate = CDateEdit(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 3, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblOrgStructure.setSizePolicy(sizePolicy)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 1, 0, 1, 1)
        self.edtEndDate = CDateEdit(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 3, 1, 1)
        self.lblStatus = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStatus.sizePolicy().hasHeightForWidth())
        self.lblStatus.setSizePolicy(sizePolicy)
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))
        self.gridLayout.addWidget(self.lblStatus, 2, 2, 1, 1)
        self.cmbStatus = QtGui.QComboBox(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbStatus.sizePolicy().hasHeightForWidth())
        self.cmbStatus.setSizePolicy(sizePolicy)
        self.cmbStatus.setObjectName(_fromUtf8("cmbStatus"))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbStatus, 2, 3, 1, 3)
        self.gridWidget = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.gridWidget.sizePolicy().hasHeightForWidth())
        self.gridWidget.setSizePolicy(sizePolicy)
        self.gridWidget.setObjectName(_fromUtf8("gridWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gridWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter_2 = QtGui.QSplitter(self.gridWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.tblTreeProbe = CJobTicketProbeTreeView2(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblTreeProbe.sizePolicy().hasHeightForWidth())
        self.tblTreeProbe.setSizePolicy(sizePolicy)
        self.tblTreeProbe.setObjectName(_fromUtf8("tblTreeProbe"))
        self.tblProps = CActionPropertiesTableView(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblProps.sizePolicy().hasHeightForWidth())
        self.tblProps.setSizePolicy(sizePolicy)
        self.tblProps.setObjectName(_fromUtf8("tblProps"))
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.btnSaveAsTemplate = QtGui.QPushButton(self.gridWidget)
        self.btnSaveAsTemplate.setObjectName(_fromUtf8("btnSaveAsTemplate"))
        self.gridLayout_5.addWidget(self.btnSaveAsTemplate, 0, 2, 1, 1)
        self.btnEditEvent = QtGui.QPushButton(self.gridWidget)
        self.btnEditEvent.setObjectName(_fromUtf8("btnEditEvent"))
        self.gridLayout_5.addWidget(self.btnEditEvent, 0, 5, 1, 1)
        self.btnAmbCard = QtGui.QPushButton(self.gridWidget)
        self.btnAmbCard.setObjectName(_fromUtf8("btnAmbCard"))
        self.gridLayout_5.addWidget(self.btnAmbCard, 0, 4, 1, 1)
        self.btnLoadTemplate = CActionTemplateChooseButton(self.gridWidget)
        self.btnLoadTemplate.setObjectName(_fromUtf8("btnLoadTemplate"))
        self.gridLayout_5.addWidget(self.btnLoadTemplate, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 7, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.verticalLayout.addWidget(self.splitter)
        self.buttonBox = QtGui.QDialogButtonBox(JobTicketEditorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.lblEndDatetime.setBuddy(self.edtEndDate)
        self.lblBegDateTime.setBuddy(self.edtBegDate)
        self.lblStatus.setBuddy(self.cmbStatus)

        self.retranslateUi(JobTicketEditorDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), JobTicketEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), JobTicketEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(JobTicketEditorDialog)
        JobTicketEditorDialog.setTabOrder(self.edtBegDate, self.edtBegTime)
        JobTicketEditorDialog.setTabOrder(self.edtBegTime, self.btnSetBegDateTime)
        JobTicketEditorDialog.setTabOrder(self.btnSetBegDateTime, self.edtEndDate)
        JobTicketEditorDialog.setTabOrder(self.edtEndDate, self.edtEndTime)
        JobTicketEditorDialog.setTabOrder(self.edtEndTime, self.btnSetEndDateTime)
        JobTicketEditorDialog.setTabOrder(self.btnSetEndDateTime, self.buttonBox)

    def retranslateUi(self, JobTicketEditorDialog):
        JobTicketEditorDialog.setWindowTitle(_translate("JobTicketEditorDialog", "ChangeMe!", None))
        self.txtClientInfoBrowser.setHtml(_translate("JobTicketEditorDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>", None))
        self.grpMain.setTitle(_translate("JobTicketEditorDialog", "Основная информация", None))
        self.lblJobTypeValue.setText(_translate("JobTicketEditorDialog", "анализ крови", None))
        self.edtEndTime.setDisplayFormat(_translate("JobTicketEditorDialog", "HH:mm", None))
        self.lblJobType.setText(_translate("JobTicketEditorDialog", "Работа", None))
        self.btnSetEndDateTime.setText(_translate("JobTicketEditorDialog", "...", None))
        self.edtBegTime.setDisplayFormat(_translate("JobTicketEditorDialog", "HH:mm", None))
        self.lblEndDatetime.setText(_translate("JobTicketEditorDialog", "Дата и время окончания выполнения", None))
        self.lblOrgStructureValue.setText(_translate("JobTicketEditorDialog", "Лаборатория", None))
        self.lblBegDateTime.setText(_translate("JobTicketEditorDialog", "Дата и время начала выполнения", None))
        self.lblDatetimeValue.setText(_translate("JobTicketEditorDialog", "01.12.2009 19:30", None))
        self.btnSetBegDateTime.setText(_translate("JobTicketEditorDialog", "...", None))
        self.lblDatetime.setText(_translate("JobTicketEditorDialog", "Плановые дата и время", None))
        self.lblOrgStructure.setText(_translate("JobTicketEditorDialog", "Подразделение", None))
        self.lblStatus.setText(_translate("JobTicketEditorDialog", "Состояние", None))
        self.cmbStatus.setItemText(0, _translate("JobTicketEditorDialog", "Ожидание", None))
        self.cmbStatus.setItemText(1, _translate("JobTicketEditorDialog", "Выполняется", None))
        self.cmbStatus.setItemText(2, _translate("JobTicketEditorDialog", "Закончено", None))
        self.btnSaveAsTemplate.setText(_translate("JobTicketEditorDialog", "Сохранить шаблон", None))
        self.btnEditEvent.setText(_translate("JobTicketEditorDialog", "Перейти в обращение", None))
        self.btnAmbCard.setText(_translate("JobTicketEditorDialog", "Медицинская карта", None))
        self.btnLoadTemplate.setText(_translate("JobTicketEditorDialog", "Загрузить шаблон", None))

from Events.ActionPropertiesTable import CActionPropertiesTableView
from Events.ActionTemplateChoose import CActionTemplateChooseButton
from Resources.JobTicketProbeModel2 import CJobTicketProbeTreeView2
from library.DateEdit import CDateEdit
from library.TextBrowser import CTextBrowser
