# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JobTicketEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_JobTicketEditorDialog(object):
    def setupUi(self, JobTicketEditorDialog):
        JobTicketEditorDialog.setObjectName(_fromUtf8("JobTicketEditorDialog"))
        JobTicketEditorDialog.resize(1069, 654)
        JobTicketEditorDialog.setSizeGripEnabled(False)
        self.verticalLayout_2 = QtGui.QVBoxLayout(JobTicketEditorDialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter_2 = QtGui.QSplitter(JobTicketEditorDialog)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.txtClientInfoBrowser = CTextBrowser(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.txtClientInfoBrowser.sizePolicy().hasHeightForWidth())
        self.txtClientInfoBrowser.setSizePolicy(sizePolicy)
        self.txtClientInfoBrowser.setMinimumSize(QtCore.QSize(0, 100))
        self.txtClientInfoBrowser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtClientInfoBrowser.setReadOnly(True)
        self.txtClientInfoBrowser.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.frmCommon = QtGui.QFrame(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmCommon.sizePolicy().hasHeightForWidth())
        self.frmCommon.setSizePolicy(sizePolicy)
        self.frmCommon.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmCommon.setFrameShadow(QtGui.QFrame.Plain)
        self.frmCommon.setLineWidth(0)
        self.frmCommon.setObjectName(_fromUtf8("frmCommon"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frmCommon)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.grpTissue = QtGui.QGroupBox(self.frmCommon)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpTissue.sizePolicy().hasHeightForWidth())
        self.grpTissue.setSizePolicy(sizePolicy)
        self.grpTissue.setObjectName(_fromUtf8("grpTissue"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grpTissue)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblTissueType = QtGui.QLabel(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueType.sizePolicy().hasHeightForWidth())
        self.lblTissueType.setSizePolicy(sizePolicy)
        self.lblTissueType.setObjectName(_fromUtf8("lblTissueType"))
        self.gridLayout_3.addWidget(self.lblTissueType, 1, 0, 1, 2)
        self.cmbTissueType = CRBComboBox(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTissueType.sizePolicy().hasHeightForWidth())
        self.cmbTissueType.setSizePolicy(sizePolicy)
        self.cmbTissueType.setObjectName(_fromUtf8("cmbTissueType"))
        self.gridLayout_3.addWidget(self.cmbTissueType, 1, 2, 1, 1)
        self.lblTissueDateTime = QtGui.QLabel(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueDateTime.sizePolicy().hasHeightForWidth())
        self.lblTissueDateTime.setSizePolicy(sizePolicy)
        self.lblTissueDateTime.setObjectName(_fromUtf8("lblTissueDateTime"))
        self.gridLayout_3.addWidget(self.lblTissueDateTime, 1, 3, 1, 1)
        self.edtTissueDate = CDateEdit(self.grpTissue)
        self.edtTissueDate.setCalendarPopup(True)
        self.edtTissueDate.setObjectName(_fromUtf8("edtTissueDate"))
        self.gridLayout_3.addWidget(self.edtTissueDate, 1, 4, 1, 1)
        self.edtTissueTime = QtGui.QTimeEdit(self.grpTissue)
        self.edtTissueTime.setObjectName(_fromUtf8("edtTissueTime"))
        self.gridLayout_3.addWidget(self.edtTissueTime, 1, 5, 1, 1)
        self.lblTissueExternalId = QtGui.QLabel(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueExternalId.sizePolicy().hasHeightForWidth())
        self.lblTissueExternalId.setSizePolicy(sizePolicy)
        self.lblTissueExternalId.setObjectName(_fromUtf8("lblTissueExternalId"))
        self.gridLayout_3.addWidget(self.lblTissueExternalId, 3, 3, 1, 1)
        self.edtTissueExternalId = QtGui.QLineEdit(self.grpTissue)
        self.edtTissueExternalId.setReadOnly(True)
        self.edtTissueExternalId.setObjectName(_fromUtf8("edtTissueExternalId"))
        self.gridLayout_3.addWidget(self.edtTissueExternalId, 3, 4, 1, 2)
        self.lblTissueNote = QtGui.QLabel(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueNote.sizePolicy().hasHeightForWidth())
        self.lblTissueNote.setSizePolicy(sizePolicy)
        self.lblTissueNote.setObjectName(_fromUtf8("lblTissueNote"))
        self.gridLayout_3.addWidget(self.lblTissueNote, 5, 0, 1, 2)
        self.edtTissueNote = QtGui.QLineEdit(self.grpTissue)
        self.edtTissueNote.setObjectName(_fromUtf8("edtTissueNote"))
        self.gridLayout_3.addWidget(self.edtTissueNote, 5, 2, 1, 7)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 6, 1, 3)
        self.lblTissueAmount = QtGui.QLabel(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueAmount.sizePolicy().hasHeightForWidth())
        self.lblTissueAmount.setSizePolicy(sizePolicy)
        self.lblTissueAmount.setObjectName(_fromUtf8("lblTissueAmount"))
        self.gridLayout_3.addWidget(self.lblTissueAmount, 2, 3, 1, 1)
        self.edtTissueAmount = QtGui.QSpinBox(self.grpTissue)
        self.edtTissueAmount.setMaximum(999999)
        self.edtTissueAmount.setObjectName(_fromUtf8("edtTissueAmount"))
        self.gridLayout_3.addWidget(self.edtTissueAmount, 2, 4, 1, 2)
        self.lblTissyeExecPerson = QtGui.QLabel(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissyeExecPerson.sizePolicy().hasHeightForWidth())
        self.lblTissyeExecPerson.setSizePolicy(sizePolicy)
        self.lblTissyeExecPerson.setObjectName(_fromUtf8("lblTissyeExecPerson"))
        self.gridLayout_3.addWidget(self.lblTissyeExecPerson, 2, 0, 1, 1)
        self.cmbTissueExecPerson = CPersonComboBoxEx(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTissueExecPerson.sizePolicy().hasHeightForWidth())
        self.cmbTissueExecPerson.setSizePolicy(sizePolicy)
        self.cmbTissueExecPerson.setObjectName(_fromUtf8("cmbTissueExecPerson"))
        self.gridLayout_3.addWidget(self.cmbTissueExecPerson, 2, 2, 1, 1)
        self.lblTissueUnit = QtGui.QLabel(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueUnit.sizePolicy().hasHeightForWidth())
        self.lblTissueUnit.setSizePolicy(sizePolicy)
        self.lblTissueUnit.setObjectName(_fromUtf8("lblTissueUnit"))
        self.gridLayout_3.addWidget(self.lblTissueUnit, 3, 0, 1, 1)
        self.cmbTissueUnit = CRBComboBox(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTissueUnit.sizePolicy().hasHeightForWidth())
        self.cmbTissueUnit.setSizePolicy(sizePolicy)
        self.cmbTissueUnit.setObjectName(_fromUtf8("cmbTissueUnit"))
        self.gridLayout_3.addWidget(self.cmbTissueUnit, 3, 2, 1, 1)
        self.lblTissueNumber = QtGui.QLabel(self.grpTissue)
        self.lblTissueNumber.setObjectName(_fromUtf8("lblTissueNumber"))
        self.gridLayout_3.addWidget(self.lblTissueNumber, 3, 7, 1, 1)
        self.edtTissueNumber = QtGui.QLineEdit(self.grpTissue)
        self.edtTissueNumber.setReadOnly(True)
        self.edtTissueNumber.setObjectName(_fromUtf8("edtTissueNumber"))
        self.gridLayout_3.addWidget(self.edtTissueNumber, 3, 8, 1, 1)
        self.btnPrintTissueLabel = QtGui.QPushButton(self.grpTissue)
        self.btnPrintTissueLabel.setEnabled(False)
        self.btnPrintTissueLabel.setObjectName(_fromUtf8("btnPrintTissueLabel"))
        self.gridLayout_3.addWidget(self.btnPrintTissueLabel, 3, 6, 1, 1)
        self.verticalLayout_3.addWidget(self.grpTissue)
        self.grpMain = QtGui.QGroupBox(self.frmCommon)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpMain.sizePolicy().hasHeightForWidth())
        self.grpMain.setSizePolicy(sizePolicy)
        self.grpMain.setObjectName(_fromUtf8("grpMain"))
        self.gridLayout = QtGui.QGridLayout(self.grpMain)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblDatetime = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDatetime.sizePolicy().hasHeightForWidth())
        self.lblDatetime.setSizePolicy(sizePolicy)
        self.lblDatetime.setObjectName(_fromUtf8("lblDatetime"))
        self.gridLayout.addWidget(self.lblDatetime, 0, 0, 1, 1)
        self.lblDatetimeValue = QtGui.QLabel(self.grpMain)
        self.lblDatetimeValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblDatetimeValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblDatetimeValue.setObjectName(_fromUtf8("lblDatetimeValue"))
        self.gridLayout.addWidget(self.lblDatetimeValue, 0, 1, 1, 1)
        self.lblBegDateTime = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDateTime.sizePolicy().hasHeightForWidth())
        self.lblBegDateTime.setSizePolicy(sizePolicy)
        self.lblBegDateTime.setObjectName(_fromUtf8("lblBegDateTime"))
        self.gridLayout.addWidget(self.lblBegDateTime, 0, 2, 1, 1)
        self.edtBegDate = CDateEdit(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 3, 1, 1)
        self.edtBegTime = QtGui.QTimeEdit(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegTime.sizePolicy().hasHeightForWidth())
        self.edtBegTime.setSizePolicy(sizePolicy)
        self.edtBegTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtBegTime.setCurrentSectionIndex(0)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.gridLayout.addWidget(self.edtBegTime, 0, 4, 1, 1)
        self.btnSetBegDateTime = QtGui.QToolButton(self.grpMain)
        self.btnSetBegDateTime.setArrowType(QtCore.Qt.LeftArrow)
        self.btnSetBegDateTime.setObjectName(_fromUtf8("btnSetBegDateTime"))
        self.gridLayout.addWidget(self.btnSetBegDateTime, 0, 5, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblOrgStructure.setSizePolicy(sizePolicy)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 1, 0, 1, 1)
        self.lblOrgStructureValue = QtGui.QLabel(self.grpMain)
        self.lblOrgStructureValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblOrgStructureValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblOrgStructureValue.setObjectName(_fromUtf8("lblOrgStructureValue"))
        self.gridLayout.addWidget(self.lblOrgStructureValue, 1, 1, 1, 1)
        self.lblEndDatetime = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDatetime.sizePolicy().hasHeightForWidth())
        self.lblEndDatetime.setSizePolicy(sizePolicy)
        self.lblEndDatetime.setObjectName(_fromUtf8("lblEndDatetime"))
        self.gridLayout.addWidget(self.lblEndDatetime, 1, 2, 1, 1)
        self.edtEndDate = CDateEdit(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 3, 1, 1)
        self.edtEndTime = QtGui.QTimeEdit(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndTime.sizePolicy().hasHeightForWidth())
        self.edtEndTime.setSizePolicy(sizePolicy)
        self.edtEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtEndTime.setCurrentSectionIndex(0)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.gridLayout.addWidget(self.edtEndTime, 1, 4, 1, 1)
        self.btnSetEndDateTime = QtGui.QToolButton(self.grpMain)
        self.btnSetEndDateTime.setArrowType(QtCore.Qt.LeftArrow)
        self.btnSetEndDateTime.setObjectName(_fromUtf8("btnSetEndDateTime"))
        self.gridLayout.addWidget(self.btnSetEndDateTime, 1, 5, 1, 1)
        self.lblJobType = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblJobType.sizePolicy().hasHeightForWidth())
        self.lblJobType.setSizePolicy(sizePolicy)
        self.lblJobType.setObjectName(_fromUtf8("lblJobType"))
        self.gridLayout.addWidget(self.lblJobType, 2, 0, 1, 1)
        self.lblJobTypeValue = QtGui.QLabel(self.grpMain)
        self.lblJobTypeValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblJobTypeValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblJobTypeValue.setObjectName(_fromUtf8("lblJobTypeValue"))
        self.gridLayout.addWidget(self.lblJobTypeValue, 2, 1, 1, 1)
        self.lblStatus = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStatus.sizePolicy().hasHeightForWidth())
        self.lblStatus.setSizePolicy(sizePolicy)
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))
        self.gridLayout.addWidget(self.lblStatus, 3, 0, 1, 1)
        self.cmbStatus = QtGui.QComboBox(self.grpMain)
        self.cmbStatus.setObjectName(_fromUtf8("cmbStatus"))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbStatus, 3, 1, 1, 1)
        self.lblLabel = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLabel.sizePolicy().hasHeightForWidth())
        self.lblLabel.setSizePolicy(sizePolicy)
        self.lblLabel.setObjectName(_fromUtf8("lblLabel"))
        self.gridLayout.addWidget(self.lblLabel, 4, 0, 1, 1)
        self.edtLabel = QtGui.QLineEdit(self.grpMain)
        self.edtLabel.setObjectName(_fromUtf8("edtLabel"))
        self.gridLayout.addWidget(self.edtLabel, 4, 1, 1, 5)
        self.lblNote = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNote.sizePolicy().hasHeightForWidth())
        self.lblNote.setSizePolicy(sizePolicy)
        self.lblNote.setObjectName(_fromUtf8("lblNote"))
        self.gridLayout.addWidget(self.lblNote, 5, 0, 1, 1)
        self.edtNote = QtGui.QLineEdit(self.grpMain)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout.addWidget(self.edtNote, 5, 1, 1, 5)
        self.verticalLayout_3.addWidget(self.grpMain)
        self.tabWidget = QtGui.QTabWidget(self.splitter_2)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabActions = QtGui.QWidget()
        self.tabActions.setObjectName(_fromUtf8("tabActions"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabActions)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(self.tabActions)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tblActions = CTableView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblActions.sizePolicy().hasHeightForWidth())
        self.tblActions.setSizePolicy(sizePolicy)
        self.tblActions.setObjectName(_fromUtf8("tblActions"))
        self.widget = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblProps = CActionPropertiesTableView(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblProps.sizePolicy().hasHeightForWidth())
        self.tblProps.setSizePolicy(sizePolicy)
        self.tblProps.setObjectName(_fromUtf8("tblProps"))
        self.gridLayout_2.addWidget(self.tblProps, 0, 0, 1, 11)
        self.verticalLayout.addWidget(self.splitter)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.btnSaveAsTemplate = QtGui.QPushButton(self.tabActions)
        self.btnSaveAsTemplate.setObjectName(_fromUtf8("btnSaveAsTemplate"))
        self.gridLayout_5.addWidget(self.btnSaveAsTemplate, 0, 2, 1, 1)
        self.btnCloneValues = QtGui.QPushButton(self.tabActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCloneValues.sizePolicy().hasHeightForWidth())
        self.btnCloneValues.setSizePolicy(sizePolicy)
        self.btnCloneValues.setObjectName(_fromUtf8("btnCloneValues"))
        self.gridLayout_5.addWidget(self.btnCloneValues, 0, 3, 1, 1)
        self.btnFillPropertiesValue = QtGui.QPushButton(self.tabActions)
        self.btnFillPropertiesValue.setObjectName(_fromUtf8("btnFillPropertiesValue"))
        self.gridLayout_5.addWidget(self.btnFillPropertiesValue, 0, 4, 1, 1)
        self.btnEditEvent = QtGui.QPushButton(self.tabActions)
        self.btnEditEvent.setObjectName(_fromUtf8("btnEditEvent"))
        self.gridLayout_5.addWidget(self.btnEditEvent, 0, 6, 1, 1)
        self.btnAmbCard = QtGui.QPushButton(self.tabActions)
        self.btnAmbCard.setObjectName(_fromUtf8("btnAmbCard"))
        self.gridLayout_5.addWidget(self.btnAmbCard, 0, 5, 1, 1)
        self.btnShowSnapshots = QtGui.QPushButton(self.tabActions)
        self.btnShowSnapshots.setObjectName(_fromUtf8("btnShowSnapshots"))
        self.gridLayout_5.addWidget(self.btnShowSnapshots, 0, 7, 1, 1)
        self.btnFindSnapshots = QtGui.QPushButton(self.tabActions)
        self.btnFindSnapshots.setObjectName(_fromUtf8("btnFindSnapshots"))
        self.gridLayout_5.addWidget(self.btnFindSnapshots, 0, 8, 1, 1)
        self.btnLoadTemplate = CActionTemplateChooseButton(self.tabActions)
        self.btnLoadTemplate.setObjectName(_fromUtf8("btnLoadTemplate"))
        self.gridLayout_5.addWidget(self.btnLoadTemplate, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 10, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.tabWidget.addTab(self.tabActions, _fromUtf8(""))
        self.tabProbes = QtGui.QWidget()
        self.tabProbes.setObjectName(_fromUtf8("tabProbes"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabProbes)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tblTreeProbe = CJobTicketProbeTreeView(self.tabProbes)
        self.tblTreeProbe.setObjectName(_fromUtf8("tblTreeProbe"))
        self.gridLayout_4.addWidget(self.tblTreeProbe, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabProbes, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.buttonBox = QtGui.QDialogButtonBox(JobTicketEditorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.lblTissueType.setBuddy(self.cmbTissueType)
        self.lblTissueDateTime.setBuddy(self.edtTissueDate)
        self.lblTissueExternalId.setBuddy(self.edtTissueExternalId)
        self.lblTissueNote.setBuddy(self.edtTissueNote)
        self.lblTissueAmount.setBuddy(self.edtTissueAmount)
        self.lblTissyeExecPerson.setBuddy(self.cmbTissueExecPerson)
        self.lblTissueUnit.setBuddy(self.cmbTissueUnit)
        self.lblBegDateTime.setBuddy(self.edtBegDate)
        self.lblEndDatetime.setBuddy(self.edtEndDate)
        self.lblStatus.setBuddy(self.cmbStatus)
        self.lblLabel.setBuddy(self.edtLabel)
        self.lblNote.setBuddy(self.edtNote)

        self.retranslateUi(JobTicketEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), JobTicketEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), JobTicketEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(JobTicketEditorDialog)
        JobTicketEditorDialog.setTabOrder(self.cmbTissueType, self.edtTissueDate)
        JobTicketEditorDialog.setTabOrder(self.edtTissueDate, self.edtTissueTime)
        JobTicketEditorDialog.setTabOrder(self.edtTissueTime, self.cmbTissueExecPerson)
        JobTicketEditorDialog.setTabOrder(self.cmbTissueExecPerson, self.edtTissueAmount)
        JobTicketEditorDialog.setTabOrder(self.edtTissueAmount, self.cmbTissueUnit)
        JobTicketEditorDialog.setTabOrder(self.cmbTissueUnit, self.edtTissueExternalId)
        JobTicketEditorDialog.setTabOrder(self.edtTissueExternalId, self.btnPrintTissueLabel)
        JobTicketEditorDialog.setTabOrder(self.btnPrintTissueLabel, self.edtTissueNumber)
        JobTicketEditorDialog.setTabOrder(self.edtTissueNumber, self.edtTissueNote)
        JobTicketEditorDialog.setTabOrder(self.edtTissueNote, self.edtBegDate)
        JobTicketEditorDialog.setTabOrder(self.edtBegDate, self.edtBegTime)
        JobTicketEditorDialog.setTabOrder(self.edtBegTime, self.btnSetBegDateTime)
        JobTicketEditorDialog.setTabOrder(self.btnSetBegDateTime, self.edtEndDate)
        JobTicketEditorDialog.setTabOrder(self.edtEndDate, self.edtEndTime)
        JobTicketEditorDialog.setTabOrder(self.edtEndTime, self.btnSetEndDateTime)
        JobTicketEditorDialog.setTabOrder(self.btnSetEndDateTime, self.cmbStatus)
        JobTicketEditorDialog.setTabOrder(self.cmbStatus, self.edtLabel)
        JobTicketEditorDialog.setTabOrder(self.edtLabel, self.edtNote)
        JobTicketEditorDialog.setTabOrder(self.edtNote, self.tabWidget)
        JobTicketEditorDialog.setTabOrder(self.tabWidget, self.tblActions)
        JobTicketEditorDialog.setTabOrder(self.tblActions, self.tblProps)
        JobTicketEditorDialog.setTabOrder(self.tblProps, self.tblTreeProbe)
        JobTicketEditorDialog.setTabOrder(self.tblTreeProbe, self.buttonBox)

    def retranslateUi(self, JobTicketEditorDialog):
        JobTicketEditorDialog.setWindowTitle(_translate("JobTicketEditorDialog", "ChangeMe!", None))
        self.txtClientInfoBrowser.setHtml(_translate("JobTicketEditorDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.grpTissue.setTitle(_translate("JobTicketEditorDialog", "Биоматериал", None))
        self.lblTissueType.setText(_translate("JobTicketEditorDialog", "Тип биоматериала", None))
        self.lblTissueDateTime.setText(_translate("JobTicketEditorDialog", "Дата и время", None))
        self.lblTissueExternalId.setText(_translate("JobTicketEditorDialog", "&Идентификатор", None))
        self.lblTissueNote.setText(_translate("JobTicketEditorDialog", "Примечание", None))
        self.lblTissueAmount.setText(_translate("JobTicketEditorDialog", "Количество", None))
        self.lblTissyeExecPerson.setText(_translate("JobTicketEditorDialog", "Исполнитель", None))
        self.lblTissueUnit.setText(_translate("JobTicketEditorDialog", "Ед. измерения", None))
        self.lblTissueNumber.setText(_translate("JobTicketEditorDialog", "Номер", None))
        self.btnPrintTissueLabel.setText(_translate("JobTicketEditorDialog", "...", None))
        self.grpMain.setTitle(_translate("JobTicketEditorDialog", "Основная информация", None))
        self.lblDatetime.setText(_translate("JobTicketEditorDialog", "Плановые дата и время", None))
        self.lblDatetimeValue.setText(_translate("JobTicketEditorDialog", "01.12.2009 19:30", None))
        self.lblBegDateTime.setText(_translate("JobTicketEditorDialog", "Дата и время начала выполнения", None))
        self.edtBegTime.setDisplayFormat(_translate("JobTicketEditorDialog", "HH:mm", None))
        self.btnSetBegDateTime.setText(_translate("JobTicketEditorDialog", "...", None))
        self.lblOrgStructure.setText(_translate("JobTicketEditorDialog", "Подразделение", None))
        self.lblOrgStructureValue.setText(_translate("JobTicketEditorDialog", "Лаборатория", None))
        self.lblEndDatetime.setText(_translate("JobTicketEditorDialog", "Дата и время окончания выполнения", None))
        self.edtEndTime.setDisplayFormat(_translate("JobTicketEditorDialog", "HH:mm", None))
        self.btnSetEndDateTime.setText(_translate("JobTicketEditorDialog", "...", None))
        self.lblJobType.setText(_translate("JobTicketEditorDialog", "Работа", None))
        self.lblJobTypeValue.setText(_translate("JobTicketEditorDialog", "анализ крови", None))
        self.lblStatus.setText(_translate("JobTicketEditorDialog", "Состояние", None))
        self.cmbStatus.setItemText(0, _translate("JobTicketEditorDialog", "Ожидание", None))
        self.cmbStatus.setItemText(1, _translate("JobTicketEditorDialog", "Выполняется", None))
        self.cmbStatus.setItemText(2, _translate("JobTicketEditorDialog", "Закончено", None))
        self.lblLabel.setText(_translate("JobTicketEditorDialog", "Отметка", None))
        self.lblNote.setText(_translate("JobTicketEditorDialog", "Примечание", None))
        self.btnSaveAsTemplate.setText(_translate("JobTicketEditorDialog", "Сохранить шаблон", None))
        self.btnCloneValues.setText(_translate("JobTicketEditorDialog", "Размножить значения свойств", None))
        self.btnFillPropertiesValue.setText(_translate("JobTicketEditorDialog", "Заполнить значения проб", None))
        self.btnEditEvent.setText(_translate("JobTicketEditorDialog", "Перейти в обращение", None))
        self.btnAmbCard.setText(_translate("JobTicketEditorDialog", "Медицинская карта", None))
        self.btnShowSnapshots.setText(_translate("JobTicketEditorDialog", "Показать снимки", None))
        self.btnFindSnapshots.setText(_translate("JobTicketEditorDialog", "Поиск снимков", None))
        self.btnLoadTemplate.setText(_translate("JobTicketEditorDialog", "Загрузить шаблон", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabActions), _translate("JobTicketEditorDialog", "&Действия", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProbes), _translate("JobTicketEditorDialog", "&Пробы", None))

from Events.ActionPropertiesTable import CActionPropertiesTableView
from Events.ActionTemplateChoose import CActionTemplateChooseButton
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Resources.JobTicketProbeModel import CJobTicketProbeTreeView
from library.DateEdit import CDateEdit
from library.TableView import CTableView
from library.TextBrowser import CTextBrowser
from library.crbcombobox import CRBComboBox
