# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PreF025.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PreF025Dialog(object):
    def setupUi(self, PreF025Dialog):
        PreF025Dialog.setObjectName(_fromUtf8("PreF025Dialog"))
        PreF025Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PreF025Dialog.resize(456, 515)
        self.verticalLayout = QtGui.QVBoxLayout(PreF025Dialog)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.grpContract = QtGui.QWidget(PreF025Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpContract.sizePolicy().hasHeightForWidth())
        self.grpContract.setSizePolicy(sizePolicy)
        self.grpContract.setObjectName(_fromUtf8("grpContract"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.grpContract)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblContract = QtGui.QLabel(self.grpContract)
        self.lblContract.setObjectName(_fromUtf8("lblContract"))
        self.horizontalLayout.addWidget(self.lblContract)
        self.cmbContract = CContractComboBox(self.grpContract)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbContract.sizePolicy().hasHeightForWidth())
        self.cmbContract.setSizePolicy(sizePolicy)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.cmbContract.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cmbContract)
        spacerItem = QtGui.QSpacerItem(613, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lblSum = QtGui.QLabel(self.grpContract)
        self.lblSum.setObjectName(_fromUtf8("lblSum"))
        self.horizontalLayout.addWidget(self.lblSum)
        self.lblSumValue = QtGui.QLabel(self.grpContract)
        self.lblSumValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblSumValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblSumValue.setTextFormat(QtCore.Qt.PlainText)
        self.lblSumValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSumValue.setObjectName(_fromUtf8("lblSumValue"))
        self.horizontalLayout.addWidget(self.lblSumValue)
        self.verticalLayout.addWidget(self.grpContract)
        self.splitter = QtGui.QSplitter(PreF025Dialog)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.grpInspections = QtGui.QGroupBox(self.splitter)
        self.grpInspections.setObjectName(_fromUtf8("grpInspections"))
        self.gridLayout = QtGui.QGridLayout(self.grpInspections)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tblDiagnostics = CInDocTableView(self.grpInspections)
        self.tblDiagnostics.setObjectName(_fromUtf8("tblDiagnostics"))
        self.gridLayout.addWidget(self.tblDiagnostics, 0, 0, 1, 3)
        self.btnSelectVisits = QtGui.QPushButton(self.grpInspections)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectVisits.sizePolicy().hasHeightForWidth())
        self.btnSelectVisits.setSizePolicy(sizePolicy)
        self.btnSelectVisits.setMinimumSize(QtCore.QSize(100, 0))
        self.btnSelectVisits.setAutoDefault(False)
        self.btnSelectVisits.setObjectName(_fromUtf8("btnSelectVisits"))
        self.gridLayout.addWidget(self.btnSelectVisits, 1, 0, 1, 1)
        self.btnDeselectVisits = QtGui.QPushButton(self.grpInspections)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeselectVisits.sizePolicy().hasHeightForWidth())
        self.btnDeselectVisits.setSizePolicy(sizePolicy)
        self.btnDeselectVisits.setMinimumSize(QtCore.QSize(100, 0))
        self.btnDeselectVisits.setAutoDefault(False)
        self.btnDeselectVisits.setObjectName(_fromUtf8("btnDeselectVisits"))
        self.gridLayout.addWidget(self.btnDeselectVisits, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(343, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.grpActions = QtGui.QGroupBox(self.splitter)
        self.grpActions.setObjectName(_fromUtf8("grpActions"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpActions)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblActions = CInDocTableView(self.grpActions)
        self.tblActions.setObjectName(_fromUtf8("tblActions"))
        self.gridLayout_2.addWidget(self.tblActions, 0, 0, 1, 3)
        self.btnSelectActions = QtGui.QPushButton(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectActions.sizePolicy().hasHeightForWidth())
        self.btnSelectActions.setSizePolicy(sizePolicy)
        self.btnSelectActions.setMinimumSize(QtCore.QSize(100, 0))
        self.btnSelectActions.setAutoDefault(False)
        self.btnSelectActions.setObjectName(_fromUtf8("btnSelectActions"))
        self.gridLayout_2.addWidget(self.btnSelectActions, 1, 0, 1, 1)
        self.btnDeselectActions = QtGui.QPushButton(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeselectActions.sizePolicy().hasHeightForWidth())
        self.btnDeselectActions.setSizePolicy(sizePolicy)
        self.btnDeselectActions.setMinimumSize(QtCore.QSize(100, 0))
        self.btnDeselectActions.setAutoDefault(False)
        self.btnDeselectActions.setObjectName(_fromUtf8("btnDeselectActions"))
        self.gridLayout_2.addWidget(self.btnDeselectActions, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(343, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.splitter)
        self.buttonBox = QtGui.QDialogButtonBox(PreF025Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PreF025Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PreF025Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PreF025Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreF025Dialog)
        PreF025Dialog.setTabOrder(self.cmbContract, self.tblDiagnostics)
        PreF025Dialog.setTabOrder(self.tblDiagnostics, self.btnSelectVisits)
        PreF025Dialog.setTabOrder(self.btnSelectVisits, self.btnDeselectVisits)
        PreF025Dialog.setTabOrder(self.btnDeselectVisits, self.tblActions)
        PreF025Dialog.setTabOrder(self.tblActions, self.btnSelectActions)
        PreF025Dialog.setTabOrder(self.btnSelectActions, self.btnDeselectActions)
        PreF025Dialog.setTabOrder(self.btnDeselectActions, self.buttonBox)

    def retranslateUi(self, PreF025Dialog):
        PreF025Dialog.setWindowTitle(_translate("PreF025Dialog", "Dialog", None))
        self.lblContract.setText(_translate("PreF025Dialog", "Договор", None))
        self.cmbContract.setWhatsThis(_translate("PreF025Dialog", "номер, дата и основание договора в рамках которого производится осмотр", None))
        self.cmbContract.setItemText(0, _translate("PreF025Dialog", "Договор", None))
        self.lblSum.setText(_translate("PreF025Dialog", "Сумма:", None))
        self.lblSumValue.setText(_translate("PreF025Dialog", "0.00", None))
        self.grpInspections.setTitle(_translate("PreF025Dialog", "Осмотры", None))
        self.btnSelectVisits.setText(_translate("PreF025Dialog", "Выбрать всё", None))
        self.btnDeselectVisits.setText(_translate("PreF025Dialog", "Очистить выбор", None))
        self.grpActions.setTitle(_translate("PreF025Dialog", "Мероприятия", None))
        self.btnSelectActions.setText(_translate("PreF025Dialog", "Выбрать всё", None))
        self.btnDeselectActions.setText(_translate("PreF025Dialog", "Очистить выбор", None))

from Orgs.OrgComboBox import CContractComboBox
from library.InDocTable import CInDocTableView
