# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\preferences\calendar.ui'
#
# Created: Fri Jun 15 12:15:34 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(846, 578)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setMargin(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.calendarHoliday = CCalendarWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarHoliday.sizePolicy().hasHeightForWidth())
        self.calendarHoliday.setSizePolicy(sizePolicy)
        self.calendarHoliday.setMinimumSize(QtCore.QSize(300, 0))
        self.calendarHoliday.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarHoliday.setGridVisible(True)
        self.calendarHoliday.setObjectName(_fromUtf8("calendarHoliday"))
        self.horizontalLayout.addWidget(self.calendarHoliday)
        self.tableHoliday = CTableView(self.tab)
        self.tableHoliday.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableHoliday.setObjectName(_fromUtf8("tableHoliday"))
        self.horizontalLayout.addWidget(self.tableHoliday)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setMargin(4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.calendarChangeday = CCalendarWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarChangeday.sizePolicy().hasHeightForWidth())
        self.calendarChangeday.setSizePolicy(sizePolicy)
        self.calendarChangeday.setMinimumSize(QtCore.QSize(300, 0))
        self.calendarChangeday.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarChangeday.setGridVisible(True)
        self.calendarChangeday.setObjectName(_fromUtf8("calendarChangeday"))
        self.horizontalLayout_3.addWidget(self.calendarChangeday)
        self.tableChangeday = CTableView(self.tab_2)
        self.tableChangeday.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableChangeday.setObjectName(_fromUtf8("tableChangeday"))
        self.horizontalLayout_3.addWidget(self.tableChangeday)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 4)
        spacerItem = QtGui.QSpacerItem(577, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.buttonEdit = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEdit.sizePolicy().hasHeightForWidth())
        self.buttonEdit.setSizePolicy(sizePolicy)
        self.buttonEdit.setDefault(True)
        self.buttonEdit.setObjectName(_fromUtf8("buttonEdit"))
        self.gridLayout.addWidget(self.buttonEdit, 1, 1, 1, 1)
        self.buttonAdd = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAdd.sizePolicy().hasHeightForWidth())
        self.buttonAdd.setSizePolicy(sizePolicy)
        self.buttonAdd.setAutoDefault(False)
        self.buttonAdd.setObjectName(_fromUtf8("buttonAdd"))
        self.gridLayout.addWidget(self.buttonAdd, 1, 2, 1, 1)
        self.buttonClose = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonClose.sizePolicy().hasHeightForWidth())
        self.buttonClose.setSizePolicy(sizePolicy)
        self.buttonClose.setAutoDefault(False)
        self.buttonClose.setObjectName(_fromUtf8("buttonClose"))
        self.gridLayout.addWidget(self.buttonClose, 1, 3, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.calendarHoliday, QtCore.SIGNAL(_fromUtf8("currentPageChanged(int,int)")), Dialog.updateTable)
        QtCore.QObject.connect(self.calendarChangeday, QtCore.SIGNAL(_fromUtf8("currentPageChanged(int,int)")), Dialog.updateTable)
        QtCore.QObject.connect(self.tableHoliday, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), Dialog.updateCalendar)
        QtCore.QObject.connect(self.tableHoliday, QtCore.SIGNAL(_fromUtf8("activated(QModelIndex)")), Dialog.updateCalendar)
        QtCore.QObject.connect(self.tableHoliday, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), Dialog.edit)
        QtCore.QObject.connect(self.tableChangeday, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), Dialog.updateCalendar)
        QtCore.QObject.connect(self.tableChangeday, QtCore.SIGNAL(_fromUtf8("activated(QModelIndex)")), Dialog.updateCalendar)
        QtCore.QObject.connect(self.tableChangeday, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), Dialog.edit)
        QtCore.QObject.connect(self.buttonClose, QtCore.SIGNAL(_fromUtf8("pressed()")), Dialog.close)
        QtCore.QObject.connect(self.buttonAdd, QtCore.SIGNAL(_fromUtf8("pressed()")), Dialog.add)
        QtCore.QObject.connect(self.buttonEdit, QtCore.SIGNAL(_fromUtf8("pressed()")), Dialog.edit)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.calendarHoliday)
        Dialog.setTabOrder(self.calendarHoliday, self.tableHoliday)
        Dialog.setTabOrder(self.tableHoliday, self.calendarChangeday)
        Dialog.setTabOrder(self.calendarChangeday, self.tableChangeday)
        Dialog.setTabOrder(self.tableChangeday, self.buttonEdit)
        Dialog.setTabOrder(self.buttonEdit, self.buttonAdd)
        Dialog.setTabOrder(self.buttonAdd, self.buttonClose)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Настройки календарных отклонений", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Праздники", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Переносы", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonEdit.setText(QtGui.QApplication.translate("Dialog", "F4 правка", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonEdit.setShortcut(QtGui.QApplication.translate("Dialog", "F4", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAdd.setText(QtGui.QApplication.translate("Dialog", "F9 вставка", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAdd.setShortcut(QtGui.QApplication.translate("Dialog", "F9", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonClose.setText(QtGui.QApplication.translate("Dialog", "Закрыть", None, QtGui.QApplication.UnicodeUTF8))

from library.TableView import CTableView
from library.calendar import CCalendarWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

