# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\Quoting\ClientQuotingComboBoxPopup.ui'
#
# Created: Fri Jun 15 12:17:34 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(473, 300)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabQuoting = QtGui.QWidget()
        self.tabQuoting.setObjectName(_fromUtf8("tabQuoting"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabQuoting)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblClientQuoting = CTableView(self.tabQuoting)
        self.tblClientQuoting.setObjectName(_fromUtf8("tblClientQuoting"))
        self.gridLayout_2.addWidget(self.tblClientQuoting, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabQuoting, _fromUtf8(""))
        self.tabFind = QtGui.QWidget()
        self.tabFind.setObjectName(_fromUtf8("tabFind"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabFind)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pnlDates = QtGui.QWidget(self.tabFind)
        self.pnlDates.setObjectName(_fromUtf8("pnlDates"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.pnlDates)
        self.horizontalLayout.setSpacing(-1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkBegDate = QtGui.QCheckBox(self.pnlDates)
        self.chkBegDate.setObjectName(_fromUtf8("chkBegDate"))
        self.horizontalLayout.addWidget(self.chkBegDate)
        self.edtBegDate = CDateEdit(self.pnlDates)
        self.edtBegDate.setEnabled(False)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout.addWidget(self.edtBegDate)
        self.lblEndDate = QtGui.QLabel(self.pnlDates)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.horizontalLayout.addWidget(self.lblEndDate)
        self.edtEndDate = CDateEdit(self.pnlDates)
        self.edtEndDate.setEnabled(False)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout.addWidget(self.edtEndDate)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_3.addWidget(self.pnlDates, 1, 0, 1, 2)
        self.chkStatus = QtGui.QCheckBox(self.tabFind)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkStatus.sizePolicy().hasHeightForWidth())
        self.chkStatus.setSizePolicy(sizePolicy)
        self.chkStatus.setObjectName(_fromUtf8("chkStatus"))
        self.gridLayout_3.addWidget(self.chkStatus, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 5, 0, 1, 2)
        self.cmbStatus = QtGui.QComboBox(self.tabFind)
        self.cmbStatus.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbStatus.sizePolicy().hasHeightForWidth())
        self.cmbStatus.setSizePolicy(sizePolicy)
        self.cmbStatus.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbStatus.setObjectName(_fromUtf8("cmbStatus"))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbStatus, 3, 1, 1, 1)
        self.pnlButtonBox = QtGui.QWidget(self.tabFind)
        self.pnlButtonBox.setObjectName(_fromUtf8("pnlButtonBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.pnlButtonBox)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonBox = QtGui.QDialogButtonBox(self.pnlButtonBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.gridLayout_3.addWidget(self.pnlButtonBox, 6, 0, 1, 2)
        self.chkClass = QtGui.QCheckBox(self.tabFind)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkClass.sizePolicy().hasHeightForWidth())
        self.chkClass.setSizePolicy(sizePolicy)
        self.chkClass.setChecked(True)
        self.chkClass.setObjectName(_fromUtf8("chkClass"))
        self.gridLayout_3.addWidget(self.chkClass, 0, 0, 1, 1)
        self.cmbClass = QtGui.QComboBox(self.tabFind)
        self.cmbClass.setObjectName(_fromUtf8("cmbClass"))
        self.gridLayout_3.addWidget(self.cmbClass, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tabFind, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.chkClass, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbClass.setEnabled)
        QtCore.QObject.connect(self.chkStatus, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbStatus.setEnabled)
        QtCore.QObject.connect(self.chkBegDate, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtBegDate.setEnabled)
        QtCore.QObject.connect(self.chkBegDate, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtEndDate.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabQuoting), QtGui.QApplication.translate("Form", "&Квоты", None, QtGui.QApplication.UnicodeUTF8))
        self.chkBegDate.setText(QtGui.QApplication.translate("Form", "Период действия с: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndDate.setText(QtGui.QApplication.translate("Form", "по: ", None, QtGui.QApplication.UnicodeUTF8))
        self.chkStatus.setText(QtGui.QApplication.translate("Form", "Статус", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbStatus.setItemText(0, QtGui.QApplication.translate("Form", "Отменено", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbStatus.setItemText(1, QtGui.QApplication.translate("Form", "Ожидание", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbStatus.setItemText(2, QtGui.QApplication.translate("Form", "Активный талон", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbStatus.setItemText(3, QtGui.QApplication.translate("Form", "Талон для заполнения", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbStatus.setItemText(4, QtGui.QApplication.translate("Form", "Заблокированный талон", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbStatus.setItemText(5, QtGui.QApplication.translate("Form", "Отказано", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbStatus.setItemText(6, QtGui.QApplication.translate("Form", "Необходимо согласовать дату обслуживания", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbStatus.setItemText(7, QtGui.QApplication.translate("Form", "Дата обслуживания на согласовании", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbStatus.setItemText(8, QtGui.QApplication.translate("Form", "Дата обслуживания согласована", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbStatus.setItemText(9, QtGui.QApplication.translate("Form", "Пролечен", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbStatus.setItemText(10, QtGui.QApplication.translate("Form", "Обслуживание отложено", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbStatus.setItemText(11, QtGui.QApplication.translate("Form", "Отказ пациента", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbStatus.setItemText(12, QtGui.QApplication.translate("Form", "Импортировано из ВТМП", None, QtGui.QApplication.UnicodeUTF8))
        self.chkClass.setText(QtGui.QApplication.translate("Form", "Класс", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFind), QtGui.QApplication.translate("Form", "&Поиск", None, QtGui.QApplication.UnicodeUTF8))

from library.TableView import CTableView
from library.DateEdit import CDateEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

