# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\Quoting\QuotingDialog.ui'
#
# Created: Fri Jun 15 12:16:57 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_QuotingDialog(object):
    def setupUi(self, QuotingDialog):
        QuotingDialog.setObjectName(_fromUtf8("QuotingDialog"))
        QuotingDialog.resize(549, 847)
        self.gridLayout_3 = QtGui.QGridLayout(QuotingDialog)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter_3 = QtGui.QSplitter(QuotingDialog)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setOpaqueResize(True)
        self.splitter_3.setChildrenCollapsible(False)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.splitter_3)
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.horizontalLayoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.calendar = CCalendarWidget(self.splitter)
        self.calendar.setObjectName(_fromUtf8("calendar"))
        self.treeQuotaType = CTreeView(self.splitter)
        self.treeQuotaType.setObjectName(_fromUtf8("treeQuotaType"))
        self.tblQuotaTypeLeaves = CTableView(self.splitter)
        self.tblQuotaTypeLeaves.setObjectName(_fromUtf8("tblQuotaTypeLeaves"))
        self.horizontalLayout.addWidget(self.splitter)
        self.tabWidgetContent = QtGui.QTabWidget(self.splitter_3)
        self.tabWidgetContent.setEnabled(True)
        self.tabWidgetContent.setObjectName(_fromUtf8("tabWidgetContent"))
        self.tabLimits = QtGui.QWidget()
        self.tabLimits.setObjectName(_fromUtf8("tabLimits"))
        self.gridLayout = QtGui.QGridLayout(self.tabLimits)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblInfo = QtGui.QLabel(self.tabLimits)
        self.lblInfo.setText(_fromUtf8(""))
        self.lblInfo.setObjectName(_fromUtf8("lblInfo"))
        self.gridLayout.addWidget(self.lblInfo, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(336, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.btnEditQuota = QtGui.QPushButton(self.tabLimits)
        self.btnEditQuota.setObjectName(_fromUtf8("btnEditQuota"))
        self.gridLayout.addWidget(self.btnEditQuota, 2, 1, 1, 1)
        self.btnProlongateQuota = QtGui.QPushButton(self.tabLimits)
        self.btnProlongateQuota.setObjectName(_fromUtf8("btnProlongateQuota"))
        self.gridLayout.addWidget(self.btnProlongateQuota, 2, 2, 1, 1)
        self.btnNewQuota = QtGui.QPushButton(self.tabLimits)
        self.btnNewQuota.setObjectName(_fromUtf8("btnNewQuota"))
        self.gridLayout.addWidget(self.btnNewQuota, 2, 3, 1, 1)
        self.btnClose = QtGui.QPushButton(self.tabLimits)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.gridLayout.addWidget(self.btnClose, 2, 4, 1, 1)
        self.splitter_2 = QtGui.QSplitter(self.tabLimits)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.tblQuoting = CTableView(self.splitter_2)
        self.tblQuoting.setObjectName(_fromUtf8("tblQuoting"))
        self.tabWidgetLimitation = QtGui.QTabWidget(self.splitter_2)
        self.tabWidgetLimitation.setObjectName(_fromUtf8("tabWidgetLimitation"))
        self.tabRegion = QtGui.QWidget()
        self.tabRegion.setObjectName(_fromUtf8("tabRegion"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabRegion)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblQuoting_Region = CInDocTableView(self.tabRegion)
        self.tblQuoting_Region.setObjectName(_fromUtf8("tblQuoting_Region"))
        self.gridLayout_2.addWidget(self.tblQuoting_Region, 0, 0, 1, 1)
        self.tabWidgetLimitation.addTab(self.tabRegion, _fromUtf8(""))
        self.tabInsurance = QtGui.QWidget()
        self.tabInsurance.setEnabled(True)
        self.tabInsurance.setObjectName(_fromUtf8("tabInsurance"))
        self.tabWidgetLimitation.addTab(self.tabInsurance, _fromUtf8(""))
        self.tabFinanceSource = QtGui.QWidget()
        self.tabFinanceSource.setObjectName(_fromUtf8("tabFinanceSource"))
        self.tabWidgetLimitation.addTab(self.tabFinanceSource, _fromUtf8(""))
        self.tabSocialStatus = QtGui.QWidget()
        self.tabSocialStatus.setObjectName(_fromUtf8("tabSocialStatus"))
        self.tabWidgetLimitation.addTab(self.tabSocialStatus, _fromUtf8(""))
        self.tabSexAndAge = QtGui.QWidget()
        self.tabSexAndAge.setObjectName(_fromUtf8("tabSexAndAge"))
        self.tabWidgetLimitation.addTab(self.tabSexAndAge, _fromUtf8(""))
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 5)
        self.tabWidgetContent.addTab(self.tabLimits, _fromUtf8(""))
        self.tabList = QtGui.QWidget()
        self.tabList.setEnabled(True)
        self.tabList.setObjectName(_fromUtf8("tabList"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabList)
        self.verticalLayout_5.setSpacing(4)
        self.verticalLayout_5.setMargin(4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.splitter_4 = QtGui.QSplitter(self.tabList)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setChildrenCollapsible(False)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.splitter_4)
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.verticalLayoutWidget_4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tblPeopleList = CTableView(self.verticalLayoutWidget_4)
        self.tblPeopleList.setObjectName(_fromUtf8("tblPeopleList"))
        self.gridLayout_5.addWidget(self.tblPeopleList, 0, 0, 1, 2)
        self.btnPrint = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.btnPrint.setObjectName(_fromUtf8("btnPrint"))
        self.gridLayout_5.addWidget(self.btnPrint, 2, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 2, 0, 1, 1)
        self.lblPersonListCount = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.lblPersonListCount.setObjectName(_fromUtf8("lblPersonListCount"))
        self.gridLayout_5.addWidget(self.lblPersonListCount, 1, 0, 1, 2)
        self.widget = QtGui.QWidget(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.chkFilterLastName = QtGui.QCheckBox(self.widget)
        self.chkFilterLastName.setObjectName(_fromUtf8("chkFilterLastName"))
        self.gridLayout_4.addWidget(self.chkFilterLastName, 0, 0, 1, 3)
        self.edtFilterLastName = QtGui.QLineEdit(self.widget)
        self.edtFilterLastName.setEnabled(False)
        self.edtFilterLastName.setObjectName(_fromUtf8("edtFilterLastName"))
        self.gridLayout_4.addWidget(self.edtFilterLastName, 1, 0, 1, 3)
        self.chkFilterFirstName = QtGui.QCheckBox(self.widget)
        self.chkFilterFirstName.setObjectName(_fromUtf8("chkFilterFirstName"))
        self.gridLayout_4.addWidget(self.chkFilterFirstName, 2, 0, 1, 2)
        self.edtFilterFirstName = QtGui.QLineEdit(self.widget)
        self.edtFilterFirstName.setEnabled(False)
        self.edtFilterFirstName.setObjectName(_fromUtf8("edtFilterFirstName"))
        self.gridLayout_4.addWidget(self.edtFilterFirstName, 3, 0, 1, 3)
        self.chkFilterPatrName = QtGui.QCheckBox(self.widget)
        self.chkFilterPatrName.setObjectName(_fromUtf8("chkFilterPatrName"))
        self.gridLayout_4.addWidget(self.chkFilterPatrName, 4, 0, 1, 3)
        self.edtFilterPatrName = QtGui.QLineEdit(self.widget)
        self.edtFilterPatrName.setEnabled(False)
        self.edtFilterPatrName.setObjectName(_fromUtf8("edtFilterPatrName"))
        self.gridLayout_4.addWidget(self.edtFilterPatrName, 5, 0, 1, 3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.chkFilterSex = QtGui.QCheckBox(self.widget)
        self.chkFilterSex.setObjectName(_fromUtf8("chkFilterSex"))
        self.horizontalLayout_2.addWidget(self.chkFilterSex)
        self.cmbFilterSex = QtGui.QComboBox(self.widget)
        self.cmbFilterSex.setEnabled(False)
        self.cmbFilterSex.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cmbFilterSex.setObjectName(_fromUtf8("cmbFilterSex"))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.cmbFilterSex.setItemText(0, _fromUtf8(""))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cmbFilterSex)
        self.chkFilterAge = QtGui.QCheckBox(self.widget)
        self.chkFilterAge.setObjectName(_fromUtf8("chkFilterAge"))
        self.horizontalLayout_2.addWidget(self.chkFilterAge)
        self.edtFilterBegAge = QtGui.QSpinBox(self.widget)
        self.edtFilterBegAge.setEnabled(False)
        self.edtFilterBegAge.setMaximum(150)
        self.edtFilterBegAge.setObjectName(_fromUtf8("edtFilterBegAge"))
        self.horizontalLayout_2.addWidget(self.edtFilterBegAge)
        self.edtFilterEndAge = QtGui.QSpinBox(self.widget)
        self.edtFilterEndAge.setEnabled(False)
        self.edtFilterEndAge.setMaximum(150)
        self.edtFilterEndAge.setProperty("value", 150)
        self.edtFilterEndAge.setObjectName(_fromUtf8("edtFilterEndAge"))
        self.horizontalLayout_2.addWidget(self.edtFilterEndAge)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 6, 0, 1, 3)
        self.chkFilterAddress = QtGui.QCheckBox(self.widget)
        self.chkFilterAddress.setObjectName(_fromUtf8("chkFilterAddress"))
        self.gridLayout_4.addWidget(self.chkFilterAddress, 8, 0, 1, 1)
        self.cmbFilterAddressType = QtGui.QComboBox(self.widget)
        self.cmbFilterAddressType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressType.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressType.setSizePolicy(sizePolicy)
        self.cmbFilterAddressType.setObjectName(_fromUtf8("cmbFilterAddressType"))
        self.cmbFilterAddressType.addItem(_fromUtf8(""))
        self.cmbFilterAddressType.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbFilterAddressType, 8, 1, 1, 2)
        self.cmbFilterAddressCity = CKLADRComboBox(self.widget)
        self.cmbFilterAddressCity.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressCity.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressCity.setSizePolicy(sizePolicy)
        self.cmbFilterAddressCity.setObjectName(_fromUtf8("cmbFilterAddressCity"))
        self.gridLayout_4.addWidget(self.cmbFilterAddressCity, 9, 0, 1, 3)
        self.cmbFilterAddressStreet = CStreetComboBox(self.widget)
        self.cmbFilterAddressStreet.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressStreet.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressStreet.setSizePolicy(sizePolicy)
        self.cmbFilterAddressStreet.setObjectName(_fromUtf8("cmbFilterAddressStreet"))
        self.gridLayout_4.addWidget(self.cmbFilterAddressStreet, 10, 0, 1, 3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.chkFilterStatus = QtGui.QCheckBox(self.widget)
        self.chkFilterStatus.setObjectName(_fromUtf8("chkFilterStatus"))
        self.verticalLayout_3.addWidget(self.chkFilterStatus)
        self.cmbFilterStatus = QtGui.QComboBox(self.widget)
        self.cmbFilterStatus.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterStatus.sizePolicy().hasHeightForWidth())
        self.cmbFilterStatus.setSizePolicy(sizePolicy)
        self.cmbFilterStatus.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbFilterStatus.setObjectName(_fromUtf8("cmbFilterStatus"))
        self.cmbFilterStatus.addItem(_fromUtf8(""))
        self.cmbFilterStatus.addItem(_fromUtf8(""))
        self.cmbFilterStatus.addItem(_fromUtf8(""))
        self.cmbFilterStatus.addItem(_fromUtf8(""))
        self.cmbFilterStatus.addItem(_fromUtf8(""))
        self.cmbFilterStatus.addItem(_fromUtf8(""))
        self.cmbFilterStatus.addItem(_fromUtf8(""))
        self.cmbFilterStatus.addItem(_fromUtf8(""))
        self.cmbFilterStatus.addItem(_fromUtf8(""))
        self.cmbFilterStatus.addItem(_fromUtf8(""))
        self.cmbFilterStatus.addItem(_fromUtf8(""))
        self.cmbFilterStatus.addItem(_fromUtf8(""))
        self.cmbFilterStatus.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.cmbFilterStatus)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.chkFilterStage = QtGui.QCheckBox(self.widget)
        self.chkFilterStage.setObjectName(_fromUtf8("chkFilterStage"))
        self.verticalLayout_4.addWidget(self.chkFilterStage)
        self.edtFilterStage = QtGui.QSpinBox(self.widget)
        self.edtFilterStage.setEnabled(False)
        self.edtFilterStage.setObjectName(_fromUtf8("edtFilterStage"))
        self.verticalLayout_4.addWidget(self.edtFilterStage)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 12, 0, 1, 3)
        self.chkFilterOrgStructure = QtGui.QCheckBox(self.widget)
        self.chkFilterOrgStructure.setObjectName(_fromUtf8("chkFilterOrgStructure"))
        self.gridLayout_4.addWidget(self.chkFilterOrgStructure, 13, 0, 1, 3)
        self.cmbFilterOrgStructure = COrgStructureComboBox(self.widget)
        self.cmbFilterOrgStructure.setEnabled(False)
        self.cmbFilterOrgStructure.setObjectName(_fromUtf8("cmbFilterOrgStructure"))
        self.gridLayout_4.addWidget(self.cmbFilterOrgStructure, 14, 0, 1, 3)
        self.chkFilterContact = QtGui.QCheckBox(self.widget)
        self.chkFilterContact.setObjectName(_fromUtf8("chkFilterContact"))
        self.gridLayout_4.addWidget(self.chkFilterContact, 15, 0, 1, 3)
        self.edtFilterContact = QtGui.QLineEdit(self.widget)
        self.edtFilterContact.setEnabled(False)
        self.edtFilterContact.setObjectName(_fromUtf8("edtFilterContact"))
        self.gridLayout_4.addWidget(self.edtFilterContact, 16, 0, 1, 3)
        self.chkFilterIdentifier = QtGui.QCheckBox(self.widget)
        self.chkFilterIdentifier.setObjectName(_fromUtf8("chkFilterIdentifier"))
        self.gridLayout_4.addWidget(self.chkFilterIdentifier, 17, 0, 1, 3)
        self.edtFilterIdentifier = QtGui.QLineEdit(self.widget)
        self.edtFilterIdentifier.setEnabled(False)
        self.edtFilterIdentifier.setObjectName(_fromUtf8("edtFilterIdentifier"))
        self.gridLayout_4.addWidget(self.edtFilterIdentifier, 18, 0, 1, 3)
        self.chkFilterTicketNumber = QtGui.QCheckBox(self.widget)
        self.chkFilterTicketNumber.setObjectName(_fromUtf8("chkFilterTicketNumber"))
        self.gridLayout_4.addWidget(self.chkFilterTicketNumber, 19, 0, 1, 3)
        self.edtFilterTicketNumber = QtGui.QLineEdit(self.widget)
        self.edtFilterTicketNumber.setEnabled(False)
        self.edtFilterTicketNumber.setObjectName(_fromUtf8("edtFilterTicketNumber"))
        self.gridLayout_4.addWidget(self.edtFilterTicketNumber, 20, 0, 1, 3)
        self.chkFilterRequest = QtGui.QCheckBox(self.widget)
        self.chkFilterRequest.setObjectName(_fromUtf8("chkFilterRequest"))
        self.gridLayout_4.addWidget(self.chkFilterRequest, 21, 0, 1, 3)
        self.cmbFilterRequest = QtGui.QComboBox(self.widget)
        self.cmbFilterRequest.setEnabled(False)
        self.cmbFilterRequest.setObjectName(_fromUtf8("cmbFilterRequest"))
        self.cmbFilterRequest.addItem(_fromUtf8(""))
        self.cmbFilterRequest.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbFilterRequest, 22, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 23, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.buttonBox = CApplyResetDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 24, 0, 1, 3)
        self.chkFilterBirthDay = QtGui.QCheckBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterBirthDay.sizePolicy().hasHeightForWidth())
        self.chkFilterBirthDay.setSizePolicy(sizePolicy)
        self.chkFilterBirthDay.setObjectName(_fromUtf8("chkFilterBirthDay"))
        self.gridLayout_4.addWidget(self.chkFilterBirthDay, 7, 0, 1, 1)
        self.edtFilterBirthDay = CDateEdit(self.widget)
        self.edtFilterBirthDay.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterBirthDay.sizePolicy().hasHeightForWidth())
        self.edtFilterBirthDay.setSizePolicy(sizePolicy)
        self.edtFilterBirthDay.setCalendarPopup(True)
        self.edtFilterBirthDay.setObjectName(_fromUtf8("edtFilterBirthDay"))
        self.gridLayout_4.addWidget(self.edtFilterBirthDay, 7, 1, 1, 2)
        self.chkFilterClientQuotaKladr = QtGui.QCheckBox(self.widget)
        self.chkFilterClientQuotaKladr.setObjectName(_fromUtf8("chkFilterClientQuotaKladr"))
        self.gridLayout_4.addWidget(self.chkFilterClientQuotaKladr, 11, 0, 1, 1)
        self.cmbFilterClientQuotaKladr = CMainRegionsKLADRComboBox(self.widget)
        self.cmbFilterClientQuotaKladr.setObjectName(_fromUtf8("cmbFilterClientQuotaKladr"))
        self.gridLayout_4.addWidget(self.cmbFilterClientQuotaKladr, 11, 1, 1, 2)
        self.verticalLayout_5.addWidget(self.splitter_4)
        self.tabWidgetContent.addTab(self.tabList, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.splitter_3, 0, 0, 1, 1)

        self.retranslateUi(QuotingDialog)
        self.tabWidgetContent.setCurrentIndex(0)
        self.tabWidgetLimitation.setCurrentIndex(0)
        QtCore.QObject.connect(self.btnClose, QtCore.SIGNAL(_fromUtf8("clicked()")), QuotingDialog.close)
        QtCore.QObject.connect(self.chkFilterLastName, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtFilterLastName.setEnabled)
        QtCore.QObject.connect(self.chkFilterFirstName, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtFilterFirstName.setEnabled)
        QtCore.QObject.connect(self.chkFilterPatrName, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtFilterPatrName.setEnabled)
        QtCore.QObject.connect(self.chkFilterBirthDay, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtFilterBirthDay.setEnabled)
        QtCore.QObject.connect(self.chkFilterSex, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbFilterSex.setEnabled)
        QtCore.QObject.connect(self.chkFilterAge, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtFilterBegAge.setEnabled)
        QtCore.QObject.connect(self.chkFilterAge, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtFilterEndAge.setEnabled)
        QtCore.QObject.connect(self.chkFilterAddress, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbFilterAddressCity.setEnabled)
        QtCore.QObject.connect(self.chkFilterAddress, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbFilterAddressStreet.setEnabled)
        QtCore.QObject.connect(self.chkFilterStage, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtFilterStage.setEnabled)
        QtCore.QObject.connect(self.chkFilterStatus, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbFilterStatus.setEnabled)
        QtCore.QObject.connect(self.chkFilterOrgStructure, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbFilterOrgStructure.setEnabled)
        QtCore.QObject.connect(self.chkFilterContact, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtFilterContact.setEnabled)
        QtCore.QObject.connect(self.chkFilterIdentifier, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtFilterIdentifier.setEnabled)
        QtCore.QObject.connect(self.chkFilterTicketNumber, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtFilterTicketNumber.setEnabled)
        QtCore.QObject.connect(self.chkFilterRequest, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbFilterRequest.setEnabled)
        QtCore.QObject.connect(self.chkFilterAddress, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbFilterAddressType.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(QuotingDialog)
        QuotingDialog.setTabOrder(self.tabWidgetContent, self.calendar)
        QuotingDialog.setTabOrder(self.calendar, self.treeQuotaType)
        QuotingDialog.setTabOrder(self.treeQuotaType, self.tblQuotaTypeLeaves)
        QuotingDialog.setTabOrder(self.tblQuotaTypeLeaves, self.btnEditQuota)
        QuotingDialog.setTabOrder(self.btnEditQuota, self.btnProlongateQuota)
        QuotingDialog.setTabOrder(self.btnProlongateQuota, self.btnNewQuota)
        QuotingDialog.setTabOrder(self.btnNewQuota, self.btnClose)
        QuotingDialog.setTabOrder(self.btnClose, self.tblQuoting)
        QuotingDialog.setTabOrder(self.tblQuoting, self.tabWidgetLimitation)
        QuotingDialog.setTabOrder(self.tabWidgetLimitation, self.tblQuoting_Region)
        QuotingDialog.setTabOrder(self.tblQuoting_Region, self.tblPeopleList)
        QuotingDialog.setTabOrder(self.tblPeopleList, self.btnPrint)
        QuotingDialog.setTabOrder(self.btnPrint, self.chkFilterLastName)
        QuotingDialog.setTabOrder(self.chkFilterLastName, self.edtFilterLastName)
        QuotingDialog.setTabOrder(self.edtFilterLastName, self.chkFilterFirstName)
        QuotingDialog.setTabOrder(self.chkFilterFirstName, self.edtFilterFirstName)
        QuotingDialog.setTabOrder(self.edtFilterFirstName, self.chkFilterPatrName)
        QuotingDialog.setTabOrder(self.chkFilterPatrName, self.edtFilterPatrName)
        QuotingDialog.setTabOrder(self.edtFilterPatrName, self.chkFilterSex)
        QuotingDialog.setTabOrder(self.chkFilterSex, self.cmbFilterSex)
        QuotingDialog.setTabOrder(self.cmbFilterSex, self.chkFilterAge)
        QuotingDialog.setTabOrder(self.chkFilterAge, self.edtFilterBegAge)
        QuotingDialog.setTabOrder(self.edtFilterBegAge, self.edtFilterEndAge)
        QuotingDialog.setTabOrder(self.edtFilterEndAge, self.chkFilterBirthDay)
        QuotingDialog.setTabOrder(self.chkFilterBirthDay, self.edtFilterBirthDay)
        QuotingDialog.setTabOrder(self.edtFilterBirthDay, self.chkFilterAddress)
        QuotingDialog.setTabOrder(self.chkFilterAddress, self.cmbFilterAddressType)
        QuotingDialog.setTabOrder(self.cmbFilterAddressType, self.cmbFilterAddressCity)
        QuotingDialog.setTabOrder(self.cmbFilterAddressCity, self.cmbFilterAddressStreet)
        QuotingDialog.setTabOrder(self.cmbFilterAddressStreet, self.chkFilterStatus)
        QuotingDialog.setTabOrder(self.chkFilterStatus, self.cmbFilterStatus)
        QuotingDialog.setTabOrder(self.cmbFilterStatus, self.chkFilterStage)
        QuotingDialog.setTabOrder(self.chkFilterStage, self.edtFilterStage)
        QuotingDialog.setTabOrder(self.edtFilterStage, self.chkFilterOrgStructure)
        QuotingDialog.setTabOrder(self.chkFilterOrgStructure, self.cmbFilterOrgStructure)
        QuotingDialog.setTabOrder(self.cmbFilterOrgStructure, self.chkFilterContact)
        QuotingDialog.setTabOrder(self.chkFilterContact, self.edtFilterContact)
        QuotingDialog.setTabOrder(self.edtFilterContact, self.chkFilterIdentifier)
        QuotingDialog.setTabOrder(self.chkFilterIdentifier, self.edtFilterIdentifier)
        QuotingDialog.setTabOrder(self.edtFilterIdentifier, self.chkFilterTicketNumber)
        QuotingDialog.setTabOrder(self.chkFilterTicketNumber, self.edtFilterTicketNumber)
        QuotingDialog.setTabOrder(self.edtFilterTicketNumber, self.chkFilterRequest)
        QuotingDialog.setTabOrder(self.chkFilterRequest, self.cmbFilterRequest)
        QuotingDialog.setTabOrder(self.cmbFilterRequest, self.buttonBox)

    def retranslateUi(self, QuotingDialog):
        QuotingDialog.setWindowTitle(QtGui.QApplication.translate("QuotingDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEditQuota.setText(QtGui.QApplication.translate("QuotingDialog", "Редактировать квоту", None, QtGui.QApplication.UnicodeUTF8))
        self.btnProlongateQuota.setText(QtGui.QApplication.translate("QuotingDialog", "Пролонгировать квоту", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNewQuota.setText(QtGui.QApplication.translate("QuotingDialog", "Добавить квоту", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClose.setText(QtGui.QApplication.translate("QuotingDialog", "Закрыть", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetLimitation.setTabText(self.tabWidgetLimitation.indexOf(self.tabRegion), QtGui.QApplication.translate("QuotingDialog", "Регион", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetLimitation.setTabText(self.tabWidgetLimitation.indexOf(self.tabInsurance), QtGui.QApplication.translate("QuotingDialog", "Страховка", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetLimitation.setTabText(self.tabWidgetLimitation.indexOf(self.tabFinanceSource), QtGui.QApplication.translate("QuotingDialog", "Источник финансирования", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetLimitation.setTabText(self.tabWidgetLimitation.indexOf(self.tabSocialStatus), QtGui.QApplication.translate("QuotingDialog", "Социальный статус", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetLimitation.setTabText(self.tabWidgetLimitation.indexOf(self.tabSexAndAge), QtGui.QApplication.translate("QuotingDialog", "Пол/Возраст", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetContent.setTabText(self.tabWidgetContent.indexOf(self.tabLimits), QtGui.QApplication.translate("QuotingDialog", "Лимиты", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPrint.setText(QtGui.QApplication.translate("QuotingDialog", "Печать", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPersonListCount.setText(QtGui.QApplication.translate("QuotingDialog", "Количество записей:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterLastName.setText(QtGui.QApplication.translate("QuotingDialog", "Фамилия", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterFirstName.setText(QtGui.QApplication.translate("QuotingDialog", "Имя", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterPatrName.setText(QtGui.QApplication.translate("QuotingDialog", "Отчество", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterSex.setText(QtGui.QApplication.translate("QuotingDialog", "Пол", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterSex.setItemText(1, QtGui.QApplication.translate("QuotingDialog", "М", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterSex.setItemText(2, QtGui.QApplication.translate("QuotingDialog", "Ж", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterAge.setText(QtGui.QApplication.translate("QuotingDialog", "Возраст", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterAddress.setText(QtGui.QApplication.translate("QuotingDialog", "Адрес", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterAddressType.setItemText(0, QtGui.QApplication.translate("QuotingDialog", "Регистрации", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterAddressType.setItemText(1, QtGui.QApplication.translate("QuotingDialog", "Проживания", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterStatus.setText(QtGui.QApplication.translate("QuotingDialog", "Статус", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterStatus.setItemText(0, QtGui.QApplication.translate("QuotingDialog", "Отменено", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterStatus.setItemText(1, QtGui.QApplication.translate("QuotingDialog", "Ожидание", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterStatus.setItemText(2, QtGui.QApplication.translate("QuotingDialog", "Активный талон", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterStatus.setItemText(3, QtGui.QApplication.translate("QuotingDialog", "Талон для заполнения", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterStatus.setItemText(4, QtGui.QApplication.translate("QuotingDialog", "Заблокированный талон", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterStatus.setItemText(5, QtGui.QApplication.translate("QuotingDialog", "Отказано", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterStatus.setItemText(6, QtGui.QApplication.translate("QuotingDialog", "Необходимо согл-вать дату обсл.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterStatus.setItemText(7, QtGui.QApplication.translate("QuotingDialog", "Дата обслуживания на соглас.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterStatus.setItemText(8, QtGui.QApplication.translate("QuotingDialog", "Дата обслуживания согласована", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterStatus.setItemText(9, QtGui.QApplication.translate("QuotingDialog", "Пролечен", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterStatus.setItemText(10, QtGui.QApplication.translate("QuotingDialog", "Обслуживание отложено", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterStatus.setItemText(11, QtGui.QApplication.translate("QuotingDialog", "Отказ пациента", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterStatus.setItemText(12, QtGui.QApplication.translate("QuotingDialog", "Импортировано из ВТМП", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterStage.setText(QtGui.QApplication.translate("QuotingDialog", "Этап", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterOrgStructure.setText(QtGui.QApplication.translate("QuotingDialog", "Подразделение", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterContact.setText(QtGui.QApplication.translate("QuotingDialog", "Контакт", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterIdentifier.setText(QtGui.QApplication.translate("QuotingDialog", "Идентификатор", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterTicketNumber.setText(QtGui.QApplication.translate("QuotingDialog", "Номер талона", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterRequest.setText(QtGui.QApplication.translate("QuotingDialog", "Обращение", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterRequest.setItemText(0, QtGui.QApplication.translate("QuotingDialog", "Первичное", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFilterRequest.setItemText(1, QtGui.QApplication.translate("QuotingDialog", "Вторичное", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterBirthDay.setText(QtGui.QApplication.translate("QuotingDialog", "Дата рождения", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterClientQuotaKladr.setText(QtGui.QApplication.translate("QuotingDialog", "Прикрепление по квоте", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetContent.setTabText(self.tabWidgetContent.indexOf(self.tabList), QtGui.QApplication.translate("QuotingDialog", "Список", None, QtGui.QApplication.UnicodeUTF8))

from library.TreeView import CTreeView
from KLADR.kladrComboxes import CKLADRComboBox, CMainRegionsKLADRComboBox, CStreetComboBox
from library.InDocTable import CInDocTableView
from library.DialogButtonBox import CApplyResetDialogButtonBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.TableView import CTableView
from library.DateEdit import CDateEdit
from library.calendar import CCalendarWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    QuotingDialog = QtGui.QDialog()
    ui = Ui_QuotingDialog()
    ui.setupUi(QuotingDialog)
    QuotingDialog.show()
    sys.exit(app.exec_())

