# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F02512.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(926, 570)
        Dialog.setSizeGripEnabled(True)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.sptTopLevel = QtGui.QSplitter(Dialog)
        self.sptTopLevel.setOrientation(QtCore.Qt.Vertical)
        self.sptTopLevel.setObjectName(_fromUtf8("sptTopLevel"))
        self.txtClientInfoBrowser = CTextBrowser(self.sptTopLevel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtClientInfoBrowser.sizePolicy().hasHeightForWidth())
        self.txtClientInfoBrowser.setSizePolicy(sizePolicy)
        self.txtClientInfoBrowser.setMinimumSize(QtCore.QSize(0, 100))
        self.txtClientInfoBrowser.setMaximumSize(QtCore.QSize(16777215, 130))
        self.txtClientInfoBrowser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.tabWidget = QtGui.QTabWidget(self.sptTopLevel)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabToken = QtGui.QWidget()
        self.tabToken.setObjectName(_fromUtf8("tabToken"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabToken)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scrollArea = QtGui.QScrollArea(self.tabToken)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 877, 928))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.splitter_2 = QtGui.QSplitter(self.scrollAreaWidgetContents)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.frameBaseAndDiagnosises = QtGui.QFrame(self.splitter_2)
        self.frameBaseAndDiagnosises.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameBaseAndDiagnosises.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBaseAndDiagnosises.setObjectName(_fromUtf8("frameBaseAndDiagnosises"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frameBaseAndDiagnosises)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.grpBase = QtGui.QGroupBox(self.frameBaseAndDiagnosises)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpBase.sizePolicy().hasHeightForWidth())
        self.grpBase.setSizePolicy(sizePolicy)
        self.grpBase.setObjectName(_fromUtf8("grpBase"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpBase)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cmbResult = CRBComboBox(self.grpBase)
        self.cmbResult.setObjectName(_fromUtf8("cmbResult"))
        self.cmbResult.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbResult, 13, 0, 1, 4)
        self.edtPregnancyWeek = QtGui.QSpinBox(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPregnancyWeek.sizePolicy().hasHeightForWidth())
        self.edtPregnancyWeek.setSizePolicy(sizePolicy)
        self.edtPregnancyWeek.setMaximum(40)
        self.edtPregnancyWeek.setObjectName(_fromUtf8("edtPregnancyWeek"))
        self.gridLayout_2.addWidget(self.edtPregnancyWeek, 10, 3, 1, 1)
        self.cmbOrder = CRBComboBox(self.grpBase)
        self.cmbOrder.setObjectName(_fromUtf8("cmbOrder"))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.setItemText(0, _fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbOrder, 9, 0, 1, 4)
        self.lblPregnancyWeek = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPregnancyWeek.sizePolicy().hasHeightForWidth())
        self.lblPregnancyWeek.setSizePolicy(sizePolicy)
        self.lblPregnancyWeek.setObjectName(_fromUtf8("lblPregnancyWeek"))
        self.gridLayout_2.addWidget(self.lblPregnancyWeek, 10, 0, 1, 3)
        self.lblResult = QtGui.QLabel(self.grpBase)
        self.lblResult.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblResult.setObjectName(_fromUtf8("lblResult"))
        self.gridLayout_2.addWidget(self.lblResult, 12, 0, 1, 4)
        self.cmbPrimary = QtGui.QComboBox(self.grpBase)
        self.cmbPrimary.setObjectName(_fromUtf8("cmbPrimary"))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbPrimary, 8, 0, 1, 3)
        self.lblBegDate = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDate.sizePolicy().hasHeightForWidth())
        self.lblBegDate.setSizePolicy(sizePolicy)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout_2.addWidget(self.lblBegDate, 3, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(self.grpBase)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbPerson, 7, 0, 1, 4)
        self.lblPerson = QtGui.QLabel(self.grpBase)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout_2.addWidget(self.lblPerson, 6, 0, 1, 4)
        self.lblNextDate = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNextDate.sizePolicy().hasHeightForWidth())
        self.lblNextDate.setSizePolicy(sizePolicy)
        self.lblNextDate.setMaximumSize(QtCore.QSize(16777215, 0))
        self.lblNextDate.setObjectName(_fromUtf8("lblNextDate"))
        self.gridLayout_2.addWidget(self.lblNextDate, 5, 0, 1, 1)
        self.chkExposeConfirmed = QtGui.QCheckBox(self.grpBase)
        self.chkExposeConfirmed.setObjectName(_fromUtf8("chkExposeConfirmed"))
        self.gridLayout_2.addWidget(self.chkExposeConfirmed, 2, 0, 1, 4)
        self.chkZNOMorph = QtGui.QCheckBox(self.grpBase)
        self.chkZNOMorph.setObjectName(_fromUtf8("chkZNOMorph"))
        self.gridLayout_2.addWidget(self.chkZNOMorph, 15, 0, 1, 3)
        self.cmbContract = CContractComboBox(self.grpBase)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.cmbContract.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbContract, 0, 0, 1, 4)
        self.lblEndDate = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDate.sizePolicy().hasHeightForWidth())
        self.lblEndDate.setSizePolicy(sizePolicy)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout_2.addWidget(self.lblEndDate, 4, 0, 1, 1)
        self.chkZNOFirst = QtGui.QCheckBox(self.grpBase)
        self.chkZNOFirst.setObjectName(_fromUtf8("chkZNOFirst"))
        self.gridLayout_2.addWidget(self.chkZNOFirst, 14, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(16, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 16, 0, 1, 4)
        self.frmEndDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmEndDateTime.sizePolicy().hasHeightForWidth())
        self.frmEndDateTime.setSizePolicy(sizePolicy)
        self.frmEndDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmEndDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmEndDateTime.setLineWidth(0)
        self.frmEndDateTime.setObjectName(_fromUtf8("frmEndDateTime"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frmEndDateTime)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.edtEndDate = CDateEdit(self.frmEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout_4.addWidget(self.edtEndDate)
        self.edtEndTime = QtGui.QTimeEdit(self.frmEndDateTime)
        self.edtEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.horizontalLayout_4.addWidget(self.edtEndTime)
        self.gridLayout_2.addWidget(self.frmEndDateTime, 4, 1, 1, 3)
        self.frmBegDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmBegDateTime.sizePolicy().hasHeightForWidth())
        self.frmBegDateTime.setSizePolicy(sizePolicy)
        self.frmBegDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmBegDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmBegDateTime.setLineWidth(0)
        self.frmBegDateTime.setObjectName(_fromUtf8("frmBegDateTime"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frmBegDateTime)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.edtBegDate = CDateEdit(self.frmBegDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout_3.addWidget(self.edtBegDate)
        self.edtBegTime = QtGui.QTimeEdit(self.frmBegDateTime)
        self.edtBegTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.horizontalLayout_3.addWidget(self.edtBegTime)
        self.gridLayout_2.addWidget(self.frmBegDateTime, 3, 1, 1, 3)
        self.frmNextDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmNextDateTime.sizePolicy().hasHeightForWidth())
        self.frmNextDateTime.setSizePolicy(sizePolicy)
        self.frmNextDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmNextDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmNextDateTime.setLineWidth(0)
        self.frmNextDateTime.setObjectName(_fromUtf8("frmNextDateTime"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frmNextDateTime)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.edtNextDate = CDateEdit(self.frmNextDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtNextDate.sizePolicy().hasHeightForWidth())
        self.edtNextDate.setSizePolicy(sizePolicy)
        self.edtNextDate.setMaximumSize(QtCore.QSize(16777215, 0))
        self.edtNextDate.setCalendarPopup(True)
        self.edtNextDate.setObjectName(_fromUtf8("edtNextDate"))
        self.horizontalLayout_5.addWidget(self.edtNextDate)
        self.gridLayout_2.addWidget(self.frmNextDateTime, 5, 1, 1, 3)
        self.gbLittleStrangerFlag = QtGui.QGroupBox(self.grpBase)
        self.gbLittleStrangerFlag.setCheckable(True)
        self.gbLittleStrangerFlag.setChecked(False)
        self.gbLittleStrangerFlag.setObjectName(_fromUtf8("gbLittleStrangerFlag"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gbLittleStrangerFlag)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.chkMultipleBirths = QtGui.QCheckBox(self.gbLittleStrangerFlag)
        self.chkMultipleBirths.setObjectName(_fromUtf8("chkMultipleBirths"))
        self.gridLayout_7.addWidget(self.chkMultipleBirths, 4, 0, 1, 2)
        self.cmbChildSex = QtGui.QComboBox(self.gbLittleStrangerFlag)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbChildSex.sizePolicy().hasHeightForWidth())
        self.cmbChildSex.setSizePolicy(sizePolicy)
        self.cmbChildSex.setObjectName(_fromUtf8("cmbChildSex"))
        self.cmbChildSex.addItem(_fromUtf8(""))
        self.cmbChildSex.setItemText(0, _fromUtf8(""))
        self.cmbChildSex.addItem(_fromUtf8(""))
        self.cmbChildSex.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cmbChildSex, 0, 3, 1, 1)
        self.lblChildSex = QtGui.QLabel(self.gbLittleStrangerFlag)
        self.lblChildSex.setObjectName(_fromUtf8("lblChildSex"))
        self.gridLayout_7.addWidget(self.lblChildSex, 0, 2, 1, 1)
        self.sbChildNumber = QtGui.QSpinBox(self.gbLittleStrangerFlag)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbChildNumber.sizePolicy().hasHeightForWidth())
        self.sbChildNumber.setSizePolicy(sizePolicy)
        self.sbChildNumber.setMinimum(1)
        self.sbChildNumber.setObjectName(_fromUtf8("sbChildNumber"))
        self.gridLayout_7.addWidget(self.sbChildNumber, 0, 1, 1, 1)
        self.lblChildNumber = QtGui.QLabel(self.gbLittleStrangerFlag)
        self.lblChildNumber.setObjectName(_fromUtf8("lblChildNumber"))
        self.gridLayout_7.addWidget(self.lblChildNumber, 0, 0, 1, 1)
        self.edtChildBirthDate = CDateEdit(self.gbLittleStrangerFlag)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtChildBirthDate.sizePolicy().hasHeightForWidth())
        self.edtChildBirthDate.setSizePolicy(sizePolicy)
        self.edtChildBirthDate.setCalendarPopup(True)
        self.edtChildBirthDate.setObjectName(_fromUtf8("edtChildBirthDate"))
        self.gridLayout_7.addWidget(self.edtChildBirthDate, 1, 2, 1, 2)
        self.lblChildBirthDate = QtGui.QLabel(self.gbLittleStrangerFlag)
        self.lblChildBirthDate.setObjectName(_fromUtf8("lblChildBirthDate"))
        self.gridLayout_7.addWidget(self.lblChildBirthDate, 1, 0, 1, 1)
        self.lblBirthWeight = QtGui.QLabel(self.gbLittleStrangerFlag)
        self.lblBirthWeight.setObjectName(_fromUtf8("lblBirthWeight"))
        self.gridLayout_7.addWidget(self.lblBirthWeight, 2, 0, 1, 2)
        self.sbBirthWeight = QtGui.QDoubleSpinBox(self.gbLittleStrangerFlag)
        self.sbBirthWeight.setMaximum(9999.99)
        self.sbBirthWeight.setObjectName(_fromUtf8("sbBirthWeight"))
        self.gridLayout_7.addWidget(self.sbBirthWeight, 2, 2, 1, 2)
        self.gridLayout_2.addWidget(self.gbLittleStrangerFlag, 11, 0, 1, 4)
        self.chkIsClosed = QtGui.QCheckBox(self.grpBase)
        self.chkIsClosed.setObjectName(_fromUtf8("chkIsClosed"))
        self.gridLayout_2.addWidget(self.chkIsClosed, 1, 0, 1, 4)
        self.horizontalLayout.addWidget(self.grpBase)
        self.groupBox = QtGui.QGroupBox(self.frameBaseAndDiagnosises)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lblVisitsCount = QtGui.QLabel(self.groupBox)
        self.lblVisitsCount.setObjectName(_fromUtf8("lblVisitsCount"))
        self.gridLayout_5.addWidget(self.lblVisitsCount, 1, 0, 1, 1)
        self.lblVisitsDurationValue = QtGui.QLabel(self.groupBox)
        self.lblVisitsDurationValue.setMinimumSize(QtCore.QSize(40, 0))
        self.lblVisitsDurationValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblVisitsDurationValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblVisitsDurationValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblVisitsDurationValue.setObjectName(_fromUtf8("lblVisitsDurationValue"))
        self.gridLayout_5.addWidget(self.lblVisitsDurationValue, 1, 3, 1, 1)
        self.lblVisitsCountValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblVisitsCountValue.sizePolicy().hasHeightForWidth())
        self.lblVisitsCountValue.setSizePolicy(sizePolicy)
        self.lblVisitsCountValue.setMinimumSize(QtCore.QSize(40, 0))
        self.lblVisitsCountValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblVisitsCountValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblVisitsCountValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblVisitsCountValue.setObjectName(_fromUtf8("lblVisitsCountValue"))
        self.gridLayout_5.addWidget(self.lblVisitsCountValue, 1, 1, 1, 1)
        self.tblVisits = CInDocTableView(self.groupBox)
        self.tblVisits.setObjectName(_fromUtf8("tblVisits"))
        self.gridLayout_5.addWidget(self.tblVisits, 0, 0, 1, 5)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 1, 4, 1, 1)
        self.lblVisitsDuration = QtGui.QLabel(self.groupBox)
        self.lblVisitsDuration.setObjectName(_fromUtf8("lblVisitsDuration"))
        self.gridLayout_5.addWidget(self.lblVisitsDuration, 1, 2, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.frameVisitsAndActionSummary = QtGui.QFrame(self.splitter_2)
        self.frameVisitsAndActionSummary.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameVisitsAndActionSummary.setFrameShadow(QtGui.QFrame.Raised)
        self.frameVisitsAndActionSummary.setObjectName(_fromUtf8("frameVisitsAndActionSummary"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frameVisitsAndActionSummary)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.splitter_4 = QtGui.QSplitter(self.frameVisitsAndActionSummary)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_4.sizePolicy().hasHeightForWidth())
        self.splitter_4.setSizePolicy(sizePolicy)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.grplFinalDiagnostics = QtGui.QGroupBox(self.splitter_4)
        self.grplFinalDiagnostics.setObjectName(_fromUtf8("grplFinalDiagnostics"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grplFinalDiagnostics)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblFinalDiagnostics = CDiagnosticsInDocTableView(self.grplFinalDiagnostics)
        self.tblFinalDiagnostics.setMinimumSize(QtCore.QSize(0, 100))
        self.tblFinalDiagnostics.setObjectName(_fromUtf8("tblFinalDiagnostics"))
        self.gridLayout_3.addWidget(self.tblFinalDiagnostics, 0, 0, 1, 1)
        self.grpActions = QtGui.QGroupBox(self.splitter_4)
        self.grpActions.setObjectName(_fromUtf8("grpActions"))
        self.verticalLayout = QtGui.QVBoxLayout(self.grpActions)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tblActions = CInDocTableView(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tblActions.sizePolicy().hasHeightForWidth())
        self.tblActions.setSizePolicy(sizePolicy)
        self.tblActions.setMinimumSize(QtCore.QSize(0, 100))
        self.tblActions.setObjectName(_fromUtf8("tblActions"))
        self.verticalLayout.addWidget(self.tblActions)
        self.frmTotalUet = QtGui.QFrame(self.grpActions)
        self.frmTotalUet.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmTotalUet.setFrameShadow(QtGui.QFrame.Plain)
        self.frmTotalUet.setObjectName(_fromUtf8("frmTotalUet"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frmTotalUet)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblTotalUet = QtGui.QLabel(self.frmTotalUet)
        self.lblTotalUet.setObjectName(_fromUtf8("lblTotalUet"))
        self.horizontalLayout_2.addWidget(self.lblTotalUet)
        self.lblShowTotalUet = QtGui.QLabel(self.frmTotalUet)
        self.lblShowTotalUet.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblShowTotalUet.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblShowTotalUet.setObjectName(_fromUtf8("lblShowTotalUet"))
        self.horizontalLayout_2.addWidget(self.lblShowTotalUet)
        spacerItem2 = QtGui.QSpacerItem(681, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.frmTotalUet)
        self.gridLayout_9.addWidget(self.splitter_4, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.splitter_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabToken, _fromUtf8(""))
        self.tabMes = CFastEventMesPage()
        self.tabMes.setObjectName(_fromUtf8("tabMes"))
        self.tabWidget.addTab(self.tabMes, _fromUtf8(""))
        self.tabStatus = CFastActionsPage()
        self.tabStatus.setObjectName(_fromUtf8("tabStatus"))
        self.tabWidget.addTab(self.tabStatus, _fromUtf8(""))
        self.tabDiagnostic = CFastActionsPage()
        self.tabDiagnostic.setObjectName(_fromUtf8("tabDiagnostic"))
        self.tabWidget.addTab(self.tabDiagnostic, _fromUtf8(""))
        self.tabCure = CFastActionsPage()
        self.tabCure.setObjectName(_fromUtf8("tabCure"))
        self.tabWidget.addTab(self.tabCure, _fromUtf8(""))
        self.tabMisc = CFastActionsPage()
        self.tabMisc.setObjectName(_fromUtf8("tabMisc"))
        self.tabWidget.addTab(self.tabMisc, _fromUtf8(""))
        self.tabAmbCard = CFastAmbCardPage()
        self.tabAmbCard.setObjectName(_fromUtf8("tabAmbCard"))
        self.tabWidget.addTab(self.tabAmbCard, _fromUtf8(""))
        self.tabTempInvalidEtc = QtGui.QWidget()
        self.tabTempInvalidEtc.setObjectName(_fromUtf8("tabTempInvalidEtc"))
        self.gridLayout = QtGui.QGridLayout(self.tabTempInvalidEtc)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tabTempInvalidEtc)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 894, 310))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tabTempInvalidAndAegrotat = QtGui.QTabWidget(self.scrollAreaWidgetContents_2)
        self.tabTempInvalidAndAegrotat.setObjectName(_fromUtf8("tabTempInvalidAndAegrotat"))
        self.tabTempInvalid = QtGui.QWidget()
        self.tabTempInvalid.setObjectName(_fromUtf8("tabTempInvalid"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabTempInvalid)
        self.gridLayout_8.setMargin(4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.grpTempInvalid = CTempInvalid(self.tabTempInvalid)
        self.grpTempInvalid.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpTempInvalid.sizePolicy().hasHeightForWidth())
        self.grpTempInvalid.setSizePolicy(sizePolicy)
        self.grpTempInvalid.setCheckable(True)
        self.grpTempInvalid.setChecked(False)
        self.grpTempInvalid.setObjectName(_fromUtf8("grpTempInvalid"))
        self.gridLayout_8.addWidget(self.grpTempInvalid, 0, 0, 1, 1)
        self.tabTempInvalidAndAegrotat.addTab(self.tabTempInvalid, _fromUtf8(""))
        self.tabTempinvalidS = QtGui.QWidget()
        self.tabTempinvalidS.setObjectName(_fromUtf8("tabTempinvalidS"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabTempinvalidS)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.grpDisability = CTempInvalid(self.tabTempinvalidS)
        self.grpDisability.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpDisability.sizePolicy().hasHeightForWidth())
        self.grpDisability.setSizePolicy(sizePolicy)
        self.grpDisability.setCheckable(True)
        self.grpDisability.setChecked(False)
        self.grpDisability.setObjectName(_fromUtf8("grpDisability"))
        self.gridLayout_6.addWidget(self.grpDisability, 0, 0, 1, 1)
        self.tabTempInvalidAndAegrotat.addTab(self.tabTempinvalidS, _fromUtf8(""))
        self.tabTempInvalidDisability = QtGui.QWidget()
        self.tabTempInvalidDisability.setObjectName(_fromUtf8("tabTempInvalidDisability"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tabTempInvalidDisability)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.grpVitalRestriction = CTempInvalid(self.tabTempInvalidDisability)
        self.grpVitalRestriction.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpVitalRestriction.sizePolicy().hasHeightForWidth())
        self.grpVitalRestriction.setSizePolicy(sizePolicy)
        self.grpVitalRestriction.setCheckable(True)
        self.grpVitalRestriction.setChecked(False)
        self.grpVitalRestriction.setObjectName(_fromUtf8("grpVitalRestriction"))
        self.gridLayout_10.addWidget(self.grpVitalRestriction, 0, 0, 1, 1)
        self.tabTempInvalidAndAegrotat.addTab(self.tabTempInvalidDisability, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.tabTempInvalidAndAegrotat)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabTempInvalidEtc, _fromUtf8(""))
        self.tabCash = CFastEventCashPage()
        self.tabCash.setObjectName(_fromUtf8("tabCash"))
        self.tabWidget.addTab(self.tabCash, _fromUtf8(""))
        self.tabNotes = CFastEventNotesPage()
        self.tabNotes.setObjectName(_fromUtf8("tabNotes"))
        self.tabWidget.addTab(self.tabNotes, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.sptTopLevel)
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lblProlongateEvent = QtGui.QLabel(self.widget)
        self.lblProlongateEvent.setText(_fromUtf8(""))
        self.lblProlongateEvent.setObjectName(_fromUtf8("lblProlongateEvent"))
        self.horizontalLayout_6.addWidget(self.lblProlongateEvent)
        self.lblValueExternalId = QtGui.QLabel(self.widget)
        self.lblValueExternalId.setText(_fromUtf8(""))
        self.lblValueExternalId.setObjectName(_fromUtf8("lblValueExternalId"))
        self.horizontalLayout_6.addWidget(self.lblValueExternalId)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_6.addWidget(self.buttonBox)
        self.verticalLayout_2.addWidget(self.widget)
        self.statusBar = QtGui.QStatusBar(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.verticalLayout_2.addWidget(self.statusBar)
        self.lblPregnancyWeek.setBuddy(self.edtPregnancyWeek)
        self.lblResult.setBuddy(self.cmbResult)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblNextDate.setBuddy(self.edtNextDate)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblBirthWeight.setBuddy(self.sbBirthWeight)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabTempInvalidAndAegrotat.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.scrollArea)
        Dialog.setTabOrder(self.scrollArea, self.cmbContract)
        Dialog.setTabOrder(self.cmbContract, self.chkIsClosed)
        Dialog.setTabOrder(self.chkIsClosed, self.chkExposeConfirmed)
        Dialog.setTabOrder(self.chkExposeConfirmed, self.edtBegDate)
        Dialog.setTabOrder(self.edtBegDate, self.edtBegTime)
        Dialog.setTabOrder(self.edtBegTime, self.edtEndDate)
        Dialog.setTabOrder(self.edtEndDate, self.edtEndTime)
        Dialog.setTabOrder(self.edtEndTime, self.edtNextDate)
        Dialog.setTabOrder(self.edtNextDate, self.cmbPerson)
        Dialog.setTabOrder(self.cmbPerson, self.cmbPrimary)
        Dialog.setTabOrder(self.cmbPrimary, self.cmbOrder)
        Dialog.setTabOrder(self.cmbOrder, self.edtPregnancyWeek)
        Dialog.setTabOrder(self.edtPregnancyWeek, self.gbLittleStrangerFlag)
        Dialog.setTabOrder(self.gbLittleStrangerFlag, self.sbChildNumber)
        Dialog.setTabOrder(self.sbChildNumber, self.cmbChildSex)
        Dialog.setTabOrder(self.cmbChildSex, self.edtChildBirthDate)
        Dialog.setTabOrder(self.edtChildBirthDate, self.sbBirthWeight)
        Dialog.setTabOrder(self.sbBirthWeight, self.chkMultipleBirths)
        Dialog.setTabOrder(self.chkMultipleBirths, self.cmbResult)
        Dialog.setTabOrder(self.cmbResult, self.chkZNOFirst)
        Dialog.setTabOrder(self.chkZNOFirst, self.chkZNOMorph)
        Dialog.setTabOrder(self.chkZNOMorph, self.tblVisits)
        Dialog.setTabOrder(self.tblVisits, self.tblFinalDiagnostics)
        Dialog.setTabOrder(self.tblFinalDiagnostics, self.tblActions)
        Dialog.setTabOrder(self.tblActions, self.scrollArea_2)
        Dialog.setTabOrder(self.scrollArea_2, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.grpTempInvalid)
        Dialog.setTabOrder(self.grpTempInvalid, self.tabTempInvalidAndAegrotat)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.txtClientInfoBrowser.setWhatsThis(_translate("Dialog", "Описание пациента", None))
        self.txtClientInfoBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.grpBase.setTitle(_translate("Dialog", "&ф.025-12/у", None))
        self.cmbResult.setWhatsThis(_translate("Dialog", "результат осмотра", None))
        self.cmbResult.setItemText(0, _translate("Dialog", "Результат", None))
        self.cmbOrder.setItemText(1, _translate("Dialog", "Плановый", None))
        self.cmbOrder.setItemText(2, _translate("Dialog", "Экстренный", None))
        self.cmbOrder.setItemText(3, _translate("Dialog", "Самообращение", None))
        self.cmbOrder.setItemText(4, _translate("Dialog", "Принудительный", None))
        self.cmbOrder.setItemText(5, _translate("Dialog", "Неотложный", None))
        self.lblPregnancyWeek.setText(_translate("Dialog", "Неделя беременности", None))
        self.lblResult.setText(_translate("Dialog", "Результат лечения", None))
        self.cmbPrimary.setItemText(0, _translate("Dialog", "Первичный", None))
        self.cmbPrimary.setItemText(1, _translate("Dialog", "Повторный", None))
        self.cmbPrimary.setItemText(2, _translate("Dialog", "Актив", None))
        self.lblBegDate.setText(_translate("Dialog", "Начато", None))
        self.cmbPerson.setWhatsThis(_translate("Dialog", "врач отвечающий за осмотр (терапевт)", None))
        self.cmbPerson.setItemText(0, _translate("Dialog", "Врач", None))
        self.lblPerson.setText(_translate("Dialog", "Лечащий врач", None))
        self.lblNextDate.setText(_translate("Dialog", "След.явка", None))
        self.chkExposeConfirmed.setText(_translate("Dialog", "Добавить к выставлению", None))
        self.chkZNOMorph.setToolTip(_translate("Dialog", "ЗНО потдверждён морфологически", None))
        self.chkZNOMorph.setText(_translate("Dialog", "ЗНО подтв. морф-ки", None))
        self.cmbContract.setWhatsThis(_translate("Dialog", "номер, дата и основание договора в рамках которого производится осмотр", None))
        self.cmbContract.setItemText(0, _translate("Dialog", "Договор", None))
        self.lblEndDate.setText(_translate("Dialog", "Закончено", None))
        self.chkZNOFirst.setToolTip(_translate("Dialog", "ЗНО установлен впервые", None))
        self.chkZNOFirst.setText(_translate("Dialog", "ЗНО уст. впервые", None))
        self.edtEndDate.setWhatsThis(_translate("Dialog", "дата окончания осмотра", None))
        self.edtEndTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.edtBegDate.setWhatsThis(_translate("Dialog", "дата начала осмотра", None))
        self.edtBegTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.gbLittleStrangerFlag.setTitle(_translate("Dialog", "Признак новорожденного", None))
        self.chkMultipleBirths.setText(_translate("Dialog", "Многоплодные роды", None))
        self.cmbChildSex.setItemText(1, _translate("Dialog", "М", None))
        self.cmbChildSex.setItemText(2, _translate("Dialog", "Ж", None))
        self.lblChildSex.setText(_translate("Dialog", "Пол", None))
        self.lblChildNumber.setText(_translate("Dialog", "По счету в семье", None))
        self.lblChildBirthDate.setText(_translate("Dialog", "Дата рождения", None))
        self.lblBirthWeight.setText(_translate("Dialog", "Вес при рождении", None))
        self.chkIsClosed.setText(_translate("Dialog", "Карта заполнена", None))
        self.groupBox.setTitle(_translate("Dialog", "&Посещения", None))
        self.lblVisitsCount.setText(_translate("Dialog", "Всего посещений:", None))
        self.lblVisitsDurationValue.setText(_translate("Dialog", "0", None))
        self.lblVisitsCountValue.setText(_translate("Dialog", "0", None))
        self.lblVisitsDuration.setText(_translate("Dialog", "Общая длительность:", None))
        self.grplFinalDiagnostics.setTitle(_translate("Dialog", "&Диагнозы", None))
        self.grpActions.setTitle(_translate("Dialog", "&Мероприятия", None))
        self.lblTotalUet.setText(_translate("Dialog", "Всего УЕТ", None))
        self.lblShowTotalUet.setText(_translate("Dialog", "0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabToken), _translate("Dialog", "Стат.&учёт", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMes), _translate("Dialog", "Стандарт", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStatus), _translate("Dialog", "&Статус", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDiagnostic), _translate("Dialog", "&Диагностика", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCure), _translate("Dialog", "&Лечение", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMisc), _translate("Dialog", "&Мероприятия", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAmbCard), _translate("Dialog", "Мед.&карта", None))
        self.grpTempInvalid.setTitle(_translate("Dialog", "&ВУТ", None))
        self.tabTempInvalidAndAegrotat.setTabText(self.tabTempInvalidAndAegrotat.indexOf(self.tabTempInvalid), _translate("Dialog", "Листок &нетрудоспособности", None))
        self.grpDisability.setTitle(_translate("Dialog", "&Инвалидность", None))
        self.tabTempInvalidAndAegrotat.setTabText(self.tabTempInvalidAndAegrotat.indexOf(self.tabTempinvalidS), _translate("Dialog", "Инвалидность", None))
        self.grpVitalRestriction.setTitle(_translate("Dialog", "&Ограничения жизнедеятельности", None))
        self.tabTempInvalidAndAegrotat.setTabText(self.tabTempInvalidAndAegrotat.indexOf(self.tabTempInvalidDisability), _translate("Dialog", "Ограничения жизнедеятельности", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTempInvalidEtc), _translate("Dialog", "Т&рудоспособность", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCash), _translate("Dialog", "Оплата", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNotes), _translate("Dialog", "Приме&чания", None))
        self.statusBar.setToolTip(_translate("Dialog", "A status bar", None))
        self.statusBar.setWhatsThis(_translate("Dialog", "A status bar.", None))

from Events.ActionsPage import CFastActionsPage
from Events.AmbCardPage import CFastAmbCardPage
from Events.EventCashPage import CFastEventCashPage
from Events.EventDiagnosticsTable import CDiagnosticsInDocTableView
from Events.EventMesPage import CFastEventMesPage
from Events.EventNotesPage import CFastEventNotesPage
from Events.TempInvalid import CTempInvalid
from Orgs.OrgComboBox import CContractComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
from library.TextBrowser import CTextBrowser
from library.crbcombobox import CRBComboBox
