# -*- coding: utf-8 -*-

#############################################################################
##
## Copyright (C) 2006-2012 Chuk&Gek and Vista Software. All rights reserved.
##
#############################################################################


rbId            = 'id'
rbCode          = 'code'
rbName          = 'name'
rbCodeRegional  = 'codeRegional' # нужно всюду заменить на regionalCode
rbRegionalCode  = 'regionalCode'
rbTypeCause     = 'typeCause'    # WTF
rbMask          = 'mask'
rbMaskEnabled   = 'maskEnabled'

rbAccountExportFormat                = 'rbAccountExportFormat'
rbAccountingSystem                   = 'rbAccountingSystem'
rbAccountType                        = 'rbAccountType'
rbActionTypeIncompatibility          = 'rbActionTypeIncompatibility'
rbActionTypeSimilarity               = 'rbActionTypeSimilarity'
rbActivity                           = 'rbActivity'
rbAssignedContracts                  = 'rbAssignedContracts'
rbAttachType                         = 'rbAttachType'
rbCashOperation                      = 'rbCashOperation'
rbContactType                        = 'rbContactType'
rbDeferredQueueStatus                = 'rbDeferredQueueStatus'
rbDetachmentReason                   = 'rbDetachmentReason'
rbDiagnosisType                      = 'rbDiagnosisType'
rbDiseaseCharacter                   = 'rbDiseaseCharacter'
rbDiseasePhases                      = 'rbDiseasePhases'
rbDiseaseStage                       = 'rbDiseaseStage'
rbDispanser                          = 'rbDispanser'
rbDocumentType                       = 'rbDocumentType'
rbDocumentTypeGroup                  = 'rbDocumentTypeGroup'
rbEmergencyAccident                  = 'rbEmergencyAccident'
rbEmergencyBrigade                   = 'EmergencyBrigade'
rbEmergencyCauseCall                 = 'rbEmergencyCauseCall'
rbEmergencyDeath                     = 'rbEmergencyDeath'
rbEmergencyDiseased                  = 'rbEmergencyDiseased'
rbEmergencyEbriety                   = 'rbEmergencyEbriety'
rbEmergencyMethodTransportation      = 'rbEmergencyMethodTransportation'
rbEmergencyPlaceCall                 = 'rbEmergencyPlaceCall'
rbEmergencyPlaceReceptionCall        = 'rbEmergencyPlaceReceptionCall'
rbEmergencyReasondDelays             = 'rbEmergencyReasondDelays'
rbEmergencyReceivedCall              = 'rbEmergencyReceivedCall'
rbEmergencyResult                    = 'rbEmergencyResult'
rbEmergencyTransferredTransportation = 'rbEmergencyTransferredTransportation'
rbEmergencyTypeAsset                 = 'rbEmergencyTypeAsset'
rbEquipment                          = 'rbEquipment'
rbEquipmentType                      = 'rbEquipmentType'
rbEventGoal                          = 'rbEventGoal'
rbEventTypePurpose                   = 'rbEventTypePurpose'
rbFinance                            = 'rbFinance'
rbExpenseServiceItem                 = 'rbExpenseServiceItem'
rbHealthGroup                        = 'rbHealthGroup'
rbHurtFactorType                     = 'rbHurtFactorType'
rbHurtType                           = 'rbHurtType'
rbMedicalAidUnit                     = 'rbMedicalAidUnit'
rbMedicalGroup                       = 'rbMedicalGroup'
rbCureMethod                         = 'rbCureMethod'
rbCureType                           = 'rbCureType'
rbPatientModel                       = 'rbPatientModel'
rbNet                                = 'rbNet'
rbOKFS                               = 'rbOKFS'
rbOKPF                               = 'rbOKPF'
rbPayRefuseType                      = 'rbPayRefuseType'
rbPolicyType                         = 'rbPolicyType'
rbPost                               = 'rbPost'
rbReasonOfAbsence                    = 'rbReasonOfAbsence'
rbRelationType                       = 'rbRelationType'
rbResult                             = 'rbResult'
rbDiagnosticResult                   = 'rbDiagnosticResult'
rbScene                              = 'rbScene'
rbService                            = 'rbService'
rbServiceClass                       = 'rbServiceClass'
rbServiceGroup                       = 'rbServiceGroup'
rbServiceCategory                    = 'rbServiceCategory'
rbServiceSection                     = 'rbServiceSection'
rbServiceType                        = 'rbServiceType'
rbSocStatusClass                     = 'rbSocStatusClass'
rbSocStatusType                      = 'rbSocStatusType'
rbSpeciality                         = 'rbSpeciality'
rbTariffCategory                     = 'rbTariffCategory'
rbTempInvalidReason                  = 'rbTempInvalidReason'
rbTempInvalidExtraReason             = 'rbTempInvalidExtraReason'
rbTraumaType                         = 'rbTraumaType'
rbUnit                               = 'rbUnit'
rbVisitType                          = 'rbVisitType'
EvenType                             = 'EventType'


#
TempInvalidTypeList = [u'ВУТ', u'Инвалидность', u'Ограничение жизнедеятельности']
