# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ActionTypeEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ActionTypeEditorDialog(object):
    def setupUi(self, ActionTypeEditorDialog):
        ActionTypeEditorDialog.setObjectName(_fromUtf8("ActionTypeEditorDialog"))
        ActionTypeEditorDialog.resize(757, 800)
        ActionTypeEditorDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(ActionTypeEditorDialog)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(ActionTypeEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMain = QtGui.QWidget()
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabMain)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.scrollArea = QtGui.QScrollArea(self.tabMain)
        self.scrollArea.setMinimumSize(QtCore.QSize(700, 0))
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 709, 1088))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frmRecommendation = QtGui.QHBoxLayout()
        self.frmRecommendation.setObjectName(_fromUtf8("frmRecommendation"))
        self.edtRecommendationExpirePeriod = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.edtRecommendationExpirePeriod.setObjectName(_fromUtf8("edtRecommendationExpirePeriod"))
        self.frmRecommendation.addWidget(self.edtRecommendationExpirePeriod)
        self.lblFrequencyCount_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblFrequencyCount_2.setObjectName(_fromUtf8("lblFrequencyCount_2"))
        self.frmRecommendation.addWidget(self.lblFrequencyCount_2)
        self.chkRecommendationControl = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkRecommendationControl.setObjectName(_fromUtf8("chkRecommendationControl"))
        self.frmRecommendation.addWidget(self.chkRecommendationControl)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.frmRecommendation.addItem(spacerItem)
        self.gridLayout.addLayout(self.frmRecommendation, 29, 1, 1, 1)
        self.edtTitle = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtTitle.setObjectName(_fromUtf8("edtTitle"))
        self.gridLayout.addWidget(self.edtTitle, 3, 1, 1, 1)
        self.edtContext = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtContext.setMaxLength(64)
        self.edtContext.setObjectName(_fromUtf8("edtContext"))
        self.gridLayout.addWidget(self.edtContext, 24, 1, 1, 1)
        self.chkShowInForm = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkShowInForm.setEnabled(True)
        self.chkShowInForm.setCheckable(True)
        self.chkShowInForm.setChecked(True)
        self.chkShowInForm.setObjectName(_fromUtf8("chkShowInForm"))
        self.gridLayout.addWidget(self.chkShowInForm, 17, 1, 1, 1)
        self.edtName = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtName.setMinimumSize(QtCore.QSize(200, 0))
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 2, 1, 1, 1)
        self.chkFilledLock = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilledLock.setObjectName(_fromUtf8("chkFilledLock"))
        self.gridLayout.addWidget(self.chkFilledLock, 31, 1, 1, 1)
        self.chkNomenclatureExpense = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkNomenclatureExpense.setObjectName(_fromUtf8("chkNomenclatureExpense"))
        self.gridLayout.addWidget(self.chkNomenclatureExpense, 27, 1, 1, 1)
        self.chkIsPreferable = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkIsPreferable.setObjectName(_fromUtf8("chkIsPreferable"))
        self.gridLayout.addWidget(self.chkIsPreferable, 25, 1, 1, 1)
        self.frmNomenclativeService = QtGui.QHBoxLayout()
        self.frmNomenclativeService.setObjectName(_fromUtf8("frmNomenclativeService"))
        self.cmbNomenclativeService = CRBComboBox(self.scrollAreaWidgetContents)
        self.cmbNomenclativeService.setMinimumSize(QtCore.QSize(150, 0))
        self.cmbNomenclativeService.setObjectName(_fromUtf8("cmbNomenclativeService"))
        self.frmNomenclativeService.addWidget(self.cmbNomenclativeService)
        self.btnSetName = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.btnSetName.setMinimumSize(QtCore.QSize(25, 0))
        self.btnSetName.setArrowType(QtCore.Qt.DownArrow)
        self.btnSetName.setObjectName(_fromUtf8("btnSetName"))
        self.frmNomenclativeService.addWidget(self.btnSetName)
        self.btnSelectService = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.btnSelectService.setMinimumSize(QtCore.QSize(25, 0))
        self.btnSelectService.setObjectName(_fromUtf8("btnSelectService"))
        self.frmNomenclativeService.addWidget(self.btnSelectService)
        self.gridLayout.addLayout(self.frmNomenclativeService, 1, 1, 1, 1)
        self.chkIsPrinted = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkIsPrinted.setObjectName(_fromUtf8("chkIsPrinted"))
        self.gridLayout.addWidget(self.chkIsPrinted, 23, 1, 1, 1)
        self.chkLock = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkLock.setEnabled(False)
        self.chkLock.setObjectName(_fromUtf8("chkLock"))
        self.gridLayout.addWidget(self.chkLock, 30, 1, 1, 1)
        self.lblFlatCode = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblFlatCode.setObjectName(_fromUtf8("lblFlatCode"))
        self.gridLayout.addWidget(self.lblFlatCode, 7, 0, 1, 1)
        self.lblServiceType = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblServiceType.setObjectName(_fromUtf8("lblServiceType"))
        self.gridLayout.addWidget(self.lblServiceType, 28, 0, 1, 1)
        self.chkIsMES = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkIsMES.setEnabled(False)
        self.chkIsMES.setObjectName(_fromUtf8("chkIsMES"))
        self.gridLayout.addWidget(self.chkIsMES, 10, 1, 1, 1)
        self.frmCode = QtGui.QHBoxLayout()
        self.frmCode.setObjectName(_fromUtf8("frmCode"))
        self.edtCode = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.frmCode.addWidget(self.edtCode)
        spacerItem1 = QtGui.QSpacerItem(145, 19, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.frmCode.addItem(spacerItem1)
        self.gridLayout.addLayout(self.frmCode, 0, 1, 1, 1)
        self.lblCode = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout.addWidget(self.lblCode, 0, 0, 1, 1)
        self.frmFrequency = QtGui.QHBoxLayout()
        self.frmFrequency.setObjectName(_fromUtf8("frmFrequency"))
        self.edtFrequencyCount = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.edtFrequencyCount.setObjectName(_fromUtf8("edtFrequencyCount"))
        self.frmFrequency.addWidget(self.edtFrequencyCount)
        self.lblFrequencyCount = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblFrequencyCount.setObjectName(_fromUtf8("lblFrequencyCount"))
        self.frmFrequency.addWidget(self.lblFrequencyCount)
        self.edtFrequencyPeriod = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.edtFrequencyPeriod.setObjectName(_fromUtf8("edtFrequencyPeriod"))
        self.frmFrequency.addWidget(self.edtFrequencyPeriod)
        self.cmbFrequencyPeriodType = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbFrequencyPeriodType.setObjectName(_fromUtf8("cmbFrequencyPeriodType"))
        self.cmbFrequencyPeriodType.addItem(_fromUtf8(""))
        self.cmbFrequencyPeriodType.addItem(_fromUtf8(""))
        self.cmbFrequencyPeriodType.addItem(_fromUtf8(""))
        self.cmbFrequencyPeriodType.addItem(_fromUtf8(""))
        self.cmbFrequencyPeriodType.addItem(_fromUtf8(""))
        self.cmbFrequencyPeriodType.addItem(_fromUtf8(""))
        self.cmbFrequencyPeriodType.addItem(_fromUtf8(""))
        self.frmFrequency.addWidget(self.cmbFrequencyPeriodType)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.frmFrequency.addItem(spacerItem2)
        self.gridLayout.addLayout(self.frmFrequency, 18, 1, 1, 1)
        self.lblLock = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblLock.setEnabled(False)
        self.lblLock.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblLock.setObjectName(_fromUtf8("lblLock"))
        self.gridLayout.addWidget(self.lblLock, 30, 0, 1, 1)
        self.lblTitle = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblTitle.setObjectName(_fromUtf8("lblTitle"))
        self.gridLayout.addWidget(self.lblTitle, 3, 0, 1, 1)
        self.chkRequiredCoordination = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkRequiredCoordination.setObjectName(_fromUtf8("chkRequiredCoordination"))
        self.gridLayout.addWidget(self.chkRequiredCoordination, 15, 1, 1, 1)
        self.frmAge = QtGui.QHBoxLayout()
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self.cmbBegAgeUnit = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbBegAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbBegAgeUnit.setSizePolicy(sizePolicy)
        self.cmbBegAgeUnit.setObjectName(_fromUtf8("cmbBegAgeUnit"))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.frmAge.addWidget(self.cmbBegAgeUnit)
        self.edtBegAgeCount = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegAgeCount.sizePolicy().hasHeightForWidth())
        self.edtBegAgeCount.setSizePolicy(sizePolicy)
        self.edtBegAgeCount.setMaxLength(3)
        self.edtBegAgeCount.setObjectName(_fromUtf8("edtBegAgeCount"))
        self.frmAge.addWidget(self.edtBegAgeCount)
        self.lblAgeSep = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblAgeSep.setObjectName(_fromUtf8("lblAgeSep"))
        self.frmAge.addWidget(self.lblAgeSep)
        self.cmbEndAgeUnit = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEndAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbEndAgeUnit.setSizePolicy(sizePolicy)
        self.cmbEndAgeUnit.setObjectName(_fromUtf8("cmbEndAgeUnit"))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.frmAge.addWidget(self.cmbEndAgeUnit)
        self.edtEndAgeCount = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndAgeCount.sizePolicy().hasHeightForWidth())
        self.edtEndAgeCount.setSizePolicy(sizePolicy)
        self.edtEndAgeCount.setMaxLength(3)
        self.edtEndAgeCount.setObjectName(_fromUtf8("edtEndAgeCount"))
        self.frmAge.addWidget(self.edtEndAgeCount)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.frmAge.addItem(spacerItem3)
        self.gridLayout.addLayout(self.frmAge, 9, 1, 1, 1)
        self.frmServiceType = QtGui.QHBoxLayout()
        self.frmServiceType.setObjectName(_fromUtf8("frmServiceType"))
        self.cmbServiceType = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbServiceType.setObjectName(_fromUtf8("cmbServiceType"))
        self.frmServiceType.addWidget(self.cmbServiceType)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.frmServiceType.addItem(spacerItem4)
        self.gridLayout.addLayout(self.frmServiceType, 28, 1, 1, 1)
        self.chkShowTime = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkShowTime.setObjectName(_fromUtf8("chkShowTime"))
        self.gridLayout.addWidget(self.chkShowTime, 11, 1, 1, 1)
        self.chkIsCustomSum = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkIsCustomSum.setObjectName(_fromUtf8("chkIsCustomSum"))
        self.gridLayout.addWidget(self.chkIsCustomSum, 14, 1, 1, 1)
        self.lblGroup = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblGroup.setObjectName(_fromUtf8("lblGroup"))
        self.gridLayout.addWidget(self.lblGroup, 6, 0, 1, 1)
        self.lblAge = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout.addWidget(self.lblAge, 9, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.chkFrequencyPeriodByCalendar = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFrequencyPeriodByCalendar.setObjectName(_fromUtf8("chkFrequencyPeriodByCalendar"))
        self.horizontalLayout_2.addWidget(self.chkFrequencyPeriodByCalendar)
        self.chkStrictFrequency = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkStrictFrequency.setObjectName(_fromUtf8("chkStrictFrequency"))
        self.horizontalLayout_2.addWidget(self.chkStrictFrequency)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_2, 19, 1, 1, 1)
        self.lblMaxOccursInEvent2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblMaxOccursInEvent2.setObjectName(_fromUtf8("lblMaxOccursInEvent2"))
        self.gridLayout.addWidget(self.lblMaxOccursInEvent2, 21, 0, 1, 1)
        self.lblPrescribedType = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblPrescribedType.setObjectName(_fromUtf8("lblPrescribedType"))
        self.gridLayout.addWidget(self.lblPrescribedType, 26, 0, 1, 1)
        self.lblNomenclativeService = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblNomenclativeService.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNomenclativeService.sizePolicy().hasHeightForWidth())
        self.lblNomenclativeService.setSizePolicy(sizePolicy)
        self.lblNomenclativeService.setScaledContents(False)
        self.lblNomenclativeService.setObjectName(_fromUtf8("lblNomenclativeService"))
        self.gridLayout.addWidget(self.lblNomenclativeService, 1, 0, 1, 1)
        self.lblClass = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblClass.setObjectName(_fromUtf8("lblClass"))
        self.gridLayout.addWidget(self.lblClass, 5, 0, 1, 1)
        self.lblAssistantRequired = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblAssistantRequired.setObjectName(_fromUtf8("lblAssistantRequired"))
        self.gridLayout.addWidget(self.lblAssistantRequired, 16, 0, 1, 1)
        self.frmSex = QtGui.QHBoxLayout()
        self.frmSex.setObjectName(_fromUtf8("frmSex"))
        self.cmbSex = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.frmSex.addWidget(self.cmbSex)
        spacerItem6 = QtGui.QSpacerItem(321, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.frmSex.addItem(spacerItem6)
        self.gridLayout.addLayout(self.frmSex, 8, 1, 1, 1)
        self.lblLisCode = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblLisCode.setObjectName(_fromUtf8("lblLisCode"))
        self.gridLayout.addWidget(self.lblLisCode, 4, 0, 1, 1)
        self.edtLisCode = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtLisCode.setObjectName(_fromUtf8("edtLisCode"))
        self.gridLayout.addWidget(self.edtLisCode, 4, 1, 1, 1)
        self.frmGroup = QtGui.QHBoxLayout()
        self.frmGroup.setObjectName(_fromUtf8("frmGroup"))
        self.cmbGroup = CRBComboBox(self.scrollAreaWidgetContents)
        self.cmbGroup.setMinimumSize(QtCore.QSize(100, 0))
        self.cmbGroup.setObjectName(_fromUtf8("cmbGroup"))
        self.frmGroup.addWidget(self.cmbGroup)
        spacerItem7 = QtGui.QSpacerItem(175, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.frmGroup.addItem(spacerItem7)
        self.gridLayout.addLayout(self.frmGroup, 6, 1, 1, 1)
        self.frmClass = QtGui.QHBoxLayout()
        self.frmClass.setObjectName(_fromUtf8("frmClass"))
        self.cmbClass = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbClass.setObjectName(_fromUtf8("cmbClass"))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.frmClass.addWidget(self.cmbClass)
        spacerItem8 = QtGui.QSpacerItem(171, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.frmClass.addItem(spacerItem8)
        self.gridLayout.addLayout(self.frmClass, 5, 1, 1, 1)
        self.lblFrequency = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblFrequency.setObjectName(_fromUtf8("lblFrequency"))
        self.gridLayout.addWidget(self.lblFrequency, 18, 0, 1, 1)
        self.lblName = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 2, 0, 1, 1)
        self.lblSex = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout.addWidget(self.lblSex, 8, 0, 1, 1)
        self.lblContext = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblContext.setObjectName(_fromUtf8("lblContext"))
        self.gridLayout.addWidget(self.lblContext, 24, 0, 1, 1)
        self.edtFlatCode = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFlatCode.sizePolicy().hasHeightForWidth())
        self.edtFlatCode.setSizePolicy(sizePolicy)
        self.edtFlatCode.setObjectName(_fromUtf8("edtFlatCode"))
        self.gridLayout.addWidget(self.edtFlatCode, 7, 1, 1, 1)
        self.cmbAssistantRequired = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbAssistantRequired.setObjectName(_fromUtf8("cmbAssistantRequired"))
        self.cmbAssistantRequired.addItem(_fromUtf8(""))
        self.cmbAssistantRequired.addItem(_fromUtf8(""))
        self.cmbAssistantRequired.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbAssistantRequired, 16, 1, 1, 1)
        self.chkGenTimetable = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkGenTimetable.setEnabled(False)
        self.chkGenTimetable.setObjectName(_fromUtf8("chkGenTimetable"))
        self.gridLayout.addWidget(self.chkGenTimetable, 22, 1, 1, 1)
        self.frmPrescribed = QtGui.QHBoxLayout()
        self.frmPrescribed.setObjectName(_fromUtf8("frmPrescribed"))
        self.cmbPrescribedType = CRBComboBox(self.scrollAreaWidgetContents)
        self.cmbPrescribedType.setObjectName(_fromUtf8("cmbPrescribedType"))
        self.frmPrescribed.addWidget(self.cmbPrescribedType)
        self.cmbShedule = CRBComboBox(self.scrollAreaWidgetContents)
        self.cmbShedule.setObjectName(_fromUtf8("cmbShedule"))
        self.frmPrescribed.addWidget(self.cmbShedule)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.frmPrescribed.addItem(spacerItem9)
        self.gridLayout.addLayout(self.frmPrescribed, 26, 1, 1, 1)
        self.frmOccurs = QtGui.QHBoxLayout()
        self.frmOccurs.setObjectName(_fromUtf8("frmOccurs"))
        self.edtMaxOccursInEvent = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMaxOccursInEvent.sizePolicy().hasHeightForWidth())
        self.edtMaxOccursInEvent.setSizePolicy(sizePolicy)
        self.edtMaxOccursInEvent.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.edtMaxOccursInEvent.setObjectName(_fromUtf8("edtMaxOccursInEvent"))
        self.frmOccurs.addWidget(self.edtMaxOccursInEvent)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.frmOccurs.addItem(spacerItem10)
        self.gridLayout.addLayout(self.frmOccurs, 21, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 32, 0, 1, 2)
        self.lblFrequency_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblFrequency_2.setObjectName(_fromUtf8("lblFrequency_2"))
        self.gridLayout.addWidget(self.lblFrequency_2, 29, 0, 1, 1)
        self.chkShowAPOrg = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkShowAPOrg.setObjectName(_fromUtf8("chkShowAPOrg"))
        self.gridLayout.addWidget(self.chkShowAPOrg, 12, 1, 1, 1)
        self.chkShowAPNotes = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkShowAPNotes.setObjectName(_fromUtf8("chkShowAPNotes"))
        self.gridLayout.addWidget(self.chkShowAPNotes, 13, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tabMain, _fromUtf8(""))
        self.tabDefaults = QtGui.QWidget()
        self.tabDefaults.setObjectName(_fromUtf8("tabDefaults"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabDefaults)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tabDefaults)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 680, 1176))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.cmbDefaultBeginDate = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        self.cmbDefaultBeginDate.setObjectName(_fromUtf8("cmbDefaultBeginDate"))
        self.cmbDefaultBeginDate.addItem(_fromUtf8(""))
        self.cmbDefaultBeginDate.addItem(_fromUtf8(""))
        self.cmbDefaultBeginDate.addItem(_fromUtf8(""))
        self.cmbDefaultBeginDate.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbDefaultBeginDate, 5, 1, 1, 2)
        self.lblDefaultSetPerson = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblDefaultSetPerson.setObjectName(_fromUtf8("lblDefaultSetPerson"))
        self.gridLayout_4.addWidget(self.lblDefaultSetPerson, 6, 0, 1, 1)
        self.chkIsSubstituteEndDateToEvent = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkIsSubstituteEndDateToEvent.setObjectName(_fromUtf8("chkIsSubstituteEndDateToEvent"))
        self.gridLayout_4.addWidget(self.chkIsSubstituteEndDateToEvent, 3, 0, 1, 3)
        self.lblDefaultPlannedEndDate = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblDefaultPlannedEndDate.setObjectName(_fromUtf8("lblDefaultPlannedEndDate"))
        self.gridLayout_4.addWidget(self.lblDefaultPlannedEndDate, 1, 0, 1, 1)
        self.lblDefaultPersonInEditor = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblDefaultPersonInEditor.setObjectName(_fromUtf8("lblDefaultPersonInEditor"))
        self.gridLayout_4.addWidget(self.lblDefaultPersonInEditor, 9, 0, 1, 1)
        self.cmbDefaultMKB = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        self.cmbDefaultMKB.setObjectName(_fromUtf8("cmbDefaultMKB"))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbDefaultMKB, 10, 1, 1, 2)
        self.lblDefaultMES = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblDefaultMES.setObjectName(_fromUtf8("lblDefaultMES"))
        self.gridLayout_4.addWidget(self.lblDefaultMES, 12, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.cmbDefaultExecPerson = CPersonComboBoxEx(self.scrollAreaWidgetContents_2)
        self.cmbDefaultExecPerson.setObjectName(_fromUtf8("cmbDefaultExecPerson"))
        self.horizontalLayout_6.addWidget(self.cmbDefaultExecPerson)
        self.btnClearDefaultExecPerson = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.btnClearDefaultExecPerson.setMaximumSize(QtCore.QSize(70, 16777214))
        self.btnClearDefaultExecPerson.setObjectName(_fromUtf8("btnClearDefaultExecPerson"))
        self.horizontalLayout_6.addWidget(self.btnClearDefaultExecPerson)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 7, 1, 1, 2)
        self.lblDefaultExecPerson = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblDefaultExecPerson.setObjectName(_fromUtf8("lblDefaultExecPerson"))
        self.gridLayout_4.addWidget(self.lblDefaultExecPerson, 7, 0, 1, 1)
        self.cmbCounter = CRBComboBox(self.scrollAreaWidgetContents_2)
        self.cmbCounter.setObjectName(_fromUtf8("cmbCounter"))
        self.gridLayout_4.addWidget(self.cmbCounter, 15, 1, 1, 2)
        self.cmbDefaultOrg = CPolyclinicComboBox(self.scrollAreaWidgetContents_2)
        self.cmbDefaultOrg.setObjectName(_fromUtf8("cmbDefaultOrg"))
        self.gridLayout_4.addWidget(self.cmbDefaultOrg, 14, 1, 1, 2)
        self.cmbDefaultMorphology = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        self.cmbDefaultMorphology.setObjectName(_fromUtf8("cmbDefaultMorphology"))
        self.cmbDefaultMorphology.addItem(_fromUtf8(""))
        self.cmbDefaultMorphology.addItem(_fromUtf8(""))
        self.cmbDefaultMorphology.addItem(_fromUtf8(""))
        self.cmbDefaultMorphology.addItem(_fromUtf8(""))
        self.cmbDefaultMorphology.addItem(_fromUtf8(""))
        self.cmbDefaultMorphology.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbDefaultMorphology, 11, 1, 1, 2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.edtAmount = QtGui.QSpinBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmount.sizePolicy().hasHeightForWidth())
        self.edtAmount.setSizePolicy(sizePolicy)
        self.edtAmount.setObjectName(_fromUtf8("edtAmount"))
        self.horizontalLayout_3.addWidget(self.edtAmount)
        self.cmbAmountEvaluation = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAmountEvaluation.sizePolicy().hasHeightForWidth())
        self.cmbAmountEvaluation.setSizePolicy(sizePolicy)
        self.cmbAmountEvaluation.setObjectName(_fromUtf8("cmbAmountEvaluation"))
        self.horizontalLayout_3.addWidget(self.cmbAmountEvaluation)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 16, 1, 1, 2)
        self.lblDefaultBeginDate = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblDefaultBeginDate.setObjectName(_fromUtf8("lblDefaultBeginDate"))
        self.gridLayout_4.addWidget(self.lblDefaultBeginDate, 5, 0, 1, 1)
        self.lblIsMorphologyRequired = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblIsMorphologyRequired.setObjectName(_fromUtf8("lblIsMorphologyRequired"))
        self.gridLayout_4.addWidget(self.lblIsMorphologyRequired, 13, 0, 1, 1)
        self.edtActualAppointmentDuration = QtGui.QSpinBox(self.scrollAreaWidgetContents_2)
        self.edtActualAppointmentDuration.setMaximum(32767)
        self.edtActualAppointmentDuration.setObjectName(_fromUtf8("edtActualAppointmentDuration"))
        self.gridLayout_4.addWidget(self.edtActualAppointmentDuration, 18, 1, 1, 2)
        self.lblDefaultPersonInEvent = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblDefaultPersonInEvent.setObjectName(_fromUtf8("lblDefaultPersonInEvent"))
        self.gridLayout_4.addWidget(self.lblDefaultPersonInEvent, 8, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tblActionSpecialities = CInDocTableView(self.groupBox_2)
        self.tblActionSpecialities.setMinimumSize(QtCore.QSize(0, 200))
        self.tblActionSpecialities.setObjectName(_fromUtf8("tblActionSpecialities"))
        self.gridLayout_8.addWidget(self.tblActionSpecialities, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 22, 0, 1, 3)
        self.chkExecRequiredForEventExec = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkExecRequiredForEventExec.setObjectName(_fromUtf8("chkExecRequiredForEventExec"))
        self.gridLayout_4.addWidget(self.chkExecRequiredForEventExec, 19, 0, 1, 3)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.chkPropertyAssignedVisible = QtGui.QCheckBox(self.groupBox)
        self.chkPropertyAssignedVisible.setChecked(True)
        self.chkPropertyAssignedVisible.setObjectName(_fromUtf8("chkPropertyAssignedVisible"))
        self.verticalLayout_2.addWidget(self.chkPropertyAssignedVisible)
        self.chkPropertyUnitVisible = QtGui.QCheckBox(self.groupBox)
        self.chkPropertyUnitVisible.setChecked(True)
        self.chkPropertyUnitVisible.setObjectName(_fromUtf8("chkPropertyUnitVisible"))
        self.verticalLayout_2.addWidget(self.chkPropertyUnitVisible)
        self.chkPropertyNormVisible = QtGui.QCheckBox(self.groupBox)
        self.chkPropertyNormVisible.setChecked(True)
        self.chkPropertyNormVisible.setObjectName(_fromUtf8("chkPropertyNormVisible"))
        self.verticalLayout_2.addWidget(self.chkPropertyNormVisible)
        self.chkPropertyEvaluationVisible = QtGui.QCheckBox(self.groupBox)
        self.chkPropertyEvaluationVisible.setChecked(True)
        self.chkPropertyEvaluationVisible.setObjectName(_fromUtf8("chkPropertyEvaluationVisible"))
        self.verticalLayout_2.addWidget(self.chkPropertyEvaluationVisible)
        self.gridLayout_4.addWidget(self.groupBox, 21, 0, 1, 3)
        self.cmbDefaultPersonInEditor = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        self.cmbDefaultPersonInEditor.setObjectName(_fromUtf8("cmbDefaultPersonInEditor"))
        self.cmbDefaultPersonInEditor.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEditor.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEditor.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEditor.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEditor.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbDefaultPersonInEditor, 9, 1, 1, 2)
        self.lblDefaultStatus = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblDefaultStatus.setObjectName(_fromUtf8("lblDefaultStatus"))
        self.gridLayout_4.addWidget(self.lblDefaultStatus, 0, 0, 1, 1)
        self.lblDefaultMorphology = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblDefaultMorphology.setObjectName(_fromUtf8("lblDefaultMorphology"))
        self.gridLayout_4.addWidget(self.lblDefaultMorphology, 11, 0, 1, 1)
        self.cmbDefaultEndDate = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDefaultEndDate.sizePolicy().hasHeightForWidth())
        self.cmbDefaultEndDate.setSizePolicy(sizePolicy)
        self.cmbDefaultEndDate.setObjectName(_fromUtf8("cmbDefaultEndDate"))
        self.cmbDefaultEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultEndDate.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbDefaultEndDate, 2, 1, 1, 2)
        self.lblOffice = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblOffice.setObjectName(_fromUtf8("lblOffice"))
        self.gridLayout_4.addWidget(self.lblOffice, 17, 0, 1, 1)
        self.lblAmount = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblAmount.setObjectName(_fromUtf8("lblAmount"))
        self.gridLayout_4.addWidget(self.lblAmount, 16, 0, 1, 1)
        self.cmbDefaultPersonInEvent = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        self.cmbDefaultPersonInEvent.setObjectName(_fromUtf8("cmbDefaultPersonInEvent"))
        self.cmbDefaultPersonInEvent.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEvent.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEvent.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEvent.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEvent.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbDefaultPersonInEvent, 8, 1, 1, 2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.cmbDefaultSetPerson = CPersonComboBoxEx(self.scrollAreaWidgetContents_2)
        self.cmbDefaultSetPerson.setObjectName(_fromUtf8("cmbDefaultSetPerson"))
        self.horizontalLayout_5.addWidget(self.cmbDefaultSetPerson)
        self.btnClearDefaultSetPerson = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.btnClearDefaultSetPerson.setMaximumSize(QtCore.QSize(70, 16777215))
        self.btnClearDefaultSetPerson.setObjectName(_fromUtf8("btnClearDefaultSetPerson"))
        self.horizontalLayout_5.addWidget(self.btnClearDefaultSetPerson)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 6, 1, 1, 2)
        self.cmbIsMorphologyRequired = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        self.cmbIsMorphologyRequired.setObjectName(_fromUtf8("cmbIsMorphologyRequired"))
        self.cmbIsMorphologyRequired.addItem(_fromUtf8(""))
        self.cmbIsMorphologyRequired.addItem(_fromUtf8(""))
        self.cmbIsMorphologyRequired.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbIsMorphologyRequired, 13, 1, 1, 2)
        self.edtOffice = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtOffice.sizePolicy().hasHeightForWidth())
        self.edtOffice.setSizePolicy(sizePolicy)
        self.edtOffice.setObjectName(_fromUtf8("edtOffice"))
        self.gridLayout_4.addWidget(self.edtOffice, 17, 1, 1, 2)
        self.cmbDefaultPlannedEndDate = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        self.cmbDefaultPlannedEndDate.setObjectName(_fromUtf8("cmbDefaultPlannedEndDate"))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbDefaultPlannedEndDate, 1, 1, 1, 2)
        self.lblDefaultEndDate = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblDefaultEndDate.setObjectName(_fromUtf8("lblDefaultEndDate"))
        self.gridLayout_4.addWidget(self.lblDefaultEndDate, 2, 0, 1, 1)
        self.cmbDefaultMES = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        self.cmbDefaultMES.setObjectName(_fromUtf8("cmbDefaultMES"))
        self.cmbDefaultMES.addItem(_fromUtf8(""))
        self.cmbDefaultMES.addItem(_fromUtf8(""))
        self.cmbDefaultMES.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbDefaultMES, 12, 1, 1, 2)
        self.lblCounter = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblCounter.setObjectName(_fromUtf8("lblCounter"))
        self.gridLayout_4.addWidget(self.lblCounter, 15, 0, 1, 1)
        self.cmbDefaultStatus = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDefaultStatus.sizePolicy().hasHeightForWidth())
        self.cmbDefaultStatus.setSizePolicy(sizePolicy)
        self.cmbDefaultStatus.setObjectName(_fromUtf8("cmbDefaultStatus"))
        self.gridLayout_4.addWidget(self.cmbDefaultStatus, 0, 1, 1, 2)
        self.lblDefaultMKB = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblDefaultMKB.setObjectName(_fromUtf8("lblDefaultMKB"))
        self.gridLayout_4.addWidget(self.lblDefaultMKB, 10, 0, 1, 1)
        self.cmbDefaultDirectionDate = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        self.cmbDefaultDirectionDate.setObjectName(_fromUtf8("cmbDefaultDirectionDate"))
        self.cmbDefaultDirectionDate.addItem(_fromUtf8(""))
        self.cmbDefaultDirectionDate.addItem(_fromUtf8(""))
        self.cmbDefaultDirectionDate.addItem(_fromUtf8(""))
        self.cmbDefaultDirectionDate.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbDefaultDirectionDate, 4, 1, 1, 2)
        self.lblActualAppointmentDuration = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblActualAppointmentDuration.setObjectName(_fromUtf8("lblActualAppointmentDuration"))
        self.gridLayout_4.addWidget(self.lblActualAppointmentDuration, 18, 0, 1, 1)
        self.lblDefaultOrg = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblDefaultOrg.setObjectName(_fromUtf8("lblDefaultOrg"))
        self.gridLayout_4.addWidget(self.lblDefaultOrg, 14, 0, 1, 1)
        self.lblDefaultDirectionDate = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblDefaultDirectionDate.setObjectName(_fromUtf8("lblDefaultDirectionDate"))
        self.gridLayout_4.addWidget(self.lblDefaultDirectionDate, 4, 0, 1, 1)
        self.chkIgnoreEventExecDate = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkIgnoreEventExecDate.setObjectName(_fromUtf8("chkIgnoreEventExecDate"))
        self.gridLayout_4.addWidget(self.chkIgnoreEventExecDate, 20, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tabDefaults, _fromUtf8(""))
        self.tabProperties = QtGui.QWidget()
        self.tabProperties.setObjectName(_fromUtf8("tabProperties"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabProperties)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblProperties = CInDocTableView(self.tabProperties)
        self.tblProperties.setObjectName(_fromUtf8("tblProperties"))
        self.gridLayout_2.addWidget(self.tblProperties, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabProperties, _fromUtf8(""))
        self.tabPayment = QtGui.QWidget()
        self.tabPayment.setObjectName(_fromUtf8("tabPayment"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabPayment)
        self.gridLayout_7.setMargin(4)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.splitter = QtGui.QSplitter(self.tabPayment)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.pnlServices = QtGui.QWidget(self.splitter)
        self.pnlServices.setObjectName(_fromUtf8("pnlServices"))
        self.gridLayout_5 = QtGui.QGridLayout(self.pnlServices)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lblServiceByFinanceType = QtGui.QLabel(self.pnlServices)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblServiceByFinanceType.sizePolicy().hasHeightForWidth())
        self.lblServiceByFinanceType.setSizePolicy(sizePolicy)
        self.lblServiceByFinanceType.setObjectName(_fromUtf8("lblServiceByFinanceType"))
        self.gridLayout_5.addWidget(self.lblServiceByFinanceType, 0, 0, 1, 1)
        self.tblServiceByFinanceType = CInDocTableView(self.pnlServices)
        self.tblServiceByFinanceType.setObjectName(_fromUtf8("tblServiceByFinanceType"))
        self.gridLayout_5.addWidget(self.tblServiceByFinanceType, 1, 0, 1, 1)
        self.pnlQuota = QtGui.QWidget(self.splitter)
        self.pnlQuota.setObjectName(_fromUtf8("pnlQuota"))
        self.gridLayout_6 = QtGui.QGridLayout(self.pnlQuota)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lblDefaultQuotaType = QtGui.QLabel(self.pnlQuota)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDefaultQuotaType.sizePolicy().hasHeightForWidth())
        self.lblDefaultQuotaType.setSizePolicy(sizePolicy)
        self.lblDefaultQuotaType.setObjectName(_fromUtf8("lblDefaultQuotaType"))
        self.gridLayout_6.addWidget(self.lblDefaultQuotaType, 0, 0, 1, 1)
        self.cmbQuotaType = CRBComboBox(self.pnlQuota)
        self.cmbQuotaType.setObjectName(_fromUtf8("cmbQuotaType"))
        self.gridLayout_6.addWidget(self.cmbQuotaType, 0, 1, 1, 1)
        self.lblQuotaType = QtGui.QLabel(self.pnlQuota)
        self.lblQuotaType.setObjectName(_fromUtf8("lblQuotaType"))
        self.gridLayout_6.addWidget(self.lblQuotaType, 1, 0, 1, 1)
        self.tblQuotaType = CInDocTableView(self.pnlQuota)
        self.tblQuotaType.setObjectName(_fromUtf8("tblQuotaType"))
        self.gridLayout_6.addWidget(self.tblQuotaType, 2, 0, 1, 2)
        self.gridLayout_7.addWidget(self.splitter, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabPayment, _fromUtf8(""))
        self.tabTissue = QtGui.QWidget()
        self.tabTissue.setObjectName(_fromUtf8("tabTissue"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabTissue)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblTissueType = CInDocTableView(self.tabTissue)
        self.tblTissueType.setObjectName(_fromUtf8("tblTissueType"))
        self.gridLayout_3.addWidget(self.tblTissueType, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.tabTissue)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabTissue, _fromUtf8(""))
        self.tabProfiles = QtGui.QWidget()
        self.tabProfiles.setObjectName(_fromUtf8("tabProfiles"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tabProfiles)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.chkSpecialitiesFilter = QtGui.QCheckBox(self.tabProfiles)
        self.chkSpecialitiesFilter.setObjectName(_fromUtf8("chkSpecialitiesFilter"))
        self.verticalLayout_7.addWidget(self.chkSpecialitiesFilter)
        self.tblSpecialitiesFilter = CRBListBox(self.tabProfiles)
        self.tblSpecialitiesFilter.setObjectName(_fromUtf8("tblSpecialitiesFilter"))
        self.verticalLayout_7.addWidget(self.tblSpecialitiesFilter)
        self.chkPostsFilter = QtGui.QCheckBox(self.tabProfiles)
        self.chkPostsFilter.setObjectName(_fromUtf8("chkPostsFilter"))
        self.verticalLayout_7.addWidget(self.chkPostsFilter)
        self.tblPostsFilter = CRBListBox(self.tabProfiles)
        self.tblPostsFilter.setObjectName(_fromUtf8("tblPostsFilter"))
        self.verticalLayout_7.addWidget(self.tblPostsFilter)
        self.tabWidget.addTab(self.tabProfiles, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(ActionTypeEditorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.lblFlatCode.setBuddy(self.edtFlatCode)
        self.lblCode.setBuddy(self.edtCode)
        self.lblLock.setBuddy(self.chkLock)
        self.lblTitle.setBuddy(self.edtTitle)
        self.lblAgeSep.setBuddy(self.cmbEndAgeUnit)
        self.lblGroup.setBuddy(self.cmbGroup)
        self.lblAge.setBuddy(self.cmbBegAgeUnit)
        self.lblMaxOccursInEvent2.setBuddy(self.edtMaxOccursInEvent)
        self.lblPrescribedType.setBuddy(self.cmbPrescribedType)
        self.lblNomenclativeService.setBuddy(self.cmbNomenclativeService)
        self.lblClass.setBuddy(self.cmbClass)
        self.lblLisCode.setBuddy(self.edtLisCode)
        self.lblName.setBuddy(self.edtName)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblContext.setBuddy(self.edtContext)
        self.lblDefaultPlannedEndDate.setBuddy(self.cmbDefaultPlannedEndDate)
        self.lblDefaultPersonInEditor.setBuddy(self.cmbDefaultPersonInEditor)
        self.lblDefaultExecPerson.setBuddy(self.cmbDefaultExecPerson)
        self.lblDefaultPersonInEvent.setBuddy(self.cmbDefaultPersonInEvent)
        self.lblDefaultStatus.setBuddy(self.cmbDefaultStatus)
        self.lblDefaultMorphology.setBuddy(self.cmbDefaultMKB)
        self.lblOffice.setBuddy(self.edtOffice)
        self.lblAmount.setBuddy(self.edtAmount)
        self.lblDefaultEndDate.setBuddy(self.cmbDefaultEndDate)
        self.lblDefaultMKB.setBuddy(self.cmbDefaultMKB)
        self.lblDefaultDirectionDate.setBuddy(self.cmbDefaultDirectionDate)
        self.lblServiceByFinanceType.setBuddy(self.tblServiceByFinanceType)
        self.lblDefaultQuotaType.setBuddy(self.cmbQuotaType)
        self.lblQuotaType.setBuddy(self.tblQuotaType)

        self.retranslateUi(ActionTypeEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ActionTypeEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ActionTypeEditorDialog.reject)
        QtCore.QObject.connect(self.chkIsPrinted, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblContext.setEnabled)
        QtCore.QObject.connect(self.chkIsPrinted, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtContext.setEnabled)
        QtCore.QObject.connect(self.chkSpecialitiesFilter, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.tblSpecialitiesFilter.setEnabled)
        QtCore.QObject.connect(self.chkPostsFilter, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.tblPostsFilter.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ActionTypeEditorDialog)
        ActionTypeEditorDialog.setTabOrder(self.edtName, self.edtTitle)
        ActionTypeEditorDialog.setTabOrder(self.edtTitle, self.edtFlatCode)
        ActionTypeEditorDialog.setTabOrder(self.edtFlatCode, self.chkIsMES)
        ActionTypeEditorDialog.setTabOrder(self.chkIsMES, self.chkShowTime)
        ActionTypeEditorDialog.setTabOrder(self.chkShowTime, self.chkRequiredCoordination)
        ActionTypeEditorDialog.setTabOrder(self.chkRequiredCoordination, self.chkShowInForm)
        ActionTypeEditorDialog.setTabOrder(self.chkShowInForm, self.chkGenTimetable)
        ActionTypeEditorDialog.setTabOrder(self.chkGenTimetable, self.edtContext)
        ActionTypeEditorDialog.setTabOrder(self.edtContext, self.chkIsPreferable)
        ActionTypeEditorDialog.setTabOrder(self.chkIsPreferable, self.chkNomenclatureExpense)
        ActionTypeEditorDialog.setTabOrder(self.chkNomenclatureExpense, self.cmbDefaultStatus)
        ActionTypeEditorDialog.setTabOrder(self.cmbDefaultStatus, self.cmbDefaultPlannedEndDate)
        ActionTypeEditorDialog.setTabOrder(self.cmbDefaultPlannedEndDate, self.cmbDefaultEndDate)
        ActionTypeEditorDialog.setTabOrder(self.cmbDefaultEndDate, self.cmbDefaultDirectionDate)
        ActionTypeEditorDialog.setTabOrder(self.cmbDefaultDirectionDate, self.cmbDefaultPersonInEvent)
        ActionTypeEditorDialog.setTabOrder(self.cmbDefaultPersonInEvent, self.cmbDefaultPersonInEditor)
        ActionTypeEditorDialog.setTabOrder(self.cmbDefaultPersonInEditor, self.cmbDefaultMKB)
        ActionTypeEditorDialog.setTabOrder(self.cmbDefaultMKB, self.cmbIsMorphologyRequired)
        ActionTypeEditorDialog.setTabOrder(self.cmbIsMorphologyRequired, self.cmbDefaultOrg)
        ActionTypeEditorDialog.setTabOrder(self.cmbDefaultOrg, self.edtOffice)
        ActionTypeEditorDialog.setTabOrder(self.edtOffice, self.edtActualAppointmentDuration)
        ActionTypeEditorDialog.setTabOrder(self.edtActualAppointmentDuration, self.chkPropertyAssignedVisible)
        ActionTypeEditorDialog.setTabOrder(self.chkPropertyAssignedVisible, self.chkPropertyUnitVisible)
        ActionTypeEditorDialog.setTabOrder(self.chkPropertyUnitVisible, self.chkPropertyNormVisible)
        ActionTypeEditorDialog.setTabOrder(self.chkPropertyNormVisible, self.chkPropertyEvaluationVisible)
        ActionTypeEditorDialog.setTabOrder(self.chkPropertyEvaluationVisible, self.tblProperties)
        ActionTypeEditorDialog.setTabOrder(self.tblProperties, self.tblServiceByFinanceType)
        ActionTypeEditorDialog.setTabOrder(self.tblServiceByFinanceType, self.cmbQuotaType)
        ActionTypeEditorDialog.setTabOrder(self.cmbQuotaType, self.tblQuotaType)
        ActionTypeEditorDialog.setTabOrder(self.tblQuotaType, self.tblTissueType)

    def retranslateUi(self, ActionTypeEditorDialog):
        ActionTypeEditorDialog.setWindowTitle(_translate("ActionTypeEditorDialog", "ChangeMe!", None))
        self.lblFrequencyCount_2.setText(_translate("ActionTypeEditorDialog", "дней", None))
        self.chkRecommendationControl.setText(_translate("ActionTypeEditorDialog", "Контроль назначившего", None))
        self.chkShowInForm.setText(_translate("ActionTypeEditorDialog", "Разрешается выбор в формах ввода событий", None))
        self.chkFilledLock.setText(_translate("ActionTypeEditorDialog", "Запретить удаление в обращении действий с заполненными свойствами", None))
        self.chkNomenclatureExpense.setText(_translate("ActionTypeEditorDialog", "Связано со списанием ЛСиИМН", None))
        self.chkIsPreferable.setText(_translate("ActionTypeEditorDialog", "Является предпочитаемым(-ой)", None))
        self.btnSetName.setToolTip(_translate("ActionTypeEditorDialog", "Установить наименование по наименованию номенклатурной услуги", None))
        self.btnSetName.setText(_translate("ActionTypeEditorDialog", "...", None))
        self.btnSelectService.setText(_translate("ActionTypeEditorDialog", "...", None))
        self.chkIsPrinted.setText(_translate("ActionTypeEditorDialog", "Вывод на печать (анализируется шаблоном печати)", None))
        self.chkLock.setText(_translate("ActionTypeEditorDialog", "Разрешить удаление типа действия в справочнике только администратору\n"
"и пользователям, имеющим соответствующее право", None))
        self.lblFlatCode.setText(_translate("ActionTypeEditorDialog", "Код для &отчётов", None))
        self.lblServiceType.setText(_translate("ActionTypeEditorDialog", "Вид услуги", None))
        self.chkIsMES.setText(_translate("ActionTypeEditorDialog", "Стандарт", None))
        self.lblCode.setText(_translate("ActionTypeEditorDialog", "&Код", None))
        self.lblFrequencyCount.setText(_translate("ActionTypeEditorDialog", "раз в", None))
        self.cmbFrequencyPeriodType.setItemText(0, _translate("ActionTypeEditorDialog", "-", None))
        self.cmbFrequencyPeriodType.setItemText(1, _translate("ActionTypeEditorDialog", "День", None))
        self.cmbFrequencyPeriodType.setItemText(2, _translate("ActionTypeEditorDialog", "Неделю", None))
        self.cmbFrequencyPeriodType.setItemText(3, _translate("ActionTypeEditorDialog", "Месяц", None))
        self.cmbFrequencyPeriodType.setItemText(4, _translate("ActionTypeEditorDialog", "Квартал", None))
        self.cmbFrequencyPeriodType.setItemText(5, _translate("ActionTypeEditorDialog", "Полугодие", None))
        self.cmbFrequencyPeriodType.setItemText(6, _translate("ActionTypeEditorDialog", "Год", None))
        self.lblLock.setText(_translate("ActionTypeEditorDialog", "Заблокировать", None))
        self.lblTitle.setText(_translate("ActionTypeEditorDialog", "Наименование для &печати", None))
        self.chkRequiredCoordination.setText(_translate("ActionTypeEditorDialog", "Требует обязательного согласования", None))
        self.cmbBegAgeUnit.setItemText(1, _translate("ActionTypeEditorDialog", "Д", None))
        self.cmbBegAgeUnit.setItemText(2, _translate("ActionTypeEditorDialog", "Н", None))
        self.cmbBegAgeUnit.setItemText(3, _translate("ActionTypeEditorDialog", "М", None))
        self.cmbBegAgeUnit.setItemText(4, _translate("ActionTypeEditorDialog", "Г", None))
        self.edtBegAgeCount.setInputMask(_translate("ActionTypeEditorDialog", "000; ", None))
        self.lblAgeSep.setText(_translate("ActionTypeEditorDialog", "по", None))
        self.cmbEndAgeUnit.setItemText(1, _translate("ActionTypeEditorDialog", "Д", None))
        self.cmbEndAgeUnit.setItemText(2, _translate("ActionTypeEditorDialog", "Н", None))
        self.cmbEndAgeUnit.setItemText(3, _translate("ActionTypeEditorDialog", "М", None))
        self.cmbEndAgeUnit.setItemText(4, _translate("ActionTypeEditorDialog", "Г", None))
        self.edtEndAgeCount.setInputMask(_translate("ActionTypeEditorDialog", "000; ", None))
        self.chkShowTime.setText(_translate("ActionTypeEditorDialog", "Показывать в интерфейсе время назначения/начала/окончания", None))
        self.chkIsCustomSum.setText(_translate("ActionTypeEditorDialog", "Возможно указание произвольной цены", None))
        self.lblGroup.setText(_translate("ActionTypeEditorDialog", "&Группа", None))
        self.lblAge.setText(_translate("ActionTypeEditorDialog", "&Возраст", None))
        self.chkFrequencyPeriodByCalendar.setToolTip(_translate("ActionTypeEditorDialog", "<html><head/><body><p>Если включено, то правило &quot;1 раз в 1 неделю&quot; будет означать </p><p><span style=\" font-weight:600; font-style:italic;\">&quot;один раз за текущую календарную неделю&quot;</span>, </p><p>иначе - <span style=\" font-weight:600; font-style:italic;\">&quot;один раз за последние 7 дней&quot;</span></p></body></html>", None))
        self.chkFrequencyPeriodByCalendar.setText(_translate("ActionTypeEditorDialog", "Календарные периоды", None))
        self.chkStrictFrequency.setText(_translate("ActionTypeEditorDialog", "Жесткая проверка", None))
        self.lblMaxOccursInEvent2.setText(_translate("ActionTypeEditorDialog", "Макс. количество в событии", None))
        self.lblPrescribedType.setText(_translate("ActionTypeEditorDialog", "Является назначением для", None))
        self.lblNomenclativeService.setText(_translate("ActionTypeEditorDialog", "&Номенклатурная услуга", None))
        self.lblClass.setText(_translate("ActionTypeEditorDialog", "Кла&сс", None))
        self.lblAssistantRequired.setText(_translate("ActionTypeEditorDialog", "Ввод ассистента", None))
        self.cmbSex.setItemText(1, _translate("ActionTypeEditorDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("ActionTypeEditorDialog", "Ж", None))
        self.lblLisCode.setText(_translate("ActionTypeEditorDialog", "Код в лабораторной системе", None))
        self.cmbClass.setItemText(0, _translate("ActionTypeEditorDialog", "Статус", None))
        self.cmbClass.setItemText(1, _translate("ActionTypeEditorDialog", "Диагностика", None))
        self.cmbClass.setItemText(2, _translate("ActionTypeEditorDialog", "Лечение", None))
        self.cmbClass.setItemText(3, _translate("ActionTypeEditorDialog", "Прочие мероприятия", None))
        self.cmbClass.setItemText(4, _translate("ActionTypeEditorDialog", "Анализы", None))
        self.lblFrequency.setText(_translate("ActionTypeEditorDialog", "Допустимая частота\n"
"повторных назначений", None))
        self.lblName.setText(_translate("ActionTypeEditorDialog", "На&именование", None))
        self.lblSex.setText(_translate("ActionTypeEditorDialog", "&Пол", None))
        self.lblContext.setText(_translate("ActionTypeEditorDialog", "Контекст пе&чати", None))
        self.cmbAssistantRequired.setItemText(0, _translate("ActionTypeEditorDialog", "Не требуется", None))
        self.cmbAssistantRequired.setItemText(1, _translate("ActionTypeEditorDialog", "Необязательное заполнение", None))
        self.cmbAssistantRequired.setItemText(2, _translate("ActionTypeEditorDialog", "Обязательное заполнение", None))
        self.chkGenTimetable.setText(_translate("ActionTypeEditorDialog", "Генерирует гра&фик", None))
        self.edtMaxOccursInEvent.setToolTip(_translate("ActionTypeEditorDialog", "0 - нет ограничения", None))
        self.lblFrequency_2.setText(_translate("ActionTypeEditorDialog", "Период актуальности\n"
"направления", None))
        self.chkShowAPOrg.setText(_translate("ActionTypeEditorDialog", "Показывать в интерфейсе \"место выполнения\"", None))
        self.chkShowAPNotes.setText(_translate("ActionTypeEditorDialog", "Показывать в интерфейсе \"примечания\"", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("ActionTypeEditorDialog", "Основная информация", None))
        self.cmbDefaultBeginDate.setItemText(0, _translate("ActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultBeginDate.setItemText(1, _translate("ActionTypeEditorDialog", "Текущая дата", None))
        self.cmbDefaultBeginDate.setItemText(2, _translate("ActionTypeEditorDialog", "Дата начала события", None))
        self.cmbDefaultBeginDate.setItemText(3, _translate("ActionTypeEditorDialog", "Дата окончания события", None))
        self.lblDefaultSetPerson.setText(_translate("ActionTypeEditorDialog", "Назначивший по умолчанию", None))
        self.chkIsSubstituteEndDateToEvent.setText(_translate("ActionTypeEditorDialog", "Подстановка даты окончания действия в дату окончания события", None))
        self.lblDefaultPlannedEndDate.setText(_translate("ActionTypeEditorDialog", "Планируемая дата выполнения", None))
        self.lblDefaultPersonInEditor.setText(_translate("ActionTypeEditorDialog", "Исполнитель в отд.редакторе", None))
        self.cmbDefaultMKB.setItemText(0, _translate("ActionTypeEditorDialog", "Не используется", None))
        self.cmbDefaultMKB.setItemText(1, _translate("ActionTypeEditorDialog", "По заключительному", None))
        self.cmbDefaultMKB.setItemText(2, _translate("ActionTypeEditorDialog", "По диагнозу назначившего действие", None))
        self.cmbDefaultMKB.setItemText(3, _translate("ActionTypeEditorDialog", "Синхронизировать с заключительным", None))
        self.cmbDefaultMKB.setItemText(4, _translate("ActionTypeEditorDialog", "Синхронизировать с диагнозом назначившего действие", None))
        self.cmbDefaultMKB.setItemText(5, _translate("ActionTypeEditorDialog", "Пустой", None))
        self.lblDefaultMES.setText(_translate("ActionTypeEditorDialog", "Стандарт", None))
        self.btnClearDefaultExecPerson.setText(_translate("ActionTypeEditorDialog", "Очистить", None))
        self.lblDefaultExecPerson.setText(_translate("ActionTypeEditorDialog", "Исполнитель по умолчанию", None))
        self.cmbDefaultMorphology.setItemText(0, _translate("ActionTypeEditorDialog", "Не используется", None))
        self.cmbDefaultMorphology.setItemText(1, _translate("ActionTypeEditorDialog", "По заключительному", None))
        self.cmbDefaultMorphology.setItemText(2, _translate("ActionTypeEditorDialog", "По диагнозу назначившего действие", None))
        self.cmbDefaultMorphology.setItemText(3, _translate("ActionTypeEditorDialog", "Синхронизировать с заключительным", None))
        self.cmbDefaultMorphology.setItemText(4, _translate("ActionTypeEditorDialog", "Синхронизировать с диагнозом назначившего действие", None))
        self.cmbDefaultMorphology.setItemText(5, _translate("ActionTypeEditorDialog", "Пустой", None))
        self.lblDefaultBeginDate.setText(_translate("ActionTypeEditorDialog", "Дата начала", None))
        self.lblIsMorphologyRequired.setText(_translate("ActionTypeEditorDialog", "Заполнение `морфологии`", None))
        self.lblDefaultPersonInEvent.setText(_translate("ActionTypeEditorDialog", "Исполнитель в событии", None))
        self.groupBox_2.setTitle(_translate("ActionTypeEditorDialog", "Допустимая специальность выполнившего врача", None))
        self.chkExecRequiredForEventExec.setText(_translate("ActionTypeEditorDialog", "Контроль выполнения услуги в законченном событии (Да/Нет)", None))
        self.groupBox.setTitle(_translate("ActionTypeEditorDialog", "Настройка визуализации колонок свойств в редакторе Действия", None))
        self.chkPropertyAssignedVisible.setText(_translate("ActionTypeEditorDialog", "Колонка `назначено`", None))
        self.chkPropertyUnitVisible.setText(_translate("ActionTypeEditorDialog", "Колонка `единица измерения`", None))
        self.chkPropertyNormVisible.setText(_translate("ActionTypeEditorDialog", "Колонка `норма`", None))
        self.chkPropertyEvaluationVisible.setText(_translate("ActionTypeEditorDialog", "Колонка `оценка`", None))
        self.cmbDefaultPersonInEditor.setItemText(0, _translate("ActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultPersonInEditor.setItemText(1, _translate("ActionTypeEditorDialog", "Не заполняется", None))
        self.cmbDefaultPersonInEditor.setItemText(2, _translate("ActionTypeEditorDialog", "Назначивший действие", None))
        self.cmbDefaultPersonInEditor.setItemText(3, _translate("ActionTypeEditorDialog", "Ответственный за событие", None))
        self.cmbDefaultPersonInEditor.setItemText(4, _translate("ActionTypeEditorDialog", "Пользователь", None))
        self.lblDefaultStatus.setText(_translate("ActionTypeEditorDialog", "С&остояние", None))
        self.lblDefaultMorphology.setText(_translate("ActionTypeEditorDialog", "Морфология по умолчанию", None))
        self.cmbDefaultEndDate.setItemText(0, _translate("ActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultEndDate.setItemText(1, _translate("ActionTypeEditorDialog", "Текущая дата", None))
        self.cmbDefaultEndDate.setItemText(2, _translate("ActionTypeEditorDialog", "Дата начала события", None))
        self.cmbDefaultEndDate.setItemText(3, _translate("ActionTypeEditorDialog", "Дата окончания события", None))
        self.lblOffice.setText(_translate("ActionTypeEditorDialog", "Кабине&т", None))
        self.lblAmount.setText(_translate("ActionTypeEditorDialog", "Ко&личество", None))
        self.cmbDefaultPersonInEvent.setItemText(0, _translate("ActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultPersonInEvent.setItemText(1, _translate("ActionTypeEditorDialog", "Не заполняется", None))
        self.cmbDefaultPersonInEvent.setItemText(2, _translate("ActionTypeEditorDialog", "Назначивший действие", None))
        self.cmbDefaultPersonInEvent.setItemText(3, _translate("ActionTypeEditorDialog", "Ответственный за событие", None))
        self.cmbDefaultPersonInEvent.setItemText(4, _translate("ActionTypeEditorDialog", "Пользователь", None))
        self.btnClearDefaultSetPerson.setText(_translate("ActionTypeEditorDialog", "Очистить", None))
        self.cmbIsMorphologyRequired.setItemText(0, _translate("ActionTypeEditorDialog", "Не проверяется", None))
        self.cmbIsMorphologyRequired.setItemText(1, _translate("ActionTypeEditorDialog", "Мягкий контроль", None))
        self.cmbIsMorphologyRequired.setItemText(2, _translate("ActionTypeEditorDialog", "Жесткий контроль", None))
        self.cmbDefaultPlannedEndDate.setItemText(0, _translate("ActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultPlannedEndDate.setItemText(1, _translate("ActionTypeEditorDialog", "Следующий день", None))
        self.cmbDefaultPlannedEndDate.setItemText(2, _translate("ActionTypeEditorDialog", "Следующий рабочий день", None))
        self.cmbDefaultPlannedEndDate.setItemText(3, _translate("ActionTypeEditorDialog", "Дата талона на Работу", None))
        self.cmbDefaultPlannedEndDate.setItemText(4, _translate("ActionTypeEditorDialog", "Дата начала + количество", None))
        self.cmbDefaultPlannedEndDate.setItemText(5, _translate("ActionTypeEditorDialog", "Дата начала + длительность", None))
        self.lblDefaultEndDate.setText(_translate("ActionTypeEditorDialog", "&Дата окончания", None))
        self.cmbDefaultMES.setItemText(0, _translate("ActionTypeEditorDialog", "Не используется", None))
        self.cmbDefaultMES.setItemText(1, _translate("ActionTypeEditorDialog", "Стандарт из события", None))
        self.cmbDefaultMES.setItemText(2, _translate("ActionTypeEditorDialog", "Пустой", None))
        self.lblCounter.setText(_translate("ActionTypeEditorDialog", "Счетчик", None))
        self.lblDefaultMKB.setText(_translate("ActionTypeEditorDialog", "МКБ по умолчанию", None))
        self.cmbDefaultDirectionDate.setItemText(0, _translate("ActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultDirectionDate.setItemText(1, _translate("ActionTypeEditorDialog", "Дата начала события", None))
        self.cmbDefaultDirectionDate.setItemText(2, _translate("ActionTypeEditorDialog", "Текущая дата", None))
        self.cmbDefaultDirectionDate.setItemText(3, _translate("ActionTypeEditorDialog", "Синхронизация по дате выполнения", None))
        self.lblActualAppointmentDuration.setText(_translate("ActionTypeEditorDialog", "Актуальность при назначении", None))
        self.lblDefaultOrg.setText(_translate("ActionTypeEditorDialog", "Организация по умолчанию", None))
        self.lblDefaultDirectionDate.setText(_translate("ActionTypeEditorDialog", "Дата назначения", None))
        self.chkIgnoreEventExecDate.setText(_translate("ActionTypeEditorDialog", "Игнорировать дату окончания события", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDefaults), _translate("ActionTypeEditorDialog", "Умолчания", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProperties), _translate("ActionTypeEditorDialog", "Свойства", None))
        self.lblServiceByFinanceType.setText(_translate("ActionTypeEditorDialog", "&Услуга в зависимости от типа финансирования:", None))
        self.lblDefaultQuotaType.setText(_translate("ActionTypeEditorDialog", "Вид квоты по умолчанию", None))
        self.lblQuotaType.setText(_translate("ActionTypeEditorDialog", "Квотирование:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPayment), _translate("ActionTypeEditorDialog", "Услуги/Квотирование", None))
        self.label.setText(_translate("ActionTypeEditorDialog", "Возможные типы биоматериалов необходимые для выполнения действия:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTissue), _translate("ActionTypeEditorDialog", "Забор биоматериалов", None))
        self.chkSpecialitiesFilter.setText(_translate("ActionTypeEditorDialog", "Разрешить выбор только пользователям указанных специальностей", None))
        self.chkPostsFilter.setText(_translate("ActionTypeEditorDialog", "Разрешить выбор только пользователям указанных должностей", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProfiles), _translate("ActionTypeEditorDialog", "Профили", None))

from Orgs.OrgComboBox import CPolyclinicComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.InDocTable import CInDocTableView
from library.RBListBox import CRBListBox
from library.crbcombobox import CRBComboBox
