# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ActionTemplateEditor.ui'
#
# Created: Tue Jun 02 21:57:28 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ActionTemplateEditorDialog(object):
    def setupUi(self, ActionTemplateEditorDialog):
        ActionTemplateEditorDialog.setObjectName(_fromUtf8("ActionTemplateEditorDialog"))
        ActionTemplateEditorDialog.resize(487, 565)
        ActionTemplateEditorDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(ActionTemplateEditorDialog)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(ActionTemplateEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabInfo = QtGui.QWidget()
        self.tabInfo.setObjectName(_fromUtf8("tabInfo"))
        self.gridLayout = QtGui.QGridLayout(self.tabInfo)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblBaseProperties = QtGui.QLabel(self.tabInfo)
        self.lblBaseProperties.setObjectName(_fromUtf8("lblBaseProperties"))
        self.gridLayout.addWidget(self.lblBaseProperties, 0, 0, 1, 12)
        self.lblName = QtGui.QLabel(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 1, 1, 1, 2)
        self.edtName = QtGui.QLineEdit(self.tabInfo)
        self.edtName.setMinimumSize(QtCore.QSize(200, 0))
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 1, 4, 1, 8)
        self.line_2 = QtGui.QFrame(self.tabInfo)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 2, 0, 1, 1)
        self.lblActionType = QtGui.QLabel(self.tabInfo)
        self.lblActionType.setObjectName(_fromUtf8("lblActionType"))
        self.gridLayout.addWidget(self.lblActionType, 2, 1, 1, 2)
        self.cmbActionType = CActionTypeComboBox(self.tabInfo)
        self.cmbActionType.setObjectName(_fromUtf8("cmbActionType"))
        self.gridLayout.addWidget(self.cmbActionType, 2, 4, 1, 8)
        self.lblCase = QtGui.QLabel(self.tabInfo)
        self.lblCase.setObjectName(_fromUtf8("lblCase"))
        self.gridLayout.addWidget(self.lblCase, 3, 0, 1, 13)
        self.lblSex = QtGui.QLabel(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSex.sizePolicy().hasHeightForWidth())
        self.lblSex.setSizePolicy(sizePolicy)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout.addWidget(self.lblSex, 4, 1, 1, 1)
        self.cmbSex = QtGui.QComboBox(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 4, 4, 1, 2)
        spacerItem = QtGui.QSpacerItem(231, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 6, 1, 6)
        self.lblAge = QtGui.QLabel(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAge.sizePolicy().hasHeightForWidth())
        self.lblAge.setSizePolicy(sizePolicy)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout.addWidget(self.lblAge, 5, 1, 1, 1)
        self.cmbBegAgeUnit = QtGui.QComboBox(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbBegAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbBegAgeUnit.setSizePolicy(sizePolicy)
        self.cmbBegAgeUnit.setObjectName(_fromUtf8("cmbBegAgeUnit"))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbBegAgeUnit, 5, 4, 1, 2)
        self.edtBegAgeCount = QtGui.QLineEdit(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegAgeCount.sizePolicy().hasHeightForWidth())
        self.edtBegAgeCount.setSizePolicy(sizePolicy)
        self.edtBegAgeCount.setMaxLength(3)
        self.edtBegAgeCount.setObjectName(_fromUtf8("edtBegAgeCount"))
        self.gridLayout.addWidget(self.edtBegAgeCount, 5, 6, 1, 1)
        self.lblAgeSep = QtGui.QLabel(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAgeSep.sizePolicy().hasHeightForWidth())
        self.lblAgeSep.setSizePolicy(sizePolicy)
        self.lblAgeSep.setObjectName(_fromUtf8("lblAgeSep"))
        self.gridLayout.addWidget(self.lblAgeSep, 5, 7, 1, 1)
        self.cmbEndAgeUnit = QtGui.QComboBox(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEndAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbEndAgeUnit.setSizePolicy(sizePolicy)
        self.cmbEndAgeUnit.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.cmbEndAgeUnit.setObjectName(_fromUtf8("cmbEndAgeUnit"))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbEndAgeUnit, 5, 8, 1, 1)
        self.edtEndAgeCount = QtGui.QLineEdit(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndAgeCount.sizePolicy().hasHeightForWidth())
        self.edtEndAgeCount.setSizePolicy(sizePolicy)
        self.edtEndAgeCount.setMaxLength(3)
        self.edtEndAgeCount.setObjectName(_fromUtf8("edtEndAgeCount"))
        self.gridLayout.addWidget(self.edtEndAgeCount, 5, 9, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(71, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 11, 1, 1)
        self.line_3 = QtGui.QFrame(self.tabInfo)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 6, 0, 1, 1)
        self.lblName_2 = QtGui.QLabel(self.tabInfo)
        self.lblName_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName_2.sizePolicy().hasHeightForWidth())
        self.lblName_2.setSizePolicy(sizePolicy)
        self.lblName_2.setObjectName(_fromUtf8("lblName_2"))
        self.gridLayout.addWidget(self.lblName_2, 6, 1, 1, 1)
        self.edtMKBList = QtGui.QLineEdit(self.tabInfo)
        self.edtMKBList.setEnabled(False)
        self.edtMKBList.setMinimumSize(QtCore.QSize(200, 0))
        self.edtMKBList.setObjectName(_fromUtf8("edtMKBList"))
        self.gridLayout.addWidget(self.edtMKBList, 6, 4, 1, 8)
        self.lblVisibleTo = QtGui.QLabel(self.tabInfo)
        self.lblVisibleTo.setObjectName(_fromUtf8("lblVisibleTo"))
        self.gridLayout.addWidget(self.lblVisibleTo, 7, 0, 1, 12)
        self.rbVisibleToOwner = QtGui.QRadioButton(self.tabInfo)
        self.rbVisibleToOwner.setChecked(True)
        self.rbVisibleToOwner.setObjectName(_fromUtf8("rbVisibleToOwner"))
        self.gridLayout.addWidget(self.rbVisibleToOwner, 8, 0, 1, 5)
        self.cmbOwner = CPersonComboBoxEx(self.tabInfo)
        self.cmbOwner.setObjectName(_fromUtf8("cmbOwner"))
        self.gridLayout.addWidget(self.cmbOwner, 8, 5, 1, 7)
        self.rbVisibleToSpeciality = QtGui.QRadioButton(self.tabInfo)
        self.rbVisibleToSpeciality.setObjectName(_fromUtf8("rbVisibleToSpeciality"))
        self.gridLayout.addWidget(self.rbVisibleToSpeciality, 9, 0, 1, 5)
        self.cmbSpeciality = CRBComboBox(self.tabInfo)
        self.cmbSpeciality.setEnabled(False)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 9, 5, 1, 5)
        spacerItem2 = QtGui.QSpacerItem(232, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 9, 10, 1, 2)
        self.rbVisibleToAll = QtGui.QRadioButton(self.tabInfo)
        self.rbVisibleToAll.setObjectName(_fromUtf8("rbVisibleToAll"))
        self.gridLayout.addWidget(self.rbVisibleToAll, 10, 0, 1, 5)
        spacerItem3 = QtGui.QSpacerItem(51, 331, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 11, 0, 1, 2)
        self.tabWidget.addTab(self.tabInfo, _fromUtf8(""))
        self.tabProperties = QtGui.QWidget()
        self.tabProperties.setObjectName(_fromUtf8("tabProperties"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabProperties)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblStatus = QtGui.QLabel(self.tabProperties)
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))
        self.gridLayout_2.addWidget(self.lblStatus, 0, 0, 1, 1)
        self.cmbStatus = QtGui.QComboBox(self.tabProperties)
        self.cmbStatus.setObjectName(_fromUtf8("cmbStatus"))
        self.gridLayout_2.addWidget(self.cmbStatus, 0, 1, 1, 1)
        self.lblAmount = QtGui.QLabel(self.tabProperties)
        self.lblAmount.setObjectName(_fromUtf8("lblAmount"))
        self.gridLayout_2.addWidget(self.lblAmount, 0, 2, 1, 1)
        self.edtAmount = QtGui.QSpinBox(self.tabProperties)
        self.edtAmount.setObjectName(_fromUtf8("edtAmount"))
        self.gridLayout_2.addWidget(self.edtAmount, 0, 3, 1, 1)
        self.lblOffice = QtGui.QLabel(self.tabProperties)
        self.lblOffice.setObjectName(_fromUtf8("lblOffice"))
        self.gridLayout_2.addWidget(self.lblOffice, 0, 4, 1, 1)
        self.edtOffice = QtGui.QLineEdit(self.tabProperties)
        self.edtOffice.setMaxLength(16)
        self.edtOffice.setObjectName(_fromUtf8("edtOffice"))
        self.gridLayout_2.addWidget(self.edtOffice, 0, 5, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(107, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 6, 1, 1)
        self.lblPerson = QtGui.QLabel(self.tabProperties)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout_2.addWidget(self.lblPerson, 1, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(self.tabProperties)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout_2.addWidget(self.cmbPerson, 1, 1, 1, 5)
        spacerItem5 = QtGui.QSpacerItem(107, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 6, 1, 1)
        self.lblStatusNote = QtGui.QLabel(self.tabProperties)
        self.lblStatusNote.setObjectName(_fromUtf8("lblStatusNote"))
        self.gridLayout_2.addWidget(self.lblStatusNote, 2, 0, 1, 1)
        self.edtNote = QtGui.QLineEdit(self.tabProperties)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout_2.addWidget(self.edtNote, 2, 1, 1, 6)
        self.tblProps = CActionPropertiesTableView(self.tabProperties)
        self.tblProps.setEnabled(True)
        self.tblProps.setObjectName(_fromUtf8("tblProps"))
        self.gridLayout_2.addWidget(self.tblProps, 3, 0, 1, 7)
        self.tabWidget.addTab(self.tabProperties, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(ActionTemplateEditorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.lblName.setBuddy(self.edtName)
        self.lblActionType.setBuddy(self.cmbActionType)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblAge.setBuddy(self.cmbBegAgeUnit)
        self.lblAgeSep.setBuddy(self.cmbEndAgeUnit)
        self.lblName_2.setBuddy(self.edtMKBList)
        self.lblStatus.setBuddy(self.cmbStatus)
        self.lblAmount.setBuddy(self.edtAmount)
        self.lblOffice.setBuddy(self.edtOffice)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblStatusNote.setBuddy(self.edtNote)

        self.retranslateUi(ActionTemplateEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ActionTemplateEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ActionTemplateEditorDialog.reject)
        QtCore.QObject.connect(self.rbVisibleToOwner, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbOwner.setEnabled)
        QtCore.QObject.connect(self.rbVisibleToSpeciality, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbSpeciality.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ActionTemplateEditorDialog)
        ActionTemplateEditorDialog.setTabOrder(self.tabWidget, self.edtName)
        ActionTemplateEditorDialog.setTabOrder(self.edtName, self.cmbActionType)
        ActionTemplateEditorDialog.setTabOrder(self.cmbActionType, self.cmbSex)
        ActionTemplateEditorDialog.setTabOrder(self.cmbSex, self.cmbBegAgeUnit)
        ActionTemplateEditorDialog.setTabOrder(self.cmbBegAgeUnit, self.edtBegAgeCount)
        ActionTemplateEditorDialog.setTabOrder(self.edtBegAgeCount, self.cmbEndAgeUnit)
        ActionTemplateEditorDialog.setTabOrder(self.cmbEndAgeUnit, self.edtEndAgeCount)
        ActionTemplateEditorDialog.setTabOrder(self.edtEndAgeCount, self.edtMKBList)
        ActionTemplateEditorDialog.setTabOrder(self.edtMKBList, self.rbVisibleToOwner)
        ActionTemplateEditorDialog.setTabOrder(self.rbVisibleToOwner, self.cmbOwner)
        ActionTemplateEditorDialog.setTabOrder(self.cmbOwner, self.rbVisibleToSpeciality)
        ActionTemplateEditorDialog.setTabOrder(self.rbVisibleToSpeciality, self.cmbSpeciality)
        ActionTemplateEditorDialog.setTabOrder(self.cmbSpeciality, self.rbVisibleToAll)
        ActionTemplateEditorDialog.setTabOrder(self.rbVisibleToAll, self.cmbStatus)
        ActionTemplateEditorDialog.setTabOrder(self.cmbStatus, self.edtAmount)
        ActionTemplateEditorDialog.setTabOrder(self.edtAmount, self.edtOffice)
        ActionTemplateEditorDialog.setTabOrder(self.edtOffice, self.cmbPerson)
        ActionTemplateEditorDialog.setTabOrder(self.cmbPerson, self.edtNote)
        ActionTemplateEditorDialog.setTabOrder(self.edtNote, self.tblProps)
        ActionTemplateEditorDialog.setTabOrder(self.tblProps, self.buttonBox)

    def retranslateUi(self, ActionTemplateEditorDialog):
        ActionTemplateEditorDialog.setWindowTitle(_translate("ActionTemplateEditorDialog", "ChangeMe!", None))
        self.lblBaseProperties.setText(_translate("ActionTemplateEditorDialog", "Основные свойства шаблона", None))
        self.lblName.setText(_translate("ActionTemplateEditorDialog", "На&именование", None))
        self.lblActionType.setText(_translate("ActionTemplateEditorDialog", "&Тип действия", None))
        self.lblCase.setText(_translate("ActionTemplateEditorDialog", "Этот шаблон можно применять в случаях:", None))
        self.lblSex.setText(_translate("ActionTemplateEditorDialog", "&Пол", None))
        self.cmbSex.setItemText(1, _translate("ActionTemplateEditorDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("ActionTemplateEditorDialog", "Ж", None))
        self.lblAge.setText(_translate("ActionTemplateEditorDialog", "&Возраст", None))
        self.cmbBegAgeUnit.setItemText(1, _translate("ActionTemplateEditorDialog", "Д", None))
        self.cmbBegAgeUnit.setItemText(2, _translate("ActionTemplateEditorDialog", "Н", None))
        self.cmbBegAgeUnit.setItemText(3, _translate("ActionTemplateEditorDialog", "М", None))
        self.cmbBegAgeUnit.setItemText(4, _translate("ActionTemplateEditorDialog", "Г", None))
        self.edtBegAgeCount.setInputMask(_translate("ActionTemplateEditorDialog", "000; ", None))
        self.lblAgeSep.setText(_translate("ActionTemplateEditorDialog", "по", None))
        self.cmbEndAgeUnit.setItemText(1, _translate("ActionTemplateEditorDialog", "Д", None))
        self.cmbEndAgeUnit.setItemText(2, _translate("ActionTemplateEditorDialog", "Н", None))
        self.cmbEndAgeUnit.setItemText(3, _translate("ActionTemplateEditorDialog", "М", None))
        self.cmbEndAgeUnit.setItemText(4, _translate("ActionTemplateEditorDialog", "Г", None))
        self.edtEndAgeCount.setInputMask(_translate("ActionTemplateEditorDialog", "000; ", None))
        self.lblName_2.setText(_translate("ActionTemplateEditorDialog", "&Диагнозы", None))
        self.lblVisibleTo.setText(_translate("ActionTemplateEditorDialog", "Этот шаблон могут применять:", None))
        self.rbVisibleToOwner.setText(_translate("ActionTemplateEditorDialog", "Врач", None))
        self.rbVisibleToSpeciality.setText(_translate("ActionTemplateEditorDialog", "Специальность", None))
        self.rbVisibleToAll.setText(_translate("ActionTemplateEditorDialog", "Все", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInfo), _translate("ActionTemplateEditorDialog", "Описание", None))
        self.lblStatus.setText(_translate("ActionTemplateEditorDialog", "Статус", None))
        self.lblAmount.setText(_translate("ActionTemplateEditorDialog", "Количество", None))
        self.lblOffice.setText(_translate("ActionTemplateEditorDialog", "Кабинет", None))
        self.lblPerson.setText(_translate("ActionTemplateEditorDialog", "Исполнитель", None))
        self.lblStatusNote.setText(_translate("ActionTemplateEditorDialog", "Примечания", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProperties), _translate("ActionTemplateEditorDialog", "Свойства", None))

from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.crbcombobox import CRBComboBox
from Events.ActionPropertiesTable import CActionPropertiesTableView
from Events.ActionTypeComboBox import CActionTypeComboBox
