# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EventTypeEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ItemEditorDialog(object):
    def setupUi(self, ItemEditorDialog):
        ItemEditorDialog.setObjectName(_fromUtf8("ItemEditorDialog"))
        ItemEditorDialog.resize(1020, 744)
        ItemEditorDialog.setSizeGripEnabled(True)
        self.gridLayout_8 = QtGui.QGridLayout(ItemEditorDialog)
        self.gridLayout_8.setMargin(4)
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        spacerItem = QtGui.QSpacerItem(321, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 0, 2, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ItemEditorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_8.addWidget(self.buttonBox, 9, 0, 1, 3)
        self.lblMedicalAidKind = QtGui.QLabel(ItemEditorDialog)
        self.lblMedicalAidKind.setObjectName(_fromUtf8("lblMedicalAidKind"))
        self.gridLayout_8.addWidget(self.lblMedicalAidKind, 4, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 3, 2, 1, 1)
        self.cmbEventProfile = CRBComboBox(ItemEditorDialog)
        self.cmbEventProfile.setObjectName(_fromUtf8("cmbEventProfile"))
        self.gridLayout_8.addWidget(self.cmbEventProfile, 3, 1, 1, 1)
        self.lblMedicalAidType = QtGui.QLabel(ItemEditorDialog)
        self.lblMedicalAidType.setObjectName(_fromUtf8("lblMedicalAidType"))
        self.gridLayout_8.addWidget(self.lblMedicalAidType, 5, 0, 1, 1)
        self.cmbMedicalAidKind = CRBComboBox(ItemEditorDialog)
        self.cmbMedicalAidKind.setObjectName(_fromUtf8("cmbMedicalAidKind"))
        self.gridLayout_8.addWidget(self.cmbMedicalAidKind, 4, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 5, 2, 1, 1)
        self.cmbMedicalAidType = CRBComboBox(ItemEditorDialog)
        self.cmbMedicalAidType.setObjectName(_fromUtf8("cmbMedicalAidType"))
        self.gridLayout_8.addWidget(self.cmbMedicalAidType, 5, 1, 1, 1)
        self.edtName = QtGui.QLineEdit(ItemEditorDialog)
        self.edtName.setMinimumSize(QtCore.QSize(200, 0))
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout_8.addWidget(self.edtName, 1, 1, 1, 1)
        self.lblEventProfile = QtGui.QLabel(ItemEditorDialog)
        self.lblEventProfile.setObjectName(_fromUtf8("lblEventProfile"))
        self.gridLayout_8.addWidget(self.lblEventProfile, 3, 0, 1, 1)
        self.lblName = QtGui.QLabel(ItemEditorDialog)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout_8.addWidget(self.lblName, 1, 0, 1, 1)
        self.lblPurpose = QtGui.QLabel(ItemEditorDialog)
        self.lblPurpose.setObjectName(_fromUtf8("lblPurpose"))
        self.gridLayout_8.addWidget(self.lblPurpose, 2, 0, 1, 1)
        self.cmbPurpose = CRBComboBox(ItemEditorDialog)
        self.cmbPurpose.setObjectName(_fromUtf8("cmbPurpose"))
        self.gridLayout_8.addWidget(self.cmbPurpose, 2, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(221, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 2, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(221, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 1, 2, 1, 1)
        self.lblCode = QtGui.QLabel(ItemEditorDialog)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout_8.addWidget(self.lblCode, 0, 0, 1, 1)
        self.edtCode = QtGui.QLineEdit(ItemEditorDialog)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout_8.addWidget(self.edtCode, 0, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(ItemEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMainInfo = QtGui.QWidget()
        self.tabMainInfo.setObjectName(_fromUtf8("tabMainInfo"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabMainInfo)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.scrollArea = QtGui.QScrollArea(self.tabMainInfo)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 968, 692))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_15 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.lblSex = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout_15.addWidget(self.lblSex, 0, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.cmbSex, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(122, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem5, 0, 2, 1, 1)
        self.lblAge = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout_15.addWidget(self.lblAge, 1, 0, 1, 1)
        self.edtAgeSelector = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtAgeSelector.setObjectName(_fromUtf8("edtAgeSelector"))
        self.gridLayout_15.addWidget(self.edtAgeSelector, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(122, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem6, 1, 2, 1, 1)
        self.lblMinDuration = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblMinDuration.setObjectName(_fromUtf8("lblMinDuration"))
        self.gridLayout_15.addWidget(self.lblMinDuration, 2, 0, 1, 1)
        self.edtMinDuration = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.edtMinDuration.setMaximum(999)
        self.edtMinDuration.setObjectName(_fromUtf8("edtMinDuration"))
        self.gridLayout_15.addWidget(self.edtMinDuration, 2, 1, 1, 1)
        self.lblMaxDuration = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblMaxDuration.setObjectName(_fromUtf8("lblMaxDuration"))
        self.gridLayout_15.addWidget(self.lblMaxDuration, 3, 0, 1, 1)
        self.edtMaxDuration = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.edtMaxDuration.setMaximum(999)
        self.edtMaxDuration.setObjectName(_fromUtf8("edtMaxDuration"))
        self.gridLayout_15.addWidget(self.edtMaxDuration, 3, 1, 1, 1)
        self.lblPeriod = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblPeriod.setObjectName(_fromUtf8("lblPeriod"))
        self.gridLayout_15.addWidget(self.lblPeriod, 4, 0, 1, 1)
        self.edtPeriod = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.edtPeriod.setObjectName(_fromUtf8("edtPeriod"))
        self.gridLayout_15.addWidget(self.edtPeriod, 4, 1, 1, 1)
        self.lblSingleInPeriod = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblSingleInPeriod.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSingleInPeriod.setObjectName(_fromUtf8("lblSingleInPeriod"))
        self.gridLayout_15.addWidget(self.lblSingleInPeriod, 4, 2, 1, 1)
        self.cmbSingleInPeriod = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbSingleInPeriod.setObjectName(_fromUtf8("cmbSingleInPeriod"))
        self.cmbSingleInPeriod.addItem(_fromUtf8(""))
        self.cmbSingleInPeriod.addItem(_fromUtf8(""))
        self.cmbSingleInPeriod.addItem(_fromUtf8(""))
        self.cmbSingleInPeriod.addItem(_fromUtf8(""))
        self.cmbSingleInPeriod.addItem(_fromUtf8(""))
        self.cmbSingleInPeriod.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.cmbSingleInPeriod, 4, 3, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(246, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem7, 4, 4, 1, 1)
        self.lblForm = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblForm.setObjectName(_fromUtf8("lblForm"))
        self.gridLayout_15.addWidget(self.lblForm, 5, 0, 1, 1)
        self.cmbForm = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbForm.setObjectName(_fromUtf8("cmbForm"))
        self.gridLayout_15.addWidget(self.cmbForm, 5, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(232, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem8, 5, 2, 1, 2)
        self.lblContext = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblContext.setObjectName(_fromUtf8("lblContext"))
        self.gridLayout_15.addWidget(self.lblContext, 6, 0, 1, 1)
        self.edtContext = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtContext.setMaxLength(64)
        self.edtContext.setObjectName(_fromUtf8("edtContext"))
        self.gridLayout_15.addWidget(self.edtContext, 6, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(232, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem9, 6, 2, 1, 2)
        self.lblDateInput = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblDateInput.setObjectName(_fromUtf8("lblDateInput"))
        self.gridLayout_15.addWidget(self.lblDateInput, 7, 0, 1, 1)
        self.cmbDateInput = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbDateInput.setObjectName(_fromUtf8("cmbDateInput"))
        self.cmbDateInput.addItem(_fromUtf8(""))
        self.cmbDateInput.addItem(_fromUtf8(""))
        self.cmbDateInput.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.cmbDateInput, 7, 1, 1, 1)
        self.chkResetSetDate = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkResetSetDate.setObjectName(_fromUtf8("chkResetSetDate"))
        self.gridLayout_15.addWidget(self.chkResetSetDate, 7, 2, 1, 3)
        self.lblDefaultEndTime = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblDefaultEndTime.setObjectName(_fromUtf8("lblDefaultEndTime"))
        self.gridLayout_15.addWidget(self.lblDefaultEndTime, 8, 0, 1, 1)
        self.edtDefaultEndTime = QtGui.QTimeEdit(self.scrollAreaWidgetContents)
        self.edtDefaultEndTime.setMinimumTime(QtCore.QTime(0, 0, 0))
        self.edtDefaultEndTime.setObjectName(_fromUtf8("edtDefaultEndTime"))
        self.gridLayout_15.addWidget(self.edtDefaultEndTime, 8, 1, 1, 1)
        self.lblDefaultOrder = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblDefaultOrder.setObjectName(_fromUtf8("lblDefaultOrder"))
        self.gridLayout_15.addWidget(self.lblDefaultOrder, 9, 0, 1, 1)
        self.cmbDefaultOrder = CRBComboBox(self.scrollAreaWidgetContents)
        self.cmbDefaultOrder.setObjectName(_fromUtf8("cmbDefaultOrder"))
        self.gridLayout_15.addWidget(self.cmbDefaultOrder, 9, 1, 1, 1)
        self.lblCheckKSG = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblCheckKSG.setObjectName(_fromUtf8("lblCheckKSG"))
        self.gridLayout_15.addWidget(self.lblCheckKSG, 10, 0, 1, 1)
        self.cmbCheckKSG = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbCheckKSG.setObjectName(_fromUtf8("cmbCheckKSG"))
        self.cmbCheckKSG.addItem(_fromUtf8(""))
        self.cmbCheckKSG.addItem(_fromUtf8(""))
        self.cmbCheckKSG.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.cmbCheckKSG, 10, 1, 1, 1)
        self.lblService = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblService.setObjectName(_fromUtf8("lblService"))
        self.gridLayout_15.addWidget(self.lblService, 11, 0, 1, 1)
        self.cmbService = CRBComboBox(self.scrollAreaWidgetContents)
        self.cmbService.setObjectName(_fromUtf8("cmbService"))
        self.gridLayout_15.addWidget(self.cmbService, 11, 1, 1, 2)
        self.btnSelectService = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.btnSelectService.setObjectName(_fromUtf8("btnSelectService"))
        self.gridLayout_15.addWidget(self.btnSelectService, 11, 4, 1, 1)
        self.lblFinance = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout_15.addWidget(self.lblFinance, 12, 0, 1, 1)
        self.cmbFinance = CRBComboBox(self.scrollAreaWidgetContents)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout_15.addWidget(self.cmbFinance, 12, 1, 1, 2)
        self.chkCanHavePayableActions = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkCanHavePayableActions.setObjectName(_fromUtf8("chkCanHavePayableActions"))
        self.gridLayout_15.addWidget(self.chkCanHavePayableActions, 12, 4, 1, 1)
        self.lblActionFinance = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblActionFinance.setObjectName(_fromUtf8("lblActionFinance"))
        self.gridLayout_15.addWidget(self.lblActionFinance, 13, 0, 1, 1)
        self.cmbActionFinance = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbActionFinance.setObjectName(_fromUtf8("cmbActionFinance"))
        self.cmbActionFinance.addItem(_fromUtf8(""))
        self.cmbActionFinance.addItem(_fromUtf8(""))
        self.cmbActionFinance.addItem(_fromUtf8(""))
        self.cmbActionFinance.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.cmbActionFinance, 13, 1, 1, 3)
        self.lblActionContract = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblActionContract.setObjectName(_fromUtf8("lblActionContract"))
        self.gridLayout_15.addWidget(self.lblActionContract, 14, 0, 1, 1)
        self.cmbActionContract = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbActionContract.setObjectName(_fromUtf8("cmbActionContract"))
        self.cmbActionContract.addItem(_fromUtf8(""))
        self.cmbActionContract.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.cmbActionContract, 14, 1, 1, 3)
        self.lblCaseCast = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblCaseCast.setObjectName(_fromUtf8("lblCaseCast"))
        self.gridLayout_15.addWidget(self.lblCaseCast, 15, 0, 1, 1)
        self.cmbCaseCast = CRBComboBox(self.scrollAreaWidgetContents)
        self.cmbCaseCast.setObjectName(_fromUtf8("cmbCaseCast"))
        self.gridLayout_15.addWidget(self.cmbCaseCast, 15, 1, 1, 3)
        self.lblExposeGrouped = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblExposeGrouped.setObjectName(_fromUtf8("lblExposeGrouped"))
        self.gridLayout_15.addWidget(self.lblExposeGrouped, 16, 0, 1, 1)
        self.edtExposeGrouped = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.edtExposeGrouped.setMaximum(999)
        self.edtExposeGrouped.setObjectName(_fromUtf8("edtExposeGrouped"))
        self.gridLayout_15.addWidget(self.edtExposeGrouped, 16, 1, 1, 1)
        self.lblWeekdays = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblWeekdays.setObjectName(_fromUtf8("lblWeekdays"))
        self.gridLayout_15.addWidget(self.lblWeekdays, 17, 0, 1, 1)
        self.cmbWeekdays = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbWeekdays.setObjectName(_fromUtf8("cmbWeekdays"))
        self.cmbWeekdays.addItem(_fromUtf8(""))
        self.cmbWeekdays.addItem(_fromUtf8(""))
        self.cmbWeekdays.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.cmbWeekdays, 17, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_6.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabMainInfo, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.chkSpecialitiesFilter = QtGui.QCheckBox(self.tab_2)
        self.chkSpecialitiesFilter.setObjectName(_fromUtf8("chkSpecialitiesFilter"))
        self.verticalLayout_2.addWidget(self.chkSpecialitiesFilter)
        self.tblSpecialitiesFilter = CRBListBox(self.tab_2)
        self.tblSpecialitiesFilter.setObjectName(_fromUtf8("tblSpecialitiesFilter"))
        self.verticalLayout_2.addWidget(self.tblSpecialitiesFilter)
        self.chkPostsFilter = QtGui.QCheckBox(self.tab_2)
        self.chkPostsFilter.setObjectName(_fromUtf8("chkPostsFilter"))
        self.verticalLayout_2.addWidget(self.chkPostsFilter)
        self.tblPostsFilter = CRBListBox(self.tab_2)
        self.tblPostsFilter.setObjectName(_fromUtf8("tblPostsFilter"))
        self.verticalLayout_2.addWidget(self.tblPostsFilter)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -347, 968, 806))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_16 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chkShowTime = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkShowTime.setObjectName(_fromUtf8("chkShowTime"))
        self.verticalLayout.addWidget(self.chkShowTime)
        self.chkOrgStructurePriorityForAddActions = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkOrgStructurePriorityForAddActions.setObjectName(_fromUtf8("chkOrgStructurePriorityForAddActions"))
        self.verticalLayout.addWidget(self.chkOrgStructurePriorityForAddActions)
        self.chkOnJobPayedFilter = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkOnJobPayedFilter.setObjectName(_fromUtf8("chkOnJobPayedFilter"))
        self.verticalLayout.addWidget(self.chkOnJobPayedFilter)
        self.chkDiagnosisSetDate = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkDiagnosisSetDate.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.chkDiagnosisSetDate.setObjectName(_fromUtf8("chkDiagnosisSetDate"))
        self.verticalLayout.addWidget(self.chkDiagnosisSetDate)
        self.chkIsTakenTissue = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkIsTakenTissue.setObjectName(_fromUtf8("chkIsTakenTissue"))
        self.verticalLayout.addWidget(self.chkIsTakenTissue)
        self.chkHasAssistant = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkHasAssistant.setObjectName(_fromUtf8("chkHasAssistant"))
        self.verticalLayout.addWidget(self.chkHasAssistant)
        self.chkHasCurator = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkHasCurator.setObjectName(_fromUtf8("chkHasCurator"))
        self.verticalLayout.addWidget(self.chkHasCurator)
        self.chkRequiredCoordination = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkRequiredCoordination.setObjectName(_fromUtf8("chkRequiredCoordination"))
        self.verticalLayout.addWidget(self.chkRequiredCoordination)
        self.chkPermitAnyDate = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkPermitAnyDate.setObjectName(_fromUtf8("chkPermitAnyDate"))
        self.verticalLayout.addWidget(self.chkPermitAnyDate)
        self.chkLittleStranger = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkLittleStranger.setObjectName(_fromUtf8("chkLittleStranger"))
        self.verticalLayout.addWidget(self.chkLittleStranger)
        self.chkIsLong = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkIsLong.setObjectName(_fromUtf8("chkIsLong"))
        self.verticalLayout.addWidget(self.chkIsLong)
        self.chkInheritDiagnosis = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkInheritDiagnosis.setObjectName(_fromUtf8("chkInheritDiagnosis"))
        self.verticalLayout.addWidget(self.chkInheritDiagnosis)
        self.chkAvailInFastCreateMode = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkAvailInFastCreateMode.setObjectName(_fromUtf8("chkAvailInFastCreateMode"))
        self.verticalLayout.addWidget(self.chkAvailInFastCreateMode)
        self.chkExposeConfirmation = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkExposeConfirmation.setObjectName(_fromUtf8("chkExposeConfirmation"))
        self.verticalLayout.addWidget(self.chkExposeConfirmation)
        self.chkShowZNO = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkShowZNO.setObjectName(_fromUtf8("chkShowZNO"))
        self.verticalLayout.addWidget(self.chkShowZNO)
        self.chkGoalFilter = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkGoalFilter.setObjectName(_fromUtf8("chkGoalFilter"))
        self.verticalLayout.addWidget(self.chkGoalFilter)
        self.chkInheritResult = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkInheritResult.setObjectName(_fromUtf8("chkInheritResult"))
        self.verticalLayout.addWidget(self.chkInheritResult)
        self.chkInheritCheckupResult = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkInheritCheckupResult.setObjectName(_fromUtf8("chkInheritCheckupResult"))
        self.verticalLayout.addWidget(self.chkInheritCheckupResult)
        self.chkInheritGoal = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkInheritGoal.setObjectName(_fromUtf8("chkInheritGoal"))
        self.verticalLayout.addWidget(self.chkInheritGoal)
        self.chkDispByMobileTeam = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkDispByMobileTeam.setToolTip(_fromUtf8(""))
        self.chkDispByMobileTeam.setWhatsThis(_fromUtf8(""))
        self.chkDispByMobileTeam.setObjectName(_fromUtf8("chkDispByMobileTeam"))
        self.verticalLayout.addWidget(self.chkDispByMobileTeam)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.lblIgnoreServicesStop = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lblIgnoreServicesStop.setObjectName(_fromUtf8("lblIgnoreServicesStop"))
        self.verticalLayout.addWidget(self.lblIgnoreServicesStop)
        self.chkCompulsoryServiceStopIgnore = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkCompulsoryServiceStopIgnore.setObjectName(_fromUtf8("chkCompulsoryServiceStopIgnore"))
        self.verticalLayout.addWidget(self.chkCompulsoryServiceStopIgnore)
        self.chkVoluntaryServiceStopIgnore = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chkVoluntaryServiceStopIgnore.setObjectName(_fromUtf8("chkVoluntaryServiceStopIgnore"))
        self.verticalLayout.addWidget(self.chkVoluntaryServiceStopIgnore)
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.gridLayout_16.addLayout(self.verticalLayout, 0, 0, 3, 1)
        self.gbMesRequired = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.gbMesRequired.setCheckable(True)
        self.gbMesRequired.setChecked(False)
        self.gbMesRequired.setObjectName(_fromUtf8("gbMesRequired"))
        self.gridLayout_11 = QtGui.QGridLayout(self.gbMesRequired)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.cmbDefaultMesSpecification = CRBComboBox(self.gbMesRequired)
        self.cmbDefaultMesSpecification.setEnabled(False)
        self.cmbDefaultMesSpecification.setObjectName(_fromUtf8("cmbDefaultMesSpecification"))
        self.gridLayout_11.addWidget(self.cmbDefaultMesSpecification, 3, 1, 1, 1)
        self.chkMesNecessityEqOne = QtGui.QCheckBox(self.gbMesRequired)
        self.chkMesNecessityEqOne.setObjectName(_fromUtf8("chkMesNecessityEqOne"))
        self.gridLayout_11.addWidget(self.chkMesNecessityEqOne, 1, 0, 1, 1)
        self.lblMesNameMask = QtGui.QLabel(self.gbMesRequired)
        self.lblMesNameMask.setObjectName(_fromUtf8("lblMesNameMask"))
        self.gridLayout_11.addWidget(self.lblMesNameMask, 5, 0, 1, 1)
        self.edtMesPerfPercent = QtGui.QSpinBox(self.gbMesRequired)
        self.edtMesPerfPercent.setMaximum(100)
        self.edtMesPerfPercent.setObjectName(_fromUtf8("edtMesPerfPercent"))
        self.gridLayout_11.addWidget(self.edtMesPerfPercent, 2, 1, 1, 1)
        self.edtMesNameMask = QtGui.QLineEdit(self.gbMesRequired)
        self.edtMesNameMask.setObjectName(_fromUtf8("edtMesNameMask"))
        self.gridLayout_11.addWidget(self.edtMesNameMask, 5, 1, 1, 1)
        self.chkShowMedicaments = QtGui.QCheckBox(self.gbMesRequired)
        self.chkShowMedicaments.setObjectName(_fromUtf8("chkShowMedicaments"))
        self.gridLayout_11.addWidget(self.chkShowMedicaments, 0, 1, 1, 1)
        self.lblMesCodeMask = QtGui.QLabel(self.gbMesRequired)
        self.lblMesCodeMask.setObjectName(_fromUtf8("lblMesCodeMask"))
        self.gridLayout_11.addWidget(self.lblMesCodeMask, 4, 0, 1, 1)
        self.edtMesCodeMask = QtGui.QLineEdit(self.gbMesRequired)
        self.edtMesCodeMask.setObjectName(_fromUtf8("edtMesCodeMask"))
        self.gridLayout_11.addWidget(self.edtMesCodeMask, 4, 1, 1, 1)
        self.chkDefaultMesSpecification = QtGui.QCheckBox(self.gbMesRequired)
        self.chkDefaultMesSpecification.setObjectName(_fromUtf8("chkDefaultMesSpecification"))
        self.gridLayout_11.addWidget(self.chkDefaultMesSpecification, 3, 0, 1, 1)
        self.chkShowAmountFromMes = QtGui.QCheckBox(self.gbMesRequired)
        self.chkShowAmountFromMes.setObjectName(_fromUtf8("chkShowAmountFromMes"))
        self.gridLayout_11.addWidget(self.chkShowAmountFromMes, 0, 0, 1, 1)
        self.lblMesPerformPercent = QtGui.QLabel(self.gbMesRequired)
        self.lblMesPerformPercent.setObjectName(_fromUtf8("lblMesPerformPercent"))
        self.gridLayout_11.addWidget(self.lblMesPerformPercent, 2, 0, 1, 1)
        self.lblSetFilters = QtGui.QLabel(self.gbMesRequired)
        self.lblSetFilters.setObjectName(_fromUtf8("lblSetFilters"))
        self.gridLayout_11.addWidget(self.lblSetFilters, 6, 0, 1, 1)
        self.cmbSetFilters = QtGui.QComboBox(self.gbMesRequired)
        self.cmbSetFilters.setObjectName(_fromUtf8("cmbSetFilters"))
        self.gridLayout_11.addWidget(self.cmbSetFilters, 6, 1, 1, 1)
        self.gridLayout_16.addWidget(self.gbMesRequired, 0, 1, 1, 1)
        self.chkExternalId = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.chkExternalId.setCheckable(True)
        self.chkExternalId.setChecked(False)
        self.chkExternalId.setObjectName(_fromUtf8("chkExternalId"))
        self.gridLayout_9 = QtGui.QGridLayout(self.chkExternalId)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.chkUniqueExternalId = QtGui.QCheckBox(self.chkExternalId)
        self.chkUniqueExternalId.setObjectName(_fromUtf8("chkUniqueExternalId"))
        self.gridLayout_9.addWidget(self.chkUniqueExternalId, 0, 2, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblPrefix = QtGui.QLabel(self.chkExternalId)
        self.lblPrefix.setObjectName(_fromUtf8("lblPrefix"))
        self.horizontalLayout.addWidget(self.lblPrefix)
        self.edtPrefix = QtGui.QLineEdit(self.chkExternalId)
        self.edtPrefix.setMinimumSize(QtCore.QSize(60, 0))
        self.edtPrefix.setObjectName(_fromUtf8("edtPrefix"))
        self.horizontalLayout.addWidget(self.edtPrefix)
        self.gridLayout_9.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.lblCounterType = QtGui.QLabel(self.chkExternalId)
        self.lblCounterType.setObjectName(_fromUtf8("lblCounterType"))
        self.gridLayout_13.addWidget(self.lblCounterType, 1, 0, 1, 1)
        self.cmbCounterType = QtGui.QComboBox(self.chkExternalId)
        self.cmbCounterType.setObjectName(_fromUtf8("cmbCounterType"))
        self.cmbCounterType.addItem(_fromUtf8(""))
        self.cmbCounterType.addItem(_fromUtf8(""))
        self.cmbCounterType.addItem(_fromUtf8(""))
        self.cmbCounterType.addItem(_fromUtf8(""))
        self.gridLayout_13.addWidget(self.cmbCounterType, 1, 1, 1, 1)
        self.lblCounter = QtGui.QLabel(self.chkExternalId)
        self.lblCounter.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblCounter.setObjectName(_fromUtf8("lblCounter"))
        self.gridLayout_13.addWidget(self.lblCounter, 2, 0, 1, 1)
        self.cmbCounter = CRBComboBox(self.chkExternalId)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCounter.sizePolicy().hasHeightForWidth())
        self.cmbCounter.setSizePolicy(sizePolicy)
        self.cmbCounter.setMinimumSize(QtCore.QSize(73, 0))
        self.cmbCounter.setObjectName(_fromUtf8("cmbCounter"))
        self.gridLayout_13.addWidget(self.cmbCounter, 2, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_13, 2, 0, 2, 4)
        self.chkExternalIdAsAccountNumber = QtGui.QCheckBox(self.chkExternalId)
        self.chkExternalIdAsAccountNumber.setObjectName(_fromUtf8("chkExternalIdAsAccountNumber"))
        self.gridLayout_9.addWidget(self.chkExternalIdAsAccountNumber, 4, 0, 1, 4)
        self.chkExternalIdRequired = QtGui.QCheckBox(self.chkExternalId)
        self.chkExternalIdRequired.setObjectName(_fromUtf8("chkExternalIdRequired"))
        self.gridLayout_9.addWidget(self.chkExternalIdRequired, 5, 0, 1, 1)
        self.gridLayout_16.addWidget(self.chkExternalId, 1, 1, 1, 1)
        self.gbAutoPrint = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.gbAutoPrint.setCheckable(True)
        self.gbAutoPrint.setObjectName(_fromUtf8("gbAutoPrint"))
        self.gridLayout_12 = QtGui.QGridLayout(self.gbAutoPrint)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.tblAutoPrint = CInDocTableView(self.gbAutoPrint)
        self.tblAutoPrint.setObjectName(_fromUtf8("tblAutoPrint"))
        self.gridLayout_12.addWidget(self.tblAutoPrint, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.gbAutoPrint, 2, 1, 1, 1)
        self.gbAssociations = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.gbAssociations.setCheckable(False)
        self.gbAssociations.setObjectName(_fromUtf8("gbAssociations"))
        self.gridLayout_14 = QtGui.QGridLayout(self.gbAssociations)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.tblAssociations = CInDocTableView(self.gbAssociations)
        self.tblAssociations.setObjectName(_fromUtf8("tblAssociations"))
        self.gridLayout_14.addWidget(self.tblAssociations, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.gbAssociations, 3, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem11, 4, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 3, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem12, 4, 1, 2, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem13, 5, 0, 1, 1)
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.lblTypeCode = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTypeCode.sizePolicy().hasHeightForWidth())
        self.lblTypeCode.setSizePolicy(sizePolicy)
        self.lblTypeCode.setObjectName(_fromUtf8("lblTypeCode"))
        self.gridLayout_18.addWidget(self.lblTypeCode, 0, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem14, 3, 0, 1, 1)
        self.cmbTypeCode = CRBComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTypeCode.sizePolicy().hasHeightForWidth())
        self.cmbTypeCode.setSizePolicy(sizePolicy)
        self.cmbTypeCode.setObjectName(_fromUtf8("cmbTypeCode"))
        self.gridLayout_18.addWidget(self.cmbTypeCode, 0, 1, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_18, 3, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_10.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tabVisits = QtGui.QWidget()
        self.tabVisits.setObjectName(_fromUtf8("tabVisits"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabVisits)
        self.gridLayout_7.setMargin(4)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.scrollArea_3 = QtGui.QScrollArea(self.tabVisits)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 501, 378))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_17 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.lblScene = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.lblScene.setObjectName(_fromUtf8("lblScene"))
        self.gridLayout_17.addWidget(self.lblScene, 0, 0, 1, 1)
        self.cmbScene = CRBComboBox(self.scrollAreaWidgetContents_3)
        self.cmbScene.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.cmbScene.setObjectName(_fromUtf8("cmbScene"))
        self.gridLayout_17.addWidget(self.cmbScene, 0, 1, 1, 1)
        self.chkHasVisitAssistant = QtGui.QCheckBox(self.scrollAreaWidgetContents_3)
        self.chkHasVisitAssistant.setObjectName(_fromUtf8("chkHasVisitAssistant"))
        self.gridLayout_17.addWidget(self.chkHasVisitAssistant, 1, 1, 1, 1)
        self.grpVisitServiceModifier = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.grpVisitServiceModifier.setObjectName(_fromUtf8("grpVisitServiceModifier"))
        self.gridLayout_5 = QtGui.QGridLayout(self.grpVisitServiceModifier)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.chkModifyTailService = QtGui.QCheckBox(self.grpVisitServiceModifier)
        self.chkModifyTailService.setObjectName(_fromUtf8("chkModifyTailService"))
        self.gridLayout_5.addWidget(self.chkModifyTailService, 3, 0, 1, 1)
        self.edtModifyTailService = QtGui.QLineEdit(self.grpVisitServiceModifier)
        self.edtModifyTailService.setEnabled(False)
        self.edtModifyTailService.setObjectName(_fromUtf8("edtModifyTailService"))
        self.gridLayout_5.addWidget(self.edtModifyTailService, 3, 3, 1, 1)
        self.chkModifyHeadService = QtGui.QCheckBox(self.grpVisitServiceModifier)
        self.chkModifyHeadService.setObjectName(_fromUtf8("chkModifyHeadService"))
        self.gridLayout_5.addWidget(self.chkModifyHeadService, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.grpVisitServiceModifier)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 2, 2, 1, 1)
        self.edtModifyTailService_N = QtGui.QLineEdit(self.grpVisitServiceModifier)
        self.edtModifyTailService_N.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtModifyTailService_N.sizePolicy().hasHeightForWidth())
        self.edtModifyTailService_N.setSizePolicy(sizePolicy)
        self.edtModifyTailService_N.setObjectName(_fromUtf8("edtModifyTailService_N"))
        self.gridLayout_5.addWidget(self.edtModifyTailService_N, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.grpVisitServiceModifier)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 3, 2, 1, 1)
        self.chkReplaceService = QtGui.QCheckBox(self.grpVisitServiceModifier)
        self.chkReplaceService.setObjectName(_fromUtf8("chkReplaceService"))
        self.gridLayout_5.addWidget(self.chkReplaceService, 1, 0, 1, 1)
        self.edtReplaceService = QtGui.QLineEdit(self.grpVisitServiceModifier)
        self.edtReplaceService.setEnabled(False)
        self.edtReplaceService.setObjectName(_fromUtf8("edtReplaceService"))
        self.gridLayout_5.addWidget(self.edtReplaceService, 1, 1, 1, 3)
        self.chkNoModifyService = QtGui.QCheckBox(self.grpVisitServiceModifier)
        self.chkNoModifyService.setChecked(True)
        self.chkNoModifyService.setObjectName(_fromUtf8("chkNoModifyService"))
        self.gridLayout_5.addWidget(self.chkNoModifyService, 0, 0, 1, 4)
        self.edtModifyHeadService_N = QtGui.QLineEdit(self.grpVisitServiceModifier)
        self.edtModifyHeadService_N.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtModifyHeadService_N.sizePolicy().hasHeightForWidth())
        self.edtModifyHeadService_N.setSizePolicy(sizePolicy)
        self.edtModifyHeadService_N.setObjectName(_fromUtf8("edtModifyHeadService_N"))
        self.gridLayout_5.addWidget(self.edtModifyHeadService_N, 2, 1, 1, 1)
        self.edtModifyHeadService = QtGui.QLineEdit(self.grpVisitServiceModifier)
        self.edtModifyHeadService.setEnabled(False)
        self.edtModifyHeadService.setObjectName(_fromUtf8("edtModifyHeadService"))
        self.gridLayout_5.addWidget(self.edtModifyHeadService, 2, 3, 1, 1)
        self.gridLayout_17.addWidget(self.grpVisitServiceModifier, 2, 0, 1, 2)
        self.lblVisitFinance = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.lblVisitFinance.setObjectName(_fromUtf8("lblVisitFinance"))
        self.gridLayout_17.addWidget(self.lblVisitFinance, 3, 0, 1, 1)
        self.cmbVisitFinance = QtGui.QComboBox(self.scrollAreaWidgetContents_3)
        self.cmbVisitFinance.setObjectName(_fromUtf8("cmbVisitFinance"))
        self.cmbVisitFinance.addItem(_fromUtf8(""))
        self.cmbVisitFinance.addItem(_fromUtf8(""))
        self.gridLayout_17.addWidget(self.cmbVisitFinance, 3, 1, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(397, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem15, 3, 2, 1, 1)
        self.lblVisitServiceFilter = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.lblVisitServiceFilter.setObjectName(_fromUtf8("lblVisitServiceFilter"))
        self.gridLayout_17.addWidget(self.lblVisitServiceFilter, 4, 0, 1, 1)
        self.edtVisitServiceFilter = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.edtVisitServiceFilter.setToolTip(_fromUtf8(""))
        self.edtVisitServiceFilter.setStatusTip(_fromUtf8(""))
        self.edtVisitServiceFilter.setObjectName(_fromUtf8("edtVisitServiceFilter"))
        self.gridLayout_17.addWidget(self.edtVisitServiceFilter, 4, 1, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(397, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem16, 4, 2, 1, 1)
        self.btnVisitServiceFilterTest = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.btnVisitServiceFilterTest.setEnabled(False)
        self.btnVisitServiceFilterTest.setObjectName(_fromUtf8("btnVisitServiceFilterTest"))
        self.gridLayout_17.addWidget(self.btnVisitServiceFilterTest, 5, 0, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(20, 146, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem17, 6, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_7.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabVisits, _fromUtf8(""))
        self.tabDiagnostics = QtGui.QWidget()
        self.tabDiagnostics.setObjectName(_fromUtf8("tabDiagnostics"))
        self.gridlayout = QtGui.QGridLayout(self.tabDiagnostics)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.tblDiagnostics = CInDocTableView(self.tabDiagnostics)
        self.tblDiagnostics.setObjectName(_fromUtf8("tblDiagnostics"))
        self.gridlayout.addWidget(self.tblDiagnostics, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabDiagnostics, _fromUtf8(""))
        self.tabStatusActions = QtGui.QWidget()
        self.tabStatusActions.setObjectName(_fromUtf8("tabStatusActions"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabStatusActions)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tblStatusActions = CInDocTableView(self.tabStatusActions)
        self.tblStatusActions.setObjectName(_fromUtf8("tblStatusActions"))
        self.gridLayout_4.addWidget(self.tblStatusActions, 0, 0, 1, 1)
        self.chkStatusShowOptionalInPlanner = QtGui.QCheckBox(self.tabStatusActions)
        self.chkStatusShowOptionalInPlanner.setChecked(True)
        self.chkStatusShowOptionalInPlanner.setObjectName(_fromUtf8("chkStatusShowOptionalInPlanner"))
        self.gridLayout_4.addWidget(self.chkStatusShowOptionalInPlanner, 1, 0, 1, 1)
        self.chkStatusLimitInput = QtGui.QCheckBox(self.tabStatusActions)
        self.chkStatusLimitInput.setObjectName(_fromUtf8("chkStatusLimitInput"))
        self.gridLayout_4.addWidget(self.chkStatusLimitInput, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabStatusActions, _fromUtf8(""))
        self.tabDiagnosticActions = QtGui.QWidget()
        self.tabDiagnosticActions.setObjectName(_fromUtf8("tabDiagnosticActions"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabDiagnosticActions)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblDiagnosticActions = CInDocTableView(self.tabDiagnosticActions)
        self.tblDiagnosticActions.setObjectName(_fromUtf8("tblDiagnosticActions"))
        self.gridLayout_3.addWidget(self.tblDiagnosticActions, 0, 0, 1, 1)
        self.chkDiagnosticShowOptionalInPlanner = QtGui.QCheckBox(self.tabDiagnosticActions)
        self.chkDiagnosticShowOptionalInPlanner.setChecked(True)
        self.chkDiagnosticShowOptionalInPlanner.setObjectName(_fromUtf8("chkDiagnosticShowOptionalInPlanner"))
        self.gridLayout_3.addWidget(self.chkDiagnosticShowOptionalInPlanner, 1, 0, 1, 1)
        self.chkDiagnosticLimitInput = QtGui.QCheckBox(self.tabDiagnosticActions)
        self.chkDiagnosticLimitInput.setObjectName(_fromUtf8("chkDiagnosticLimitInput"))
        self.gridLayout_3.addWidget(self.chkDiagnosticLimitInput, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabDiagnosticActions, _fromUtf8(""))
        self.tabCureActions = QtGui.QWidget()
        self.tabCureActions.setObjectName(_fromUtf8("tabCureActions"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabCureActions)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblCureActions = CInDocTableView(self.tabCureActions)
        self.tblCureActions.setObjectName(_fromUtf8("tblCureActions"))
        self.gridLayout_2.addWidget(self.tblCureActions, 0, 0, 1, 1)
        self.chkCureShowOptionalInPlanner = QtGui.QCheckBox(self.tabCureActions)
        self.chkCureShowOptionalInPlanner.setChecked(True)
        self.chkCureShowOptionalInPlanner.setObjectName(_fromUtf8("chkCureShowOptionalInPlanner"))
        self.gridLayout_2.addWidget(self.chkCureShowOptionalInPlanner, 1, 0, 1, 1)
        self.chkCureLimitInput = QtGui.QCheckBox(self.tabCureActions)
        self.chkCureLimitInput.setObjectName(_fromUtf8("chkCureLimitInput"))
        self.gridLayout_2.addWidget(self.chkCureLimitInput, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabCureActions, _fromUtf8(""))
        self.tabMiscActions = QtGui.QWidget()
        self.tabMiscActions.setObjectName(_fromUtf8("tabMiscActions"))
        self.gridLayout = QtGui.QGridLayout(self.tabMiscActions)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tblMiscActions = CInDocTableView(self.tabMiscActions)
        self.tblMiscActions.setObjectName(_fromUtf8("tblMiscActions"))
        self.gridLayout.addWidget(self.tblMiscActions, 0, 0, 1, 1)
        self.chkMiscShowOptionalInPlanner = QtGui.QCheckBox(self.tabMiscActions)
        self.chkMiscShowOptionalInPlanner.setChecked(True)
        self.chkMiscShowOptionalInPlanner.setObjectName(_fromUtf8("chkMiscShowOptionalInPlanner"))
        self.gridLayout.addWidget(self.chkMiscShowOptionalInPlanner, 1, 0, 1, 1)
        self.chkMiscLimitInput = QtGui.QCheckBox(self.tabMiscActions)
        self.chkMiscLimitInput.setObjectName(_fromUtf8("chkMiscLimitInput"))
        self.gridLayout.addWidget(self.chkMiscLimitInput, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabMiscActions, _fromUtf8(""))
        self.tabAnalyses = QtGui.QWidget()
        self.tabAnalyses.setObjectName(_fromUtf8("tabAnalyses"))
        self.gridLayout1 = QtGui.QGridLayout(self.tabAnalyses)
        self.gridLayout1.setMargin(4)
        self.gridLayout1.setSpacing(4)
        self.gridLayout1.setObjectName(_fromUtf8("gridLayout1"))
        self.tblAnalysesActions = CInDocTableView(self.tabAnalyses)
        self.tblAnalysesActions.setObjectName(_fromUtf8("tblAnalysesActions"))
        self.gridLayout1.addWidget(self.tblAnalysesActions, 0, 0, 1, 1)
        self.chkAnalysesShowOptionalInPlanner = QtGui.QCheckBox(self.tabAnalyses)
        self.chkAnalysesShowOptionalInPlanner.setChecked(True)
        self.chkAnalysesShowOptionalInPlanner.setObjectName(_fromUtf8("chkAnalysesShowOptionalInPlanner"))
        self.gridLayout1.addWidget(self.chkAnalysesShowOptionalInPlanner, 1, 0, 1, 1)
        self.chkAnalysesLimitInput = QtGui.QCheckBox(self.tabAnalyses)
        self.chkAnalysesLimitInput.setObjectName(_fromUtf8("chkAnalysesLimitInput"))
        self.gridLayout1.addWidget(self.chkAnalysesLimitInput, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabAnalyses, _fromUtf8(""))
        self.gridLayout_8.addWidget(self.tabWidget, 6, 0, 1, 3)
        self.lblMedicalAidKind.setBuddy(self.cmbMedicalAidKind)
        self.lblMedicalAidType.setBuddy(self.cmbMedicalAidType)
        self.lblEventProfile.setBuddy(self.cmbEventProfile)
        self.lblName.setBuddy(self.edtName)
        self.lblPurpose.setBuddy(self.cmbPurpose)
        self.lblCode.setBuddy(self.edtCode)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblMinDuration.setBuddy(self.edtMinDuration)
        self.lblMaxDuration.setBuddy(self.edtMaxDuration)
        self.lblPeriod.setBuddy(self.edtPeriod)
        self.lblSingleInPeriod.setBuddy(self.cmbSingleInPeriod)
        self.lblForm.setBuddy(self.cmbForm)
        self.lblContext.setBuddy(self.edtContext)
        self.lblDateInput.setBuddy(self.cmbDateInput)
        self.lblDefaultOrder.setBuddy(self.cmbDefaultOrder)
        self.lblService.setBuddy(self.cmbService)
        self.lblFinance.setBuddy(self.cmbFinance)
        self.lblActionFinance.setBuddy(self.cmbActionFinance)
        self.lblActionContract.setBuddy(self.cmbActionContract)
        self.lblCaseCast.setBuddy(self.cmbCaseCast)
        self.lblExposeGrouped.setBuddy(self.cmbCaseCast)
        self.lblMesNameMask.setBuddy(self.edtMesNameMask)
        self.lblMesCodeMask.setBuddy(self.edtMesCodeMask)
        self.lblPrefix.setBuddy(self.edtPrefix)
        self.lblCounterType.setBuddy(self.cmbCounterType)
        self.lblCounter.setBuddy(self.cmbCounter)
        self.lblScene.setBuddy(self.cmbScene)
        self.lblVisitFinance.setBuddy(self.cmbVisitFinance)
        self.lblVisitServiceFilter.setBuddy(self.edtVisitServiceFilter)

        self.retranslateUi(ItemEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        self.cmbActionFinance.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ItemEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ItemEditorDialog.reject)
        QtCore.QObject.connect(self.chkSpecialitiesFilter, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.tblSpecialitiesFilter.setEnabled)
        QtCore.QObject.connect(self.chkPostsFilter, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.tblPostsFilter.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ItemEditorDialog)
        ItemEditorDialog.setTabOrder(self.edtCode, self.edtName)
        ItemEditorDialog.setTabOrder(self.edtName, self.cmbPurpose)
        ItemEditorDialog.setTabOrder(self.cmbPurpose, self.cmbEventProfile)
        ItemEditorDialog.setTabOrder(self.cmbEventProfile, self.cmbMedicalAidKind)
        ItemEditorDialog.setTabOrder(self.cmbMedicalAidKind, self.cmbMedicalAidType)
        ItemEditorDialog.setTabOrder(self.cmbMedicalAidType, self.tabWidget)
        ItemEditorDialog.setTabOrder(self.tabWidget, self.buttonBox)
        ItemEditorDialog.setTabOrder(self.buttonBox, self.tblDiagnostics)
        ItemEditorDialog.setTabOrder(self.tblDiagnostics, self.tblStatusActions)
        ItemEditorDialog.setTabOrder(self.tblStatusActions, self.chkStatusShowOptionalInPlanner)
        ItemEditorDialog.setTabOrder(self.chkStatusShowOptionalInPlanner, self.chkStatusLimitInput)
        ItemEditorDialog.setTabOrder(self.chkStatusLimitInput, self.tblDiagnosticActions)
        ItemEditorDialog.setTabOrder(self.tblDiagnosticActions, self.chkDiagnosticShowOptionalInPlanner)
        ItemEditorDialog.setTabOrder(self.chkDiagnosticShowOptionalInPlanner, self.chkDiagnosticLimitInput)
        ItemEditorDialog.setTabOrder(self.chkDiagnosticLimitInput, self.tblCureActions)
        ItemEditorDialog.setTabOrder(self.tblCureActions, self.chkCureShowOptionalInPlanner)
        ItemEditorDialog.setTabOrder(self.chkCureShowOptionalInPlanner, self.chkCureLimitInput)
        ItemEditorDialog.setTabOrder(self.chkCureLimitInput, self.tblMiscActions)
        ItemEditorDialog.setTabOrder(self.tblMiscActions, self.chkMiscShowOptionalInPlanner)
        ItemEditorDialog.setTabOrder(self.chkMiscShowOptionalInPlanner, self.chkMiscLimitInput)

    def retranslateUi(self, ItemEditorDialog):
        ItemEditorDialog.setWindowTitle(_translate("ItemEditorDialog", "ChangeMe!", None))
        self.lblMedicalAidKind.setText(_translate("ItemEditorDialog", "&Вид медицинской помощи", None))
        self.lblMedicalAidType.setText(_translate("ItemEditorDialog", "&Тип медицинской помощи", None))
        self.lblEventProfile.setText(_translate("ItemEditorDialog", "Профиль", None))
        self.lblName.setText(_translate("ItemEditorDialog", "На&именование", None))
        self.lblPurpose.setText(_translate("ItemEditorDialog", "&Назначение", None))
        self.lblCode.setText(_translate("ItemEditorDialog", "&Код", None))
        self.lblSex.setText(_translate("ItemEditorDialog", "&Пол", None))
        self.cmbSex.setItemText(1, _translate("ItemEditorDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("ItemEditorDialog", "Ж", None))
        self.lblAge.setText(_translate("ItemEditorDialog", "Возраст", None))
        self.lblMinDuration.setText(_translate("ItemEditorDialog", "Минимальная длительность", None))
        self.lblMaxDuration.setText(_translate("ItemEditorDialog", "Максимальная длительность", None))
        self.lblPeriod.setText(_translate("ItemEditorDialog", "П&ериод (мес)", None))
        self.lblSingleInPeriod.setText(_translate("ItemEditorDialog", "или раз в", None))
        self.cmbSingleInPeriod.setItemText(0, _translate("ItemEditorDialog", "-", None))
        self.cmbSingleInPeriod.setItemText(1, _translate("ItemEditorDialog", "Неделю", None))
        self.cmbSingleInPeriod.setItemText(2, _translate("ItemEditorDialog", "Месяц", None))
        self.cmbSingleInPeriod.setItemText(3, _translate("ItemEditorDialog", "Квартал", None))
        self.cmbSingleInPeriod.setItemText(4, _translate("ItemEditorDialog", "Полугодие", None))
        self.cmbSingleInPeriod.setItemText(5, _translate("ItemEditorDialog", "Год", None))
        self.lblForm.setText(_translate("ItemEditorDialog", "&Форма", None))
        self.lblContext.setText(_translate("ItemEditorDialog", "Контекст пе&чати", None))
        self.lblDateInput.setText(_translate("ItemEditorDialog", "При &создании", None))
        self.cmbDateInput.setItemText(0, _translate("ItemEditorDialog", "Указывать дату начала", None))
        self.cmbDateInput.setItemText(1, _translate("ItemEditorDialog", "Указывать дату окончания", None))
        self.cmbDateInput.setItemText(2, _translate("ItemEditorDialog", "Указывать обе даты", None))
        self.chkResetSetDate.setText(_translate("ItemEditorDialog", "Контроль даты начала (устанавливать сегодняшнюю)", None))
        self.lblDefaultEndTime.setText(_translate("ItemEditorDialog", "Время окончания по умолчанию", None))
        self.edtDefaultEndTime.setDisplayFormat(_translate("ItemEditorDialog", "H:mm", None))
        self.lblDefaultOrder.setText(_translate("ItemEditorDialog", "Порядок поступления по умолчанию", None))
        self.lblCheckKSG.setText(_translate("ItemEditorDialog", "Проверка КСГ", None))
        self.cmbCheckKSG.setItemText(0, _translate("ItemEditorDialog", "Нет", None))
        self.cmbCheckKSG.setItemText(1, _translate("ItemEditorDialog", "Мягкая проверка", None))
        self.cmbCheckKSG.setItemText(2, _translate("ItemEditorDialog", "Жесткая проверка", None))
        self.lblService.setText(_translate("ItemEditorDialog", "Базовая &услуга", None))
        self.btnSelectService.setText(_translate("ItemEditorDialog", "...", None))
        self.lblFinance.setText(_translate("ItemEditorDialog", "&Тип финансирования", None))
        self.chkCanHavePayableActions.setText(_translate("ItemEditorDialog", "Может иметь платные действия", None))
        self.lblActionFinance.setText(_translate("ItemEditorDialog", "Финансирование действий", None))
        self.cmbActionFinance.setItemText(0, _translate("ItemEditorDialog", "Автоматически не заполнять", None))
        self.cmbActionFinance.setItemText(1, _translate("ItemEditorDialog", "По событию", None))
        self.cmbActionFinance.setItemText(2, _translate("ItemEditorDialog", "По назначившему врачу", None))
        self.cmbActionFinance.setItemText(3, _translate("ItemEditorDialog", "По исполнителю", None))
        self.lblActionContract.setText(_translate("ItemEditorDialog", "Договоры действий", None))
        self.cmbActionContract.setItemText(0, _translate("ItemEditorDialog", "Автоматически не заполнять", None))
        self.cmbActionContract.setItemText(1, _translate("ItemEditorDialog", "При возможности заполнять по событию ", None))
        self.lblCaseCast.setToolTip(_translate("ItemEditorDialog", "Используется для заполнения поля CASE_CAST при выгрузке в ЕИСОМС по Санкт-Петербургу.", None))
        self.lblCaseCast.setText(_translate("ItemEditorDialog", "Тип случая лечения", None))
        self.cmbCaseCast.setToolTip(_translate("ItemEditorDialog", "Используется для заполнения поля CASE_CAST при выгрузке в ЕИСОМС по Санкт-Петербургу.", None))
        self.lblExposeGrouped.setToolTip(_translate("ItemEditorDialog", "Используется для заполнения поля CASE_CAST при выгрузке в ЕИСОМС по Санкт-Петербургу.", None))
        self.lblExposeGrouped.setText(_translate("ItemEditorDialog", "Группа в счетах", None))
        self.lblWeekdays.setText(_translate("ItemEditorDialog", "Длительность рабочей недели", None))
        self.cmbWeekdays.setItemText(0, _translate("ItemEditorDialog", "5 дней", None))
        self.cmbWeekdays.setItemText(1, _translate("ItemEditorDialog", "6 дней", None))
        self.cmbWeekdays.setItemText(2, _translate("ItemEditorDialog", "7 дней", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMainInfo), _translate("ItemEditorDialog", "Основная информация", None))
        self.chkSpecialitiesFilter.setText(_translate("ItemEditorDialog", "Разрешить выбор только пользователям указанных специальностей", None))
        self.chkPostsFilter.setText(_translate("ItemEditorDialog", "Разрешить выбор только пользователям указанных должностей", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ItemEditorDialog", "Профили", None))
        self.chkShowTime.setText(_translate("ItemEditorDialog", "Показывать в интерфейсе время назначения/окончания", None))
        self.chkOrgStructurePriorityForAddActions.setText(_translate("ItemEditorDialog", "Приоритет подразделения для функции \"Добавить ...\"", None))
        self.chkOnJobPayedFilter.setText(_translate("ItemEditorDialog", "Учитывать настройки вывода работ по оплате", None))
        self.chkDiagnosisSetDate.setText(_translate("ItemEditorDialog", "Выводить дату постановки диагноза", None))
        self.chkIsTakenTissue.setText(_translate("ItemEditorDialog", "Использует забор биоматериалов", None))
        self.chkHasAssistant.setText(_translate("ItemEditorDialog", "Требуется ввод ассистента", None))
        self.chkHasCurator.setText(_translate("ItemEditorDialog", "Требуется ввод куратора", None))
        self.chkRequiredCoordination.setText(_translate("ItemEditorDialog", "Требует согласования", None))
        self.chkPermitAnyDate.setText(_translate("ItemEditorDialog", "Разрешить ввод любых дат выполнения", None))
        self.chkLittleStranger.setText(_translate("ItemEditorDialog", "Отображать \"Признак новорожденного\"", None))
        self.chkIsLong.setText(_translate("ItemEditorDialog", "Является п&родолжительным", None))
        self.chkInheritDiagnosis.setText(_translate("ItemEditorDialog", "Наследовать диагноз из предыдушего обращения", None))
        self.chkAvailInFastCreateMode.setText(_translate("ItemEditorDialog", "Сделать доступным при быстром создании обращения", None))
        self.chkExposeConfirmation.setText(_translate("ItemEditorDialog", "Указывать явно возможность добавления события в счет", None))
        self.chkShowZNO.setToolTip(_translate("ItemEditorDialog", "Показывать при редактировании обращение чекбоксы:\n"
"\"Диагноз ЗНО установлен впервые\" и \"Диагноз ЗНО подтверждён морфологически\"", None))
        self.chkShowZNO.setText(_translate("ItemEditorDialog", "Отображать ЗНО", None))
        self.chkGoalFilter.setText(_translate("ItemEditorDialog", "Фильтровать типы действий по цели события", None))
        self.chkInheritResult.setText(_translate("ItemEditorDialog", "Наследовать результат обращения", None))
        self.chkInheritCheckupResult.setText(_translate("ItemEditorDialog", "Наследовать результат осмотра", None))
        self.chkInheritGoal.setText(_translate("ItemEditorDialog", "Наследовать цель обращения", None))
        self.chkDispByMobileTeam.setText(_translate("ItemEditorDialog", "Диспансеризация(проф.осмотр) проведена МВБ", None))
        self.lblIgnoreServicesStop.setText(_translate("ItemEditorDialog", "Игнорировать запрет обслуживания:", None))
        self.chkCompulsoryServiceStopIgnore.setText(_translate("ItemEditorDialog", "ОМС", None))
        self.chkVoluntaryServiceStopIgnore.setText(_translate("ItemEditorDialog", "ДМС", None))
        self.gbMesRequired.setTitle(_translate("ItemEditorDialog", "Требует указания МЭС", None))
        self.chkMesNecessityEqOne.setText(_translate("ItemEditorDialog", "Контроль услуг с частотой прим. 1", None))
        self.lblMesNameMask.setText(_translate("ItemEditorDialog", "Шаблон наименования МЭС", None))
        self.chkShowMedicaments.setText(_translate("ItemEditorDialog", "Выводить медикаменты", None))
        self.lblMesCodeMask.setText(_translate("ItemEditorDialog", "Шаблон кода МЭС", None))
        self.chkDefaultMesSpecification.setText(_translate("ItemEditorDialog", "Особенности выполнения по умолчанию", None))
        self.chkShowAmountFromMes.setText(_translate("ItemEditorDialog", "Выводить количество из МЭС", None))
        self.lblMesPerformPercent.setText(_translate("ItemEditorDialog", "Процент выполняемости услуг", None))
        self.lblSetFilters.setText(_translate("ItemEditorDialog", "Набор фильтров", None))
        self.chkExternalId.setTitle(_translate("ItemEditorDialog", "Требуется ввод внешнего идентификатора", None))
        self.chkUniqueExternalId.setText(_translate("ItemEditorDialog", "Проверять на уникальность", None))
        self.lblPrefix.setText(_translate("ItemEditorDialog", "Префикс", None))
        self.lblCounterType.setToolTip(_translate("ItemEditorDialog", "При выборе варианта \"по изменению результата\" тип счетчика указывается в справочнике \"Результаты обращения\"", None))
        self.lblCounterType.setText(_translate("ItemEditorDialog", "Тип счетчика", None))
        self.cmbCounterType.setToolTip(_translate("ItemEditorDialog", "При выборе варианта \"по изменению результата\" тип счетчика указывается в справочнике \"Результаты обращения\"", None))
        self.cmbCounterType.setItemText(0, _translate("ItemEditorDialog", "Нет", None))
        self.cmbCounterType.setItemText(1, _translate("ItemEditorDialog", "По созданию обращения", None))
        self.cmbCounterType.setItemText(2, _translate("ItemEditorDialog", "По сохранению обращения", None))
        self.cmbCounterType.setItemText(3, _translate("ItemEditorDialog", "По изменению результата", None))
        self.lblCounter.setText(_translate("ItemEditorDialog", "Счетчик", None))
        self.chkExternalIdAsAccountNumber.setToolTip(_translate("ItemEditorDialog", "Использовать внешний идентификатор в качестве номера счета при создании счета из редактора обращений.", None))
        self.chkExternalIdAsAccountNumber.setText(_translate("ItemEditorDialog", "Использовать в качестве номера счета", None))
        self.chkExternalIdRequired.setText(_translate("ItemEditorDialog", "Жесткая проверка", None))
        self.gbAutoPrint.setTitle(_translate("ItemEditorDialog", "Автопечать", None))
        self.gbAssociations.setTitle(_translate("ItemEditorDialog", "Взаимосвязанные типы событий", None))
        self.lblTypeCode.setText(_translate("ItemEditorDialog", "Вид события", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ItemEditorDialog", "Другие параметры", None))
        self.lblScene.setText(_translate("ItemEditorDialog", "&Место визита", None))
        self.chkHasVisitAssistant.setText(_translate("ItemEditorDialog", "Требуется ввод ассистента", None))
        self.grpVisitServiceModifier.setTitle(_translate("ItemEditorDialog", "Модификатор услуги визита", None))
        self.chkModifyTailService.setText(_translate("ItemEditorDialog", "Заменяет заключительные", None))
        self.chkModifyHeadService.setText(_translate("ItemEditorDialog", "Заменяет начальные", None))
        self.label.setText(_translate("ItemEditorDialog", "символов на", None))
        self.edtModifyTailService_N.setInputMask(_translate("ItemEditorDialog", "90; ", None))
        self.label_2.setText(_translate("ItemEditorDialog", "символов на", None))
        self.chkReplaceService.setText(_translate("ItemEditorDialog", "Заменяет услугу на", None))
        self.chkNoModifyService.setText(_translate("ItemEditorDialog", "Не меняет услугу", None))
        self.edtModifyHeadService_N.setInputMask(_translate("ItemEditorDialog", "90; ", None))
        self.lblVisitFinance.setText(_translate("ItemEditorDialog", "&Финансирование визита", None))
        self.cmbVisitFinance.setItemText(0, _translate("ItemEditorDialog", "По событию", None))
        self.cmbVisitFinance.setItemText(1, _translate("ItemEditorDialog", "По врачу", None))
        self.lblVisitServiceFilter.setText(_translate("ItemEditorDialog", "Шаблон списка услуг визитов", None))
        self.btnVisitServiceFilterTest.setText(_translate("ItemEditorDialog", "Испытание", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVisits), _translate("ItemEditorDialog", "Визиты", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDiagnostics), _translate("ItemEditorDialog", "&Осмотры", None))
        self.chkStatusShowOptionalInPlanner.setText(_translate("ItemEditorDialog", "Показывать в планировщике необязательные мероприятия", None))
        self.chkStatusLimitInput.setText(_translate("ItemEditorDialog", "Ограничить ввод мероприятий указанным списком", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStatusActions), _translate("ItemEditorDialog", "&Статус", None))
        self.chkDiagnosticShowOptionalInPlanner.setText(_translate("ItemEditorDialog", "Показывать в планировщике необязательные мероприятия", None))
        self.chkDiagnosticLimitInput.setText(_translate("ItemEditorDialog", "Ограничить ввод мероприятий указанным списком", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDiagnosticActions), _translate("ItemEditorDialog", "&Диагностика", None))
        self.chkCureShowOptionalInPlanner.setText(_translate("ItemEditorDialog", "Показывать в планировщике необязательные мероприятия", None))
        self.chkCureLimitInput.setText(_translate("ItemEditorDialog", "Ограничить ввод мероприятий указанным списком", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCureActions), _translate("ItemEditorDialog", "&Лечение", None))
        self.chkMiscShowOptionalInPlanner.setText(_translate("ItemEditorDialog", "Показывать в планировщике необязательные мероприятия", None))
        self.chkMiscLimitInput.setText(_translate("ItemEditorDialog", "Ограничить ввод мероприятий указанным списком", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMiscActions), _translate("ItemEditorDialog", "Прочие &Мероприятия", None))
        self.chkAnalysesShowOptionalInPlanner.setText(_translate("ItemEditorDialog", "Показывать в планировщике необязательные мероприятия", None))
        self.chkAnalysesLimitInput.setText(_translate("ItemEditorDialog", "Ограничить ввод мероприятий указанным списком", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAnalyses), _translate("ItemEditorDialog", "Анализы", None))

from library.InDocTable import CInDocTableView
from library.RBListBox import CRBListBox
from library.crbcombobox import CRBComboBox
