# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GroupActionTypeEditor.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GroupActionTypeEditorDialog(object):
    def setupUi(self, GroupActionTypeEditorDialog):
        GroupActionTypeEditorDialog.setObjectName(_fromUtf8("GroupActionTypeEditorDialog"))
        GroupActionTypeEditorDialog.resize(768, 723)
        self.verticalLayout_3 = QtGui.QVBoxLayout(GroupActionTypeEditorDialog)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.scrollArea = QtGui.QScrollArea(GroupActionTypeEditorDialog)
        self.scrollArea.setMinimumSize(QtCore.QSize(750, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 732, 1231))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.chkMaxOccursInEvent = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkMaxOccursInEvent.setObjectName(_fromUtf8("chkMaxOccursInEvent"))
        self.gridLayout.addWidget(self.chkMaxOccursInEvent, 12, 0, 1, 1)
        self.pnlShowTime = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.pnlShowTime.setObjectName(_fromUtf8("pnlShowTime"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.pnlShowTime)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.chkChkShowTime = QtGui.QCheckBox(self.pnlShowTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkShowTime.sizePolicy().hasHeightForWidth())
        self.chkChkShowTime.setSizePolicy(sizePolicy)
        self.chkChkShowTime.setText(_fromUtf8(""))
        self.chkChkShowTime.setObjectName(_fromUtf8("chkChkShowTime"))
        self.horizontalLayout_6.addWidget(self.chkChkShowTime)
        self.chkShowTime = QtGui.QCheckBox(self.pnlShowTime)
        self.chkShowTime.setEnabled(False)
        self.chkShowTime.setObjectName(_fromUtf8("chkShowTime"))
        self.horizontalLayout_6.addWidget(self.chkShowTime)
        self.gridLayout.addWidget(self.pnlShowTime, 2, 0, 1, 2)
        self.pnlPreferable = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.pnlPreferable.setObjectName(_fromUtf8("pnlPreferable"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.pnlPreferable)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.chkPreferable = QtGui.QCheckBox(self.pnlPreferable)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkPreferable.sizePolicy().hasHeightForWidth())
        self.chkPreferable.setSizePolicy(sizePolicy)
        self.chkPreferable.setText(_fromUtf8(""))
        self.chkPreferable.setObjectName(_fromUtf8("chkPreferable"))
        self.horizontalLayout_3.addWidget(self.chkPreferable)
        self.chkIsPreferable = QtGui.QCheckBox(self.pnlPreferable)
        self.chkIsPreferable.setEnabled(False)
        self.chkIsPreferable.setObjectName(_fromUtf8("chkIsPreferable"))
        self.horizontalLayout_3.addWidget(self.chkIsPreferable)
        self.gridLayout.addWidget(self.pnlPreferable, 11, 0, 1, 1)
        self.chkIsMorphologyRequired = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkIsMorphologyRequired.setObjectName(_fromUtf8("chkIsMorphologyRequired"))
        self.gridLayout.addWidget(self.chkIsMorphologyRequired, 30, 0, 1, 1)
        self.chkServiceType = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkServiceType.setObjectName(_fromUtf8("chkServiceType"))
        self.gridLayout.addWidget(self.chkServiceType, 13, 0, 1, 1)
        self.chkDefaultMorphology = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkDefaultMorphology.setObjectName(_fromUtf8("chkDefaultMorphology"))
        self.gridLayout.addWidget(self.chkDefaultMorphology, 29, 0, 1, 1)
        self.chkSex = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkSex.setObjectName(_fromUtf8("chkSex"))
        self.gridLayout.addWidget(self.chkSex, 0, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbSex.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 0, 1, 1, 1)
        self.cmbDefaultPersonInEvent = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbDefaultPersonInEvent.setEnabled(False)
        self.cmbDefaultPersonInEvent.setObjectName(_fromUtf8("cmbDefaultPersonInEvent"))
        self.cmbDefaultPersonInEvent.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEvent.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEvent.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEvent.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEvent.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbDefaultPersonInEvent, 26, 1, 1, 1)
        self.cmbDefaultPlannedEndDate = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbDefaultPlannedEndDate.setEnabled(False)
        self.cmbDefaultPlannedEndDate.setObjectName(_fromUtf8("cmbDefaultPlannedEndDate"))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbDefaultPlannedEndDate, 21, 1, 1, 1)
        self.widget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.chkChkIgnoreEventEndDate = QtGui.QCheckBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkIgnoreEventEndDate.sizePolicy().hasHeightForWidth())
        self.chkChkIgnoreEventEndDate.setSizePolicy(sizePolicy)
        self.chkChkIgnoreEventEndDate.setText(_fromUtf8(""))
        self.chkChkIgnoreEventEndDate.setObjectName(_fromUtf8("chkChkIgnoreEventEndDate"))
        self.horizontalLayout_9.addWidget(self.chkChkIgnoreEventEndDate)
        self.chkIgnoreEventEndDate = QtGui.QCheckBox(self.widget)
        self.chkIgnoreEventEndDate.setEnabled(False)
        self.chkIgnoreEventEndDate.setObjectName(_fromUtf8("chkIgnoreEventEndDate"))
        self.horizontalLayout_9.addWidget(self.chkIgnoreEventEndDate)
        self.gridLayout.addWidget(self.widget, 34, 0, 1, 2)
        self.cmbServiceType = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbServiceType.setEnabled(False)
        self.cmbServiceType.setObjectName(_fromUtf8("cmbServiceType"))
        self.gridLayout.addWidget(self.cmbServiceType, 13, 1, 1, 1)
        self.chkAssistant = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkAssistant.sizePolicy().hasHeightForWidth())
        self.chkAssistant.setSizePolicy(sizePolicy)
        self.chkAssistant.setObjectName(_fromUtf8("chkAssistant"))
        self.gridLayout.addWidget(self.chkAssistant, 7, 0, 1, 1)
        self.cmbDefaultPersonInEditor = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbDefaultPersonInEditor.setEnabled(False)
        self.cmbDefaultPersonInEditor.setObjectName(_fromUtf8("cmbDefaultPersonInEditor"))
        self.cmbDefaultPersonInEditor.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEditor.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEditor.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEditor.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEditor.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbDefaultPersonInEditor, 27, 1, 1, 1)
        self.cmbDefaultOrg = CPolyclinicComboBox(self.scrollAreaWidgetContents)
        self.cmbDefaultOrg.setEnabled(False)
        self.cmbDefaultOrg.setObjectName(_fromUtf8("cmbDefaultOrg"))
        self.gridLayout.addWidget(self.cmbDefaultOrg, 31, 1, 1, 1)
        self.chkDefaultMKB = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkDefaultMKB.setObjectName(_fromUtf8("chkDefaultMKB"))
        self.gridLayout.addWidget(self.chkDefaultMKB, 28, 0, 1, 1)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 17, 0, 2, 2)
        self.pnlShowAPOrg = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.pnlShowAPOrg.setObjectName(_fromUtf8("pnlShowAPOrg"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.pnlShowAPOrg)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.chkChkShowAPOrg = QtGui.QCheckBox(self.pnlShowAPOrg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkShowAPOrg.sizePolicy().hasHeightForWidth())
        self.chkChkShowAPOrg.setSizePolicy(sizePolicy)
        self.chkChkShowAPOrg.setText(_fromUtf8(""))
        self.chkChkShowAPOrg.setObjectName(_fromUtf8("chkChkShowAPOrg"))
        self.horizontalLayout_10.addWidget(self.chkChkShowAPOrg)
        self.chkShowAPOrg = QtGui.QCheckBox(self.pnlShowAPOrg)
        self.chkShowAPOrg.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkShowAPOrg.sizePolicy().hasHeightForWidth())
        self.chkShowAPOrg.setSizePolicy(sizePolicy)
        self.chkShowAPOrg.setObjectName(_fromUtf8("chkShowAPOrg"))
        self.horizontalLayout_10.addWidget(self.chkShowAPOrg)
        self.gridLayout.addWidget(self.pnlShowAPOrg, 4, 0, 1, 2)
        self.chkDefaultPersonInEvent = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkDefaultPersonInEvent.setObjectName(_fromUtf8("chkDefaultPersonInEvent"))
        self.gridLayout.addWidget(self.chkDefaultPersonInEvent, 26, 0, 1, 1)
        self.cmbDefaultMKB = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbDefaultMKB.setEnabled(False)
        self.cmbDefaultMKB.setObjectName(_fromUtf8("cmbDefaultMKB"))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbDefaultMKB, 28, 1, 1, 1)
        self.cmbDefaultMorphology = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbDefaultMorphology.setEnabled(False)
        self.cmbDefaultMorphology.setObjectName(_fromUtf8("cmbDefaultMorphology"))
        self.cmbDefaultMorphology.addItem(_fromUtf8(""))
        self.cmbDefaultMorphology.addItem(_fromUtf8(""))
        self.cmbDefaultMorphology.addItem(_fromUtf8(""))
        self.cmbDefaultMorphology.addItem(_fromUtf8(""))
        self.cmbDefaultMorphology.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbDefaultMorphology, 29, 1, 1, 1)
        self.edtAmount = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.edtAmount.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmount.sizePolicy().hasHeightForWidth())
        self.edtAmount.setSizePolicy(sizePolicy)
        self.edtAmount.setObjectName(_fromUtf8("edtAmount"))
        self.gridLayout.addWidget(self.edtAmount, 32, 1, 1, 1)
        self.chkDefaultEndDate = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkDefaultEndDate.setObjectName(_fromUtf8("chkDefaultEndDate"))
        self.gridLayout.addWidget(self.chkDefaultEndDate, 23, 0, 1, 1)
        self.cmbIsMorphologyRequired = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbIsMorphologyRequired.setEnabled(False)
        self.cmbIsMorphologyRequired.setObjectName(_fromUtf8("cmbIsMorphologyRequired"))
        self.cmbIsMorphologyRequired.addItem(_fromUtf8(""))
        self.cmbIsMorphologyRequired.addItem(_fromUtf8(""))
        self.cmbIsMorphologyRequired.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbIsMorphologyRequired, 30, 1, 1, 1)
        self.chkContext = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkContext.setObjectName(_fromUtf8("chkContext"))
        self.gridLayout.addWidget(self.chkContext, 9, 0, 1, 1)
        self.chkAmount = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkAmount.setObjectName(_fromUtf8("chkAmount"))
        self.gridLayout.addWidget(self.chkAmount, 32, 0, 1, 1)
        self.chkDefaultBeginDate = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkDefaultBeginDate.setObjectName(_fromUtf8("chkDefaultBeginDate"))
        self.gridLayout.addWidget(self.chkDefaultBeginDate, 22, 0, 1, 1)
        self.cmbDefaultStatus = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbDefaultStatus.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDefaultStatus.sizePolicy().hasHeightForWidth())
        self.cmbDefaultStatus.setSizePolicy(sizePolicy)
        self.cmbDefaultStatus.setObjectName(_fromUtf8("cmbDefaultStatus"))
        self.gridLayout.addWidget(self.cmbDefaultStatus, 20, 1, 1, 1)
        self.edtMaxOccursInEvent = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.edtMaxOccursInEvent.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMaxOccursInEvent.sizePolicy().hasHeightForWidth())
        self.edtMaxOccursInEvent.setSizePolicy(sizePolicy)
        self.edtMaxOccursInEvent.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.edtMaxOccursInEvent.setObjectName(_fromUtf8("edtMaxOccursInEvent"))
        self.gridLayout.addWidget(self.edtMaxOccursInEvent, 12, 1, 1, 1)
        self.chkDefaultExecPerson = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkDefaultExecPerson.setObjectName(_fromUtf8("chkDefaultExecPerson"))
        self.gridLayout.addWidget(self.chkDefaultExecPerson, 25, 0, 1, 1)
        self.chkDefaultDirectionDate = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkDefaultDirectionDate.setObjectName(_fromUtf8("chkDefaultDirectionDate"))
        self.gridLayout.addWidget(self.chkDefaultDirectionDate, 24, 0, 1, 1)
        self.edtContext = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtContext.setEnabled(False)
        self.edtContext.setMaxLength(64)
        self.edtContext.setObjectName(_fromUtf8("edtContext"))
        self.gridLayout.addWidget(self.edtContext, 9, 1, 1, 1)
        self.pnlShowAPNotes = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.pnlShowAPNotes.setObjectName(_fromUtf8("pnlShowAPNotes"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.pnlShowAPNotes)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.chkChkShowAPNotes = QtGui.QCheckBox(self.pnlShowAPNotes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkShowAPNotes.sizePolicy().hasHeightForWidth())
        self.chkChkShowAPNotes.setSizePolicy(sizePolicy)
        self.chkChkShowAPNotes.setText(_fromUtf8(""))
        self.chkChkShowAPNotes.setObjectName(_fromUtf8("chkChkShowAPNotes"))
        self.horizontalLayout_11.addWidget(self.chkChkShowAPNotes)
        self.chkShowAPNotes = QtGui.QCheckBox(self.pnlShowAPNotes)
        self.chkShowAPNotes.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkShowAPNotes.sizePolicy().hasHeightForWidth())
        self.chkShowAPNotes.setSizePolicy(sizePolicy)
        self.chkShowAPNotes.setObjectName(_fromUtf8("chkShowAPNotes"))
        self.horizontalLayout_11.addWidget(self.chkShowAPNotes)
        self.gridLayout.addWidget(self.pnlShowAPNotes, 5, 0, 1, 2)
        self.chkDefaultPersonInEditor = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkDefaultPersonInEditor.setObjectName(_fromUtf8("chkDefaultPersonInEditor"))
        self.gridLayout.addWidget(self.chkDefaultPersonInEditor, 27, 0, 1, 1)
        self.cmbDefaultExecPerson = CPersonComboBoxEx(self.scrollAreaWidgetContents)
        self.cmbDefaultExecPerson.setEnabled(False)
        self.cmbDefaultExecPerson.setObjectName(_fromUtf8("cmbDefaultExecPerson"))
        self.gridLayout.addWidget(self.cmbDefaultExecPerson, 25, 1, 1, 1)
        self.grpPropertiesFields = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.grpPropertiesFields.setFlat(False)
        self.grpPropertiesFields.setCheckable(True)
        self.grpPropertiesFields.setChecked(False)
        self.grpPropertiesFields.setObjectName(_fromUtf8("grpPropertiesFields"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.grpPropertiesFields)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.chkPropertyAssignedVisible = QtGui.QCheckBox(self.grpPropertiesFields)
        self.chkPropertyAssignedVisible.setChecked(True)
        self.chkPropertyAssignedVisible.setObjectName(_fromUtf8("chkPropertyAssignedVisible"))
        self.verticalLayout_2.addWidget(self.chkPropertyAssignedVisible)
        self.chkPropertyUnitVisible = QtGui.QCheckBox(self.grpPropertiesFields)
        self.chkPropertyUnitVisible.setChecked(True)
        self.chkPropertyUnitVisible.setObjectName(_fromUtf8("chkPropertyUnitVisible"))
        self.verticalLayout_2.addWidget(self.chkPropertyUnitVisible)
        self.chkPropertyNormVisible = QtGui.QCheckBox(self.grpPropertiesFields)
        self.chkPropertyNormVisible.setChecked(True)
        self.chkPropertyNormVisible.setObjectName(_fromUtf8("chkPropertyNormVisible"))
        self.verticalLayout_2.addWidget(self.chkPropertyNormVisible)
        self.chkPropertyEvaluationVisible = QtGui.QCheckBox(self.grpPropertiesFields)
        self.chkPropertyEvaluationVisible.setChecked(True)
        self.chkPropertyEvaluationVisible.setObjectName(_fromUtf8("chkPropertyEvaluationVisible"))
        self.verticalLayout_2.addWidget(self.chkPropertyEvaluationVisible)
        self.gridLayout.addWidget(self.grpPropertiesFields, 35, 0, 1, 2)
        self.chkAge = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkAge.setObjectName(_fromUtf8("chkAge"))
        self.gridLayout.addWidget(self.chkAge, 1, 0, 1, 1)
        self.cmbDefaultBeginDate = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbDefaultBeginDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDefaultBeginDate.sizePolicy().hasHeightForWidth())
        self.cmbDefaultBeginDate.setSizePolicy(sizePolicy)
        self.cmbDefaultBeginDate.setObjectName(_fromUtf8("cmbDefaultBeginDate"))
        self.cmbDefaultBeginDate.addItem(_fromUtf8(""))
        self.cmbDefaultBeginDate.addItem(_fromUtf8(""))
        self.cmbDefaultBeginDate.addItem(_fromUtf8(""))
        self.cmbDefaultBeginDate.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbDefaultBeginDate, 22, 1, 1, 1)
        self.cmbDefaultEndDate = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbDefaultEndDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDefaultEndDate.sizePolicy().hasHeightForWidth())
        self.cmbDefaultEndDate.setSizePolicy(sizePolicy)
        self.cmbDefaultEndDate.setObjectName(_fromUtf8("cmbDefaultEndDate"))
        self.cmbDefaultEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultEndDate.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbDefaultEndDate, 23, 1, 1, 1)
        self.pnlRequiredCoordination = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.pnlRequiredCoordination.setObjectName(_fromUtf8("pnlRequiredCoordination"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.pnlRequiredCoordination)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.chkChkRequiredCoordination = QtGui.QCheckBox(self.pnlRequiredCoordination)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkRequiredCoordination.sizePolicy().hasHeightForWidth())
        self.chkChkRequiredCoordination.setSizePolicy(sizePolicy)
        self.chkChkRequiredCoordination.setText(_fromUtf8(""))
        self.chkChkRequiredCoordination.setObjectName(_fromUtf8("chkChkRequiredCoordination"))
        self.horizontalLayout_5.addWidget(self.chkChkRequiredCoordination)
        self.chkRequiredCoordination = QtGui.QCheckBox(self.pnlRequiredCoordination)
        self.chkRequiredCoordination.setEnabled(False)
        self.chkRequiredCoordination.setObjectName(_fromUtf8("chkRequiredCoordination"))
        self.horizontalLayout_5.addWidget(self.chkRequiredCoordination)
        self.gridLayout.addWidget(self.pnlRequiredCoordination, 6, 0, 1, 1)
        self.pnlShowInForm = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.pnlShowInForm.setObjectName(_fromUtf8("pnlShowInForm"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.pnlShowInForm)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.chkChkShowInForm = QtGui.QCheckBox(self.pnlShowInForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkShowInForm.sizePolicy().hasHeightForWidth())
        self.chkChkShowInForm.setSizePolicy(sizePolicy)
        self.chkChkShowInForm.setText(_fromUtf8(""))
        self.chkChkShowInForm.setObjectName(_fromUtf8("chkChkShowInForm"))
        self.horizontalLayout_4.addWidget(self.chkChkShowInForm)
        self.chkShowInForm = QtGui.QCheckBox(self.pnlShowInForm)
        self.chkShowInForm.setEnabled(False)
        self.chkShowInForm.setCheckable(True)
        self.chkShowInForm.setChecked(True)
        self.chkShowInForm.setObjectName(_fromUtf8("chkShowInForm"))
        self.horizontalLayout_4.addWidget(self.chkShowInForm)
        self.gridLayout.addWidget(self.pnlShowInForm, 8, 0, 1, 2)
        self.chkRecommendationExpirePeriod = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkRecommendationExpirePeriod.setObjectName(_fromUtf8("chkRecommendationExpirePeriod"))
        self.gridLayout.addWidget(self.chkRecommendationExpirePeriod, 14, 0, 1, 1)
        self.chkOffice = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkOffice.setObjectName(_fromUtf8("chkOffice"))
        self.gridLayout.addWidget(self.chkOffice, 33, 0, 1, 1)
        self.chkDefaultPlannedEndDate = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkDefaultPlannedEndDate.setObjectName(_fromUtf8("chkDefaultPlannedEndDate"))
        self.gridLayout.addWidget(self.chkDefaultPlannedEndDate, 21, 0, 1, 1)
        self.chkDefaultOrg = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkDefaultOrg.setObjectName(_fromUtf8("chkDefaultOrg"))
        self.gridLayout.addWidget(self.chkDefaultOrg, 31, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 36, 0, 1, 2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.edtRecommendationExpirePeriod = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.edtRecommendationExpirePeriod.setEnabled(False)
        self.edtRecommendationExpirePeriod.setObjectName(_fromUtf8("edtRecommendationExpirePeriod"))
        self.horizontalLayout_8.addWidget(self.edtRecommendationExpirePeriod)
        self.lblFrequencyCount_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFrequencyCount_2.sizePolicy().hasHeightForWidth())
        self.lblFrequencyCount_2.setSizePolicy(sizePolicy)
        self.lblFrequencyCount_2.setObjectName(_fromUtf8("lblFrequencyCount_2"))
        self.horizontalLayout_8.addWidget(self.lblFrequencyCount_2)
        self.gridLayout.addLayout(self.horizontalLayout_8, 14, 1, 1, 1)
        self.frameAge = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameAge.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameAge.sizePolicy().hasHeightForWidth())
        self.frameAge.setSizePolicy(sizePolicy)
        self.frameAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAge.setObjectName(_fromUtf8("frameAge"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frameAge)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cmbBegAgeUnit = QtGui.QComboBox(self.frameAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbBegAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbBegAgeUnit.setSizePolicy(sizePolicy)
        self.cmbBegAgeUnit.setObjectName(_fromUtf8("cmbBegAgeUnit"))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cmbBegAgeUnit)
        self.edtBegAgeCount = QtGui.QLineEdit(self.frameAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegAgeCount.sizePolicy().hasHeightForWidth())
        self.edtBegAgeCount.setSizePolicy(sizePolicy)
        self.edtBegAgeCount.setMaxLength(3)
        self.edtBegAgeCount.setObjectName(_fromUtf8("edtBegAgeCount"))
        self.horizontalLayout_2.addWidget(self.edtBegAgeCount)
        self.lblAgeSep = QtGui.QLabel(self.frameAge)
        self.lblAgeSep.setObjectName(_fromUtf8("lblAgeSep"))
        self.horizontalLayout_2.addWidget(self.lblAgeSep)
        self.cmbEndAgeUnit = QtGui.QComboBox(self.frameAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEndAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbEndAgeUnit.setSizePolicy(sizePolicy)
        self.cmbEndAgeUnit.setObjectName(_fromUtf8("cmbEndAgeUnit"))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cmbEndAgeUnit)
        self.edtEndAgeCount = QtGui.QLineEdit(self.frameAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndAgeCount.sizePolicy().hasHeightForWidth())
        self.edtEndAgeCount.setSizePolicy(sizePolicy)
        self.edtEndAgeCount.setMaxLength(3)
        self.edtEndAgeCount.setObjectName(_fromUtf8("edtEndAgeCount"))
        self.horizontalLayout_2.addWidget(self.edtEndAgeCount)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(4, 1)
        self.horizontalLayout_2.setStretch(5, 4)
        self.gridLayout.addWidget(self.frameAge, 1, 1, 1, 1)
        self.cmbDefaultDirectionDate = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbDefaultDirectionDate.setEnabled(False)
        self.cmbDefaultDirectionDate.setObjectName(_fromUtf8("cmbDefaultDirectionDate"))
        self.cmbDefaultDirectionDate.addItem(_fromUtf8(""))
        self.cmbDefaultDirectionDate.addItem(_fromUtf8(""))
        self.cmbDefaultDirectionDate.addItem(_fromUtf8(""))
        self.cmbDefaultDirectionDate.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbDefaultDirectionDate, 24, 1, 1, 1)
        self.pnlExecRequiredForEventExec = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.pnlExecRequiredForEventExec.setEnabled(True)
        self.pnlExecRequiredForEventExec.setObjectName(_fromUtf8("pnlExecRequiredForEventExec"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.pnlExecRequiredForEventExec)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkChkExecRequiredForEventExec = QtGui.QCheckBox(self.pnlExecRequiredForEventExec)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkExecRequiredForEventExec.sizePolicy().hasHeightForWidth())
        self.chkChkExecRequiredForEventExec.setSizePolicy(sizePolicy)
        self.chkChkExecRequiredForEventExec.setText(_fromUtf8(""))
        self.chkChkExecRequiredForEventExec.setObjectName(_fromUtf8("chkChkExecRequiredForEventExec"))
        self.horizontalLayout.addWidget(self.chkChkExecRequiredForEventExec)
        self.chkExecRequiredForEventExec = QtGui.QCheckBox(self.pnlExecRequiredForEventExec)
        self.chkExecRequiredForEventExec.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkExecRequiredForEventExec.sizePolicy().hasHeightForWidth())
        self.chkExecRequiredForEventExec.setSizePolicy(sizePolicy)
        self.chkExecRequiredForEventExec.setCheckable(True)
        self.chkExecRequiredForEventExec.setChecked(True)
        self.chkExecRequiredForEventExec.setObjectName(_fromUtf8("chkExecRequiredForEventExec"))
        self.horizontalLayout.addWidget(self.chkExecRequiredForEventExec)
        self.gridLayout.addWidget(self.pnlExecRequiredForEventExec, 16, 0, 1, 2)
        self.cmbAssistantRequired = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbAssistantRequired.setEnabled(False)
        self.cmbAssistantRequired.setObjectName(_fromUtf8("cmbAssistantRequired"))
        self.cmbAssistantRequired.addItem(_fromUtf8(""))
        self.cmbAssistantRequired.addItem(_fromUtf8(""))
        self.cmbAssistantRequired.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbAssistantRequired, 7, 1, 1, 1)
        self.pnlRecommendationControl = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.pnlRecommendationControl.setObjectName(_fromUtf8("pnlRecommendationControl"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.pnlRecommendationControl)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.chkChkRecommendationControl = QtGui.QCheckBox(self.pnlRecommendationControl)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkRecommendationControl.sizePolicy().hasHeightForWidth())
        self.chkChkRecommendationControl.setSizePolicy(sizePolicy)
        self.chkChkRecommendationControl.setText(_fromUtf8(""))
        self.chkChkRecommendationControl.setObjectName(_fromUtf8("chkChkRecommendationControl"))
        self.horizontalLayout_7.addWidget(self.chkChkRecommendationControl)
        self.chkRecommendationControl = QtGui.QCheckBox(self.pnlRecommendationControl)
        self.chkRecommendationControl.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkRecommendationControl.sizePolicy().hasHeightForWidth())
        self.chkRecommendationControl.setSizePolicy(sizePolicy)
        self.chkRecommendationControl.setCheckable(True)
        self.chkRecommendationControl.setChecked(True)
        self.chkRecommendationControl.setObjectName(_fromUtf8("chkRecommendationControl"))
        self.horizontalLayout_7.addWidget(self.chkRecommendationControl)
        self.gridLayout.addWidget(self.pnlRecommendationControl, 15, 0, 1, 2)
        self.chkDefaultStatus = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkDefaultStatus.setObjectName(_fromUtf8("chkDefaultStatus"))
        self.gridLayout.addWidget(self.chkDefaultStatus, 20, 0, 1, 1)
        self.edtOffice = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtOffice.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtOffice.sizePolicy().hasHeightForWidth())
        self.edtOffice.setSizePolicy(sizePolicy)
        self.edtOffice.setObjectName(_fromUtf8("edtOffice"))
        self.gridLayout.addWidget(self.edtOffice, 33, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.buttonBox = QtGui.QDialogButtonBox(GroupActionTypeEditorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.lblAgeSep.setBuddy(self.cmbEndAgeUnit)

        self.retranslateUi(GroupActionTypeEditorDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), GroupActionTypeEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), GroupActionTypeEditorDialog.reject)
        QtCore.QObject.connect(self.chkSex, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbSex.setEnabled)
        QtCore.QObject.connect(self.chkAge, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.frameAge.setEnabled)
        QtCore.QObject.connect(self.chkContext, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtContext.setEnabled)
        QtCore.QObject.connect(self.chkMaxOccursInEvent, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtMaxOccursInEvent.setEnabled)
        QtCore.QObject.connect(self.chkDefaultStatus, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbDefaultStatus.setEnabled)
        QtCore.QObject.connect(self.chkDefaultPlannedEndDate, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbDefaultPlannedEndDate.setEnabled)
        QtCore.QObject.connect(self.chkDefaultEndDate, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbDefaultEndDate.setEnabled)
        QtCore.QObject.connect(self.chkDefaultDirectionDate, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbDefaultDirectionDate.setEnabled)
        QtCore.QObject.connect(self.chkDefaultExecPerson, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbDefaultExecPerson.setEnabled)
        QtCore.QObject.connect(self.chkDefaultPersonInEvent, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbDefaultPersonInEvent.setEnabled)
        QtCore.QObject.connect(self.chkDefaultPersonInEditor, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbDefaultPersonInEditor.setEnabled)
        QtCore.QObject.connect(self.chkDefaultMKB, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbDefaultMKB.setEnabled)
        QtCore.QObject.connect(self.chkIsMorphologyRequired, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbIsMorphologyRequired.setEnabled)
        QtCore.QObject.connect(self.chkDefaultOrg, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbDefaultOrg.setEnabled)
        QtCore.QObject.connect(self.chkAmount, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtAmount.setEnabled)
        QtCore.QObject.connect(self.chkOffice, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtOffice.setEnabled)
        QtCore.QObject.connect(self.chkChkShowInForm, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.chkShowInForm.setEnabled)
        QtCore.QObject.connect(self.chkPreferable, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.chkIsPreferable.setEnabled)
        QtCore.QObject.connect(self.chkChkShowTime, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.chkShowTime.setEnabled)
        QtCore.QObject.connect(self.chkChkRequiredCoordination, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.chkRequiredCoordination.setEnabled)
        QtCore.QObject.connect(self.chkServiceType, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbServiceType.setEnabled)
        QtCore.QObject.connect(self.chkAssistant, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbAssistantRequired.setEnabled)
        QtCore.QObject.connect(self.chkChkRecommendationControl, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.chkRecommendationControl.setEnabled)
        QtCore.QObject.connect(self.chkRecommendationExpirePeriod, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtRecommendationExpirePeriod.setEnabled)
        QtCore.QObject.connect(self.chkChkExecRequiredForEventExec, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.chkExecRequiredForEventExec.setEnabled)
        QtCore.QObject.connect(self.chkDefaultBeginDate, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbDefaultBeginDate.setEnabled)
        QtCore.QObject.connect(self.chkChkShowAPOrg, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkShowAPOrg.setEnabled)
        QtCore.QObject.connect(self.chkChkShowAPNotes, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkShowAPNotes.setEnabled)
        QtCore.QObject.connect(self.chkChkIgnoreEventEndDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkIgnoreEventEndDate.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(GroupActionTypeEditorDialog)
        GroupActionTypeEditorDialog.setTabOrder(self.chkSex, self.cmbSex)
        GroupActionTypeEditorDialog.setTabOrder(self.cmbSex, self.chkAge)
        GroupActionTypeEditorDialog.setTabOrder(self.chkAge, self.cmbBegAgeUnit)
        GroupActionTypeEditorDialog.setTabOrder(self.cmbBegAgeUnit, self.edtBegAgeCount)
        GroupActionTypeEditorDialog.setTabOrder(self.edtBegAgeCount, self.cmbEndAgeUnit)
        GroupActionTypeEditorDialog.setTabOrder(self.cmbEndAgeUnit, self.edtEndAgeCount)
        GroupActionTypeEditorDialog.setTabOrder(self.edtEndAgeCount, self.chkChkShowTime)
        GroupActionTypeEditorDialog.setTabOrder(self.chkChkShowTime, self.chkShowTime)
        GroupActionTypeEditorDialog.setTabOrder(self.chkShowTime, self.chkChkRequiredCoordination)
        GroupActionTypeEditorDialog.setTabOrder(self.chkChkRequiredCoordination, self.chkRequiredCoordination)
        GroupActionTypeEditorDialog.setTabOrder(self.chkRequiredCoordination, self.chkChkShowInForm)
        GroupActionTypeEditorDialog.setTabOrder(self.chkChkShowInForm, self.chkShowInForm)
        GroupActionTypeEditorDialog.setTabOrder(self.chkShowInForm, self.chkContext)
        GroupActionTypeEditorDialog.setTabOrder(self.chkContext, self.edtContext)
        GroupActionTypeEditorDialog.setTabOrder(self.edtContext, self.chkPreferable)
        GroupActionTypeEditorDialog.setTabOrder(self.chkPreferable, self.chkIsPreferable)
        GroupActionTypeEditorDialog.setTabOrder(self.chkIsPreferable, self.chkMaxOccursInEvent)
        GroupActionTypeEditorDialog.setTabOrder(self.chkMaxOccursInEvent, self.edtMaxOccursInEvent)
        GroupActionTypeEditorDialog.setTabOrder(self.edtMaxOccursInEvent, self.chkDefaultStatus)
        GroupActionTypeEditorDialog.setTabOrder(self.chkDefaultStatus, self.chkDefaultPlannedEndDate)
        GroupActionTypeEditorDialog.setTabOrder(self.chkDefaultPlannedEndDate, self.chkDefaultEndDate)
        GroupActionTypeEditorDialog.setTabOrder(self.chkDefaultEndDate, self.chkDefaultDirectionDate)
        GroupActionTypeEditorDialog.setTabOrder(self.chkDefaultDirectionDate, self.chkDefaultExecPerson)
        GroupActionTypeEditorDialog.setTabOrder(self.chkDefaultExecPerson, self.chkDefaultPersonInEvent)
        GroupActionTypeEditorDialog.setTabOrder(self.chkDefaultPersonInEvent, self.chkDefaultPersonInEditor)
        GroupActionTypeEditorDialog.setTabOrder(self.chkDefaultPersonInEditor, self.chkDefaultMKB)
        GroupActionTypeEditorDialog.setTabOrder(self.chkDefaultMKB, self.chkIsMorphologyRequired)
        GroupActionTypeEditorDialog.setTabOrder(self.chkIsMorphologyRequired, self.chkDefaultOrg)
        GroupActionTypeEditorDialog.setTabOrder(self.chkDefaultOrg, self.chkAmount)
        GroupActionTypeEditorDialog.setTabOrder(self.chkAmount, self.chkOffice)
        GroupActionTypeEditorDialog.setTabOrder(self.chkOffice, self.grpPropertiesFields)
        GroupActionTypeEditorDialog.setTabOrder(self.grpPropertiesFields, self.chkPropertyAssignedVisible)
        GroupActionTypeEditorDialog.setTabOrder(self.chkPropertyAssignedVisible, self.chkPropertyUnitVisible)
        GroupActionTypeEditorDialog.setTabOrder(self.chkPropertyUnitVisible, self.chkPropertyNormVisible)
        GroupActionTypeEditorDialog.setTabOrder(self.chkPropertyNormVisible, self.chkPropertyEvaluationVisible)

    def retranslateUi(self, GroupActionTypeEditorDialog):
        GroupActionTypeEditorDialog.setWindowTitle(_translate("GroupActionTypeEditorDialog", "Dialog", None))
        self.chkMaxOccursInEvent.setText(_translate("GroupActionTypeEditorDialog", "Макс. количество в событии", None))
        self.chkShowTime.setText(_translate("GroupActionTypeEditorDialog", "Показывать в интерфейсе время назначения/начала/окончания", None))
        self.chkIsPreferable.setText(_translate("GroupActionTypeEditorDialog", "Является предпочитаемым(-ой)", None))
        self.chkIsMorphologyRequired.setText(_translate("GroupActionTypeEditorDialog", "Заполнение `морфологии`", None))
        self.chkServiceType.setText(_translate("GroupActionTypeEditorDialog", "Вид услуги", None))
        self.chkDefaultMorphology.setText(_translate("GroupActionTypeEditorDialog", "Морфология по умолчанию", None))
        self.chkSex.setText(_translate("GroupActionTypeEditorDialog", "Пол", None))
        self.cmbSex.setItemText(1, _translate("GroupActionTypeEditorDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("GroupActionTypeEditorDialog", "Ж", None))
        self.cmbDefaultPersonInEvent.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultPersonInEvent.setItemText(1, _translate("GroupActionTypeEditorDialog", "Не заполняется", None))
        self.cmbDefaultPersonInEvent.setItemText(2, _translate("GroupActionTypeEditorDialog", "Назначивший действие", None))
        self.cmbDefaultPersonInEvent.setItemText(3, _translate("GroupActionTypeEditorDialog", "Ответственный за событие", None))
        self.cmbDefaultPersonInEvent.setItemText(4, _translate("GroupActionTypeEditorDialog", "Пользователь", None))
        self.cmbDefaultPlannedEndDate.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultPlannedEndDate.setItemText(1, _translate("GroupActionTypeEditorDialog", "Следующий день", None))
        self.cmbDefaultPlannedEndDate.setItemText(2, _translate("GroupActionTypeEditorDialog", "Следующий рабочий день", None))
        self.cmbDefaultPlannedEndDate.setItemText(3, _translate("GroupActionTypeEditorDialog", "Дата талона на Работу", None))
        self.cmbDefaultPlannedEndDate.setItemText(4, _translate("GroupActionTypeEditorDialog", "Дата начала + количество", None))
        self.cmbDefaultPlannedEndDate.setItemText(5, _translate("GroupActionTypeEditorDialog", "Дата начала + длительность", None))
        self.chkIgnoreEventEndDate.setText(_translate("GroupActionTypeEditorDialog", "Игнорировать дату окончания события", None))
        self.chkAssistant.setText(_translate("GroupActionTypeEditorDialog", "Ввод ассистента", None))
        self.cmbDefaultPersonInEditor.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultPersonInEditor.setItemText(1, _translate("GroupActionTypeEditorDialog", "Не заполняется", None))
        self.cmbDefaultPersonInEditor.setItemText(2, _translate("GroupActionTypeEditorDialog", "Назначивший действие", None))
        self.cmbDefaultPersonInEditor.setItemText(3, _translate("GroupActionTypeEditorDialog", "Ответственный за событие", None))
        self.cmbDefaultPersonInEditor.setItemText(4, _translate("GroupActionTypeEditorDialog", "Пользователь", None))
        self.chkDefaultMKB.setText(_translate("GroupActionTypeEditorDialog", "МКБ по умолчанию", None))
        self.chkShowAPOrg.setText(_translate("GroupActionTypeEditorDialog", "Показывать в интерфейсе \"место выполнения\"", None))
        self.chkDefaultPersonInEvent.setText(_translate("GroupActionTypeEditorDialog", "Исполнитель в событии", None))
        self.cmbDefaultMKB.setItemText(0, _translate("GroupActionTypeEditorDialog", "не используется", None))
        self.cmbDefaultMKB.setItemText(1, _translate("GroupActionTypeEditorDialog", "по заключительному", None))
        self.cmbDefaultMKB.setItemText(2, _translate("GroupActionTypeEditorDialog", "по диагнозу назначившего действие", None))
        self.cmbDefaultMKB.setItemText(3, _translate("GroupActionTypeEditorDialog", "синхронизировать с заключительным", None))
        self.cmbDefaultMKB.setItemText(4, _translate("GroupActionTypeEditorDialog", "синхронизировать с диагнозом назначившего действие", None))
        self.cmbDefaultMKB.setItemText(5, _translate("GroupActionTypeEditorDialog", "пустой", None))
        self.cmbDefaultMorphology.setItemText(0, _translate("GroupActionTypeEditorDialog", "не используется", None))
        self.cmbDefaultMorphology.setItemText(1, _translate("GroupActionTypeEditorDialog", "по заключительному", None))
        self.cmbDefaultMorphology.setItemText(2, _translate("GroupActionTypeEditorDialog", "по диагнозу назначившего действие", None))
        self.cmbDefaultMorphology.setItemText(3, _translate("GroupActionTypeEditorDialog", "синхронизировать с заключительным", None))
        self.cmbDefaultMorphology.setItemText(4, _translate("GroupActionTypeEditorDialog", "синхронизировать с диагнозом назначившего действие", None))
        self.chkDefaultEndDate.setText(_translate("GroupActionTypeEditorDialog", "&Дата окончания", None))
        self.cmbIsMorphologyRequired.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не проверяется", None))
        self.cmbIsMorphologyRequired.setItemText(1, _translate("GroupActionTypeEditorDialog", "Мягкий контроль", None))
        self.cmbIsMorphologyRequired.setItemText(2, _translate("GroupActionTypeEditorDialog", "Жесткий контроль", None))
        self.chkContext.setText(_translate("GroupActionTypeEditorDialog", "Контекст печати", None))
        self.chkAmount.setText(_translate("GroupActionTypeEditorDialog", "Ко&личество", None))
        self.chkDefaultBeginDate.setText(_translate("GroupActionTypeEditorDialog", "Дата начала", None))
        self.edtMaxOccursInEvent.setToolTip(_translate("GroupActionTypeEditorDialog", "0 - нет ограничения", None))
        self.chkDefaultExecPerson.setText(_translate("GroupActionTypeEditorDialog", "Исполнитель по умолчанию", None))
        self.chkDefaultDirectionDate.setText(_translate("GroupActionTypeEditorDialog", "Дата назначения", None))
        self.chkShowAPNotes.setText(_translate("GroupActionTypeEditorDialog", "Показывать в интерфейсе \"примечания\"", None))
        self.chkDefaultPersonInEditor.setText(_translate("GroupActionTypeEditorDialog", "Исполнитель в отд.редакторе", None))
        self.grpPropertiesFields.setTitle(_translate("GroupActionTypeEditorDialog", "Настройка визуализации колонок свойств в редакторе Действия", None))
        self.chkPropertyAssignedVisible.setText(_translate("GroupActionTypeEditorDialog", "Колонка `назначено`", None))
        self.chkPropertyUnitVisible.setText(_translate("GroupActionTypeEditorDialog", "Колонка `единица измерения`", None))
        self.chkPropertyNormVisible.setText(_translate("GroupActionTypeEditorDialog", "Колонка `норма`", None))
        self.chkPropertyEvaluationVisible.setText(_translate("GroupActionTypeEditorDialog", "Колонка `оценка`", None))
        self.chkAge.setText(_translate("GroupActionTypeEditorDialog", "Возраст", None))
        self.cmbDefaultBeginDate.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultBeginDate.setItemText(1, _translate("GroupActionTypeEditorDialog", "Текущая дата", None))
        self.cmbDefaultBeginDate.setItemText(2, _translate("GroupActionTypeEditorDialog", "Дата начала события", None))
        self.cmbDefaultBeginDate.setItemText(3, _translate("GroupActionTypeEditorDialog", "Дата окончания события", None))
        self.cmbDefaultEndDate.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultEndDate.setItemText(1, _translate("GroupActionTypeEditorDialog", "Текущая дата", None))
        self.cmbDefaultEndDate.setItemText(2, _translate("GroupActionTypeEditorDialog", "Дата начала события", None))
        self.cmbDefaultEndDate.setItemText(3, _translate("GroupActionTypeEditorDialog", "Дата окончания события", None))
        self.chkRequiredCoordination.setText(_translate("GroupActionTypeEditorDialog", "Требует обязательного согласования", None))
        self.chkShowInForm.setText(_translate("GroupActionTypeEditorDialog", "Разрешается выбор в формах ввода событий", None))
        self.chkRecommendationExpirePeriod.setText(_translate("GroupActionTypeEditorDialog", "Период актуальности рекомендации", None))
        self.chkOffice.setText(_translate("GroupActionTypeEditorDialog", "Кабине&т", None))
        self.chkDefaultPlannedEndDate.setText(_translate("GroupActionTypeEditorDialog", "Планируемая дата выполнения", None))
        self.chkDefaultOrg.setText(_translate("GroupActionTypeEditorDialog", "Организация по умолчанию", None))
        self.lblFrequencyCount_2.setText(_translate("GroupActionTypeEditorDialog", "дней", None))
        self.cmbBegAgeUnit.setItemText(1, _translate("GroupActionTypeEditorDialog", "Д", None))
        self.cmbBegAgeUnit.setItemText(2, _translate("GroupActionTypeEditorDialog", "Н", None))
        self.cmbBegAgeUnit.setItemText(3, _translate("GroupActionTypeEditorDialog", "М", None))
        self.cmbBegAgeUnit.setItemText(4, _translate("GroupActionTypeEditorDialog", "Г", None))
        self.edtBegAgeCount.setInputMask(_translate("GroupActionTypeEditorDialog", "000", None))
        self.lblAgeSep.setText(_translate("GroupActionTypeEditorDialog", "по", None))
        self.cmbEndAgeUnit.setItemText(1, _translate("GroupActionTypeEditorDialog", "Д", None))
        self.cmbEndAgeUnit.setItemText(2, _translate("GroupActionTypeEditorDialog", "Н", None))
        self.cmbEndAgeUnit.setItemText(3, _translate("GroupActionTypeEditorDialog", "М", None))
        self.cmbEndAgeUnit.setItemText(4, _translate("GroupActionTypeEditorDialog", "Г", None))
        self.edtEndAgeCount.setInputMask(_translate("GroupActionTypeEditorDialog", "000", None))
        self.cmbDefaultDirectionDate.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultDirectionDate.setItemText(1, _translate("GroupActionTypeEditorDialog", "Дата начала события", None))
        self.cmbDefaultDirectionDate.setItemText(2, _translate("GroupActionTypeEditorDialog", "Текущая дата", None))
        self.cmbDefaultDirectionDate.setItemText(3, _translate("GroupActionTypeEditorDialog", "Синхронизация по дате выполнения", None))
        self.chkExecRequiredForEventExec.setText(_translate("GroupActionTypeEditorDialog", "Контроль выполнения услуги в законченном событии (Да/Нет)", None))
        self.cmbAssistantRequired.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не требуется", None))
        self.cmbAssistantRequired.setItemText(1, _translate("GroupActionTypeEditorDialog", "Необязательное заполнение", None))
        self.cmbAssistantRequired.setItemText(2, _translate("GroupActionTypeEditorDialog", "Обязательное заполнение", None))
        self.chkRecommendationControl.setText(_translate("GroupActionTypeEditorDialog", "Контроль назначившего", None))
        self.chkDefaultStatus.setText(_translate("GroupActionTypeEditorDialog", "С&остояние", None))

from Orgs.OrgComboBox import CPolyclinicComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
