# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OrgStructureEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ItemEditorDialog(object):
    def setupUi(self, ItemEditorDialog):
        ItemEditorDialog.setObjectName(_fromUtf8("ItemEditorDialog"))
        ItemEditorDialog.resize(1216, 1008)
        ItemEditorDialog.setSizeGripEnabled(True)
        self.gridLayout_3 = QtGui.QGridLayout(ItemEditorDialog)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.buttonBox = QtGui.QDialogButtonBox(ItemEditorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(ItemEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMain = QtGui.QWidget()
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.gridLayout = QtGui.QGridLayout(self.tabMain)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblAttachCode = QtGui.QLabel(self.tabMain)
        self.lblAttachCode.setObjectName(_fromUtf8("lblAttachCode"))
        self.gridLayout.addWidget(self.lblAttachCode, 18, 0, 1, 1)
        self.lblMiacHead = QtGui.QLabel(self.tabMain)
        self.lblMiacHead.setEnabled(False)
        self.lblMiacHead.setObjectName(_fromUtf8("lblMiacHead"))
        self.gridLayout.addWidget(self.lblMiacHead, 20, 0, 1, 1)
        self.btnSelectOrganisation = QtGui.QToolButton(self.tabMain)
        self.btnSelectOrganisation.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectOrganisation.sizePolicy().hasHeightForWidth())
        self.btnSelectOrganisation.setSizePolicy(sizePolicy)
        self.btnSelectOrganisation.setObjectName(_fromUtf8("btnSelectOrganisation"))
        self.gridLayout.addWidget(self.btnSelectOrganisation, 0, 3, 1, 1)
        self.chkAvailableForExternal = QtGui.QCheckBox(self.tabMain)
        self.chkAvailableForExternal.setObjectName(_fromUtf8("chkAvailableForExternal"))
        self.gridLayout.addWidget(self.chkAvailableForExternal, 29, 2, 1, 2)
        self.lblBookkeeperCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBookkeeperCode.sizePolicy().hasHeightForWidth())
        self.lblBookkeeperCode.setSizePolicy(sizePolicy)
        self.lblBookkeeperCode.setObjectName(_fromUtf8("lblBookkeeperCode"))
        self.gridLayout.addWidget(self.lblBookkeeperCode, 4, 0, 1, 1)
        self.chkHasHospitalBeds = QtGui.QCheckBox(self.tabMain)
        self.chkHasHospitalBeds.setObjectName(_fromUtf8("chkHasHospitalBeds"))
        self.gridLayout.addWidget(self.chkHasHospitalBeds, 26, 2, 1, 2)
        self.edtName = QtGui.QLineEdit(self.tabMain)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 6, 2, 1, 2)
        self.edtInfisDepTypeCode = QtGui.QLineEdit(self.tabMain)
        self.edtInfisDepTypeCode.setMaxLength(30)
        self.edtInfisDepTypeCode.setObjectName(_fromUtf8("edtInfisDepTypeCode"))
        self.gridLayout.addWidget(self.edtInfisDepTypeCode, 14, 2, 1, 2)
        self.lblInfisCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInfisCode.sizePolicy().hasHeightForWidth())
        self.lblInfisCode.setSizePolicy(sizePolicy)
        self.lblInfisCode.setObjectName(_fromUtf8("lblInfisCode"))
        self.gridLayout.addWidget(self.lblInfisCode, 12, 0, 1, 1)
        self.chkHasStocks = QtGui.QCheckBox(self.tabMain)
        self.chkHasStocks.setObjectName(_fromUtf8("chkHasStocks"))
        self.gridLayout.addWidget(self.chkHasStocks, 27, 2, 1, 2)
        self.lblHeadNurse = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHeadNurse.sizePolicy().hasHeightForWidth())
        self.lblHeadNurse.setSizePolicy(sizePolicy)
        self.lblHeadNurse.setObjectName(_fromUtf8("lblHeadNurse"))
        self.gridLayout.addWidget(self.lblHeadNurse, 11, 0, 1, 1)
        self.label = QtGui.QLabel(self.tabMain)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.lblInfisTariffCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInfisTariffCode.sizePolicy().hasHeightForWidth())
        self.lblInfisTariffCode.setSizePolicy(sizePolicy)
        self.lblInfisTariffCode.setObjectName(_fromUtf8("lblInfisTariffCode"))
        self.gridLayout.addWidget(self.lblInfisTariffCode, 16, 0, 1, 1)
        self.edtStorageCode = QtGui.QLineEdit(self.tabMain)
        self.edtStorageCode.setObjectName(_fromUtf8("edtStorageCode"))
        self.gridLayout.addWidget(self.edtStorageCode, 3, 2, 1, 2)
        self.lblChief = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblChief.sizePolicy().hasHeightForWidth())
        self.lblChief.setSizePolicy(sizePolicy)
        self.lblChief.setObjectName(_fromUtf8("lblChief"))
        self.gridLayout.addWidget(self.lblChief, 10, 0, 1, 1)
        self.lblNet = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNet.sizePolicy().hasHeightForWidth())
        self.lblNet.setSizePolicy(sizePolicy)
        self.lblNet.setObjectName(_fromUtf8("lblNet"))
        self.gridLayout.addWidget(self.lblNet, 9, 0, 1, 1)
        self.chkVisibleInDR = QtGui.QCheckBox(self.tabMain)
        self.chkVisibleInDR.setChecked(True)
        self.chkVisibleInDR.setObjectName(_fromUtf8("chkVisibleInDR"))
        self.gridLayout.addWidget(self.chkVisibleInDR, 25, 2, 1, 2)
        self.cmbHeadNurse = CPersonComboBoxEx(self.tabMain)
        self.cmbHeadNurse.setObjectName(_fromUtf8("cmbHeadNurse"))
        self.gridLayout.addWidget(self.cmbHeadNurse, 11, 2, 1, 2)
        self.cmbType = CEnumComboBox(self.tabMain)
        self.cmbType.setObjectName(_fromUtf8("cmbType"))
        self.gridLayout.addWidget(self.cmbType, 8, 2, 1, 2)
        self.cmbChief = CPersonComboBoxEx(self.tabMain)
        self.cmbChief.setObjectName(_fromUtf8("cmbChief"))
        self.gridLayout.addWidget(self.cmbChief, 10, 2, 1, 2)
        self.lblType = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblType.sizePolicy().hasHeightForWidth())
        self.lblType.setSizePolicy(sizePolicy)
        self.lblType.setObjectName(_fromUtf8("lblType"))
        self.gridLayout.addWidget(self.lblType, 8, 0, 1, 1)
        self.lblSyncGUID = QtGui.QLabel(self.tabMain)
        self.lblSyncGUID.setObjectName(_fromUtf8("lblSyncGUID"))
        self.gridLayout.addWidget(self.lblSyncGUID, 17, 0, 1, 1)
        self.lblCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout.addWidget(self.lblCode, 2, 0, 1, 1)
        self.edtAddress = QtGui.QLineEdit(self.tabMain)
        self.edtAddress.setObjectName(_fromUtf8("edtAddress"))
        self.gridLayout.addWidget(self.edtAddress, 7, 2, 1, 2)
        self.lblOrganisation = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrganisation.sizePolicy().hasHeightForWidth())
        self.lblOrganisation.setSizePolicy(sizePolicy)
        self.lblOrganisation.setObjectName(_fromUtf8("lblOrganisation"))
        self.gridLayout.addWidget(self.lblOrganisation, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 41, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 30, 0, 1, 1)
        self.cmbNet = CRBComboBox(self.tabMain)
        self.cmbNet.setObjectName(_fromUtf8("cmbNet"))
        self.gridLayout.addWidget(self.cmbNet, 9, 2, 1, 2)
        self.lblInfisDepTypeCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInfisDepTypeCode.sizePolicy().hasHeightForWidth())
        self.lblInfisDepTypeCode.setSizePolicy(sizePolicy)
        self.lblInfisDepTypeCode.setObjectName(_fromUtf8("lblInfisDepTypeCode"))
        self.gridLayout.addWidget(self.lblInfisDepTypeCode, 14, 0, 1, 1)
        self.chkHasDS = QtGui.QCheckBox(self.tabMain)
        self.chkHasDS.setObjectName(_fromUtf8("chkHasDS"))
        self.gridLayout.addWidget(self.chkHasDS, 28, 2, 1, 2)
        self.lblAddress = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAddress.sizePolicy().hasHeightForWidth())
        self.lblAddress.setSizePolicy(sizePolicy)
        self.lblAddress.setObjectName(_fromUtf8("lblAddress"))
        self.gridLayout.addWidget(self.lblAddress, 7, 0, 1, 1)
        self.lblInfisInternalCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInfisInternalCode.sizePolicy().hasHeightForWidth())
        self.lblInfisInternalCode.setSizePolicy(sizePolicy)
        self.lblInfisInternalCode.setObjectName(_fromUtf8("lblInfisInternalCode"))
        self.gridLayout.addWidget(self.lblInfisInternalCode, 13, 0, 1, 1)
        self.cmbParent = CDbComboBox(self.tabMain)
        self.cmbParent.setEnabled(False)
        self.cmbParent.setFrame(True)
        self.cmbParent.setObjectName(_fromUtf8("cmbParent"))
        self.gridLayout.addWidget(self.cmbParent, 1, 2, 1, 2)
        self.cmbIsArea = CEnumComboBox(self.tabMain)
        self.cmbIsArea.setObjectName(_fromUtf8("cmbIsArea"))
        self.gridLayout.addWidget(self.cmbIsArea, 19, 2, 1, 2)
        self.edtInfisTariffCode = QtGui.QLineEdit(self.tabMain)
        self.edtInfisTariffCode.setMaxLength(16)
        self.edtInfisTariffCode.setObjectName(_fromUtf8("edtInfisTariffCode"))
        self.gridLayout.addWidget(self.edtInfisTariffCode, 16, 2, 1, 2)
        self.edtCode = QtGui.QLineEdit(self.tabMain)
        self.edtCode.setMaxLength(64)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout.addWidget(self.edtCode, 2, 2, 1, 2)
        self.edtInfisInternalCode = QtGui.QLineEdit(self.tabMain)
        self.edtInfisInternalCode.setMaxLength(30)
        self.edtInfisInternalCode.setObjectName(_fromUtf8("edtInfisInternalCode"))
        self.gridLayout.addWidget(self.edtInfisInternalCode, 13, 2, 1, 2)
        self.lblDayLimit = QtGui.QLabel(self.tabMain)
        self.lblDayLimit.setObjectName(_fromUtf8("lblDayLimit"))
        self.gridLayout.addWidget(self.lblDayLimit, 21, 0, 1, 1)
        self.edtInfisCode = QtGui.QLineEdit(self.tabMain)
        self.edtInfisCode.setMaxLength(16)
        self.edtInfisCode.setObjectName(_fromUtf8("edtInfisCode"))
        self.gridLayout.addWidget(self.edtInfisCode, 12, 2, 1, 2)
        self.lblIsArea = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblIsArea.sizePolicy().hasHeightForWidth())
        self.lblIsArea.setSizePolicy(sizePolicy)
        self.lblIsArea.setObjectName(_fromUtf8("lblIsArea"))
        self.gridLayout.addWidget(self.lblIsArea, 19, 0, 1, 1)
        self.edtBookkeeperCode = QtGui.QLineEdit(self.tabMain)
        self.edtBookkeeperCode.setObjectName(_fromUtf8("edtBookkeeperCode"))
        self.gridLayout.addWidget(self.edtBookkeeperCode, 4, 2, 1, 2)
        self.lblParent = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblParent.sizePolicy().hasHeightForWidth())
        self.lblParent.setSizePolicy(sizePolicy)
        self.lblParent.setObjectName(_fromUtf8("lblParent"))
        self.gridLayout.addWidget(self.lblParent, 1, 0, 1, 1)
        self.cmbOrganisation = COrgComboBox(self.tabMain)
        self.cmbOrganisation.setEnabled(True)
        self.cmbOrganisation.setObjectName(_fromUtf8("cmbOrganisation"))
        self.gridLayout.addWidget(self.cmbOrganisation, 0, 2, 1, 1)
        self.edtDayLimit = QtGui.QLineEdit(self.tabMain)
        self.edtDayLimit.setObjectName(_fromUtf8("edtDayLimit"))
        self.gridLayout.addWidget(self.edtDayLimit, 21, 2, 1, 2)
        self.lblName = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 6, 0, 1, 1)
        self.lblSalaryPercentage = QtGui.QLabel(self.tabMain)
        self.lblSalaryPercentage.setObjectName(_fromUtf8("lblSalaryPercentage"))
        self.gridLayout.addWidget(self.lblSalaryPercentage, 23, 0, 1, 1)
        self.cmbMiacHead = COrgStructureComboBoxOnlyInfisEnabled(self.tabMain)
        self.cmbMiacHead.setEnabled(False)
        self.cmbMiacHead.setObjectName(_fromUtf8("cmbMiacHead"))
        self.gridLayout.addWidget(self.cmbMiacHead, 20, 2, 1, 2)
        self.edtSyncGUID = QtGui.QLineEdit(self.tabMain)
        self.edtSyncGUID.setObjectName(_fromUtf8("edtSyncGUID"))
        self.gridLayout.addWidget(self.edtSyncGUID, 17, 2, 1, 2)
        self.edtAttachCode = QtGui.QLineEdit(self.tabMain)
        self.edtAttachCode.setObjectName(_fromUtf8("edtAttachCode"))
        self.gridLayout.addWidget(self.edtAttachCode, 18, 2, 1, 2)
        self.edtSalaryPercentage = QtGui.QDoubleSpinBox(self.tabMain)
        self.edtSalaryPercentage.setMaximum(100.0)
        self.edtSalaryPercentage.setObjectName(_fromUtf8("edtSalaryPercentage"))
        self.gridLayout.addWidget(self.edtSalaryPercentage, 23, 2, 1, 2)
        self.lblQuota = QtGui.QLabel(self.tabMain)
        self.lblQuota.setObjectName(_fromUtf8("lblQuota"))
        self.gridLayout.addWidget(self.lblQuota, 24, 0, 1, 1)
        self.edtQuota = QtGui.QSpinBox(self.tabMain)
        self.edtQuota.setObjectName(_fromUtf8("edtQuota"))
        self.gridLayout.addWidget(self.edtQuota, 24, 2, 1, 2)
        self.lblMiacCode = QtGui.QLabel(self.tabMain)
        self.lblMiacCode.setObjectName(_fromUtf8("lblMiacCode"))
        self.gridLayout.addWidget(self.lblMiacCode, 5, 0, 1, 1)
        self.edtMiacCode = QtGui.QLineEdit(self.tabMain)
        self.edtMiacCode.setObjectName(_fromUtf8("edtMiacCode"))
        self.gridLayout.addWidget(self.edtMiacCode, 5, 2, 1, 2)
        self.tabWidget.addTab(self.tabMain, _fromUtf8(""))
        self.tabAddress = QtGui.QWidget()
        self.tabAddress.setEnabled(True)
        self.tabAddress.setObjectName(_fromUtf8("tabAddress"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabAddress)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblAddress = CTableView(self.tabAddress)
        self.tblAddress.setEnabled(False)
        self.tblAddress.setSortingEnabled(True)
        self.tblAddress.setObjectName(_fromUtf8("tblAddress"))
        self.gridLayout_2.addWidget(self.tblAddress, 0, 0, 1, 7)
        self.layFilter = QtGui.QHBoxLayout()
        self.layFilter.setContentsMargins(0, -1, 0, -1)
        self.layFilter.setSpacing(3)
        self.layFilter.setObjectName(_fromUtf8("layFilter"))
        self.lblFilterStreet = QtGui.QLabel(self.tabAddress)
        self.lblFilterStreet.setMaximumSize(QtCore.QSize(43, 16777215))
        self.lblFilterStreet.setObjectName(_fromUtf8("lblFilterStreet"))
        self.layFilter.addWidget(self.lblFilterStreet)
        self.cmbFilterAddressStreet = CStreetComboBox(self.tabAddress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressStreet.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressStreet.setSizePolicy(sizePolicy)
        self.cmbFilterAddressStreet.setMaximumSize(QtCore.QSize(237, 16777215))
        self.cmbFilterAddressStreet.setObjectName(_fromUtf8("cmbFilterAddressStreet"))
        self.layFilter.addWidget(self.cmbFilterAddressStreet)
        self.lblFilterHouse = QtGui.QLabel(self.tabAddress)
        self.lblFilterHouse.setMaximumSize(QtCore.QSize(42, 16777215))
        self.lblFilterHouse.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lblFilterHouse.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFilterHouse.setObjectName(_fromUtf8("lblFilterHouse"))
        self.layFilter.addWidget(self.lblFilterHouse)
        self.edtFilterAdressHouse = QtGui.QLineEdit(self.tabAddress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterAdressHouse.sizePolicy().hasHeightForWidth())
        self.edtFilterAdressHouse.setSizePolicy(sizePolicy)
        self.edtFilterAdressHouse.setMaximumSize(QtCore.QSize(68, 16777215))
        self.edtFilterAdressHouse.setObjectName(_fromUtf8("edtFilterAdressHouse"))
        self.layFilter.addWidget(self.edtFilterAdressHouse)
        spacerItem1 = QtGui.QSpacerItem(117, 19, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.layFilter.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.layFilter, 6, 0, 2, 1)
        self.lblFilterScreach = QtGui.QLabel(self.tabAddress)
        self.lblFilterScreach.setObjectName(_fromUtf8("lblFilterScreach"))
        self.gridLayout_2.addWidget(self.lblFilterScreach, 1, 0, 1, 1)
        self.btnAddAddresses = QtGui.QPushButton(self.tabAddress)
        self.btnAddAddresses.setObjectName(_fromUtf8("btnAddAddresses"))
        self.gridLayout_2.addWidget(self.btnAddAddresses, 8, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.tabAddress)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.edtFilterCorp = QtGui.QLineEdit(self.tabAddress)
        self.edtFilterCorp.setObjectName(_fromUtf8("edtFilterCorp"))
        self.horizontalLayout.addWidget(self.edtFilterCorp)
        self.lblFilterFirstKv = QtGui.QLabel(self.tabAddress)
        self.lblFilterFirstKv.setObjectName(_fromUtf8("lblFilterFirstKv"))
        self.horizontalLayout.addWidget(self.lblFilterFirstKv)
        self.edtFilterFirstKv = QtGui.QLineEdit(self.tabAddress)
        self.edtFilterFirstKv.setObjectName(_fromUtf8("edtFilterFirstKv"))
        self.horizontalLayout.addWidget(self.edtFilterFirstKv)
        self.lblFilterLastKv = QtGui.QLabel(self.tabAddress)
        self.lblFilterLastKv.setObjectName(_fromUtf8("lblFilterLastKv"))
        self.horizontalLayout.addWidget(self.lblFilterLastKv)
        self.edtFilterLastKv = QtGui.QLineEdit(self.tabAddress)
        self.edtFilterLastKv.setObjectName(_fromUtf8("edtFilterLastKv"))
        self.horizontalLayout.addWidget(self.edtFilterLastKv)
        self.btnFilterApply = QtGui.QPushButton(self.tabAddress)
        self.btnFilterApply.setObjectName(_fromUtf8("btnFilterApply"))
        self.horizontalLayout.addWidget(self.btnFilterApply)
        self.lblBegKv = QtGui.QLabel(self.tabAddress)
        self.lblBegKv.setText(_fromUtf8(""))
        self.lblBegKv.setObjectName(_fromUtf8("lblBegKv"))
        self.horizontalLayout.addWidget(self.lblBegKv)
        self.gridLayout_2.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        self.tabWidget.addTab(self.tabAddress, _fromUtf8(""))
        self.tabHospitalBeds = QtGui.QWidget()
        self.tabHospitalBeds.setEnabled(True)
        self.tabHospitalBeds.setObjectName(_fromUtf8("tabHospitalBeds"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabHospitalBeds)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tblHospitalBeds = CInDocTableView(self.tabHospitalBeds)
        self.tblHospitalBeds.setEnabled(True)
        self.tblHospitalBeds.setObjectName(_fromUtf8("tblHospitalBeds"))
        self.gridLayout_4.addWidget(self.tblHospitalBeds, 0, 0, 1, 1)
        self.tblInvoluteBeds = CInDocTableView(self.tabHospitalBeds)
        self.tblInvoluteBeds.setEnabled(True)
        self.tblInvoluteBeds.setObjectName(_fromUtf8("tblInvoluteBeds"))
        self.gridLayout_4.addWidget(self.tblInvoluteBeds, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabHospitalBeds, _fromUtf8(""))
        self.tabJobs = QtGui.QWidget()
        self.tabJobs.setObjectName(_fromUtf8("tabJobs"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabJobs)
        self.gridLayout_6.setMargin(4)
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tblJobs = CInDocTableView(self.tabJobs)
        self.tblJobs.setEnabled(True)
        self.tblJobs.setObjectName(_fromUtf8("tblJobs"))
        self.gridLayout_6.addWidget(self.tblJobs, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabJobs, _fromUtf8(""))
        self.tabGaps = QtGui.QWidget()
        self.tabGaps.setObjectName(_fromUtf8("tabGaps"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabGaps)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tblGaps = CInDocTableView(self.tabGaps)
        self.tblGaps.setEnabled(True)
        self.tblGaps.setObjectName(_fromUtf8("tblGaps"))
        self.gridLayout_5.addWidget(self.tblGaps, 1, 0, 1, 1)
        self.chkInheritGaps = QtGui.QCheckBox(self.tabGaps)
        self.chkInheritGaps.setObjectName(_fromUtf8("chkInheritGaps"))
        self.gridLayout_5.addWidget(self.chkInheritGaps, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabGaps, _fromUtf8(""))
        self.tabEventTypes = QtGui.QWidget()
        self.tabEventTypes.setObjectName(_fromUtf8("tabEventTypes"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabEventTypes)
        self.gridLayout_7.setMargin(4)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.chkInheritEventTypes = QtGui.QCheckBox(self.tabEventTypes)
        self.chkInheritEventTypes.setObjectName(_fromUtf8("chkInheritEventTypes"))
        self.gridLayout_7.addWidget(self.chkInheritEventTypes, 0, 0, 1, 1)
        self.tblEventTypes = CInDocTableView(self.tabEventTypes)
        self.tblEventTypes.setEnabled(True)
        self.tblEventTypes.setObjectName(_fromUtf8("tblEventTypes"))
        self.gridLayout_7.addWidget(self.tblEventTypes, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabEventTypes, _fromUtf8(""))
        self.tabActionTypes = QtGui.QWidget()
        self.tabActionTypes.setObjectName(_fromUtf8("tabActionTypes"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabActionTypes)
        self.gridLayout_8.setMargin(4)
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.chkInheritActionTypes = QtGui.QCheckBox(self.tabActionTypes)
        self.chkInheritActionTypes.setObjectName(_fromUtf8("chkInheritActionTypes"))
        self.gridLayout_8.addWidget(self.chkInheritActionTypes, 0, 0, 1, 1)
        self.tblActionTypes = CInDocTableView(self.tabActionTypes)
        self.tblActionTypes.setEnabled(True)
        self.tblActionTypes.setObjectName(_fromUtf8("tblActionTypes"))
        self.gridLayout_8.addWidget(self.tblActionTypes, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabActionTypes, _fromUtf8(""))
        self.tabDisabledAttendance = QtGui.QWidget()
        self.tabDisabledAttendance.setObjectName(_fromUtf8("tabDisabledAttendance"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tabDisabledAttendance)
        self.gridLayout_9.setMargin(4)
        self.gridLayout_9.setSpacing(4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tblDisabledAttendance = CInDocTableView(self.tabDisabledAttendance)
        self.tblDisabledAttendance.setObjectName(_fromUtf8("tblDisabledAttendance"))
        self.gridLayout_9.addWidget(self.tblDisabledAttendance, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabDisabledAttendance, _fromUtf8(""))
        self.tabStocks = QtGui.QWidget()
        self.tabStocks.setObjectName(_fromUtf8("tabStocks"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tabStocks)
        self.gridLayout_10.setMargin(4)
        self.gridLayout_10.setSpacing(4)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.tblStocks = CInDocTableView(self.tabStocks)
        self.tblStocks.setObjectName(_fromUtf8("tblStocks"))
        self.gridLayout_10.addWidget(self.tblStocks, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabStocks, _fromUtf8(""))
        self.tabEquipment = QtGui.QWidget()
        self.tabEquipment.setObjectName(_fromUtf8("tabEquipment"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tabEquipment)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.tblEquipments = CInDocTableView(self.tabEquipment)
        self.tblEquipments.setObjectName(_fromUtf8("tblEquipments"))
        self.gridLayout_11.addWidget(self.tblEquipments, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabEquipment, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.lblBookkeeperCode.setBuddy(self.edtBookkeeperCode)
        self.lblInfisCode.setBuddy(self.edtInfisCode)
        self.lblHeadNurse.setBuddy(self.cmbHeadNurse)
        self.lblInfisTariffCode.setBuddy(self.edtInfisTariffCode)
        self.lblChief.setBuddy(self.cmbChief)
        self.lblNet.setBuddy(self.cmbNet)
        self.lblType.setBuddy(self.cmbType)
        self.lblCode.setBuddy(self.edtCode)
        self.lblOrganisation.setBuddy(self.cmbOrganisation)
        self.lblInfisDepTypeCode.setBuddy(self.edtInfisDepTypeCode)
        self.lblAddress.setBuddy(self.edtAddress)
        self.lblInfisInternalCode.setBuddy(self.edtInfisInternalCode)
        self.lblIsArea.setBuddy(self.cmbIsArea)
        self.lblParent.setBuddy(self.cmbParent)
        self.lblName.setBuddy(self.edtName)

        self.retranslateUi(ItemEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ItemEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ItemEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ItemEditorDialog)
        ItemEditorDialog.setTabOrder(self.tabWidget, self.cmbOrganisation)
        ItemEditorDialog.setTabOrder(self.cmbOrganisation, self.btnSelectOrganisation)
        ItemEditorDialog.setTabOrder(self.btnSelectOrganisation, self.cmbParent)
        ItemEditorDialog.setTabOrder(self.cmbParent, self.edtCode)
        ItemEditorDialog.setTabOrder(self.edtCode, self.edtBookkeeperCode)
        ItemEditorDialog.setTabOrder(self.edtBookkeeperCode, self.edtName)
        ItemEditorDialog.setTabOrder(self.edtName, self.edtAddress)
        ItemEditorDialog.setTabOrder(self.edtAddress, self.cmbType)
        ItemEditorDialog.setTabOrder(self.cmbType, self.cmbNet)
        ItemEditorDialog.setTabOrder(self.cmbNet, self.cmbChief)
        ItemEditorDialog.setTabOrder(self.cmbChief, self.cmbHeadNurse)
        ItemEditorDialog.setTabOrder(self.cmbHeadNurse, self.edtInfisCode)
        ItemEditorDialog.setTabOrder(self.edtInfisCode, self.edtInfisInternalCode)
        ItemEditorDialog.setTabOrder(self.edtInfisInternalCode, self.edtInfisDepTypeCode)
        ItemEditorDialog.setTabOrder(self.edtInfisDepTypeCode, self.edtInfisTariffCode)
        ItemEditorDialog.setTabOrder(self.edtInfisTariffCode, self.cmbIsArea)
        ItemEditorDialog.setTabOrder(self.cmbIsArea, self.chkHasHospitalBeds)
        ItemEditorDialog.setTabOrder(self.chkHasHospitalBeds, self.chkHasStocks)
        ItemEditorDialog.setTabOrder(self.chkHasStocks, self.tblAddress)
        ItemEditorDialog.setTabOrder(self.tblAddress, self.tblHospitalBeds)
        ItemEditorDialog.setTabOrder(self.tblHospitalBeds, self.tblJobs)
        ItemEditorDialog.setTabOrder(self.tblJobs, self.chkInheritGaps)
        ItemEditorDialog.setTabOrder(self.chkInheritGaps, self.tblGaps)
        ItemEditorDialog.setTabOrder(self.tblGaps, self.chkInheritEventTypes)
        ItemEditorDialog.setTabOrder(self.chkInheritEventTypes, self.tblEventTypes)
        ItemEditorDialog.setTabOrder(self.tblEventTypes, self.chkInheritActionTypes)
        ItemEditorDialog.setTabOrder(self.chkInheritActionTypes, self.tblActionTypes)
        ItemEditorDialog.setTabOrder(self.tblActionTypes, self.tblDisabledAttendance)
        ItemEditorDialog.setTabOrder(self.tblDisabledAttendance, self.tblStocks)
        ItemEditorDialog.setTabOrder(self.tblStocks, self.buttonBox)
        ItemEditorDialog.setTabOrder(self.buttonBox, self.tblEquipments)

    def retranslateUi(self, ItemEditorDialog):
        ItemEditorDialog.setWindowTitle(_translate("ItemEditorDialog", "ChangeMe!", None))
        self.lblAttachCode.setText(_translate("ItemEditorDialog", "Код прикрепления", None))
        self.lblMiacHead.setText(_translate("ItemEditorDialog", "Участок относится к", None))
        self.btnSelectOrganisation.setText(_translate("ItemEditorDialog", "...", None))
        self.chkAvailableForExternal.setText(_translate("ItemEditorDialog", "Информация о подразделении доступна для внешних систем", None))
        self.lblBookkeeperCode.setText(_translate("ItemEditorDialog", "Код для &бухгалтерии", None))
        self.chkHasHospitalBeds.setText(_translate("ItemEditorDialog", "Имеет койки", None))
        self.edtInfisDepTypeCode.setToolTip(_translate("ItemEditorDialog", "Экспорт в ИНФИС - файл data.dbf, поле PROFTYPE", None))
        self.lblInfisCode.setText(_translate("ItemEditorDialog", "Код отделения по &ИнФИС", None))
        self.chkHasStocks.setText(_translate("ItemEditorDialog", "Имеет склад", None))
        self.lblHeadNurse.setText(_translate("ItemEditorDialog", "Старшая &медсестра", None))
        self.label.setText(_translate("ItemEditorDialog", "Код склада", None))
        self.lblInfisTariffCode.setToolTip(_translate("ItemEditorDialog", "HSOBJECT", None))
        self.lblInfisTariffCode.setText(_translate("ItemEditorDialog", "&Селектор тарифа для ИнФИС", None))
        self.lblChief.setText(_translate("ItemEditorDialog", "&Зав.отделением", None))
        self.lblNet.setText(_translate("ItemEditorDialog", "&Сеть", None))
        self.chkVisibleInDR.setToolTip(_translate("ItemEditorDialog", "Подразделение будет отображаться в \"Виста-МЕД Web-service\".", None))
        self.chkVisibleInDR.setText(_translate("ItemEditorDialog", "Видимость в DoctorRoom", None))
        self.cmbHeadNurse.setWhatsThis(_translate("ItemEditorDialog", "врач отвечающий за осмотр (терапевт)", None))
        self.cmbChief.setWhatsThis(_translate("ItemEditorDialog", "врач отвечающий за осмотр (терапевт)", None))
        self.lblType.setText(_translate("ItemEditorDialog", "&Тип", None))
        self.lblSyncGUID.setText(_translate("ItemEditorDialog", "Код синхронизации", None))
        self.lblCode.setText(_translate("ItemEditorDialog", "&Код", None))
        self.lblOrganisation.setText(_translate("ItemEditorDialog", "&ЛПУ", None))
        self.lblInfisDepTypeCode.setText(_translate("ItemEditorDialog", "Код &типа отделения по ИнФИС", None))
        self.chkHasDS.setText(_translate("ItemEditorDialog", "Имеет дневной стационар", None))
        self.lblAddress.setText(_translate("ItemEditorDialog", "&Адрес", None))
        self.lblInfisInternalCode.setText(_translate("ItemEditorDialog", "\"Внутренний\" &код по ИнФИС", None))
        self.edtInfisTariffCode.setToolTip(_translate("ItemEditorDialog", "Экспорт в ИНФИС - файл data.dbf, поле HSOBJECT", None))
        self.edtInfisInternalCode.setToolTip(_translate("ItemEditorDialog", "Экспорт в ИНФИС - файл data.dbf, поле DEPART", None))
        self.lblDayLimit.setText(_translate("ItemEditorDialog", "Лимит мест для госпитализации", None))
        self.edtInfisCode.setToolTip(_translate("ItemEditorDialog", "Экспорт в ИНФИС - файл data.dbf, поле RECIEVER", None))
        self.lblIsArea.setText(_translate("ItemEditorDialog", "&Участок", None))
        self.edtBookkeeperCode.setToolTip(_translate("ItemEditorDialog", "Код для связи с ИС БУХУЧЕТА ЛПУ", None))
        self.lblParent.setText(_translate("ItemEditorDialog", "&Вышестоящее подразделение", None))
        self.lblName.setText(_translate("ItemEditorDialog", "&Наименование", None))
        self.lblSalaryPercentage.setText(_translate("ItemEditorDialog", "Процент зачисления з/п", None))
        self.edtSalaryPercentage.setToolTip(_translate("ItemEditorDialog", "<html><head/><body><p>Процент начисления з/п сотруднику. </p><p>При отсутсвии процента у подразделения оставить значение процента равным нулю.</p></body></html>", None))
        self.lblQuota.setText(_translate("ItemEditorDialog", "Квота для внешних систем", None))
        self.lblMiacCode.setText(_translate("ItemEditorDialog", "Код МИАЦ", None))
        self.edtMiacCode.setToolTip(_translate("ItemEditorDialog", "экспорт счетов в ЕИС- поля ID_LPU_P и ID_LPU_P_C", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("ItemEditorDialog", "Основная информация", None))
        self.lblFilterStreet.setText(_translate("ItemEditorDialog", "Улица:", None))
        self.lblFilterHouse.setText(_translate("ItemEditorDialog", "Дом:", None))
        self.lblFilterScreach.setText(_translate("ItemEditorDialog", "Поиск:", None))
        self.btnAddAddresses.setText(_translate("ItemEditorDialog", "Добавить адреса", None))
        self.label_2.setText(_translate("ItemEditorDialog", "Корпус:", None))
        self.lblFilterFirstKv.setText(_translate("ItemEditorDialog", "Первая кв.:", None))
        self.lblFilterLastKv.setText(_translate("ItemEditorDialog", "Последняя кв.:", None))
        self.btnFilterApply.setText(_translate("ItemEditorDialog", "Применить фильтр", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAddress), _translate("ItemEditorDialog", "Зона обслуживания", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHospitalBeds), _translate("ItemEditorDialog", "Койки", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabJobs), _translate("ItemEditorDialog", "Работы", None))
        self.chkInheritGaps.setText(_translate("ItemEditorDialog", "Наследует перерывы", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGaps), _translate("ItemEditorDialog", "Перерывы", None))
        self.chkInheritEventTypes.setText(_translate("ItemEditorDialog", "Наследует типы событий", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEventTypes), _translate("ItemEditorDialog", "Типы событий", None))
        self.chkInheritActionTypes.setText(_translate("ItemEditorDialog", "Наследует типы действий", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabActionTypes), _translate("ItemEditorDialog", "Типы действий", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDisabledAttendance), _translate("ItemEditorDialog", "Запрет обслуживания", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStocks), _translate("ItemEditorDialog", "Склад", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEquipment), _translate("ItemEditorDialog", "Оборудование", None))

from KLADR.kladrComboxes import CStreetComboBox
from Orgs.OrgComboBox import COrgComboBox
from Orgs.OrgStructComboBoxOnlyInfis import COrgStructureComboBoxOnlyInfisEnabled
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DbComboBox import CDbComboBox
from library.Enum import CEnumComboBox
from library.InDocTable import CInDocTableView
from library.TableView import CTableView
from library.crbcombobox import CRBComboBox
