# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RBServiceEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ItemEditorDialog(object):
    def setupUi(self, ItemEditorDialog):
        ItemEditorDialog.setObjectName(_fromUtf8("ItemEditorDialog"))
        ItemEditorDialog.resize(619, 481)
        ItemEditorDialog.setSizeGripEnabled(True)
        self.gridLayout_2 = QtGui.QGridLayout(ItemEditorDialog)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.edtCode = QtGui.QLineEdit(ItemEditorDialog)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout_2.addWidget(self.edtCode, 1, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ItemEditorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 4, 0, 1, 2)
        self.cmbServiceGroup = CRBComboBox(ItemEditorDialog)
        self.cmbServiceGroup.setObjectName(_fromUtf8("cmbServiceGroup"))
        self.gridLayout_2.addWidget(self.cmbServiceGroup, 0, 1, 1, 1)
        self.lblCode = QtGui.QLabel(ItemEditorDialog)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout_2.addWidget(self.lblCode, 1, 0, 1, 1)
        self.edtName = QtGui.QTextEdit(ItemEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtName.sizePolicy().hasHeightForWidth())
        self.edtName.setSizePolicy(sizePolicy)
        self.edtName.setSizeIncrement(QtCore.QSize(0, 1))
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout_2.addWidget(self.edtName, 2, 1, 1, 1)
        self.lblName = QtGui.QLabel(ItemEditorDialog)
        self.lblName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout_2.addWidget(self.lblName, 2, 0, 1, 1)
        self.lblServiceGroup = QtGui.QLabel(ItemEditorDialog)
        self.lblServiceGroup.setObjectName(_fromUtf8("lblServiceGroup"))
        self.gridLayout_2.addWidget(self.lblServiceGroup, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(ItemEditorDialog)
        self.tabWidget.setSizeIncrement(QtCore.QSize(0, 2))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabInfo = QtGui.QWidget()
        self.tabInfo.setObjectName(_fromUtf8("tabInfo"))
        self.gridLayout = QtGui.QGridLayout(self.tabInfo)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edtUetAdultDoctor = QtGui.QDoubleSpinBox(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtUetAdultDoctor.sizePolicy().hasHeightForWidth())
        self.edtUetAdultDoctor.setSizePolicy(sizePolicy)
        self.edtUetAdultDoctor.setDecimals(3)
        self.edtUetAdultDoctor.setObjectName(_fromUtf8("edtUetAdultDoctor"))
        self.gridLayout.addWidget(self.edtUetAdultDoctor, 10, 1, 1, 1)
        self.edtSuperviseComplexityFactor = QtGui.QDoubleSpinBox(self.tabInfo)
        self.edtSuperviseComplexityFactor.setDecimals(2)
        self.edtSuperviseComplexityFactor.setMaximum(9999.99)
        self.edtSuperviseComplexityFactor.setObjectName(_fromUtf8("edtSuperviseComplexityFactor"))
        self.gridLayout.addWidget(self.edtSuperviseComplexityFactor, 8, 1, 1, 1)
        self.edtQualityLevel = QtGui.QDoubleSpinBox(self.tabInfo)
        self.edtQualityLevel.setDecimals(3)
        self.edtQualityLevel.setMaximum(999999.999)
        self.edtQualityLevel.setObjectName(_fromUtf8("edtQualityLevel"))
        self.gridLayout.addWidget(self.edtQualityLevel, 7, 1, 1, 1)
        self.lblQualityLevel = QtGui.QLabel(self.tabInfo)
        self.lblQualityLevel.setObjectName(_fromUtf8("lblQualityLevel"))
        self.gridLayout.addWidget(self.lblQualityLevel, 7, 0, 1, 1)
        self.lblUetAvarageMedWorker = QtGui.QLabel(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUetAvarageMedWorker.sizePolicy().hasHeightForWidth())
        self.lblUetAvarageMedWorker.setSizePolicy(sizePolicy)
        self.lblUetAvarageMedWorker.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblUetAvarageMedWorker.setWordWrap(True)
        self.lblUetAvarageMedWorker.setObjectName(_fromUtf8("lblUetAvarageMedWorker"))
        self.gridLayout.addWidget(self.lblUetAvarageMedWorker, 9, 2, 1, 3)
        self.lblUetDoctor = QtGui.QLabel(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUetDoctor.sizePolicy().hasHeightForWidth())
        self.lblUetDoctor.setSizePolicy(sizePolicy)
        self.lblUetDoctor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblUetDoctor.setObjectName(_fromUtf8("lblUetDoctor"))
        self.gridLayout.addWidget(self.lblUetDoctor, 9, 0, 1, 2)
        self.edtUetChildAvarageMedWorker = QtGui.QDoubleSpinBox(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtUetChildAvarageMedWorker.sizePolicy().hasHeightForWidth())
        self.edtUetChildAvarageMedWorker.setSizePolicy(sizePolicy)
        self.edtUetChildAvarageMedWorker.setDecimals(3)
        self.edtUetChildAvarageMedWorker.setObjectName(_fromUtf8("edtUetChildAvarageMedWorker"))
        self.gridLayout.addWidget(self.edtUetChildAvarageMedWorker, 11, 3, 1, 1)
        self.cmbLicense = QtGui.QComboBox(self.tabInfo)
        self.cmbLicense.setObjectName(_fromUtf8("cmbLicense"))
        self.cmbLicense.addItem(_fromUtf8(""))
        self.cmbLicense.addItem(_fromUtf8(""))
        self.cmbLicense.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbLicense, 5, 1, 1, 4)
        self.lblUetAdultAvarageMedWorker = QtGui.QLabel(self.tabInfo)
        self.lblUetAdultAvarageMedWorker.setObjectName(_fromUtf8("lblUetAdultAvarageMedWorker"))
        self.gridLayout.addWidget(self.lblUetAdultAvarageMedWorker, 10, 2, 1, 1)
        self.lblBegDate = QtGui.QLabel(self.tabInfo)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.edtBegDate = QtGui.QDateEdit(self.tabInfo)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(131, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.lblEndDate = QtGui.QLabel(self.tabInfo)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.edtEndDate = QtGui.QDateEdit(self.tabInfo)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(131, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 1)
        self.chkeisLegacy = QtGui.QCheckBox(self.tabInfo)
        self.chkeisLegacy.setObjectName(_fromUtf8("chkeisLegacy"))
        self.gridLayout.addWidget(self.chkeisLegacy, 3, 1, 1, 4)
        self.lblLicense = QtGui.QLabel(self.tabInfo)
        self.lblLicense.setObjectName(_fromUtf8("lblLicense"))
        self.gridLayout.addWidget(self.lblLicense, 5, 0, 1, 1)
        self.lblInfis = QtGui.QLabel(self.tabInfo)
        self.lblInfis.setObjectName(_fromUtf8("lblInfis"))
        self.gridLayout.addWidget(self.lblInfis, 6, 0, 1, 1)
        self.edtInfis = QtGui.QLineEdit(self.tabInfo)
        self.edtInfis.setObjectName(_fromUtf8("edtInfis"))
        self.gridLayout.addWidget(self.edtInfis, 6, 1, 1, 4)
        spacerItem2 = QtGui.QSpacerItem(20, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 13, 0, 1, 1)
        self.lblUetAdultDoctor = QtGui.QLabel(self.tabInfo)
        self.lblUetAdultDoctor.setObjectName(_fromUtf8("lblUetAdultDoctor"))
        self.gridLayout.addWidget(self.lblUetAdultDoctor, 10, 0, 1, 1)
        self.lblUetChildDoctor = QtGui.QLabel(self.tabInfo)
        self.lblUetChildDoctor.setObjectName(_fromUtf8("lblUetChildDoctor"))
        self.gridLayout.addWidget(self.lblUetChildDoctor, 11, 0, 1, 1)
        self.lblUetChildAvarageMedWorker = QtGui.QLabel(self.tabInfo)
        self.lblUetChildAvarageMedWorker.setObjectName(_fromUtf8("lblUetChildAvarageMedWorker"))
        self.gridLayout.addWidget(self.lblUetChildAvarageMedWorker, 11, 2, 1, 1)
        self.edtUetChildDoctor = QtGui.QDoubleSpinBox(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtUetChildDoctor.sizePolicy().hasHeightForWidth())
        self.edtUetChildDoctor.setSizePolicy(sizePolicy)
        self.edtUetChildDoctor.setDecimals(3)
        self.edtUetChildDoctor.setObjectName(_fromUtf8("edtUetChildDoctor"))
        self.gridLayout.addWidget(self.edtUetChildDoctor, 11, 1, 1, 1)
        self.edtUetAdultAvarageMedWorker = QtGui.QDoubleSpinBox(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtUetAdultAvarageMedWorker.sizePolicy().hasHeightForWidth())
        self.edtUetAdultAvarageMedWorker.setSizePolicy(sizePolicy)
        self.edtUetAdultAvarageMedWorker.setDecimals(3)
        self.edtUetAdultAvarageMedWorker.setObjectName(_fromUtf8("edtUetAdultAvarageMedWorker"))
        self.gridLayout.addWidget(self.edtUetAdultAvarageMedWorker, 10, 3, 1, 1)
        self.lblSuperviseComplexityFactor = QtGui.QLabel(self.tabInfo)
        self.lblSuperviseComplexityFactor.setObjectName(_fromUtf8("lblSuperviseComplexityFactor"))
        self.gridLayout.addWidget(self.lblSuperviseComplexityFactor, 8, 0, 1, 1)
        self.chkNomenclatureLegacy = QtGui.QCheckBox(self.tabInfo)
        self.chkNomenclatureLegacy.setObjectName(_fromUtf8("chkNomenclatureLegacy"))
        self.gridLayout.addWidget(self.chkNomenclatureLegacy, 4, 1, 1, 4)
        self.lblServiceCategory = QtGui.QLabel(self.tabInfo)
        self.lblServiceCategory.setObjectName(_fromUtf8("lblServiceCategory"))
        self.gridLayout.addWidget(self.lblServiceCategory, 12, 0, 1, 1)
        self.cmbServiceCategory = CRBComboBox(self.tabInfo)
        self.cmbServiceCategory.setObjectName(_fromUtf8("cmbServiceCategory"))
        self.gridLayout.addWidget(self.cmbServiceCategory, 12, 1, 1, 4)
        self.tabWidget.addTab(self.tabInfo, _fromUtf8(""))
        self.tabContent = QtGui.QWidget()
        self.tabContent.setObjectName(_fromUtf8("tabContent"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabContent)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tblServices = CInDocTableView(self.tabContent)
        self.tblServices.setObjectName(_fromUtf8("tblServices"))
        self.verticalLayout.addWidget(self.tblServices)
        self.tabWidget.addTab(self.tabContent, _fromUtf8(""))
        self.tabMedicalAidProfiles = QtGui.QWidget()
        self.tabMedicalAidProfiles.setObjectName(_fromUtf8("tabMedicalAidProfiles"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabMedicalAidProfiles)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblProfiles = QtGui.QLabel(self.tabMedicalAidProfiles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProfiles.sizePolicy().hasHeightForWidth())
        self.lblProfiles.setSizePolicy(sizePolicy)
        self.lblProfiles.setObjectName(_fromUtf8("lblProfiles"))
        self.gridLayout_3.addWidget(self.lblProfiles, 0, 0, 1, 1)
        self.cmbMedicalAidProfile = CRBComboBox(self.tabMedicalAidProfiles)
        self.cmbMedicalAidProfile.setObjectName(_fromUtf8("cmbMedicalAidProfile"))
        self.gridLayout_3.addWidget(self.cmbMedicalAidProfile, 0, 1, 1, 1)
        self.tblMedicalAidProfiles = CInDocTableView(self.tabMedicalAidProfiles)
        self.tblMedicalAidProfiles.setObjectName(_fromUtf8("tblMedicalAidProfiles"))
        self.gridLayout_3.addWidget(self.tblMedicalAidProfiles, 3, 0, 1, 2)
        self.lblMedicalAidProfile = QtGui.QLabel(self.tabMedicalAidProfiles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMedicalAidProfile.sizePolicy().hasHeightForWidth())
        self.lblMedicalAidProfile.setSizePolicy(sizePolicy)
        self.lblMedicalAidProfile.setObjectName(_fromUtf8("lblMedicalAidProfile"))
        self.gridLayout_3.addWidget(self.lblMedicalAidProfile, 2, 0, 1, 1)
        self.cmbMedicalAidType = CRBComboBox(self.tabMedicalAidProfiles)
        self.cmbMedicalAidType.setObjectName(_fromUtf8("cmbMedicalAidType"))
        self.gridLayout_3.addWidget(self.cmbMedicalAidType, 2, 1, 1, 1)
        self.cmbMedicalAidKind = CRBComboBox(self.tabMedicalAidProfiles)
        self.cmbMedicalAidKind.setObjectName(_fromUtf8("cmbMedicalAidKind"))
        self.gridLayout_3.addWidget(self.cmbMedicalAidKind, 1, 1, 1, 1)
        self.lblMedicalAidKind = QtGui.QLabel(self.tabMedicalAidProfiles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMedicalAidKind.sizePolicy().hasHeightForWidth())
        self.lblMedicalAidKind.setSizePolicy(sizePolicy)
        self.lblMedicalAidKind.setObjectName(_fromUtf8("lblMedicalAidKind"))
        self.gridLayout_3.addWidget(self.lblMedicalAidKind, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabMedicalAidProfiles, _fromUtf8(""))
        self.tabPurpose = QtGui.QWidget()
        self.tabPurpose.setObjectName(_fromUtf8("tabPurpose"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabPurpose)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.tabPurpose)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.tblGoals = CInDocTableView(self.tabPurpose)
        self.tblGoals.setObjectName(_fromUtf8("tblGoals"))
        self.verticalLayout_2.addWidget(self.tblGoals)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.cmbCaseCast = CRBComboBox(self.tabPurpose)
        self.cmbCaseCast.setMinimumSize(QtCore.QSize(448, 0))
        self.cmbCaseCast.setObjectName(_fromUtf8("cmbCaseCast"))
        self.gridLayout_5.addWidget(self.cmbCaseCast, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.tabPurpose)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.tabWidget.addTab(self.tabPurpose, _fromUtf8(""))
        self.tabMKB = QtGui.QWidget()
        self.tabMKB.setObjectName(_fromUtf8("tabMKB"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabMKB)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tblMKB = CInDocTableView(self.tabMKB)
        self.tblMKB.setObjectName(_fromUtf8("tblMKB"))
        self.verticalLayout_3.addWidget(self.tblMKB)
        self.tabWidget.addTab(self.tabMKB, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 3, 0, 1, 2)
        self.lblCode.setBuddy(self.edtCode)
        self.lblName.setBuddy(self.edtName)
        self.lblServiceGroup.setBuddy(self.cmbServiceGroup)
        self.lblQualityLevel.setBuddy(self.edtQualityLevel)
        self.lblUetAdultAvarageMedWorker.setBuddy(self.edtUetAdultAvarageMedWorker)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblLicense.setBuddy(self.cmbLicense)
        self.lblInfis.setBuddy(self.edtInfis)
        self.lblUetAdultDoctor.setBuddy(self.edtUetAdultDoctor)
        self.lblUetChildDoctor.setBuddy(self.edtUetChildDoctor)
        self.lblUetChildAvarageMedWorker.setBuddy(self.edtUetChildAvarageMedWorker)
        self.lblSuperviseComplexityFactor.setBuddy(self.edtSuperviseComplexityFactor)
        self.lblProfiles.setBuddy(self.cmbMedicalAidProfile)
        self.lblMedicalAidProfile.setBuddy(self.cmbMedicalAidType)
        self.lblMedicalAidKind.setBuddy(self.cmbMedicalAidKind)

        self.retranslateUi(ItemEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ItemEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ItemEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ItemEditorDialog)
        ItemEditorDialog.setTabOrder(self.cmbServiceGroup, self.edtCode)
        ItemEditorDialog.setTabOrder(self.edtCode, self.edtName)
        ItemEditorDialog.setTabOrder(self.edtName, self.tabWidget)
        ItemEditorDialog.setTabOrder(self.tabWidget, self.edtBegDate)
        ItemEditorDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ItemEditorDialog.setTabOrder(self.edtEndDate, self.chkeisLegacy)
        ItemEditorDialog.setTabOrder(self.chkeisLegacy, self.cmbLicense)
        ItemEditorDialog.setTabOrder(self.cmbLicense, self.edtInfis)
        ItemEditorDialog.setTabOrder(self.edtInfis, self.edtQualityLevel)
        ItemEditorDialog.setTabOrder(self.edtQualityLevel, self.edtSuperviseComplexityFactor)
        ItemEditorDialog.setTabOrder(self.edtSuperviseComplexityFactor, self.edtUetAdultDoctor)
        ItemEditorDialog.setTabOrder(self.edtUetAdultDoctor, self.edtUetChildDoctor)
        ItemEditorDialog.setTabOrder(self.edtUetChildDoctor, self.edtUetAdultAvarageMedWorker)
        ItemEditorDialog.setTabOrder(self.edtUetAdultAvarageMedWorker, self.edtUetChildAvarageMedWorker)
        ItemEditorDialog.setTabOrder(self.edtUetChildAvarageMedWorker, self.tblServices)
        ItemEditorDialog.setTabOrder(self.tblServices, self.cmbMedicalAidProfile)
        ItemEditorDialog.setTabOrder(self.cmbMedicalAidProfile, self.cmbMedicalAidKind)
        ItemEditorDialog.setTabOrder(self.cmbMedicalAidKind, self.cmbMedicalAidType)
        ItemEditorDialog.setTabOrder(self.cmbMedicalAidType, self.tblMedicalAidProfiles)
        ItemEditorDialog.setTabOrder(self.tblMedicalAidProfiles, self.buttonBox)

    def retranslateUi(self, ItemEditorDialog):
        ItemEditorDialog.setWindowTitle(_translate("ItemEditorDialog", "ChangeMe!", None))
        self.lblCode.setText(_translate("ItemEditorDialog", "&Код", None))
        self.lblName.setText(_translate("ItemEditorDialog", "&Наименование", None))
        self.lblServiceGroup.setText(_translate("ItemEditorDialog", "&Группа", None))
        self.lblQualityLevel.setText(_translate("ItemEditorDialog", "Уровень качества лечения", None))
        self.lblUetAvarageMedWorker.setText(_translate("ItemEditorDialog", "УЕТ для среднего медицинского персонала", None))
        self.lblUetDoctor.setText(_translate("ItemEditorDialog", "УЕТ для врача", None))
        self.cmbLicense.setItemText(0, _translate("ItemEditorDialog", "не требуется", None))
        self.cmbLicense.setItemText(1, _translate("ItemEditorDialog", "требуется лицензия", None))
        self.cmbLicense.setItemText(2, _translate("ItemEditorDialog", "требуется персональный сертификат", None))
        self.lblUetAdultAvarageMedWorker.setText(_translate("ItemEditorDialog", "Взрослый", None))
        self.lblBegDate.setText(_translate("ItemEditorDialog", "Начальная дата", None))
        self.lblEndDate.setText(_translate("ItemEditorDialog", "Конечная дата", None))
        self.chkeisLegacy.setText(_translate("ItemEditorDialog", "&Унаследовано из ЕИС", None))
        self.lblLicense.setText(_translate("ItemEditorDialog", "&Лицензирование", None))
        self.lblInfis.setText(_translate("ItemEditorDialog", "Код &ИНФИС", None))
        self.lblUetAdultDoctor.setText(_translate("ItemEditorDialog", "Взрослый", None))
        self.lblUetChildDoctor.setText(_translate("ItemEditorDialog", "Детский", None))
        self.lblUetChildAvarageMedWorker.setText(_translate("ItemEditorDialog", "Детский", None))
        self.lblSuperviseComplexityFactor.setText(_translate("ItemEditorDialog", "Коэффициент сложности курации", None))
        self.chkNomenclatureLegacy.setText(_translate("ItemEditorDialog", "&Унаследовано из номенклатуры Минздрава", None))
        self.lblServiceCategory.setText(_translate("ItemEditorDialog", "Категория", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInfo), _translate("ItemEditorDialog", "Основная информация", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabContent), _translate("ItemEditorDialog", "Состав", None))
        self.lblProfiles.setText(_translate("ItemEditorDialog", "Профиль по умолчанию", None))
        self.lblMedicalAidProfile.setText(_translate("ItemEditorDialog", "Тип по умолчанию", None))
        self.lblMedicalAidKind.setText(_translate("ItemEditorDialog", "Вид по умолчанию", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMedicalAidProfiles), _translate("ItemEditorDialog", "Профили, виды и типы помощи", None))
        self.label_2.setText(_translate("ItemEditorDialog", "Цели случая лечения", None))
        self.label.setText(_translate("ItemEditorDialog", "Типы случая лечения", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPurpose), _translate("ItemEditorDialog", "Типы и цели случая лечения", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMKB), _translate("ItemEditorDialog", "МКБ", None))

from library.InDocTable import CInDocTableView
from library.crbcombobox import CRBComboBox
