# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\RefBooks\RBMKBMorphologyEditor.ui'
#
# Created: Fri Jun 15 12:17:19 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MKBMorphologyEditor(object):
    def setupUi(self, MKBMorphologyEditor):
        MKBMorphologyEditor.setObjectName(_fromUtf8("MKBMorphologyEditor"))
        MKBMorphologyEditor.resize(336, 168)
        MKBMorphologyEditor.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(MKBMorphologyEditor)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblCode = QtGui.QLabel(MKBMorphologyEditor)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout.addWidget(self.lblCode, 0, 0, 1, 1)
        self.edtCode = QtGui.QLineEdit(MKBMorphologyEditor)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout.addWidget(self.edtCode, 0, 1, 1, 2)
        self.lblName = QtGui.QLabel(MKBMorphologyEditor)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 1, 0, 1, 1)
        self.edtName = QtGui.QLineEdit(MKBMorphologyEditor)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 1, 1, 1, 2)
        self.lblGroup = QtGui.QLabel(MKBMorphologyEditor)
        self.lblGroup.setObjectName(_fromUtf8("lblGroup"))
        self.gridLayout.addWidget(self.lblGroup, 4, 0, 1, 1)
        self.lblDiagRange1 = QtGui.QLabel(MKBMorphologyEditor)
        self.lblDiagRange1.setObjectName(_fromUtf8("lblDiagRange1"))
        self.gridLayout.addWidget(self.lblDiagRange1, 6, 0, 1, 1)
        self.frmDiagRange2 = QtGui.QFrame(MKBMorphologyEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmDiagRange2.sizePolicy().hasHeightForWidth())
        self.frmDiagRange2.setSizePolicy(sizePolicy)
        self.frmDiagRange2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmDiagRange2.setFrameShadow(QtGui.QFrame.Plain)
        self.frmDiagRange2.setLineWidth(0)
        self.frmDiagRange2.setObjectName(_fromUtf8("frmDiagRange2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frmDiagRange2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblDiagRangeFrom2 = QtGui.QLabel(self.frmDiagRange2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDiagRangeFrom2.sizePolicy().hasHeightForWidth())
        self.lblDiagRangeFrom2.setSizePolicy(sizePolicy)
        self.lblDiagRangeFrom2.setObjectName(_fromUtf8("lblDiagRangeFrom2"))
        self.gridLayout_3.addWidget(self.lblDiagRangeFrom2, 0, 0, 1, 1)
        self.cmbDiagRangeFrom2 = CICDCodeEditEx(self.frmDiagRange2)
        self.cmbDiagRangeFrom2.setObjectName(_fromUtf8("cmbDiagRangeFrom2"))
        self.gridLayout_3.addWidget(self.cmbDiagRangeFrom2, 0, 1, 1, 1)
        self.lblDiagRangeTo2 = QtGui.QLabel(self.frmDiagRange2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDiagRangeTo2.sizePolicy().hasHeightForWidth())
        self.lblDiagRangeTo2.setSizePolicy(sizePolicy)
        self.lblDiagRangeTo2.setObjectName(_fromUtf8("lblDiagRangeTo2"))
        self.gridLayout_3.addWidget(self.lblDiagRangeTo2, 0, 2, 1, 1)
        self.cmbDiagRangeTo2 = CICDCodeEditEx(self.frmDiagRange2)
        self.cmbDiagRangeTo2.setObjectName(_fromUtf8("cmbDiagRangeTo2"))
        self.gridLayout_3.addWidget(self.cmbDiagRangeTo2, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.frmDiagRange2, 8, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(MKBMorphologyEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 10, 0, 1, 3)
        self.lblDiagRange2 = QtGui.QLabel(MKBMorphologyEditor)
        self.lblDiagRange2.setObjectName(_fromUtf8("lblDiagRange2"))
        self.gridLayout.addWidget(self.lblDiagRange2, 8, 0, 1, 1)
        self.cmbGroup = CRBComboBox(MKBMorphologyEditor)
        self.cmbGroup.setObjectName(_fromUtf8("cmbGroup"))
        self.gridLayout.addWidget(self.cmbGroup, 4, 1, 1, 2)
        self.frmDiagRange1 = QtGui.QFrame(MKBMorphologyEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmDiagRange1.sizePolicy().hasHeightForWidth())
        self.frmDiagRange1.setSizePolicy(sizePolicy)
        self.frmDiagRange1.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmDiagRange1.setFrameShadow(QtGui.QFrame.Plain)
        self.frmDiagRange1.setLineWidth(0)
        self.frmDiagRange1.setObjectName(_fromUtf8("frmDiagRange1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frmDiagRange1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblDiagRangeFrom1 = QtGui.QLabel(self.frmDiagRange1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDiagRangeFrom1.sizePolicy().hasHeightForWidth())
        self.lblDiagRangeFrom1.setSizePolicy(sizePolicy)
        self.lblDiagRangeFrom1.setObjectName(_fromUtf8("lblDiagRangeFrom1"))
        self.gridLayout_2.addWidget(self.lblDiagRangeFrom1, 0, 0, 1, 1)
        self.cmbDiagRangeFrom1 = CICDCodeEditEx(self.frmDiagRange1)
        self.cmbDiagRangeFrom1.setObjectName(_fromUtf8("cmbDiagRangeFrom1"))
        self.gridLayout_2.addWidget(self.cmbDiagRangeFrom1, 0, 1, 1, 1)
        self.lblDiagRangeTo1 = QtGui.QLabel(self.frmDiagRange1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDiagRangeTo1.sizePolicy().hasHeightForWidth())
        self.lblDiagRangeTo1.setSizePolicy(sizePolicy)
        self.lblDiagRangeTo1.setObjectName(_fromUtf8("lblDiagRangeTo1"))
        self.gridLayout_2.addWidget(self.lblDiagRangeTo1, 0, 2, 1, 1)
        self.cmbDiagRangeTo1 = CICDCodeEditEx(self.frmDiagRange1)
        self.cmbDiagRangeTo1.setObjectName(_fromUtf8("cmbDiagRangeTo1"))
        self.gridLayout_2.addWidget(self.cmbDiagRangeTo1, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.frmDiagRange1, 6, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 8, 2, 1, 1)
        self.lblCode.setBuddy(self.edtCode)
        self.lblName.setBuddy(self.edtName)
        self.lblGroup.setBuddy(self.cmbGroup)
        self.lblDiagRange1.setBuddy(self.cmbDiagRangeFrom1)
        self.lblDiagRangeFrom2.setBuddy(self.cmbDiagRangeFrom2)
        self.lblDiagRangeTo2.setBuddy(self.cmbDiagRangeTo2)
        self.lblDiagRange2.setBuddy(self.cmbDiagRangeFrom2)
        self.lblDiagRangeFrom1.setBuddy(self.cmbDiagRangeFrom1)
        self.lblDiagRangeTo1.setBuddy(self.cmbDiagRangeTo1)

        self.retranslateUi(MKBMorphologyEditor)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MKBMorphologyEditor.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MKBMorphologyEditor.reject)
        QtCore.QMetaObject.connectSlotsByName(MKBMorphologyEditor)
        MKBMorphologyEditor.setTabOrder(self.edtCode, self.edtName)
        MKBMorphologyEditor.setTabOrder(self.edtName, self.cmbGroup)
        MKBMorphologyEditor.setTabOrder(self.cmbGroup, self.cmbDiagRangeFrom1)
        MKBMorphologyEditor.setTabOrder(self.cmbDiagRangeFrom1, self.cmbDiagRangeTo1)
        MKBMorphologyEditor.setTabOrder(self.cmbDiagRangeTo1, self.cmbDiagRangeFrom2)
        MKBMorphologyEditor.setTabOrder(self.cmbDiagRangeFrom2, self.cmbDiagRangeTo2)
        MKBMorphologyEditor.setTabOrder(self.cmbDiagRangeTo2, self.buttonBox)

    def retranslateUi(self, MKBMorphologyEditor):
        MKBMorphologyEditor.setWindowTitle(QtGui.QApplication.translate("MKBMorphologyEditor", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCode.setText(QtGui.QApplication.translate("MKBMorphologyEditor", "Код", None, QtGui.QApplication.UnicodeUTF8))
        self.lblName.setText(QtGui.QApplication.translate("MKBMorphologyEditor", "Наименование", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGroup.setText(QtGui.QApplication.translate("MKBMorphologyEditor", "Группа", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDiagRange1.setText(QtGui.QApplication.translate("MKBMorphologyEditor", "Диапозон МКБ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDiagRangeFrom2.setText(QtGui.QApplication.translate("MKBMorphologyEditor", "с", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDiagRangeTo2.setText(QtGui.QApplication.translate("MKBMorphologyEditor", "по", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDiagRange2.setText(QtGui.QApplication.translate("MKBMorphologyEditor", "Диапозон МКБ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDiagRangeFrom1.setText(QtGui.QApplication.translate("MKBMorphologyEditor", "с", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDiagRangeTo1.setText(QtGui.QApplication.translate("MKBMorphologyEditor", "по", None, QtGui.QApplication.UnicodeUTF8))

from library.crbcombobox import CRBComboBox
from library.ICDCodeEdit import CICDCodeEditEx

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MKBMorphologyEditor = QtGui.QDialog()
    ui = Ui_MKBMorphologyEditor()
    ui.setupUi(MKBMorphologyEditor)
    MKBMorphologyEditor.show()
    sys.exit(app.exec_())

