# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CreateDialog(object):
    def setupUi(self, CreateDialog):
        CreateDialog.setObjectName(_fromUtf8("CreateDialog"))
        CreateDialog.resize(502, 146)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CreateDialog.sizePolicy().hasHeightForWidth())
        CreateDialog.setSizePolicy(sizePolicy)
        CreateDialog.setSizeGripEnabled(False)
        self.gridLayout_2 = QtGui.QGridLayout(CreateDialog)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setHorizontalSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edtExtExamDisabledTotal = QtGui.QLineEdit(CreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtExtExamDisabledTotal.sizePolicy().hasHeightForWidth())
        self.edtExtExamDisabledTotal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edtExtExamDisabledTotal.setFont(font)
        self.edtExtExamDisabledTotal.setFrame(False)
        self.edtExtExamDisabledTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtExtExamDisabledTotal.setReadOnly(True)
        self.edtExtExamDisabledTotal.setObjectName(_fromUtf8("edtExtExamDisabledTotal"))
        self.gridLayout.addWidget(self.edtExtExamDisabledTotal, 1, 1, 1, 1)
        self.lbl = QtGui.QLabel(CreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl.sizePolicy().hasHeightForWidth())
        self.lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl.setFont(font)
        self.lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl.setObjectName(_fromUtf8("lbl"))
        self.gridLayout.addWidget(self.lbl, 0, 2, 1, 1)
        self.lblTotal = QtGui.QLabel(CreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTotal.sizePolicy().hasHeightForWidth())
        self.lblTotal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblTotal.setFont(font)
        self.lblTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotal.setObjectName(_fromUtf8("lblTotal"))
        self.gridLayout.addWidget(self.lblTotal, 0, 1, 1, 1)
        self.lblExtExam = QtGui.QLabel(CreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExtExam.sizePolicy().hasHeightForWidth())
        self.lblExtExam.setSizePolicy(sizePolicy)
        self.lblExtExam.setObjectName(_fromUtf8("lblExtExam"))
        self.gridLayout.addWidget(self.lblExtExam, 2, 0, 1, 1)
        self.edtExtExam = QtGui.QLineEdit(CreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtExtExam.sizePolicy().hasHeightForWidth())
        self.edtExtExam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edtExtExam.setFont(font)
        self.edtExtExam.setFrame(False)
        self.edtExtExam.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtExtExam.setReadOnly(True)
        self.edtExtExam.setObjectName(_fromUtf8("edtExtExam"))
        self.gridLayout.addWidget(self.edtExtExam, 2, 2, 1, 1)
        self.lblExtExamDisabled = QtGui.QLabel(CreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExtExamDisabled.sizePolicy().hasHeightForWidth())
        self.lblExtExamDisabled.setSizePolicy(sizePolicy)
        self.lblExtExamDisabled.setObjectName(_fromUtf8("lblExtExamDisabled"))
        self.gridLayout.addWidget(self.lblExtExamDisabled, 1, 0, 1, 1)
        self.edtExtExamDisabled = QtGui.QLineEdit(CreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtExtExamDisabled.sizePolicy().hasHeightForWidth())
        self.edtExtExamDisabled.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edtExtExamDisabled.setFont(font)
        self.edtExtExamDisabled.setFrame(False)
        self.edtExtExamDisabled.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtExtExamDisabled.setReadOnly(True)
        self.edtExtExamDisabled.setObjectName(_fromUtf8("edtExtExamDisabled"))
        self.gridLayout.addWidget(self.edtExtExamDisabled, 1, 2, 1, 1)
        self.edtExtExamTotal = QtGui.QLineEdit(CreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtExtExamTotal.sizePolicy().hasHeightForWidth())
        self.edtExtExamTotal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edtExtExamTotal.setFont(font)
        self.edtExtExamTotal.setFrame(False)
        self.edtExtExamTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtExtExamTotal.setReadOnly(True)
        self.edtExtExamTotal.setObjectName(_fromUtf8("edtExtExamTotal"))
        self.gridLayout.addWidget(self.edtExtExamTotal, 2, 1, 1, 1)
        self.lblPreventiveExam = QtGui.QLabel(CreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPreventiveExam.sizePolicy().hasHeightForWidth())
        self.lblPreventiveExam.setSizePolicy(sizePolicy)
        self.lblPreventiveExam.setObjectName(_fromUtf8("lblPreventiveExam"))
        self.gridLayout.addWidget(self.lblPreventiveExam, 3, 0, 2, 1)
        self.edtPreventiveExamTotal = QtGui.QLineEdit(CreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPreventiveExamTotal.sizePolicy().hasHeightForWidth())
        self.edtPreventiveExamTotal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edtPreventiveExamTotal.setFont(font)
        self.edtPreventiveExamTotal.setFrame(False)
        self.edtPreventiveExamTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtPreventiveExamTotal.setReadOnly(True)
        self.edtPreventiveExamTotal.setObjectName(_fromUtf8("edtPreventiveExamTotal"))
        self.gridLayout.addWidget(self.edtPreventiveExamTotal, 3, 1, 2, 1)
        self.edtPreventiveExam = QtGui.QLineEdit(CreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPreventiveExam.sizePolicy().hasHeightForWidth())
        self.edtPreventiveExam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edtPreventiveExam.setFont(font)
        self.edtPreventiveExam.setFrame(False)
        self.edtPreventiveExam.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtPreventiveExam.setReadOnly(True)
        self.edtPreventiveExam.setObjectName(_fromUtf8("edtPreventiveExam"))
        self.gridLayout.addWidget(self.edtPreventiveExam, 3, 2, 2, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(CreateDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(19, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)

        self.retranslateUi(CreateDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateDialog)

    def retranslateUi(self, CreateDialog):
        CreateDialog.setWindowTitle(_translate("CreateDialog", "Dialog", None))
        self.edtExtExamDisabledTotal.setText(_translate("CreateDialog", "0", None))
        self.lbl.setText(_translate("CreateDialog", "Будет добавлено", None))
        self.lblTotal.setText(_translate("CreateDialog", "В списках", None))
        self.lblExtExam.setText(_translate("CreateDialog", "Диспансеризация взрослого населения", None))
        self.edtExtExam.setText(_translate("CreateDialog", "0", None))
        self.lblExtExamDisabled.setText(_translate("CreateDialog", "Диспансеризация инвалидов", None))
        self.edtExtExamDisabled.setText(_translate("CreateDialog", "0", None))
        self.edtExtExamTotal.setText(_translate("CreateDialog", "0", None))
        self.lblPreventiveExam.setText(_translate("CreateDialog", "Проф. осмотры", None))
        self.edtPreventiveExamTotal.setText(_translate("CreateDialog", "0", None))
        self.edtPreventiveExam.setText(_translate("CreateDialog", "0", None))

