##################################################
# file: EMSRNExchange_client.py
#
# client stubs generated by "ZSI.generate.wsdl2python.WriteServiceModule"
#     C:\pydev\Python25\wsdl2py.bat -b https://webservice.ktsz.spb.ru:4443/EMSRNExchange.asmx?WSDL
#
##################################################

from EMSRNExchange_types import *
from ZSI import client
from ZSI.schema import GED

# Locator
class EMSRNExchangeLocator:
    EMSRNExchangeSoap_address = "https://webservice.ktsz.spb.ru:4443/EMSRNExchange.asmx"
    def getEMSRNExchangeSoapAddress(self):
        return EMSRNExchangeLocator.EMSRNExchangeSoap_address
    def getEMSRNExchangeSoap(self, url=None, **kw):
        return EMSRNExchangeSoapSOAP(url or EMSRNExchangeLocator.EMSRNExchangeSoap_address, **kw)

# Methods
class EMSRNExchangeSoapSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: MessageList_XML
    def MessageList_XML(self, request, **kw):
        if isinstance(request, MessageList_XMLSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://webservice.ktsz.spb.ru/MessageList_XML", **kw)
        # no output wsaction
        response = self.binding.Receive(MessageList_XMLSoapOut.typecode)
        return response

    # op: Message_XML
    def Message_XML(self, request, **kw):
        if isinstance(request, Message_XMLSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://webservice.ktsz.spb.ru/Message_XML", **kw)
        # no output wsaction
        response = self.binding.Receive(Message_XMLSoapOut.typecode)
        return response

    # op: MessageObtained_XML
    def MessageObtained_XML(self, request, **kw):
        if isinstance(request, MessageObtained_XMLSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://webservice.ktsz.spb.ru/MessageObtained_XML", **kw)
        # no output wsaction
        response = self.binding.Receive(MessageObtained_XMLSoapOut.typecode)
        return response

    # op: MessageDeclined_XML
    def MessageDeclined_XML(self, request, **kw):
        if isinstance(request, MessageDeclined_XMLSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://webservice.ktsz.spb.ru/MessageDeclined_XML", **kw)
        # no output wsaction
        response = self.binding.Receive(MessageDeclined_XMLSoapOut.typecode)
        return response

    # op: PersonBenefitCategories
    def PersonBenefitCategories(self, request, **kw):
        if isinstance(request, PersonBenefitCategoriesSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://webservice.ktsz.spb.ru/PersonBenefitCategories", **kw)
        # no output wsaction
        response = self.binding.Receive(PersonBenefitCategoriesSoapOut.typecode)
        return response

MessageList_XMLSoapIn = GED("http://webservice.ktsz.spb.ru/", "MessageList_XML").pyclass

MessageList_XMLSoapOut = GED("http://webservice.ktsz.spb.ru/", "MessageList_XMLResponse").pyclass

Message_XMLSoapIn = GED("http://webservice.ktsz.spb.ru/", "Message_XML").pyclass

Message_XMLSoapOut = GED("http://webservice.ktsz.spb.ru/", "Message_XMLResponse").pyclass

MessageObtained_XMLSoapIn = GED("http://webservice.ktsz.spb.ru/", "MessageObtained_XML").pyclass

MessageObtained_XMLSoapOut = GED("http://webservice.ktsz.spb.ru/", "MessageObtained_XMLResponse").pyclass

MessageDeclined_XMLSoapIn = GED("http://webservice.ktsz.spb.ru/", "MessageDeclined_XML").pyclass

MessageDeclined_XMLSoapOut = GED("http://webservice.ktsz.spb.ru/", "MessageDeclined_XMLResponse").pyclass

PersonBenefitCategoriesSoapIn = GED("http://webservice.ktsz.spb.ru/", "PersonBenefitCategories").pyclass

PersonBenefitCategoriesSoapOut = GED("http://webservice.ktsz.spb.ru/", "PersonBenefitCategoriesResponse").pyclass
