##################################################
# file: EMSRNExchange_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      C:\pydev\Python25\wsdl2py.bat -b https://webservice.ktsz.spb.ru:4443/EMSRNExchange.asmx?WSDL
#
##################################################

from ZSI.schema import GED
from EMSRNExchange_types    import *
from ZSI.ServiceContainer   import ServiceSOAPBinding

# Messages  
MessageList_XMLSoapIn = GED("http://webservice.ktsz.spb.ru/", "MessageList_XML").pyclass

MessageList_XMLSoapOut = GED("http://webservice.ktsz.spb.ru/", "MessageList_XMLResponse").pyclass

Message_XMLSoapIn = GED("http://webservice.ktsz.spb.ru/", "Message_XML").pyclass

Message_XMLSoapOut = GED("http://webservice.ktsz.spb.ru/", "Message_XMLResponse").pyclass

MessageObtained_XMLSoapIn = GED("http://webservice.ktsz.spb.ru/", "MessageObtained_XML").pyclass

MessageObtained_XMLSoapOut = GED("http://webservice.ktsz.spb.ru/", "MessageObtained_XMLResponse").pyclass

MessageDeclined_XMLSoapIn = GED("http://webservice.ktsz.spb.ru/", "MessageDeclined_XML").pyclass

MessageDeclined_XMLSoapOut = GED("http://webservice.ktsz.spb.ru/", "MessageDeclined_XMLResponse").pyclass

PersonBenefitCategoriesSoapIn = GED("http://webservice.ktsz.spb.ru/", "PersonBenefitCategories").pyclass

PersonBenefitCategoriesSoapOut = GED("http://webservice.ktsz.spb.ru/", "PersonBenefitCategoriesResponse").pyclass


# Service Skeletons
class EMSRNExchange(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/EMSRNExchange.asmx', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_MessageList_XML(self, ps, **kw):
        request = ps.Parse(MessageList_XMLSoapIn.typecode)
        return request,MessageList_XMLSoapOut()

    soapAction['http://webservice.ktsz.spb.ru/MessageList_XML'] = 'soap_MessageList_XML'
    root[(MessageList_XMLSoapIn.typecode.nspname,MessageList_XMLSoapIn.typecode.pname)] = 'soap_MessageList_XML'

    def soap_Message_XML(self, ps, **kw):
        request = ps.Parse(Message_XMLSoapIn.typecode)
        return request,Message_XMLSoapOut()

    soapAction['http://webservice.ktsz.spb.ru/Message_XML'] = 'soap_Message_XML'
    root[(Message_XMLSoapIn.typecode.nspname,Message_XMLSoapIn.typecode.pname)] = 'soap_Message_XML'

    def soap_MessageObtained_XML(self, ps, **kw):
        request = ps.Parse(MessageObtained_XMLSoapIn.typecode)
        return request,MessageObtained_XMLSoapOut()

    soapAction['http://webservice.ktsz.spb.ru/MessageObtained_XML'] = 'soap_MessageObtained_XML'
    root[(MessageObtained_XMLSoapIn.typecode.nspname,MessageObtained_XMLSoapIn.typecode.pname)] = 'soap_MessageObtained_XML'

    def soap_MessageDeclined_XML(self, ps, **kw):
        request = ps.Parse(MessageDeclined_XMLSoapIn.typecode)
        return request,MessageDeclined_XMLSoapOut()

    soapAction['http://webservice.ktsz.spb.ru/MessageDeclined_XML'] = 'soap_MessageDeclined_XML'
    root[(MessageDeclined_XMLSoapIn.typecode.nspname,MessageDeclined_XMLSoapIn.typecode.pname)] = 'soap_MessageDeclined_XML'

    def soap_PersonBenefitCategories(self, ps, **kw):
        request = ps.Parse(PersonBenefitCategoriesSoapIn.typecode)
        return request,PersonBenefitCategoriesSoapOut()

    soapAction['http://webservice.ktsz.spb.ru/PersonBenefitCategories'] = 'soap_PersonBenefitCategories'
    root[(PersonBenefitCategoriesSoapIn.typecode.nspname,PersonBenefitCategoriesSoapIn.typecode.pname)] = 'soap_PersonBenefitCategories'

