################################################## 
# IemcServer_services.py 
# generated by ZSI.generate.wsdl2python
##################################################


from IemcServer_services_types import *
from ZSI import client

# Locator
class IemcServerLocator:
    IemcServer_address = "http://localhost:7000"
    def getIemcServerAddress(self):
        return IemcServerLocator.IemcServer_address
    def getIemcServer(self, url=None, **kw):
        return IemcServerSOAP(url or IemcServerLocator.IemcServer_address, **kw)

# Methods
class IemcServerSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: SendEventData
    def SendEventData(self, request):
        if isinstance(request, SendEventDataRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="SendEventData", **kw)
        # no output wsaction
        response = self.binding.Receive(SendEventDataResponse.typecode)
        return response

SendEventDataRequest = ns0.iemc_Dec().pyclass

SendEventDataResponse = ns0.Errors_Dec().pyclass
