# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F110.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1250, 838)
        Dialog.setSizeGripEnabled(True)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.sptTopLevel = QtGui.QSplitter(Dialog)
        self.sptTopLevel.setOrientation(QtCore.Qt.Vertical)
        self.sptTopLevel.setObjectName(_fromUtf8("sptTopLevel"))
        self.txtClientInfoBrowser = CTextBrowser(self.sptTopLevel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtClientInfoBrowser.sizePolicy().hasHeightForWidth())
        self.txtClientInfoBrowser.setSizePolicy(sizePolicy)
        self.txtClientInfoBrowser.setMinimumSize(QtCore.QSize(0, 100))
        self.txtClientInfoBrowser.setMaximumSize(QtCore.QSize(16777215, 130))
        self.txtClientInfoBrowser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.tabWidget = QtGui.QTabWidget(self.sptTopLevel)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabToken = QtGui.QWidget()
        self.tabToken.setObjectName(_fromUtf8("tabToken"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabToken)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.tabToken)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1201, 907))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frameBaseAndDiagnosises = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameBaseAndDiagnosises.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameBaseAndDiagnosises.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBaseAndDiagnosises.setObjectName(_fromUtf8("frameBaseAndDiagnosises"))
        self.gridLayout_10 = QtGui.QGridLayout(self.frameBaseAndDiagnosises)
        self.gridLayout_10.setMargin(2)
        self.gridLayout_10.setSpacing(2)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.splitter = QtGui.QSplitter(self.frameBaseAndDiagnosises)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.grplFinalDiagnostics = QtGui.QGroupBox(self.splitter)
        self.grplFinalDiagnostics.setObjectName(_fromUtf8("grplFinalDiagnostics"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grplFinalDiagnostics)
        self.gridLayout_3.setMargin(2)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblFinalDiagnostics = CInDocTableView(self.grplFinalDiagnostics)
        self.tblFinalDiagnostics.setObjectName(_fromUtf8("tblFinalDiagnostics"))
        self.gridLayout_3.addWidget(self.tblFinalDiagnostics, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.splitter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setMargin(2)
        self.gridLayout_5.setSpacing(2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tblPersonnel = CInDocTableView(self.groupBox)
        self.tblPersonnel.setObjectName(_fromUtf8("tblPersonnel"))
        self.gridLayout_5.addWidget(self.tblPersonnel, 0, 0, 1, 1)
        self.grpRenunOfHospital = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpRenunOfHospital.sizePolicy().hasHeightForWidth())
        self.grpRenunOfHospital.setSizePolicy(sizePolicy)
        self.grpRenunOfHospital.setCheckable(True)
        self.grpRenunOfHospital.setChecked(False)
        self.grpRenunOfHospital.setObjectName(_fromUtf8("grpRenunOfHospital"))
        self.gridLayout_4 = QtGui.QGridLayout(self.grpRenunOfHospital)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setHorizontalSpacing(4)
        self.gridLayout_4.setVerticalSpacing(2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblFaceRenunOfHospital = QtGui.QLabel(self.grpRenunOfHospital)
        self.lblFaceRenunOfHospital.setEnabled(False)
        self.lblFaceRenunOfHospital.setObjectName(_fromUtf8("lblFaceRenunOfHospital"))
        self.gridLayout_4.addWidget(self.lblFaceRenunOfHospital, 0, 0, 1, 1)
        self.edtFaceRenunOfHospital = QtGui.QLineEdit(self.grpRenunOfHospital)
        self.edtFaceRenunOfHospital.setEnabled(False)
        self.edtFaceRenunOfHospital.setObjectName(_fromUtf8("edtFaceRenunOfHospital"))
        self.gridLayout_4.addWidget(self.edtFaceRenunOfHospital, 0, 1, 1, 1)
        self.gridLayout_10.addWidget(self.splitter, 0, 1, 1, 1)
        self.grpBase = QtGui.QGroupBox(self.frameBaseAndDiagnosises)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpBase.sizePolicy().hasHeightForWidth())
        self.grpBase.setSizePolicy(sizePolicy)
        self.grpBase.setObjectName(_fromUtf8("grpBase"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpBase)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setHorizontalSpacing(4)
        self.gridLayout_2.setVerticalSpacing(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblCauseCall = QtGui.QLabel(self.grpBase)
        self.lblCauseCall.setObjectName(_fromUtf8("lblCauseCall"))
        self.gridLayout_2.addWidget(self.lblCauseCall, 5, 0, 1, 1)
        self.cmbPrimary = QtGui.QComboBox(self.grpBase)
        self.cmbPrimary.setObjectName(_fromUtf8("cmbPrimary"))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.setItemText(0, _fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbPrimary, 16, 1, 1, 4)
        self.edtNextTime = QtGui.QTimeEdit(self.grpBase)
        self.edtNextTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtNextTime.setObjectName(_fromUtf8("edtNextTime"))
        self.gridLayout_2.addWidget(self.edtNextTime, 25, 4, 1, 1)
        self.cmbResult = CRBComboBox(self.grpBase)
        self.cmbResult.setObjectName(_fromUtf8("cmbResult"))
        self.cmbResult.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbResult, 18, 1, 1, 4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 28, 0, 1, 2)
        self.lblFinishServiceDate = QtGui.QLabel(self.grpBase)
        self.lblFinishServiceDate.setObjectName(_fromUtf8("lblFinishServiceDate"))
        self.gridLayout_2.addWidget(self.lblFinishServiceDate, 12, 0, 1, 1)
        self.lblTypeAsset = QtGui.QLabel(self.grpBase)
        self.lblTypeAsset.setObjectName(_fromUtf8("lblTypeAsset"))
        self.gridLayout_2.addWidget(self.lblTypeAsset, 24, 0, 1, 3)
        self.lblVisitsDurationValue = QtGui.QLabel(self.grpBase)
        self.lblVisitsDurationValue.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lblVisitsDurationValue.setFont(font)
        self.lblVisitsDurationValue.setMouseTracking(False)
        self.lblVisitsDurationValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblVisitsDurationValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblVisitsDurationValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblVisitsDurationValue.setObjectName(_fromUtf8("lblVisitsDurationValue"))
        self.gridLayout_2.addWidget(self.lblVisitsDurationValue, 8, 4, 1, 1)
        self.edtWhoCallOnPhone = QtGui.QLineEdit(self.grpBase)
        self.edtWhoCallOnPhone.setObjectName(_fromUtf8("edtWhoCallOnPhone"))
        self.gridLayout_2.addWidget(self.edtWhoCallOnPhone, 6, 1, 1, 4)
        self.lblNumberBrigade = QtGui.QLabel(self.grpBase)
        self.lblNumberBrigade.setObjectName(_fromUtf8("lblNumberBrigade"))
        self.gridLayout_2.addWidget(self.lblNumberBrigade, 4, 0, 1, 1)
        self.lblEndDateDate = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDateDate.sizePolicy().hasHeightForWidth())
        self.lblEndDateDate.setSizePolicy(sizePolicy)
        self.lblEndDateDate.setObjectName(_fromUtf8("lblEndDateDate"))
        self.gridLayout_2.addWidget(self.lblEndDateDate, 13, 0, 1, 1)
        self.cmbTypeAsset = CRBComboBox(self.grpBase)
        self.cmbTypeAsset.setObjectName(_fromUtf8("cmbTypeAsset"))
        self.cmbTypeAsset.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbTypeAsset, 25, 0, 1, 3)
        self.lblTimeToFinishServiceDate = QtGui.QLabel(self.grpBase)
        self.lblTimeToFinishServiceDate.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblTimeToFinishServiceDate.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblTimeToFinishServiceDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTimeToFinishServiceDate.setObjectName(_fromUtf8("lblTimeToFinishServiceDate"))
        self.gridLayout_2.addWidget(self.lblTimeToFinishServiceDate, 12, 4, 1, 1)
        self.lblTimeToEndDate = QtGui.QLabel(self.grpBase)
        self.lblTimeToEndDate.setMouseTracking(False)
        self.lblTimeToEndDate.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblTimeToEndDate.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblTimeToEndDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTimeToEndDate.setObjectName(_fromUtf8("lblTimeToEndDate"))
        self.gridLayout_2.addWidget(self.lblTimeToEndDate, 13, 4, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(self.grpBase)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbPerson, 14, 1, 1, 4)
        self.lblTimeToDepartureDate = QtGui.QLabel(self.grpBase)
        self.lblTimeToDepartureDate.setStatusTip(_fromUtf8(""))
        self.lblTimeToDepartureDate.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblTimeToDepartureDate.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblTimeToDepartureDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTimeToDepartureDate.setObjectName(_fromUtf8("lblTimeToDepartureDate"))
        self.gridLayout_2.addWidget(self.lblTimeToDepartureDate, 10, 4, 1, 1)
        self.lblOrder_2 = QtGui.QLabel(self.grpBase)
        self.lblOrder_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblOrder_2.setObjectName(_fromUtf8("lblOrder_2"))
        self.gridLayout_2.addWidget(self.lblOrder_2, 17, 0, 1, 1)
        self.chkZNOFirst = QtGui.QCheckBox(self.grpBase)
        self.chkZNOFirst.setObjectName(_fromUtf8("chkZNOFirst"))
        self.gridLayout_2.addWidget(self.chkZNOFirst, 21, 0, 1, 3)
        self.cmbOrder = CRBComboBox(self.grpBase)
        self.cmbOrder.setObjectName(_fromUtf8("cmbOrder"))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.setItemText(0, _fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbOrder, 17, 1, 1, 4)
        self.lblGoal = QtGui.QLabel(self.grpBase)
        self.lblGoal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblGoal.setObjectName(_fromUtf8("lblGoal"))
        self.gridLayout_2.addWidget(self.lblGoal, 19, 0, 1, 1)
        self.lblPerson = QtGui.QLabel(self.grpBase)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout_2.addWidget(self.lblPerson, 14, 0, 1, 1)
        self.cmbGoal = CRBComboBox(self.grpBase)
        self.cmbGoal.setObjectName(_fromUtf8("cmbGoal"))
        self.gridLayout_2.addWidget(self.cmbGoal, 19, 1, 1, 4)
        self.chkExposeConfirmed = QtGui.QCheckBox(self.grpBase)
        self.chkExposeConfirmed.setObjectName(_fromUtf8("chkExposeConfirmed"))
        self.gridLayout_2.addWidget(self.chkExposeConfirmed, 3, 0, 1, 5)
        self.chkZNOMorph = QtGui.QCheckBox(self.grpBase)
        self.chkZNOMorph.setObjectName(_fromUtf8("chkZNOMorph"))
        self.gridLayout_2.addWidget(self.chkZNOMorph, 22, 0, 1, 5)
        self.lblBegDate = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDate.sizePolicy().hasHeightForWidth())
        self.lblBegDate.setSizePolicy(sizePolicy)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout_2.addWidget(self.lblBegDate, 8, 0, 1, 1)
        self.lblNumberCardCall = QtGui.QLabel(self.grpBase)
        self.lblNumberCardCall.setObjectName(_fromUtf8("lblNumberCardCall"))
        self.gridLayout_2.addWidget(self.lblNumberCardCall, 0, 0, 1, 1)
        self.edtNumberCardCall = QtGui.QLineEdit(self.grpBase)
        self.edtNumberCardCall.setObjectName(_fromUtf8("edtNumberCardCall"))
        self.gridLayout_2.addWidget(self.edtNumberCardCall, 0, 1, 1, 4)
        self.lblDepartureDate = QtGui.QLabel(self.grpBase)
        self.lblDepartureDate.setObjectName(_fromUtf8("lblDepartureDate"))
        self.gridLayout_2.addWidget(self.lblDepartureDate, 10, 0, 1, 1)
        self.lblArrivalDate = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblArrivalDate.sizePolicy().hasHeightForWidth())
        self.lblArrivalDate.setSizePolicy(sizePolicy)
        self.lblArrivalDate.setObjectName(_fromUtf8("lblArrivalDate"))
        self.gridLayout_2.addWidget(self.lblArrivalDate, 11, 0, 1, 1)
        self.lblResult = QtGui.QLabel(self.grpBase)
        self.lblResult.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblResult.setObjectName(_fromUtf8("lblResult"))
        self.gridLayout_2.addWidget(self.lblResult, 18, 0, 1, 1)
        self.lblWhoCallOnPhone = QtGui.QLabel(self.grpBase)
        self.lblWhoCallOnPhone.setObjectName(_fromUtf8("lblWhoCallOnPhone"))
        self.gridLayout_2.addWidget(self.lblWhoCallOnPhone, 6, 0, 1, 1)
        self.lblPrimary = QtGui.QLabel(self.grpBase)
        self.lblPrimary.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPrimary.setObjectName(_fromUtf8("lblPrimary"))
        self.gridLayout_2.addWidget(self.lblPrimary, 16, 0, 1, 1)
        self.cmbNumberBrigade = CRBComboBox(self.grpBase)
        self.cmbNumberBrigade.setObjectName(_fromUtf8("cmbNumberBrigade"))
        self.cmbNumberBrigade.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbNumberBrigade, 4, 1, 1, 4)
        self.lblNumberPhone = QtGui.QLabel(self.grpBase)
        self.lblNumberPhone.setObjectName(_fromUtf8("lblNumberPhone"))
        self.gridLayout_2.addWidget(self.lblNumberPhone, 7, 0, 1, 1)
        self.frmArrivalDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmArrivalDateTime.sizePolicy().hasHeightForWidth())
        self.frmArrivalDateTime.setSizePolicy(sizePolicy)
        self.frmArrivalDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmArrivalDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmArrivalDateTime.setLineWidth(0)
        self.frmArrivalDateTime.setObjectName(_fromUtf8("frmArrivalDateTime"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frmArrivalDateTime)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.edtArrivalDate = CDateEdit(self.frmArrivalDateTime)
        self.edtArrivalDate.setCalendarPopup(True)
        self.edtArrivalDate.setObjectName(_fromUtf8("edtArrivalDate"))
        self.horizontalLayout_6.addWidget(self.edtArrivalDate)
        self.edtArrivalTime = QtGui.QTimeEdit(self.frmArrivalDateTime)
        self.edtArrivalTime.setObjectName(_fromUtf8("edtArrivalTime"))
        self.horizontalLayout_6.addWidget(self.edtArrivalTime)
        self.gridLayout_2.addWidget(self.frmArrivalDateTime, 11, 1, 1, 3)
        self.frmPassDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmPassDateTime.sizePolicy().hasHeightForWidth())
        self.frmPassDateTime.setSizePolicy(sizePolicy)
        self.frmPassDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmPassDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmPassDateTime.setLineWidth(0)
        self.frmPassDateTime.setObjectName(_fromUtf8("frmPassDateTime"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frmPassDateTime)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.edtPassDate = CDateEdit(self.frmPassDateTime)
        self.edtPassDate.setCalendarPopup(True)
        self.edtPassDate.setObjectName(_fromUtf8("edtPassDate"))
        self.horizontalLayout_7.addWidget(self.edtPassDate)
        self.edtPassTime = QtGui.QTimeEdit(self.frmPassDateTime)
        self.edtPassTime.setObjectName(_fromUtf8("edtPassTime"))
        self.horizontalLayout_7.addWidget(self.edtPassTime)
        self.gridLayout_2.addWidget(self.frmPassDateTime, 9, 1, 1, 3)
        self.frmFinishServiceDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmFinishServiceDateTime.sizePolicy().hasHeightForWidth())
        self.frmFinishServiceDateTime.setSizePolicy(sizePolicy)
        self.frmFinishServiceDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmFinishServiceDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmFinishServiceDateTime.setLineWidth(0)
        self.frmFinishServiceDateTime.setObjectName(_fromUtf8("frmFinishServiceDateTime"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frmFinishServiceDateTime)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.edtFinishServiceDate = CDateEdit(self.frmFinishServiceDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFinishServiceDate.sizePolicy().hasHeightForWidth())
        self.edtFinishServiceDate.setSizePolicy(sizePolicy)
        self.edtFinishServiceDate.setCalendarPopup(True)
        self.edtFinishServiceDate.setObjectName(_fromUtf8("edtFinishServiceDate"))
        self.horizontalLayout_4.addWidget(self.edtFinishServiceDate)
        self.edtFinishServiceTime = QtGui.QTimeEdit(self.frmFinishServiceDateTime)
        self.edtFinishServiceTime.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.edtFinishServiceTime.setObjectName(_fromUtf8("edtFinishServiceTime"))
        self.horizontalLayout_4.addWidget(self.edtFinishServiceTime)
        self.gridLayout_2.addWidget(self.frmFinishServiceDateTime, 12, 1, 1, 3)
        self.gbAddress = QtGui.QGroupBox(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbAddress.sizePolicy().hasHeightForWidth())
        self.gbAddress.setSizePolicy(sizePolicy)
        self.gbAddress.setObjectName(_fromUtf8("gbAddress"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gbAddress)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.chkKLADR = QtGui.QCheckBox(self.gbAddress)
        self.chkKLADR.setChecked(True)
        self.chkKLADR.setObjectName(_fromUtf8("chkKLADR"))
        self.gridLayout_7.addWidget(self.chkKLADR, 0, 1, 1, 1)
        self.edtAddressFreeInput = QtGui.QLineEdit(self.gbAddress)
        self.edtAddressFreeInput.setEnabled(False)
        self.edtAddressFreeInput.setObjectName(_fromUtf8("edtAddressFreeInput"))
        self.gridLayout_7.addWidget(self.edtAddressFreeInput, 0, 2, 1, 1)
        self.btnLoadAddress = QtGui.QToolButton(self.gbAddress)
        self.btnLoadAddress.setArrowType(QtCore.Qt.RightArrow)
        self.btnLoadAddress.setObjectName(_fromUtf8("btnLoadAddress"))
        self.gridLayout_7.addWidget(self.btnLoadAddress, 0, 0, 1, 1)
        self.cmbAddressStreet = CStreetComboBox(self.gbAddress)
        self.cmbAddressStreet.setMinimumSize(QtCore.QSize(200, 0))
        self.cmbAddressStreet.setObjectName(_fromUtf8("cmbAddressStreet"))
        self.gridLayout_7.addWidget(self.cmbAddressStreet, 3, 0, 1, 3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblAddressHouse = QtGui.QLabel(self.gbAddress)
        self.lblAddressHouse.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAddressHouse.setObjectName(_fromUtf8("lblAddressHouse"))
        self.horizontalLayout_2.addWidget(self.lblAddressHouse)
        self.edtAddressHouse = QtGui.QLineEdit(self.gbAddress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAddressHouse.sizePolicy().hasHeightForWidth())
        self.edtAddressHouse.setSizePolicy(sizePolicy)
        self.edtAddressHouse.setMaxLength(10)
        self.edtAddressHouse.setObjectName(_fromUtf8("edtAddressHouse"))
        self.horizontalLayout_2.addWidget(self.edtAddressHouse)
        self.lblAddressBuilding = QtGui.QLabel(self.gbAddress)
        self.lblAddressBuilding.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAddressBuilding.setObjectName(_fromUtf8("lblAddressBuilding"))
        self.horizontalLayout_2.addWidget(self.lblAddressBuilding)
        self.edtAddressCorpus = QtGui.QLineEdit(self.gbAddress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAddressCorpus.sizePolicy().hasHeightForWidth())
        self.edtAddressCorpus.setSizePolicy(sizePolicy)
        self.edtAddressCorpus.setMaxLength(10)
        self.edtAddressCorpus.setObjectName(_fromUtf8("edtAddressCorpus"))
        self.horizontalLayout_2.addWidget(self.edtAddressCorpus)
        self.lblAddressFlat = QtGui.QLabel(self.gbAddress)
        self.lblAddressFlat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAddressFlat.setObjectName(_fromUtf8("lblAddressFlat"))
        self.horizontalLayout_2.addWidget(self.lblAddressFlat)
        self.edtAddressFlat = QtGui.QLineEdit(self.gbAddress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAddressFlat.sizePolicy().hasHeightForWidth())
        self.edtAddressFlat.setSizePolicy(sizePolicy)
        self.edtAddressFlat.setMaxLength(10)
        self.edtAddressFlat.setObjectName(_fromUtf8("edtAddressFlat"))
        self.horizontalLayout_2.addWidget(self.edtAddressFlat)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 4, 0, 1, 3)
        self.gridLayout_2.addWidget(self.gbAddress, 26, 0, 1, 5)
        self.frmBegDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmBegDateTime.sizePolicy().hasHeightForWidth())
        self.frmBegDateTime.setSizePolicy(sizePolicy)
        self.frmBegDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmBegDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmBegDateTime.setLineWidth(0)
        self.frmBegDateTime.setObjectName(_fromUtf8("frmBegDateTime"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frmBegDateTime)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setSpacing(4)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.edtBegDate = CDateEdit(self.frmBegDateTime)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout_8.addWidget(self.edtBegDate)
        self.edtBegTime = QtGui.QTimeEdit(self.frmBegDateTime)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.horizontalLayout_8.addWidget(self.edtBegTime)
        self.gridLayout_2.addWidget(self.frmBegDateTime, 8, 1, 1, 3)
        self.frmEndDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmEndDateTime.sizePolicy().hasHeightForWidth())
        self.frmEndDateTime.setSizePolicy(sizePolicy)
        self.frmEndDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmEndDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmEndDateTime.setLineWidth(0)
        self.frmEndDateTime.setObjectName(_fromUtf8("frmEndDateTime"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frmEndDateTime)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.edtEndDate = CDateEdit(self.frmEndDateTime)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout_5.addWidget(self.edtEndDate)
        self.edtEndTime = QtGui.QTimeEdit(self.frmEndDateTime)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.horizontalLayout_5.addWidget(self.edtEndTime)
        self.gridLayout_2.addWidget(self.frmEndDateTime, 13, 1, 1, 3)
        self.frmDepartureDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmDepartureDateTime.sizePolicy().hasHeightForWidth())
        self.frmDepartureDateTime.setSizePolicy(sizePolicy)
        self.frmDepartureDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmDepartureDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmDepartureDateTime.setLineWidth(0)
        self.frmDepartureDateTime.setObjectName(_fromUtf8("frmDepartureDateTime"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frmDepartureDateTime)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setSpacing(4)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.edtDepartureDate = CDateEdit(self.frmDepartureDateTime)
        self.edtDepartureDate.setCalendarPopup(True)
        self.edtDepartureDate.setObjectName(_fromUtf8("edtDepartureDate"))
        self.horizontalLayout_9.addWidget(self.edtDepartureDate)
        self.edtDepartureTime = QtGui.QTimeEdit(self.frmDepartureDateTime)
        self.edtDepartureTime.setObjectName(_fromUtf8("edtDepartureTime"))
        self.horizontalLayout_9.addWidget(self.edtDepartureTime)
        self.gridLayout_2.addWidget(self.frmDepartureDateTime, 10, 1, 1, 3)
        self.gbLittleStrangerFlag = QtGui.QGroupBox(self.grpBase)
        self.gbLittleStrangerFlag.setCheckable(True)
        self.gbLittleStrangerFlag.setChecked(False)
        self.gbLittleStrangerFlag.setObjectName(_fromUtf8("gbLittleStrangerFlag"))
        self.gridLayout_11 = QtGui.QGridLayout(self.gbLittleStrangerFlag)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.lblChildNumber = QtGui.QLabel(self.gbLittleStrangerFlag)
        self.lblChildNumber.setObjectName(_fromUtf8("lblChildNumber"))
        self.gridLayout_11.addWidget(self.lblChildNumber, 0, 0, 1, 1)
        self.sbChildNumber = QtGui.QSpinBox(self.gbLittleStrangerFlag)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbChildNumber.sizePolicy().hasHeightForWidth())
        self.sbChildNumber.setSizePolicy(sizePolicy)
        self.sbChildNumber.setMinimum(1)
        self.sbChildNumber.setObjectName(_fromUtf8("sbChildNumber"))
        self.gridLayout_11.addWidget(self.sbChildNumber, 0, 1, 1, 1)
        self.lblChildBirthDate = QtGui.QLabel(self.gbLittleStrangerFlag)
        self.lblChildBirthDate.setObjectName(_fromUtf8("lblChildBirthDate"))
        self.gridLayout_11.addWidget(self.lblChildBirthDate, 1, 0, 1, 1)
        self.cmbChildSex = QtGui.QComboBox(self.gbLittleStrangerFlag)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbChildSex.sizePolicy().hasHeightForWidth())
        self.cmbChildSex.setSizePolicy(sizePolicy)
        self.cmbChildSex.setObjectName(_fromUtf8("cmbChildSex"))
        self.cmbChildSex.addItem(_fromUtf8(""))
        self.cmbChildSex.setItemText(0, _fromUtf8(""))
        self.cmbChildSex.addItem(_fromUtf8(""))
        self.cmbChildSex.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.cmbChildSex, 0, 3, 1, 1)
        self.edtChildBirthDate = CDateEdit(self.gbLittleStrangerFlag)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtChildBirthDate.sizePolicy().hasHeightForWidth())
        self.edtChildBirthDate.setSizePolicy(sizePolicy)
        self.edtChildBirthDate.setCalendarPopup(True)
        self.edtChildBirthDate.setObjectName(_fromUtf8("edtChildBirthDate"))
        self.gridLayout_11.addWidget(self.edtChildBirthDate, 1, 2, 1, 2)
        self.lblChildSex = QtGui.QLabel(self.gbLittleStrangerFlag)
        self.lblChildSex.setObjectName(_fromUtf8("lblChildSex"))
        self.gridLayout_11.addWidget(self.lblChildSex, 0, 2, 1, 1)
        self.chkMultipleBirths = QtGui.QCheckBox(self.gbLittleStrangerFlag)
        self.chkMultipleBirths.setObjectName(_fromUtf8("chkMultipleBirths"))
        self.gridLayout_11.addWidget(self.chkMultipleBirths, 4, 0, 1, 2)
        self.lblBirthWeight = QtGui.QLabel(self.gbLittleStrangerFlag)
        self.lblBirthWeight.setObjectName(_fromUtf8("lblBirthWeight"))
        self.gridLayout_11.addWidget(self.lblBirthWeight, 2, 0, 1, 2)
        self.sbBirthWeight = QtGui.QDoubleSpinBox(self.gbLittleStrangerFlag)
        self.sbBirthWeight.setMaximum(9999.99)
        self.sbBirthWeight.setObjectName(_fromUtf8("sbBirthWeight"))
        self.gridLayout_11.addWidget(self.sbBirthWeight, 2, 2, 1, 2)
        self.gridLayout_2.addWidget(self.gbLittleStrangerFlag, 27, 0, 1, 5)
        self.lblTimeToPassDate = QtGui.QLabel(self.grpBase)
        self.lblTimeToPassDate.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblTimeToPassDate.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblTimeToPassDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTimeToPassDate.setObjectName(_fromUtf8("lblTimeToPassDate"))
        self.gridLayout_2.addWidget(self.lblTimeToPassDate, 9, 4, 1, 1)
        self.lblTimeToArrivalDate = QtGui.QLabel(self.grpBase)
        self.lblTimeToArrivalDate.setWhatsThis(_fromUtf8(""))
        self.lblTimeToArrivalDate.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblTimeToArrivalDate.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblTimeToArrivalDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTimeToArrivalDate.setObjectName(_fromUtf8("lblTimeToArrivalDate"))
        self.gridLayout_2.addWidget(self.lblTimeToArrivalDate, 11, 4, 1, 1)
        self.lblPassDate = QtGui.QLabel(self.grpBase)
        self.lblPassDate.setObjectName(_fromUtf8("lblPassDate"))
        self.gridLayout_2.addWidget(self.lblPassDate, 9, 0, 1, 1)
        self.cmbDispatcher = CPersonComboBoxEx(self.grpBase)
        self.cmbDispatcher.setObjectName(_fromUtf8("cmbDispatcher"))
        self.cmbDispatcher.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbDispatcher, 15, 1, 1, 4)
        self.edtNextDate = CDateEdit(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtNextDate.sizePolicy().hasHeightForWidth())
        self.edtNextDate.setSizePolicy(sizePolicy)
        self.edtNextDate.setCalendarPopup(True)
        self.edtNextDate.setObjectName(_fromUtf8("edtNextDate"))
        self.gridLayout_2.addWidget(self.edtNextDate, 25, 3, 1, 1)
        self.cmbCauseCall = CRBComboBox(self.grpBase)
        self.cmbCauseCall.setObjectName(_fromUtf8("cmbCauseCall"))
        self.cmbCauseCall.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbCauseCall, 5, 1, 1, 4)
        self.edtNumberPhone = QtGui.QLineEdit(self.grpBase)
        self.edtNumberPhone.setObjectName(_fromUtf8("edtNumberPhone"))
        self.gridLayout_2.addWidget(self.edtNumberPhone, 7, 1, 1, 4)
        self.chkDispByMobileTeam = QtGui.QCheckBox(self.grpBase)
        self.chkDispByMobileTeam.setToolTip(_fromUtf8(""))
        self.chkDispByMobileTeam.setWhatsThis(_fromUtf8(""))
        self.chkDispByMobileTeam.setObjectName(_fromUtf8("chkDispByMobileTeam"))
        self.gridLayout_2.addWidget(self.chkDispByMobileTeam, 20, 0, 1, 5)
        self.lblDispatcher = QtGui.QLabel(self.grpBase)
        self.lblDispatcher.setObjectName(_fromUtf8("lblDispatcher"))
        self.gridLayout_2.addWidget(self.lblDispatcher, 15, 0, 1, 1)
        self.cmbContract = CContractComboBox(self.grpBase)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.cmbContract.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbContract, 1, 0, 1, 5)
        self.chkIsClosed = QtGui.QCheckBox(self.grpBase)
        self.chkIsClosed.setObjectName(_fromUtf8("chkIsClosed"))
        self.gridLayout_2.addWidget(self.chkIsClosed, 2, 0, 1, 5)
        self.gridLayout_10.addWidget(self.grpBase, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frameBaseAndDiagnosises)
        self.grpActions = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.grpActions.setObjectName(_fromUtf8("grpActions"))
        self.gridLayout_8 = QtGui.QGridLayout(self.grpActions)
        self.gridLayout_8.setMargin(2)
        self.gridLayout_8.setSpacing(2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.cmbPlaceReceptionCall = CRBComboBox(self.grpActions)
        self.cmbPlaceReceptionCall.setObjectName(_fromUtf8("cmbPlaceReceptionCall"))
        self.cmbPlaceReceptionCall.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cmbPlaceReceptionCall, 0, 1, 1, 1)
        self.lblDisease = QtGui.QLabel(self.grpActions)
        self.lblDisease.setObjectName(_fromUtf8("lblDisease"))
        self.gridLayout_8.addWidget(self.lblDisease, 0, 2, 1, 1)
        self.chkDisease = QtGui.QCheckBox(self.grpActions)
        self.chkDisease.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkDisease.setText(_fromUtf8(""))
        self.chkDisease.setChecked(True)
        self.chkDisease.setObjectName(_fromUtf8("chkDisease"))
        self.gridLayout_8.addWidget(self.chkDisease, 0, 3, 1, 1)
        self.lblDeath = QtGui.QLabel(self.grpActions)
        self.lblDeath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDeath.setObjectName(_fromUtf8("lblDeath"))
        self.gridLayout_8.addWidget(self.lblDeath, 0, 4, 1, 1)
        self.cmbDeath = CRBComboBox(self.grpActions)
        self.cmbDeath.setObjectName(_fromUtf8("cmbDeath"))
        self.cmbDeath.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cmbDeath, 0, 5, 1, 1)
        self.lblMethodTransportation = QtGui.QLabel(self.grpActions)
        self.lblMethodTransportation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblMethodTransportation.setObjectName(_fromUtf8("lblMethodTransportation"))
        self.gridLayout_8.addWidget(self.lblMethodTransportation, 0, 6, 1, 1)
        self.cmbMethodTransportation = CRBComboBox(self.grpActions)
        self.cmbMethodTransportation.setObjectName(_fromUtf8("cmbMethodTransportation"))
        self.cmbMethodTransportation.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cmbMethodTransportation, 0, 7, 1, 1)
        self.lblReceivedCall = QtGui.QLabel(self.grpActions)
        self.lblReceivedCall.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblReceivedCall.setObjectName(_fromUtf8("lblReceivedCall"))
        self.gridLayout_8.addWidget(self.lblReceivedCall, 1, 0, 1, 1)
        self.cmbReceivedCall = CRBComboBox(self.grpActions)
        self.cmbReceivedCall.setObjectName(_fromUtf8("cmbReceivedCall"))
        self.cmbReceivedCall.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cmbReceivedCall, 1, 1, 1, 1)
        self.lblBirth = QtGui.QLabel(self.grpActions)
        self.lblBirth.setObjectName(_fromUtf8("lblBirth"))
        self.gridLayout_8.addWidget(self.lblBirth, 1, 2, 1, 1)
        self.chkBirth = QtGui.QCheckBox(self.grpActions)
        self.chkBirth.setText(_fromUtf8(""))
        self.chkBirth.setObjectName(_fromUtf8("chkBirth"))
        self.gridLayout_8.addWidget(self.chkBirth, 1, 3, 1, 1)
        self.lblEbriety = QtGui.QLabel(self.grpActions)
        self.lblEbriety.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblEbriety.setObjectName(_fromUtf8("lblEbriety"))
        self.gridLayout_8.addWidget(self.lblEbriety, 1, 4, 1, 1)
        self.cmbEbriety = CRBComboBox(self.grpActions)
        self.cmbEbriety.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.cmbEbriety.setObjectName(_fromUtf8("cmbEbriety"))
        self.cmbEbriety.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cmbEbriety, 1, 5, 1, 1)
        self.lblTransferredTransportation = QtGui.QLabel(self.grpActions)
        self.lblTransferredTransportation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTransferredTransportation.setObjectName(_fromUtf8("lblTransferredTransportation"))
        self.gridLayout_8.addWidget(self.lblTransferredTransportation, 1, 6, 1, 1)
        self.cmbTransferredTransportation = CRBComboBox(self.grpActions)
        self.cmbTransferredTransportation.setObjectName(_fromUtf8("cmbTransferredTransportation"))
        self.cmbTransferredTransportation.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cmbTransferredTransportation, 1, 7, 1, 1)
        self.lblReasondDelays = QtGui.QLabel(self.grpActions)
        self.lblReasondDelays.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblReasondDelays.setObjectName(_fromUtf8("lblReasondDelays"))
        self.gridLayout_8.addWidget(self.lblReasondDelays, 2, 0, 1, 1)
        self.cmbReasondDelays = CRBComboBox(self.grpActions)
        self.cmbReasondDelays.setObjectName(_fromUtf8("cmbReasondDelays"))
        self.cmbReasondDelays.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cmbReasondDelays, 2, 1, 1, 1)
        self.lblPregnancyFailure = QtGui.QLabel(self.grpActions)
        self.lblPregnancyFailure.setObjectName(_fromUtf8("lblPregnancyFailure"))
        self.gridLayout_8.addWidget(self.lblPregnancyFailure, 2, 2, 1, 1)
        self.chkPregnancyFailure = QtGui.QCheckBox(self.grpActions)
        self.chkPregnancyFailure.setText(_fromUtf8(""))
        self.chkPregnancyFailure.setObjectName(_fromUtf8("chkPregnancyFailure"))
        self.gridLayout_8.addWidget(self.chkPregnancyFailure, 2, 3, 1, 1)
        self.lblDiseased = QtGui.QLabel(self.grpActions)
        self.lblDiseased.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDiseased.setObjectName(_fromUtf8("lblDiseased"))
        self.gridLayout_8.addWidget(self.lblDiseased, 2, 4, 1, 1)
        self.cmbDiseased = CRBComboBox(self.grpActions)
        self.cmbDiseased.setObjectName(_fromUtf8("cmbDiseased"))
        self.cmbDiseased.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cmbDiseased, 2, 5, 1, 1)
        self.lblResultCircumstanceCall = QtGui.QLabel(self.grpActions)
        self.lblResultCircumstanceCall.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblResultCircumstanceCall.setObjectName(_fromUtf8("lblResultCircumstanceCall"))
        self.gridLayout_8.addWidget(self.lblResultCircumstanceCall, 3, 0, 1, 1)
        self.cmbResultCircumstanceCall = CRBComboBox(self.grpActions)
        self.cmbResultCircumstanceCall.setObjectName(_fromUtf8("cmbResultCircumstanceCall"))
        self.cmbResultCircumstanceCall.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cmbResultCircumstanceCall, 3, 1, 1, 1)
        self.lblAccident = QtGui.QLabel(self.grpActions)
        self.lblAccident.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAccident.setObjectName(_fromUtf8("lblAccident"))
        self.gridLayout_8.addWidget(self.lblAccident, 3, 2, 1, 1)
        self.cmbAccident = CRBComboBox(self.grpActions)
        self.cmbAccident.setObjectName(_fromUtf8("cmbAccident"))
        self.cmbAccident.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cmbAccident, 3, 3, 1, 1)
        self.lblPlaceCall = QtGui.QLabel(self.grpActions)
        self.lblPlaceCall.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPlaceCall.setObjectName(_fromUtf8("lblPlaceCall"))
        self.gridLayout_8.addWidget(self.lblPlaceCall, 3, 4, 1, 1)
        self.cmbPlaceCall = CRBComboBox(self.grpActions)
        self.cmbPlaceCall.setObjectName(_fromUtf8("cmbPlaceCall"))
        self.cmbPlaceCall.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cmbPlaceCall, 3, 5, 1, 1)
        self.lblPlaceReceptionCall = QtGui.QLabel(self.grpActions)
        self.lblPlaceReceptionCall.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPlaceReceptionCall.setObjectName(_fromUtf8("lblPlaceReceptionCall"))
        self.gridLayout_8.addWidget(self.lblPlaceReceptionCall, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.grpActions)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tabToken, _fromUtf8(""))
        self.tabMes = CFastEventMesPage()
        self.tabMes.setObjectName(_fromUtf8("tabMes"))
        self.tabWidget.addTab(self.tabMes, _fromUtf8(""))
        self.tabStatus = CActionsPage()
        self.tabStatus.setObjectName(_fromUtf8("tabStatus"))
        self.tabWidget.addTab(self.tabStatus, _fromUtf8(""))
        self.tabDiagnostic = CActionsPage()
        self.tabDiagnostic.setObjectName(_fromUtf8("tabDiagnostic"))
        self.tabWidget.addTab(self.tabDiagnostic, _fromUtf8(""))
        self.tabCure = CActionsPage()
        self.tabCure.setObjectName(_fromUtf8("tabCure"))
        self.tabWidget.addTab(self.tabCure, _fromUtf8(""))
        self.tabMisc = CActionsPage()
        self.tabMisc.setObjectName(_fromUtf8("tabMisc"))
        self.tabWidget.addTab(self.tabMisc, _fromUtf8(""))
        self.tabAmbCard = CAmbCardPage()
        self.tabAmbCard.setObjectName(_fromUtf8("tabAmbCard"))
        self.tabWidget.addTab(self.tabAmbCard, _fromUtf8(""))
        self.tabTempInvalidEtc = QtGui.QWidget()
        self.tabTempInvalidEtc.setObjectName(_fromUtf8("tabTempInvalidEtc"))
        self.gridLayout = QtGui.QGridLayout(self.tabTempInvalidEtc)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tabTempInvalidEtc)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1218, 594))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tabTempInvalidAndAegrotat = QtGui.QTabWidget(self.scrollAreaWidgetContents_2)
        self.tabTempInvalidAndAegrotat.setObjectName(_fromUtf8("tabTempInvalidAndAegrotat"))
        self.tabTempInvalid = QtGui.QWidget()
        self.tabTempInvalid.setObjectName(_fromUtf8("tabTempInvalid"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tabTempInvalid)
        self.gridLayout_9.setMargin(4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.grpTempInvalid = CTempInvalid(self.tabTempInvalid)
        self.grpTempInvalid.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpTempInvalid.sizePolicy().hasHeightForWidth())
        self.grpTempInvalid.setSizePolicy(sizePolicy)
        self.grpTempInvalid.setCheckable(True)
        self.grpTempInvalid.setChecked(False)
        self.grpTempInvalid.setObjectName(_fromUtf8("grpTempInvalid"))
        self.gridLayout_9.addWidget(self.grpTempInvalid, 0, 0, 1, 1)
        self.tabTempInvalidAndAegrotat.addTab(self.tabTempInvalid, _fromUtf8(""))
        self.tabTempInvalidS = QtGui.QWidget()
        self.tabTempInvalidS.setObjectName(_fromUtf8("tabTempInvalidS"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabTempInvalidS)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.grpDisability = CTempInvalid(self.tabTempInvalidS)
        self.grpDisability.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpDisability.sizePolicy().hasHeightForWidth())
        self.grpDisability.setSizePolicy(sizePolicy)
        self.grpDisability.setCheckable(True)
        self.grpDisability.setChecked(False)
        self.grpDisability.setObjectName(_fromUtf8("grpDisability"))
        self.gridLayout_6.addWidget(self.grpDisability, 0, 0, 1, 1)
        self.tabTempInvalidAndAegrotat.addTab(self.tabTempInvalidS, _fromUtf8(""))
        self.tabTempinvalidDisability = QtGui.QWidget()
        self.tabTempinvalidDisability.setObjectName(_fromUtf8("tabTempinvalidDisability"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tabTempinvalidDisability)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.grpVitalRestriction = CTempInvalid(self.tabTempinvalidDisability)
        self.grpVitalRestriction.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpVitalRestriction.sizePolicy().hasHeightForWidth())
        self.grpVitalRestriction.setSizePolicy(sizePolicy)
        self.grpVitalRestriction.setCheckable(True)
        self.grpVitalRestriction.setChecked(False)
        self.grpVitalRestriction.setObjectName(_fromUtf8("grpVitalRestriction"))
        self.gridLayout_12.addWidget(self.grpVitalRestriction, 0, 0, 1, 1)
        self.tabTempInvalidAndAegrotat.addTab(self.tabTempinvalidDisability, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.tabTempInvalidAndAegrotat)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabTempInvalidEtc, _fromUtf8(""))
        self.tabCash = CEventCashPage()
        self.tabCash.setObjectName(_fromUtf8("tabCash"))
        self.tabWidget.addTab(self.tabCash, _fromUtf8(""))
        self.tabNotes = CEventNotesPage()
        self.tabNotes.setObjectName(_fromUtf8("tabNotes"))
        self.tabWidget.addTab(self.tabNotes, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.sptTopLevel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblValueExternalId = QtGui.QLabel(Dialog)
        self.lblValueExternalId.setText(_fromUtf8(""))
        self.lblValueExternalId.setObjectName(_fromUtf8("lblValueExternalId"))
        self.horizontalLayout.addWidget(self.lblValueExternalId)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.statusBar = QtGui.QStatusBar(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.verticalLayout_2.addWidget(self.statusBar)
        self.lblFaceRenunOfHospital.setBuddy(self.edtFaceRenunOfHospital)
        self.lblCauseCall.setBuddy(self.cmbCauseCall)
        self.lblFinishServiceDate.setBuddy(self.edtFinishServiceDate)
        self.lblTypeAsset.setBuddy(self.cmbTypeAsset)
        self.lblNumberBrigade.setBuddy(self.cmbNumberBrigade)
        self.lblEndDateDate.setBuddy(self.edtEndDate)
        self.lblOrder_2.setBuddy(self.cmbOrder)
        self.lblGoal.setBuddy(self.cmbGoal)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblNumberCardCall.setBuddy(self.edtNumberCardCall)
        self.lblDepartureDate.setBuddy(self.edtDepartureDate)
        self.lblArrivalDate.setBuddy(self.edtArrivalDate)
        self.lblResult.setBuddy(self.cmbResult)
        self.lblWhoCallOnPhone.setBuddy(self.edtWhoCallOnPhone)
        self.lblPrimary.setBuddy(self.cmbPrimary)
        self.lblNumberPhone.setBuddy(self.edtNumberPhone)
        self.lblAddressHouse.setBuddy(self.edtAddressHouse)
        self.lblAddressBuilding.setBuddy(self.edtAddressCorpus)
        self.lblAddressFlat.setBuddy(self.edtAddressFlat)
        self.lblChildNumber.setBuddy(self.sbChildNumber)
        self.lblChildBirthDate.setBuddy(self.edtChildBirthDate)
        self.lblChildSex.setBuddy(self.cmbChildSex)
        self.lblBirthWeight.setBuddy(self.sbBirthWeight)
        self.lblPassDate.setBuddy(self.edtPassDate)
        self.lblDispatcher.setBuddy(self.cmbDispatcher)
        self.lblDisease.setBuddy(self.chkDisease)
        self.lblDeath.setBuddy(self.cmbDeath)
        self.lblMethodTransportation.setBuddy(self.cmbMethodTransportation)
        self.lblReceivedCall.setBuddy(self.cmbReceivedCall)
        self.lblBirth.setBuddy(self.chkBirth)
        self.lblEbriety.setBuddy(self.cmbEbriety)
        self.lblTransferredTransportation.setBuddy(self.cmbTransferredTransportation)
        self.lblReasondDelays.setBuddy(self.cmbReasondDelays)
        self.lblPregnancyFailure.setBuddy(self.chkPregnancyFailure)
        self.lblDiseased.setBuddy(self.cmbDiseased)
        self.lblResultCircumstanceCall.setBuddy(self.cmbResultCircumstanceCall)
        self.lblAccident.setBuddy(self.cmbAccident)
        self.lblPlaceCall.setBuddy(self.cmbPlaceCall)
        self.lblPlaceReceptionCall.setBuddy(self.cmbPlaceReceptionCall)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabTempInvalidAndAegrotat.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.scrollArea)
        Dialog.setTabOrder(self.scrollArea, self.edtNumberCardCall)
        Dialog.setTabOrder(self.edtNumberCardCall, self.cmbContract)
        Dialog.setTabOrder(self.cmbContract, self.chkIsClosed)
        Dialog.setTabOrder(self.chkIsClosed, self.chkExposeConfirmed)
        Dialog.setTabOrder(self.chkExposeConfirmed, self.cmbNumberBrigade)
        Dialog.setTabOrder(self.cmbNumberBrigade, self.cmbCauseCall)
        Dialog.setTabOrder(self.cmbCauseCall, self.edtWhoCallOnPhone)
        Dialog.setTabOrder(self.edtWhoCallOnPhone, self.edtNumberPhone)
        Dialog.setTabOrder(self.edtNumberPhone, self.edtBegDate)
        Dialog.setTabOrder(self.edtBegDate, self.edtBegTime)
        Dialog.setTabOrder(self.edtBegTime, self.edtPassDate)
        Dialog.setTabOrder(self.edtPassDate, self.edtPassTime)
        Dialog.setTabOrder(self.edtPassTime, self.edtDepartureDate)
        Dialog.setTabOrder(self.edtDepartureDate, self.edtDepartureTime)
        Dialog.setTabOrder(self.edtDepartureTime, self.edtArrivalDate)
        Dialog.setTabOrder(self.edtArrivalDate, self.edtArrivalTime)
        Dialog.setTabOrder(self.edtArrivalTime, self.edtFinishServiceDate)
        Dialog.setTabOrder(self.edtFinishServiceDate, self.edtFinishServiceTime)
        Dialog.setTabOrder(self.edtFinishServiceTime, self.edtEndDate)
        Dialog.setTabOrder(self.edtEndDate, self.edtEndTime)
        Dialog.setTabOrder(self.edtEndTime, self.cmbPerson)
        Dialog.setTabOrder(self.cmbPerson, self.cmbDispatcher)
        Dialog.setTabOrder(self.cmbDispatcher, self.cmbPrimary)
        Dialog.setTabOrder(self.cmbPrimary, self.cmbOrder)
        Dialog.setTabOrder(self.cmbOrder, self.cmbResult)
        Dialog.setTabOrder(self.cmbResult, self.cmbGoal)
        Dialog.setTabOrder(self.cmbGoal, self.chkDispByMobileTeam)
        Dialog.setTabOrder(self.chkDispByMobileTeam, self.chkZNOFirst)
        Dialog.setTabOrder(self.chkZNOFirst, self.chkZNOMorph)
        Dialog.setTabOrder(self.chkZNOMorph, self.cmbTypeAsset)
        Dialog.setTabOrder(self.cmbTypeAsset, self.edtNextDate)
        Dialog.setTabOrder(self.edtNextDate, self.edtNextTime)
        Dialog.setTabOrder(self.edtNextTime, self.btnLoadAddress)
        Dialog.setTabOrder(self.btnLoadAddress, self.chkKLADR)
        Dialog.setTabOrder(self.chkKLADR, self.edtAddressFreeInput)
        Dialog.setTabOrder(self.edtAddressFreeInput, self.cmbAddressStreet)
        Dialog.setTabOrder(self.cmbAddressStreet, self.edtAddressHouse)
        Dialog.setTabOrder(self.edtAddressHouse, self.edtAddressCorpus)
        Dialog.setTabOrder(self.edtAddressCorpus, self.edtAddressFlat)
        Dialog.setTabOrder(self.edtAddressFlat, self.gbLittleStrangerFlag)
        Dialog.setTabOrder(self.gbLittleStrangerFlag, self.sbChildNumber)
        Dialog.setTabOrder(self.sbChildNumber, self.cmbChildSex)
        Dialog.setTabOrder(self.cmbChildSex, self.edtChildBirthDate)
        Dialog.setTabOrder(self.edtChildBirthDate, self.sbBirthWeight)
        Dialog.setTabOrder(self.sbBirthWeight, self.chkMultipleBirths)
        Dialog.setTabOrder(self.chkMultipleBirths, self.tblFinalDiagnostics)
        Dialog.setTabOrder(self.tblFinalDiagnostics, self.tblPersonnel)
        Dialog.setTabOrder(self.tblPersonnel, self.grpRenunOfHospital)
        Dialog.setTabOrder(self.grpRenunOfHospital, self.edtFaceRenunOfHospital)
        Dialog.setTabOrder(self.edtFaceRenunOfHospital, self.cmbPlaceReceptionCall)
        Dialog.setTabOrder(self.cmbPlaceReceptionCall, self.cmbReceivedCall)
        Dialog.setTabOrder(self.cmbReceivedCall, self.cmbReasondDelays)
        Dialog.setTabOrder(self.cmbReasondDelays, self.cmbResultCircumstanceCall)
        Dialog.setTabOrder(self.cmbResultCircumstanceCall, self.chkDisease)
        Dialog.setTabOrder(self.chkDisease, self.chkBirth)
        Dialog.setTabOrder(self.chkBirth, self.chkPregnancyFailure)
        Dialog.setTabOrder(self.chkPregnancyFailure, self.cmbAccident)
        Dialog.setTabOrder(self.cmbAccident, self.cmbDeath)
        Dialog.setTabOrder(self.cmbDeath, self.cmbEbriety)
        Dialog.setTabOrder(self.cmbEbriety, self.cmbDiseased)
        Dialog.setTabOrder(self.cmbDiseased, self.cmbPlaceCall)
        Dialog.setTabOrder(self.cmbPlaceCall, self.cmbMethodTransportation)
        Dialog.setTabOrder(self.cmbMethodTransportation, self.cmbTransferredTransportation)
        Dialog.setTabOrder(self.cmbTransferredTransportation, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.tabTempInvalidAndAegrotat)
        Dialog.setTabOrder(self.tabTempInvalidAndAegrotat, self.scrollArea_2)
        Dialog.setTabOrder(self.scrollArea_2, self.grpTempInvalid)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.txtClientInfoBrowser.setWhatsThis(_translate("Dialog", "Описание пациента", None))
        self.txtClientInfoBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.grplFinalDiagnostics.setTitle(_translate("Dialog", "&Диагнозы", None))
        self.groupBox.setTitle(_translate("Dialog", "&Состав бригады", None))
        self.grpRenunOfHospital.setTitle(_translate("Dialog", "Отказ от госпитализации", None))
        self.lblFaceRenunOfHospital.setText(_translate("Dialog", "Лицо отказа от госпитализации", None))
        self.grpBase.setTitle(_translate("Dialog", "&ф.110/У", None))
        self.lblCauseCall.setText(_translate("Dialog", "Повод к вызову", None))
        self.cmbPrimary.setItemText(1, _translate("Dialog", "Первичный", None))
        self.cmbPrimary.setItemText(2, _translate("Dialog", "Повторный", None))
        self.cmbPrimary.setItemText(3, _translate("Dialog", "Активное посещение", None))
        self.cmbPrimary.setItemText(4, _translate("Dialog", "Перевозка", None))
        self.cmbPrimary.setItemText(5, _translate("Dialog", "Амбулаторно", None))
        self.edtNextTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.cmbResult.setWhatsThis(_translate("Dialog", "результат осмотра", None))
        self.cmbResult.setItemText(0, _translate("Dialog", "Результат", None))
        self.lblFinishServiceDate.setText(_translate("Dialog", "Оконч. обслуж.", None))
        self.lblTypeAsset.setText(_translate("Dialog", "Активное посещение", None))
        self.lblVisitsDurationValue.setToolTip(_translate("Dialog", "Общее время вызова", None))
        self.lblVisitsDurationValue.setText(_translate("Dialog", "00:00", None))
        self.lblNumberBrigade.setText(_translate("Dialog", "Номер бригады", None))
        self.lblEndDateDate.setText(_translate("Dialog", "Возвр. на станц.", None))
        self.cmbTypeAsset.setItemText(0, _translate("Dialog", "Активное посещение", None))
        self.lblTimeToFinishServiceDate.setToolTip(_translate("Dialog", "Время до оконч. обслуж.", None))
        self.lblTimeToFinishServiceDate.setText(_translate("Dialog", "00:00", None))
        self.lblTimeToEndDate.setToolTip(_translate("Dialog", "Время до возвр. на станц.", None))
        self.lblTimeToEndDate.setText(_translate("Dialog", "00:00", None))
        self.cmbPerson.setWhatsThis(_translate("Dialog", "врач отвечающий за осмотр (терапевт)", None))
        self.cmbPerson.setItemText(0, _translate("Dialog", "Врач", None))
        self.lblTimeToDepartureDate.setToolTip(_translate("Dialog", "Время до выезда", None))
        self.lblTimeToDepartureDate.setText(_translate("Dialog", "00:00", None))
        self.lblOrder_2.setText(_translate("Dialog", "Порядок", None))
        self.chkZNOFirst.setToolTip(_translate("Dialog", "ЗНО установлен впервые", None))
        self.chkZNOFirst.setText(_translate("Dialog", "ЗНО уст. впервые", None))
        self.cmbOrder.setItemText(1, _translate("Dialog", "Экстренный", None))
        self.cmbOrder.setItemText(2, _translate("Dialog", "Неотложный", None))
        self.lblGoal.setText(_translate("Dialog", "Цель", None))
        self.lblPerson.setText(_translate("Dialog", "Ответственный", None))
        self.cmbGoal.setWhatsThis(_translate("Dialog", "результат осмотра", None))
        self.chkExposeConfirmed.setText(_translate("Dialog", "Добавить к выставлению", None))
        self.chkZNOMorph.setToolTip(_translate("Dialog", "ЗНО потдверждён морфологически", None))
        self.chkZNOMorph.setText(_translate("Dialog", "ЗНО подтв. морф-ки", None))
        self.lblBegDate.setText(_translate("Dialog", "Принято", None))
        self.lblNumberCardCall.setText(_translate("Dialog", "Карта вызова №", None))
        self.lblDepartureDate.setText(_translate("Dialog", "Выезд", None))
        self.lblArrivalDate.setText(_translate("Dialog", "Прибытие", None))
        self.lblResult.setText(_translate("Dialog", "Результа&т", None))
        self.lblWhoCallOnPhone.setText(_translate("Dialog", "Кто вызывал", None))
        self.lblPrimary.setText(_translate("Dialog", "В&ызов", None))
        self.cmbNumberBrigade.setItemText(0, _translate("Dialog", "Номер бригады", None))
        self.lblNumberPhone.setText(_translate("Dialog", "С телефона", None))
        self.edtArrivalDate.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy", None))
        self.edtArrivalTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.edtPassDate.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy", None))
        self.edtPassTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.edtFinishServiceDate.setWhatsThis(_translate("Dialog", "дата окончания осмотра", None))
        self.edtFinishServiceDate.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy", None))
        self.edtFinishServiceTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.gbAddress.setTitle(_translate("Dialog", "Адрес места вызова", None))
        self.chkKLADR.setText(_translate("Dialog", "КЛАДР", None))
        self.btnLoadAddress.setText(_translate("Dialog", "...", None))
        self.lblAddressHouse.setText(_translate("Dialog", "Д&ом", None))
        self.lblAddressBuilding.setText(_translate("Dialog", "К&орп", None))
        self.lblAddressFlat.setText(_translate("Dialog", "К&в", None))
        self.edtBegDate.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy", None))
        self.edtBegTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.edtEndDate.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy", None))
        self.edtEndTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.edtDepartureDate.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy", None))
        self.edtDepartureTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.gbLittleStrangerFlag.setTitle(_translate("Dialog", "Признак новорожденного", None))
        self.lblChildNumber.setText(_translate("Dialog", "По счету в семье", None))
        self.lblChildBirthDate.setText(_translate("Dialog", "Дата рождения", None))
        self.cmbChildSex.setItemText(1, _translate("Dialog", "М", None))
        self.cmbChildSex.setItemText(2, _translate("Dialog", "Ж", None))
        self.lblChildSex.setText(_translate("Dialog", "Пол", None))
        self.chkMultipleBirths.setText(_translate("Dialog", "Многоплодные роды", None))
        self.lblBirthWeight.setText(_translate("Dialog", "Вес при рождении", None))
        self.lblTimeToPassDate.setToolTip(_translate("Dialog", "Время до передачи бригаде", None))
        self.lblTimeToPassDate.setText(_translate("Dialog", "00:00", None))
        self.lblTimeToArrivalDate.setToolTip(_translate("Dialog", "Время до прибытия", None))
        self.lblTimeToArrivalDate.setText(_translate("Dialog", "00:00", None))
        self.lblPassDate.setText(_translate("Dialog", "Передано", None))
        self.cmbDispatcher.setItemText(0, _translate("Dialog", "Диспетчер", None))
        self.edtNextDate.setWhatsThis(_translate("Dialog", "дата начала осмотра", None))
        self.edtNextDate.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy", None))
        self.cmbCauseCall.setItemText(0, _translate("Dialog", "Повод к вызову", None))
        self.chkDispByMobileTeam.setText(_translate("Dialog", "Диспансеризация(проф.осмотр) проведена МВБ", None))
        self.lblDispatcher.setText(_translate("Dialog", "Диспетчер", None))
        self.cmbContract.setWhatsThis(_translate("Dialog", "номер, дата и основание договора в рамках которого производится осмотр", None))
        self.cmbContract.setItemText(0, _translate("Dialog", "Договор", None))
        self.chkIsClosed.setText(_translate("Dialog", "Карта заполнена", None))
        self.grpActions.setTitle(_translate("Dialog", "&Обстоятельства вызова", None))
        self.cmbPlaceReceptionCall.setItemText(0, _translate("Dialog", "Место получения вызова", None))
        self.lblDisease.setText(_translate("Dialog", "Заболевание", None))
        self.lblDeath.setText(_translate("Dialog", "Смерть", None))
        self.cmbDeath.setItemText(0, _translate("Dialog", "Смерть", None))
        self.lblMethodTransportation.setText(_translate("Dialog", "Способ транспортировки", None))
        self.cmbMethodTransportation.setItemText(0, _translate("Dialog", "Способ транспортировки", None))
        self.lblReceivedCall.setText(_translate("Dialog", "Вызов получен", None))
        self.cmbReceivedCall.setItemText(0, _translate("Dialog", "Вызов получен", None))
        self.lblBirth.setText(_translate("Dialog", "Роды", None))
        self.lblEbriety.setText(_translate("Dialog", "Опьянение", None))
        self.cmbEbriety.setItemText(0, _translate("Dialog", "Опьянение", None))
        self.lblTransferredTransportation.setText(_translate("Dialog", "Транспортировку перенес", None))
        self.cmbTransferredTransportation.setItemText(0, _translate("Dialog", "Транспортировку перенес", None))
        self.lblReasondDelays.setText(_translate("Dialog", "Причина задержки", None))
        self.cmbReasondDelays.setItemText(0, _translate("Dialog", "Причина задержки", None))
        self.lblPregnancyFailure.setText(_translate("Dialog", "Патология берем.", None))
        self.lblDiseased.setText(_translate("Dialog", "Больной", None))
        self.cmbDiseased.setItemText(0, _translate("Dialog", "Больной", None))
        self.lblResultCircumstanceCall.setText(_translate("Dialog", "Результат", None))
        self.cmbResultCircumstanceCall.setItemText(0, _translate("Dialog", "Результат", None))
        self.lblAccident.setText(_translate("Dialog", "Несчастный случай", None))
        self.cmbAccident.setItemText(0, _translate("Dialog", "Несчастный случай", None))
        self.lblPlaceCall.setText(_translate("Dialog", "Место вызова", None))
        self.cmbPlaceCall.setItemText(0, _translate("Dialog", "Место вызова", None))
        self.lblPlaceReceptionCall.setText(_translate("Dialog", "Место получения вызова", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabToken), _translate("Dialog", "Стат.&учёт", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMes), _translate("Dialog", "Стандарт", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStatus), _translate("Dialog", "&Статус", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDiagnostic), _translate("Dialog", "&Диагностика", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCure), _translate("Dialog", "&Лечение", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMisc), _translate("Dialog", "&Мероприятия", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAmbCard), _translate("Dialog", "Мед.&карта", None))
        self.grpTempInvalid.setTitle(_translate("Dialog", "&ВУТ", None))
        self.tabTempInvalidAndAegrotat.setTabText(self.tabTempInvalidAndAegrotat.indexOf(self.tabTempInvalid), _translate("Dialog", "Листок &нетрудоспособности", None))
        self.grpDisability.setTitle(_translate("Dialog", "&Инвалидность", None))
        self.tabTempInvalidAndAegrotat.setTabText(self.tabTempInvalidAndAegrotat.indexOf(self.tabTempInvalidS), _translate("Dialog", "Инвалидность", None))
        self.grpVitalRestriction.setTitle(_translate("Dialog", "&Ограничения жизнедеятельности", None))
        self.tabTempInvalidAndAegrotat.setTabText(self.tabTempInvalidAndAegrotat.indexOf(self.tabTempinvalidDisability), _translate("Dialog", "Ограничения жизнедеятельности", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTempInvalidEtc), _translate("Dialog", "Т&рудоспособность", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCash), _translate("Dialog", "Оплата", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNotes), _translate("Dialog", "Приме&чания", None))
        self.statusBar.setToolTip(_translate("Dialog", "A status bar", None))
        self.statusBar.setWhatsThis(_translate("Dialog", "A status bar.", None))

from Events.ActionsPage import CActionsPage
from Events.AmbCardPage import CAmbCardPage
from Events.EventCashPage import CEventCashPage
from Events.EventMesPage import CFastEventMesPage
from Events.EventNotesPage import CEventNotesPage
from Events.TempInvalid import CTempInvalid
from KLADR.kladrComboxes import CStreetComboBox
from Orgs.OrgComboBox import CContractComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
from library.TextBrowser import CTextBrowser
from library.crbcombobox import CRBComboBox
