# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\svn-s11\s11\HospitalBeds\HospitalBedFindComboBoxPopup.ui'
#
# Created: Fri Jun 15 12:16:48 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_HospitalBedFindComboBoxPopup(object):
    def setupUi(self, HospitalBedFindComboBoxPopup):
        HospitalBedFindComboBoxPopup.setObjectName(_fromUtf8("HospitalBedFindComboBoxPopup"))
        HospitalBedFindComboBoxPopup.resize(403, 232)
        self.gridlayout = QtGui.QGridLayout(HospitalBedFindComboBoxPopup)
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(0)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.tabWidget = QtGui.QTabWidget(HospitalBedFindComboBoxPopup)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabHospitalBedFind = QtGui.QWidget()
        self.tabHospitalBedFind.setObjectName(_fromUtf8("tabHospitalBedFind"))
        self.vboxlayout = QtGui.QVBoxLayout(self.tabHospitalBedFind)
        self.vboxlayout.setSpacing(4)
        self.vboxlayout.setMargin(4)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.tblHospitalBedFind = CHospitalBedPopupView(self.tabHospitalBedFind)
        self.tblHospitalBedFind.setObjectName(_fromUtf8("tblHospitalBedFind"))
        self.vboxlayout.addWidget(self.tblHospitalBedFind)
        self.tabWidget.addTab(self.tabHospitalBedFind, _fromUtf8(""))
        self.tabSearch = QtGui.QWidget()
        self.tabSearch.setObjectName(_fromUtf8("tabSearch"))
        self.gridLayout = QtGui.QGridLayout(self.tabSearch)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblOrgStructureBed = QtGui.QLabel(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgStructureBed.sizePolicy().hasHeightForWidth())
        self.lblOrgStructureBed.setSizePolicy(sizePolicy)
        self.lblOrgStructureBed.setObjectName(_fromUtf8("lblOrgStructureBed"))
        self.gridLayout.addWidget(self.lblOrgStructureBed, 0, 0, 1, 1)
        self.cmbOrgStructureBed = COrgStructureComboBox(self.tabSearch)
        self.cmbOrgStructureBed.setObjectName(_fromUtf8("cmbOrgStructureBed"))
        self.gridLayout.addWidget(self.cmbOrgStructureBed, 0, 1, 1, 6)
        self.lblSexBed = QtGui.QLabel(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSexBed.sizePolicy().hasHeightForWidth())
        self.lblSexBed.setSizePolicy(sizePolicy)
        self.lblSexBed.setObjectName(_fromUtf8("lblSexBed"))
        self.gridLayout.addWidget(self.lblSexBed, 1, 0, 1, 1)
        self.cmbSexBed = QtGui.QComboBox(self.tabSearch)
        self.cmbSexBed.setObjectName(_fromUtf8("cmbSexBed"))
        self.cmbSexBed.addItem(_fromUtf8(""))
        self.cmbSexBed.addItem(_fromUtf8(""))
        self.cmbSexBed.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSexBed, 1, 1, 1, 1)
        self.lblAgeBed = QtGui.QLabel(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAgeBed.sizePolicy().hasHeightForWidth())
        self.lblAgeBed.setSizePolicy(sizePolicy)
        self.lblAgeBed.setObjectName(_fromUtf8("lblAgeBed"))
        self.gridLayout.addWidget(self.lblAgeBed, 1, 2, 1, 1)
        self.edtAgeForBed = QtGui.QSpinBox(self.tabSearch)
        self.edtAgeForBed.setMaximum(150)
        self.edtAgeForBed.setObjectName(_fromUtf8("edtAgeForBed"))
        self.gridLayout.addWidget(self.edtAgeForBed, 1, 3, 1, 1)
        self.lblAgeTo = QtGui.QLabel(self.tabSearch)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self.gridLayout.addWidget(self.lblAgeTo, 1, 4, 1, 1)
        self.edtAgeToBed = QtGui.QSpinBox(self.tabSearch)
        self.edtAgeToBed.setObjectName(_fromUtf8("edtAgeToBed"))
        self.gridLayout.addWidget(self.edtAgeToBed, 1, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(33, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 6, 1, 1)
        self.lblProfileBed = QtGui.QLabel(self.tabSearch)
        self.lblProfileBed.setObjectName(_fromUtf8("lblProfileBed"))
        self.gridLayout.addWidget(self.lblProfileBed, 2, 0, 1, 1)
        self.cmbProfileBed = CRBComboBox(self.tabSearch)
        self.cmbProfileBed.setObjectName(_fromUtf8("cmbProfileBed"))
        self.gridLayout.addWidget(self.cmbProfileBed, 2, 1, 1, 6)
        self.lblTypeBed = QtGui.QLabel(self.tabSearch)
        self.lblTypeBed.setObjectName(_fromUtf8("lblTypeBed"))
        self.gridLayout.addWidget(self.lblTypeBed, 3, 0, 1, 1)
        self.cmbTypeBed = CRBComboBox(self.tabSearch)
        self.cmbTypeBed.setObjectName(_fromUtf8("cmbTypeBed"))
        self.gridLayout.addWidget(self.cmbTypeBed, 3, 1, 1, 6)
        self.lblIsPermanentBed = QtGui.QLabel(self.tabSearch)
        self.lblIsPermanentBed.setObjectName(_fromUtf8("lblIsPermanentBed"))
        self.gridLayout.addWidget(self.lblIsPermanentBed, 4, 0, 1, 1)
        self.cmbIsPermanentBed = QtGui.QComboBox(self.tabSearch)
        self.cmbIsPermanentBed.setObjectName(_fromUtf8("cmbIsPermanentBed"))
        self.cmbIsPermanentBed.addItem(_fromUtf8(""))
        self.cmbIsPermanentBed.addItem(_fromUtf8(""))
        self.cmbIsPermanentBed.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbIsPermanentBed, 4, 1, 1, 6)
        spacerItem1 = QtGui.QSpacerItem(231, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 3)
        self.buttonBox = QtGui.QDialogButtonBox(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 5, 3, 1, 4)
        self.tabWidget.addTab(self.tabSearch, _fromUtf8(""))
        self.gridlayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(HospitalBedFindComboBoxPopup)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HospitalBedFindComboBoxPopup)
        HospitalBedFindComboBoxPopup.setTabOrder(self.tabWidget, self.cmbOrgStructureBed)
        HospitalBedFindComboBoxPopup.setTabOrder(self.cmbOrgStructureBed, self.cmbSexBed)
        HospitalBedFindComboBoxPopup.setTabOrder(self.cmbSexBed, self.edtAgeForBed)
        HospitalBedFindComboBoxPopup.setTabOrder(self.edtAgeForBed, self.edtAgeToBed)
        HospitalBedFindComboBoxPopup.setTabOrder(self.edtAgeToBed, self.cmbProfileBed)
        HospitalBedFindComboBoxPopup.setTabOrder(self.cmbProfileBed, self.cmbTypeBed)
        HospitalBedFindComboBoxPopup.setTabOrder(self.cmbTypeBed, self.cmbIsPermanentBed)
        HospitalBedFindComboBoxPopup.setTabOrder(self.cmbIsPermanentBed, self.buttonBox)
        HospitalBedFindComboBoxPopup.setTabOrder(self.buttonBox, self.tblHospitalBedFind)

    def retranslateUi(self, HospitalBedFindComboBoxPopup):
        HospitalBedFindComboBoxPopup.setWindowTitle(QtGui.QApplication.translate("HospitalBedFindComboBoxPopup", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHospitalBedFind), QtGui.QApplication.translate("HospitalBedFindComboBoxPopup", "Результат поиска", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOrgStructureBed.setText(QtGui.QApplication.translate("HospitalBedFindComboBoxPopup", "Подразделение", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSexBed.setText(QtGui.QApplication.translate("HospitalBedFindComboBoxPopup", "Пол", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSexBed.setItemText(0, QtGui.QApplication.translate("HospitalBedFindComboBoxPopup", "нет", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSexBed.setItemText(1, QtGui.QApplication.translate("HospitalBedFindComboBoxPopup", "М", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSexBed.setItemText(2, QtGui.QApplication.translate("HospitalBedFindComboBoxPopup", "Ж", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAgeBed.setText(QtGui.QApplication.translate("HospitalBedFindComboBoxPopup", "Возраст от", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAgeTo.setText(QtGui.QApplication.translate("HospitalBedFindComboBoxPopup", "до", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProfileBed.setText(QtGui.QApplication.translate("HospitalBedFindComboBoxPopup", "Профиль", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTypeBed.setText(QtGui.QApplication.translate("HospitalBedFindComboBoxPopup", "Тип", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIsPermanentBed.setText(QtGui.QApplication.translate("HospitalBedFindComboBoxPopup", "Штат", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbIsPermanentBed.setItemText(0, QtGui.QApplication.translate("HospitalBedFindComboBoxPopup", "Все", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbIsPermanentBed.setItemText(1, QtGui.QApplication.translate("HospitalBedFindComboBoxPopup", "Нет", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbIsPermanentBed.setItemText(2, QtGui.QApplication.translate("HospitalBedFindComboBoxPopup", "Да", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), QtGui.QApplication.translate("HospitalBedFindComboBoxPopup", "&Поиск", None, QtGui.QApplication.UnicodeUTF8))

from library.crbcombobox import CRBComboBox
from HospitalBeds.HospitalBedComboBox import CHospitalBedPopupView
from Orgs.OrgStructComboBoxes import COrgStructureComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    HospitalBedFindComboBoxPopup = QtGui.QWidget()
    ui = Ui_HospitalBedFindComboBoxPopup()
    ui.setupUi(HospitalBedFindComboBoxPopup)
    HospitalBedFindComboBoxPopup.show()
    sys.exit(app.exec_())

