# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AttachExchangeDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AttachExchangeDialog(object):
    def setupUi(self, AttachExchangeDialog):
        AttachExchangeDialog.setObjectName(_fromUtf8("AttachExchangeDialog"))
        AttachExchangeDialog.resize(968, 632)
        self.gridLayout_14 = QtGui.QGridLayout(AttachExchangeDialog)
        self.gridLayout_14.setMargin(6)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.tabClientDeAttachQueryLog = QtGui.QTabWidget(AttachExchangeDialog)
        self.tabClientDeAttachQueryLog.setObjectName(_fromUtf8("tabClientDeAttachQueryLog"))
        self.tabMonitoring = QtGui.QWidget()
        self.tabMonitoring.setObjectName(_fromUtf8("tabMonitoring"))
        self.gridLayout = QtGui.QGridLayout(self.tabMonitoring)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.clientAttachMonitoring = CClientAttachMonitoring(self.tabMonitoring)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientAttachMonitoring.sizePolicy().hasHeightForWidth())
        self.clientAttachMonitoring.setSizePolicy(sizePolicy)
        self.clientAttachMonitoring.setObjectName(_fromUtf8("clientAttachMonitoring"))
        self.gridLayout.addWidget(self.clientAttachMonitoring, 0, 0, 1, 1)
        self.gridMoveFromOneToOther = QtGui.QGridLayout()
        self.gridMoveFromOneToOther.setObjectName(_fromUtf8("gridMoveFromOneToOther"))
        self.lblMovingSex = QtGui.QLabel(self.tabMonitoring)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMovingSex.sizePolicy().hasHeightForWidth())
        self.lblMovingSex.setSizePolicy(sizePolicy)
        self.lblMovingSex.setObjectName(_fromUtf8("lblMovingSex"))
        self.gridMoveFromOneToOther.addWidget(self.lblMovingSex, 0, 0, 1, 1)
        self.cmbMovingAge = QtGui.QComboBox(self.tabMonitoring)
        self.cmbMovingAge.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMovingAge.sizePolicy().hasHeightForWidth())
        self.cmbMovingAge.setSizePolicy(sizePolicy)
        self.cmbMovingAge.setObjectName(_fromUtf8("cmbMovingAge"))
        self.cmbMovingAge.addItem(_fromUtf8(""))
        self.cmbMovingAge.addItem(_fromUtf8(""))
        self.cmbMovingAge.addItem(_fromUtf8(""))
        self.gridMoveFromOneToOther.addWidget(self.cmbMovingAge, 1, 1, 1, 1)
        self.edtMovingCount = QtGui.QSpinBox(self.tabMonitoring)
        self.edtMovingCount.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMovingCount.sizePolicy().hasHeightForWidth())
        self.edtMovingCount.setSizePolicy(sizePolicy)
        self.edtMovingCount.setMaximum(100000)
        self.edtMovingCount.setObjectName(_fromUtf8("edtMovingCount"))
        self.gridMoveFromOneToOther.addWidget(self.edtMovingCount, 2, 1, 1, 1)
        self.lblMovingCount = QtGui.QLabel(self.tabMonitoring)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMovingCount.sizePolicy().hasHeightForWidth())
        self.lblMovingCount.setSizePolicy(sizePolicy)
        self.lblMovingCount.setObjectName(_fromUtf8("lblMovingCount"))
        self.gridMoveFromOneToOther.addWidget(self.lblMovingCount, 2, 0, 1, 1)
        self.cmbMovingSex = QtGui.QComboBox(self.tabMonitoring)
        self.cmbMovingSex.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMovingSex.sizePolicy().hasHeightForWidth())
        self.cmbMovingSex.setSizePolicy(sizePolicy)
        self.cmbMovingSex.setObjectName(_fromUtf8("cmbMovingSex"))
        self.cmbMovingSex.addItem(_fromUtf8(""))
        self.cmbMovingSex.addItem(_fromUtf8(""))
        self.cmbMovingSex.addItem(_fromUtf8(""))
        self.gridMoveFromOneToOther.addWidget(self.cmbMovingSex, 0, 1, 1, 1)
        self.lblMovingAge = QtGui.QLabel(self.tabMonitoring)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMovingAge.sizePolicy().hasHeightForWidth())
        self.lblMovingAge.setSizePolicy(sizePolicy)
        self.lblMovingAge.setObjectName(_fromUtf8("lblMovingAge"))
        self.gridMoveFromOneToOther.addWidget(self.lblMovingAge, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblMovingFrom = QtGui.QLabel(self.tabMonitoring)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMovingFrom.sizePolicy().hasHeightForWidth())
        self.lblMovingFrom.setSizePolicy(sizePolicy)
        self.lblMovingFrom.setObjectName(_fromUtf8("lblMovingFrom"))
        self.horizontalLayout_3.addWidget(self.lblMovingFrom)
        self.cmbMovingFromOrgStructure = COrgStructureComboBox(self.tabMonitoring)
        self.cmbMovingFromOrgStructure.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMovingFromOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbMovingFromOrgStructure.setSizePolicy(sizePolicy)
        self.cmbMovingFromOrgStructure.setObjectName(_fromUtf8("cmbMovingFromOrgStructure"))
        self.horizontalLayout_3.addWidget(self.cmbMovingFromOrgStructure)
        self.lblMovingTo = QtGui.QLabel(self.tabMonitoring)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMovingTo.sizePolicy().hasHeightForWidth())
        self.lblMovingTo.setSizePolicy(sizePolicy)
        self.lblMovingTo.setObjectName(_fromUtf8("lblMovingTo"))
        self.horizontalLayout_3.addWidget(self.lblMovingTo)
        self.cmbMovingToOrgStructure = COrgStructureComboBox(self.tabMonitoring)
        self.cmbMovingToOrgStructure.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMovingToOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbMovingToOrgStructure.setSizePolicy(sizePolicy)
        self.cmbMovingToOrgStructure.setObjectName(_fromUtf8("cmbMovingToOrgStructure"))
        self.horizontalLayout_3.addWidget(self.cmbMovingToOrgStructure)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridMoveFromOneToOther.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridMoveFromOneToOther, 1, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.btnMoveAttaches = QtGui.QPushButton(self.tabMonitoring)
        self.btnMoveAttaches.setObjectName(_fromUtf8("btnMoveAttaches"))
        self.horizontalLayout_13.addWidget(self.btnMoveAttaches)
        self.btnPrintReport = QtGui.QPushButton(self.tabMonitoring)
        self.btnPrintReport.setObjectName(_fromUtf8("btnPrintReport"))
        self.horizontalLayout_13.addWidget(self.btnPrintReport)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_13, 2, 0, 1, 1)
        self.tabClientDeAttachQueryLog.addTab(self.tabMonitoring, _fromUtf8(""))
        self.tabClientAttach = QtGui.QWidget()
        self.tabClientAttach.setObjectName(_fromUtf8("tabClientAttach"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabClientAttach)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnLoadClientAttach = QtGui.QPushButton(self.tabClientAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoadClientAttach.sizePolicy().hasHeightForWidth())
        self.btnLoadClientAttach.setSizePolicy(sizePolicy)
        self.btnLoadClientAttach.setObjectName(_fromUtf8("btnLoadClientAttach"))
        self.horizontalLayout.addWidget(self.btnLoadClientAttach)
        self.btnSelectAllClientAttach = QtGui.QPushButton(self.tabClientAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectAllClientAttach.sizePolicy().hasHeightForWidth())
        self.btnSelectAllClientAttach.setSizePolicy(sizePolicy)
        self.btnSelectAllClientAttach.setObjectName(_fromUtf8("btnSelectAllClientAttach"))
        self.horizontalLayout.addWidget(self.btnSelectAllClientAttach)
        self.btnDeselectAllClientAttach = QtGui.QPushButton(self.tabClientAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeselectAllClientAttach.sizePolicy().hasHeightForWidth())
        self.btnDeselectAllClientAttach.setSizePolicy(sizePolicy)
        self.btnDeselectAllClientAttach.setObjectName(_fromUtf8("btnDeselectAllClientAttach"))
        self.horizontalLayout.addWidget(self.btnDeselectAllClientAttach)
        self.btnSyncClientAttach = QtGui.QPushButton(self.tabClientAttach)
        self.btnSyncClientAttach.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSyncClientAttach.sizePolicy().hasHeightForWidth())
        self.btnSyncClientAttach.setSizePolicy(sizePolicy)
        self.btnSyncClientAttach.setObjectName(_fromUtf8("btnSyncClientAttach"))
        self.horizontalLayout.addWidget(self.btnSyncClientAttach)
        self.gridLayout_2.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblStatusClientAttach = QtGui.QLabel(self.tabClientAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStatusClientAttach.sizePolicy().hasHeightForWidth())
        self.lblStatusClientAttach.setSizePolicy(sizePolicy)
        self.lblStatusClientAttach.setObjectName(_fromUtf8("lblStatusClientAttach"))
        self.horizontalLayout_2.addWidget(self.lblStatusClientAttach)
        spacerItem2 = QtGui.QSpacerItem(524, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btnCloseClientAttach = QtGui.QPushButton(self.tabClientAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCloseClientAttach.sizePolicy().hasHeightForWidth())
        self.btnCloseClientAttach.setSizePolicy(sizePolicy)
        self.btnCloseClientAttach.setObjectName(_fromUtf8("btnCloseClientAttach"))
        self.horizontalLayout_2.addWidget(self.btnCloseClientAttach)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 6, 0, 1, 1)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.cmbInsuranceAreaClientAttach = CEnumComboBox(self.tabClientAttach)
        self.cmbInsuranceAreaClientAttach.setObjectName(_fromUtf8("cmbInsuranceAreaClientAttach"))
        self.gridLayout_13.addWidget(self.cmbInsuranceAreaClientAttach, 0, 6, 1, 1)
        self.edtBegDateClientAttach = CDateEdit(self.tabClientAttach)
        self.edtBegDateClientAttach.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDateClientAttach.sizePolicy().hasHeightForWidth())
        self.edtBegDateClientAttach.setSizePolicy(sizePolicy)
        self.edtBegDateClientAttach.setObjectName(_fromUtf8("edtBegDateClientAttach"))
        self.gridLayout_13.addWidget(self.edtBegDateClientAttach, 1, 2, 1, 1)
        self.lblOrgStructureClientAttach = QtGui.QLabel(self.tabClientAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgStructureClientAttach.sizePolicy().hasHeightForWidth())
        self.lblOrgStructureClientAttach.setSizePolicy(sizePolicy)
        self.lblOrgStructureClientAttach.setObjectName(_fromUtf8("lblOrgStructureClientAttach"))
        self.gridLayout_13.addWidget(self.lblOrgStructureClientAttach, 0, 0, 1, 1)
        self.lblDateClientAttach = QtGui.QLabel(self.tabClientAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDateClientAttach.sizePolicy().hasHeightForWidth())
        self.lblDateClientAttach.setSizePolicy(sizePolicy)
        self.lblDateClientAttach.setObjectName(_fromUtf8("lblDateClientAttach"))
        self.gridLayout_13.addWidget(self.lblDateClientAttach, 1, 0, 1, 1)
        self.lblAttachTypeClientAttach = QtGui.QLabel(self.tabClientAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAttachTypeClientAttach.sizePolicy().hasHeightForWidth())
        self.lblAttachTypeClientAttach.setSizePolicy(sizePolicy)
        self.lblAttachTypeClientAttach.setObjectName(_fromUtf8("lblAttachTypeClientAttach"))
        self.gridLayout_13.addWidget(self.lblAttachTypeClientAttach, 2, 0, 1, 1)
        self.chkEndDateClientAttach = QtGui.QCheckBox(self.tabClientAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkEndDateClientAttach.sizePolicy().hasHeightForWidth())
        self.chkEndDateClientAttach.setSizePolicy(sizePolicy)
        self.chkEndDateClientAttach.setChecked(True)
        self.chkEndDateClientAttach.setObjectName(_fromUtf8("chkEndDateClientAttach"))
        self.gridLayout_13.addWidget(self.chkEndDateClientAttach, 1, 3, 1, 1)
        self.cmbOrgStructureClientAttach = COrgStructureComboBox(self.tabClientAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrgStructureClientAttach.sizePolicy().hasHeightForWidth())
        self.cmbOrgStructureClientAttach.setSizePolicy(sizePolicy)
        self.cmbOrgStructureClientAttach.setObjectName(_fromUtf8("cmbOrgStructureClientAttach"))
        self.gridLayout_13.addWidget(self.cmbOrgStructureClientAttach, 0, 1, 1, 4)
        self.edtEndDateClientAttach = CDateEdit(self.tabClientAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDateClientAttach.sizePolicy().hasHeightForWidth())
        self.edtEndDateClientAttach.setSizePolicy(sizePolicy)
        self.edtEndDateClientAttach.setObjectName(_fromUtf8("edtEndDateClientAttach"))
        self.gridLayout_13.addWidget(self.edtEndDateClientAttach, 1, 4, 1, 1)
        self.chkBegDateClientAttach = QtGui.QCheckBox(self.tabClientAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkBegDateClientAttach.sizePolicy().hasHeightForWidth())
        self.chkBegDateClientAttach.setSizePolicy(sizePolicy)
        self.chkBegDateClientAttach.setChecked(False)
        self.chkBegDateClientAttach.setObjectName(_fromUtf8("chkBegDateClientAttach"))
        self.gridLayout_13.addWidget(self.chkBegDateClientAttach, 1, 1, 1, 1)
        self.cmbAttachTypeClientAttach = CEnumComboBox(self.tabClientAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAttachTypeClientAttach.sizePolicy().hasHeightForWidth())
        self.cmbAttachTypeClientAttach.setSizePolicy(sizePolicy)
        self.cmbAttachTypeClientAttach.setObjectName(_fromUtf8("cmbAttachTypeClientAttach"))
        self.gridLayout_13.addWidget(self.cmbAttachTypeClientAttach, 2, 1, 1, 4)
        self.lblInsuranceAreaClientAttach = QtGui.QLabel(self.tabClientAttach)
        self.lblInsuranceAreaClientAttach.setObjectName(_fromUtf8("lblInsuranceAreaClientAttach"))
        self.gridLayout_13.addWidget(self.lblInsuranceAreaClientAttach, 0, 5, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem3, 2, 7, 1, 1)
        self.chkChangeSection = QtGui.QCheckBox(self.tabClientAttach)
        self.chkChangeSection.setObjectName(_fromUtf8("chkChangeSection"))
        self.gridLayout_13.addWidget(self.chkChangeSection, 1, 5, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_13, 1, 0, 1, 1)
        self.tblClientAttach = CInDocTableView(self.tabClientAttach)
        self.tblClientAttach.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tblClientAttach.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblClientAttach.setObjectName(_fromUtf8("tblClientAttach"))
        self.gridLayout_2.addWidget(self.tblClientAttach, 0, 0, 1, 1)
        self.tabClientDeAttachQueryLog.addTab(self.tabClientAttach, _fromUtf8(""))
        self.tabPersonAttach = QtGui.QWidget()
        self.tabPersonAttach.setObjectName(_fromUtf8("tabPersonAttach"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabPersonAttach)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.edtBegDatePersonAttach = CDateEdit(self.tabPersonAttach)
        self.edtBegDatePersonAttach.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDatePersonAttach.sizePolicy().hasHeightForWidth())
        self.edtBegDatePersonAttach.setSizePolicy(sizePolicy)
        self.edtBegDatePersonAttach.setObjectName(_fromUtf8("edtBegDatePersonAttach"))
        self.gridLayout_5.addWidget(self.edtBegDatePersonAttach, 1, 3, 1, 1)
        self.lblDatePersonAttach = QtGui.QLabel(self.tabPersonAttach)
        self.lblDatePersonAttach.setObjectName(_fromUtf8("lblDatePersonAttach"))
        self.gridLayout_5.addWidget(self.lblDatePersonAttach, 1, 0, 1, 1)
        self.lblOrgStructurePersonAttach = QtGui.QLabel(self.tabPersonAttach)
        self.lblOrgStructurePersonAttach.setObjectName(_fromUtf8("lblOrgStructurePersonAttach"))
        self.gridLayout_5.addWidget(self.lblOrgStructurePersonAttach, 0, 0, 1, 1)
        self.edtEndDatePersonAttach = CDateEdit(self.tabPersonAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDatePersonAttach.sizePolicy().hasHeightForWidth())
        self.edtEndDatePersonAttach.setSizePolicy(sizePolicy)
        self.edtEndDatePersonAttach.setObjectName(_fromUtf8("edtEndDatePersonAttach"))
        self.gridLayout_5.addWidget(self.edtEndDatePersonAttach, 1, 5, 1, 1)
        self.chkBegDatePersonAttach = QtGui.QCheckBox(self.tabPersonAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkBegDatePersonAttach.sizePolicy().hasHeightForWidth())
        self.chkBegDatePersonAttach.setSizePolicy(sizePolicy)
        self.chkBegDatePersonAttach.setChecked(False)
        self.chkBegDatePersonAttach.setObjectName(_fromUtf8("chkBegDatePersonAttach"))
        self.gridLayout_5.addWidget(self.chkBegDatePersonAttach, 1, 1, 1, 2)
        self.chkEndDatePersonAttach = QtGui.QCheckBox(self.tabPersonAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkEndDatePersonAttach.sizePolicy().hasHeightForWidth())
        self.chkEndDatePersonAttach.setSizePolicy(sizePolicy)
        self.chkEndDatePersonAttach.setChecked(True)
        self.chkEndDatePersonAttach.setObjectName(_fromUtf8("chkEndDatePersonAttach"))
        self.gridLayout_5.addWidget(self.chkEndDatePersonAttach, 1, 4, 1, 1)
        self.cmbOrgStructurePersonAttach = COrgStructureComboBox(self.tabPersonAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrgStructurePersonAttach.sizePolicy().hasHeightForWidth())
        self.cmbOrgStructurePersonAttach.setSizePolicy(sizePolicy)
        self.cmbOrgStructurePersonAttach.setObjectName(_fromUtf8("cmbOrgStructurePersonAttach"))
        self.gridLayout_5.addWidget(self.cmbOrgStructurePersonAttach, 0, 1, 1, 5)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 6, 2, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.btnLoadPersonAttach = QtGui.QPushButton(self.tabPersonAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoadPersonAttach.sizePolicy().hasHeightForWidth())
        self.btnLoadPersonAttach.setSizePolicy(sizePolicy)
        self.btnLoadPersonAttach.setObjectName(_fromUtf8("btnLoadPersonAttach"))
        self.horizontalLayout_9.addWidget(self.btnLoadPersonAttach)
        self.btnSelectAllPersonAttach = QtGui.QPushButton(self.tabPersonAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectAllPersonAttach.sizePolicy().hasHeightForWidth())
        self.btnSelectAllPersonAttach.setSizePolicy(sizePolicy)
        self.btnSelectAllPersonAttach.setObjectName(_fromUtf8("btnSelectAllPersonAttach"))
        self.horizontalLayout_9.addWidget(self.btnSelectAllPersonAttach)
        self.btnDeselectAllPersonAttach = QtGui.QPushButton(self.tabPersonAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeselectAllPersonAttach.sizePolicy().hasHeightForWidth())
        self.btnDeselectAllPersonAttach.setSizePolicy(sizePolicy)
        self.btnDeselectAllPersonAttach.setObjectName(_fromUtf8("btnDeselectAllPersonAttach"))
        self.horizontalLayout_9.addWidget(self.btnDeselectAllPersonAttach)
        self.btnSyncPersonAttach = QtGui.QPushButton(self.tabPersonAttach)
        self.btnSyncPersonAttach.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSyncPersonAttach.sizePolicy().hasHeightForWidth())
        self.btnSyncPersonAttach.setSizePolicy(sizePolicy)
        self.btnSyncPersonAttach.setObjectName(_fromUtf8("btnSyncPersonAttach"))
        self.horizontalLayout_9.addWidget(self.btnSyncPersonAttach)
        self.gridLayout_6.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        self.tblPersonAttach = CInDocTableView(self.tabPersonAttach)
        self.tblPersonAttach.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tblPersonAttach.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblPersonAttach.setObjectName(_fromUtf8("tblPersonAttach"))
        self.gridLayout_6.addWidget(self.tblPersonAttach, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.lblStatusPersonAttach = QtGui.QLabel(self.tabPersonAttach)
        self.lblStatusPersonAttach.setObjectName(_fromUtf8("lblStatusPersonAttach"))
        self.horizontalLayout_10.addWidget(self.lblStatusPersonAttach)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.btnClosePersonAttach = QtGui.QPushButton(self.tabPersonAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClosePersonAttach.sizePolicy().hasHeightForWidth())
        self.btnClosePersonAttach.setSizePolicy(sizePolicy)
        self.btnClosePersonAttach.setObjectName(_fromUtf8("btnClosePersonAttach"))
        self.horizontalLayout_10.addWidget(self.btnClosePersonAttach)
        self.gridLayout_6.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.tabClientDeAttachQueryLog.addTab(self.tabPersonAttach, _fromUtf8(""))
        self.tabSync = QtGui.QWidget()
        self.tabSync.setObjectName(_fromUtf8("tabSync"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabSync)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.groupBox_2 = QtGui.QGroupBox(self.tabSync)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btnLoadAttachedClientInfo = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoadAttachedClientInfo.sizePolicy().hasHeightForWidth())
        self.btnLoadAttachedClientInfo.setSizePolicy(sizePolicy)
        self.btnLoadAttachedClientInfo.setObjectName(_fromUtf8("btnLoadAttachedClientInfo"))
        self.horizontalLayout_6.addWidget(self.btnLoadAttachedClientInfo)
        self.btnSelectAllAttachedClientInfo = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectAllAttachedClientInfo.sizePolicy().hasHeightForWidth())
        self.btnSelectAllAttachedClientInfo.setSizePolicy(sizePolicy)
        self.btnSelectAllAttachedClientInfo.setObjectName(_fromUtf8("btnSelectAllAttachedClientInfo"))
        self.horizontalLayout_6.addWidget(self.btnSelectAllAttachedClientInfo)
        self.btnDeselectAllAttachedClientInfo = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeselectAllAttachedClientInfo.sizePolicy().hasHeightForWidth())
        self.btnDeselectAllAttachedClientInfo.setSizePolicy(sizePolicy)
        self.btnDeselectAllAttachedClientInfo.setObjectName(_fromUtf8("btnDeselectAllAttachedClientInfo"))
        self.horizontalLayout_6.addWidget(self.btnDeselectAllAttachedClientInfo)
        self.btnImportAttachedClientInfo = QtGui.QPushButton(self.groupBox_2)
        self.btnImportAttachedClientInfo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnImportAttachedClientInfo.sizePolicy().hasHeightForWidth())
        self.btnImportAttachedClientInfo.setSizePolicy(sizePolicy)
        self.btnImportAttachedClientInfo.setObjectName(_fromUtf8("btnImportAttachedClientInfo"))
        self.horizontalLayout_6.addWidget(self.btnImportAttachedClientInfo)
        self.btnSaveAttachedClientInfo = QtGui.QPushButton(self.groupBox_2)
        self.btnSaveAttachedClientInfo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSaveAttachedClientInfo.sizePolicy().hasHeightForWidth())
        self.btnSaveAttachedClientInfo.setSizePolicy(sizePolicy)
        self.btnSaveAttachedClientInfo.setObjectName(_fromUtf8("btnSaveAttachedClientInfo"))
        self.horizontalLayout_6.addWidget(self.btnSaveAttachedClientInfo)
        self.gridLayout_12.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lblClientFound = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblClientFound.sizePolicy().hasHeightForWidth())
        self.lblClientFound.setSizePolicy(sizePolicy)
        self.lblClientFound.setObjectName(_fromUtf8("lblClientFound"))
        self.gridLayout_8.addWidget(self.lblClientFound, 0, 5, 1, 1)
        self.cmbAttachTypeSync = CEnumComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAttachTypeSync.sizePolicy().hasHeightForWidth())
        self.cmbAttachTypeSync.setSizePolicy(sizePolicy)
        self.cmbAttachTypeSync.setObjectName(_fromUtf8("cmbAttachTypeSync"))
        self.gridLayout_8.addWidget(self.cmbAttachTypeSync, 1, 1, 1, 4)
        self.cmbOrgStructureSync = COrgStructureComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrgStructureSync.sizePolicy().hasHeightForWidth())
        self.cmbOrgStructureSync.setSizePolicy(sizePolicy)
        self.cmbOrgStructureSync.setObjectName(_fromUtf8("cmbOrgStructureSync"))
        self.gridLayout_8.addWidget(self.cmbOrgStructureSync, 0, 1, 1, 4)
        self.lblAttachTypeSync = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAttachTypeSync.sizePolicy().hasHeightForWidth())
        self.lblAttachTypeSync.setSizePolicy(sizePolicy)
        self.lblAttachTypeSync.setObjectName(_fromUtf8("lblAttachTypeSync"))
        self.gridLayout_8.addWidget(self.lblAttachTypeSync, 1, 0, 1, 1)
        self.chkEndDateFromSync = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkEndDateFromSync.sizePolicy().hasHeightForWidth())
        self.chkEndDateFromSync.setSizePolicy(sizePolicy)
        self.chkEndDateFromSync.setChecked(False)
        self.chkEndDateFromSync.setObjectName(_fromUtf8("chkEndDateFromSync"))
        self.gridLayout_8.addWidget(self.chkEndDateFromSync, 3, 1, 1, 1)
        self.cmbClientFound = CEnumComboBox(self.groupBox_2)
        self.cmbClientFound.setObjectName(_fromUtf8("cmbClientFound"))
        self.gridLayout_8.addWidget(self.cmbClientFound, 0, 6, 1, 1)
        self.lblBegDateSync = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDateSync.sizePolicy().hasHeightForWidth())
        self.lblBegDateSync.setSizePolicy(sizePolicy)
        self.lblBegDateSync.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblBegDateSync.setObjectName(_fromUtf8("lblBegDateSync"))
        self.gridLayout_8.addWidget(self.lblBegDateSync, 2, 0, 1, 1)
        self.chkEndDateToSync = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkEndDateToSync.sizePolicy().hasHeightForWidth())
        self.chkEndDateToSync.setSizePolicy(sizePolicy)
        self.chkEndDateToSync.setChecked(False)
        self.chkEndDateToSync.setObjectName(_fromUtf8("chkEndDateToSync"))
        self.gridLayout_8.addWidget(self.chkEndDateToSync, 3, 3, 1, 1)
        self.chkBegDateToSync = QtGui.QCheckBox(self.groupBox_2)
        self.chkBegDateToSync.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkBegDateToSync.sizePolicy().hasHeightForWidth())
        self.chkBegDateToSync.setSizePolicy(sizePolicy)
        self.chkBegDateToSync.setChecked(False)
        self.chkBegDateToSync.setObjectName(_fromUtf8("chkBegDateToSync"))
        self.gridLayout_8.addWidget(self.chkBegDateToSync, 2, 3, 1, 1)
        self.cmbAttachSyncStatus = CEnumComboBox(self.groupBox_2)
        self.cmbAttachSyncStatus.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAttachSyncStatus.sizePolicy().hasHeightForWidth())
        self.cmbAttachSyncStatus.setSizePolicy(sizePolicy)
        self.cmbAttachSyncStatus.setObjectName(_fromUtf8("cmbAttachSyncStatus"))
        self.gridLayout_8.addWidget(self.cmbAttachSyncStatus, 2, 6, 1, 1)
        self.edtBegDateFromSync = CDateEdit(self.groupBox_2)
        self.edtBegDateFromSync.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDateFromSync.sizePolicy().hasHeightForWidth())
        self.edtBegDateFromSync.setSizePolicy(sizePolicy)
        self.edtBegDateFromSync.setObjectName(_fromUtf8("edtBegDateFromSync"))
        self.gridLayout_8.addWidget(self.edtBegDateFromSync, 2, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem6, 0, 7, 1, 1)
        self.lblEndDateSync = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDateSync.sizePolicy().hasHeightForWidth())
        self.lblEndDateSync.setSizePolicy(sizePolicy)
        self.lblEndDateSync.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblEndDateSync.setObjectName(_fromUtf8("lblEndDateSync"))
        self.gridLayout_8.addWidget(self.lblEndDateSync, 3, 0, 1, 1)
        self.lblClientAttachFound = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblClientAttachFound.sizePolicy().hasHeightForWidth())
        self.lblClientAttachFound.setSizePolicy(sizePolicy)
        self.lblClientAttachFound.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblClientAttachFound.setObjectName(_fromUtf8("lblClientAttachFound"))
        self.gridLayout_8.addWidget(self.lblClientAttachFound, 1, 5, 1, 1)
        self.cmbClientAttachFound = CEnumComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbClientAttachFound.sizePolicy().hasHeightForWidth())
        self.cmbClientAttachFound.setSizePolicy(sizePolicy)
        self.cmbClientAttachFound.setObjectName(_fromUtf8("cmbClientAttachFound"))
        self.gridLayout_8.addWidget(self.cmbClientAttachFound, 1, 6, 1, 1)
        self.edtEndDateToSync = CDateEdit(self.groupBox_2)
        self.edtEndDateToSync.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDateToSync.sizePolicy().hasHeightForWidth())
        self.edtEndDateToSync.setSizePolicy(sizePolicy)
        self.edtEndDateToSync.setObjectName(_fromUtf8("edtEndDateToSync"))
        self.gridLayout_8.addWidget(self.edtEndDateToSync, 3, 4, 1, 1)
        self.edtEndDateFromSync = CDateEdit(self.groupBox_2)
        self.edtEndDateFromSync.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDateFromSync.sizePolicy().hasHeightForWidth())
        self.edtEndDateFromSync.setSizePolicy(sizePolicy)
        self.edtEndDateFromSync.setObjectName(_fromUtf8("edtEndDateFromSync"))
        self.gridLayout_8.addWidget(self.edtEndDateFromSync, 3, 2, 1, 1)
        self.lblOrgStructureSync = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgStructureSync.sizePolicy().hasHeightForWidth())
        self.lblOrgStructureSync.setSizePolicy(sizePolicy)
        self.lblOrgStructureSync.setObjectName(_fromUtf8("lblOrgStructureSync"))
        self.gridLayout_8.addWidget(self.lblOrgStructureSync, 0, 0, 1, 1)
        self.chkBegDateFromSync = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkBegDateFromSync.sizePolicy().hasHeightForWidth())
        self.chkBegDateFromSync.setSizePolicy(sizePolicy)
        self.chkBegDateFromSync.setChecked(False)
        self.chkBegDateFromSync.setObjectName(_fromUtf8("chkBegDateFromSync"))
        self.gridLayout_8.addWidget(self.chkBegDateFromSync, 2, 1, 1, 1)
        self.edtBegDateToSync = CDateEdit(self.groupBox_2)
        self.edtBegDateToSync.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDateToSync.sizePolicy().hasHeightForWidth())
        self.edtBegDateToSync.setSizePolicy(sizePolicy)
        self.edtBegDateToSync.setObjectName(_fromUtf8("edtBegDateToSync"))
        self.gridLayout_8.addWidget(self.edtBegDateToSync, 2, 4, 1, 1)
        self.chkAttachSyncStatus = QtGui.QCheckBox(self.groupBox_2)
        self.chkAttachSyncStatus.setObjectName(_fromUtf8("chkAttachSyncStatus"))
        self.gridLayout_8.addWidget(self.chkAttachSyncStatus, 2, 5, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.lblStatusAttachedClientInfo = QtGui.QLabel(self.tabSync)
        self.lblStatusAttachedClientInfo.setObjectName(_fromUtf8("lblStatusAttachedClientInfo"))
        self.horizontalLayout_14.addWidget(self.lblStatusAttachedClientInfo)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.btnCloseAttachedClientInfo = QtGui.QPushButton(self.tabSync)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCloseAttachedClientInfo.sizePolicy().hasHeightForWidth())
        self.btnCloseAttachedClientInfo.setSizePolicy(sizePolicy)
        self.btnCloseAttachedClientInfo.setObjectName(_fromUtf8("btnCloseAttachedClientInfo"))
        self.horizontalLayout_14.addWidget(self.btnCloseAttachedClientInfo)
        self.gridLayout_7.addLayout(self.horizontalLayout_14, 12, 0, 1, 2)
        self.tblAttachedClientInfo = CInDocTableView(self.tabSync)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tblAttachedClientInfo.sizePolicy().hasHeightForWidth())
        self.tblAttachedClientInfo.setSizePolicy(sizePolicy)
        self.tblAttachedClientInfo.setObjectName(_fromUtf8("tblAttachedClientInfo"))
        self.gridLayout_7.addWidget(self.tblAttachedClientInfo, 0, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.tabSync)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem8, 3, 0, 1, 1)
        self.btnLoadAttachedTFOMS = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoadAttachedTFOMS.sizePolicy().hasHeightForWidth())
        self.btnLoadAttachedTFOMS.setSizePolicy(sizePolicy)
        self.btnLoadAttachedTFOMS.setObjectName(_fromUtf8("btnLoadAttachedTFOMS"))
        self.gridLayout_11.addWidget(self.btnLoadAttachedTFOMS, 5, 0, 1, 1)
        self.chkLoadDeAttached = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkLoadDeAttached.sizePolicy().hasHeightForWidth())
        self.chkLoadDeAttached.setSizePolicy(sizePolicy)
        self.chkLoadDeAttached.setChecked(True)
        self.chkLoadDeAttached.setObjectName(_fromUtf8("chkLoadDeAttached"))
        self.gridLayout_11.addWidget(self.chkLoadDeAttached, 1, 0, 1, 1)
        self.chkLoadAttached = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkLoadAttached.sizePolicy().hasHeightForWidth())
        self.chkLoadAttached.setSizePolicy(sizePolicy)
        self.chkLoadAttached.setChecked(True)
        self.chkLoadAttached.setObjectName(_fromUtf8("chkLoadAttached"))
        self.gridLayout_11.addWidget(self.chkLoadAttached, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 1, 0, 1, 1)
        self.tabClientDeAttachQueryLog.addTab(self.tabSync, _fromUtf8(""))
        self.tabDeAttachLog = QtGui.QWidget()
        self.tabDeAttachLog.setObjectName(_fromUtf8("tabDeAttachLog"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabDeAttachLog)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.btnCloseDeAttachLog = QtGui.QPushButton(self.tabDeAttachLog)
        self.btnCloseDeAttachLog.setObjectName(_fromUtf8("btnCloseDeAttachLog"))
        self.horizontalLayout_12.addWidget(self.btnCloseDeAttachLog)
        self.gridLayout_4.addLayout(self.horizontalLayout_12, 3, 0, 1, 1)
        self.tabDeAttach = QtGui.QTabWidget(self.tabDeAttachLog)
        self.tabDeAttach.setTabPosition(QtGui.QTabWidget.North)
        self.tabDeAttach.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabDeAttach.setElideMode(QtCore.Qt.ElideNone)
        self.tabDeAttach.setObjectName(_fromUtf8("tabDeAttach"))
        self.tabIncomeDeAttach = QtGui.QWidget()
        self.tabIncomeDeAttach.setObjectName(_fromUtf8("tabIncomeDeAttach"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabIncomeDeAttach)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.layoutAttachLogButtons = QtGui.QHBoxLayout()
        self.layoutAttachLogButtons.setObjectName(_fromUtf8("layoutAttachLogButtons"))
        self.btnGetDeAttachQuery = QtGui.QPushButton(self.tabIncomeDeAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGetDeAttachQuery.sizePolicy().hasHeightForWidth())
        self.btnGetDeAttachQuery.setSizePolicy(sizePolicy)
        self.btnGetDeAttachQuery.setObjectName(_fromUtf8("btnGetDeAttachQuery"))
        self.layoutAttachLogButtons.addWidget(self.btnGetDeAttachQuery)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layoutAttachLogButtons.addItem(spacerItem10)
        self.gridLayout_3.addLayout(self.layoutAttachLogButtons, 2, 0, 1, 1)
        self.layoutAttachLogFilter = QtGui.QHBoxLayout()
        self.layoutAttachLogFilter.setObjectName(_fromUtf8("layoutAttachLogFilter"))
        self.lblQueryDeAttachDate = QtGui.QLabel(self.tabIncomeDeAttach)
        self.lblQueryDeAttachDate.setObjectName(_fromUtf8("lblQueryDeAttachDate"))
        self.layoutAttachLogFilter.addWidget(self.lblQueryDeAttachDate)
        self.edtQueryDeAttachDate = CDateEdit(self.tabIncomeDeAttach)
        self.edtQueryDeAttachDate.setObjectName(_fromUtf8("edtQueryDeAttachDate"))
        self.layoutAttachLogFilter.addWidget(self.edtQueryDeAttachDate)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layoutAttachLogFilter.addItem(spacerItem11)
        self.gridLayout_3.addLayout(self.layoutAttachLogFilter, 1, 0, 1, 1)
        self.tblIncomeDeAttachQuery = CTableView(self.tabIncomeDeAttach)
        self.tblIncomeDeAttachQuery.setObjectName(_fromUtf8("tblIncomeDeAttachQuery"))
        self.gridLayout_3.addWidget(self.tblIncomeDeAttachQuery, 0, 0, 1, 1)
        self.tabDeAttach.addTab(self.tabIncomeDeAttach, _fromUtf8(""))
        self.tabOutcomeDeAttach = QtGui.QWidget()
        self.tabOutcomeDeAttach.setObjectName(_fromUtf8("tabOutcomeDeAttach"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tabOutcomeDeAttach)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tblOutcomeDeAttachQuery = CInDocTableView(self.tabOutcomeDeAttach)
        self.tblOutcomeDeAttachQuery.setObjectName(_fromUtf8("tblOutcomeDeAttachQuery"))
        self.gridLayout_9.addWidget(self.tblOutcomeDeAttachQuery, 1, 0, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblStatusOutcomeDeAttachQuery = QtGui.QLabel(self.tabOutcomeDeAttach)
        self.lblStatusOutcomeDeAttachQuery.setObjectName(_fromUtf8("lblStatusOutcomeDeAttachQuery"))
        self.horizontalLayout_4.addWidget(self.lblStatusOutcomeDeAttachQuery)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.btnSelectAllSendDeAttachQuery = QtGui.QPushButton(self.tabOutcomeDeAttach)
        self.btnSelectAllSendDeAttachQuery.setObjectName(_fromUtf8("btnSelectAllSendDeAttachQuery"))
        self.horizontalLayout_4.addWidget(self.btnSelectAllSendDeAttachQuery)
        self.btnDeselectAllSendDeAttachQuery = QtGui.QPushButton(self.tabOutcomeDeAttach)
        self.btnDeselectAllSendDeAttachQuery.setObjectName(_fromUtf8("btnDeselectAllSendDeAttachQuery"))
        self.horizontalLayout_4.addWidget(self.btnDeselectAllSendDeAttachQuery)
        self.btnSendNotSentDeAttachQuery = QtGui.QPushButton(self.tabOutcomeDeAttach)
        self.btnSendNotSentDeAttachQuery.setEnabled(False)
        self.btnSendNotSentDeAttachQuery.setObjectName(_fromUtf8("btnSendNotSentDeAttachQuery"))
        self.horizontalLayout_4.addWidget(self.btnSendNotSentDeAttachQuery)
        self.gridLayout_9.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnUpdateDeAttachQueryLog = QtGui.QPushButton(self.tabOutcomeDeAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUpdateDeAttachQueryLog.sizePolicy().hasHeightForWidth())
        self.btnUpdateDeAttachQueryLog.setSizePolicy(sizePolicy)
        self.btnUpdateDeAttachQueryLog.setObjectName(_fromUtf8("btnUpdateDeAttachQueryLog"))
        self.horizontalLayout_5.addWidget(self.btnUpdateDeAttachQueryLog)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.gridLayout_9.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.chkQueryNumTo = QtGui.QCheckBox(self.tabOutcomeDeAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkQueryNumTo.sizePolicy().hasHeightForWidth())
        self.chkQueryNumTo.setSizePolicy(sizePolicy)
        self.chkQueryNumTo.setObjectName(_fromUtf8("chkQueryNumTo"))
        self.gridLayout_10.addWidget(self.chkQueryNumTo, 0, 3, 1, 1)
        self.chkQueryDateTo = QtGui.QCheckBox(self.tabOutcomeDeAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkQueryDateTo.sizePolicy().hasHeightForWidth())
        self.chkQueryDateTo.setSizePolicy(sizePolicy)
        self.chkQueryDateTo.setObjectName(_fromUtf8("chkQueryDateTo"))
        self.gridLayout_10.addWidget(self.chkQueryDateTo, 1, 3, 1, 1)
        self.edtQueryNumFrom = QtGui.QLineEdit(self.tabOutcomeDeAttach)
        self.edtQueryNumFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtQueryNumFrom.sizePolicy().hasHeightForWidth())
        self.edtQueryNumFrom.setSizePolicy(sizePolicy)
        self.edtQueryNumFrom.setInputMask(_fromUtf8(""))
        self.edtQueryNumFrom.setMaxLength(32767)
        self.edtQueryNumFrom.setObjectName(_fromUtf8("edtQueryNumFrom"))
        self.gridLayout_10.addWidget(self.edtQueryNumFrom, 0, 2, 1, 1)
        self.lblQueryNum = QtGui.QLabel(self.tabOutcomeDeAttach)
        self.lblQueryNum.setObjectName(_fromUtf8("lblQueryNum"))
        self.gridLayout_10.addWidget(self.lblQueryNum, 0, 0, 1, 1)
        self.chkQueryNumFrom = QtGui.QCheckBox(self.tabOutcomeDeAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkQueryNumFrom.sizePolicy().hasHeightForWidth())
        self.chkQueryNumFrom.setSizePolicy(sizePolicy)
        self.chkQueryNumFrom.setObjectName(_fromUtf8("chkQueryNumFrom"))
        self.gridLayout_10.addWidget(self.chkQueryNumFrom, 0, 1, 1, 1)
        self.edtQueryDateFrom = CDateEdit(self.tabOutcomeDeAttach)
        self.edtQueryDateFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtQueryDateFrom.sizePolicy().hasHeightForWidth())
        self.edtQueryDateFrom.setSizePolicy(sizePolicy)
        self.edtQueryDateFrom.setObjectName(_fromUtf8("edtQueryDateFrom"))
        self.gridLayout_10.addWidget(self.edtQueryDateFrom, 1, 2, 1, 1)
        self.edtQueryNumTo = QtGui.QLineEdit(self.tabOutcomeDeAttach)
        self.edtQueryNumTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtQueryNumTo.sizePolicy().hasHeightForWidth())
        self.edtQueryNumTo.setSizePolicy(sizePolicy)
        self.edtQueryNumTo.setInputMask(_fromUtf8(""))
        self.edtQueryNumTo.setObjectName(_fromUtf8("edtQueryNumTo"))
        self.gridLayout_10.addWidget(self.edtQueryNumTo, 0, 4, 1, 1)
        self.chkQueryDateFrom = QtGui.QCheckBox(self.tabOutcomeDeAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkQueryDateFrom.sizePolicy().hasHeightForWidth())
        self.chkQueryDateFrom.setSizePolicy(sizePolicy)
        self.chkQueryDateFrom.setObjectName(_fromUtf8("chkQueryDateFrom"))
        self.gridLayout_10.addWidget(self.chkQueryDateFrom, 1, 1, 1, 1)
        self.lblQueryDate = QtGui.QLabel(self.tabOutcomeDeAttach)
        self.lblQueryDate.setObjectName(_fromUtf8("lblQueryDate"))
        self.gridLayout_10.addWidget(self.lblQueryDate, 1, 0, 1, 1)
        self.edtQueryDateTo = CDateEdit(self.tabOutcomeDeAttach)
        self.edtQueryDateTo.setEnabled(False)
        self.edtQueryDateTo.setObjectName(_fromUtf8("edtQueryDateTo"))
        self.gridLayout_10.addWidget(self.edtQueryDateTo, 1, 4, 1, 1)
        self.lblSrcOrgCode = QtGui.QLabel(self.tabOutcomeDeAttach)
        self.lblSrcOrgCode.setObjectName(_fromUtf8("lblSrcOrgCode"))
        self.gridLayout_10.addWidget(self.lblSrcOrgCode, 2, 0, 1, 1)
        self.edtSrcOrgCode = QtGui.QLineEdit(self.tabOutcomeDeAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtSrcOrgCode.sizePolicy().hasHeightForWidth())
        self.edtSrcOrgCode.setSizePolicy(sizePolicy)
        self.edtSrcOrgCode.setMaxLength(16)
        self.edtSrcOrgCode.setObjectName(_fromUtf8("edtSrcOrgCode"))
        self.gridLayout_10.addWidget(self.edtSrcOrgCode, 2, 1, 1, 2)
        self.chkNotSentDeAttachQuery = QtGui.QCheckBox(self.tabOutcomeDeAttach)
        self.chkNotSentDeAttachQuery.setObjectName(_fromUtf8("chkNotSentDeAttachQuery"))
        self.gridLayout_10.addWidget(self.chkNotSentDeAttachQuery, 0, 5, 1, 1)
        self.edtDestOrgCode = QtGui.QLineEdit(self.tabOutcomeDeAttach)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDestOrgCode.sizePolicy().hasHeightForWidth())
        self.edtDestOrgCode.setSizePolicy(sizePolicy)
        self.edtDestOrgCode.setMaxLength(16)
        self.edtDestOrgCode.setObjectName(_fromUtf8("edtDestOrgCode"))
        self.gridLayout_10.addWidget(self.edtDestOrgCode, 3, 1, 1, 2)
        self.lblDestOrgCode = QtGui.QLabel(self.tabOutcomeDeAttach)
        self.lblDestOrgCode.setObjectName(_fromUtf8("lblDestOrgCode"))
        self.gridLayout_10.addWidget(self.lblDestOrgCode, 3, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem14, 3, 5, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_10, 2, 0, 1, 1)
        self.tabDeAttach.addTab(self.tabOutcomeDeAttach, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabDeAttach, 2, 0, 1, 1)
        self.tabClientDeAttachQueryLog.addTab(self.tabDeAttachLog, _fromUtf8(""))
        self.gridLayout_14.addWidget(self.tabClientDeAttachQueryLog, 0, 0, 1, 1)
        self.lblOrgStructureClientAttach.setBuddy(self.cmbOrgStructureClientAttach)
        self.lblDateClientAttach.setBuddy(self.chkBegDateClientAttach)
        self.lblAttachTypeClientAttach.setBuddy(self.cmbAttachTypeClientAttach)
        self.lblDatePersonAttach.setBuddy(self.chkBegDatePersonAttach)
        self.lblOrgStructurePersonAttach.setBuddy(self.cmbOrgStructurePersonAttach)
        self.lblAttachTypeSync.setBuddy(self.cmbAttachTypeSync)
        self.lblBegDateSync.setBuddy(self.chkBegDateFromSync)
        self.lblEndDateSync.setBuddy(self.chkBegDateFromSync)
        self.lblClientAttachFound.setBuddy(self.cmbAttachSyncStatus)
        self.lblOrgStructureSync.setBuddy(self.cmbOrgStructureSync)
        self.lblQueryDeAttachDate.setBuddy(self.edtQueryDeAttachDate)
        self.lblQueryNum.setBuddy(self.chkQueryNumFrom)
        self.lblQueryDate.setBuddy(self.edtQueryDateFrom)
        self.lblSrcOrgCode.setBuddy(self.edtSrcOrgCode)
        self.lblDestOrgCode.setBuddy(self.edtDestOrgCode)

        self.retranslateUi(AttachExchangeDialog)
        self.tabClientDeAttachQueryLog.setCurrentIndex(0)
        self.tabDeAttach.setCurrentIndex(0)
        QtCore.QObject.connect(self.chkBegDateClientAttach, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegDateClientAttach.setEnabled)
        QtCore.QObject.connect(self.chkEndDateClientAttach, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndDateClientAttach.setEnabled)
        QtCore.QObject.connect(self.chkBegDatePersonAttach, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegDatePersonAttach.setEnabled)
        QtCore.QObject.connect(self.chkEndDatePersonAttach, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndDatePersonAttach.setEnabled)
        QtCore.QObject.connect(self.chkBegDateFromSync, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegDateFromSync.setEnabled)
        QtCore.QObject.connect(self.chkBegDateToSync, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegDateToSync.setEnabled)
        QtCore.QObject.connect(self.chkQueryNumFrom, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtQueryNumFrom.setEnabled)
        QtCore.QObject.connect(self.chkQueryNumTo, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtQueryNumTo.setEnabled)
        QtCore.QObject.connect(self.chkQueryDateFrom, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtQueryDateFrom.setEnabled)
        QtCore.QObject.connect(self.chkQueryDateTo, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtQueryDateTo.setEnabled)
        QtCore.QObject.connect(self.chkEndDateFromSync, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndDateFromSync.setEnabled)
        QtCore.QObject.connect(self.chkEndDateToSync, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndDateToSync.setEnabled)
        QtCore.QObject.connect(self.chkAttachSyncStatus, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbAttachSyncStatus.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(AttachExchangeDialog)
        AttachExchangeDialog.setTabOrder(self.btnCloseDeAttachLog, self.cmbMovingSex)
        AttachExchangeDialog.setTabOrder(self.cmbMovingSex, self.cmbMovingFromOrgStructure)
        AttachExchangeDialog.setTabOrder(self.cmbMovingFromOrgStructure, self.cmbMovingToOrgStructure)
        AttachExchangeDialog.setTabOrder(self.cmbMovingToOrgStructure, self.cmbMovingAge)
        AttachExchangeDialog.setTabOrder(self.cmbMovingAge, self.edtMovingCount)
        AttachExchangeDialog.setTabOrder(self.edtMovingCount, self.btnMoveAttaches)
        AttachExchangeDialog.setTabOrder(self.btnMoveAttaches, self.tblClientAttach)
        AttachExchangeDialog.setTabOrder(self.tblClientAttach, self.cmbOrgStructureClientAttach)
        AttachExchangeDialog.setTabOrder(self.cmbOrgStructureClientAttach, self.chkBegDateClientAttach)
        AttachExchangeDialog.setTabOrder(self.chkBegDateClientAttach, self.edtBegDateClientAttach)
        AttachExchangeDialog.setTabOrder(self.edtBegDateClientAttach, self.chkEndDateClientAttach)
        AttachExchangeDialog.setTabOrder(self.chkEndDateClientAttach, self.edtEndDateClientAttach)
        AttachExchangeDialog.setTabOrder(self.edtEndDateClientAttach, self.cmbAttachTypeClientAttach)
        AttachExchangeDialog.setTabOrder(self.cmbAttachTypeClientAttach, self.cmbInsuranceAreaClientAttach)
        AttachExchangeDialog.setTabOrder(self.cmbInsuranceAreaClientAttach, self.chkChangeSection)
        AttachExchangeDialog.setTabOrder(self.chkChangeSection, self.btnLoadClientAttach)
        AttachExchangeDialog.setTabOrder(self.btnLoadClientAttach, self.btnSelectAllClientAttach)
        AttachExchangeDialog.setTabOrder(self.btnSelectAllClientAttach, self.btnDeselectAllClientAttach)
        AttachExchangeDialog.setTabOrder(self.btnDeselectAllClientAttach, self.btnSyncClientAttach)
        AttachExchangeDialog.setTabOrder(self.btnSyncClientAttach, self.btnCloseClientAttach)
        AttachExchangeDialog.setTabOrder(self.btnCloseClientAttach, self.tblPersonAttach)
        AttachExchangeDialog.setTabOrder(self.tblPersonAttach, self.cmbOrgStructurePersonAttach)
        AttachExchangeDialog.setTabOrder(self.cmbOrgStructurePersonAttach, self.chkBegDatePersonAttach)
        AttachExchangeDialog.setTabOrder(self.chkBegDatePersonAttach, self.edtBegDatePersonAttach)
        AttachExchangeDialog.setTabOrder(self.edtBegDatePersonAttach, self.chkEndDatePersonAttach)
        AttachExchangeDialog.setTabOrder(self.chkEndDatePersonAttach, self.edtEndDatePersonAttach)
        AttachExchangeDialog.setTabOrder(self.edtEndDatePersonAttach, self.btnLoadPersonAttach)
        AttachExchangeDialog.setTabOrder(self.btnLoadPersonAttach, self.btnSelectAllPersonAttach)
        AttachExchangeDialog.setTabOrder(self.btnSelectAllPersonAttach, self.btnDeselectAllPersonAttach)
        AttachExchangeDialog.setTabOrder(self.btnDeselectAllPersonAttach, self.btnSyncPersonAttach)
        AttachExchangeDialog.setTabOrder(self.btnSyncPersonAttach, self.btnClosePersonAttach)
        AttachExchangeDialog.setTabOrder(self.btnClosePersonAttach, self.tblAttachedClientInfo)
        AttachExchangeDialog.setTabOrder(self.tblAttachedClientInfo, self.chkLoadDeAttached)
        AttachExchangeDialog.setTabOrder(self.chkLoadDeAttached, self.chkLoadAttached)
        AttachExchangeDialog.setTabOrder(self.chkLoadAttached, self.btnLoadAttachedTFOMS)
        AttachExchangeDialog.setTabOrder(self.btnLoadAttachedTFOMS, self.cmbOrgStructureSync)
        AttachExchangeDialog.setTabOrder(self.cmbOrgStructureSync, self.cmbAttachTypeSync)
        AttachExchangeDialog.setTabOrder(self.cmbAttachTypeSync, self.chkBegDateFromSync)
        AttachExchangeDialog.setTabOrder(self.chkBegDateFromSync, self.edtBegDateFromSync)
        AttachExchangeDialog.setTabOrder(self.edtBegDateFromSync, self.chkBegDateToSync)
        AttachExchangeDialog.setTabOrder(self.chkBegDateToSync, self.edtBegDateToSync)
        AttachExchangeDialog.setTabOrder(self.edtBegDateToSync, self.chkEndDateFromSync)
        AttachExchangeDialog.setTabOrder(self.chkEndDateFromSync, self.edtEndDateFromSync)
        AttachExchangeDialog.setTabOrder(self.edtEndDateFromSync, self.chkEndDateToSync)
        AttachExchangeDialog.setTabOrder(self.chkEndDateToSync, self.edtEndDateToSync)
        AttachExchangeDialog.setTabOrder(self.edtEndDateToSync, self.cmbClientFound)
        AttachExchangeDialog.setTabOrder(self.cmbClientFound, self.cmbClientAttachFound)
        AttachExchangeDialog.setTabOrder(self.cmbClientAttachFound, self.chkAttachSyncStatus)
        AttachExchangeDialog.setTabOrder(self.chkAttachSyncStatus, self.cmbAttachSyncStatus)
        AttachExchangeDialog.setTabOrder(self.cmbAttachSyncStatus, self.btnLoadAttachedClientInfo)
        AttachExchangeDialog.setTabOrder(self.btnLoadAttachedClientInfo, self.btnSelectAllAttachedClientInfo)
        AttachExchangeDialog.setTabOrder(self.btnSelectAllAttachedClientInfo, self.btnDeselectAllAttachedClientInfo)
        AttachExchangeDialog.setTabOrder(self.btnDeselectAllAttachedClientInfo, self.btnImportAttachedClientInfo)
        AttachExchangeDialog.setTabOrder(self.btnImportAttachedClientInfo, self.btnSaveAttachedClientInfo)
        AttachExchangeDialog.setTabOrder(self.btnSaveAttachedClientInfo, self.btnCloseAttachedClientInfo)
        AttachExchangeDialog.setTabOrder(self.btnCloseAttachedClientInfo, self.tabDeAttach)
        AttachExchangeDialog.setTabOrder(self.tabDeAttach, self.tblIncomeDeAttachQuery)
        AttachExchangeDialog.setTabOrder(self.tblIncomeDeAttachQuery, self.edtQueryDeAttachDate)
        AttachExchangeDialog.setTabOrder(self.edtQueryDeAttachDate, self.btnGetDeAttachQuery)
        AttachExchangeDialog.setTabOrder(self.btnGetDeAttachQuery, self.tabClientDeAttachQueryLog)
        AttachExchangeDialog.setTabOrder(self.tabClientDeAttachQueryLog, self.tblOutcomeDeAttachQuery)
        AttachExchangeDialog.setTabOrder(self.tblOutcomeDeAttachQuery, self.chkQueryNumFrom)
        AttachExchangeDialog.setTabOrder(self.chkQueryNumFrom, self.edtQueryNumFrom)
        AttachExchangeDialog.setTabOrder(self.edtQueryNumFrom, self.chkQueryNumTo)
        AttachExchangeDialog.setTabOrder(self.chkQueryNumTo, self.edtQueryNumTo)
        AttachExchangeDialog.setTabOrder(self.edtQueryNumTo, self.chkQueryDateFrom)
        AttachExchangeDialog.setTabOrder(self.chkQueryDateFrom, self.edtQueryDateFrom)
        AttachExchangeDialog.setTabOrder(self.edtQueryDateFrom, self.chkQueryDateTo)
        AttachExchangeDialog.setTabOrder(self.chkQueryDateTo, self.edtQueryDateTo)
        AttachExchangeDialog.setTabOrder(self.edtQueryDateTo, self.edtSrcOrgCode)
        AttachExchangeDialog.setTabOrder(self.edtSrcOrgCode, self.edtDestOrgCode)
        AttachExchangeDialog.setTabOrder(self.edtDestOrgCode, self.chkNotSentDeAttachQuery)
        AttachExchangeDialog.setTabOrder(self.chkNotSentDeAttachQuery, self.btnUpdateDeAttachQueryLog)
        AttachExchangeDialog.setTabOrder(self.btnUpdateDeAttachQueryLog, self.btnSelectAllSendDeAttachQuery)
        AttachExchangeDialog.setTabOrder(self.btnSelectAllSendDeAttachQuery, self.btnDeselectAllSendDeAttachQuery)
        AttachExchangeDialog.setTabOrder(self.btnDeselectAllSendDeAttachQuery, self.btnSendNotSentDeAttachQuery)

    def retranslateUi(self, AttachExchangeDialog):
        AttachExchangeDialog.setWindowTitle(_translate("AttachExchangeDialog", "Dialog", None))
        self.lblMovingSex.setText(_translate("AttachExchangeDialog", "Пол", None))
        self.cmbMovingAge.setItemText(0, _translate("AttachExchangeDialog", "Все", None))
        self.cmbMovingAge.setItemText(1, _translate("AttachExchangeDialog", "Дети", None))
        self.cmbMovingAge.setItemText(2, _translate("AttachExchangeDialog", "Взрослые", None))
        self.lblMovingCount.setText(_translate("AttachExchangeDialog", "Кол-во", None))
        self.cmbMovingSex.setItemText(0, _translate("AttachExchangeDialog", "Все", None))
        self.cmbMovingSex.setItemText(1, _translate("AttachExchangeDialog", "Мужчины", None))
        self.cmbMovingSex.setItemText(2, _translate("AttachExchangeDialog", "Женщины", None))
        self.lblMovingAge.setText(_translate("AttachExchangeDialog", "Возраст", None))
        self.lblMovingFrom.setText(_translate("AttachExchangeDialog", "с", None))
        self.lblMovingTo.setText(_translate("AttachExchangeDialog", "на", None))
        self.btnMoveAttaches.setText(_translate("AttachExchangeDialog", "Перенести", None))
        self.btnPrintReport.setText(_translate("AttachExchangeDialog", "Печать", None))
        self.tabClientDeAttachQueryLog.setTabText(self.tabClientDeAttachQueryLog.indexOf(self.tabMonitoring), _translate("AttachExchangeDialog", "Мониторинг", None))
        self.btnLoadClientAttach.setText(_translate("AttachExchangeDialog", "Применить", None))
        self.btnSelectAllClientAttach.setText(_translate("AttachExchangeDialog", "Выделить всё", None))
        self.btnDeselectAllClientAttach.setText(_translate("AttachExchangeDialog", "Снять выделение", None))
        self.btnSyncClientAttach.setText(_translate("AttachExchangeDialog", "Отослать выделенное", None))
        self.lblStatusClientAttach.setText(_translate("AttachExchangeDialog", "Записей в таблице выделено/всего: 0/0", None))
        self.btnCloseClientAttach.setText(_translate("AttachExchangeDialog", "Закрыть", None))
        self.lblOrgStructureClientAttach.setText(_translate("AttachExchangeDialog", "Подразделение", None))
        self.lblDateClientAttach.setText(_translate("AttachExchangeDialog", "Дата прикрепления", None))
        self.lblAttachTypeClientAttach.setText(_translate("AttachExchangeDialog", "Тип прикрепления", None))
        self.chkEndDateClientAttach.setText(_translate("AttachExchangeDialog", "до", None))
        self.chkBegDateClientAttach.setText(_translate("AttachExchangeDialog", "от", None))
        self.lblInsuranceAreaClientAttach.setText(_translate("AttachExchangeDialog", "Территория страхования", None))
        self.chkChangeSection.setText(_translate("AttachExchangeDialog", "Смена участка", None))
        self.tabClientDeAttachQueryLog.setTabText(self.tabClientDeAttachQueryLog.indexOf(self.tabClientAttach), _translate("AttachExchangeDialog", "Прикреплённое население", None))
        self.lblDatePersonAttach.setText(_translate("AttachExchangeDialog", "Дата", None))
        self.lblOrgStructurePersonAttach.setText(_translate("AttachExchangeDialog", "Подразделение", None))
        self.chkBegDatePersonAttach.setText(_translate("AttachExchangeDialog", "от", None))
        self.chkEndDatePersonAttach.setText(_translate("AttachExchangeDialog", "до", None))
        self.btnLoadPersonAttach.setText(_translate("AttachExchangeDialog", "Применить", None))
        self.btnSelectAllPersonAttach.setText(_translate("AttachExchangeDialog", "Выделить всё", None))
        self.btnDeselectAllPersonAttach.setText(_translate("AttachExchangeDialog", "Снять выделение", None))
        self.btnSyncPersonAttach.setText(_translate("AttachExchangeDialog", "Отослать выделенное", None))
        self.lblStatusPersonAttach.setText(_translate("AttachExchangeDialog", "Записей в таблице выделено/всего: 0/0", None))
        self.btnClosePersonAttach.setText(_translate("AttachExchangeDialog", "Закрыть", None))
        self.tabClientDeAttachQueryLog.setTabText(self.tabClientDeAttachQueryLog.indexOf(self.tabPersonAttach), _translate("AttachExchangeDialog", "Медицинский персонал", None))
        self.groupBox_2.setTitle(_translate("AttachExchangeDialog", "Обработка данных", None))
        self.btnLoadAttachedClientInfo.setText(_translate("AttachExchangeDialog", "Применить", None))
        self.btnSelectAllAttachedClientInfo.setText(_translate("AttachExchangeDialog", "Выделить всё", None))
        self.btnDeselectAllAttachedClientInfo.setText(_translate("AttachExchangeDialog", "Снять выделение", None))
        self.btnImportAttachedClientInfo.setText(_translate("AttachExchangeDialog", "Импортировать", None))
        self.btnSaveAttachedClientInfo.setText(_translate("AttachExchangeDialog", "Сохранить", None))
        self.lblClientFound.setText(_translate("AttachExchangeDialog", "Пациент", None))
        self.lblAttachTypeSync.setText(_translate("AttachExchangeDialog", "Тип прикрепления", None))
        self.chkEndDateFromSync.setText(_translate("AttachExchangeDialog", "от", None))
        self.cmbClientFound.setToolTip(_translate("AttachExchangeDialog", "Найден ли пациент в БД по данным, полученным от ТФОМС", None))
        self.lblBegDateSync.setText(_translate("AttachExchangeDialog", "Дата прикрепления", None))
        self.chkEndDateToSync.setText(_translate("AttachExchangeDialog", "до", None))
        self.chkBegDateToSync.setText(_translate("AttachExchangeDialog", "до", None))
        self.lblEndDateSync.setText(_translate("AttachExchangeDialog", "Дата открепления", None))
        self.lblClientAttachFound.setText(_translate("AttachExchangeDialog", "Прикрепление", None))
        self.lblOrgStructureSync.setText(_translate("AttachExchangeDialog", "Подразделение", None))
        self.chkBegDateFromSync.setText(_translate("AttachExchangeDialog", "от", None))
        self.chkAttachSyncStatus.setText(_translate("AttachExchangeDialog", "Статус синхронизации", None))
        self.lblStatusAttachedClientInfo.setText(_translate("AttachExchangeDialog", "Записей в таблице выделено/всего: 0/0", None))
        self.btnCloseAttachedClientInfo.setText(_translate("AttachExchangeDialog", "Закрыть", None))
        self.groupBox.setTitle(_translate("AttachExchangeDialog", "Загрузка данных", None))
        self.btnLoadAttachedTFOMS.setText(_translate("AttachExchangeDialog", "Загрузить из ТФОМС", None))
        self.chkLoadDeAttached.setText(_translate("AttachExchangeDialog", "Загружать откреплённых", None))
        self.chkLoadAttached.setText(_translate("AttachExchangeDialog", "Загружать прикреплённых", None))
        self.tabClientDeAttachQueryLog.setTabText(self.tabClientDeAttachQueryLog.indexOf(self.tabSync), _translate("AttachExchangeDialog", "Синхронизация", None))
        self.btnCloseDeAttachLog.setText(_translate("AttachExchangeDialog", "Закрыть", None))
        self.btnGetDeAttachQuery.setText(_translate("AttachExchangeDialog", "Обновить", None))
        self.lblQueryDeAttachDate.setText(_translate("AttachExchangeDialog", "Дата данных", None))
        self.tabDeAttach.setTabText(self.tabDeAttach.indexOf(self.tabIncomeDeAttach), _translate("AttachExchangeDialog", "Входящие", None))
        self.lblStatusOutcomeDeAttachQuery.setText(_translate("AttachExchangeDialog", "Записей в таблице выделено/всего: 0/0", None))
        self.btnSelectAllSendDeAttachQuery.setText(_translate("AttachExchangeDialog", "Выделить всё", None))
        self.btnDeselectAllSendDeAttachQuery.setText(_translate("AttachExchangeDialog", "Снять выделение", None))
        self.btnSendNotSentDeAttachQuery.setText(_translate("AttachExchangeDialog", "Отправить выделенное", None))
        self.btnUpdateDeAttachQueryLog.setText(_translate("AttachExchangeDialog", "Применить", None))
        self.chkQueryNumTo.setText(_translate("AttachExchangeDialog", "до", None))
        self.chkQueryDateTo.setText(_translate("AttachExchangeDialog", "до", None))
        self.lblQueryNum.setText(_translate("AttachExchangeDialog", "№ уведомления", None))
        self.chkQueryNumFrom.setText(_translate("AttachExchangeDialog", "от", None))
        self.edtQueryDateFrom.setDisplayFormat(_translate("AttachExchangeDialog", "dd.MM.yyyy", None))
        self.chkQueryDateFrom.setText(_translate("AttachExchangeDialog", "от", None))
        self.lblQueryDate.setText(_translate("AttachExchangeDialog", "Дата уведомления", None))
        self.edtQueryDateTo.setDisplayFormat(_translate("AttachExchangeDialog", "dd.MM.yyyy", None))
        self.lblSrcOrgCode.setText(_translate("AttachExchangeDialog", "Код отправителя", None))
        self.chkNotSentDeAttachQuery.setText(_translate("AttachExchangeDialog", "не отправлено", None))
        self.lblDestOrgCode.setText(_translate("AttachExchangeDialog", "Код получателя", None))
        self.tabDeAttach.setTabText(self.tabDeAttach.indexOf(self.tabOutcomeDeAttach), _translate("AttachExchangeDialog", "Исходящие", None))
        self.tabClientDeAttachQueryLog.setTabText(self.tabClientDeAttachQueryLog.indexOf(self.tabDeAttachLog), _translate("AttachExchangeDialog", "Уведомления о прикреплении", None))

from Orgs.ClientAttachMonitoring import CClientAttachMonitoring
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.DateEdit import CDateEdit
from library.Enum import CEnumComboBox
from library.InDocTable import CInDocTableView
from library.TableView import CTableView
