################################################## 
# UploadService_services.py 
# generated by ZSI.generate.wsdl2python
##################################################


from UploadService_services_types import *
from ZSI import client

# Locator
class UploadServiceLocator:
    UploadServiceSoap_address = "http://10.0.1.154/drugstore/UploadService.asmx"
    def getUploadServiceSoapAddress(self):
        return UploadServiceLocator.UploadServiceSoap_address
    def getUploadServiceSoap(self, url=None, **kw):
        return UploadServiceSoapSOAP(url or UploadServiceLocator.UploadServiceSoap_address, **kw)

# Methods
class UploadServiceSoapSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: RecipesClientSave
    def RecipesClientSave(self, request):
        if isinstance(request, RecipesClientSaveSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://tempuri.org/RecipesClientSave", **kw)
        # no output wsaction
        response = self.binding.Receive(RecipesClientSaveSoapOut.typecode)
        return response

    # op: DoctorsClientSave
    def DoctorsClientSave(self, request):
        if isinstance(request, DoctorsClientSaveSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://tempuri.org/DoctorsClientSave", **kw)
        # no output wsaction
        response = self.binding.Receive(DoctorsClientSaveSoapOut.typecode)
        return response

    # op: PersonClientSave
    def PersonClientSave(self, request):
        if isinstance(request, PersonClientSaveSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://tempuri.org/PersonClientSave", **kw)
        # no output wsaction
        response = self.binding.Receive(PersonClientSaveSoapOut.typecode)
        return response

    # op: PersonClientCheck
    def PersonClientCheck(self, request):
        if isinstance(request, PersonClientCheckSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://tempuri.org/PersonClientCheck", **kw)
        # no output wsaction
        response = self.binding.Receive(PersonClientCheckSoapOut.typecode)
        return response

RecipesClientSaveSoapIn = ns0.RecipesClientSave_Dec().pyclass

RecipesClientSaveSoapOut = ns0.RecipesClientSaveResponse_Dec().pyclass

DoctorsClientSaveSoapIn = ns0.DoctorsClientSave_Dec().pyclass

DoctorsClientSaveSoapOut = ns0.DoctorsClientSaveResponse_Dec().pyclass

PersonClientSaveSoapIn = ns0.PersonClientSave_Dec().pyclass

PersonClientSaveSoapOut = ns0.PersonClientSaveResponse_Dec().pyclass

PersonClientCheckSoapIn = ns0.PersonClientCheck_Dec().pyclass

PersonClientCheckSoapOut = ns0.PersonClientCheckResponse_Dec().pyclass
