# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ActionsPage.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ActionsPageWidget(object):
    def setupUi(self, ActionsPageWidget):
        ActionsPageWidget.setObjectName(_fromUtf8("ActionsPageWidget"))
        ActionsPageWidget.resize(1021, 825)
        self.verticalLayout = QtGui.QVBoxLayout(ActionsPageWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.attrsAP = QtGui.QFrame(ActionsPageWidget)
        self.attrsAP.setObjectName(_fromUtf8("attrsAP"))
        self.gridLayout_3 = QtGui.QGridLayout(self.attrsAP)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.edtAPBegDate = CDateEdit(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPBegDate.sizePolicy().hasHeightForWidth())
        self.edtAPBegDate.setSizePolicy(sizePolicy)
        self.edtAPBegDate.setCalendarPopup(True)
        self.edtAPBegDate.setObjectName(_fromUtf8("edtAPBegDate"))
        self.horizontalLayout_11.addWidget(self.edtAPBegDate)
        self.edtAPBegTime = QtGui.QTimeEdit(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPBegTime.sizePolicy().hasHeightForWidth())
        self.edtAPBegTime.setSizePolicy(sizePolicy)
        self.edtAPBegTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPBegTime.setObjectName(_fromUtf8("edtAPBegTime"))
        self.horizontalLayout_11.addWidget(self.edtAPBegTime)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 1, 1, 1, 1)
        self.lblAPEndDate = QtGui.QLabel(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPEndDate.sizePolicy().hasHeightForWidth())
        self.lblAPEndDate.setSizePolicy(sizePolicy)
        self.lblAPEndDate.setObjectName(_fromUtf8("lblAPEndDate"))
        self.gridLayout_3.addWidget(self.lblAPEndDate, 1, 4, 1, 1)
        self.mkbLayout = QtGui.QWidget(self.attrsAP)
        self.mkbLayout.setObjectName(_fromUtf8("mkbLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.mkbLayout)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cmbHMPMethod = CRBComboBox(self.mkbLayout)
        self.cmbHMPMethod.setObjectName(_fromUtf8("cmbHMPMethod"))
        self.horizontalLayout_2.addWidget(self.cmbHMPMethod)
        self.gridLayout_3.addWidget(self.mkbLayout, 6, 5, 1, 1)
        self.lblAPOffice = QtGui.QLabel(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPOffice.sizePolicy().hasHeightForWidth())
        self.lblAPOffice.setSizePolicy(sizePolicy)
        self.lblAPOffice.setObjectName(_fromUtf8("lblAPOffice"))
        self.gridLayout_3.addWidget(self.lblAPOffice, 1, 2, 1, 1)
        self.lblAPDirectionDate = QtGui.QLabel(self.attrsAP)
        self.lblAPDirectionDate.setObjectName(_fromUtf8("lblAPDirectionDate"))
        self.gridLayout_3.addWidget(self.lblAPDirectionDate, 0, 4, 1, 1)
        self.lblAPStatus = QtGui.QLabel(self.attrsAP)
        self.lblAPStatus.setObjectName(_fromUtf8("lblAPStatus"))
        self.gridLayout_3.addWidget(self.lblAPStatus, 0, 0, 1, 1)
        self.lblAPOrg = QtGui.QLabel(self.attrsAP)
        self.lblAPOrg.setObjectName(_fromUtf8("lblAPOrg"))
        self.gridLayout_3.addWidget(self.lblAPOrg, 2, 0, 1, 1)
        self.lblAPBegDate = QtGui.QLabel(self.attrsAP)
        self.lblAPBegDate.setObjectName(_fromUtf8("lblAPBegDate"))
        self.gridLayout_3.addWidget(self.lblAPBegDate, 1, 0, 1, 1)
        self.cmbAPSetPerson = CPersonComboBoxEx(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPSetPerson.sizePolicy().hasHeightForWidth())
        self.cmbAPSetPerson.setSizePolicy(sizePolicy)
        self.cmbAPSetPerson.setObjectName(_fromUtf8("cmbAPSetPerson"))
        self.cmbAPSetPerson.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbAPSetPerson, 0, 7, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnPlanNextAction = QtGui.QToolButton(self.attrsAP)
        self.btnPlanNextAction.setEnabled(True)
        self.btnPlanNextAction.setObjectName(_fromUtf8("btnPlanNextAction"))
        self.horizontalLayout_5.addWidget(self.btnPlanNextAction)
        self.btnNextAction = QtGui.QPushButton(self.attrsAP)
        self.btnNextAction.setEnabled(True)
        self.btnNextAction.setObjectName(_fromUtf8("btnNextAction"))
        self.horizontalLayout_5.addWidget(self.btnNextAction)
        self.btnReanimation = QtGui.QPushButton(self.attrsAP)
        self.btnReanimation.setObjectName(_fromUtf8("btnReanimation"))
        self.horizontalLayout_5.addWidget(self.btnReanimation)
        self.btnMaternityWard = QtGui.QPushButton(self.attrsAP)
        self.btnMaternityWard.setObjectName(_fromUtf8("btnMaternityWard"))
        self.horizontalLayout_5.addWidget(self.btnMaternityWard)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 2, 4, 1, 2)
        self.cmbAPPerson = CPersonComboBoxEx(self.attrsAP)
        self.cmbAPPerson.setObjectName(_fromUtf8("cmbAPPerson"))
        self.cmbAPPerson.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbAPPerson, 1, 7, 1, 1)
        self.lblAPPerson = QtGui.QLabel(self.attrsAP)
        self.lblAPPerson.setObjectName(_fromUtf8("lblAPPerson"))
        self.gridLayout_3.addWidget(self.lblAPPerson, 1, 6, 1, 1)
        self.lblAPSetPerson = QtGui.QLabel(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPSetPerson.sizePolicy().hasHeightForWidth())
        self.lblAPSetPerson.setSizePolicy(sizePolicy)
        self.lblAPSetPerson.setObjectName(_fromUtf8("lblAPSetPerson"))
        self.gridLayout_3.addWidget(self.lblAPSetPerson, 0, 6, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.edtAPEndDate = CDateEdit(self.attrsAP)
        self.edtAPEndDate.setCalendarPopup(True)
        self.edtAPEndDate.setObjectName(_fromUtf8("edtAPEndDate"))
        self.horizontalLayout_8.addWidget(self.edtAPEndDate)
        self.edtAPEndTime = QtGui.QTimeEdit(self.attrsAP)
        self.edtAPEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPEndTime.setObjectName(_fromUtf8("edtAPEndTime"))
        self.horizontalLayout_8.addWidget(self.edtAPEndTime)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 1, 5, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.edtAPDirectionDate = CDateEdit(self.attrsAP)
        self.edtAPDirectionDate.setCalendarPopup(True)
        self.edtAPDirectionDate.setObjectName(_fromUtf8("edtAPDirectionDate"))
        self.horizontalLayout_6.addWidget(self.edtAPDirectionDate)
        self.edtAPDirectionTime = QtGui.QTimeEdit(self.attrsAP)
        self.edtAPDirectionTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPDirectionTime.setObjectName(_fromUtf8("edtAPDirectionTime"))
        self.horizontalLayout_6.addWidget(self.edtAPDirectionTime)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 0, 5, 1, 1)
        self.edtAPOffice = QtGui.QLineEdit(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPOffice.sizePolicy().hasHeightForWidth())
        self.edtAPOffice.setSizePolicy(sizePolicy)
        self.edtAPOffice.setMaxLength(16)
        self.edtAPOffice.setObjectName(_fromUtf8("edtAPOffice"))
        self.gridLayout_3.addWidget(self.edtAPOffice, 1, 3, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cmbAPStatus = QtGui.QComboBox(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPStatus.sizePolicy().hasHeightForWidth())
        self.cmbAPStatus.setSizePolicy(sizePolicy)
        self.cmbAPStatus.setObjectName(_fromUtf8("cmbAPStatus"))
        self.horizontalLayout_3.addWidget(self.cmbAPStatus)
        self.chkAPIsUrgent = QtGui.QCheckBox(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkAPIsUrgent.sizePolicy().hasHeightForWidth())
        self.chkAPIsUrgent.setSizePolicy(sizePolicy)
        self.chkAPIsUrgent.setObjectName(_fromUtf8("chkAPIsUrgent"))
        self.horizontalLayout_3.addWidget(self.chkAPIsUrgent)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 1, 1, 3)
        self.lblAPAssistant = QtGui.QLabel(self.attrsAP)
        self.lblAPAssistant.setObjectName(_fromUtf8("lblAPAssistant"))
        self.gridLayout_3.addWidget(self.lblAPAssistant, 3, 0, 1, 1)
        self.cmbAPAssistant = CPersonComboBoxEx(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPAssistant.sizePolicy().hasHeightForWidth())
        self.cmbAPAssistant.setSizePolicy(sizePolicy)
        self.cmbAPAssistant.setObjectName(_fromUtf8("cmbAPAssistant"))
        self.cmbAPAssistant.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbAPAssistant, 3, 1, 1, 3)
        self.cmbAPAssistant3 = CPersonComboBoxEx(self.attrsAP)
        self.cmbAPAssistant3.setObjectName(_fromUtf8("cmbAPAssistant3"))
        self.gridLayout_3.addWidget(self.cmbAPAssistant3, 3, 7, 1, 1)
        self.cmbAPAssistant2 = CPersonComboBoxEx(self.attrsAP)
        self.cmbAPAssistant2.setObjectName(_fromUtf8("cmbAPAssistant2"))
        self.gridLayout_3.addWidget(self.cmbAPAssistant2, 3, 5, 1, 1)
        self.lblAPAssistant2 = QtGui.QLabel(self.attrsAP)
        self.lblAPAssistant2.setObjectName(_fromUtf8("lblAPAssistant2"))
        self.gridLayout_3.addWidget(self.lblAPAssistant2, 3, 4, 1, 1)
        self.lblAPAssistant3 = QtGui.QLabel(self.attrsAP)
        self.lblAPAssistant3.setObjectName(_fromUtf8("lblAPAssistant3"))
        self.gridLayout_3.addWidget(self.lblAPAssistant3, 3, 6, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblAPAmount = QtGui.QLabel(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPAmount.sizePolicy().hasHeightForWidth())
        self.lblAPAmount.setSizePolicy(sizePolicy)
        self.lblAPAmount.setObjectName(_fromUtf8("lblAPAmount"))
        self.horizontalLayout.addWidget(self.lblAPAmount)
        self.edtAPAmount = QtGui.QDoubleSpinBox(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPAmount.sizePolicy().hasHeightForWidth())
        self.edtAPAmount.setSizePolicy(sizePolicy)
        self.edtAPAmount.setMaximum(999.99)
        self.edtAPAmount.setObjectName(_fromUtf8("edtAPAmount"))
        self.horizontalLayout.addWidget(self.edtAPAmount)
        self.lblAPUet = QtGui.QLabel(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPUet.sizePolicy().hasHeightForWidth())
        self.lblAPUet.setSizePolicy(sizePolicy)
        self.lblAPUet.setObjectName(_fromUtf8("lblAPUet"))
        self.horizontalLayout.addWidget(self.lblAPUet)
        self.edtAPUet = QtGui.QDoubleSpinBox(self.attrsAP)
        self.edtAPUet.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPUet.sizePolicy().hasHeightForWidth())
        self.edtAPUet.setSizePolicy(sizePolicy)
        self.edtAPUet.setSingleStep(0.5)
        self.edtAPUet.setObjectName(_fromUtf8("edtAPUet"))
        self.horizontalLayout.addWidget(self.edtAPUet)
        self.lblAPNote = QtGui.QLabel(self.attrsAP)
        self.lblAPNote.setObjectName(_fromUtf8("lblAPNote"))
        self.horizontalLayout.addWidget(self.lblAPNote)
        self.edtAPNote = QtGui.QLineEdit(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPNote.sizePolicy().hasHeightForWidth())
        self.edtAPNote.setSizePolicy(sizePolicy)
        self.edtAPNote.setObjectName(_fromUtf8("edtAPNote"))
        self.horizontalLayout.addWidget(self.edtAPNote)
        self.lblAPMKB = QtGui.QLabel(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPMKB.sizePolicy().hasHeightForWidth())
        self.lblAPMKB.setSizePolicy(sizePolicy)
        self.lblAPMKB.setObjectName(_fromUtf8("lblAPMKB"))
        self.horizontalLayout.addWidget(self.lblAPMKB)
        self.cmbAPMKB = CICDCodeEditEx(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPMKB.sizePolicy().hasHeightForWidth())
        self.cmbAPMKB.setSizePolicy(sizePolicy)
        self.cmbAPMKB.setObjectName(_fromUtf8("cmbAPMKB"))
        self.horizontalLayout.addWidget(self.cmbAPMKB)
        self.lblAPMKBText = QtGui.QLabel(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPMKBText.sizePolicy().hasHeightForWidth())
        self.lblAPMKBText.setSizePolicy(sizePolicy)
        self.lblAPMKBText.setText(_fromUtf8(""))
        self.lblAPMKBText.setWordWrap(True)
        self.lblAPMKBText.setObjectName(_fromUtf8("lblAPMKBText"))
        self.horizontalLayout.addWidget(self.lblAPMKBText)
        self.gridLayout_3.addLayout(self.horizontalLayout, 5, 0, 1, 8)
        self.grpAPOrg = QtGui.QWidget(self.attrsAP)
        self.grpAPOrg.setObjectName(_fromUtf8("grpAPOrg"))
        self._2 = QtGui.QHBoxLayout(self.grpAPOrg)
        self._2.setMargin(1)
        self._2.setObjectName(_fromUtf8("_2"))
        self.cmbAPOrg = CPolyclinicExtendedComboBox(self.grpAPOrg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPOrg.sizePolicy().hasHeightForWidth())
        self.cmbAPOrg.setSizePolicy(sizePolicy)
        self.cmbAPOrg.setObjectName(_fromUtf8("cmbAPOrg"))
        self.cmbAPOrg.addItem(_fromUtf8(""))
        self._2.addWidget(self.cmbAPOrg)
        self.btnAPSelectOrg = QtGui.QToolButton(self.grpAPOrg)
        self.btnAPSelectOrg.setObjectName(_fromUtf8("btnAPSelectOrg"))
        self._2.addWidget(self.btnAPSelectOrg)
        self.gridLayout_3.addWidget(self.grpAPOrg, 2, 1, 1, 3)
        self.cmbAPMorphologyMKB = CICDMorphologyCodeEditEx(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPMorphologyMKB.sizePolicy().hasHeightForWidth())
        self.cmbAPMorphologyMKB.setSizePolicy(sizePolicy)
        self.cmbAPMorphologyMKB.setMinimumSize(QtCore.QSize(0, 0))
        self.cmbAPMorphologyMKB.setObjectName(_fromUtf8("cmbAPMorphologyMKB"))
        self.gridLayout_3.addWidget(self.cmbAPMorphologyMKB, 2, 7, 1, 1)
        self.lblAPMorphologyMKB = QtGui.QLabel(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPMorphologyMKB.sizePolicy().hasHeightForWidth())
        self.lblAPMorphologyMKB.setSizePolicy(sizePolicy)
        self.lblAPMorphologyMKB.setObjectName(_fromUtf8("lblAPMorphologyMKB"))
        self.gridLayout_3.addWidget(self.lblAPMorphologyMKB, 2, 6, 1, 1)
        self.lblHMPKind = QtGui.QLabel(self.attrsAP)
        self.lblHMPKind.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblHMPKind.setObjectName(_fromUtf8("lblHMPKind"))
        self.gridLayout_3.addWidget(self.lblHMPKind, 6, 0, 1, 1)
        self.cmbHMPKind = CRBComboBox(self.attrsAP)
        self.cmbHMPKind.setObjectName(_fromUtf8("cmbHMPKind"))
        self.gridLayout_3.addWidget(self.cmbHMPKind, 6, 1, 1, 3)
        self.lblHMPMethod = QtGui.QLabel(self.attrsAP)
        self.lblHMPMethod.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblHMPMethod.setObjectName(_fromUtf8("lblHMPMethod"))
        self.gridLayout_3.addWidget(self.lblHMPMethod, 6, 4, 1, 1)
        self.lblActionMes = QtGui.QLabel(self.attrsAP)
        self.lblActionMes.setObjectName(_fromUtf8("lblActionMes"))
        self.gridLayout_3.addWidget(self.lblActionMes, 6, 6, 1, 1)
        self.cmbActionMes = CMESComboBox(self.attrsAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbActionMes.sizePolicy().hasHeightForWidth())
        self.cmbActionMes.setSizePolicy(sizePolicy)
        self.cmbActionMes.setObjectName(_fromUtf8("cmbActionMes"))
        self.gridLayout_3.addWidget(self.cmbActionMes, 6, 7, 1, 1)
        self.verticalLayout.addWidget(self.attrsAP)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.btnToggleAttrsAP = QtGui.QPushButton(ActionsPageWidget)
        self.btnToggleAttrsAP.setMinimumSize(QtCore.QSize(0, 0))
        self.btnToggleAttrsAP.setMaximumSize(QtCore.QSize(40, 20))
        self.btnToggleAttrsAP.setCheckable(True)
        self.btnToggleAttrsAP.setChecked(False)
        self.btnToggleAttrsAP.setObjectName(_fromUtf8("btnToggleAttrsAP"))
        self.horizontalLayout_7.addWidget(self.btnToggleAttrsAP)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.scrollArea = QtGui.QScrollArea(ActionsPageWidget)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1009, 547))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitterAP = QtGui.QSplitter(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitterAP.sizePolicy().hasHeightForWidth())
        self.splitterAP.setSizePolicy(sizePolicy)
        self.splitterAP.setOrientation(QtCore.Qt.Horizontal)
        self.splitterAP.setChildrenCollapsible(False)
        self.splitterAP.setObjectName(_fromUtf8("splitterAP"))
        self.tblAPActions = CActionsTableView(self.splitterAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblAPActions.sizePolicy().hasHeightForWidth())
        self.tblAPActions.setSizePolicy(sizePolicy)
        self.tblAPActions.setMinimumSize(QtCore.QSize(150, 0))
        self.tblAPActions.setObjectName(_fromUtf8("tblAPActions"))
        self.frameAP = QtGui.QFrame(self.splitterAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameAP.sizePolicy().hasHeightForWidth())
        self.frameAP.setSizePolicy(sizePolicy)
        self.frameAP.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameAP.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAP.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameAP.setObjectName(_fromUtf8("frameAP"))
        self.gridLayout = QtGui.QGridLayout(self.frameAP)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tblAPProps = CExActionPropertiesTableView(self.frameAP)
        self.tblAPProps.setEnabled(False)
        self.tblAPProps.setMinimumSize(QtCore.QSize(0, 250))
        self.tblAPProps.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tblAPProps.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tblAPProps.setObjectName(_fromUtf8("tblAPProps"))
        self.gridLayout.addWidget(self.tblAPProps, 18, 0, 1, 2)
        self.frmAPButtonsBar = QtGui.QFrame(self.frameAP)
        self.frmAPButtonsBar.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPButtonsBar.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPButtonsBar.setLineWidth(0)
        self.frmAPButtonsBar.setObjectName(_fromUtf8("frmAPButtonsBar"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frmAPButtonsBar)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnAPPrint = CPrintButton(self.frmAPButtonsBar)
        self.btnAPPrint.setObjectName(_fromUtf8("btnAPPrint"))
        self.horizontalLayout_4.addWidget(self.btnAPPrint)
        self.btnAPLoadTemplate = CActionTemplateChooseButton(self.frmAPButtonsBar)
        self.btnAPLoadTemplate.setObjectName(_fromUtf8("btnAPLoadTemplate"))
        self.horizontalLayout_4.addWidget(self.btnAPLoadTemplate)
        self.btnAPSaveAsTemplate = QtGui.QPushButton(self.frmAPButtonsBar)
        self.btnAPSaveAsTemplate.setObjectName(_fromUtf8("btnAPSaveAsTemplate"))
        self.horizontalLayout_4.addWidget(self.btnAPSaveAsTemplate)
        self.btnAPLoadPrevAction = QtGui.QPushButton(self.frmAPButtonsBar)
        self.btnAPLoadPrevAction.setEnabled(False)
        self.btnAPLoadPrevAction.setObjectName(_fromUtf8("btnAPLoadPrevAction"))
        self.horizontalLayout_4.addWidget(self.btnAPLoadPrevAction)
        spacerItem = QtGui.QSpacerItem(145, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addWidget(self.frmAPButtonsBar, 19, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.splitterAP)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(ActionsPageWidget)
        QtCore.QObject.connect(self.btnToggleAttrsAP, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.attrsAP.setHidden)
        QtCore.QMetaObject.connectSlotsByName(ActionsPageWidget)
        ActionsPageWidget.setTabOrder(self.cmbAPStatus, self.chkAPIsUrgent)
        ActionsPageWidget.setTabOrder(self.chkAPIsUrgent, self.edtAPDirectionDate)
        ActionsPageWidget.setTabOrder(self.edtAPDirectionDate, self.edtAPDirectionTime)
        ActionsPageWidget.setTabOrder(self.edtAPDirectionTime, self.cmbAPSetPerson)
        ActionsPageWidget.setTabOrder(self.cmbAPSetPerson, self.edtAPBegDate)
        ActionsPageWidget.setTabOrder(self.edtAPBegDate, self.edtAPBegTime)
        ActionsPageWidget.setTabOrder(self.edtAPBegTime, self.edtAPOffice)
        ActionsPageWidget.setTabOrder(self.edtAPOffice, self.edtAPEndDate)
        ActionsPageWidget.setTabOrder(self.edtAPEndDate, self.edtAPEndTime)
        ActionsPageWidget.setTabOrder(self.edtAPEndTime, self.cmbAPPerson)
        ActionsPageWidget.setTabOrder(self.cmbAPPerson, self.cmbAPOrg)
        ActionsPageWidget.setTabOrder(self.cmbAPOrg, self.btnAPSelectOrg)
        ActionsPageWidget.setTabOrder(self.btnAPSelectOrg, self.btnPlanNextAction)
        ActionsPageWidget.setTabOrder(self.btnPlanNextAction, self.btnNextAction)
        ActionsPageWidget.setTabOrder(self.btnNextAction, self.btnReanimation)
        ActionsPageWidget.setTabOrder(self.btnReanimation, self.btnMaternityWard)
        ActionsPageWidget.setTabOrder(self.btnMaternityWard, self.cmbAPMorphologyMKB)
        ActionsPageWidget.setTabOrder(self.cmbAPMorphologyMKB, self.cmbAPAssistant)
        ActionsPageWidget.setTabOrder(self.cmbAPAssistant, self.cmbAPAssistant2)
        ActionsPageWidget.setTabOrder(self.cmbAPAssistant2, self.cmbAPAssistant3)
        ActionsPageWidget.setTabOrder(self.cmbAPAssistant3, self.edtAPAmount)
        ActionsPageWidget.setTabOrder(self.edtAPAmount, self.edtAPUet)
        ActionsPageWidget.setTabOrder(self.edtAPUet, self.edtAPNote)
        ActionsPageWidget.setTabOrder(self.edtAPNote, self.cmbAPMKB)
        ActionsPageWidget.setTabOrder(self.cmbAPMKB, self.cmbHMPKind)
        ActionsPageWidget.setTabOrder(self.cmbHMPKind, self.cmbHMPMethod)
        ActionsPageWidget.setTabOrder(self.cmbHMPMethod, self.cmbActionMes)
        ActionsPageWidget.setTabOrder(self.cmbActionMes, self.btnToggleAttrsAP)
        ActionsPageWidget.setTabOrder(self.btnToggleAttrsAP, self.scrollArea)
        ActionsPageWidget.setTabOrder(self.scrollArea, self.tblAPActions)
        ActionsPageWidget.setTabOrder(self.tblAPActions, self.tblAPProps)
        ActionsPageWidget.setTabOrder(self.tblAPProps, self.btnAPPrint)
        ActionsPageWidget.setTabOrder(self.btnAPPrint, self.btnAPLoadTemplate)
        ActionsPageWidget.setTabOrder(self.btnAPLoadTemplate, self.btnAPSaveAsTemplate)
        ActionsPageWidget.setTabOrder(self.btnAPSaveAsTemplate, self.btnAPLoadPrevAction)

    def retranslateUi(self, ActionsPageWidget):
        ActionsPageWidget.setWindowTitle(_translate("ActionsPageWidget", "Form", None))
        self.edtAPBegDate.setWhatsThis(_translate("ActionsPageWidget", "дата окончания осмотра", None))
        self.edtAPBegTime.setDisplayFormat(_translate("ActionsPageWidget", "HH:mm", None))
        self.lblAPEndDate.setText(_translate("ActionsPageWidget", "Выполнено", None))
        self.cmbHMPMethod.setWhatsThis(_translate("ActionsPageWidget", "результат осмотра", None))
        self.lblAPOffice.setText(_translate("ActionsPageWidget", "Кабинет", None))
        self.lblAPDirectionDate.setText(_translate("ActionsPageWidget", "Назначено", None))
        self.lblAPStatus.setText(_translate("ActionsPageWidget", "Состояние", None))
        self.lblAPOrg.setText(_translate("ActionsPageWidget", "Место выполнения", None))
        self.lblAPBegDate.setText(_translate("ActionsPageWidget", "Начато", None))
        self.cmbAPSetPerson.setItemText(0, _translate("ActionsPageWidget", "Врач", None))
        self.btnPlanNextAction.setText(_translate("ActionsPageWidget", "...", None))
        self.btnNextAction.setText(_translate("ActionsPageWidget", "Действие", None))
        self.btnReanimation.setText(_translate("ActionsPageWidget", "Реанимация", None))
        self.btnMaternityWard.setText(_translate("ActionsPageWidget", "Родовое", None))
        self.cmbAPPerson.setItemText(0, _translate("ActionsPageWidget", "Врач", None))
        self.lblAPPerson.setText(_translate("ActionsPageWidget", "Исполнитель", None))
        self.lblAPSetPerson.setText(_translate("ActionsPageWidget", "Назначил", None))
        self.edtAPEndTime.setDisplayFormat(_translate("ActionsPageWidget", "HH:mm", None))
        self.edtAPDirectionDate.setWhatsThis(_translate("ActionsPageWidget", "дата начала осмотра", None))
        self.edtAPDirectionTime.setDisplayFormat(_translate("ActionsPageWidget", "HH:mm", None))
        self.chkAPIsUrgent.setText(_translate("ActionsPageWidget", "Срочно", None))
        self.lblAPAssistant.setText(_translate("ActionsPageWidget", "Ассистент", None))
        self.cmbAPAssistant.setItemText(0, _translate("ActionsPageWidget", "Врач", None))
        self.lblAPAssistant2.setText(_translate("ActionsPageWidget", "Ассистент2", None))
        self.lblAPAssistant3.setText(_translate("ActionsPageWidget", "Ассистент3", None))
        self.lblAPAmount.setText(_translate("ActionsPageWidget", "Количество", None))
        self.lblAPUet.setText(_translate("ActionsPageWidget", "УЕТ", None))
        self.lblAPNote.setText(_translate("ActionsPageWidget", "Примечания", None))
        self.lblAPMKB.setText(_translate("ActionsPageWidget", "Диагноз", None))
        self.cmbAPOrg.setItemText(0, _translate("ActionsPageWidget", "Организация", None))
        self.btnAPSelectOrg.setText(_translate("ActionsPageWidget", "...", None))
        self.lblAPMorphologyMKB.setText(_translate("ActionsPageWidget", "Морфология МКБ", None))
        self.lblHMPKind.setText(_translate("ActionsPageWidget", "Вид ВМП", None))
        self.cmbHMPKind.setWhatsThis(_translate("ActionsPageWidget", "результат осмотра", None))
        self.lblHMPMethod.setText(_translate("ActionsPageWidget", "Метод ВМП", None))
        self.lblActionMes.setText(_translate("ActionsPageWidget", "Стандарт", None))
        self.btnToggleAttrsAP.setText(_translate("ActionsPageWidget", "^", None))
        self.btnAPPrint.setText(_translate("ActionsPageWidget", "Печать", None))
        self.btnAPLoadTemplate.setText(_translate("ActionsPageWidget", "Загрузить шаблон", None))
        self.btnAPSaveAsTemplate.setText(_translate("ActionsPageWidget", "Сохранить шаблон", None))
        self.btnAPLoadPrevAction.setText(_translate("ActionsPageWidget", "Копировать из предыдущего", None))

from Events.ActionPropertiesTable import CExActionPropertiesTableView
from Events.ActionTemplateChoose import CActionTemplateChooseButton
from Events.ActionsTable import CActionsTableView
from Orgs.OrgComboBox import CPolyclinicExtendedComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEditEx
from library.ICDMorphologyCodeEdit import CICDMorphologyCodeEditEx
from library.MES.MESComboBox import CMESComboBox
from library.PrintTemplates import CPrintButton
from library.crbcombobox import CRBComboBox
