# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EventCashPage.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EventCashPageWidget(object):
    def setupUi(self, EventCashPageWidget):
        EventCashPageWidget.setObjectName(_fromUtf8("EventCashPageWidget"))
        EventCashPageWidget.resize(872, 748)
        self.verticalLayout_4 = QtGui.QVBoxLayout(EventCashPageWidget)
        self.verticalLayout_4.setMargin(4)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabCach = QtGui.QTabWidget(EventCashPageWidget)
        self.tabCach.setDocumentMode(False)
        self.tabCach.setTabsClosable(False)
        self.tabCach.setMovable(False)
        self.tabCach.setObjectName(_fromUtf8("tabCach"))
        self.tabCoordination = QtGui.QWidget()
        self.tabCoordination.setObjectName(_fromUtf8("tabCoordination"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabCoordination)
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.tabCoordination)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 848, 697))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.grpLocalContract = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.grpLocalContract.setCheckable(True)
        self.grpLocalContract.setChecked(False)
        self.grpLocalContract.setObjectName(_fromUtf8("grpLocalContract"))
        self.gridLayout_4 = QtGui.QGridLayout(self.grpLocalContract)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.grpPayer = QtGui.QGroupBox(self.grpLocalContract)
        self.grpPayer.setObjectName(_fromUtf8("grpPayer"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grpPayer)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.edtPatrName = CPatrNameEditor(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPatrName.sizePolicy().hasHeightForWidth())
        self.edtPatrName.setSizePolicy(sizePolicy)
        self.edtPatrName.setObjectName(_fromUtf8("edtPatrName"))
        self.gridLayout_3.addWidget(self.edtPatrName, 2, 1, 1, 2)
        self.edtRegAddress = QtGui.QLineEdit(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtRegAddress.sizePolicy().hasHeightForWidth())
        self.edtRegAddress.setSizePolicy(sizePolicy)
        self.edtRegAddress.setObjectName(_fromUtf8("edtRegAddress"))
        self.gridLayout_3.addWidget(self.edtRegAddress, 5, 1, 1, 7)
        self.lblDocNumber = QtGui.QLabel(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDocNumber.sizePolicy().hasHeightForWidth())
        self.lblDocNumber.setSizePolicy(sizePolicy)
        self.lblDocNumber.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDocNumber.setObjectName(_fromUtf8("lblDocNumber"))
        self.gridLayout_3.addWidget(self.lblDocNumber, 4, 6, 1, 1)
        self.edtDocSerialRight = CDocSerialRightEdit(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDocSerialRight.sizePolicy().hasHeightForWidth())
        self.edtDocSerialRight.setSizePolicy(sizePolicy)
        self.edtDocSerialRight.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtDocSerialRight.setMaxLength(8)
        self.edtDocSerialRight.setObjectName(_fromUtf8("edtDocSerialRight"))
        self.gridLayout_3.addWidget(self.edtDocSerialRight, 4, 5, 1, 1)
        self.lblStreetReg = QtGui.QLabel(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStreetReg.sizePolicy().hasHeightForWidth())
        self.lblStreetReg.setSizePolicy(sizePolicy)
        self.lblStreetReg.setMinimumSize(QtCore.QSize(106, 0))
        self.lblStreetReg.setObjectName(_fromUtf8("lblStreetReg"))
        self.gridLayout_3.addWidget(self.lblStreetReg, 5, 0, 1, 1)
        self.edtDocSerialLeft = CDocSerialLeftEdit(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDocSerialLeft.sizePolicy().hasHeightForWidth())
        self.edtDocSerialLeft.setSizePolicy(sizePolicy)
        self.edtDocSerialLeft.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtDocSerialLeft.setMaxLength(8)
        self.edtDocSerialLeft.setEchoMode(QtGui.QLineEdit.Normal)
        self.edtDocSerialLeft.setObjectName(_fromUtf8("edtDocSerialLeft"))
        self.gridLayout_3.addWidget(self.edtDocSerialLeft, 4, 4, 1, 1)
        self.edtBirthDate = CDateEdit(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBirthDate.sizePolicy().hasHeightForWidth())
        self.edtBirthDate.setSizePolicy(sizePolicy)
        self.edtBirthDate.setProperty("calendarPopup", True)
        self.edtBirthDate.setObjectName(_fromUtf8("edtBirthDate"))
        self.gridLayout_3.addWidget(self.edtBirthDate, 3, 1, 1, 1)
        self.edtFirstName = CFirstNameEditor(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFirstName.sizePolicy().hasHeightForWidth())
        self.edtFirstName.setSizePolicy(sizePolicy)
        self.edtFirstName.setObjectName(_fromUtf8("edtFirstName"))
        self.gridLayout_3.addWidget(self.edtFirstName, 1, 1, 1, 2)
        self.cmbOrganisation = COrgComboBox(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrganisation.sizePolicy().hasHeightForWidth())
        self.cmbOrganisation.setSizePolicy(sizePolicy)
        self.cmbOrganisation.setObjectName(_fromUtf8("cmbOrganisation"))
        self.gridLayout_3.addWidget(self.cmbOrganisation, 6, 1, 1, 7)
        self.edtLastName = QtGui.QLineEdit(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtLastName.sizePolicy().hasHeightForWidth())
        self.edtLastName.setSizePolicy(sizePolicy)
        self.edtLastName.setObjectName(_fromUtf8("edtLastName"))
        self.gridLayout_3.addWidget(self.edtLastName, 0, 1, 1, 2)
        self.lblDocument = QtGui.QLabel(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDocument.sizePolicy().hasHeightForWidth())
        self.lblDocument.setSizePolicy(sizePolicy)
        self.lblDocument.setMinimumSize(QtCore.QSize(106, 0))
        self.lblDocument.setObjectName(_fromUtf8("lblDocument"))
        self.gridLayout_3.addWidget(self.lblDocument, 4, 0, 1, 1)
        self.cmbDocType = CRBComboBox(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDocType.sizePolicy().hasHeightForWidth())
        self.cmbDocType.setSizePolicy(sizePolicy)
        self.cmbDocType.setMinimumSize(QtCore.QSize(150, 0))
        self.cmbDocType.setObjectName(_fromUtf8("cmbDocType"))
        self.gridLayout_3.addWidget(self.cmbDocType, 4, 1, 1, 2)
        self.lblPatrName = QtGui.QLabel(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPatrName.sizePolicy().hasHeightForWidth())
        self.lblPatrName.setSizePolicy(sizePolicy)
        self.lblPatrName.setMinimumSize(QtCore.QSize(106, 0))
        self.lblPatrName.setObjectName(_fromUtf8("lblPatrName"))
        self.gridLayout_3.addWidget(self.lblPatrName, 2, 0, 1, 1)
        self.lblOrganisation = QtGui.QLabel(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrganisation.sizePolicy().hasHeightForWidth())
        self.lblOrganisation.setSizePolicy(sizePolicy)
        self.lblOrganisation.setMinimumSize(QtCore.QSize(106, 0))
        self.lblOrganisation.setObjectName(_fromUtf8("lblOrganisation"))
        self.gridLayout_3.addWidget(self.lblOrganisation, 6, 0, 1, 1)
        self.lblFirstName = QtGui.QLabel(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFirstName.sizePolicy().hasHeightForWidth())
        self.lblFirstName.setSizePolicy(sizePolicy)
        self.lblFirstName.setMinimumSize(QtCore.QSize(106, 0))
        self.lblFirstName.setObjectName(_fromUtf8("lblFirstName"))
        self.gridLayout_3.addWidget(self.lblFirstName, 1, 0, 1, 1)
        self.btnGetClientInfo = QtGui.QToolButton(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGetClientInfo.sizePolicy().hasHeightForWidth())
        self.btnGetClientInfo.setSizePolicy(sizePolicy)
        self.btnGetClientInfo.setObjectName(_fromUtf8("btnGetClientInfo"))
        self.gridLayout_3.addWidget(self.btnGetClientInfo, 0, 3, 1, 1)
        self.btnSelectOrganisation = QtGui.QToolButton(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectOrganisation.sizePolicy().hasHeightForWidth())
        self.btnSelectOrganisation.setSizePolicy(sizePolicy)
        self.btnSelectOrganisation.setObjectName(_fromUtf8("btnSelectOrganisation"))
        self.gridLayout_3.addWidget(self.btnSelectOrganisation, 6, 8, 1, 1)
        self.lblDocSerial = QtGui.QLabel(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDocSerial.sizePolicy().hasHeightForWidth())
        self.lblDocSerial.setSizePolicy(sizePolicy)
        self.lblDocSerial.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDocSerial.setObjectName(_fromUtf8("lblDocSerial"))
        self.gridLayout_3.addWidget(self.lblDocSerial, 4, 3, 1, 1)
        self.edtDocNumber = QtGui.QLineEdit(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDocNumber.sizePolicy().hasHeightForWidth())
        self.edtDocNumber.setSizePolicy(sizePolicy)
        self.edtDocNumber.setMaxLength(16)
        self.edtDocNumber.setObjectName(_fromUtf8("edtDocNumber"))
        self.gridLayout_3.addWidget(self.edtDocNumber, 4, 7, 1, 1)
        self.lblBirthDate = QtGui.QLabel(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBirthDate.sizePolicy().hasHeightForWidth())
        self.lblBirthDate.setSizePolicy(sizePolicy)
        self.lblBirthDate.setMinimumSize(QtCore.QSize(106, 0))
        self.lblBirthDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblBirthDate.setObjectName(_fromUtf8("lblBirthDate"))
        self.gridLayout_3.addWidget(self.lblBirthDate, 3, 0, 1, 1)
        self.lblLastName = QtGui.QLabel(self.grpPayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLastName.sizePolicy().hasHeightForWidth())
        self.lblLastName.setSizePolicy(sizePolicy)
        self.lblLastName.setMinimumSize(QtCore.QSize(106, 0))
        self.lblLastName.setObjectName(_fromUtf8("lblLastName"))
        self.gridLayout_3.addWidget(self.lblLastName, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 6, 9, 1, 1)
        self.gridLayout_4.addWidget(self.grpPayer, 9, 0, 1, 4)
        self.lblCoordInspector = QtGui.QLabel(self.grpLocalContract)
        self.lblCoordInspector.setMinimumSize(QtCore.QSize(0, 0))
        self.lblCoordInspector.setObjectName(_fromUtf8("lblCoordInspector"))
        self.gridLayout_4.addWidget(self.lblCoordInspector, 2, 0, 2, 1)
        self.groupBox = QtGui.QGroupBox(self.grpLocalContract)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblSumLimit = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSumLimit.sizePolicy().hasHeightForWidth())
        self.lblSumLimit.setSizePolicy(sizePolicy)
        self.lblSumLimit.setMinimumSize(QtCore.QSize(106, 0))
        self.lblSumLimit.setObjectName(_fromUtf8("lblSumLimit"))
        self.gridLayout.addWidget(self.lblSumLimit, 2, 0, 1, 1)
        self.lblContractDate = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblContractDate.sizePolicy().hasHeightForWidth())
        self.lblContractDate.setSizePolicy(sizePolicy)
        self.lblContractDate.setMinimumSize(QtCore.QSize(106, 0))
        self.lblContractDate.setObjectName(_fromUtf8("lblContractDate"))
        self.gridLayout.addWidget(self.lblContractDate, 0, 0, 1, 1)
        self.edtContractNumber = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtContractNumber.sizePolicy().hasHeightForWidth())
        self.edtContractNumber.setSizePolicy(sizePolicy)
        self.edtContractNumber.setObjectName(_fromUtf8("edtContractNumber"))
        self.gridLayout.addWidget(self.edtContractNumber, 1, 1, 1, 1)
        self.btnGetExternalId = QtGui.QToolButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGetExternalId.sizePolicy().hasHeightForWidth())
        self.btnGetExternalId.setSizePolicy(sizePolicy)
        self.btnGetExternalId.setObjectName(_fromUtf8("btnGetExternalId"))
        self.gridLayout.addWidget(self.btnGetExternalId, 1, 2, 1, 1)
        self.edtContractDate = CDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtContractDate.sizePolicy().hasHeightForWidth())
        self.edtContractDate.setSizePolicy(sizePolicy)
        self.edtContractDate.setProperty("calendarPopup", True)
        self.edtContractDate.setObjectName(_fromUtf8("edtContractDate"))
        self.gridLayout.addWidget(self.edtContractDate, 0, 1, 1, 1)
        self.lblNumberContract = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNumberContract.sizePolicy().hasHeightForWidth())
        self.lblNumberContract.setSizePolicy(sizePolicy)
        self.lblNumberContract.setMinimumSize(QtCore.QSize(106, 0))
        self.lblNumberContract.setToolTip(_fromUtf8(""))
        self.lblNumberContract.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblNumberContract.setObjectName(_fromUtf8("lblNumberContract"))
        self.gridLayout.addWidget(self.lblNumberContract, 1, 0, 1, 1)
        self.edtSumLimit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtSumLimit.sizePolicy().hasHeightForWidth())
        self.edtSumLimit.setSizePolicy(sizePolicy)
        self.edtSumLimit.setObjectName(_fromUtf8("edtSumLimit"))
        self.gridLayout.addWidget(self.edtSumLimit, 2, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 8, 0, 1, 4)
        self.edtCoordAgent = QtGui.QLineEdit(self.grpLocalContract)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtCoordAgent.sizePolicy().hasHeightForWidth())
        self.edtCoordAgent.setSizePolicy(sizePolicy)
        self.edtCoordAgent.setObjectName(_fromUtf8("edtCoordAgent"))
        self.gridLayout_4.addWidget(self.edtCoordAgent, 1, 1, 1, 2)
        self.edtCoordDate = CDateEdit(self.grpLocalContract)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtCoordDate.sizePolicy().hasHeightForWidth())
        self.edtCoordDate.setSizePolicy(sizePolicy)
        self.edtCoordDate.setProperty("calendarPopup", True)
        self.edtCoordDate.setObjectName(_fromUtf8("edtCoordDate"))
        self.gridLayout_4.addWidget(self.edtCoordDate, 0, 1, 1, 1)
        self.lblCoordDate = QtGui.QLabel(self.grpLocalContract)
        self.lblCoordDate.setEnabled(False)
        self.lblCoordDate.setMinimumSize(QtCore.QSize(0, 0))
        self.lblCoordDate.setObjectName(_fromUtf8("lblCoordDate"))
        self.gridLayout_4.addWidget(self.lblCoordDate, 0, 0, 1, 1)
        self.edtCoordInspector = QtGui.QLineEdit(self.grpLocalContract)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtCoordInspector.sizePolicy().hasHeightForWidth())
        self.edtCoordInspector.setSizePolicy(sizePolicy)
        self.edtCoordInspector.setObjectName(_fromUtf8("edtCoordInspector"))
        self.gridLayout_4.addWidget(self.edtCoordInspector, 2, 1, 2, 2)
        self.lblCoordAgent = QtGui.QLabel(self.grpLocalContract)
        self.lblCoordAgent.setMinimumSize(QtCore.QSize(0, 0))
        self.lblCoordAgent.setObjectName(_fromUtf8("lblCoordAgent"))
        self.gridLayout_4.addWidget(self.lblCoordAgent, 1, 0, 1, 1)
        self.lblCoordText = QtGui.QLabel(self.grpLocalContract)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCoordText.sizePolicy().hasHeightForWidth())
        self.lblCoordText.setSizePolicy(sizePolicy)
        self.lblCoordText.setMinimumSize(QtCore.QSize(0, 0))
        self.lblCoordText.setObjectName(_fromUtf8("lblCoordText"))
        self.gridLayout_4.addWidget(self.lblCoordText, 4, 0, 2, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 6, 0, 1, 1)
        self.edtCoordText = QtGui.QTextEdit(self.grpLocalContract)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtCoordText.sizePolicy().hasHeightForWidth())
        self.edtCoordText.setSizePolicy(sizePolicy)
        self.edtCoordText.setObjectName(_fromUtf8("edtCoordText"))
        self.gridLayout_4.addWidget(self.edtCoordText, 4, 1, 3, 2)
        self.horizontalLayout_8.addWidget(self.grpLocalContract)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.tabCach.addTab(self.tabCoordination, _fromUtf8(""))
        self.tabActionsAndCash = QtGui.QWidget()
        self.tabActionsAndCash.setObjectName(_fromUtf8("tabActionsAndCash"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabActionsAndCash)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tabActionsAndCash)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 824, 669))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(self.scrollAreaWidgetContents_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.grpActions = QtGui.QGroupBox(self.splitter)
        self.grpActions.setObjectName(_fromUtf8("grpActions"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.grpActions)
        self.horizontalLayout_4.setMargin(4)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tblAccActions = CInDocTableView(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tblAccActions.sizePolicy().hasHeightForWidth())
        self.tblAccActions.setSizePolicy(sizePolicy)
        self.tblAccActions.setObjectName(_fromUtf8("tblAccActions"))
        self.horizontalLayout_4.addWidget(self.tblAccActions)
        self.grpActionsDetail = QtGui.QWidget(self.grpActions)
        self.grpActionsDetail.setObjectName(_fromUtf8("grpActionsDetail"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpActionsDetail)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblAPDirectionDate = QtGui.QLabel(self.grpActionsDetail)
        self.lblAPDirectionDate.setObjectName(_fromUtf8("lblAPDirectionDate"))
        self.gridLayout_2.addWidget(self.lblAPDirectionDate, 0, 0, 1, 1)
        self.frmAPDirectionDateTime = QtGui.QFrame(self.grpActionsDetail)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPDirectionDateTime.sizePolicy().hasHeightForWidth())
        self.frmAPDirectionDateTime.setSizePolicy(sizePolicy)
        self.frmAPDirectionDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPDirectionDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPDirectionDateTime.setObjectName(_fromUtf8("frmAPDirectionDateTime"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frmAPDirectionDateTime)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtAPDirectionDate = CDateEdit(self.frmAPDirectionDateTime)
        self.edtAPDirectionDate.setEnabled(False)
        self.edtAPDirectionDate.setProperty("calendarPopup", True)
        self.edtAPDirectionDate.setObjectName(_fromUtf8("edtAPDirectionDate"))
        self.horizontalLayout.addWidget(self.edtAPDirectionDate)
        self.edtAPDirectionTime = QtGui.QTimeEdit(self.frmAPDirectionDateTime)
        self.edtAPDirectionTime.setEnabled(False)
        self.edtAPDirectionTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPDirectionTime.setObjectName(_fromUtf8("edtAPDirectionTime"))
        self.horizontalLayout.addWidget(self.edtAPDirectionTime)
        self.gridLayout_2.addWidget(self.frmAPDirectionDateTime, 0, 1, 1, 1)
        self.chkAPIsUrgent = QtGui.QCheckBox(self.grpActionsDetail)
        self.chkAPIsUrgent.setEnabled(False)
        self.chkAPIsUrgent.setObjectName(_fromUtf8("chkAPIsUrgent"))
        self.gridLayout_2.addWidget(self.chkAPIsUrgent, 0, 2, 1, 1)
        self.lblAPPlannedEndDate = QtGui.QLabel(self.grpActionsDetail)
        self.lblAPPlannedEndDate.setObjectName(_fromUtf8("lblAPPlannedEndDate"))
        self.gridLayout_2.addWidget(self.lblAPPlannedEndDate, 1, 0, 1, 1)
        self.frmAPPlannedEndDateTime = QtGui.QFrame(self.grpActionsDetail)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPPlannedEndDateTime.sizePolicy().hasHeightForWidth())
        self.frmAPPlannedEndDateTime.setSizePolicy(sizePolicy)
        self.frmAPPlannedEndDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPPlannedEndDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPPlannedEndDateTime.setObjectName(_fromUtf8("frmAPPlannedEndDateTime"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frmAPPlannedEndDateTime)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.edtAPPlannedEndDate = CDateEdit(self.frmAPPlannedEndDateTime)
        self.edtAPPlannedEndDate.setEnabled(False)
        self.edtAPPlannedEndDate.setProperty("calendarPopup", True)
        self.edtAPPlannedEndDate.setObjectName(_fromUtf8("edtAPPlannedEndDate"))
        self.horizontalLayout_5.addWidget(self.edtAPPlannedEndDate)
        self.edtAPPlannedEndTime = QtGui.QTimeEdit(self.frmAPPlannedEndDateTime)
        self.edtAPPlannedEndTime.setEnabled(False)
        self.edtAPPlannedEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPPlannedEndTime.setObjectName(_fromUtf8("edtAPPlannedEndTime"))
        self.horizontalLayout_5.addWidget(self.edtAPPlannedEndTime)
        self.gridLayout_2.addWidget(self.frmAPPlannedEndDateTime, 1, 1, 1, 1)
        self.lblAPSetPerson = QtGui.QLabel(self.grpActionsDetail)
        self.lblAPSetPerson.setObjectName(_fromUtf8("lblAPSetPerson"))
        self.gridLayout_2.addWidget(self.lblAPSetPerson, 2, 0, 1, 1)
        self.cmbAPSetPerson = CPersonComboBoxEx(self.grpActionsDetail)
        self.cmbAPSetPerson.setEnabled(False)
        self.cmbAPSetPerson.setObjectName(_fromUtf8("cmbAPSetPerson"))
        self.cmbAPSetPerson.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbAPSetPerson, 2, 1, 1, 2)
        self.lblAPCoordDate = QtGui.QLabel(self.grpActionsDetail)
        self.lblAPCoordDate.setObjectName(_fromUtf8("lblAPCoordDate"))
        self.gridLayout_2.addWidget(self.lblAPCoordDate, 3, 0, 1, 1)
        self.frmAPCoordDate = QtGui.QFrame(self.grpActionsDetail)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPCoordDate.sizePolicy().hasHeightForWidth())
        self.frmAPCoordDate.setSizePolicy(sizePolicy)
        self.frmAPCoordDate.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPCoordDate.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPCoordDate.setObjectName(_fromUtf8("frmAPCoordDate"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frmAPCoordDate)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.edtAPCoordDate = CDateEdit(self.frmAPCoordDate)
        self.edtAPCoordDate.setEnabled(True)
        self.edtAPCoordDate.setProperty("calendarPopup", True)
        self.edtAPCoordDate.setObjectName(_fromUtf8("edtAPCoordDate"))
        self.horizontalLayout_6.addWidget(self.edtAPCoordDate)
        self.edtAPCoordTime = QtGui.QTimeEdit(self.frmAPCoordDate)
        self.edtAPCoordTime.setEnabled(True)
        self.edtAPCoordTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPCoordTime.setObjectName(_fromUtf8("edtAPCoordTime"))
        self.horizontalLayout_6.addWidget(self.edtAPCoordTime)
        self.gridLayout_2.addWidget(self.frmAPCoordDate, 3, 1, 1, 1)
        self.lblAPStatus = QtGui.QLabel(self.grpActionsDetail)
        self.lblAPStatus.setObjectName(_fromUtf8("lblAPStatus"))
        self.gridLayout_2.addWidget(self.lblAPStatus, 8, 0, 1, 1)
        self.cmbAPStatus = QtGui.QComboBox(self.grpActionsDetail)
        self.cmbAPStatus.setEnabled(False)
        self.cmbAPStatus.setObjectName(_fromUtf8("cmbAPStatus"))
        self.gridLayout_2.addWidget(self.cmbAPStatus, 8, 1, 1, 1)
        self.lblAPBegDate = QtGui.QLabel(self.grpActionsDetail)
        self.lblAPBegDate.setObjectName(_fromUtf8("lblAPBegDate"))
        self.gridLayout_2.addWidget(self.lblAPBegDate, 9, 0, 1, 1)
        self.frmAPBegDateTime = QtGui.QFrame(self.grpActionsDetail)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPBegDateTime.sizePolicy().hasHeightForWidth())
        self.frmAPBegDateTime.setSizePolicy(sizePolicy)
        self.frmAPBegDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPBegDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPBegDateTime.setObjectName(_fromUtf8("frmAPBegDateTime"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frmAPBegDateTime)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.edtAPBegDate = CDateEdit(self.frmAPBegDateTime)
        self.edtAPBegDate.setEnabled(False)
        self.edtAPBegDate.setProperty("calendarPopup", True)
        self.edtAPBegDate.setObjectName(_fromUtf8("edtAPBegDate"))
        self.horizontalLayout_2.addWidget(self.edtAPBegDate)
        self.edtAPBegTime = QtGui.QTimeEdit(self.frmAPBegDateTime)
        self.edtAPBegTime.setEnabled(False)
        self.edtAPBegTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPBegTime.setObjectName(_fromUtf8("edtAPBegTime"))
        self.horizontalLayout_2.addWidget(self.edtAPBegTime)
        self.gridLayout_2.addWidget(self.frmAPBegDateTime, 9, 1, 1, 1)
        self.lblAPEndDate = QtGui.QLabel(self.grpActionsDetail)
        self.lblAPEndDate.setObjectName(_fromUtf8("lblAPEndDate"))
        self.gridLayout_2.addWidget(self.lblAPEndDate, 10, 0, 1, 1)
        self.frmAPEndDateTime = QtGui.QFrame(self.grpActionsDetail)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPEndDateTime.sizePolicy().hasHeightForWidth())
        self.frmAPEndDateTime.setSizePolicy(sizePolicy)
        self.frmAPEndDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPEndDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPEndDateTime.setObjectName(_fromUtf8("frmAPEndDateTime"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frmAPEndDateTime)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.edtAPEndDate = CDateEdit(self.frmAPEndDateTime)
        self.edtAPEndDate.setEnabled(False)
        self.edtAPEndDate.setProperty("calendarPopup", True)
        self.edtAPEndDate.setObjectName(_fromUtf8("edtAPEndDate"))
        self.horizontalLayout_3.addWidget(self.edtAPEndDate)
        self.edtAPEndTime = QtGui.QTimeEdit(self.frmAPEndDateTime)
        self.edtAPEndTime.setEnabled(False)
        self.edtAPEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPEndTime.setObjectName(_fromUtf8("edtAPEndTime"))
        self.horizontalLayout_3.addWidget(self.edtAPEndTime)
        self.gridLayout_2.addWidget(self.frmAPEndDateTime, 10, 1, 1, 1)
        self.lblAPPerson = QtGui.QLabel(self.grpActionsDetail)
        self.lblAPPerson.setObjectName(_fromUtf8("lblAPPerson"))
        self.gridLayout_2.addWidget(self.lblAPPerson, 11, 0, 1, 1)
        self.cmbAPPerson = CPersonComboBoxEx(self.grpActionsDetail)
        self.cmbAPPerson.setEnabled(False)
        self.cmbAPPerson.setObjectName(_fromUtf8("cmbAPPerson"))
        self.cmbAPPerson.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbAPPerson, 11, 1, 1, 2)
        self.lblAPOffice = QtGui.QLabel(self.grpActionsDetail)
        self.lblAPOffice.setObjectName(_fromUtf8("lblAPOffice"))
        self.gridLayout_2.addWidget(self.lblAPOffice, 12, 0, 1, 1)
        self.edtAPOffice = QtGui.QLineEdit(self.grpActionsDetail)
        self.edtAPOffice.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPOffice.sizePolicy().hasHeightForWidth())
        self.edtAPOffice.setSizePolicy(sizePolicy)
        self.edtAPOffice.setMaxLength(16)
        self.edtAPOffice.setObjectName(_fromUtf8("edtAPOffice"))
        self.gridLayout_2.addWidget(self.edtAPOffice, 12, 1, 1, 1)
        self.lblAPNote = QtGui.QLabel(self.grpActionsDetail)
        self.lblAPNote.setObjectName(_fromUtf8("lblAPNote"))
        self.gridLayout_2.addWidget(self.lblAPNote, 13, 0, 1, 1)
        self.edtAPNote = QtGui.QLineEdit(self.grpActionsDetail)
        self.edtAPNote.setEnabled(False)
        self.edtAPNote.setObjectName(_fromUtf8("edtAPNote"))
        self.gridLayout_2.addWidget(self.edtAPNote, 13, 1, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 14, 1, 1, 1)
        self.edtAPCoordInspector = QtGui.QLineEdit(self.grpActionsDetail)
        self.edtAPCoordInspector.setObjectName(_fromUtf8("edtAPCoordInspector"))
        self.gridLayout_2.addWidget(self.edtAPCoordInspector, 5, 1, 1, 2)
        self.edtAPCoordText = QtGui.QTextEdit(self.grpActionsDetail)
        self.edtAPCoordText.setObjectName(_fromUtf8("edtAPCoordText"))
        self.gridLayout_2.addWidget(self.edtAPCoordText, 6, 1, 2, 2)
        self.edtAPCoordAgent = QtGui.QLineEdit(self.grpActionsDetail)
        self.edtAPCoordAgent.setObjectName(_fromUtf8("edtAPCoordAgent"))
        self.gridLayout_2.addWidget(self.edtAPCoordAgent, 4, 1, 1, 2)
        self.lblAPCoordAgent = QtGui.QLabel(self.grpActionsDetail)
        self.lblAPCoordAgent.setObjectName(_fromUtf8("lblAPCoordAgent"))
        self.gridLayout_2.addWidget(self.lblAPCoordAgent, 4, 0, 1, 1)
        self.lblAPCoordInspector = QtGui.QLabel(self.grpActionsDetail)
        self.lblAPCoordInspector.setObjectName(_fromUtf8("lblAPCoordInspector"))
        self.gridLayout_2.addWidget(self.lblAPCoordInspector, 5, 0, 1, 1)
        self.lblAPCoordText = QtGui.QLabel(self.grpActionsDetail)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPCoordText.sizePolicy().hasHeightForWidth())
        self.lblAPCoordText.setSizePolicy(sizePolicy)
        self.lblAPCoordText.setMinimumSize(QtCore.QSize(0, 20))
        self.lblAPCoordText.setObjectName(_fromUtf8("lblAPCoordText"))
        self.gridLayout_2.addWidget(self.lblAPCoordText, 6, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 7, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.grpActionsDetail)
        self.grpCash = QtGui.QGroupBox(self.splitter)
        self.grpCash.setObjectName(_fromUtf8("grpCash"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.grpCash)
        self.verticalLayout_3.setMargin(4)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tblPayments = CInDocTableView(self.grpCash)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tblPayments.sizePolicy().hasHeightForWidth())
        self.tblPayments.setSizePolicy(sizePolicy)
        self.tblPayments.setObjectName(_fromUtf8("tblPayments"))
        self.verticalLayout_3.addWidget(self.tblPayments)
        self.verticalLayout.addWidget(self.splitter)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.scrollArea_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lblPaymentAcc = QtGui.QLabel(self.tabActionsAndCash)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPaymentAcc.sizePolicy().hasHeightForWidth())
        self.lblPaymentAcc.setSizePolicy(sizePolicy)
        self.lblPaymentAcc.setObjectName(_fromUtf8("lblPaymentAcc"))
        self.horizontalLayout_7.addWidget(self.lblPaymentAcc)
        self.lblPaymentAccValue = QtGui.QLabel(self.tabActionsAndCash)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPaymentAccValue.sizePolicy().hasHeightForWidth())
        self.lblPaymentAccValue.setSizePolicy(sizePolicy)
        self.lblPaymentAccValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblPaymentAccValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblPaymentAccValue.setScaledContents(False)
        self.lblPaymentAccValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPaymentAccValue.setObjectName(_fromUtf8("lblPaymentAccValue"))
        self.horizontalLayout_7.addWidget(self.lblPaymentAccValue)
        self.lblPaymentPayedSum = QtGui.QLabel(self.tabActionsAndCash)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPaymentPayedSum.sizePolicy().hasHeightForWidth())
        self.lblPaymentPayedSum.setSizePolicy(sizePolicy)
        self.lblPaymentPayedSum.setObjectName(_fromUtf8("lblPaymentPayedSum"))
        self.horizontalLayout_7.addWidget(self.lblPaymentPayedSum)
        self.lblPaymentPayedSumValue = QtGui.QLabel(self.tabActionsAndCash)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPaymentPayedSumValue.sizePolicy().hasHeightForWidth())
        self.lblPaymentPayedSumValue.setSizePolicy(sizePolicy)
        self.lblPaymentPayedSumValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblPaymentPayedSumValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblPaymentPayedSumValue.setScaledContents(False)
        self.lblPaymentPayedSumValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPaymentPayedSumValue.setObjectName(_fromUtf8("lblPaymentPayedSumValue"))
        self.horizontalLayout_7.addWidget(self.lblPaymentPayedSumValue)
        self.lblPaymentTotal = QtGui.QLabel(self.tabActionsAndCash)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPaymentTotal.sizePolicy().hasHeightForWidth())
        self.lblPaymentTotal.setSizePolicy(sizePolicy)
        self.lblPaymentTotal.setObjectName(_fromUtf8("lblPaymentTotal"))
        self.horizontalLayout_7.addWidget(self.lblPaymentTotal)
        self.lblPaymentTotalValue = QtGui.QLabel(self.tabActionsAndCash)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPaymentTotalValue.sizePolicy().hasHeightForWidth())
        self.lblPaymentTotalValue.setSizePolicy(sizePolicy)
        self.lblPaymentTotalValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblPaymentTotalValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblPaymentTotalValue.setScaledContents(False)
        self.lblPaymentTotalValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPaymentTotalValue.setObjectName(_fromUtf8("lblPaymentTotalValue"))
        self.horizontalLayout_7.addWidget(self.lblPaymentTotalValue)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.tabCach.addTab(self.tabActionsAndCash, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabCach)
        self.lblDocNumber.setBuddy(self.edtDocNumber)
        self.lblStreetReg.setBuddy(self.edtRegAddress)
        self.lblDocument.setBuddy(self.cmbDocType)
        self.lblPatrName.setBuddy(self.edtPatrName)
        self.lblFirstName.setBuddy(self.edtFirstName)
        self.lblDocSerial.setBuddy(self.edtDocSerialLeft)
        self.lblBirthDate.setBuddy(self.edtBirthDate)
        self.lblLastName.setBuddy(self.edtLastName)
        self.lblCoordInspector.setBuddy(self.edtCoordInspector)
        self.lblSumLimit.setBuddy(self.edtSumLimit)
        self.lblContractDate.setBuddy(self.edtContractDate)
        self.lblNumberContract.setBuddy(self.edtContractNumber)
        self.lblCoordDate.setBuddy(self.edtCoordDate)
        self.lblCoordAgent.setBuddy(self.edtCoordAgent)
        self.lblCoordText.setBuddy(self.edtCoordText)
        self.lblAPDirectionDate.setBuddy(self.edtAPDirectionDate)
        self.lblAPPlannedEndDate.setBuddy(self.edtAPPlannedEndDate)
        self.lblAPSetPerson.setBuddy(self.cmbAPSetPerson)
        self.lblAPCoordDate.setBuddy(self.edtAPCoordDate)
        self.lblAPStatus.setBuddy(self.cmbAPStatus)
        self.lblAPBegDate.setBuddy(self.edtAPBegDate)
        self.lblAPEndDate.setBuddy(self.edtAPEndDate)
        self.lblAPPerson.setBuddy(self.cmbAPPerson)
        self.lblAPOffice.setBuddy(self.edtAPOffice)
        self.lblAPNote.setBuddy(self.edtAPNote)
        self.lblAPCoordAgent.setBuddy(self.edtAPCoordAgent)
        self.lblAPCoordInspector.setBuddy(self.edtAPCoordInspector)
        self.lblAPCoordText.setBuddy(self.edtAPCoordText)

        self.retranslateUi(EventCashPageWidget)
        self.tabCach.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(EventCashPageWidget)
        EventCashPageWidget.setTabOrder(self.edtCoordDate, self.edtCoordAgent)
        EventCashPageWidget.setTabOrder(self.edtCoordAgent, self.edtCoordInspector)
        EventCashPageWidget.setTabOrder(self.edtCoordInspector, self.edtCoordText)
        EventCashPageWidget.setTabOrder(self.edtCoordText, self.edtContractDate)
        EventCashPageWidget.setTabOrder(self.edtContractDate, self.edtContractNumber)
        EventCashPageWidget.setTabOrder(self.edtContractNumber, self.btnGetExternalId)
        EventCashPageWidget.setTabOrder(self.btnGetExternalId, self.edtSumLimit)
        EventCashPageWidget.setTabOrder(self.edtSumLimit, self.edtLastName)
        EventCashPageWidget.setTabOrder(self.edtLastName, self.btnGetClientInfo)
        EventCashPageWidget.setTabOrder(self.btnGetClientInfo, self.edtFirstName)
        EventCashPageWidget.setTabOrder(self.edtFirstName, self.edtPatrName)
        EventCashPageWidget.setTabOrder(self.edtPatrName, self.edtBirthDate)
        EventCashPageWidget.setTabOrder(self.edtBirthDate, self.cmbDocType)
        EventCashPageWidget.setTabOrder(self.cmbDocType, self.edtDocSerialLeft)
        EventCashPageWidget.setTabOrder(self.edtDocSerialLeft, self.edtDocSerialRight)
        EventCashPageWidget.setTabOrder(self.edtDocSerialRight, self.edtDocNumber)
        EventCashPageWidget.setTabOrder(self.edtDocNumber, self.edtRegAddress)
        EventCashPageWidget.setTabOrder(self.edtRegAddress, self.cmbOrganisation)
        EventCashPageWidget.setTabOrder(self.cmbOrganisation, self.btnSelectOrganisation)
        EventCashPageWidget.setTabOrder(self.btnSelectOrganisation, self.tabCach)
        EventCashPageWidget.setTabOrder(self.tabCach, self.scrollArea)
        EventCashPageWidget.setTabOrder(self.scrollArea, self.grpLocalContract)
        EventCashPageWidget.setTabOrder(self.grpLocalContract, self.edtAPDirectionDate)
        EventCashPageWidget.setTabOrder(self.edtAPDirectionDate, self.edtAPDirectionTime)
        EventCashPageWidget.setTabOrder(self.edtAPDirectionTime, self.chkAPIsUrgent)
        EventCashPageWidget.setTabOrder(self.chkAPIsUrgent, self.edtAPPlannedEndDate)
        EventCashPageWidget.setTabOrder(self.edtAPPlannedEndDate, self.edtAPPlannedEndTime)
        EventCashPageWidget.setTabOrder(self.edtAPPlannedEndTime, self.cmbAPSetPerson)
        EventCashPageWidget.setTabOrder(self.cmbAPSetPerson, self.edtAPCoordDate)
        EventCashPageWidget.setTabOrder(self.edtAPCoordDate, self.edtAPCoordTime)
        EventCashPageWidget.setTabOrder(self.edtAPCoordTime, self.edtAPCoordAgent)
        EventCashPageWidget.setTabOrder(self.edtAPCoordAgent, self.edtAPCoordInspector)
        EventCashPageWidget.setTabOrder(self.edtAPCoordInspector, self.edtAPCoordText)
        EventCashPageWidget.setTabOrder(self.edtAPCoordText, self.cmbAPStatus)
        EventCashPageWidget.setTabOrder(self.cmbAPStatus, self.edtAPBegDate)
        EventCashPageWidget.setTabOrder(self.edtAPBegDate, self.edtAPBegTime)
        EventCashPageWidget.setTabOrder(self.edtAPBegTime, self.edtAPEndDate)
        EventCashPageWidget.setTabOrder(self.edtAPEndDate, self.edtAPEndTime)
        EventCashPageWidget.setTabOrder(self.edtAPEndTime, self.cmbAPPerson)
        EventCashPageWidget.setTabOrder(self.cmbAPPerson, self.edtAPOffice)
        EventCashPageWidget.setTabOrder(self.edtAPOffice, self.edtAPNote)
        EventCashPageWidget.setTabOrder(self.edtAPNote, self.tblAccActions)
        EventCashPageWidget.setTabOrder(self.tblAccActions, self.tblPayments)
        EventCashPageWidget.setTabOrder(self.tblPayments, self.scrollArea_2)

    def retranslateUi(self, EventCashPageWidget):
        EventCashPageWidget.setWindowTitle(_translate("EventCashPageWidget", "Form", None))
        self.grpLocalContract.setTitle(_translate("EventCashPageWidget", "Согласование с Договорным отделом ЛПУ", None))
        self.grpPayer.setTitle(_translate("EventCashPageWidget", "Плательщик", None))
        self.lblDocNumber.setText(_translate("EventCashPageWidget", "Номер", None))
        self.lblStreetReg.setText(_translate("EventCashPageWidget", "Адрес", None))
        self.edtBirthDate.setProperty("displayFormat", _translate("EventCashPageWidget", "dd.MM.yyyy", None))
        self.cmbOrganisation.setWhatsThis(_translate("EventCashPageWidget", "место работы пациента", None))
        self.lblDocument.setText(_translate("EventCashPageWidget", "Документ", None))
        self.lblPatrName.setText(_translate("EventCashPageWidget", "Отчество", None))
        self.lblOrganisation.setText(_translate("EventCashPageWidget", "Юр.лицо", None))
        self.lblFirstName.setText(_translate("EventCashPageWidget", "Имя", None))
        self.btnGetClientInfo.setToolTip(_translate("EventCashPageWidget", "Подставить данные пациента", None))
        self.btnGetClientInfo.setText(_translate("EventCashPageWidget", "...", None))
        self.btnSelectOrganisation.setToolTip(_translate("EventCashPageWidget", "Выбрать организацию", None))
        self.btnSelectOrganisation.setText(_translate("EventCashPageWidget", "...", None))
        self.lblDocSerial.setText(_translate("EventCashPageWidget", "Серия", None))
        self.lblBirthDate.setText(_translate("EventCashPageWidget", "Дата ро&ждения", None))
        self.lblLastName.setText(_translate("EventCashPageWidget", "Фамилия", None))
        self.lblCoordInspector.setText(_translate("EventCashPageWidget", "От заказчика", None))
        self.groupBox.setTitle(_translate("EventCashPageWidget", "Договор", None))
        self.lblSumLimit.setText(_translate("EventCashPageWidget", "Ограничение суммы", None))
        self.lblContractDate.setText(_translate("EventCashPageWidget", "Дата", None))
        self.edtContractNumber.setToolTip(_translate("EventCashPageWidget", "Номер договора", None))
        self.btnGetExternalId.setToolTip(_translate("EventCashPageWidget", "Подставить внешний идентификатор карточки", None))
        self.btnGetExternalId.setText(_translate("EventCashPageWidget", "...", None))
        self.edtContractDate.setToolTip(_translate("EventCashPageWidget", "Дата договора", None))
        self.edtContractDate.setProperty("displayFormat", _translate("EventCashPageWidget", "dd.MM.yyyy", None))
        self.lblNumberContract.setText(_translate("EventCashPageWidget", "Номер договора", None))
        self.edtSumLimit.setText(_translate("EventCashPageWidget", "0", None))
        self.edtCoordDate.setWhatsThis(_translate("EventCashPageWidget", "дата начала осмотра", None))
        self.lblCoordDate.setText(_translate("EventCashPageWidget", "Согласовано", None))
        self.lblCoordAgent.setText(_translate("EventCashPageWidget", "От ЛПУ", None))
        self.lblCoordText.setText(_translate("EventCashPageWidget", "Обстоятельства", None))
        self.tabCach.setTabText(self.tabCach.indexOf(self.tabCoordination), _translate("EventCashPageWidget", "Согласование", None))
        self.grpActions.setTitle(_translate("EventCashPageWidget", "Оказанные услуги", None))
        self.lblAPDirectionDate.setText(_translate("EventCashPageWidget", "Назначено", None))
        self.edtAPDirectionDate.setWhatsThis(_translate("EventCashPageWidget", "дата начала осмотра", None))
        self.edtAPDirectionTime.setDisplayFormat(_translate("EventCashPageWidget", "HH:mm", None))
        self.chkAPIsUrgent.setText(_translate("EventCashPageWidget", "Срочно", None))
        self.lblAPPlannedEndDate.setText(_translate("EventCashPageWidget", "План", None))
        self.edtAPPlannedEndTime.setDisplayFormat(_translate("EventCashPageWidget", "HH:mm", None))
        self.lblAPSetPerson.setText(_translate("EventCashPageWidget", "Назначил", None))
        self.cmbAPSetPerson.setItemText(0, _translate("EventCashPageWidget", "Врач", None))
        self.lblAPCoordDate.setText(_translate("EventCashPageWidget", "Согласовано", None))
        self.edtAPCoordDate.setWhatsThis(_translate("EventCashPageWidget", "дата начала осмотра", None))
        self.edtAPCoordTime.setDisplayFormat(_translate("EventCashPageWidget", "HH:mm", None))
        self.lblAPStatus.setText(_translate("EventCashPageWidget", "Состояние", None))
        self.lblAPBegDate.setText(_translate("EventCashPageWidget", "Начато", None))
        self.edtAPBegDate.setWhatsThis(_translate("EventCashPageWidget", "дата окончания осмотра", None))
        self.edtAPBegTime.setDisplayFormat(_translate("EventCashPageWidget", "HH:mm", None))
        self.lblAPEndDate.setText(_translate("EventCashPageWidget", "Выполнено", None))
        self.edtAPEndTime.setDisplayFormat(_translate("EventCashPageWidget", "HH:mm", None))
        self.lblAPPerson.setText(_translate("EventCashPageWidget", "Исполнитель", None))
        self.cmbAPPerson.setItemText(0, _translate("EventCashPageWidget", "Врач", None))
        self.lblAPOffice.setText(_translate("EventCashPageWidget", "Кабинет", None))
        self.lblAPNote.setText(_translate("EventCashPageWidget", "Примечания", None))
        self.lblAPCoordAgent.setText(_translate("EventCashPageWidget", "От ЛПУ", None))
        self.lblAPCoordInspector.setText(_translate("EventCashPageWidget", "От заказчика", None))
        self.lblAPCoordText.setText(_translate("EventCashPageWidget", "Обстоятельства", None))
        self.grpCash.setTitle(_translate("EventCashPageWidget", "Расчет через кассу", None))
        self.lblPaymentAcc.setText(_translate("EventCashPageWidget", "Всего к оплате:", None))
        self.lblPaymentAccValue.setText(_translate("EventCashPageWidget", "000.00", None))
        self.lblPaymentPayedSum.setText(_translate("EventCashPageWidget", "Оплачено:", None))
        self.lblPaymentPayedSumValue.setText(_translate("EventCashPageWidget", "000.00", None))
        self.lblPaymentTotal.setText(_translate("EventCashPageWidget", "Долг:", None))
        self.lblPaymentTotalValue.setText(_translate("EventCashPageWidget", "000.00", None))
        self.tabCach.setTabText(self.tabCach.indexOf(self.tabActionsAndCash), _translate("EventCashPageWidget", "Услуги", None))

from Orgs.OrgComboBox import COrgComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Registry.DocSerialEdit import CDocSerialLeftEdit, CDocSerialRightEdit
from Registry.NamesEditor import CFirstNameEditor, CPatrNameEditor
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
from library.crbcombobox import CRBComboBox
