# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EventNotesPage.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EventNotesPageWidget(object):
    def setupUi(self, EventNotesPageWidget):
        EventNotesPageWidget.setObjectName(_fromUtf8("EventNotesPageWidget"))
        EventNotesPageWidget.resize(732, 659)
        self.verticalLayout = QtGui.QVBoxLayout(EventNotesPageWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(EventNotesPageWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMain = QtGui.QWidget()
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabMain)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.tabMain)
        self.scrollArea.setMinimumSize(QtCore.QSize(700, 0))
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 680, 1010))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbCureType = CRBComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCureType.sizePolicy().hasHeightForWidth())
        self.cmbCureType.setSizePolicy(sizePolicy)
        self.cmbCureType.setObjectName(_fromUtf8("cmbCureType"))
        self.gridLayout.addWidget(self.cmbCureType, 28, 1, 1, 3)
        self.edtPlannedDate = CDateEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPlannedDate.sizePolicy().hasHeightForWidth())
        self.edtPlannedDate.setSizePolicy(sizePolicy)
        self.edtPlannedDate.setCalendarPopup(True)
        self.edtPlannedDate.setObjectName(_fromUtf8("edtPlannedDate"))
        self.gridLayout.addWidget(self.edtPlannedDate, 10, 1, 1, 1)
        self.cmbMKB = CICDCodeEditEx(self.scrollAreaWidgetContents)
        self.cmbMKB.setObjectName(_fromUtf8("cmbMKB"))
        self.gridLayout.addWidget(self.cmbMKB, 15, 1, 1, 3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cmbRelegateOrg = CPolyclinicComboBox(self.scrollAreaWidgetContents)
        self.cmbRelegateOrg.setEnabled(True)
        self.cmbRelegateOrg.setObjectName(_fromUtf8("cmbRelegateOrg"))
        self.horizontalLayout.addWidget(self.cmbRelegateOrg)
        self.btnSelectRelegateOrg = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.btnSelectRelegateOrg.setObjectName(_fromUtf8("btnSelectRelegateOrg"))
        self.horizontalLayout.addWidget(self.btnSelectRelegateOrg)
        self.gridLayout.addLayout(self.horizontalLayout, 11, 1, 1, 3)
        self.lblRelegateOrg = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblRelegateOrg.setObjectName(_fromUtf8("lblRelegateOrg"))
        self.gridLayout.addWidget(self.lblRelegateOrg, 11, 0, 1, 1)
        self.cmbCureMethod = CRBComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCureMethod.sizePolicy().hasHeightForWidth())
        self.cmbCureMethod.setSizePolicy(sizePolicy)
        self.cmbCureMethod.setObjectName(_fromUtf8("cmbCureMethod"))
        self.gridLayout.addWidget(self.cmbCureMethod, 29, 1, 1, 3)
        self.lblEventCreateDateTime = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblEventCreateDateTime.setObjectName(_fromUtf8("lblEventCreateDateTime"))
        self.gridLayout.addWidget(self.lblEventCreateDateTime, 23, 0, 1, 1)
        self.lblArmyDate = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblArmyDate.setObjectName(_fromUtf8("lblArmyDate"))
        self.gridLayout.addWidget(self.lblArmyDate, 18, 0, 1, 1)
        self.lblEventCuratorIdValue = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblEventCuratorIdValue.setObjectName(_fromUtf8("lblEventCuratorIdValue"))
        self.gridLayout.addWidget(self.lblEventCuratorIdValue, 22, 0, 1, 1)
        self.lblEventCreatePersonValue = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventCreatePersonValue.sizePolicy().hasHeightForWidth())
        self.lblEventCreatePersonValue.setSizePolicy(sizePolicy)
        self.lblEventCreatePersonValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventCreatePersonValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventCreatePersonValue.setText(_fromUtf8(""))
        self.lblEventCreatePersonValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventCreatePersonValue.setObjectName(_fromUtf8("lblEventCreatePersonValue"))
        self.gridLayout.addWidget(self.lblEventCreatePersonValue, 24, 1, 1, 3)
        self.chkLock = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkLock.setEnabled(False)
        self.chkLock.setText(_fromUtf8(""))
        self.chkLock.setObjectName(_fromUtf8("chkLock"))
        self.gridLayout.addWidget(self.chkLock, 32, 1, 1, 3)
        self.edtPerson = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtPerson.setMinimumSize(QtCore.QSize(347, 0))
        self.edtPerson.setObjectName(_fromUtf8("edtPerson"))
        self.gridLayout.addWidget(self.edtPerson, 13, 1, 1, 3)
        self.chkArmyReferral = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkArmyReferral.setObjectName(_fromUtf8("chkArmyReferral"))
        self.gridLayout.addWidget(self.chkArmyReferral, 16, 0, 1, 4)
        self.edtPrevEventInfo = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtPrevEventInfo.setEnabled(False)
        self.edtPrevEventInfo.setObjectName(_fromUtf8("edtPrevEventInfo"))
        self.gridLayout.addWidget(self.edtPrevEventInfo, 2, 1, 1, 3)
        self.lblEventAssistantIdValue = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblEventAssistantIdValue.setObjectName(_fromUtf8("lblEventAssistantIdValue"))
        self.gridLayout.addWidget(self.lblEventAssistantIdValue, 21, 0, 1, 1)
        self.lblEventCreatePerson = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblEventCreatePerson.setObjectName(_fromUtf8("lblEventCreatePerson"))
        self.gridLayout.addWidget(self.lblEventCreatePerson, 24, 0, 1, 1)
        self.lblSpeciality = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridLayout.addWidget(self.lblSpeciality, 14, 0, 1, 1)
        self.cmbClientPolicy = CClientPolicyComboBox(self.scrollAreaWidgetContents)
        self.cmbClientPolicy.setObjectName(_fromUtf8("cmbClientPolicy"))
        self.gridLayout.addWidget(self.cmbClientPolicy, 4, 1, 1, 3)
        self.lblArmyNumber = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblArmyNumber.setObjectName(_fromUtf8("lblArmyNumber"))
        self.gridLayout.addWidget(self.lblArmyNumber, 17, 0, 1, 1)
        self.lblNumber = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblNumber.setObjectName(_fromUtf8("lblNumber"))
        self.gridLayout.addWidget(self.lblNumber, 8, 0, 1, 1)
        self.cmbEventCurator = CPersonComboBoxEx(self.scrollAreaWidgetContents)
        self.cmbEventCurator.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEventCurator.sizePolicy().hasHeightForWidth())
        self.cmbEventCurator.setSizePolicy(sizePolicy)
        self.cmbEventCurator.setObjectName(_fromUtf8("cmbEventCurator"))
        self.gridLayout.addWidget(self.cmbEventCurator, 22, 1, 1, 3)
        self.lblCureType = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblCureType.setObjectName(_fromUtf8("lblCureType"))
        self.gridLayout.addWidget(self.lblCureType, 28, 0, 1, 1)
        self.cmbSpeciality = CRBComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSpeciality.sizePolicy().hasHeightForWidth())
        self.cmbSpeciality.setSizePolicy(sizePolicy)
        self.cmbSpeciality.setMinimumSize(QtCore.QSize(321, 0))
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 14, 1, 1, 3)
        self.lblClientPolicy = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblClientPolicy.setObjectName(_fromUtf8("lblClientPolicy"))
        self.gridLayout.addWidget(self.lblClientPolicy, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cmbArmyOrg = CArmyOrgComboBox(self.scrollAreaWidgetContents)
        self.cmbArmyOrg.setObjectName(_fromUtf8("cmbArmyOrg"))
        self.horizontalLayout_4.addWidget(self.cmbArmyOrg)
        self.btnSelectArmyOrg = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.btnSelectArmyOrg.setObjectName(_fromUtf8("btnSelectArmyOrg"))
        self.horizontalLayout_4.addWidget(self.btnSelectArmyOrg)
        self.gridLayout.addLayout(self.horizontalLayout_4, 19, 1, 1, 3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.chkArmyFreeInput = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkArmyFreeInput.setText(_fromUtf8(""))
        self.chkArmyFreeInput.setObjectName(_fromUtf8("chkArmyFreeInput"))
        self.horizontalLayout_3.addWidget(self.chkArmyFreeInput)
        self.edtArmyFreeInput = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtArmyFreeInput.setEnabled(False)
        self.edtArmyFreeInput.setText(_fromUtf8(""))
        self.edtArmyFreeInput.setObjectName(_fromUtf8("edtArmyFreeInput"))
        self.horizontalLayout_3.addWidget(self.edtArmyFreeInput)
        self.gridLayout.addLayout(self.horizontalLayout_3, 20, 1, 1, 3)
        self.cmbEventAssistant = CPersonComboBoxEx(self.scrollAreaWidgetContents)
        self.cmbEventAssistant.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEventAssistant.sizePolicy().hasHeightForWidth())
        self.cmbEventAssistant.setSizePolicy(sizePolicy)
        self.cmbEventAssistant.setObjectName(_fromUtf8("cmbEventAssistant"))
        self.gridLayout.addWidget(self.cmbEventAssistant, 21, 1, 1, 3)
        self.lblPrevEvent = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblPrevEvent.setObjectName(_fromUtf8("lblPrevEvent"))
        self.gridLayout.addWidget(self.lblPrevEvent, 2, 0, 1, 1)
        self.cmbPatientModel = CModelPatientComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPatientModel.sizePolicy().hasHeightForWidth())
        self.cmbPatientModel.setSizePolicy(sizePolicy)
        self.cmbPatientModel.setObjectName(_fromUtf8("cmbPatientModel"))
        self.gridLayout.addWidget(self.cmbPatientModel, 27, 1, 1, 3)
        self.edtDate = CDateEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDate.sizePolicy().hasHeightForWidth())
        self.edtDate.setSizePolicy(sizePolicy)
        self.edtDate.setCalendarPopup(True)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.gridLayout.addWidget(self.edtDate, 9, 1, 1, 3)
        self.btnExternalIdupd = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnExternalIdupd.setVisible(False)
        self.btnExternalIdupd.setObjectName(_fromUtf8("btnExternalIdupd"))
        self.gridLayout.addWidget(self.btnExternalIdupd, 3, 1, 1, 1)
        self.lblEventExternalId = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblEventExternalId.setObjectName(_fromUtf8("lblEventExternalId"))
        self.gridLayout.addWidget(self.lblEventExternalId, 1, 0, 1, 1)
        self.lblEventNote = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventNote.sizePolicy().hasHeightForWidth())
        self.lblEventNote.setSizePolicy(sizePolicy)
        self.lblEventNote.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblEventNote.setObjectName(_fromUtf8("lblEventNote"))
        self.gridLayout.addWidget(self.lblEventNote, 31, 0, 1, 1)
        self.lblPlannedDate = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblPlannedDate.setObjectName(_fromUtf8("lblPlannedDate"))
        self.gridLayout.addWidget(self.lblPlannedDate, 10, 0, 1, 1)
        self.lblEventModifyPersonValue = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventModifyPersonValue.sizePolicy().hasHeightForWidth())
        self.lblEventModifyPersonValue.setSizePolicy(sizePolicy)
        self.lblEventModifyPersonValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventModifyPersonValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventModifyPersonValue.setText(_fromUtf8(""))
        self.lblEventModifyPersonValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventModifyPersonValue.setObjectName(_fromUtf8("lblEventModifyPersonValue"))
        self.gridLayout.addWidget(self.lblEventModifyPersonValue, 26, 1, 1, 3)
        self.lblCureMethod = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblCureMethod.setObjectName(_fromUtf8("lblCureMethod"))
        self.gridLayout.addWidget(self.lblCureMethod, 29, 0, 1, 1)
        self.chkLPUReferral = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkLPUReferral.setObjectName(_fromUtf8("chkLPUReferral"))
        self.gridLayout.addWidget(self.chkLPUReferral, 6, 0, 1, 4)
        self.edtEventNote = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.edtEventNote.setObjectName(_fromUtf8("edtEventNote"))
        self.gridLayout.addWidget(self.edtEventNote, 31, 1, 1, 3)
        self.lblDate = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout.addWidget(self.lblDate, 9, 0, 1, 1)
        self.edtEventExternalIdValue = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtEventExternalIdValue.setEnabled(False)
        self.edtEventExternalIdValue.setObjectName(_fromUtf8("edtEventExternalIdValue"))
        self.gridLayout.addWidget(self.edtEventExternalIdValue, 1, 1, 1, 3)
        self.lblDiagnosis = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblDiagnosis.setObjectName(_fromUtf8("lblDiagnosis"))
        self.gridLayout.addWidget(self.lblDiagnosis, 15, 0, 1, 1)
        self.lblEventModifyDateTime = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblEventModifyDateTime.setObjectName(_fromUtf8("lblEventModifyDateTime"))
        self.gridLayout.addWidget(self.lblEventModifyDateTime, 25, 0, 1, 1)
        self.lblPatientModel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblPatientModel.setObjectName(_fromUtf8("lblPatientModel"))
        self.gridLayout.addWidget(self.lblPatientModel, 27, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.chkFreeInput = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFreeInput.setText(_fromUtf8(""))
        self.chkFreeInput.setObjectName(_fromUtf8("chkFreeInput"))
        self.horizontalLayout_2.addWidget(self.chkFreeInput)
        self.edtFreeInput = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtFreeInput.setEnabled(False)
        self.edtFreeInput.setText(_fromUtf8(""))
        self.edtFreeInput.setObjectName(_fromUtf8("edtFreeInput"))
        self.horizontalLayout_2.addWidget(self.edtFreeInput)
        self.gridLayout.addLayout(self.horizontalLayout_2, 12, 1, 1, 3)
        self.lblEventCreateDateTimeValue = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventCreateDateTimeValue.sizePolicy().hasHeightForWidth())
        self.lblEventCreateDateTimeValue.setSizePolicy(sizePolicy)
        self.lblEventCreateDateTimeValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventCreateDateTimeValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventCreateDateTimeValue.setText(_fromUtf8(""))
        self.lblEventCreateDateTimeValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventCreateDateTimeValue.setObjectName(_fromUtf8("lblEventCreateDateTimeValue"))
        self.gridLayout.addWidget(self.lblEventCreateDateTimeValue, 23, 1, 1, 3)
        self.lblArmyFreeInput = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblArmyFreeInput.setObjectName(_fromUtf8("lblArmyFreeInput"))
        self.gridLayout.addWidget(self.lblArmyFreeInput, 19, 0, 1, 1)
        self.lblEventId = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblEventId.setObjectName(_fromUtf8("lblEventId"))
        self.gridLayout.addWidget(self.lblEventId, 0, 0, 1, 1)
        self.lblEventIdValue = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventIdValue.sizePolicy().hasHeightForWidth())
        self.lblEventIdValue.setSizePolicy(sizePolicy)
        self.lblEventIdValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventIdValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventIdValue.setText(_fromUtf8(""))
        self.lblEventIdValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventIdValue.setObjectName(_fromUtf8("lblEventIdValue"))
        self.gridLayout.addWidget(self.lblEventIdValue, 0, 1, 1, 3)
        self.lblLock = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblLock.setEnabled(False)
        self.lblLock.setObjectName(_fromUtf8("lblLock"))
        self.gridLayout.addWidget(self.lblLock, 32, 0, 1, 1)
        self.cmbArmyNumber = CReferralComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbArmyNumber.sizePolicy().hasHeightForWidth())
        self.cmbArmyNumber.setSizePolicy(sizePolicy)
        self.cmbArmyNumber.setObjectName(_fromUtf8("cmbArmyNumber"))
        self.gridLayout.addWidget(self.cmbArmyNumber, 17, 1, 1, 3)
        self.lblEventModifyDateTimeValue = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventModifyDateTimeValue.sizePolicy().hasHeightForWidth())
        self.lblEventModifyDateTimeValue.setSizePolicy(sizePolicy)
        self.lblEventModifyDateTimeValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventModifyDateTimeValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventModifyDateTimeValue.setText(_fromUtf8(""))
        self.lblEventModifyDateTimeValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventModifyDateTimeValue.setObjectName(_fromUtf8("lblEventModifyDateTimeValue"))
        self.gridLayout.addWidget(self.lblEventModifyDateTimeValue, 25, 1, 1, 3)
        self.lblEventModifyPerson = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblEventModifyPerson.setObjectName(_fromUtf8("lblEventModifyPerson"))
        self.gridLayout.addWidget(self.lblEventModifyPerson, 26, 0, 1, 1)
        self.edtArmyDate = CDateEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtArmyDate.sizePolicy().hasHeightForWidth())
        self.edtArmyDate.setSizePolicy(sizePolicy)
        self.edtArmyDate.setCalendarPopup(True)
        self.edtArmyDate.setObjectName(_fromUtf8("edtArmyDate"))
        self.gridLayout.addWidget(self.edtArmyDate, 18, 1, 1, 2)
        self.lblPerson = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 13, 0, 1, 1)
        self.lblRefType = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblRefType.setObjectName(_fromUtf8("lblRefType"))
        self.gridLayout.addWidget(self.lblRefType, 7, 0, 1, 1)
        self.cmbReferralType = CRBComboBox(self.scrollAreaWidgetContents)
        self.cmbReferralType.setObjectName(_fromUtf8("cmbReferralType"))
        self.gridLayout.addWidget(self.cmbReferralType, 7, 1, 1, 3)
        self.edtNumber = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtNumber.setObjectName(_fromUtf8("edtNumber"))
        self.gridLayout.addWidget(self.edtNumber, 8, 1, 1, 3)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabMain, _fromUtf8(""))
        self.tabIEMK = QtGui.QWidget()
        self.tabIEMK.setObjectName(_fromUtf8("tabIEMK"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabIEMK)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.txtBrowserIEMKHistoryLog = QtGui.QTextBrowser(self.tabIEMK)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtBrowserIEMKHistoryLog.sizePolicy().hasHeightForWidth())
        self.txtBrowserIEMKHistoryLog.setSizePolicy(sizePolicy)
        self.txtBrowserIEMKHistoryLog.setObjectName(_fromUtf8("txtBrowserIEMKHistoryLog"))
        self.gridLayout_3.addWidget(self.txtBrowserIEMKHistoryLog, 1, 0, 1, 4)
        self.btnSendCase = QtGui.QPushButton(self.tabIEMK)
        self.btnSendCase.setObjectName(_fromUtf8("btnSendCase"))
        self.gridLayout_3.addWidget(self.btnSendCase, 9, 2, 1, 2)
        self.btnSendClient = QtGui.QPushButton(self.tabIEMK)
        self.btnSendClient.setObjectName(_fromUtf8("btnSendClient"))
        self.gridLayout_3.addWidget(self.btnSendClient, 9, 0, 1, 2)
        self.label = QtGui.QLabel(self.tabIEMK)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 4)
        self.chkWebEpicrisis = QtGui.QCheckBox(self.tabIEMK)
        self.chkWebEpicrisis.setObjectName(_fromUtf8("chkWebEpicrisis"))
        self.gridLayout_3.addWidget(self.chkWebEpicrisis, 8, 0, 1, 4)
        self.txtBrowserIEMKCurrentLog = QtGui.QTextBrowser(self.tabIEMK)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtBrowserIEMKCurrentLog.sizePolicy().hasHeightForWidth())
        self.txtBrowserIEMKCurrentLog.setSizePolicy(sizePolicy)
        self.txtBrowserIEMKCurrentLog.setObjectName(_fromUtf8("txtBrowserIEMKCurrentLog"))
        self.gridLayout_3.addWidget(self.txtBrowserIEMKCurrentLog, 3, 0, 1, 4)
        self.label_3 = QtGui.QLabel(self.tabIEMK)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 4, 0, 1, 1)
        self.edtCaseURL = QtGui.QLineEdit(self.tabIEMK)
        self.edtCaseURL.setObjectName(_fromUtf8("edtCaseURL"))
        self.gridLayout_3.addWidget(self.edtCaseURL, 4, 1, 1, 3)
        self.label_2 = QtGui.QLabel(self.tabIEMK)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 4)
        self.edtPixURL = QtGui.QLineEdit(self.tabIEMK)
        self.edtPixURL.setObjectName(_fromUtf8("edtPixURL"))
        self.gridLayout_3.addWidget(self.edtPixURL, 5, 1, 1, 3)
        self.label_4 = QtGui.QLabel(self.tabIEMK)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 5, 0, 1, 1)
        self.btnCreateService = QtGui.QPushButton(self.tabIEMK)
        self.btnCreateService.setObjectName(_fromUtf8("btnCreateService"))
        self.gridLayout_3.addWidget(self.btnCreateService, 7, 0, 1, 4)
        self.label_5 = QtGui.QLabel(self.tabIEMK)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 6, 0, 1, 1)
        self.edtGUID = QtGui.QLineEdit(self.tabIEMK)
        self.edtGUID.setObjectName(_fromUtf8("edtGUID"))
        self.gridLayout_3.addWidget(self.edtGUID, 6, 1, 1, 3)
        self.tabWidget.addTab(self.tabIEMK, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.lblRelegateOrg.setBuddy(self.cmbRelegateOrg)
        self.lblArmyDate.setBuddy(self.edtArmyDate)
        self.lblEventCuratorIdValue.setBuddy(self.cmbEventCurator)
        self.lblEventAssistantIdValue.setBuddy(self.cmbEventAssistant)
        self.lblSpeciality.setBuddy(self.cmbSpeciality)
        self.lblArmyNumber.setBuddy(self.cmbArmyNumber)
        self.lblCureType.setBuddy(self.cmbCureType)
        self.lblEventExternalId.setBuddy(self.edtEventExternalIdValue)
        self.lblEventNote.setBuddy(self.edtEventNote)
        self.lblCureMethod.setBuddy(self.cmbCureMethod)
        self.lblDate.setBuddy(self.edtDate)
        self.lblDiagnosis.setBuddy(self.cmbMKB)
        self.lblPatientModel.setBuddy(self.cmbPatientModel)
        self.lblArmyFreeInput.setBuddy(self.edtArmyFreeInput)
        self.lblLock.setBuddy(self.chkLock)
        self.lblPerson.setBuddy(self.edtPerson)

        self.retranslateUi(EventNotesPageWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(EventNotesPageWidget)
        EventNotesPageWidget.setTabOrder(self.edtEventExternalIdValue, self.edtPrevEventInfo)
        EventNotesPageWidget.setTabOrder(self.edtPrevEventInfo, self.cmbClientPolicy)
        EventNotesPageWidget.setTabOrder(self.cmbClientPolicy, self.chkLPUReferral)
        EventNotesPageWidget.setTabOrder(self.chkLPUReferral, self.cmbReferralType)
        EventNotesPageWidget.setTabOrder(self.cmbReferralType, self.edtNumber)
        EventNotesPageWidget.setTabOrder(self.edtNumber, self.edtDate)
        EventNotesPageWidget.setTabOrder(self.edtDate, self.edtPlannedDate)
        EventNotesPageWidget.setTabOrder(self.edtPlannedDate, self.cmbRelegateOrg)
        EventNotesPageWidget.setTabOrder(self.cmbRelegateOrg, self.btnSelectRelegateOrg)
        EventNotesPageWidget.setTabOrder(self.btnSelectRelegateOrg, self.chkFreeInput)
        EventNotesPageWidget.setTabOrder(self.chkFreeInput, self.edtFreeInput)
        EventNotesPageWidget.setTabOrder(self.edtFreeInput, self.edtPerson)
        EventNotesPageWidget.setTabOrder(self.edtPerson, self.cmbSpeciality)
        EventNotesPageWidget.setTabOrder(self.cmbSpeciality, self.cmbMKB)
        EventNotesPageWidget.setTabOrder(self.cmbMKB, self.chkArmyReferral)
        EventNotesPageWidget.setTabOrder(self.chkArmyReferral, self.cmbArmyNumber)
        EventNotesPageWidget.setTabOrder(self.cmbArmyNumber, self.edtArmyDate)
        EventNotesPageWidget.setTabOrder(self.edtArmyDate, self.cmbArmyOrg)
        EventNotesPageWidget.setTabOrder(self.cmbArmyOrg, self.btnSelectArmyOrg)
        EventNotesPageWidget.setTabOrder(self.btnSelectArmyOrg, self.chkArmyFreeInput)
        EventNotesPageWidget.setTabOrder(self.chkArmyFreeInput, self.edtArmyFreeInput)
        EventNotesPageWidget.setTabOrder(self.edtArmyFreeInput, self.cmbEventAssistant)
        EventNotesPageWidget.setTabOrder(self.cmbEventAssistant, self.cmbEventCurator)
        EventNotesPageWidget.setTabOrder(self.cmbEventCurator, self.chkLock)
        EventNotesPageWidget.setTabOrder(self.chkLock, self.cmbCureType)
        EventNotesPageWidget.setTabOrder(self.cmbCureType, self.cmbPatientModel)
        EventNotesPageWidget.setTabOrder(self.cmbPatientModel, self.cmbCureMethod)
        EventNotesPageWidget.setTabOrder(self.cmbCureMethod, self.edtEventNote)

    def retranslateUi(self, EventNotesPageWidget):
        EventNotesPageWidget.setWindowTitle(_translate("EventNotesPageWidget", "Form", None))
        self.edtPlannedDate.setToolTip(_translate("EventNotesPageWidget", "Заполняется только для направлений на ВМП", None))
        self.btnSelectRelegateOrg.setText(_translate("EventNotesPageWidget", "...", None))
        self.lblRelegateOrg.setText(_translate("EventNotesPageWidget", "Направитель", None))
        self.lblEventCreateDateTime.setText(_translate("EventNotesPageWidget", "Дата и время создания", None))
        self.lblArmyDate.setText(_translate("EventNotesPageWidget", "Дата выдачи направления", None))
        self.lblEventCuratorIdValue.setText(_translate("EventNotesPageWidget", "Куратор", None))
        self.chkArmyReferral.setText(_translate("EventNotesPageWidget", "Прикрепить направление из военкомата", None))
        self.lblEventAssistantIdValue.setText(_translate("EventNotesPageWidget", "Ассистент", None))
        self.lblEventCreatePerson.setText(_translate("EventNotesPageWidget", "Автор", None))
        self.lblSpeciality.setText(_translate("EventNotesPageWidget", "Специальность", None))
        self.lblArmyNumber.setText(_translate("EventNotesPageWidget", "Номер направления", None))
        self.lblNumber.setText(_translate("EventNotesPageWidget", "Номер направления", None))
        self.lblCureType.setText(_translate("EventNotesPageWidget", "Вид лечения", None))
        self.cmbSpeciality.setWhatsThis(_translate("EventNotesPageWidget", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None))
        self.lblClientPolicy.setText(_translate("EventNotesPageWidget", "Полис пациента", None))
        self.btnSelectArmyOrg.setText(_translate("EventNotesPageWidget", "...", None))
        self.lblPrevEvent.setText(_translate("EventNotesPageWidget", "Предыдущее событие", None))
        self.btnExternalIdupd.setText(_translate("EventNotesPageWidget", "Обновить внешний индентификатор записи", None))
        self.lblEventExternalId.setText(_translate("EventNotesPageWidget", "Внешний идентификатор записи", None))
        self.lblEventNote.setText(_translate("EventNotesPageWidget", "Примечания", None))
        self.lblPlannedDate.setToolTip(_translate("EventNotesPageWidget", "Заполняется только для направлений на ВМП", None))
        self.lblPlannedDate.setText(_translate("EventNotesPageWidget", "Дата планируемой госпитализации", None))
        self.lblCureMethod.setText(_translate("EventNotesPageWidget", "Метод лечения", None))
        self.chkLPUReferral.setText(_translate("EventNotesPageWidget", "Прикрепить направление из ЛПУ", None))
        self.lblDate.setText(_translate("EventNotesPageWidget", "Дата выдачи направления", None))
        self.lblDiagnosis.setText(_translate("EventNotesPageWidget", "Диагноз", None))
        self.lblEventModifyDateTime.setText(_translate("EventNotesPageWidget", "Дата и время последнего изменения", None))
        self.lblPatientModel.setText(_translate("EventNotesPageWidget", "Модель пациента", None))
        self.lblArmyFreeInput.setText(_translate("EventNotesPageWidget", "Направитель", None))
        self.lblEventId.setText(_translate("EventNotesPageWidget", "Идентификатор записи", None))
        self.lblLock.setText(_translate("EventNotesPageWidget", "Заблокировать обращение", None))
        self.lblEventModifyPerson.setText(_translate("EventNotesPageWidget", "Автор последнего изменения", None))
        self.lblPerson.setText(_translate("EventNotesPageWidget", "Врач", None))
        self.lblRefType.setText(_translate("EventNotesPageWidget", "Тип направления", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("EventNotesPageWidget", "Основное", None))
        self.btnSendCase.setText(_translate("EventNotesPageWidget", "Отправить случай", None))
        self.btnSendClient.setText(_translate("EventNotesPageWidget", "Отправить человека", None))
        self.label.setText(_translate("EventNotesPageWidget", "История посылок", None))
        self.chkWebEpicrisis.setText(_translate("EventNotesPageWidget", "Посылать веб эпикризы", None))
        self.label_3.setText(_translate("EventNotesPageWidget", "Адрес сервиса случаев", None))
        self.label_2.setText(_translate("EventNotesPageWidget", "Лог текущей посылки", None))
        self.label_4.setText(_translate("EventNotesPageWidget", "Адрес сервиса пациентов", None))
        self.btnCreateService.setText(_translate("EventNotesPageWidget", "Использовать адреса", None))
        self.label_5.setText(_translate("EventNotesPageWidget", "GUID", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIEMK), _translate("EventNotesPageWidget", "ЭМК", None))

from Events.ClientPolicyComboBox import CClientPolicyComboBox
from Orgs.OrgComboBox import CArmyOrgComboBox, CPolyclinicComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEditEx
from library.ModelPatientComboBox import CModelPatientComboBox
from library.ReferralComboBox import CReferralComboBox
from library.crbcombobox import CRBComboBox
