# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormularyItemSelectionDialog.ui'
#
# Created: Fri Jul 25 15:42:36 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FormularyItemSelectionDialog(object):
    def setupUi(self, FormularyItemSelectionDialog):
        FormularyItemSelectionDialog.setObjectName(_fromUtf8("FormularyItemSelectionDialog"))
        FormularyItemSelectionDialog.resize(703, 437)
        self.gridlayout = QtGui.QGridLayout(FormularyItemSelectionDialog)
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(0)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.tabWidget = QtGui.QTabWidget(FormularyItemSelectionDialog)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabFormularItems = QtGui.QWidget()
        self.tabFormularItems.setObjectName(_fromUtf8("tabFormularItems"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabFormularItems)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.tabFormularItems)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.cmbFormulars = QtGui.QComboBox(self.tabFormularItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFormulars.sizePolicy().hasHeightForWidth())
        self.cmbFormulars.setSizePolicy(sizePolicy)
        self.cmbFormulars.setObjectName(_fromUtf8("cmbFormulars"))
        self.horizontalLayout_2.addWidget(self.cmbFormulars)
        self.chkAllFormulars = QtGui.QCheckBox(self.tabFormularItems)
        self.chkAllFormulars.setObjectName(_fromUtf8("chkAllFormulars"))
        self.horizontalLayout_2.addWidget(self.chkAllFormulars)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lstMNNs = QtGui.QListView(self.tabFormularItems)
        self.lstMNNs.setObjectName(_fromUtf8("lstMNNs"))
        self.horizontalLayout.addWidget(self.lstMNNs)
        self.lstDrugForms = QtGui.QListView(self.tabFormularItems)
        self.lstDrugForms.setObjectName(_fromUtf8("lstDrugForms"))
        self.horizontalLayout.addWidget(self.lstDrugForms)
        self.lstFullNames = QtGui.QListView(self.tabFormularItems)
        self.lstFullNames.setObjectName(_fromUtf8("lstFullNames"))
        self.horizontalLayout.addWidget(self.lstFullNames)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tabFormularItems, _fromUtf8(""))
        self.tabSearch = QtGui.QWidget()
        self.tabSearch.setObjectName(_fromUtf8("tabSearch"))
        self.gridLayout = QtGui.QGridLayout(self.tabSearch)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edtKind = QtGui.QLineEdit(self.tabSearch)
        self.edtKind.setObjectName(_fromUtf8("edtKind"))
        self.gridLayout.addWidget(self.edtKind, 4, 2, 1, 1)
        self.lblKind = QtGui.QLabel(self.tabSearch)
        self.lblKind.setObjectName(_fromUtf8("lblKind"))
        self.gridLayout.addWidget(self.lblKind, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.lblCode = QtGui.QLabel(self.tabSearch)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout.addWidget(self.lblCode, 0, 0, 1, 1)
        self.edtCode = QtGui.QLineEdit(self.tabSearch)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout.addWidget(self.edtCode, 0, 1, 1, 2)
        self.lblName = QtGui.QLabel(self.tabSearch)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(178, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 7, 0, 1, 2)
        self.edtName = QtGui.QLineEdit(self.tabSearch)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 1, 1, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 7, 2, 1, 1)
        self.edtMnn = QtGui.QLineEdit(self.tabSearch)
        self.edtMnn.setObjectName(_fromUtf8("edtMnn"))
        self.gridLayout.addWidget(self.edtMnn, 2, 1, 1, 2)
        self.lblMnn = QtGui.QLabel(self.tabSearch)
        self.lblMnn.setObjectName(_fromUtf8("lblMnn"))
        self.gridLayout.addWidget(self.lblMnn, 2, 0, 1, 1)
        self.lblCharacteristic = QtGui.QLabel(self.tabSearch)
        self.lblCharacteristic.setObjectName(_fromUtf8("lblCharacteristic"))
        self.gridLayout.addWidget(self.lblCharacteristic, 3, 0, 1, 1)
        self.edtCharacteristic = QtGui.QLineEdit(self.tabSearch)
        self.edtCharacteristic.setObjectName(_fromUtf8("edtCharacteristic"))
        self.gridLayout.addWidget(self.edtCharacteristic, 3, 1, 1, 2)
        self.lblArticle = QtGui.QLabel(self.tabSearch)
        self.lblArticle.setObjectName(_fromUtf8("lblArticle"))
        self.gridLayout.addWidget(self.lblArticle, 5, 0, 1, 1)
        self.edtArticle = QtGui.QLineEdit(self.tabSearch)
        self.edtArticle.setObjectName(_fromUtf8("edtArticle"))
        self.gridLayout.addWidget(self.edtArticle, 5, 2, 1, 1)
        self.tabWidget.addTab(self.tabSearch, _fromUtf8(""))
        self.gridlayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.lblKind.setBuddy(self.edtCharacteristic)
        self.lblCode.setBuddy(self.edtCode)
        self.lblName.setBuddy(self.edtName)
        self.lblMnn.setBuddy(self.edtMnn)
        self.lblCharacteristic.setBuddy(self.edtCharacteristic)
        self.lblArticle.setBuddy(self.edtCharacteristic)

        self.retranslateUi(FormularyItemSelectionDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormularyItemSelectionDialog)
        FormularyItemSelectionDialog.setTabOrder(self.tabWidget, self.edtCode)
        FormularyItemSelectionDialog.setTabOrder(self.edtCode, self.edtName)
        FormularyItemSelectionDialog.setTabOrder(self.edtName, self.edtMnn)
        FormularyItemSelectionDialog.setTabOrder(self.edtMnn, self.edtCharacteristic)
        FormularyItemSelectionDialog.setTabOrder(self.edtCharacteristic, self.buttonBox)

    def retranslateUi(self, FormularyItemSelectionDialog):
        FormularyItemSelectionDialog.setWindowTitle(_translate("FormularyItemSelectionDialog", "Выбор препарата из формуляра", None))
        self.label.setText(_translate("FormularyItemSelectionDialog", "Формуляр", None))
        self.chkAllFormulars.setText(_translate("FormularyItemSelectionDialog", "Все формуляры", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFormularItems), _translate("FormularyItemSelectionDialog", "&Формуляр", None))
        self.lblKind.setText(_translate("FormularyItemSelectionDialog", "Сорт", None))
        self.lblCode.setText(_translate("FormularyItemSelectionDialog", "&Код", None))
        self.lblName.setText(_translate("FormularyItemSelectionDialog", "&Наименование", None))
        self.lblMnn.setText(_translate("FormularyItemSelectionDialog", "МНН", None))
        self.lblCharacteristic.setText(_translate("FormularyItemSelectionDialog", "Характеристика", None))
        self.lblArticle.setText(_translate("FormularyItemSelectionDialog", "Артикул", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), _translate("FormularyItemSelectionDialog", "&Поиск", None))

