# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PreCreateEventDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PreCreateEventDialog(object):
    def setupUi(self, PreCreateEventDialog):
        PreCreateEventDialog.setObjectName(_fromUtf8("PreCreateEventDialog"))
        PreCreateEventDialog.resize(713, 800)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PreCreateEventDialog.sizePolicy().hasHeightForWidth())
        PreCreateEventDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(PreCreateEventDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(PreCreateEventDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabStandart = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabStandart.sizePolicy().hasHeightForWidth())
        self.tabStandart.setSizePolicy(sizePolicy)
        self.tabStandart.setObjectName(_fromUtf8("tabStandart"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabStandart)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.grpReferral = QtGui.QGroupBox(self.tabStandart)
        self.grpReferral.setFlat(True)
        self.grpReferral.setCheckable(True)
        self.grpReferral.setChecked(False)
        self.grpReferral.setObjectName(_fromUtf8("grpReferral"))
        self.gridLayout_5 = QtGui.QGridLayout(self.grpReferral)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.edtFreeInput = QtGui.QLineEdit(self.grpReferral)
        self.edtFreeInput.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFreeInput.sizePolicy().hasHeightForWidth())
        self.edtFreeInput.setSizePolicy(sizePolicy)
        self.edtFreeInput.setMinimumSize(QtCore.QSize(373, 24))
        self.edtFreeInput.setText(_fromUtf8(""))
        self.edtFreeInput.setObjectName(_fromUtf8("edtFreeInput"))
        self.gridLayout_5.addWidget(self.edtFreeInput, 5, 1, 1, 2)
        self.lblDate = QtGui.QLabel(self.grpReferral)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout_5.addWidget(self.lblDate, 2, 0, 1, 1)
        self.lblReferralType = QtGui.QLabel(self.grpReferral)
        self.lblReferralType.setObjectName(_fromUtf8("lblReferralType"))
        self.gridLayout_5.addWidget(self.lblReferralType, 0, 0, 1, 1)
        self.edtDate = CDateEdit(self.grpReferral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDate.sizePolicy().hasHeightForWidth())
        self.edtDate.setSizePolicy(sizePolicy)
        self.edtDate.setCalendarPopup(True)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.gridLayout_5.addWidget(self.edtDate, 2, 1, 1, 1)
        self.lblNumber = QtGui.QLabel(self.grpReferral)
        self.lblNumber.setObjectName(_fromUtf8("lblNumber"))
        self.gridLayout_5.addWidget(self.lblNumber, 1, 0, 1, 1)
        self.cmbRelegateOrg = CPolyclinicComboBox(self.grpReferral)
        self.cmbRelegateOrg.setMinimumSize(QtCore.QSize(367, 0))
        self.cmbRelegateOrg.setObjectName(_fromUtf8("cmbRelegateOrg"))
        self.gridLayout_5.addWidget(self.cmbRelegateOrg, 4, 1, 1, 2)
        self.lblRelegateOrg = QtGui.QLabel(self.grpReferral)
        self.lblRelegateOrg.setObjectName(_fromUtf8("lblRelegateOrg"))
        self.gridLayout_5.addWidget(self.lblRelegateOrg, 4, 0, 1, 1)
        self.btnSelectRelegateOrg = QtGui.QToolButton(self.grpReferral)
        self.btnSelectRelegateOrg.setObjectName(_fromUtf8("btnSelectRelegateOrg"))
        self.gridLayout_5.addWidget(self.btnSelectRelegateOrg, 4, 3, 1, 1)
        self.lblPlannedDate = QtGui.QLabel(self.grpReferral)
        self.lblPlannedDate.setObjectName(_fromUtf8("lblPlannedDate"))
        self.gridLayout_5.addWidget(self.lblPlannedDate, 3, 0, 1, 1)
        self.edtPlannedDate = CDateEdit(self.grpReferral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPlannedDate.sizePolicy().hasHeightForWidth())
        self.edtPlannedDate.setSizePolicy(sizePolicy)
        self.edtPlannedDate.setToolTip(_fromUtf8(""))
        self.edtPlannedDate.setCalendarPopup(True)
        self.edtPlannedDate.setObjectName(_fromUtf8("edtPlannedDate"))
        self.gridLayout_5.addWidget(self.edtPlannedDate, 3, 1, 1, 1)
        self.chkFreeInput = QtGui.QCheckBox(self.grpReferral)
        self.chkFreeInput.setObjectName(_fromUtf8("chkFreeInput"))
        self.gridLayout_5.addWidget(self.chkFreeInput, 5, 0, 1, 1)
        self.lblPerson = QtGui.QLabel(self.grpReferral)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout_5.addWidget(self.lblPerson, 6, 0, 1, 1)
        self.edtPerson = QtGui.QLineEdit(self.grpReferral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPerson.sizePolicy().hasHeightForWidth())
        self.edtPerson.setSizePolicy(sizePolicy)
        self.edtPerson.setMinimumSize(QtCore.QSize(401, 0))
        self.edtPerson.setObjectName(_fromUtf8("edtPerson"))
        self.gridLayout_5.addWidget(self.edtPerson, 6, 1, 1, 3)
        self.lblSpeciality = QtGui.QLabel(self.grpReferral)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridLayout_5.addWidget(self.lblSpeciality, 7, 0, 1, 1)
        self.cmbSpeciality = CRBComboBox(self.grpReferral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSpeciality.sizePolicy().hasHeightForWidth())
        self.cmbSpeciality.setSizePolicy(sizePolicy)
        self.cmbSpeciality.setMinimumSize(QtCore.QSize(401, 0))
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout_5.addWidget(self.cmbSpeciality, 7, 1, 1, 3)
        self.lblDiagnosis = QtGui.QLabel(self.grpReferral)
        self.lblDiagnosis.setObjectName(_fromUtf8("lblDiagnosis"))
        self.gridLayout_5.addWidget(self.lblDiagnosis, 8, 0, 1, 1)
        self.cmbMKB = CICDCodeEditEx(self.grpReferral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMKB.sizePolicy().hasHeightForWidth())
        self.cmbMKB.setSizePolicy(sizePolicy)
        self.cmbMKB.setMinimumSize(QtCore.QSize(401, 0))
        self.cmbMKB.setObjectName(_fromUtf8("cmbMKB"))
        self.gridLayout_5.addWidget(self.cmbMKB, 8, 1, 1, 3)
        self.cmbReferralType = CRBComboBox(self.grpReferral)
        self.cmbReferralType.setObjectName(_fromUtf8("cmbReferralType"))
        self.gridLayout_5.addWidget(self.cmbReferralType, 0, 1, 1, 3)
        self.edtNumber = QtGui.QLineEdit(self.grpReferral)
        self.edtNumber.setObjectName(_fromUtf8("edtNumber"))
        self.gridLayout_5.addWidget(self.edtNumber, 1, 1, 1, 3)
        self.gridLayout_2.addWidget(self.grpReferral, 3, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 1, 1, 1)
        self.chkSelectPreviousActions = QtGui.QCheckBox(self.tabStandart)
        self.chkSelectPreviousActions.setEnabled(True)
        self.chkSelectPreviousActions.setObjectName(_fromUtf8("chkSelectPreviousActions"))
        self.gridLayout_2.addWidget(self.chkSelectPreviousActions, 5, 2, 1, 1)
        self.btnAppointment = QtGui.QPushButton(self.tabStandart)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAppointment.sizePolicy().hasHeightForWidth())
        self.btnAppointment.setSizePolicy(sizePolicy)
        self.btnAppointment.setObjectName(_fromUtf8("btnAppointment"))
        self.gridLayout_2.addWidget(self.btnAppointment, 5, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 4, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tabStandart)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.cmbOrg = CPolyclinicComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrg.sizePolicy().hasHeightForWidth())
        self.cmbOrg.setSizePolicy(sizePolicy)
        self.cmbOrg.setMinimumSize(QtCore.QSize(401, 0))
        self.cmbOrg.setObjectName(_fromUtf8("cmbOrg"))
        self.gridLayout_4.addWidget(self.cmbOrg, 0, 2, 1, 9)
        self.lblExternalId = QtGui.QLabel(self.groupBox)
        self.lblExternalId.setObjectName(_fromUtf8("lblExternalId"))
        self.gridLayout_4.addWidget(self.lblExternalId, 8, 1, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPerson.sizePolicy().hasHeightForWidth())
        self.cmbPerson.setSizePolicy(sizePolicy)
        self.cmbPerson.setMinimumSize(QtCore.QSize(401, 0))
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout_4.addWidget(self.cmbPerson, 2, 2, 1, 9)
        self.lblPersonal = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPersonal.sizePolicy().hasHeightForWidth())
        self.lblPersonal.setSizePolicy(sizePolicy)
        self.lblPersonal.setObjectName(_fromUtf8("lblPersonal"))
        self.gridLayout_4.addWidget(self.lblPersonal, 2, 1, 1, 1)
        self.lblEventType = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventType.sizePolicy().hasHeightForWidth())
        self.lblEventType.setSizePolicy(sizePolicy)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridLayout_4.addWidget(self.lblEventType, 1, 1, 1, 1)
        self.chkIncludeRedDays = QtGui.QCheckBox(self.groupBox)
        self.chkIncludeRedDays.setObjectName(_fromUtf8("chkIncludeRedDays"))
        self.gridLayout_4.addWidget(self.chkIncludeRedDays, 5, 1, 1, 1)
        self.chkAddVisits = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkAddVisits.sizePolicy().hasHeightForWidth())
        self.chkAddVisits.setSizePolicy(sizePolicy)
        self.chkAddVisits.setObjectName(_fromUtf8("chkAddVisits"))
        self.gridLayout_4.addWidget(self.chkAddVisits, 5, 2, 1, 9)
        self.edtDays = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDays.sizePolicy().hasHeightForWidth())
        self.edtDays.setSizePolicy(sizePolicy)
        self.edtDays.setObjectName(_fromUtf8("edtDays"))
        self.gridLayout_4.addWidget(self.edtDays, 7, 2, 1, 1)
        self.lblOrg = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrg.sizePolicy().hasHeightForWidth())
        self.lblOrg.setSizePolicy(sizePolicy)
        self.lblOrg.setObjectName(_fromUtf8("lblOrg"))
        self.gridLayout_4.addWidget(self.lblOrg, 0, 1, 1, 1)
        self.lblCuratorId = QtGui.QLabel(self.groupBox)
        self.lblCuratorId.setObjectName(_fromUtf8("lblCuratorId"))
        self.gridLayout_4.addWidget(self.lblCuratorId, 10, 1, 1, 1)
        self.cmbCuratorId = CPersonComboBoxEx(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCuratorId.sizePolicy().hasHeightForWidth())
        self.cmbCuratorId.setSizePolicy(sizePolicy)
        self.cmbCuratorId.setMinimumSize(QtCore.QSize(401, 0))
        self.cmbCuratorId.setObjectName(_fromUtf8("cmbCuratorId"))
        self.gridLayout_4.addWidget(self.cmbCuratorId, 10, 2, 1, 9)
        self.lblAssistantId = QtGui.QLabel(self.groupBox)
        self.lblAssistantId.setObjectName(_fromUtf8("lblAssistantId"))
        self.gridLayout_4.addWidget(self.lblAssistantId, 9, 1, 1, 1)
        self.edtExternalId = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtExternalId.sizePolicy().hasHeightForWidth())
        self.edtExternalId.setSizePolicy(sizePolicy)
        self.edtExternalId.setMinimumSize(QtCore.QSize(401, 0))
        self.edtExternalId.setObjectName(_fromUtf8("edtExternalId"))
        self.gridLayout_4.addWidget(self.edtExternalId, 8, 2, 1, 9)
        self.lblDays = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDays.sizePolicy().hasHeightForWidth())
        self.lblDays.setSizePolicy(sizePolicy)
        self.lblDays.setObjectName(_fromUtf8("lblDays"))
        self.gridLayout_4.addWidget(self.lblDays, 7, 1, 1, 1)
        self.cmbEventType = CRBComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEventType.sizePolicy().hasHeightForWidth())
        self.cmbEventType.setSizePolicy(sizePolicy)
        self.cmbEventType.setMinimumSize(QtCore.QSize(401, 0))
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout_4.addWidget(self.cmbEventType, 1, 2, 1, 9)
        self.cmbTissueType = CRBComboBox(self.groupBox)
        self.cmbTissueType.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTissueType.sizePolicy().hasHeightForWidth())
        self.cmbTissueType.setSizePolicy(sizePolicy)
        self.cmbTissueType.setMinimumSize(QtCore.QSize(401, 25))
        self.cmbTissueType.setObjectName(_fromUtf8("cmbTissueType"))
        self.gridLayout_4.addWidget(self.cmbTissueType, 11, 2, 1, 9)
        self.cmbAssistantId = CPersonComboBoxEx(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAssistantId.sizePolicy().hasHeightForWidth())
        self.cmbAssistantId.setSizePolicy(sizePolicy)
        self.cmbAssistantId.setMinimumSize(QtCore.QSize(401, 0))
        self.cmbAssistantId.setObjectName(_fromUtf8("cmbAssistantId"))
        self.gridLayout_4.addWidget(self.cmbAssistantId, 9, 2, 1, 9)
        self.lblTissueType = QtGui.QLabel(self.groupBox)
        self.lblTissueType.setObjectName(_fromUtf8("lblTissueType"))
        self.gridLayout_4.addWidget(self.lblTissueType, 11, 1, 1, 1)
        self.lblEventSetDate = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventSetDate.sizePolicy().hasHeightForWidth())
        self.lblEventSetDate.setSizePolicy(sizePolicy)
        self.lblEventSetDate.setObjectName(_fromUtf8("lblEventSetDate"))
        self.gridLayout_4.addWidget(self.lblEventSetDate, 4, 1, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(self.groupBox)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout_4.addWidget(self.lblOrgStructure, 3, 1, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbOrgStructure.setSizePolicy(sizePolicy)
        self.cmbOrgStructure.setMinimumSize(QtCore.QSize(401, 0))
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout_4.addWidget(self.cmbOrgStructure, 3, 2, 1, 9)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblEventDateFrom = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventDateFrom.sizePolicy().hasHeightForWidth())
        self.lblEventDateFrom.setSizePolicy(sizePolicy)
        self.lblEventDateFrom.setObjectName(_fromUtf8("lblEventDateFrom"))
        self.horizontalLayout.addWidget(self.lblEventDateFrom)
        self.edtEventSetDate = CDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEventSetDate.sizePolicy().hasHeightForWidth())
        self.edtEventSetDate.setSizePolicy(sizePolicy)
        self.edtEventSetDate.setCalendarPopup(True)
        self.edtEventSetDate.setObjectName(_fromUtf8("edtEventSetDate"))
        self.horizontalLayout.addWidget(self.edtEventSetDate)
        self.edtEventSetTime = QtGui.QTimeEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEventSetTime.sizePolicy().hasHeightForWidth())
        self.edtEventSetTime.setSizePolicy(sizePolicy)
        self.edtEventSetTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtEventSetTime.setCurrentSectionIndex(0)
        self.edtEventSetTime.setObjectName(_fromUtf8("edtEventSetTime"))
        self.horizontalLayout.addWidget(self.edtEventSetTime)
        self.lblEventDateTo = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventDateTo.sizePolicy().hasHeightForWidth())
        self.lblEventDateTo.setSizePolicy(sizePolicy)
        self.lblEventDateTo.setObjectName(_fromUtf8("lblEventDateTo"))
        self.horizontalLayout.addWidget(self.lblEventDateTo)
        self.edtEventDate = CDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEventDate.sizePolicy().hasHeightForWidth())
        self.edtEventDate.setSizePolicy(sizePolicy)
        self.edtEventDate.setCalendarPopup(True)
        self.edtEventDate.setObjectName(_fromUtf8("edtEventDate"))
        self.horizontalLayout.addWidget(self.edtEventDate)
        self.edtEventTime = QtGui.QTimeEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEventTime.sizePolicy().hasHeightForWidth())
        self.edtEventTime.setSizePolicy(sizePolicy)
        self.edtEventTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtEventTime.setCurrentSectionIndex(0)
        self.edtEventTime.setObjectName(_fromUtf8("edtEventTime"))
        self.horizontalLayout.addWidget(self.edtEventTime)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_4.addLayout(self.horizontalLayout, 4, 2, 1, 9)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 3)
        self.btnAppointment.raise_()
        self.chkSelectPreviousActions.raise_()
        self.groupBox.raise_()
        self.grpReferral.raise_()
        self.tabWidget.addTab(self.tabStandart, _fromUtf8(""))
        self.tabNosology = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabNosology.sizePolicy().hasHeightForWidth())
        self.tabNosology.setSizePolicy(sizePolicy)
        self.tabNosology.setObjectName(_fromUtf8("tabNosology"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabNosology)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.edtNosologyDiagnosis = CICDCodeComboBoxEx(self.tabNosology)
        self.edtNosologyDiagnosis.setObjectName(_fromUtf8("edtNosologyDiagnosis"))
        self.gridLayout_3.addWidget(self.edtNosologyDiagnosis, 0, 1, 1, 1)
        self.lblNosologyDiagnosis = QtGui.QLabel(self.tabNosology)
        self.lblNosologyDiagnosis.setObjectName(_fromUtf8("lblNosologyDiagnosis"))
        self.gridLayout_3.addWidget(self.lblNosologyDiagnosis, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tabNosology, _fromUtf8(""))
        self.tabArmyReferral = QtGui.QWidget()
        self.tabArmyReferral.setObjectName(_fromUtf8("tabArmyReferral"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabArmyReferral)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.grpArmyRefferel = QtGui.QGroupBox(self.tabArmyReferral)
        self.grpArmyRefferel.setCheckable(True)
        self.grpArmyRefferel.setChecked(False)
        self.grpArmyRefferel.setObjectName(_fromUtf8("grpArmyRefferel"))
        self.gridLayout_6 = QtGui.QGridLayout(self.grpArmyRefferel)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.edtArmyDate = CDateEdit(self.grpArmyRefferel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtArmyDate.sizePolicy().hasHeightForWidth())
        self.edtArmyDate.setSizePolicy(sizePolicy)
        self.edtArmyDate.setCalendarPopup(True)
        self.edtArmyDate.setObjectName(_fromUtf8("edtArmyDate"))
        self.gridLayout_6.addWidget(self.edtArmyDate, 1, 1, 1, 2)
        self.lblArmyDate = QtGui.QLabel(self.grpArmyRefferel)
        self.lblArmyDate.setObjectName(_fromUtf8("lblArmyDate"))
        self.gridLayout_6.addWidget(self.lblArmyDate, 1, 0, 1, 1)
        self.cmbArmyOrg = CArmyOrgComboBox(self.grpArmyRefferel)
        self.cmbArmyOrg.setObjectName(_fromUtf8("cmbArmyOrg"))
        self.gridLayout_6.addWidget(self.cmbArmyOrg, 2, 1, 1, 1)
        self.cmbArmyNumber = CReferralComboBox(self.grpArmyRefferel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbArmyNumber.sizePolicy().hasHeightForWidth())
        self.cmbArmyNumber.setSizePolicy(sizePolicy)
        self.cmbArmyNumber.setMinimumSize(QtCore.QSize(401, 0))
        self.cmbArmyNumber.setObjectName(_fromUtf8("cmbArmyNumber"))
        self.gridLayout_6.addWidget(self.cmbArmyNumber, 0, 1, 1, 2)
        self.lblArmyFreeInput = QtGui.QLabel(self.grpArmyRefferel)
        self.lblArmyFreeInput.setObjectName(_fromUtf8("lblArmyFreeInput"))
        self.gridLayout_6.addWidget(self.lblArmyFreeInput, 2, 0, 1, 1)
        self.lblArmyNumber = QtGui.QLabel(self.grpArmyRefferel)
        self.lblArmyNumber.setObjectName(_fromUtf8("lblArmyNumber"))
        self.gridLayout_6.addWidget(self.lblArmyNumber, 0, 0, 1, 1)
        self.btnSelectArmyOrg = QtGui.QToolButton(self.grpArmyRefferel)
        self.btnSelectArmyOrg.setObjectName(_fromUtf8("btnSelectArmyOrg"))
        self.gridLayout_6.addWidget(self.btnSelectArmyOrg, 2, 2, 1, 1)
        self.edtArmyFreeInput = QtGui.QLineEdit(self.grpArmyRefferel)
        self.edtArmyFreeInput.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtArmyFreeInput.sizePolicy().hasHeightForWidth())
        self.edtArmyFreeInput.setSizePolicy(sizePolicy)
        self.edtArmyFreeInput.setMinimumSize(QtCore.QSize(373, 24))
        self.edtArmyFreeInput.setText(_fromUtf8(""))
        self.edtArmyFreeInput.setObjectName(_fromUtf8("edtArmyFreeInput"))
        self.gridLayout_6.addWidget(self.edtArmyFreeInput, 3, 1, 1, 2)
        self.chkArmyFreeInput = QtGui.QCheckBox(self.grpArmyRefferel)
        self.chkArmyFreeInput.setObjectName(_fromUtf8("chkArmyFreeInput"))
        self.gridLayout_6.addWidget(self.chkArmyFreeInput, 3, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem5, 4, 1, 1, 1)
        self.lblArmyNumber.raise_()
        self.cmbArmyNumber.raise_()
        self.lblArmyDate.raise_()
        self.edtArmyDate.raise_()
        self.lblArmyFreeInput.raise_()
        self.cmbArmyOrg.raise_()
        self.btnSelectArmyOrg.raise_()
        self.chkArmyFreeInput.raise_()
        self.edtArmyFreeInput.raise_()
        self.verticalLayout.addWidget(self.grpArmyRefferel)
        self.tabWidget.addTab(self.tabArmyReferral, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(PreCreateEventDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.lblDate.setBuddy(self.edtDate)
        self.lblPerson.setBuddy(self.edtPerson)
        self.lblSpeciality.setBuddy(self.cmbSpeciality)
        self.lblDiagnosis.setBuddy(self.cmbMKB)
        self.lblExternalId.setBuddy(self.edtExternalId)
        self.lblPersonal.setBuddy(self.cmbPerson)
        self.lblEventType.setBuddy(self.cmbEventType)
        self.lblOrg.setBuddy(self.cmbOrg)
        self.lblCuratorId.setBuddy(self.cmbCuratorId)
        self.lblAssistantId.setBuddy(self.cmbAssistantId)
        self.lblDays.setBuddy(self.edtDays)
        self.lblTissueType.setBuddy(self.cmbTissueType)
        self.lblEventSetDate.setBuddy(self.edtEventSetDate)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblEventDateTo.setBuddy(self.edtEventDate)
        self.lblArmyDate.setBuddy(self.edtArmyDate)
        self.lblArmyFreeInput.setBuddy(self.edtArmyFreeInput)
        self.lblArmyNumber.setBuddy(self.cmbArmyNumber)

        self.retranslateUi(PreCreateEventDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PreCreateEventDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PreCreateEventDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreCreateEventDialog)
        PreCreateEventDialog.setTabOrder(self.tabWidget, self.cmbOrg)
        PreCreateEventDialog.setTabOrder(self.cmbOrg, self.cmbEventType)
        PreCreateEventDialog.setTabOrder(self.cmbEventType, self.cmbPerson)
        PreCreateEventDialog.setTabOrder(self.cmbPerson, self.cmbOrgStructure)
        PreCreateEventDialog.setTabOrder(self.cmbOrgStructure, self.edtEventSetDate)
        PreCreateEventDialog.setTabOrder(self.edtEventSetDate, self.edtEventSetTime)
        PreCreateEventDialog.setTabOrder(self.edtEventSetTime, self.edtEventDate)
        PreCreateEventDialog.setTabOrder(self.edtEventDate, self.edtEventTime)
        PreCreateEventDialog.setTabOrder(self.edtEventTime, self.chkIncludeRedDays)
        PreCreateEventDialog.setTabOrder(self.chkIncludeRedDays, self.chkAddVisits)
        PreCreateEventDialog.setTabOrder(self.chkAddVisits, self.edtDays)
        PreCreateEventDialog.setTabOrder(self.edtDays, self.edtExternalId)
        PreCreateEventDialog.setTabOrder(self.edtExternalId, self.cmbAssistantId)
        PreCreateEventDialog.setTabOrder(self.cmbAssistantId, self.cmbCuratorId)
        PreCreateEventDialog.setTabOrder(self.cmbCuratorId, self.cmbTissueType)
        PreCreateEventDialog.setTabOrder(self.cmbTissueType, self.grpReferral)
        PreCreateEventDialog.setTabOrder(self.grpReferral, self.cmbReferralType)
        PreCreateEventDialog.setTabOrder(self.cmbReferralType, self.edtNumber)
        PreCreateEventDialog.setTabOrder(self.edtNumber, self.edtDate)
        PreCreateEventDialog.setTabOrder(self.edtDate, self.edtPlannedDate)
        PreCreateEventDialog.setTabOrder(self.edtPlannedDate, self.cmbRelegateOrg)
        PreCreateEventDialog.setTabOrder(self.cmbRelegateOrg, self.btnSelectRelegateOrg)
        PreCreateEventDialog.setTabOrder(self.btnSelectRelegateOrg, self.chkFreeInput)
        PreCreateEventDialog.setTabOrder(self.chkFreeInput, self.edtFreeInput)
        PreCreateEventDialog.setTabOrder(self.edtFreeInput, self.edtPerson)
        PreCreateEventDialog.setTabOrder(self.edtPerson, self.cmbSpeciality)
        PreCreateEventDialog.setTabOrder(self.cmbSpeciality, self.cmbMKB)
        PreCreateEventDialog.setTabOrder(self.cmbMKB, self.btnAppointment)
        PreCreateEventDialog.setTabOrder(self.btnAppointment, self.chkSelectPreviousActions)
        PreCreateEventDialog.setTabOrder(self.chkSelectPreviousActions, self.buttonBox)
        PreCreateEventDialog.setTabOrder(self.buttonBox, self.edtNosologyDiagnosis)
        PreCreateEventDialog.setTabOrder(self.edtNosologyDiagnosis, self.grpArmyRefferel)
        PreCreateEventDialog.setTabOrder(self.grpArmyRefferel, self.cmbArmyNumber)
        PreCreateEventDialog.setTabOrder(self.cmbArmyNumber, self.edtArmyDate)
        PreCreateEventDialog.setTabOrder(self.edtArmyDate, self.cmbArmyOrg)
        PreCreateEventDialog.setTabOrder(self.cmbArmyOrg, self.btnSelectArmyOrg)
        PreCreateEventDialog.setTabOrder(self.btnSelectArmyOrg, self.chkArmyFreeInput)
        PreCreateEventDialog.setTabOrder(self.chkArmyFreeInput, self.edtArmyFreeInput)

    def retranslateUi(self, PreCreateEventDialog):
        PreCreateEventDialog.setWindowTitle(_translate("PreCreateEventDialog", "Новое обращение", None))
        self.grpReferral.setTitle(_translate("PreCreateEventDialog", "Добавить направление из ЛПУ", None))
        self.lblDate.setText(_translate("PreCreateEventDialog", "Дата выдачи направления", None))
        self.lblReferralType.setText(_translate("PreCreateEventDialog", "Тип направления", None))
        self.lblNumber.setText(_translate("PreCreateEventDialog", "Номер направления", None))
        self.lblRelegateOrg.setText(_translate("PreCreateEventDialog", "Направитель", None))
        self.btnSelectRelegateOrg.setText(_translate("PreCreateEventDialog", "...", None))
        self.lblPlannedDate.setToolTip(_translate("PreCreateEventDialog", "Заполняется только для направлений на ВМП", None))
        self.lblPlannedDate.setText(_translate("PreCreateEventDialog", "Дата планируемой госпитализации", None))
        self.chkFreeInput.setText(_translate("PreCreateEventDialog", "Свободный ввод", None))
        self.lblPerson.setText(_translate("PreCreateEventDialog", "Врач", None))
        self.lblSpeciality.setText(_translate("PreCreateEventDialog", "Специальность", None))
        self.cmbSpeciality.setWhatsThis(_translate("PreCreateEventDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None))
        self.lblDiagnosis.setText(_translate("PreCreateEventDialog", "Диагноз", None))
        self.chkSelectPreviousActions.setText(_translate("PreCreateEventDialog", "Отметить действия добавленные в прошлый раз", None))
        self.btnAppointment.setText(_translate("PreCreateEventDialog", "Запись на прием в другое ЛПУ", None))
        self.lblExternalId.setText(_translate("PreCreateEventDialog", "Внешний идентификатор", None))
        self.lblPersonal.setText(_translate("PreCreateEventDialog", "&Врач", None))
        self.lblEventType.setText(_translate("PreCreateEventDialog", "&Цель", None))
        self.chkIncludeRedDays.setText(_translate("PreCreateEventDialog", "включая выходные", None))
        self.chkAddVisits.setText(_translate("PreCreateEventDialog", "Добавить визиты по длительности", None))
        self.lblOrg.setText(_translate("PreCreateEventDialog", "&ЛПУ", None))
        self.lblCuratorId.setText(_translate("PreCreateEventDialog", "Куратор", None))
        self.lblAssistantId.setText(_translate("PreCreateEventDialog", "Ассистент", None))
        self.lblDays.setText(_translate("PreCreateEventDialog", "Дней", None))
        self.lblTissueType.setText(_translate("PreCreateEventDialog", "Тип биоматериала", None))
        self.lblEventSetDate.setText(_translate("PreCreateEventDialog", "&Дата", None))
        self.lblOrgStructure.setText(_translate("PreCreateEventDialog", "&Подразделение", None))
        self.lblEventDateFrom.setText(_translate("PreCreateEventDialog", "с", None))
        self.edtEventSetTime.setDisplayFormat(_translate("PreCreateEventDialog", "HH:mm", None))
        self.lblEventDateTo.setText(_translate("PreCreateEventDialog", "по", None))
        self.edtEventTime.setDisplayFormat(_translate("PreCreateEventDialog", "HH:mm", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStandart), _translate("PreCreateEventDialog", "Стандартное", None))
        self.lblNosologyDiagnosis.setText(_translate("PreCreateEventDialog", "Диагноз", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNosology), _translate("PreCreateEventDialog", "Нозология (ф.30)", None))
        self.grpArmyRefferel.setTitle(_translate("PreCreateEventDialog", "Добавить направление из военкомата", None))
        self.lblArmyDate.setText(_translate("PreCreateEventDialog", "Дата выдачи направления", None))
        self.lblArmyFreeInput.setText(_translate("PreCreateEventDialog", "Направитель", None))
        self.lblArmyNumber.setText(_translate("PreCreateEventDialog", "Номер направления", None))
        self.btnSelectArmyOrg.setText(_translate("PreCreateEventDialog", "...", None))
        self.chkArmyFreeInput.setText(_translate("PreCreateEventDialog", "Свободный ввод", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabArmyReferral), _translate("PreCreateEventDialog", "Направление из военкомата", None))

from Orgs.OrgComboBox import CArmyOrgComboBox, CPolyclinicComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeComboBoxEx, CICDCodeEditEx
from library.ReferralComboBox import CReferralComboBox
from library.crbcombobox import CRBComboBox
