# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReferralPage.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReferralPage(object):
    def setupUi(self, ReferralPage):
        ReferralPage.setObjectName(_fromUtf8("ReferralPage"))
        ReferralPage.resize(1265, 795)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ReferralPage.sizePolicy().hasHeightForWidth())
        ReferralPage.setSizePolicy(sizePolicy)
        ReferralPage.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_5 = QtGui.QGridLayout(ReferralPage)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tabWidget = QtGui.QTabWidget(ReferralPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabReserved = QtGui.QWidget()
        self.tabReserved.setObjectName(_fromUtf8("tabReserved"))
        self.gridLayout = QtGui.QGridLayout(self.tabReserved)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tblRefType = QtGui.QTableView(self.tabReserved)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblRefType.sizePolicy().hasHeightForWidth())
        self.tblRefType.setSizePolicy(sizePolicy)
        self.tblRefType.setObjectName(_fromUtf8("tblRefType"))
        self.gridLayout.addWidget(self.tblRefType, 0, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.tabReserved)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 963, 726))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_8 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.splitter = QtGui.QSplitter(self.scrollAreaWidgetContents)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.btnRefGenNumber = QtGui.QPushButton(self.layoutWidget)
        self.btnRefGenNumber.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnRefGenNumber.setObjectName(_fromUtf8("btnRefGenNumber"))
        self.gridLayout_3.addWidget(self.btnRefGenNumber, 0, 1, 1, 1)
        self.edtRefNumber = QtGui.QLineEdit(self.layoutWidget)
        self.edtRefNumber.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtRefNumber.setObjectName(_fromUtf8("edtRefNumber"))
        self.gridLayout_3.addWidget(self.edtRefNumber, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.edtRefMKB = CICDCodeEditEx(self.layoutWidget)
        self.edtRefMKB.setObjectName(_fromUtf8("edtRefMKB"))
        self.gridLayout_6.addWidget(self.edtRefMKB, 11, 1, 1, 1)
        self.lblRelegateMo = QtGui.QLabel(self.layoutWidget)
        self.lblRelegateMo.setObjectName(_fromUtf8("lblRelegateMo"))
        self.gridLayout_6.addWidget(self.lblRelegateMo, 9, 0, 1, 1)
        self.lblNotes = QtGui.QLabel(self.layoutWidget)
        self.lblNotes.setObjectName(_fromUtf8("lblNotes"))
        self.gridLayout_6.addWidget(self.lblNotes, 13, 0, 1, 1)
        self.lblRefBedProfile = QtGui.QLabel(self.layoutWidget)
        self.lblRefBedProfile.setObjectName(_fromUtf8("lblRefBedProfile"))
        self.gridLayout_6.addWidget(self.lblRefBedProfile, 5, 0, 1, 1)
        self.cmbRefHospType = QtGui.QComboBox(self.layoutWidget)
        self.cmbRefHospType.setObjectName(_fromUtf8("cmbRefHospType"))
        self.cmbRefHospType.addItem(_fromUtf8(""))
        self.cmbRefHospType.addItem(_fromUtf8(""))
        self.cmbRefHospType.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cmbRefHospType, 4, 1, 1, 1)
        self.lblRefMKB = QtGui.QLabel(self.layoutWidget)
        self.lblRefMKB.setObjectName(_fromUtf8("lblRefMKB"))
        self.gridLayout_6.addWidget(self.lblRefMKB, 11, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 15, 0, 1, 1)
        self.cmbMedProfile = CRBComboBox(self.layoutWidget)
        self.cmbMedProfile.setObjectName(_fromUtf8("cmbMedProfile"))
        self.gridLayout_6.addWidget(self.cmbMedProfile, 10, 1, 1, 1)
        self.chkRefAgreement = QtGui.QCheckBox(self.layoutWidget)
        self.chkRefAgreement.setObjectName(_fromUtf8("chkRefAgreement"))
        self.gridLayout_6.addWidget(self.chkRefAgreement, 12, 0, 1, 2)
        self.lblPerson = QtGui.QLabel(self.layoutWidget)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout_6.addWidget(self.lblPerson, 3, 0, 1, 1)
        self.edtNotes = QtGui.QTextEdit(self.layoutWidget)
        self.edtNotes.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtNotes.setObjectName(_fromUtf8("edtNotes"))
        self.gridLayout_6.addWidget(self.edtNotes, 14, 0, 1, 2)
        self.cmbRefBedProfile = CRBComboBox(self.layoutWidget)
        self.cmbRefBedProfile.setObjectName(_fromUtf8("cmbRefBedProfile"))
        self.gridLayout_6.addWidget(self.cmbRefBedProfile, 5, 1, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(self.layoutWidget)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout_6.addWidget(self.cmbPerson, 3, 1, 1, 1)
        self.lblRefNumber = QtGui.QLabel(self.layoutWidget)
        self.lblRefNumber.setObjectName(_fromUtf8("lblRefNumber"))
        self.gridLayout_6.addWidget(self.lblRefNumber, 0, 0, 1, 1)
        self.lblRefDate = QtGui.QLabel(self.layoutWidget)
        self.lblRefDate.setObjectName(_fromUtf8("lblRefDate"))
        self.gridLayout_6.addWidget(self.lblRefDate, 1, 0, 1, 1)
        self.lblRefHospType = QtGui.QLabel(self.layoutWidget)
        self.lblRefHospType.setObjectName(_fromUtf8("lblRefHospType"))
        self.gridLayout_6.addWidget(self.lblRefHospType, 4, 0, 1, 1)
        self.lblRefPlanned = QtGui.QLabel(self.layoutWidget)
        self.lblRefPlanned.setObjectName(_fromUtf8("lblRefPlanned"))
        self.gridLayout_6.addWidget(self.lblRefPlanned, 2, 0, 1, 1)
        self.lblMedProfile = QtGui.QLabel(self.layoutWidget)
        self.lblMedProfile.setObjectName(_fromUtf8("lblMedProfile"))
        self.gridLayout_6.addWidget(self.lblMedProfile, 10, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.cmbRelegateMO = COrgComboBox(self.layoutWidget)
        self.cmbRelegateMO.setObjectName(_fromUtf8("cmbRelegateMO"))
        self.gridLayout_7.addWidget(self.cmbRelegateMO, 0, 0, 1, 1)
        self.btnOrgFilter = QtGui.QToolButton(self.layoutWidget)
        self.btnOrgFilter.setObjectName(_fromUtf8("btnOrgFilter"))
        self.gridLayout_7.addWidget(self.btnOrgFilter, 0, 1, 1, 1)
        self.btnResetMo = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResetMo.sizePolicy().hasHeightForWidth())
        self.btnResetMo.setSizePolicy(sizePolicy)
        self.btnResetMo.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btnResetMo.setObjectName(_fromUtf8("btnResetMo"))
        self.gridLayout_7.addWidget(self.btnResetMo, 0, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 9, 1, 1, 1)
        self.cmbOrgStructure = CRBComboBox(self.layoutWidget)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout_6.addWidget(self.cmbOrgStructure, 6, 1, 1, 1)
        self.lblOrgStructureProfile = QtGui.QLabel(self.layoutWidget)
        self.lblOrgStructureProfile.setObjectName(_fromUtf8("lblOrgStructureProfile"))
        self.gridLayout_6.addWidget(self.lblOrgStructureProfile, 6, 0, 1, 1)
        self.cmbStatyonaryType = QtGui.QComboBox(self.layoutWidget)
        self.cmbStatyonaryType.setObjectName(_fromUtf8("cmbStatyonaryType"))
        self.cmbStatyonaryType.addItem(_fromUtf8(""))
        self.cmbStatyonaryType.addItem(_fromUtf8(""))
        self.cmbStatyonaryType.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cmbStatyonaryType, 7, 1, 1, 1)
        self.lblStatyonaryType = QtGui.QLabel(self.layoutWidget)
        self.lblStatyonaryType.setObjectName(_fromUtf8("lblStatyonaryType"))
        self.gridLayout_6.addWidget(self.lblStatyonaryType, 7, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.dtRefPlaned = CDateEdit(self.layoutWidget)
        self.dtRefPlaned.setObjectName(_fromUtf8("dtRefPlaned"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.dtRefPlaned)
        self.gridLayout_6.addLayout(self.formLayout, 2, 1, 1, 1)
        self.lblExamType = QtGui.QLabel(self.layoutWidget)
        self.lblExamType.setObjectName(_fromUtf8("lblExamType"))
        self.gridLayout_6.addWidget(self.lblExamType, 8, 0, 1, 1)
        self.cmbExamType = QtGui.QComboBox(self.layoutWidget)
        self.cmbExamType.setObjectName(_fromUtf8("cmbExamType"))
        self.cmbExamType.addItem(_fromUtf8(""))
        self.cmbExamType.addItem(_fromUtf8(""))
        self.cmbExamType.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cmbExamType, 8, 1, 1, 1)
        self.dtRefDate = CDateEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtRefDate.sizePolicy().hasHeightForWidth())
        self.dtRefDate.setSizePolicy(sizePolicy)
        self.dtRefDate.setMinimumSize(QtCore.QSize(141, 0))
        self.dtRefDate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dtRefDate.setObjectName(_fromUtf8("dtRefDate"))
        self.gridLayout_6.addWidget(self.dtRefDate, 1, 1, 1, 1)
        self.tblMoList = QtGui.QTableWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblMoList.sizePolicy().hasHeightForWidth())
        self.tblMoList.setSizePolicy(sizePolicy)
        self.tblMoList.setObjectName(_fromUtf8("tblMoList"))
        self.tblMoList.setColumnCount(0)
        self.tblMoList.setRowCount(0)
        self.gridLayout_8.addWidget(self.splitter, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnAnotherLpu = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnAnotherLpu.setObjectName(_fromUtf8("btnAnotherLpu"))
        self.horizontalLayout_2.addWidget(self.btnAnotherLpu)
        self.btnGetMoList = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnGetMoList.setObjectName(_fromUtf8("btnGetMoList"))
        self.horizontalLayout_2.addWidget(self.btnGetMoList)
        self.btnSendRef = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnSendRef.setObjectName(_fromUtf8("btnSendRef"))
        self.horizontalLayout_2.addWidget(self.btnSendRef)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tabReserved, _fromUtf8(""))
        self.history = QtGui.QWidget()
        self.history.setObjectName(_fromUtf8("history"))
        self.gridLayout_2 = QtGui.QGridLayout(self.history)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btnUpdateTable = QtGui.QPushButton(self.history)
        self.btnUpdateTable.setObjectName(_fromUtf8("btnUpdateTable"))
        self.gridLayout_4.addWidget(self.btnUpdateTable, 0, 1, 1, 1)
        self.btnUpdateStatuses = QtGui.QPushButton(self.history)
        self.btnUpdateStatuses.setCheckable(False)
        self.btnUpdateStatuses.setObjectName(_fromUtf8("btnUpdateStatuses"))
        self.gridLayout_4.addWidget(self.btnUpdateStatuses, 0, 2, 1, 1)
        self.btnCancellation = QtGui.QPushButton(self.history)
        self.btnCancellation.setObjectName(_fromUtf8("btnCancellation"))
        self.gridLayout_4.addWidget(self.btnCancellation, 0, 3, 1, 1)
        self.btnResultDocument = QtGui.QPushButton(self.history)
        self.btnResultDocument.setObjectName(_fromUtf8("btnResultDocument"))
        self.gridLayout_4.addWidget(self.btnResultDocument, 0, 0, 1, 1)
        self.btnEditReferral = QtGui.QPushButton(self.history)
        self.btnEditReferral.setObjectName(_fromUtf8("btnEditReferral"))
        self.gridLayout_4.addWidget(self.btnEditReferral, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 1, 1, 1, 1)
        self.scrollArea_2 = QtGui.QScrollArea(self.history)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1225, 691))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tblHistory = QtGui.QTableView(self.scrollAreaWidgetContents_2)
        self.tblHistory.setMinimumSize(QtCore.QSize(0, 200))
        self.tblHistory.setObjectName(_fromUtf8("tblHistory"))
        self.horizontalLayout.addWidget(self.tblHistory)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.scrollArea_2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.history, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(ReferralPage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ReferralPage)
        ReferralPage.setTabOrder(self.edtRefNumber, self.btnRefGenNumber)
        ReferralPage.setTabOrder(self.btnRefGenNumber, self.dtRefDate)
        ReferralPage.setTabOrder(self.dtRefDate, self.dtRefPlaned)
        ReferralPage.setTabOrder(self.dtRefPlaned, self.cmbPerson)
        ReferralPage.setTabOrder(self.cmbPerson, self.cmbRefHospType)
        ReferralPage.setTabOrder(self.cmbRefHospType, self.cmbRefBedProfile)
        ReferralPage.setTabOrder(self.cmbRefBedProfile, self.cmbOrgStructure)
        ReferralPage.setTabOrder(self.cmbOrgStructure, self.cmbStatyonaryType)
        ReferralPage.setTabOrder(self.cmbStatyonaryType, self.cmbRelegateMO)
        ReferralPage.setTabOrder(self.cmbRelegateMO, self.btnOrgFilter)
        ReferralPage.setTabOrder(self.btnOrgFilter, self.cmbMedProfile)
        ReferralPage.setTabOrder(self.cmbMedProfile, self.edtRefMKB)
        ReferralPage.setTabOrder(self.edtRefMKB, self.chkRefAgreement)
        ReferralPage.setTabOrder(self.chkRefAgreement, self.edtNotes)
        ReferralPage.setTabOrder(self.edtNotes, self.btnAnotherLpu)
        ReferralPage.setTabOrder(self.btnAnotherLpu, self.btnGetMoList)
        ReferralPage.setTabOrder(self.btnGetMoList, self.btnSendRef)
        ReferralPage.setTabOrder(self.btnSendRef, self.btnResultDocument)
        ReferralPage.setTabOrder(self.btnResultDocument, self.btnUpdateTable)
        ReferralPage.setTabOrder(self.btnUpdateTable, self.btnUpdateStatuses)
        ReferralPage.setTabOrder(self.btnUpdateStatuses, self.btnCancellation)
        ReferralPage.setTabOrder(self.btnCancellation, self.tblRefType)
        ReferralPage.setTabOrder(self.tblRefType, self.tblMoList)
        ReferralPage.setTabOrder(self.tblMoList, self.scrollArea)
        ReferralPage.setTabOrder(self.scrollArea, self.scrollArea_2)
        ReferralPage.setTabOrder(self.scrollArea_2, self.tblHistory)
        ReferralPage.setTabOrder(self.tblHistory, self.tabWidget)

    def retranslateUi(self, ReferralPage):
        ReferralPage.setWindowTitle(_translate("ReferralPage", "Form", None))
        self.btnRefGenNumber.setText(_translate("ReferralPage", "Сформировать", None))
        self.lblRelegateMo.setText(_translate("ReferralPage", "Направлен в МО:", None))
        self.lblNotes.setText(_translate("ReferralPage", "Примечание:", None))
        self.lblRefBedProfile.setText(_translate("ReferralPage", "Профиль койки:", None))
        self.cmbRefHospType.setItemText(0, _translate("ReferralPage", "не задано", None))
        self.cmbRefHospType.setItemText(1, _translate("ReferralPage", "Плановая", None))
        self.cmbRefHospType.setItemText(2, _translate("ReferralPage", "Экстренная", None))
        self.lblRefMKB.setText(_translate("ReferralPage", "Диагноз:", None))
        self.chkRefAgreement.setText(_translate("ReferralPage", "Согласие на превышение дней ожидания", None))
        self.lblPerson.setText(_translate("ReferralPage", "Врач:", None))
        self.lblRefNumber.setText(_translate("ReferralPage", "Номер направления:", None))
        self.lblRefDate.setText(_translate("ReferralPage", "Дата направления:", None))
        self.lblRefHospType.setText(_translate("ReferralPage", "Тип госпитализации:", None))
        self.lblRefPlanned.setText(_translate("ReferralPage", "Дата планируемой госпитализации:", None))
        self.lblMedProfile.setText(_translate("ReferralPage", "Специальность:", None))
        self.btnOrgFilter.setText(_translate("ReferralPage", "...", None))
        self.btnResetMo.setText(_translate("ReferralPage", "Очистить", None))
        self.lblOrgStructureProfile.setText(_translate("ReferralPage", "Профиль отделения:", None))
        self.cmbStatyonaryType.setItemText(0, _translate("ReferralPage", "не задано", None))
        self.cmbStatyonaryType.setItemText(1, _translate("ReferralPage", "Стационар", None))
        self.cmbStatyonaryType.setItemText(2, _translate("ReferralPage", "Дневной стационар", None))
        self.lblStatyonaryType.setText(_translate("ReferralPage", "Тип стационара:", None))
        self.lblExamType.setText(_translate("ReferralPage", "Вид назначенного обследования:", None))
        self.cmbExamType.setItemText(0, _translate("ReferralPage", "не задано", None))
        self.cmbExamType.setItemText(1, _translate("ReferralPage", "инструментальная диагностика", None))
        self.cmbExamType.setItemText(2, _translate("ReferralPage", "методы лучевой диагностики", None))
        self.btnAnotherLpu.setText(_translate("ReferralPage", "Запись в другое ЛПУ", None))
        self.btnGetMoList.setText(_translate("ReferralPage", "Запросить список МО", None))
        self.btnSendRef.setText(_translate("ReferralPage", "Отправить направление", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabReserved), _translate("ReferralPage", "Новое направление", None))
        self.btnUpdateTable.setText(_translate("ReferralPage", "Обновить сведения таблицы", None))
        self.btnUpdateStatuses.setText(_translate("ReferralPage", "Обновить статусы направлений ", None))
        self.btnCancellation.setText(_translate("ReferralPage", "Аннулировать направление", None))
        self.btnResultDocument.setText(_translate("ReferralPage", "Получить результирующий документ", None))
        self.btnEditReferral.setText(_translate("ReferralPage", "Редактировать направление", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.history), _translate("ReferralPage", "История", None))

from Orgs.OrgComboBox import COrgComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEditEx
from library.crbcombobox import CRBComboBox
