# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogicalControlDoubles.ui'
#
# Created: Fri Nov 13 19:07:30 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LogicalControlDoubles(object):
    def setupUi(self, LogicalControlDoubles):
        LogicalControlDoubles.setObjectName(_fromUtf8("LogicalControlDoubles"))
        LogicalControlDoubles.resize(731, 506)
        self.gridLayout_2 = QtGui.QGridLayout(LogicalControlDoubles)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btnBeginCheck = QtGui.QPushButton(LogicalControlDoubles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBeginCheck.sizePolicy().hasHeightForWidth())
        self.btnBeginCheck.setSizePolicy(sizePolicy)
        self.btnBeginCheck.setMinimumSize(QtCore.QSize(100, 0))
        self.btnBeginCheck.setObjectName(_fromUtf8("btnBeginCheck"))
        self.gridLayout_2.addWidget(self.btnBeginCheck, 4, 8, 1, 1)
        self.btnEndCheck = QtGui.QPushButton(LogicalControlDoubles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEndCheck.sizePolicy().hasHeightForWidth())
        self.btnEndCheck.setSizePolicy(sizePolicy)
        self.btnEndCheck.setMinimumSize(QtCore.QSize(100, 0))
        self.btnEndCheck.setObjectName(_fromUtf8("btnEndCheck"))
        self.gridLayout_2.addWidget(self.btnEndCheck, 4, 11, 1, 1)
        self.prbControlDoubles = CProgressBar(LogicalControlDoubles)
        self.prbControlDoubles.setObjectName(_fromUtf8("prbControlDoubles"))
        self.gridLayout_2.addWidget(self.prbControlDoubles, 2, 0, 1, 12)
        self.btnContinue = QtGui.QPushButton(LogicalControlDoubles)
        self.btnContinue.setEnabled(False)
        self.btnContinue.setObjectName(_fromUtf8("btnContinue"))
        self.gridLayout_2.addWidget(self.btnContinue, 4, 10, 1, 1)
        self.gbSearchTemplates = QtGui.QGroupBox(LogicalControlDoubles)
        self.gbSearchTemplates.setObjectName(_fromUtf8("gbSearchTemplates"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gbSearchTemplates)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblTemplateDir = QtGui.QLabel(self.gbSearchTemplates)
        self.lblTemplateDir.setObjectName(_fromUtf8("lblTemplateDir"))
        self.gridLayout_3.addWidget(self.lblTemplateDir, 0, 0, 1, 1)
        self.edtTemplateDir = QtGui.QLineEdit(self.gbSearchTemplates)
        self.edtTemplateDir.setReadOnly(True)
        self.edtTemplateDir.setObjectName(_fromUtf8("edtTemplateDir"))
        self.gridLayout_3.addWidget(self.edtTemplateDir, 0, 1, 1, 1)
        self.btnTemplateDirBrowse = QtGui.QToolButton(self.gbSearchTemplates)
        self.btnTemplateDirBrowse.setObjectName(_fromUtf8("btnTemplateDirBrowse"))
        self.gridLayout_3.addWidget(self.btnTemplateDirBrowse, 0, 2, 1, 1)
        self.cmbTemplateName = QtGui.QComboBox(self.gbSearchTemplates)
        self.cmbTemplateName.setEditable(True)
        self.cmbTemplateName.setObjectName(_fromUtf8("cmbTemplateName"))
        self.gridLayout_3.addWidget(self.cmbTemplateName, 0, 3, 1, 1)
        self.btnSaveTemplate = QtGui.QPushButton(self.gbSearchTemplates)
        self.btnSaveTemplate.setEnabled(False)
        self.btnSaveTemplate.setObjectName(_fromUtf8("btnSaveTemplate"))
        self.gridLayout_3.addWidget(self.btnSaveTemplate, 0, 4, 1, 1)
        self.gridLayout_2.addWidget(self.gbSearchTemplates, 1, 0, 1, 12)
        self.tabWidget = QtGui.QTabWidget(LogicalControlDoubles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabFilters = QtGui.QWidget()
        self.tabFilters.setObjectName(_fromUtf8("tabFilters"))
        self.gridLayout = QtGui.QGridLayout(self.tabFilters)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblComparisonPrecisionUnit_6 = QtGui.QLabel(self.tabFilters)
        self.lblComparisonPrecisionUnit_6.setObjectName(_fromUtf8("lblComparisonPrecisionUnit_6"))
        self.gridLayout.addWidget(self.lblComparisonPrecisionUnit_6, 2, 5, 1, 1)
        self.lblComparisonPrecisionUnit = QtGui.QLabel(self.tabFilters)
        self.lblComparisonPrecisionUnit.setObjectName(_fromUtf8("lblComparisonPrecisionUnit"))
        self.gridLayout.addWidget(self.lblComparisonPrecisionUnit, 1, 2, 1, 1)
        self.lblPermisibleComparsonPrecision = QtGui.QLabel(self.tabFilters)
        self.lblPermisibleComparsonPrecision.setWordWrap(True)
        self.lblPermisibleComparsonPrecision.setObjectName(_fromUtf8("lblPermisibleComparsonPrecision"))
        self.gridLayout.addWidget(self.lblPermisibleComparsonPrecision, 0, 1, 1, 2)
        self.chkName = QtGui.QCheckBox(self.tabFilters)
        self.chkName.setChecked(True)
        self.chkName.setObjectName(_fromUtf8("chkName"))
        self.gridLayout.addWidget(self.chkName, 1, 0, 1, 1)
        self.spbNameComparisonPrecision = QtGui.QSpinBox(self.tabFilters)
        self.spbNameComparisonPrecision.setObjectName(_fromUtf8("spbNameComparisonPrecision"))
        self.gridLayout.addWidget(self.spbNameComparisonPrecision, 1, 1, 1, 1)
        self.spbLocAddressComparisonPrecision = QtGui.QSpinBox(self.tabFilters)
        self.spbLocAddressComparisonPrecision.setObjectName(_fromUtf8("spbLocAddressComparisonPrecision"))
        self.gridLayout.addWidget(self.spbLocAddressComparisonPrecision, 1, 4, 1, 1)
        self.chkLocAddress = QtGui.QCheckBox(self.tabFilters)
        self.chkLocAddress.setChecked(True)
        self.chkLocAddress.setObjectName(_fromUtf8("chkLocAddress"))
        self.gridLayout.addWidget(self.chkLocAddress, 1, 3, 1, 1)
        self.lblComparisonPrecisionUnit_5 = QtGui.QLabel(self.tabFilters)
        self.lblComparisonPrecisionUnit_5.setObjectName(_fromUtf8("lblComparisonPrecisionUnit_5"))
        self.gridLayout.addWidget(self.lblComparisonPrecisionUnit_5, 1, 5, 1, 1)
        self.chkPolicy = QtGui.QCheckBox(self.tabFilters)
        self.chkPolicy.setChecked(True)
        self.chkPolicy.setObjectName(_fromUtf8("chkPolicy"))
        self.gridLayout.addWidget(self.chkPolicy, 5, 3, 1, 1)
        self.lblComparisonPrecisionUnit_4 = QtGui.QLabel(self.tabFilters)
        self.lblComparisonPrecisionUnit_4.setObjectName(_fromUtf8("lblComparisonPrecisionUnit_4"))
        self.gridLayout.addWidget(self.lblComparisonPrecisionUnit_4, 6, 2, 1, 1)
        self.chkBirthPlace = QtGui.QCheckBox(self.tabFilters)
        self.chkBirthPlace.setChecked(True)
        self.chkBirthPlace.setObjectName(_fromUtf8("chkBirthPlace"))
        self.gridLayout.addWidget(self.chkBirthPlace, 4, 0, 1, 1)
        self.chkCreateDate = QtGui.QCheckBox(self.tabFilters)
        self.chkCreateDate.setChecked(True)
        self.chkCreateDate.setObjectName(_fromUtf8("chkCreateDate"))
        self.gridLayout.addWidget(self.chkCreateDate, 3, 3, 1, 1)
        self.chkBirthDate = QtGui.QCheckBox(self.tabFilters)
        self.chkBirthDate.setChecked(True)
        self.chkBirthDate.setObjectName(_fromUtf8("chkBirthDate"))
        self.gridLayout.addWidget(self.chkBirthDate, 3, 0, 1, 1)
        self.spbPolicyComparisonPrecision = QtGui.QSpinBox(self.tabFilters)
        self.spbPolicyComparisonPrecision.setObjectName(_fromUtf8("spbPolicyComparisonPrecision"))
        self.gridLayout.addWidget(self.spbPolicyComparisonPrecision, 5, 4, 1, 1)
        self.lblComparisonPrecisionUnit_7 = QtGui.QLabel(self.tabFilters)
        self.lblComparisonPrecisionUnit_7.setObjectName(_fromUtf8("lblComparisonPrecisionUnit_7"))
        self.gridLayout.addWidget(self.lblComparisonPrecisionUnit_7, 4, 5, 1, 1)
        self.spbSNILSComparisonPrecision = QtGui.QSpinBox(self.tabFilters)
        self.spbSNILSComparisonPrecision.setObjectName(_fromUtf8("spbSNILSComparisonPrecision"))
        self.gridLayout.addWidget(self.spbSNILSComparisonPrecision, 4, 4, 1, 1)
        self.lblComparisonPrecisionUnit_8 = QtGui.QLabel(self.tabFilters)
        self.lblComparisonPrecisionUnit_8.setObjectName(_fromUtf8("lblComparisonPrecisionUnit_8"))
        self.gridLayout.addWidget(self.lblComparisonPrecisionUnit_8, 5, 5, 1, 1)
        self.lblComparisonPrecisionUnit_2 = QtGui.QLabel(self.tabFilters)
        self.lblComparisonPrecisionUnit_2.setObjectName(_fromUtf8("lblComparisonPrecisionUnit_2"))
        self.gridLayout.addWidget(self.lblComparisonPrecisionUnit_2, 4, 2, 1, 1)
        self.spbBirthPlaceComparisonPrecision = QtGui.QSpinBox(self.tabFilters)
        self.spbBirthPlaceComparisonPrecision.setObjectName(_fromUtf8("spbBirthPlaceComparisonPrecision"))
        self.gridLayout.addWidget(self.spbBirthPlaceComparisonPrecision, 4, 1, 1, 1)
        self.chkCitizenship = QtGui.QCheckBox(self.tabFilters)
        self.chkCitizenship.setChecked(True)
        self.chkCitizenship.setObjectName(_fromUtf8("chkCitizenship"))
        self.gridLayout.addWidget(self.chkCitizenship, 5, 0, 1, 1)
        self.chkSNILS = QtGui.QCheckBox(self.tabFilters)
        self.chkSNILS.setChecked(True)
        self.chkSNILS.setObjectName(_fromUtf8("chkSNILS"))
        self.gridLayout.addWidget(self.chkSNILS, 4, 3, 1, 1)
        self.spbRegAddressComparisonPrecision = QtGui.QSpinBox(self.tabFilters)
        self.spbRegAddressComparisonPrecision.setObjectName(_fromUtf8("spbRegAddressComparisonPrecision"))
        self.gridLayout.addWidget(self.spbRegAddressComparisonPrecision, 2, 4, 1, 1)
        self.chkRegAddress = QtGui.QCheckBox(self.tabFilters)
        self.chkRegAddress.setChecked(True)
        self.chkRegAddress.setObjectName(_fromUtf8("chkRegAddress"))
        self.gridLayout.addWidget(self.chkRegAddress, 2, 3, 1, 1)
        self.chkSex = QtGui.QCheckBox(self.tabFilters)
        self.chkSex.setChecked(True)
        self.chkSex.setObjectName(_fromUtf8("chkSex"))
        self.gridLayout.addWidget(self.chkSex, 2, 0, 1, 1)
        self.spbDocumentComparisonPrecision = QtGui.QSpinBox(self.tabFilters)
        self.spbDocumentComparisonPrecision.setObjectName(_fromUtf8("spbDocumentComparisonPrecision"))
        self.gridLayout.addWidget(self.spbDocumentComparisonPrecision, 6, 1, 1, 1)
        self.lblPermisibleComparsonPrecisionCol2 = QtGui.QLabel(self.tabFilters)
        self.lblPermisibleComparsonPrecisionCol2.setWordWrap(True)
        self.lblPermisibleComparsonPrecisionCol2.setObjectName(_fromUtf8("lblPermisibleComparsonPrecisionCol2"))
        self.gridLayout.addWidget(self.lblPermisibleComparsonPrecisionCol2, 0, 4, 1, 2)
        self.chkDocuments = QtGui.QCheckBox(self.tabFilters)
        self.chkDocuments.setChecked(True)
        self.chkDocuments.setObjectName(_fromUtf8("chkDocuments"))
        self.gridLayout.addWidget(self.chkDocuments, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tabFilters, _fromUtf8(""))
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName(_fromUtf8("tabSettings"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabSettings)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.chkOneQueryByClient = QtGui.QCheckBox(self.tabSettings)
        self.chkOneQueryByClient.setObjectName(_fromUtf8("chkOneQueryByClient"))
        self.gridLayout_4.addWidget(self.chkOneQueryByClient, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabSettings, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 12)
        self.tblBaseClient = CTableView(LogicalControlDoubles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblBaseClient.sizePolicy().hasHeightForWidth())
        self.tblBaseClient.setSizePolicy(sizePolicy)
        self.tblBaseClient.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblBaseClient.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblBaseClient.setObjectName(_fromUtf8("tblBaseClient"))
        self.gridLayout_2.addWidget(self.tblBaseClient, 3, 0, 1, 1)
        self.tblDuplicateClient = CTableView(LogicalControlDoubles)
        self.tblDuplicateClient.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblDuplicateClient.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblDuplicateClient.setObjectName(_fromUtf8("tblDuplicateClient"))
        self.gridLayout_2.addWidget(self.tblDuplicateClient, 3, 1, 1, 11)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(LogicalControlDoubles)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lblCountRecords = QtGui.QLabel(LogicalControlDoubles)
        self.lblCountRecords.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCountRecords.setObjectName(_fromUtf8("lblCountRecords"))
        self.horizontalLayout.addWidget(self.lblCountRecords)
        self.label_2 = QtGui.QLabel(LogicalControlDoubles)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.lblElapsedTime = QtGui.QLabel(LogicalControlDoubles)
        self.lblElapsedTime.setObjectName(_fromUtf8("lblElapsedTime"))
        self.horizontalLayout.addWidget(self.lblElapsedTime)
        self.label_4 = QtGui.QLabel(LogicalControlDoubles)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 0, 1, 7)
        self.btnPrint = QtGui.QPushButton(LogicalControlDoubles)
        self.btnPrint.setEnabled(False)
        self.btnPrint.setObjectName(_fromUtf8("btnPrint"))
        self.gridLayout_2.addWidget(self.btnPrint, 4, 9, 1, 1)

        self.retranslateUi(LogicalControlDoubles)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LogicalControlDoubles)
        LogicalControlDoubles.setTabOrder(self.chkSex, self.chkBirthDate)
        LogicalControlDoubles.setTabOrder(self.chkBirthDate, self.chkPolicy)
        LogicalControlDoubles.setTabOrder(self.chkPolicy, self.btnBeginCheck)
        LogicalControlDoubles.setTabOrder(self.btnBeginCheck, self.btnEndCheck)

    def retranslateUi(self, LogicalControlDoubles):
        LogicalControlDoubles.setWindowTitle(_translate("LogicalControlDoubles", "Контроль двойников", None))
        self.btnBeginCheck.setText(_translate("LogicalControlDoubles", "Начать проверку", None))
        self.btnEndCheck.setText(_translate("LogicalControlDoubles", "Закрыть", None))
        self.btnContinue.setText(_translate("LogicalControlDoubles", "Продолжить", None))
        self.gbSearchTemplates.setTitle(_translate("LogicalControlDoubles", "Шаблоны поиска", None))
        self.lblTemplateDir.setText(_translate("LogicalControlDoubles", "Директория:", None))
        self.btnTemplateDirBrowse.setText(_translate("LogicalControlDoubles", "...", None))
        self.btnSaveTemplate.setText(_translate("LogicalControlDoubles", "Сохранить шаблон", None))
        self.lblComparisonPrecisionUnit_6.setText(_translate("LogicalControlDoubles", "букв", None))
        self.lblComparisonPrecisionUnit.setText(_translate("LogicalControlDoubles", "букв", None))
        self.lblPermisibleComparsonPrecision.setText(_translate("LogicalControlDoubles", "Допустимая степень расхождения", None))
        self.chkName.setText(_translate("LogicalControlDoubles", "ФИО пациента", None))
        self.chkLocAddress.setText(_translate("LogicalControlDoubles", "Место жительства", None))
        self.lblComparisonPrecisionUnit_5.setText(_translate("LogicalControlDoubles", "букв", None))
        self.chkPolicy.setText(_translate("LogicalControlDoubles", "Полис", None))
        self.lblComparisonPrecisionUnit_4.setText(_translate("LogicalControlDoubles", "букв", None))
        self.chkBirthPlace.setText(_translate("LogicalControlDoubles", "Место рождения", None))
        self.chkCreateDate.setText(_translate("LogicalControlDoubles", "Дата регистрации", None))
        self.chkBirthDate.setText(_translate("LogicalControlDoubles", "Дата рождения пациента", None))
        self.lblComparisonPrecisionUnit_7.setText(_translate("LogicalControlDoubles", "букв", None))
        self.lblComparisonPrecisionUnit_8.setText(_translate("LogicalControlDoubles", "букв", None))
        self.lblComparisonPrecisionUnit_2.setText(_translate("LogicalControlDoubles", "букв", None))
        self.chkCitizenship.setText(_translate("LogicalControlDoubles", "Гражданство", None))
        self.chkSNILS.setText(_translate("LogicalControlDoubles", "СНИЛС", None))
        self.chkRegAddress.setText(_translate("LogicalControlDoubles", "Место регистрации", None))
        self.chkSex.setText(_translate("LogicalControlDoubles", "Пол пациента", None))
        self.lblPermisibleComparsonPrecisionCol2.setText(_translate("LogicalControlDoubles", "Допустимая степень расхождения", None))
        self.chkDocuments.setText(_translate("LogicalControlDoubles", "Документы", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFilters), _translate("LogicalControlDoubles", "Критерии поиска", None))
        self.chkOneQueryByClient.setText(_translate("LogicalControlDoubles", "Отдельный запрос для каждого пациента", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), _translate("LogicalControlDoubles", "Доп. настройки", None))
        self.label.setText(_translate("LogicalControlDoubles", "Найдено пациентов (уникальных/всего):", None))
        self.lblCountRecords.setText(_translate("LogicalControlDoubles", "0/0", None))
        self.label_2.setText(_translate("LogicalControlDoubles", "за", None))
        self.lblElapsedTime.setText(_translate("LogicalControlDoubles", "0", None))
        self.label_4.setText(_translate("LogicalControlDoubles", "c.", None))
        self.btnPrint.setText(_translate("LogicalControlDoubles", "Печать", None))

from library.ProgressBar import CProgressBar
from library.TableView import CTableView
