# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F003.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1084, 571)
        Dialog.setSizeGripEnabled(True)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.sptTopLevel = QtGui.QSplitter(Dialog)
        self.sptTopLevel.setOrientation(QtCore.Qt.Vertical)
        self.sptTopLevel.setObjectName(_fromUtf8("sptTopLevel"))
        self.txtClientInfoBrowser = CTextBrowser(self.sptTopLevel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtClientInfoBrowser.sizePolicy().hasHeightForWidth())
        self.txtClientInfoBrowser.setSizePolicy(sizePolicy)
        self.txtClientInfoBrowser.setMinimumSize(QtCore.QSize(0, 100))
        self.txtClientInfoBrowser.setMaximumSize(QtCore.QSize(16777215, 130))
        self.txtClientInfoBrowser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.tabWidget = QtGui.QTabWidget(self.sptTopLevel)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabToken = QtGui.QWidget()
        self.tabToken.setObjectName(_fromUtf8("tabToken"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabToken)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scrollArea = QtGui.QScrollArea(self.tabToken)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -661, 1036, 1187))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.splitter_3 = QtGui.QSplitter(self.scrollAreaWidgetContents)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setOpaqueResize(True)
        self.splitter_3.setChildrenCollapsible(False)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.frameBaseAndDiagnosises = QtGui.QFrame(self.splitter_3)
        self.frameBaseAndDiagnosises.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameBaseAndDiagnosises.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBaseAndDiagnosises.setObjectName(_fromUtf8("frameBaseAndDiagnosises"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frameBaseAndDiagnosises)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.grpBase = QtGui.QGroupBox(self.frameBaseAndDiagnosises)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpBase.sizePolicy().hasHeightForWidth())
        self.grpBase.setSizePolicy(sizePolicy)
        self.grpBase.setObjectName(_fromUtf8("grpBase"))
        self.gridLayout_6 = QtGui.QGridLayout(self.grpBase)
        self.gridLayout_6.setMargin(4)
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayoutCsg = QtGui.QGridLayout()
        self.gridLayoutCsg.setObjectName(_fromUtf8("gridLayoutCsg"))
        self.gridLayout_6.addLayout(self.gridLayoutCsg, 28, 0, 1, 2)
        self.frame_4 = QtGui.QFrame(self.grpBase)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setSpacing(4)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.edtBegDate = CDateEdit(self.frame_4)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout_8.addWidget(self.edtBegDate)
        self.edtBegTime = QtGui.QTimeEdit(self.frame_4)
        self.edtBegTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtBegTime.setCalendarPopup(False)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.horizontalLayout_8.addWidget(self.edtBegTime)
        self.gridLayout_6.addWidget(self.frame_4, 4, 1, 1, 1)
        self.gbLittleStrangerFlag = QtGui.QGroupBox(self.grpBase)
        self.gbLittleStrangerFlag.setCheckable(True)
        self.gbLittleStrangerFlag.setChecked(False)
        self.gbLittleStrangerFlag.setObjectName(_fromUtf8("gbLittleStrangerFlag"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gbLittleStrangerFlag)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lblChildNumber = QtGui.QLabel(self.gbLittleStrangerFlag)
        self.lblChildNumber.setObjectName(_fromUtf8("lblChildNumber"))
        self.gridLayout_7.addWidget(self.lblChildNumber, 0, 0, 1, 1)
        self.lblChildBirthDate = QtGui.QLabel(self.gbLittleStrangerFlag)
        self.lblChildBirthDate.setObjectName(_fromUtf8("lblChildBirthDate"))
        self.gridLayout_7.addWidget(self.lblChildBirthDate, 1, 0, 1, 1)
        self.lblChildSex = QtGui.QLabel(self.gbLittleStrangerFlag)
        self.lblChildSex.setObjectName(_fromUtf8("lblChildSex"))
        self.gridLayout_7.addWidget(self.lblChildSex, 0, 2, 1, 1)
        self.chkMultipleBirths = QtGui.QCheckBox(self.gbLittleStrangerFlag)
        self.chkMultipleBirths.setObjectName(_fromUtf8("chkMultipleBirths"))
        self.gridLayout_7.addWidget(self.chkMultipleBirths, 3, 0, 1, 4)
        self.edtChildBirthDate = CDateEdit(self.gbLittleStrangerFlag)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtChildBirthDate.sizePolicy().hasHeightForWidth())
        self.edtChildBirthDate.setSizePolicy(sizePolicy)
        self.edtChildBirthDate.setCalendarPopup(True)
        self.edtChildBirthDate.setObjectName(_fromUtf8("edtChildBirthDate"))
        self.gridLayout_7.addWidget(self.edtChildBirthDate, 1, 2, 1, 2)
        self.sbChildNumber = QtGui.QSpinBox(self.gbLittleStrangerFlag)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbChildNumber.sizePolicy().hasHeightForWidth())
        self.sbChildNumber.setSizePolicy(sizePolicy)
        self.sbChildNumber.setMinimum(1)
        self.sbChildNumber.setObjectName(_fromUtf8("sbChildNumber"))
        self.gridLayout_7.addWidget(self.sbChildNumber, 0, 1, 1, 1)
        self.cmbChildSex = QtGui.QComboBox(self.gbLittleStrangerFlag)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbChildSex.sizePolicy().hasHeightForWidth())
        self.cmbChildSex.setSizePolicy(sizePolicy)
        self.cmbChildSex.setObjectName(_fromUtf8("cmbChildSex"))
        self.cmbChildSex.addItem(_fromUtf8(""))
        self.cmbChildSex.setItemText(0, _fromUtf8(""))
        self.cmbChildSex.addItem(_fromUtf8(""))
        self.cmbChildSex.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cmbChildSex, 0, 3, 1, 1)
        self.sbBirthWeight = QtGui.QDoubleSpinBox(self.gbLittleStrangerFlag)
        self.sbBirthWeight.setMaximum(9999.99)
        self.sbBirthWeight.setObjectName(_fromUtf8("sbBirthWeight"))
        self.gridLayout_7.addWidget(self.sbBirthWeight, 2, 2, 1, 2)
        self.lblBirthWeight = QtGui.QLabel(self.gbLittleStrangerFlag)
        self.lblBirthWeight.setObjectName(_fromUtf8("lblBirthWeight"))
        self.gridLayout_7.addWidget(self.lblBirthWeight, 2, 0, 1, 2)
        self.gridLayout_6.addWidget(self.gbLittleStrangerFlag, 15, 0, 1, 2)
        self.edtCycleDay = QtGui.QSpinBox(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtCycleDay.sizePolicy().hasHeightForWidth())
        self.edtCycleDay.setSizePolicy(sizePolicy)
        self.edtCycleDay.setMinimumSize(QtCore.QSize(0, 0))
        self.edtCycleDay.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtCycleDay.setObjectName(_fromUtf8("edtCycleDay"))
        self.gridLayout_6.addWidget(self.edtCycleDay, 14, 1, 1, 1)
        self.frDurAberr = QtGui.QFrame(self.grpBase)
        self.frDurAberr.setFrameShape(QtGui.QFrame.NoFrame)
        self.frDurAberr.setFrameShadow(QtGui.QFrame.Plain)
        self.frDurAberr.setLineWidth(0)
        self.frDurAberr.setObjectName(_fromUtf8("frDurAberr"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frDurAberr)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lblDurationAberration = QtGui.QLabel(self.frDurAberr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDurationAberration.sizePolicy().hasHeightForWidth())
        self.lblDurationAberration.setSizePolicy(sizePolicy)
        self.lblDurationAberration.setObjectName(_fromUtf8("lblDurationAberration"))
        self.horizontalLayout_7.addWidget(self.lblDurationAberration)
        self.lblDurationValueAberration = QtGui.QLabel(self.frDurAberr)
        self.lblDurationValueAberration.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblDurationValueAberration.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblDurationValueAberration.setObjectName(_fromUtf8("lblDurationValueAberration"))
        self.horizontalLayout_7.addWidget(self.lblDurationValueAberration)
        self.gridLayout_6.addWidget(self.frDurAberr, 7, 0, 1, 2)
        self.frame_5 = QtGui.QFrame(self.grpBase)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_5.setLineWidth(0)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setSpacing(4)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.edtEndDate = CDateEdit(self.frame_5)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout_9.addWidget(self.edtEndDate)
        self.edtEndTime = QtGui.QTimeEdit(self.frame_5)
        self.edtEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtEndTime.setCalendarPopup(False)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.horizontalLayout_9.addWidget(self.edtEndTime)
        self.gridLayout_6.addWidget(self.frame_5, 5, 1, 1, 1)
        self.chkIsClosed = QtGui.QCheckBox(self.grpBase)
        self.chkIsClosed.setObjectName(_fromUtf8("chkIsClosed"))
        self.gridLayout_6.addWidget(self.chkIsClosed, 1, 0, 1, 2)
        self.chkZNOMorph = QtGui.QCheckBox(self.grpBase)
        self.chkZNOMorph.setObjectName(_fromUtf8("chkZNOMorph"))
        self.gridLayout_6.addWidget(self.chkZNOMorph, 25, 0, 1, 2)
        self.cmbPrimary = QtGui.QComboBox(self.grpBase)
        self.cmbPrimary.setObjectName(_fromUtf8("cmbPrimary"))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cmbPrimary, 11, 0, 1, 2)
        self.cmbContract = CContractComboBox(self.grpBase)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.cmbContract.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cmbContract, 0, 0, 1, 2)
        self.lblPregnancyWeek = QtGui.QLabel(self.grpBase)
        self.lblPregnancyWeek.setObjectName(_fromUtf8("lblPregnancyWeek"))
        self.gridLayout_6.addWidget(self.lblPregnancyWeek, 13, 0, 1, 1)
        self.cmbHMPMethod = CRBComboBox(self.grpBase)
        self.cmbHMPMethod.setObjectName(_fromUtf8("cmbHMPMethod"))
        self.gridLayout_6.addWidget(self.cmbHMPMethod, 21, 1, 1, 1)
        self.lblCycleDay = QtGui.QLabel(self.grpBase)
        self.lblCycleDay.setObjectName(_fromUtf8("lblCycleDay"))
        self.gridLayout_6.addWidget(self.lblCycleDay, 14, 0, 1, 1)
        self.lblPerson = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPerson.sizePolicy().hasHeightForWidth())
        self.lblPerson.setSizePolicy(sizePolicy)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout_6.addWidget(self.lblPerson, 8, 0, 1, 2)
        self.lblEndDate = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDate.sizePolicy().hasHeightForWidth())
        self.lblEndDate.setSizePolicy(sizePolicy)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout_6.addWidget(self.lblEndDate, 5, 0, 1, 1)
        self.chkExposeConfirmed = QtGui.QCheckBox(self.grpBase)
        self.chkExposeConfirmed.setObjectName(_fromUtf8("chkExposeConfirmed"))
        self.gridLayout_6.addWidget(self.chkExposeConfirmed, 2, 0, 1, 2)
        self.cmbResult = CRBComboBox(self.grpBase)
        self.cmbResult.setObjectName(_fromUtf8("cmbResult"))
        self.cmbResult.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cmbResult, 17, 0, 1, 2)
        self.cmbHMPKind = CRBComboBox(self.grpBase)
        self.cmbHMPKind.setObjectName(_fromUtf8("cmbHMPKind"))
        self.gridLayout_6.addWidget(self.cmbHMPKind, 20, 1, 1, 1)
        self.edtPregnancyWeek = QtGui.QSpinBox(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPregnancyWeek.sizePolicy().hasHeightForWidth())
        self.edtPregnancyWeek.setSizePolicy(sizePolicy)
        self.edtPregnancyWeek.setMaximum(40)
        self.edtPregnancyWeek.setObjectName(_fromUtf8("edtPregnancyWeek"))
        self.gridLayout_6.addWidget(self.edtPregnancyWeek, 13, 1, 1, 1)
        self.chkPrimary = QtGui.QCheckBox(self.grpBase)
        self.chkPrimary.setObjectName(_fromUtf8("chkPrimary"))
        self.gridLayout_6.addWidget(self.chkPrimary, 10, 0, 1, 1)
        self.cmbOrder = CRBComboBox(self.grpBase)
        self.cmbOrder.setObjectName(_fromUtf8("cmbOrder"))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.setItemText(0, _fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cmbOrder, 12, 0, 1, 2)
        self.chkHospParent = QtGui.QCheckBox(self.grpBase)
        self.chkHospParent.setObjectName(_fromUtf8("chkHospParent"))
        self.gridLayout_6.addWidget(self.chkHospParent, 3, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 27, 0, 1, 2)
        self.cmbGoal = CRBComboBox(self.grpBase)
        self.cmbGoal.setObjectName(_fromUtf8("cmbGoal"))
        self.gridLayout_6.addWidget(self.cmbGoal, 18, 1, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(self.grpBase)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cmbPerson, 9, 0, 1, 2)
        self.lblHMPKind = QtGui.QLabel(self.grpBase)
        self.lblHMPKind.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblHMPKind.setObjectName(_fromUtf8("lblHMPKind"))
        self.gridLayout_6.addWidget(self.lblHMPKind, 20, 0, 1, 1)
        self.chkZNOFirst = QtGui.QCheckBox(self.grpBase)
        self.chkZNOFirst.setObjectName(_fromUtf8("chkZNOFirst"))
        self.gridLayout_6.addWidget(self.chkZNOFirst, 22, 0, 1, 2)
        self.cmbIBLocation = CRBComboBox(self.grpBase)
        self.cmbIBLocation.setObjectName(_fromUtf8("cmbIBLocation"))
        self.gridLayout_6.addWidget(self.cmbIBLocation, 19, 1, 1, 1)
        self.lblResult = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblResult.sizePolicy().hasHeightForWidth())
        self.lblResult.setSizePolicy(sizePolicy)
        self.lblResult.setObjectName(_fromUtf8("lblResult"))
        self.gridLayout_6.addWidget(self.lblResult, 16, 0, 1, 2)
        self.lblOrder = QtGui.QLabel(self.grpBase)
        self.lblOrder.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOrder.setObjectName(_fromUtf8("lblOrder"))
        self.gridLayout_6.addWidget(self.lblOrder, 10, 1, 1, 1)
        self.lblIBLocation = QtGui.QLabel(self.grpBase)
        self.lblIBLocation.setObjectName(_fromUtf8("lblIBLocation"))
        self.gridLayout_6.addWidget(self.lblIBLocation, 19, 0, 1, 1)
        self.lblGoal = QtGui.QLabel(self.grpBase)
        self.lblGoal.setObjectName(_fromUtf8("lblGoal"))
        self.gridLayout_6.addWidget(self.lblGoal, 18, 0, 1, 1)
        self.lblBegDate = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDate.sizePolicy().hasHeightForWidth())
        self.lblBegDate.setSizePolicy(sizePolicy)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout_6.addWidget(self.lblBegDate, 4, 0, 1, 1)
        self.lblDurationValue = QtGui.QLabel(self.grpBase)
        self.lblDurationValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblDurationValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblDurationValue.setObjectName(_fromUtf8("lblDurationValue"))
        self.gridLayout_6.addWidget(self.lblDurationValue, 6, 1, 1, 1)
        self.lblDuration = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDuration.sizePolicy().hasHeightForWidth())
        self.lblDuration.setSizePolicy(sizePolicy)
        self.lblDuration.setObjectName(_fromUtf8("lblDuration"))
        self.gridLayout_6.addWidget(self.lblDuration, 6, 0, 1, 1)
        self.lblHMPMethod = QtGui.QLabel(self.grpBase)
        self.lblHMPMethod.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblHMPMethod.setObjectName(_fromUtf8("lblHMPMethod"))
        self.gridLayout_6.addWidget(self.lblHMPMethod, 21, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.grpBase)
        self.splitter_4 = QtGui.QSplitter(self.frameBaseAndDiagnosises)
        self.splitter_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter_4.setFrameShadow(QtGui.QFrame.Plain)
        self.splitter_4.setLineWidth(0)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setChildrenCollapsible(False)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.grpInspections_3 = QtGui.QGroupBox(self.splitter_4)
        self.grpInspections_3.setObjectName(_fromUtf8("grpInspections_3"))
        self._5 = QtGui.QVBoxLayout(self.grpInspections_3)
        self._5.setMargin(4)
        self._5.setSpacing(4)
        self._5.setObjectName(_fromUtf8("_5"))
        self.tblPreliminaryDiagnostics = CDiagnosticsInDocTableView(self.grpInspections_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblPreliminaryDiagnostics.sizePolicy().hasHeightForWidth())
        self.tblPreliminaryDiagnostics.setSizePolicy(sizePolicy)
        self.tblPreliminaryDiagnostics.setMinimumSize(QtCore.QSize(0, 100))
        self.tblPreliminaryDiagnostics.setObjectName(_fromUtf8("tblPreliminaryDiagnostics"))
        self._5.addWidget(self.tblPreliminaryDiagnostics)
        self.grpInspections_4 = QtGui.QGroupBox(self.splitter_4)
        self.grpInspections_4.setObjectName(_fromUtf8("grpInspections_4"))
        self._6 = QtGui.QVBoxLayout(self.grpInspections_4)
        self._6.setMargin(4)
        self._6.setSpacing(4)
        self._6.setObjectName(_fromUtf8("_6"))
        self.tblFinalDiagnostics = CDiagnosticsInDocTableView(self.grpInspections_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblFinalDiagnostics.sizePolicy().hasHeightForWidth())
        self.tblFinalDiagnostics.setSizePolicy(sizePolicy)
        self.tblFinalDiagnostics.setMinimumSize(QtCore.QSize(0, 100))
        self.tblFinalDiagnostics.setObjectName(_fromUtf8("tblFinalDiagnostics"))
        self._6.addWidget(self.tblFinalDiagnostics)
        self.horizontalLayout_6.addWidget(self.splitter_4)
        self.frame_6 = QtGui.QFrame(self.splitter_3)
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.grpActions = QtGui.QGroupBox(self.frame_6)
        self.grpActions.setObjectName(_fromUtf8("grpActions"))
        self._7 = QtGui.QGridLayout(self.grpActions)
        self._7.setMargin(4)
        self._7.setSpacing(4)
        self._7.setObjectName(_fromUtf8("_7"))
        self.tblActions = CInDocTableView(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tblActions.sizePolicy().hasHeightForWidth())
        self.tblActions.setSizePolicy(sizePolicy)
        self.tblActions.setMinimumSize(QtCore.QSize(0, 200))
        self.tblActions.setObjectName(_fromUtf8("tblActions"))
        self._7.addWidget(self.tblActions, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.grpActions)
        self.verticalLayout_8.addWidget(self.splitter_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabToken, _fromUtf8(""))
        self.tabMes = CFastEventMesPage()
        self.tabMes.setObjectName(_fromUtf8("tabMes"))
        self.tabWidget.addTab(self.tabMes, _fromUtf8(""))
        self.tabStatus = CFastActionsPage()
        self.tabStatus.setObjectName(_fromUtf8("tabStatus"))
        self.tabWidget.addTab(self.tabStatus, _fromUtf8(""))
        self.tabDiagnostic = CFastActionsPage()
        self.tabDiagnostic.setObjectName(_fromUtf8("tabDiagnostic"))
        self.tabWidget.addTab(self.tabDiagnostic, _fromUtf8(""))
        self.tabCure = CFastActionsPage()
        self.tabCure.setObjectName(_fromUtf8("tabCure"))
        self.tabWidget.addTab(self.tabCure, _fromUtf8(""))
        self.tabMisc = CFastActionsPage()
        self.tabMisc.setObjectName(_fromUtf8("tabMisc"))
        self.tabWidget.addTab(self.tabMisc, _fromUtf8(""))
        self.tabAnalyses = CFastAnalysesActionsPage()
        self.tabAnalyses.setObjectName(_fromUtf8("tabAnalyses"))
        self.tabWidget.addTab(self.tabAnalyses, _fromUtf8(""))
        self.tabAmbCard = CFastAmbCardPage()
        self.tabAmbCard.setObjectName(_fromUtf8("tabAmbCard"))
        self.tabWidget.addTab(self.tabAmbCard, _fromUtf8(""))
        self.tabTempInvalidEtc = QtGui.QWidget()
        self.tabTempInvalidEtc.setObjectName(_fromUtf8("tabTempInvalidEtc"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabTempInvalidEtc)
        self.gridLayout_8.setMargin(4)
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.scrollArea1 = QtGui.QScrollArea(self.tabTempInvalidEtc)
        self.scrollArea1.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea1.setWidgetResizable(True)
        self.scrollArea1.setObjectName(_fromUtf8("scrollArea1"))
        self.scrollAreaWidgetContents1 = QtGui.QWidget()
        self.scrollAreaWidgetContents1.setGeometry(QtCore.QRect(0, 0, 1056, 314))
        self.scrollAreaWidgetContents1.setObjectName(_fromUtf8("scrollAreaWidgetContents1"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents1)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.tabTempInvalidAndAegrotat = QtGui.QTabWidget(self.scrollAreaWidgetContents1)
        self.tabTempInvalidAndAegrotat.setObjectName(_fromUtf8("tabTempInvalidAndAegrotat"))
        self.tabTempInvalid = QtGui.QWidget()
        self.tabTempInvalid.setObjectName(_fromUtf8("tabTempInvalid"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabTempInvalid)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.grpTempInvalid = CTempInvalid(self.tabTempInvalid)
        self.grpTempInvalid.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpTempInvalid.sizePolicy().hasHeightForWidth())
        self.grpTempInvalid.setSizePolicy(sizePolicy)
        self.grpTempInvalid.setCheckable(True)
        self.grpTempInvalid.setChecked(False)
        self.grpTempInvalid.setObjectName(_fromUtf8("grpTempInvalid"))
        self.gridLayout_3.addWidget(self.grpTempInvalid, 0, 0, 1, 1)
        self.tabTempInvalidAndAegrotat.addTab(self.tabTempInvalid, _fromUtf8(""))
        self.tabTempInvalidS = QtGui.QWidget()
        self.tabTempInvalidS.setObjectName(_fromUtf8("tabTempInvalidS"))
        self.gridLayout = QtGui.QGridLayout(self.tabTempInvalidS)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.grpDisability = CTempInvalid(self.tabTempInvalidS)
        self.grpDisability.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpDisability.sizePolicy().hasHeightForWidth())
        self.grpDisability.setSizePolicy(sizePolicy)
        self.grpDisability.setCheckable(True)
        self.grpDisability.setChecked(False)
        self.grpDisability.setObjectName(_fromUtf8("grpDisability"))
        self.gridLayout.addWidget(self.grpDisability, 0, 0, 1, 1)
        self.tabTempInvalidAndAegrotat.addTab(self.tabTempInvalidS, _fromUtf8(""))
        self.tabTempInvalidDisability = QtGui.QWidget()
        self.tabTempInvalidDisability.setObjectName(_fromUtf8("tabTempInvalidDisability"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabTempInvalidDisability)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.grpVitalRestriction = CTempInvalid(self.tabTempInvalidDisability)
        self.grpVitalRestriction.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpVitalRestriction.sizePolicy().hasHeightForWidth())
        self.grpVitalRestriction.setSizePolicy(sizePolicy)
        self.grpVitalRestriction.setCheckable(True)
        self.grpVitalRestriction.setChecked(False)
        self.grpVitalRestriction.setObjectName(_fromUtf8("grpVitalRestriction"))
        self.gridLayout_2.addWidget(self.grpVitalRestriction, 0, 0, 1, 1)
        self.tabTempInvalidAndAegrotat.addTab(self.tabTempInvalidDisability, _fromUtf8(""))
        self.verticalLayout_9.addWidget(self.tabTempInvalidAndAegrotat)
        self.scrollArea1.setWidget(self.scrollAreaWidgetContents1)
        self.gridLayout_8.addWidget(self.scrollArea1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabTempInvalidEtc, _fromUtf8(""))
        self.tabFeed = CFastEventFeedPage()
        self.tabFeed.setObjectName(_fromUtf8("tabFeed"))
        self.tabWidget.addTab(self.tabFeed, _fromUtf8(""))
        self.tabCash = CFastEventCashPage()
        self.tabCash.setObjectName(_fromUtf8("tabCash"))
        self.tabWidget.addTab(self.tabCash, _fromUtf8(""))
        self.tabNotes = CFastEventNotesPage()
        self.tabNotes.setObjectName(_fromUtf8("tabNotes"))
        self.tabWidget.addTab(self.tabNotes, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.sptTopLevel)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblProlongateEvent = QtGui.QLabel(Dialog)
        self.lblProlongateEvent.setText(_fromUtf8(""))
        self.lblProlongateEvent.setObjectName(_fromUtf8("lblProlongateEvent"))
        self.horizontalLayout_4.addWidget(self.lblProlongateEvent)
        self.lblValueExternalId = QtGui.QLabel(Dialog)
        self.lblValueExternalId.setText(_fromUtf8(""))
        self.lblValueExternalId.setObjectName(_fromUtf8("lblValueExternalId"))
        self.horizontalLayout_4.addWidget(self.lblValueExternalId)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.statusBar = QtGui.QStatusBar(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.verticalLayout_2.addWidget(self.statusBar)
        self.lblChildNumber.setBuddy(self.sbChildNumber)
        self.lblChildBirthDate.setBuddy(self.edtChildBirthDate)
        self.lblChildSex.setBuddy(self.cmbChildSex)
        self.lblBirthWeight.setBuddy(self.sbBirthWeight)
        self.lblPregnancyWeek.setBuddy(self.edtPregnancyWeek)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblHMPKind.setBuddy(self.cmbResult)
        self.lblResult.setBuddy(self.cmbResult)
        self.lblOrder.setBuddy(self.cmbOrder)
        self.lblIBLocation.setBuddy(self.cmbIBLocation)
        self.lblGoal.setBuddy(self.cmbGoal)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblHMPMethod.setBuddy(self.cmbResult)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabTempInvalidAndAegrotat.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.scrollArea)
        Dialog.setTabOrder(self.scrollArea, self.cmbContract)
        Dialog.setTabOrder(self.cmbContract, self.chkIsClosed)
        Dialog.setTabOrder(self.chkIsClosed, self.chkExposeConfirmed)
        Dialog.setTabOrder(self.chkExposeConfirmed, self.chkHospParent)
        Dialog.setTabOrder(self.chkHospParent, self.edtBegDate)
        Dialog.setTabOrder(self.edtBegDate, self.edtBegTime)
        Dialog.setTabOrder(self.edtBegTime, self.edtEndDate)
        Dialog.setTabOrder(self.edtEndDate, self.edtEndTime)
        Dialog.setTabOrder(self.edtEndTime, self.cmbPerson)
        Dialog.setTabOrder(self.cmbPerson, self.chkPrimary)
        Dialog.setTabOrder(self.chkPrimary, self.cmbPrimary)
        Dialog.setTabOrder(self.cmbPrimary, self.cmbOrder)
        Dialog.setTabOrder(self.cmbOrder, self.edtPregnancyWeek)
        Dialog.setTabOrder(self.edtPregnancyWeek, self.edtCycleDay)
        Dialog.setTabOrder(self.edtCycleDay, self.gbLittleStrangerFlag)
        Dialog.setTabOrder(self.gbLittleStrangerFlag, self.sbChildNumber)
        Dialog.setTabOrder(self.sbChildNumber, self.cmbChildSex)
        Dialog.setTabOrder(self.cmbChildSex, self.edtChildBirthDate)
        Dialog.setTabOrder(self.edtChildBirthDate, self.sbBirthWeight)
        Dialog.setTabOrder(self.sbBirthWeight, self.chkMultipleBirths)
        Dialog.setTabOrder(self.chkMultipleBirths, self.cmbResult)
        Dialog.setTabOrder(self.cmbResult, self.cmbGoal)
        Dialog.setTabOrder(self.cmbGoal, self.cmbIBLocation)
        Dialog.setTabOrder(self.cmbIBLocation, self.cmbHMPKind)
        Dialog.setTabOrder(self.cmbHMPKind, self.cmbHMPMethod)
        Dialog.setTabOrder(self.cmbHMPMethod, self.chkZNOFirst)
        Dialog.setTabOrder(self.chkZNOFirst, self.chkZNOMorph)
        Dialog.setTabOrder(self.chkZNOMorph, self.tblPreliminaryDiagnostics)
        Dialog.setTabOrder(self.tblPreliminaryDiagnostics, self.tblFinalDiagnostics)
        Dialog.setTabOrder(self.tblFinalDiagnostics, self.tblActions)
        Dialog.setTabOrder(self.tblActions, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.tabTempInvalidAndAegrotat)
        Dialog.setTabOrder(self.tabTempInvalidAndAegrotat, self.scrollArea)
        Dialog.setTabOrder(self.scrollArea, self.grpTempInvalid)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.txtClientInfoBrowser.setWhatsThis(_translate("Dialog", "Описание пациента", None))
        self.txtClientInfoBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>", None))
        self.grpBase.setTitle(_translate("Dialog", "&ф.003", None))
        self.edtBegDate.setWhatsThis(_translate("Dialog", "дата начала осмотра", None))
        self.edtBegTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.gbLittleStrangerFlag.setTitle(_translate("Dialog", "Признак новорожденного", None))
        self.lblChildNumber.setText(_translate("Dialog", "По счету в семье", None))
        self.lblChildBirthDate.setText(_translate("Dialog", "Дата рождения", None))
        self.lblChildSex.setText(_translate("Dialog", "Пол", None))
        self.chkMultipleBirths.setText(_translate("Dialog", "Многоплодные роды", None))
        self.cmbChildSex.setItemText(1, _translate("Dialog", "М", None))
        self.cmbChildSex.setItemText(2, _translate("Dialog", "Ж", None))
        self.lblBirthWeight.setText(_translate("Dialog", "Вес при рождении", None))
        self.lblDurationAberration.setText(_translate("Dialog", "Норма по МЭС/отклонение", None))
        self.lblDurationValueAberration.setText(_translate("Dialog", "-", None))
        self.edtEndDate.setWhatsThis(_translate("Dialog", "дата окончания осмотра", None))
        self.edtEndTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.chkIsClosed.setText(_translate("Dialog", "Карта заполнена", None))
        self.chkZNOMorph.setToolTip(_translate("Dialog", "ЗНО потдверждён морфологически", None))
        self.chkZNOMorph.setText(_translate("Dialog", "ЗНО подтв. морф-ки", None))
        self.cmbPrimary.setItemText(0, _translate("Dialog", "Первичный", None))
        self.cmbPrimary.setItemText(1, _translate("Dialog", "Повторный", None))
        self.cmbPrimary.setItemText(2, _translate("Dialog", "Актив", None))
        self.cmbContract.setWhatsThis(_translate("Dialog", "номер, дата и основание договора в рамках которого производится осмотр", None))
        self.cmbContract.setItemText(0, _translate("Dialog", "Договор", None))
        self.lblPregnancyWeek.setText(_translate("Dialog", "Неделя беременности", None))
        self.cmbHMPMethod.setWhatsThis(_translate("Dialog", "результат осмотра", None))
        self.lblCycleDay.setText(_translate("Dialog", "День цикла", None))
        self.lblPerson.setText(_translate("Dialog", "Лечащий врач", None))
        self.lblEndDate.setText(_translate("Dialog", "Выбытие", None))
        self.chkExposeConfirmed.setText(_translate("Dialog", "Добавить к выставлению", None))
        self.cmbResult.setWhatsThis(_translate("Dialog", "результат осмотра", None))
        self.cmbResult.setItemText(0, _translate("Dialog", "Результат", None))
        self.cmbHMPKind.setWhatsThis(_translate("Dialog", "результат осмотра", None))
        self.chkPrimary.setText(_translate("Dialog", "Пе&рвичный", None))
        self.cmbOrder.setItemText(1, _translate("Dialog", "Плановый", None))
        self.cmbOrder.setItemText(2, _translate("Dialog", "Экстренный", None))
        self.cmbOrder.setItemText(3, _translate("Dialog", "Самообращение", None))
        self.cmbOrder.setItemText(4, _translate("Dialog", "Принудительный", None))
        self.cmbOrder.setItemText(5, _translate("Dialog", "Неотложный", None))
        self.chkHospParent.setText(_translate("Dialog", "Госпитализация с родителем/представителем", None))
        self.cmbPerson.setWhatsThis(_translate("Dialog", "врач отвечающий за осмотр (терапевт)", None))
        self.cmbPerson.setItemText(0, _translate("Dialog", "Врач", None))
        self.lblHMPKind.setText(_translate("Dialog", "Вид ВМП", None))
        self.chkZNOFirst.setToolTip(_translate("Dialog", "ЗНО установлен впервые", None))
        self.chkZNOFirst.setText(_translate("Dialog", "ЗНО уст. впервые", None))
        self.lblResult.setText(_translate("Dialog", "Результат", None))
        self.lblOrder.setText(_translate("Dialog", "П&орядок", None))
        self.lblIBLocation.setText(_translate("Dialog", "Местонахождение и/б", None))
        self.lblGoal.setText(_translate("Dialog", "Цель", None))
        self.lblBegDate.setText(_translate("Dialog", "Поступление", None))
        self.lblDurationValue.setText(_translate("Dialog", "-", None))
        self.lblDuration.setText(_translate("Dialog", "Длительность", None))
        self.lblHMPMethod.setText(_translate("Dialog", "Метод ВМП", None))
        self.grpInspections_3.setTitle(_translate("Dialog", "&Предварительный диагноз", None))
        self.grpInspections_4.setTitle(_translate("Dialog", "&Заключительный диагноз", None))
        self.grpActions.setTitle(_translate("Dialog", "&Мероприятия", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabToken), _translate("Dialog", "Стат.&учёт", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMes), _translate("Dialog", "Стандарт", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStatus), _translate("Dialog", "&Статус", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDiagnostic), _translate("Dialog", "&Диагностика", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCure), _translate("Dialog", "&Лечение", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMisc), _translate("Dialog", "&Мероприятия", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAnalyses), _translate("Dialog", "&Анализы", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAmbCard), _translate("Dialog", "Мед.&карта", None))
        self.grpTempInvalid.setTitle(_translate("Dialog", "&ВУТ", None))
        self.tabTempInvalidAndAegrotat.setTabText(self.tabTempInvalidAndAegrotat.indexOf(self.tabTempInvalid), _translate("Dialog", "Листок &нетрудоспособности", None))
        self.grpDisability.setTitle(_translate("Dialog", "&Инвалидность", None))
        self.tabTempInvalidAndAegrotat.setTabText(self.tabTempInvalidAndAegrotat.indexOf(self.tabTempInvalidS), _translate("Dialog", "Инвалидность", None))
        self.grpVitalRestriction.setTitle(_translate("Dialog", "&Ограничения жизнедеятельности", None))
        self.tabTempInvalidAndAegrotat.setTabText(self.tabTempInvalidAndAegrotat.indexOf(self.tabTempInvalidDisability), _translate("Dialog", "Ограничения жизнедеятельности", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTempInvalidEtc), _translate("Dialog", "Т&рудоспособность", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFeed), _translate("Dialog", "Питание", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCash), _translate("Dialog", "Оплата", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNotes), _translate("Dialog", "Приме&чания", None))
        self.statusBar.setToolTip(_translate("Dialog", "A status bar", None))
        self.statusBar.setWhatsThis(_translate("Dialog", "A status bar.", None))

from Events.ActionsPage import CFastActionsPage
from Events.AmbCardPage import CFastAmbCardPage
from Events.AnalysesActionsPage import CFastAnalysesActionsPage
from Events.EventCashPage import CFastEventCashPage
from Events.EventDiagnosticsTable import CDiagnosticsInDocTableView
from Events.EventFeedPage import CFastEventFeedPage
from Events.EventMesPage import CFastEventMesPage
from Events.EventNotesPage import CFastEventNotesPage
from Events.TempInvalid import CTempInvalid
from Orgs.OrgComboBox import CContractComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
from library.TextBrowser import CTextBrowser
from library.crbcombobox import CRBComboBox
