# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TissueJournalDialog.ui'
#
# Created: Fri May 16 13:15:25 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TissueJournalDialog(object):
    def setupUi(self, TissueJournalDialog):
        TissueJournalDialog.setObjectName(_fromUtf8("TissueJournalDialog"))
        TissueJournalDialog.resize(857, 1002)
        self.gridLayout_6 = QtGui.QGridLayout(TissueJournalDialog)
        self.gridLayout_6.setMargin(4)
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.mainTabWidget = QtGui.QTabWidget(TissueJournalDialog)
        self.mainTabWidget.setObjectName(_fromUtf8("mainTabWidget"))
        self.tabTissue = QtGui.QWidget()
        self.tabTissue.setObjectName(_fromUtf8("tabTissue"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabTissue)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.txtClientInfoBrowser = CTextBrowser(self.tabTissue)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.gridLayout_2.addWidget(self.txtClientInfoBrowser, 0, 0, 1, 3)
        self.splitter_3 = QtGui.QSplitter(self.tabTissue)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setChildrenCollapsible(False)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.pnlFilter = QtGui.QWidget(self.splitter_3)
        self.pnlFilter.setObjectName(_fromUtf8("pnlFilter"))
        self.verticalLayout = QtGui.QVBoxLayout(self.pnlFilter)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pnlSmartFilter = QtGui.QWidget(self.pnlFilter)
        self.pnlSmartFilter.setObjectName(_fromUtf8("pnlSmartFilter"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.pnlSmartFilter)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.pnlSmartFilter)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.treeOrgStructure = QtGui.QTreeView(self.splitter)
        self.treeOrgStructure.setObjectName(_fromUtf8("treeOrgStructure"))
        self.tabWidgetFilter = QtGui.QTabWidget(self.splitter)
        self.tabWidgetFilter.setObjectName(_fromUtf8("tabWidgetFilter"))
        self.tabCalendar = QtGui.QWidget()
        self.tabCalendar.setObjectName(_fromUtf8("tabCalendar"))
        self.gridLayout = QtGui.QGridLayout(self.tabCalendar)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.calendar = CCalendarWidget(self.tabCalendar)
        self.calendar.setObjectName(_fromUtf8("calendar"))
        self.gridLayout.addWidget(self.calendar, 0, 1, 1, 1)
        self.btnCalendar = QtGui.QRadioButton(self.tabCalendar)
        self.btnCalendar.setText(_fromUtf8(""))
        self.btnCalendar.setChecked(True)
        self.btnCalendar.setObjectName(_fromUtf8("btnCalendar"))
        self.gridLayout.addWidget(self.btnCalendar, 0, 0, 1, 1)
        self.btnDateRange = QtGui.QRadioButton(self.tabCalendar)
        self.btnDateRange.setText(_fromUtf8(""))
        self.btnDateRange.setObjectName(_fromUtf8("btnDateRange"))
        self.gridLayout.addWidget(self.btnDateRange, 1, 0, 1, 1)
        self.pnDateRange = QtGui.QWidget(self.tabCalendar)
        self.pnDateRange.setEnabled(False)
        self.pnDateRange.setObjectName(_fromUtf8("pnDateRange"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.pnDateRange)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lblDateFrom = QtGui.QLabel(self.pnDateRange)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDateFrom.sizePolicy().hasHeightForWidth())
        self.lblDateFrom.setSizePolicy(sizePolicy)
        self.lblDateFrom.setObjectName(_fromUtf8("lblDateFrom"))
        self.horizontalLayout_6.addWidget(self.lblDateFrom)
        self.edtDateFrom = CDateEdit(self.pnDateRange)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDateFrom.sizePolicy().hasHeightForWidth())
        self.edtDateFrom.setSizePolicy(sizePolicy)
        self.edtDateFrom.setCalendarPopup(True)
        self.edtDateFrom.setObjectName(_fromUtf8("edtDateFrom"))
        self.horizontalLayout_6.addWidget(self.edtDateFrom)
        self.lblDateTo = QtGui.QLabel(self.pnDateRange)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDateTo.sizePolicy().hasHeightForWidth())
        self.lblDateTo.setSizePolicy(sizePolicy)
        self.lblDateTo.setObjectName(_fromUtf8("lblDateTo"))
        self.horizontalLayout_6.addWidget(self.lblDateTo)
        self.edtDateTo = CDateEdit(self.pnDateRange)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDateTo.sizePolicy().hasHeightForWidth())
        self.edtDateTo.setSizePolicy(sizePolicy)
        self.edtDateTo.setCalendarPopup(True)
        self.edtDateTo.setObjectName(_fromUtf8("edtDateTo"))
        self.horizontalLayout_6.addWidget(self.edtDateTo)
        self.gridLayout.addWidget(self.pnDateRange, 1, 1, 1, 1)
        self.tabWidgetFilter.addTab(self.tabCalendar, _fromUtf8(""))
        self.tabClient = QtGui.QWidget()
        self.tabClient.setObjectName(_fromUtf8("tabClient"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabClient)
        self.gridLayout_3.setMargin(2)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.chkFilterId = QtGui.QCheckBox(self.tabClient)
        self.chkFilterId.setObjectName(_fromUtf8("chkFilterId"))
        self.gridLayout_3.addWidget(self.chkFilterId, 0, 0, 1, 1)
        self.edtFilterId = QtGui.QLineEdit(self.tabClient)
        self.edtFilterId.setEnabled(False)
        self.edtFilterId.setInputMask(_fromUtf8(""))
        self.edtFilterId.setMaxLength(32767)
        self.edtFilterId.setObjectName(_fromUtf8("edtFilterId"))
        self.gridLayout_3.addWidget(self.edtFilterId, 1, 0, 1, 3)
        self.chkFilterLastName = QtGui.QCheckBox(self.tabClient)
        self.chkFilterLastName.setObjectName(_fromUtf8("chkFilterLastName"))
        self.gridLayout_3.addWidget(self.chkFilterLastName, 2, 0, 1, 1)
        self.chkFilterFirstName = QtGui.QCheckBox(self.tabClient)
        self.chkFilterFirstName.setObjectName(_fromUtf8("chkFilterFirstName"))
        self.gridLayout_3.addWidget(self.chkFilterFirstName, 4, 0, 1, 1)
        self.chkFilterPatrName = QtGui.QCheckBox(self.tabClient)
        self.chkFilterPatrName.setObjectName(_fromUtf8("chkFilterPatrName"))
        self.gridLayout_3.addWidget(self.chkFilterPatrName, 6, 0, 1, 1)
        self.chkFilterBirthDay = QtGui.QCheckBox(self.tabClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterBirthDay.sizePolicy().hasHeightForWidth())
        self.chkFilterBirthDay.setSizePolicy(sizePolicy)
        self.chkFilterBirthDay.setObjectName(_fromUtf8("chkFilterBirthDay"))
        self.gridLayout_3.addWidget(self.chkFilterBirthDay, 8, 0, 1, 1)
        self.edtFilterBirthDay = CDateEdit(self.tabClient)
        self.edtFilterBirthDay.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterBirthDay.sizePolicy().hasHeightForWidth())
        self.edtFilterBirthDay.setSizePolicy(sizePolicy)
        self.edtFilterBirthDay.setCalendarPopup(True)
        self.edtFilterBirthDay.setObjectName(_fromUtf8("edtFilterBirthDay"))
        self.gridLayout_3.addWidget(self.edtFilterBirthDay, 8, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 8, 2, 1, 1)
        self.cmbFilterAccountingSystem = CRBComboBox(self.tabClient)
        self.cmbFilterAccountingSystem.setEnabled(False)
        self.cmbFilterAccountingSystem.setObjectName(_fromUtf8("cmbFilterAccountingSystem"))
        self.gridLayout_3.addWidget(self.cmbFilterAccountingSystem, 0, 1, 1, 2)
        self.edtFilterLastName = QtGui.QLineEdit(self.tabClient)
        self.edtFilterLastName.setEnabled(False)
        self.edtFilterLastName.setObjectName(_fromUtf8("edtFilterLastName"))
        self.gridLayout_3.addWidget(self.edtFilterLastName, 2, 1, 1, 2)
        self.edtFilterFirstName = QtGui.QLineEdit(self.tabClient)
        self.edtFilterFirstName.setEnabled(False)
        self.edtFilterFirstName.setObjectName(_fromUtf8("edtFilterFirstName"))
        self.gridLayout_3.addWidget(self.edtFilterFirstName, 4, 1, 1, 2)
        self.edtFilterPatrName = QtGui.QLineEdit(self.tabClient)
        self.edtFilterPatrName.setEnabled(False)
        self.edtFilterPatrName.setObjectName(_fromUtf8("edtFilterPatrName"))
        self.gridLayout_3.addWidget(self.edtFilterPatrName, 6, 1, 1, 2)
        self.tabWidgetFilter.addTab(self.tabClient, _fromUtf8(""))
        self.tblTissueTypes = CTableView(self.splitter)
        self.tblTissueTypes.setObjectName(_fromUtf8("tblTissueTypes"))
        self.horizontalLayout.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.pnlSmartFilter)
        self.grpStaticFilter = QtGui.QGroupBox(self.pnlFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpStaticFilter.sizePolicy().hasHeightForWidth())
        self.grpStaticFilter.setSizePolicy(sizePolicy)
        self.grpStaticFilter.setObjectName(_fromUtf8("grpStaticFilter"))
        self.gridLayout_5 = QtGui.QGridLayout(self.grpStaticFilter)
        self.gridLayout_5.setMargin(2)
        self.gridLayout_5.setSpacing(2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.chkTissueType = QtGui.QCheckBox(self.grpStaticFilter)
        self.chkTissueType.setObjectName(_fromUtf8("chkTissueType"))
        self.gridLayout_5.addWidget(self.chkTissueType, 1, 0, 1, 3)
        self.chkUrgent = QtGui.QCheckBox(self.grpStaticFilter)
        self.chkUrgent.setObjectName(_fromUtf8("chkUrgent"))
        self.gridLayout_5.addWidget(self.chkUrgent, 3, 0, 1, 1)
        self.chkStatus = QtGui.QCheckBox(self.grpStaticFilter)
        self.chkStatus.setObjectName(_fromUtf8("chkStatus"))
        self.gridLayout_5.addWidget(self.chkStatus, 5, 0, 1, 1)
        self.cmbStatus = QtGui.QComboBox(self.grpStaticFilter)
        self.cmbStatus.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbStatus.sizePolicy().hasHeightForWidth())
        self.cmbStatus.setSizePolicy(sizePolicy)
        self.cmbStatus.setObjectName(_fromUtf8("cmbStatus"))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cmbStatus, 5, 1, 1, 2)
        self.lblEventType = QtGui.QLabel(self.grpStaticFilter)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridLayout_5.addWidget(self.lblEventType, 7, 0, 1, 1)
        self.cmbEventType = CRBComboBox(self.grpStaticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEventType.sizePolicy().hasHeightForWidth())
        self.cmbEventType.setSizePolicy(sizePolicy)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout_5.addWidget(self.cmbEventType, 7, 1, 1, 2)
        self.lblService = QtGui.QLabel(self.grpStaticFilter)
        self.lblService.setObjectName(_fromUtf8("lblService"))
        self.gridLayout_5.addWidget(self.lblService, 8, 0, 1, 1)
        self.cmbService = CRBServiceComboBox(self.grpStaticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbService.sizePolicy().hasHeightForWidth())
        self.cmbService.setSizePolicy(sizePolicy)
        self.cmbService.setObjectName(_fromUtf8("cmbService"))
        self.gridLayout_5.addWidget(self.cmbService, 8, 1, 1, 2)
        self.lblActionType = QtGui.QLabel(self.grpStaticFilter)
        self.lblActionType.setObjectName(_fromUtf8("lblActionType"))
        self.gridLayout_5.addWidget(self.lblActionType, 9, 0, 1, 1)
        self.cmbActionType = CActionTypeComboBox(self.grpStaticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbActionType.sizePolicy().hasHeightForWidth())
        self.cmbActionType.setSizePolicy(sizePolicy)
        self.cmbActionType.setObjectName(_fromUtf8("cmbActionType"))
        self.gridLayout_5.addWidget(self.cmbActionType, 9, 1, 1, 2)
        self.lblFinanceType = QtGui.QLabel(self.grpStaticFilter)
        self.lblFinanceType.setObjectName(_fromUtf8("lblFinanceType"))
        self.gridLayout_5.addWidget(self.lblFinanceType, 10, 0, 1, 1)
        self.cmbFinanceType = CRBComboBox(self.grpStaticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFinanceType.sizePolicy().hasHeightForWidth())
        self.cmbFinanceType.setSizePolicy(sizePolicy)
        self.cmbFinanceType.setObjectName(_fromUtf8("cmbFinanceType"))
        self.gridLayout_5.addWidget(self.cmbFinanceType, 10, 1, 1, 2)
        self.lblExecOrgStructure = QtGui.QLabel(self.grpStaticFilter)
        self.lblExecOrgStructure.setObjectName(_fromUtf8("lblExecOrgStructure"))
        self.gridLayout_5.addWidget(self.lblExecOrgStructure, 11, 0, 1, 1)
        self.cmbExecOrgStructure = COrgStructureComboBox(self.grpStaticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbExecOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbExecOrgStructure.setSizePolicy(sizePolicy)
        self.cmbExecOrgStructure.setObjectName(_fromUtf8("cmbExecOrgStructure"))
        self.gridLayout_5.addWidget(self.cmbExecOrgStructure, 11, 1, 1, 2)
        self.lblExecPerson = QtGui.QLabel(self.grpStaticFilter)
        self.lblExecPerson.setObjectName(_fromUtf8("lblExecPerson"))
        self.gridLayout_5.addWidget(self.lblExecPerson, 12, 0, 1, 1)
        self.cmbExecPerson = CPersonComboBoxEx(self.grpStaticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbExecPerson.sizePolicy().hasHeightForWidth())
        self.cmbExecPerson.setSizePolicy(sizePolicy)
        self.cmbExecPerson.setObjectName(_fromUtf8("cmbExecPerson"))
        self.gridLayout_5.addWidget(self.cmbExecPerson, 12, 1, 1, 2)
        self.lblExecOrg = QtGui.QLabel(self.grpStaticFilter)
        self.lblExecOrg.setObjectName(_fromUtf8("lblExecOrg"))
        self.gridLayout_5.addWidget(self.lblExecOrg, 13, 0, 1, 1)
        self.cmbExecOrg = CPolyclinicComboBox(self.grpStaticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbExecOrg.sizePolicy().hasHeightForWidth())
        self.cmbExecOrg.setSizePolicy(sizePolicy)
        self.cmbExecOrg.setObjectName(_fromUtf8("cmbExecOrg"))
        self.gridLayout_5.addWidget(self.cmbExecOrg, 13, 1, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.buttonBoxFilter = CApplyResetDialogButtonBox(self.grpStaticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBoxFilter.sizePolicy().hasHeightForWidth())
        self.buttonBoxFilter.setSizePolicy(sizePolicy)
        self.buttonBoxFilter.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxFilter.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBoxFilter.setCenterButtons(True)
        self.buttonBoxFilter.setObjectName(_fromUtf8("buttonBoxFilter"))
        self.horizontalLayout_4.addWidget(self.buttonBoxFilter)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 15, 0, 4, 3)
        self.chkClientSex = QtGui.QCheckBox(self.grpStaticFilter)
        self.chkClientSex.setObjectName(_fromUtf8("chkClientSex"))
        self.gridLayout_5.addWidget(self.chkClientSex, 3, 1, 1, 1)
        self.cmbClientSex = QtGui.QComboBox(self.grpStaticFilter)
        self.cmbClientSex.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbClientSex.sizePolicy().hasHeightForWidth())
        self.cmbClientSex.setSizePolicy(sizePolicy)
        self.cmbClientSex.setObjectName(_fromUtf8("cmbClientSex"))
        self.cmbClientSex.addItem(_fromUtf8(""))
        self.cmbClientSex.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cmbClientSex, 3, 2, 1, 1)
        self.chkRelegateOrg = QtGui.QCheckBox(self.grpStaticFilter)
        self.chkRelegateOrg.setObjectName(_fromUtf8("chkRelegateOrg"))
        self.gridLayout_5.addWidget(self.chkRelegateOrg, 4, 0, 1, 1)
        self.cmbRelegateOrg = COrgComboBox(self.grpStaticFilter)
        self.cmbRelegateOrg.setEnabled(False)
        self.cmbRelegateOrg.setObjectName(_fromUtf8("cmbRelegateOrg"))
        self.gridLayout_5.addWidget(self.cmbRelegateOrg, 4, 1, 1, 2)
        self.chkPreliminaryResult = QtGui.QCheckBox(self.grpStaticFilter)
        self.chkPreliminaryResult.setObjectName(_fromUtf8("chkPreliminaryResult"))
        self.gridLayout_5.addWidget(self.chkPreliminaryResult, 6, 0, 1, 1)
        self.cmbPreliminaryResult = QtGui.QComboBox(self.grpStaticFilter)
        self.cmbPreliminaryResult.setEnabled(False)
        self.cmbPreliminaryResult.setObjectName(_fromUtf8("cmbPreliminaryResult"))
        self.cmbPreliminaryResult.addItem(_fromUtf8(""))
        self.cmbPreliminaryResult.addItem(_fromUtf8(""))
        self.cmbPreliminaryResult.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cmbPreliminaryResult, 6, 1, 1, 2)
        self.chkWithoutSampling = QtGui.QCheckBox(self.grpStaticFilter)
        self.chkWithoutSampling.setObjectName(_fromUtf8("chkWithoutSampling"))
        self.gridLayout_5.addWidget(self.chkWithoutSampling, 2, 0, 1, 3)
        self.pnlIBM = QtGui.QWidget(self.grpStaticFilter)
        self.pnlIBM.setObjectName(_fromUtf8("pnlIBM"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.pnlIBM)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.chkIBM = QtGui.QCheckBox(self.pnlIBM)
        self.chkIBM.setObjectName(_fromUtf8("chkIBM"))
        self.horizontalLayout_5.addWidget(self.chkIBM)
        self.edtIBM = QtGui.QLineEdit(self.pnlIBM)
        self.edtIBM.setEnabled(False)
        self.edtIBM.setObjectName(_fromUtf8("edtIBM"))
        self.horizontalLayout_5.addWidget(self.edtIBM)
        self.gridLayout_5.addWidget(self.pnlIBM, 0, 0, 1, 3)
        self.verticalLayout.addWidget(self.grpStaticFilter)
        self.pnlTissueJotnalAndActions = QtGui.QWidget(self.splitter_3)
        self.pnlTissueJotnalAndActions.setObjectName(_fromUtf8("pnlTissueJotnalAndActions"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.pnlTissueJotnalAndActions)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.splitter_2 = QtGui.QSplitter(self.pnlTissueJotnalAndActions)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.pnlTissueJournal = QtGui.QWidget(self.splitter_2)
        self.pnlTissueJournal.setObjectName(_fromUtf8("pnlTissueJournal"))
        self.gridLayout_4 = QtGui.QGridLayout(self.pnlTissueJournal)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tblTissueJournal = CTableView(self.pnlTissueJournal)
        self.tblTissueJournal.setObjectName(_fromUtf8("tblTissueJournal"))
        self.gridLayout_4.addWidget(self.tblTissueJournal, 0, 0, 1, 5)
        self.lblTissueJournalCount = QtGui.QLabel(self.pnlTissueJournal)
        self.lblTissueJournalCount.setObjectName(_fromUtf8("lblTissueJournalCount"))
        self.gridLayout_4.addWidget(self.lblTissueJournalCount, 1, 0, 1, 2)
        self.lblAllActionsCount = QtGui.QLabel(self.pnlTissueJournal)
        self.lblAllActionsCount.setObjectName(_fromUtf8("lblAllActionsCount"))
        self.gridLayout_4.addWidget(self.lblAllActionsCount, 1, 4, 1, 1)
        self.lblClientCount = QtGui.QLabel(self.pnlTissueJournal)
        self.lblClientCount.setObjectName(_fromUtf8("lblClientCount"))
        self.gridLayout_4.addWidget(self.lblClientCount, 1, 2, 1, 2)
        self.pnlActions = QtGui.QWidget(self.splitter_2)
        self.pnlActions.setObjectName(_fromUtf8("pnlActions"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pnlActions)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tblTissueJournalActions = CTableView(self.pnlActions)
        self.tblTissueJournalActions.setObjectName(_fromUtf8("tblTissueJournalActions"))
        self.verticalLayout_3.addWidget(self.tblTissueJournalActions)
        self.lblActionsCount = QtGui.QLabel(self.pnlActions)
        self.lblActionsCount.setObjectName(_fromUtf8("lblActionsCount"))
        self.verticalLayout_3.addWidget(self.lblActionsCount)
        self.horizontalLayout_2.addWidget(self.splitter_2)
        self.gridLayout_2.addWidget(self.splitter_3, 1, 0, 1, 3)
        self.mainTabWidget.addTab(self.tabTissue, _fromUtf8(""))
        self.tabProbeWorkList = CProbeWorkListPage()
        self.tabProbeWorkList.setObjectName(_fromUtf8("tabProbeWorkList"))
        self.mainTabWidget.addTab(self.tabProbeWorkList, _fromUtf8(""))
        self.tabResult = QtGui.QWidget()
        self.tabResult.setObjectName(_fromUtf8("tabResult"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tabResult)
        self.gridLayout_13.setMargin(4)
        self.gridLayout_13.setSpacing(4)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.splitter_6 = QtGui.QSplitter(self.tabResult)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setChildrenCollapsible(False)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.pnlResultFilter = QtGui.QWidget(self.splitter_6)
        self.pnlResultFilter.setObjectName(_fromUtf8("pnlResultFilter"))
        self.gridLayout_12 = QtGui.QGridLayout(self.pnlResultFilter)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.splitter_5 = QtGui.QSplitter(self.pnlResultFilter)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setChildrenCollapsible(False)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.pnlResultTissueTypePeriodEventType = QtGui.QWidget(self.splitter_5)
        self.pnlResultTissueTypePeriodEventType.setObjectName(_fromUtf8("pnlResultTissueTypePeriodEventType"))
        self.gridLayout_10 = QtGui.QGridLayout(self.pnlResultTissueTypePeriodEventType)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setSpacing(2)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.tblResultTissueType = CTableView(self.pnlResultTissueTypePeriodEventType)
        self.tblResultTissueType.setObjectName(_fromUtf8("tblResultTissueType"))
        self.gridLayout_10.addWidget(self.tblResultTissueType, 0, 0, 1, 4)
        self.chkResultEventType = QtGui.QCheckBox(self.pnlResultTissueTypePeriodEventType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkResultEventType.sizePolicy().hasHeightForWidth())
        self.chkResultEventType.setSizePolicy(sizePolicy)
        self.chkResultEventType.setObjectName(_fromUtf8("chkResultEventType"))
        self.gridLayout_10.addWidget(self.chkResultEventType, 4, 0, 1, 1)
        self.pnlResultPeriod = QtGui.QWidget(self.pnlResultTissueTypePeriodEventType)
        self.pnlResultPeriod.setObjectName(_fromUtf8("pnlResultPeriod"))
        self.gridLayout_14 = QtGui.QGridLayout(self.pnlResultPeriod)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setSpacing(2)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.lblResultFrom = QtGui.QLabel(self.pnlResultPeriod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblResultFrom.sizePolicy().hasHeightForWidth())
        self.lblResultFrom.setSizePolicy(sizePolicy)
        self.lblResultFrom.setObjectName(_fromUtf8("lblResultFrom"))
        self.gridLayout_14.addWidget(self.lblResultFrom, 0, 0, 1, 1)
        self.edtResultDateFrom = CDateEdit(self.pnlResultPeriod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtResultDateFrom.sizePolicy().hasHeightForWidth())
        self.edtResultDateFrom.setSizePolicy(sizePolicy)
        self.edtResultDateFrom.setCalendarPopup(True)
        self.edtResultDateFrom.setObjectName(_fromUtf8("edtResultDateFrom"))
        self.gridLayout_14.addWidget(self.edtResultDateFrom, 0, 2, 1, 1)
        self.lblResultTo = QtGui.QLabel(self.pnlResultPeriod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblResultTo.sizePolicy().hasHeightForWidth())
        self.lblResultTo.setSizePolicy(sizePolicy)
        self.lblResultTo.setObjectName(_fromUtf8("lblResultTo"))
        self.gridLayout_14.addWidget(self.lblResultTo, 0, 3, 1, 1)
        self.edtResultDateTo = CDateEdit(self.pnlResultPeriod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtResultDateTo.sizePolicy().hasHeightForWidth())
        self.edtResultDateTo.setSizePolicy(sizePolicy)
        self.edtResultDateTo.setCalendarPopup(True)
        self.edtResultDateTo.setObjectName(_fromUtf8("edtResultDateTo"))
        self.gridLayout_14.addWidget(self.edtResultDateTo, 0, 4, 1, 1)
        self.lblResultTissueIdentifierFrom = QtGui.QLabel(self.pnlResultPeriod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblResultTissueIdentifierFrom.sizePolicy().hasHeightForWidth())
        self.lblResultTissueIdentifierFrom.setSizePolicy(sizePolicy)
        self.lblResultTissueIdentifierFrom.setObjectName(_fromUtf8("lblResultTissueIdentifierFrom"))
        self.gridLayout_14.addWidget(self.lblResultTissueIdentifierFrom, 1, 0, 1, 2)
        self.edtResultTissueIdentifierFrom = QtGui.QLineEdit(self.pnlResultPeriod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtResultTissueIdentifierFrom.sizePolicy().hasHeightForWidth())
        self.edtResultTissueIdentifierFrom.setSizePolicy(sizePolicy)
        self.edtResultTissueIdentifierFrom.setObjectName(_fromUtf8("edtResultTissueIdentifierFrom"))
        self.gridLayout_14.addWidget(self.edtResultTissueIdentifierFrom, 1, 2, 1, 1)
        self.lblResultTissueIdentifierTo = QtGui.QLabel(self.pnlResultPeriod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblResultTissueIdentifierTo.sizePolicy().hasHeightForWidth())
        self.lblResultTissueIdentifierTo.setSizePolicy(sizePolicy)
        self.lblResultTissueIdentifierTo.setObjectName(_fromUtf8("lblResultTissueIdentifierTo"))
        self.gridLayout_14.addWidget(self.lblResultTissueIdentifierTo, 1, 3, 1, 1)
        self.edtResultTissueIdentifierTo = QtGui.QLineEdit(self.pnlResultPeriod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtResultTissueIdentifierTo.sizePolicy().hasHeightForWidth())
        self.edtResultTissueIdentifierTo.setSizePolicy(sizePolicy)
        self.edtResultTissueIdentifierTo.setObjectName(_fromUtf8("edtResultTissueIdentifierTo"))
        self.gridLayout_14.addWidget(self.edtResultTissueIdentifierTo, 1, 4, 1, 1)
        self.gridLayout_10.addWidget(self.pnlResultPeriod, 2, 0, 1, 4)
        self.cmbResultEventType = CRBComboBox(self.pnlResultTissueTypePeriodEventType)
        self.cmbResultEventType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbResultEventType.sizePolicy().hasHeightForWidth())
        self.cmbResultEventType.setSizePolicy(sizePolicy)
        self.cmbResultEventType.setObjectName(_fromUtf8("cmbResultEventType"))
        self.gridLayout_10.addWidget(self.cmbResultEventType, 4, 1, 1, 3)
        self.chkResultTissueRegistrator = QtGui.QCheckBox(self.pnlResultTissueTypePeriodEventType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkResultTissueRegistrator.sizePolicy().hasHeightForWidth())
        self.chkResultTissueRegistrator.setSizePolicy(sizePolicy)
        self.chkResultTissueRegistrator.setObjectName(_fromUtf8("chkResultTissueRegistrator"))
        self.gridLayout_10.addWidget(self.chkResultTissueRegistrator, 3, 0, 1, 1)
        self.cmbResultTissueRegistrator = CPersonComboBoxEx(self.pnlResultTissueTypePeriodEventType)
        self.cmbResultTissueRegistrator.setEnabled(False)
        self.cmbResultTissueRegistrator.setObjectName(_fromUtf8("cmbResultTissueRegistrator"))
        self.gridLayout_10.addWidget(self.cmbResultTissueRegistrator, 3, 1, 1, 3)
        self.lblResultService = QtGui.QLabel(self.pnlResultTissueTypePeriodEventType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblResultService.sizePolicy().hasHeightForWidth())
        self.lblResultService.setSizePolicy(sizePolicy)
        self.lblResultService.setObjectName(_fromUtf8("lblResultService"))
        self.gridLayout_10.addWidget(self.lblResultService, 5, 0, 1, 1)
        self.cmbResultService = CRBServiceComboBox(self.pnlResultTissueTypePeriodEventType)
        self.cmbResultService.setObjectName(_fromUtf8("cmbResultService"))
        self.gridLayout_10.addWidget(self.cmbResultService, 5, 1, 1, 3)
        self.chkResultRelegateOrg = QtGui.QCheckBox(self.pnlResultTissueTypePeriodEventType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkResultRelegateOrg.sizePolicy().hasHeightForWidth())
        self.chkResultRelegateOrg.setSizePolicy(sizePolicy)
        self.chkResultRelegateOrg.setObjectName(_fromUtf8("chkResultRelegateOrg"))
        self.gridLayout_10.addWidget(self.chkResultRelegateOrg, 1, 0, 1, 1)
        self.cmbResultRelegateOrg = COrgComboBox(self.pnlResultTissueTypePeriodEventType)
        self.cmbResultRelegateOrg.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbResultRelegateOrg.sizePolicy().hasHeightForWidth())
        self.cmbResultRelegateOrg.setSizePolicy(sizePolicy)
        self.cmbResultRelegateOrg.setObjectName(_fromUtf8("cmbResultRelegateOrg"))
        self.gridLayout_10.addWidget(self.cmbResultRelegateOrg, 1, 1, 1, 3)
        self.tblResultActionType = CActionTypePopupView(self.splitter_5)
        self.tblResultActionType.setObjectName(_fromUtf8("tblResultActionType"))
        self.grpResultActionsFilter = QtGui.QGroupBox(self.splitter_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpResultActionsFilter.sizePolicy().hasHeightForWidth())
        self.grpResultActionsFilter.setSizePolicy(sizePolicy)
        self.grpResultActionsFilter.setObjectName(_fromUtf8("grpResultActionsFilter"))
        self.gridLayout_11 = QtGui.QGridLayout(self.grpResultActionsFilter)
        self.gridLayout_11.setMargin(4)
        self.gridLayout_11.setSpacing(4)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.tblResultTests = CTableView(self.grpResultActionsFilter)
        self.tblResultTests.setObjectName(_fromUtf8("tblResultTests"))
        self.gridLayout_11.addWidget(self.tblResultTests, 1, 0, 1, 3)
        self.tabWidgetResultActionsFilter = QtGui.QTabWidget(self.grpResultActionsFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetResultActionsFilter.sizePolicy().hasHeightForWidth())
        self.tabWidgetResultActionsFilter.setSizePolicy(sizePolicy)
        self.tabWidgetResultActionsFilter.setObjectName(_fromUtf8("tabWidgetResultActionsFilter"))
        self.tabResultActionsFilterMain = QtGui.QWidget()
        self.tabResultActionsFilterMain.setObjectName(_fromUtf8("tabResultActionsFilterMain"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tabResultActionsFilterMain)
        self.gridLayout_15.setMargin(0)
        self.gridLayout_15.setSpacing(2)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.chkResultUrgent = QtGui.QCheckBox(self.tabResultActionsFilterMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkResultUrgent.sizePolicy().hasHeightForWidth())
        self.chkResultUrgent.setSizePolicy(sizePolicy)
        self.chkResultUrgent.setObjectName(_fromUtf8("chkResultUrgent"))
        self.gridLayout_15.addWidget(self.chkResultUrgent, 0, 0, 1, 1)
        self.pnlResultSamplingNumber = QtGui.QWidget(self.tabResultActionsFilterMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pnlResultSamplingNumber.sizePolicy().hasHeightForWidth())
        self.pnlResultSamplingNumber.setSizePolicy(sizePolicy)
        self.pnlResultSamplingNumber.setObjectName(_fromUtf8("pnlResultSamplingNumber"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.pnlResultSamplingNumber)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblResultSamplingNumberFrom = QtGui.QLabel(self.pnlResultSamplingNumber)
        self.lblResultSamplingNumberFrom.setObjectName(_fromUtf8("lblResultSamplingNumberFrom"))
        self.horizontalLayout_3.addWidget(self.lblResultSamplingNumberFrom)
        self.edtResultSamplingNumberFrom = QtGui.QSpinBox(self.pnlResultSamplingNumber)
        self.edtResultSamplingNumberFrom.setObjectName(_fromUtf8("edtResultSamplingNumberFrom"))
        self.horizontalLayout_3.addWidget(self.edtResultSamplingNumberFrom)
        self.lblResultSamplingNumberTo = QtGui.QLabel(self.pnlResultSamplingNumber)
        self.lblResultSamplingNumberTo.setObjectName(_fromUtf8("lblResultSamplingNumberTo"))
        self.horizontalLayout_3.addWidget(self.lblResultSamplingNumberTo)
        self.edtResultSamplingNumberTo = QtGui.QSpinBox(self.pnlResultSamplingNumber)
        self.edtResultSamplingNumberTo.setObjectName(_fromUtf8("edtResultSamplingNumberTo"))
        self.horizontalLayout_3.addWidget(self.edtResultSamplingNumberTo)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_15.addWidget(self.pnlResultSamplingNumber, 0, 1, 1, 2)
        self.chkResultStatus = QtGui.QCheckBox(self.tabResultActionsFilterMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkResultStatus.sizePolicy().hasHeightForWidth())
        self.chkResultStatus.setSizePolicy(sizePolicy)
        self.chkResultStatus.setObjectName(_fromUtf8("chkResultStatus"))
        self.gridLayout_15.addWidget(self.chkResultStatus, 2, 0, 1, 1)
        self.cmbResultStatus = QtGui.QComboBox(self.tabResultActionsFilterMain)
        self.cmbResultStatus.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbResultStatus.sizePolicy().hasHeightForWidth())
        self.cmbResultStatus.setSizePolicy(sizePolicy)
        self.cmbResultStatus.setObjectName(_fromUtf8("cmbResultStatus"))
        self.cmbResultStatus.addItem(_fromUtf8(""))
        self.cmbResultStatus.addItem(_fromUtf8(""))
        self.cmbResultStatus.addItem(_fromUtf8(""))
        self.cmbResultStatus.addItem(_fromUtf8(""))
        self.cmbResultStatus.addItem(_fromUtf8(""))
        self.cmbResultStatus.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.cmbResultStatus, 2, 1, 1, 2)
        self.chkResultFinance = QtGui.QCheckBox(self.tabResultActionsFilterMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkResultFinance.sizePolicy().hasHeightForWidth())
        self.chkResultFinance.setSizePolicy(sizePolicy)
        self.chkResultFinance.setObjectName(_fromUtf8("chkResultFinance"))
        self.gridLayout_15.addWidget(self.chkResultFinance, 4, 0, 1, 1)
        self.cmbResultFinanceType = CRBComboBox(self.tabResultActionsFilterMain)
        self.cmbResultFinanceType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbResultFinanceType.sizePolicy().hasHeightForWidth())
        self.cmbResultFinanceType.setSizePolicy(sizePolicy)
        self.cmbResultFinanceType.setObjectName(_fromUtf8("cmbResultFinanceType"))
        self.gridLayout_15.addWidget(self.cmbResultFinanceType, 4, 1, 1, 2)
        self.chkResultOnlyTests = QtGui.QCheckBox(self.tabResultActionsFilterMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkResultOnlyTests.sizePolicy().hasHeightForWidth())
        self.chkResultOnlyTests.setSizePolicy(sizePolicy)
        self.chkResultOnlyTests.setObjectName(_fromUtf8("chkResultOnlyTests"))
        self.gridLayout_15.addWidget(self.chkResultOnlyTests, 6, 0, 1, 1)
        self.chkResultClientSex = QtGui.QCheckBox(self.tabResultActionsFilterMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkResultClientSex.sizePolicy().hasHeightForWidth())
        self.chkResultClientSex.setSizePolicy(sizePolicy)
        self.chkResultClientSex.setObjectName(_fromUtf8("chkResultClientSex"))
        self.gridLayout_15.addWidget(self.chkResultClientSex, 1, 0, 1, 1)
        self.cmbResultClientSex = QtGui.QComboBox(self.tabResultActionsFilterMain)
        self.cmbResultClientSex.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbResultClientSex.sizePolicy().hasHeightForWidth())
        self.cmbResultClientSex.setSizePolicy(sizePolicy)
        self.cmbResultClientSex.setObjectName(_fromUtf8("cmbResultClientSex"))
        self.cmbResultClientSex.addItem(_fromUtf8(""))
        self.cmbResultClientSex.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.cmbResultClientSex, 1, 1, 1, 1)
        self.lblResultExecOrg = QtGui.QLabel(self.tabResultActionsFilterMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblResultExecOrg.sizePolicy().hasHeightForWidth())
        self.lblResultExecOrg.setSizePolicy(sizePolicy)
        self.lblResultExecOrg.setObjectName(_fromUtf8("lblResultExecOrg"))
        self.gridLayout_15.addWidget(self.lblResultExecOrg, 7, 0, 1, 1)
        self.cmbResultExecOrg = COrgComboBox(self.tabResultActionsFilterMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbResultExecOrg.sizePolicy().hasHeightForWidth())
        self.cmbResultExecOrg.setSizePolicy(sizePolicy)
        self.cmbResultExecOrg.setObjectName(_fromUtf8("cmbResultExecOrg"))
        self.gridLayout_15.addWidget(self.cmbResultExecOrg, 7, 1, 1, 2)
        self.chkResultPreliminaryResult = QtGui.QCheckBox(self.tabResultActionsFilterMain)
        self.chkResultPreliminaryResult.setObjectName(_fromUtf8("chkResultPreliminaryResult"))
        self.gridLayout_15.addWidget(self.chkResultPreliminaryResult, 3, 0, 1, 1)
        self.cmbResultPreliminaryResult = QtGui.QComboBox(self.tabResultActionsFilterMain)
        self.cmbResultPreliminaryResult.setEnabled(False)
        self.cmbResultPreliminaryResult.setObjectName(_fromUtf8("cmbResultPreliminaryResult"))
        self.cmbResultPreliminaryResult.addItem(_fromUtf8(""))
        self.cmbResultPreliminaryResult.addItem(_fromUtf8(""))
        self.cmbResultPreliminaryResult.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.cmbResultPreliminaryResult, 3, 1, 1, 2)
        self.chkResultWithoutSampling = QtGui.QCheckBox(self.tabResultActionsFilterMain)
        self.chkResultWithoutSampling.setObjectName(_fromUtf8("chkResultWithoutSampling"))
        self.gridLayout_15.addWidget(self.chkResultWithoutSampling, 6, 1, 1, 2)
        self.tabWidgetResultActionsFilter.addTab(self.tabResultActionsFilterMain, _fromUtf8(""))
        self.tabResultActionsFilterExtension = QtGui.QWidget()
        self.tabResultActionsFilterExtension.setObjectName(_fromUtf8("tabResultActionsFilterExtension"))
        self.gridLayout_16 = QtGui.QGridLayout(self.tabResultActionsFilterExtension)
        self.gridLayout_16.setMargin(0)
        self.gridLayout_16.setSpacing(2)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.chkResultActionSetPerson = QtGui.QCheckBox(self.tabResultActionsFilterExtension)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkResultActionSetPerson.sizePolicy().hasHeightForWidth())
        self.chkResultActionSetPerson.setSizePolicy(sizePolicy)
        self.chkResultActionSetPerson.setObjectName(_fromUtf8("chkResultActionSetPerson"))
        self.gridLayout_16.addWidget(self.chkResultActionSetPerson, 0, 0, 1, 1)
        self.cmbResultActionSetPersonOrgStructure = COrgStructureComboBox(self.tabResultActionsFilterExtension)
        self.cmbResultActionSetPersonOrgStructure.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbResultActionSetPersonOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbResultActionSetPersonOrgStructure.setSizePolicy(sizePolicy)
        self.cmbResultActionSetPersonOrgStructure.setObjectName(_fromUtf8("cmbResultActionSetPersonOrgStructure"))
        self.gridLayout_16.addWidget(self.cmbResultActionSetPersonOrgStructure, 0, 1, 1, 1)
        self.cmbResultActionSetPersonSpeciality = CRBComboBox(self.tabResultActionsFilterExtension)
        self.cmbResultActionSetPersonSpeciality.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbResultActionSetPersonSpeciality.sizePolicy().hasHeightForWidth())
        self.cmbResultActionSetPersonSpeciality.setSizePolicy(sizePolicy)
        self.cmbResultActionSetPersonSpeciality.setObjectName(_fromUtf8("cmbResultActionSetPersonSpeciality"))
        self.gridLayout_16.addWidget(self.cmbResultActionSetPersonSpeciality, 1, 0, 1, 1)
        self.cmbResultActionSetPerson = CPersonComboBoxEx(self.tabResultActionsFilterExtension)
        self.cmbResultActionSetPerson.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbResultActionSetPerson.sizePolicy().hasHeightForWidth())
        self.cmbResultActionSetPerson.setSizePolicy(sizePolicy)
        self.cmbResultActionSetPerson.setObjectName(_fromUtf8("cmbResultActionSetPerson"))
        self.gridLayout_16.addWidget(self.cmbResultActionSetPerson, 1, 1, 1, 1)
        self.chkResultActionExecPerson = QtGui.QCheckBox(self.tabResultActionsFilterExtension)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkResultActionExecPerson.sizePolicy().hasHeightForWidth())
        self.chkResultActionExecPerson.setSizePolicy(sizePolicy)
        self.chkResultActionExecPerson.setObjectName(_fromUtf8("chkResultActionExecPerson"))
        self.gridLayout_16.addWidget(self.chkResultActionExecPerson, 3, 0, 1, 1)
        self.line = QtGui.QFrame(self.tabResultActionsFilterExtension)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_16.addWidget(self.line, 2, 0, 1, 2)
        self.cmbResultActionExecPerson = CPersonComboBoxEx(self.tabResultActionsFilterExtension)
        self.cmbResultActionExecPerson.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbResultActionExecPerson.sizePolicy().hasHeightForWidth())
        self.cmbResultActionExecPerson.setSizePolicy(sizePolicy)
        self.cmbResultActionExecPerson.setObjectName(_fromUtf8("cmbResultActionExecPerson"))
        self.gridLayout_16.addWidget(self.cmbResultActionExecPerson, 3, 1, 1, 1)
        self.chkResultClientId = QtGui.QCheckBox(self.tabResultActionsFilterExtension)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkResultClientId.sizePolicy().hasHeightForWidth())
        self.chkResultClientId.setSizePolicy(sizePolicy)
        self.chkResultClientId.setObjectName(_fromUtf8("chkResultClientId"))
        self.gridLayout_16.addWidget(self.chkResultClientId, 6, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.tabResultActionsFilterExtension)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_16.addWidget(self.line_2, 5, 0, 1, 2)
        self.cmbResultClientIdAccountingSystem = CRBComboBox(self.tabResultActionsFilterExtension)
        self.cmbResultClientIdAccountingSystem.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbResultClientIdAccountingSystem.sizePolicy().hasHeightForWidth())
        self.cmbResultClientIdAccountingSystem.setSizePolicy(sizePolicy)
        self.cmbResultClientIdAccountingSystem.setObjectName(_fromUtf8("cmbResultClientIdAccountingSystem"))
        self.gridLayout_16.addWidget(self.cmbResultClientIdAccountingSystem, 6, 1, 1, 1)
        self.edtResultClientId = QtGui.QLineEdit(self.tabResultActionsFilterExtension)
        self.edtResultClientId.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtResultClientId.sizePolicy().hasHeightForWidth())
        self.edtResultClientId.setSizePolicy(sizePolicy)
        self.edtResultClientId.setObjectName(_fromUtf8("edtResultClientId"))
        self.gridLayout_16.addWidget(self.edtResultClientId, 7, 0, 1, 2)
        self.chkResultActionAssistant = QtGui.QCheckBox(self.tabResultActionsFilterExtension)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkResultActionAssistant.sizePolicy().hasHeightForWidth())
        self.chkResultActionAssistant.setSizePolicy(sizePolicy)
        self.chkResultActionAssistant.setObjectName(_fromUtf8("chkResultActionAssistant"))
        self.gridLayout_16.addWidget(self.chkResultActionAssistant, 4, 0, 1, 1)
        self.cmbResultActionAssistant = CPersonComboBoxEx(self.tabResultActionsFilterExtension)
        self.cmbResultActionAssistant.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbResultActionAssistant.sizePolicy().hasHeightForWidth())
        self.cmbResultActionAssistant.setSizePolicy(sizePolicy)
        self.cmbResultActionAssistant.setObjectName(_fromUtf8("cmbResultActionAssistant"))
        self.gridLayout_16.addWidget(self.cmbResultActionAssistant, 4, 1, 1, 1)
        self.tabWidgetResultActionsFilter.addTab(self.tabResultActionsFilterExtension, _fromUtf8(""))
        self.gridLayout_11.addWidget(self.tabWidgetResultActionsFilter, 0, 0, 1, 3)
        self.buttonBoxResult = CApplyResetDialogButtonBox(self.grpResultActionsFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBoxResult.sizePolicy().hasHeightForWidth())
        self.buttonBoxResult.setSizePolicy(sizePolicy)
        self.buttonBoxResult.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBoxResult.setObjectName(_fromUtf8("buttonBoxResult"))
        self.gridLayout_11.addWidget(self.buttonBoxResult, 2, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 2, 0, 1, 2)
        self.gridLayout_12.addWidget(self.splitter_5, 0, 0, 1, 1)
        self.splitter_4 = QtGui.QSplitter(self.splitter_6)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setChildrenCollapsible(False)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.pnlResultActions = QtGui.QWidget(self.splitter_4)
        self.pnlResultActions.setObjectName(_fromUtf8("pnlResultActions"))
        self.gridLayout_8 = QtGui.QGridLayout(self.pnlResultActions)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tblResultActions = CTableView(self.pnlResultActions)
        self.tblResultActions.setObjectName(_fromUtf8("tblResultActions"))
        self.gridLayout_8.addWidget(self.tblResultActions, 0, 0, 1, 1)
        self.lblResultActionsCount = QtGui.QLabel(self.pnlResultActions)
        self.lblResultActionsCount.setObjectName(_fromUtf8("lblResultActionsCount"))
        self.gridLayout_8.addWidget(self.lblResultActionsCount, 1, 0, 1, 1)
        self.pnlResultProperties = QtGui.QWidget(self.splitter_4)
        self.pnlResultProperties.setObjectName(_fromUtf8("pnlResultProperties"))
        self.gridLayout_9 = QtGui.QGridLayout(self.pnlResultProperties)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setSpacing(4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tblResultProperties = CTableView(self.pnlResultProperties)
        self.tblResultProperties.setObjectName(_fromUtf8("tblResultProperties"))
        self.gridLayout_9.addWidget(self.tblResultProperties, 0, 0, 1, 1)
        self.lblResultPropertiesCount = QtGui.QLabel(self.pnlResultProperties)
        self.lblResultPropertiesCount.setObjectName(_fromUtf8("lblResultPropertiesCount"))
        self.gridLayout_9.addWidget(self.lblResultPropertiesCount, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.splitter_6, 0, 0, 1, 1)
        self.mainTabWidget.addTab(self.tabResult, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.mainTabWidget, 0, 0, 1, 3)
        self.statusBar = QtGui.QStatusBar(TissueJournalDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.gridLayout_6.addWidget(self.statusBar, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(TissueJournalDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_6.addWidget(self.buttonBox, 1, 2, 1, 1)
        self.btnSend = QtGui.QPushButton(TissueJournalDialog)
        self.btnSend.setObjectName(_fromUtf8("btnSend"))
        self.gridLayout_6.addWidget(self.btnSend, 1, 1, 1, 1)

        self.retranslateUi(TissueJournalDialog)
        self.mainTabWidget.setCurrentIndex(0)
        self.tabWidgetFilter.setCurrentIndex(0)
        self.tabWidgetResultActionsFilter.setCurrentIndex(0)
        QtCore.QObject.connect(self.chkStatus, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbStatus.setEnabled)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TissueJournalDialog.reject)
        QtCore.QObject.connect(self.chkResultEventType, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbResultEventType.setEnabled)
        QtCore.QObject.connect(self.chkResultStatus, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbResultStatus.setEnabled)
        QtCore.QObject.connect(self.chkResultFinance, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbResultFinanceType.setEnabled)
        QtCore.QObject.connect(self.chkResultActionSetPerson, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbResultActionSetPersonOrgStructure.setEnabled)
        QtCore.QObject.connect(self.chkResultActionSetPerson, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbResultActionSetPerson.setEnabled)
        QtCore.QObject.connect(self.chkResultActionSetPerson, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbResultActionSetPersonSpeciality.setEnabled)
        QtCore.QObject.connect(self.chkResultActionExecPerson, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbResultActionExecPerson.setEnabled)
        QtCore.QObject.connect(self.chkResultClientId, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbResultClientIdAccountingSystem.setEnabled)
        QtCore.QObject.connect(self.chkResultClientId, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtResultClientId.setEnabled)
        QtCore.QObject.connect(self.chkResultTissueRegistrator, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbResultTissueRegistrator.setEnabled)
        QtCore.QObject.connect(self.chkResultActionAssistant, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbResultActionAssistant.setEnabled)
        QtCore.QObject.connect(self.chkClientSex, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbClientSex.setEnabled)
        QtCore.QObject.connect(self.chkResultClientSex, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbResultClientSex.setEnabled)
        QtCore.QObject.connect(self.chkRelegateOrg, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbRelegateOrg.setEnabled)
        QtCore.QObject.connect(self.chkResultRelegateOrg, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbResultRelegateOrg.setEnabled)
        QtCore.QObject.connect(self.chkPreliminaryResult, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbPreliminaryResult.setEnabled)
        QtCore.QObject.connect(self.chkResultPreliminaryResult, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbResultPreliminaryResult.setEnabled)
        QtCore.QObject.connect(self.btnCalendar, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.calendar.setEnabled)
        QtCore.QObject.connect(self.btnCalendar, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pnDateRange.setDisabled)
        QtCore.QObject.connect(self.btnDateRange, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pnDateRange.setEnabled)
        QtCore.QObject.connect(self.btnDateRange, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.calendar.setDisabled)
        QtCore.QObject.connect(self.chkIBM, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edtIBM.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(TissueJournalDialog)
        TissueJournalDialog.setTabOrder(self.mainTabWidget, self.txtClientInfoBrowser)
        TissueJournalDialog.setTabOrder(self.txtClientInfoBrowser, self.treeOrgStructure)
        TissueJournalDialog.setTabOrder(self.treeOrgStructure, self.tabWidgetFilter)
        TissueJournalDialog.setTabOrder(self.tabWidgetFilter, self.btnCalendar)
        TissueJournalDialog.setTabOrder(self.btnCalendar, self.calendar)
        TissueJournalDialog.setTabOrder(self.calendar, self.btnDateRange)
        TissueJournalDialog.setTabOrder(self.btnDateRange, self.edtDateFrom)
        TissueJournalDialog.setTabOrder(self.edtDateFrom, self.edtDateTo)
        TissueJournalDialog.setTabOrder(self.edtDateTo, self.chkFilterId)
        TissueJournalDialog.setTabOrder(self.chkFilterId, self.cmbFilterAccountingSystem)
        TissueJournalDialog.setTabOrder(self.cmbFilterAccountingSystem, self.edtFilterId)
        TissueJournalDialog.setTabOrder(self.edtFilterId, self.chkFilterLastName)
        TissueJournalDialog.setTabOrder(self.chkFilterLastName, self.edtFilterLastName)
        TissueJournalDialog.setTabOrder(self.edtFilterLastName, self.chkFilterFirstName)
        TissueJournalDialog.setTabOrder(self.chkFilterFirstName, self.edtFilterFirstName)
        TissueJournalDialog.setTabOrder(self.edtFilterFirstName, self.chkFilterPatrName)
        TissueJournalDialog.setTabOrder(self.chkFilterPatrName, self.edtFilterPatrName)
        TissueJournalDialog.setTabOrder(self.edtFilterPatrName, self.chkFilterBirthDay)
        TissueJournalDialog.setTabOrder(self.chkFilterBirthDay, self.edtFilterBirthDay)
        TissueJournalDialog.setTabOrder(self.edtFilterBirthDay, self.tblTissueTypes)
        TissueJournalDialog.setTabOrder(self.tblTissueTypes, self.chkIBM)
        TissueJournalDialog.setTabOrder(self.chkIBM, self.edtIBM)
        TissueJournalDialog.setTabOrder(self.edtIBM, self.chkTissueType)
        TissueJournalDialog.setTabOrder(self.chkTissueType, self.chkWithoutSampling)
        TissueJournalDialog.setTabOrder(self.chkWithoutSampling, self.chkUrgent)
        TissueJournalDialog.setTabOrder(self.chkUrgent, self.chkClientSex)
        TissueJournalDialog.setTabOrder(self.chkClientSex, self.cmbClientSex)
        TissueJournalDialog.setTabOrder(self.cmbClientSex, self.chkRelegateOrg)
        TissueJournalDialog.setTabOrder(self.chkRelegateOrg, self.cmbRelegateOrg)
        TissueJournalDialog.setTabOrder(self.cmbRelegateOrg, self.chkStatus)
        TissueJournalDialog.setTabOrder(self.chkStatus, self.cmbStatus)
        TissueJournalDialog.setTabOrder(self.cmbStatus, self.chkPreliminaryResult)
        TissueJournalDialog.setTabOrder(self.chkPreliminaryResult, self.cmbPreliminaryResult)
        TissueJournalDialog.setTabOrder(self.cmbPreliminaryResult, self.cmbEventType)
        TissueJournalDialog.setTabOrder(self.cmbEventType, self.cmbService)
        TissueJournalDialog.setTabOrder(self.cmbService, self.cmbActionType)
        TissueJournalDialog.setTabOrder(self.cmbActionType, self.cmbFinanceType)
        TissueJournalDialog.setTabOrder(self.cmbFinanceType, self.cmbExecOrgStructure)
        TissueJournalDialog.setTabOrder(self.cmbExecOrgStructure, self.cmbExecPerson)
        TissueJournalDialog.setTabOrder(self.cmbExecPerson, self.cmbExecOrg)
        TissueJournalDialog.setTabOrder(self.cmbExecOrg, self.buttonBoxFilter)
        TissueJournalDialog.setTabOrder(self.buttonBoxFilter, self.tblTissueJournal)
        TissueJournalDialog.setTabOrder(self.tblTissueJournal, self.tblTissueJournalActions)
        TissueJournalDialog.setTabOrder(self.tblTissueJournalActions, self.tblResultTissueType)
        TissueJournalDialog.setTabOrder(self.tblResultTissueType, self.chkResultRelegateOrg)
        TissueJournalDialog.setTabOrder(self.chkResultRelegateOrg, self.cmbResultRelegateOrg)
        TissueJournalDialog.setTabOrder(self.cmbResultRelegateOrg, self.edtResultDateFrom)
        TissueJournalDialog.setTabOrder(self.edtResultDateFrom, self.edtResultDateTo)
        TissueJournalDialog.setTabOrder(self.edtResultDateTo, self.edtResultTissueIdentifierFrom)
        TissueJournalDialog.setTabOrder(self.edtResultTissueIdentifierFrom, self.edtResultTissueIdentifierTo)
        TissueJournalDialog.setTabOrder(self.edtResultTissueIdentifierTo, self.chkResultTissueRegistrator)
        TissueJournalDialog.setTabOrder(self.chkResultTissueRegistrator, self.cmbResultTissueRegistrator)
        TissueJournalDialog.setTabOrder(self.cmbResultTissueRegistrator, self.chkResultEventType)
        TissueJournalDialog.setTabOrder(self.chkResultEventType, self.cmbResultEventType)
        TissueJournalDialog.setTabOrder(self.cmbResultEventType, self.cmbResultService)
        TissueJournalDialog.setTabOrder(self.cmbResultService, self.tblResultActionType)
        TissueJournalDialog.setTabOrder(self.tblResultActionType, self.tabWidgetResultActionsFilter)
        TissueJournalDialog.setTabOrder(self.tabWidgetResultActionsFilter, self.chkResultUrgent)
        TissueJournalDialog.setTabOrder(self.chkResultUrgent, self.edtResultSamplingNumberFrom)
        TissueJournalDialog.setTabOrder(self.edtResultSamplingNumberFrom, self.edtResultSamplingNumberTo)
        TissueJournalDialog.setTabOrder(self.edtResultSamplingNumberTo, self.chkResultClientSex)
        TissueJournalDialog.setTabOrder(self.chkResultClientSex, self.cmbResultClientSex)
        TissueJournalDialog.setTabOrder(self.cmbResultClientSex, self.chkResultStatus)
        TissueJournalDialog.setTabOrder(self.chkResultStatus, self.cmbResultStatus)
        TissueJournalDialog.setTabOrder(self.cmbResultStatus, self.chkResultPreliminaryResult)
        TissueJournalDialog.setTabOrder(self.chkResultPreliminaryResult, self.cmbResultPreliminaryResult)
        TissueJournalDialog.setTabOrder(self.cmbResultPreliminaryResult, self.chkResultFinance)
        TissueJournalDialog.setTabOrder(self.chkResultFinance, self.cmbResultFinanceType)
        TissueJournalDialog.setTabOrder(self.cmbResultFinanceType, self.chkResultOnlyTests)
        TissueJournalDialog.setTabOrder(self.chkResultOnlyTests, self.cmbResultExecOrg)
        TissueJournalDialog.setTabOrder(self.cmbResultExecOrg, self.chkResultActionSetPerson)
        TissueJournalDialog.setTabOrder(self.chkResultActionSetPerson, self.cmbResultActionSetPersonOrgStructure)
        TissueJournalDialog.setTabOrder(self.cmbResultActionSetPersonOrgStructure, self.cmbResultActionSetPersonSpeciality)
        TissueJournalDialog.setTabOrder(self.cmbResultActionSetPersonSpeciality, self.cmbResultActionSetPerson)
        TissueJournalDialog.setTabOrder(self.cmbResultActionSetPerson, self.chkResultActionExecPerson)
        TissueJournalDialog.setTabOrder(self.chkResultActionExecPerson, self.cmbResultActionExecPerson)
        TissueJournalDialog.setTabOrder(self.cmbResultActionExecPerson, self.chkResultActionAssistant)
        TissueJournalDialog.setTabOrder(self.chkResultActionAssistant, self.cmbResultActionAssistant)
        TissueJournalDialog.setTabOrder(self.cmbResultActionAssistant, self.chkResultClientId)
        TissueJournalDialog.setTabOrder(self.chkResultClientId, self.cmbResultClientIdAccountingSystem)
        TissueJournalDialog.setTabOrder(self.cmbResultClientIdAccountingSystem, self.edtResultClientId)
        TissueJournalDialog.setTabOrder(self.edtResultClientId, self.tblResultTests)
        TissueJournalDialog.setTabOrder(self.tblResultTests, self.tblResultActions)
        TissueJournalDialog.setTabOrder(self.tblResultActions, self.tblResultProperties)
        TissueJournalDialog.setTabOrder(self.tblResultProperties, self.buttonBox)
        TissueJournalDialog.setTabOrder(self.buttonBox, self.buttonBoxResult)
        TissueJournalDialog.setTabOrder(self.buttonBoxResult, self.chkResultWithoutSampling)

    def retranslateUi(self, TissueJournalDialog):
        TissueJournalDialog.setWindowTitle(_translate("TissueJournalDialog", "Dialog", None))
        self.lblDateFrom.setText(_translate("TissueJournalDialog", "Дата с: ", None))
        self.lblDateTo.setText(_translate("TissueJournalDialog", "по: ", None))
        self.tabWidgetFilter.setTabText(self.tabWidgetFilter.indexOf(self.tabCalendar), _translate("TissueJournalDialog", "По дате", None))
        self.chkFilterId.setText(_translate("TissueJournalDialog", "Код", None))
        self.chkFilterLastName.setText(_translate("TissueJournalDialog", "Фамилия", None))
        self.chkFilterFirstName.setText(_translate("TissueJournalDialog", "Имя", None))
        self.chkFilterPatrName.setText(_translate("TissueJournalDialog", "Отчество", None))
        self.chkFilterBirthDay.setText(_translate("TissueJournalDialog", "Дата рожд", None))
        self.tabWidgetFilter.setTabText(self.tabWidgetFilter.indexOf(self.tabClient), _translate("TissueJournalDialog", "По пациенту", None))
        self.grpStaticFilter.setTitle(_translate("TissueJournalDialog", "Фильтр", None))
        self.chkTissueType.setText(_translate("TissueJournalDialog", "Не учитывать тип биоматериала", None))
        self.chkUrgent.setText(_translate("TissueJournalDialog", "Срочно", None))
        self.chkStatus.setText(_translate("TissueJournalDialog", "Статус", None))
        self.cmbStatus.setItemText(0, _translate("TissueJournalDialog", "Начато", None))
        self.cmbStatus.setItemText(1, _translate("TissueJournalDialog", "Ожидание", None))
        self.cmbStatus.setItemText(2, _translate("TissueJournalDialog", "Закончено", None))
        self.cmbStatus.setItemText(3, _translate("TissueJournalDialog", "Отменено", None))
        self.cmbStatus.setItemText(4, _translate("TissueJournalDialog", "Без результата", None))
        self.cmbStatus.setItemText(5, _translate("TissueJournalDialog", "Назначено", None))
        self.lblEventType.setText(_translate("TissueJournalDialog", "Тип события", None))
        self.lblService.setText(_translate("TissueJournalDialog", "Профиль оплаты", None))
        self.lblActionType.setText(_translate("TissueJournalDialog", "Тип действия", None))
        self.lblFinanceType.setText(_translate("TissueJournalDialog", "Тип финансирования", None))
        self.lblExecOrgStructure.setText(_translate("TissueJournalDialog", "Подразделение", None))
        self.lblExecPerson.setText(_translate("TissueJournalDialog", "Ответственный", None))
        self.lblExecOrg.setText(_translate("TissueJournalDialog", "Место выполнения", None))
        self.chkClientSex.setText(_translate("TissueJournalDialog", "Пол", None))
        self.cmbClientSex.setItemText(0, _translate("TissueJournalDialog", "М", None))
        self.cmbClientSex.setItemText(1, _translate("TissueJournalDialog", "Ж", None))
        self.chkRelegateOrg.setText(_translate("TissueJournalDialog", "Направитель", None))
        self.chkPreliminaryResult.setText(_translate("TissueJournalDialog", "Предварительный результат", None))
        self.cmbPreliminaryResult.setItemText(0, _translate("TissueJournalDialog", "Не определен", None))
        self.cmbPreliminaryResult.setItemText(1, _translate("TissueJournalDialog", "Получен", None))
        self.cmbPreliminaryResult.setItemText(2, _translate("TissueJournalDialog", "Без результата", None))
        self.chkWithoutSampling.setText(_translate("TissueJournalDialog", "Без пробоподготовки", None))
        self.chkIBM.setText(_translate("TissueJournalDialog", "ИБМ", None))
        self.lblTissueJournalCount.setText(_translate("TissueJournalDialog", "Список забора тканей пуст", None))
        self.lblAllActionsCount.setText(_translate("TissueJournalDialog", "Количество всех связанных действий", None))
        self.lblClientCount.setText(_translate("TissueJournalDialog", "Количиство пациентов", None))
        self.lblActionsCount.setText(_translate("TissueJournalDialog", "Список действий пуст", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tabTissue), _translate("TissueJournalDialog", "&Биоматериал", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tabProbeWorkList), _translate("TissueJournalDialog", "Р&абочий лист", None))
        self.chkResultEventType.setText(_translate("TissueJournalDialog", "Тип события", None))
        self.lblResultFrom.setText(_translate("TissueJournalDialog", "Дата с: ", None))
        self.lblResultTo.setText(_translate("TissueJournalDialog", "по: ", None))
        self.lblResultTissueIdentifierFrom.setText(_translate("TissueJournalDialog", "ИБМ с: ", None))
        self.edtResultTissueIdentifierFrom.setToolTip(_translate("TissueJournalDialog", "Идентификатор биоматериала, нижняя граница\n"
"Если отсутствует верхняя граница(\'по\') проверяет не полное вхождение", None))
        self.lblResultTissueIdentifierTo.setText(_translate("TissueJournalDialog", "по: ", None))
        self.edtResultTissueIdentifierTo.setToolTip(_translate("TissueJournalDialog", "Идентификатор биоматериала, верхняя граница", None))
        self.chkResultTissueRegistrator.setText(_translate("TissueJournalDialog", "Регистратор биоматериала", None))
        self.lblResultService.setText(_translate("TissueJournalDialog", "Профиль оплаты", None))
        self.chkResultRelegateOrg.setText(_translate("TissueJournalDialog", "Направитель", None))
        self.grpResultActionsFilter.setTitle(_translate("TissueJournalDialog", "Фильтр действий", None))
        self.chkResultUrgent.setText(_translate("TissueJournalDialog", "Срочно", None))
        self.lblResultSamplingNumberFrom.setText(_translate("TissueJournalDialog", "Номер пробы с:", None))
        self.lblResultSamplingNumberTo.setText(_translate("TissueJournalDialog", "по: ", None))
        self.chkResultStatus.setText(_translate("TissueJournalDialog", "Статус", None))
        self.cmbResultStatus.setItemText(0, _translate("TissueJournalDialog", "Начато", None))
        self.cmbResultStatus.setItemText(1, _translate("TissueJournalDialog", "Ожидание", None))
        self.cmbResultStatus.setItemText(2, _translate("TissueJournalDialog", "Закончено", None))
        self.cmbResultStatus.setItemText(3, _translate("TissueJournalDialog", "Отменено", None))
        self.cmbResultStatus.setItemText(4, _translate("TissueJournalDialog", "Без результата", None))
        self.cmbResultStatus.setItemText(5, _translate("TissueJournalDialog", "Назначено", None))
        self.chkResultFinance.setText(_translate("TissueJournalDialog", "Тип финансирования", None))
        self.chkResultOnlyTests.setText(_translate("TissueJournalDialog", "Только тесты", None))
        self.chkResultClientSex.setText(_translate("TissueJournalDialog", "Пол", None))
        self.cmbResultClientSex.setItemText(0, _translate("TissueJournalDialog", "М", None))
        self.cmbResultClientSex.setItemText(1, _translate("TissueJournalDialog", "Ж", None))
        self.lblResultExecOrg.setText(_translate("TissueJournalDialog", "Место выполнения", None))
        self.chkResultPreliminaryResult.setText(_translate("TissueJournalDialog", "Предварительный результат", None))
        self.cmbResultPreliminaryResult.setItemText(0, _translate("TissueJournalDialog", "Не определен", None))
        self.cmbResultPreliminaryResult.setItemText(1, _translate("TissueJournalDialog", "Получен", None))
        self.cmbResultPreliminaryResult.setItemText(2, _translate("TissueJournalDialog", "Без результата", None))
        self.chkResultWithoutSampling.setText(_translate("TissueJournalDialog", "Без пробоподготовки", None))
        self.tabWidgetResultActionsFilter.setTabText(self.tabWidgetResultActionsFilter.indexOf(self.tabResultActionsFilterMain), _translate("TissueJournalDialog", "Основной", None))
        self.chkResultActionSetPerson.setText(_translate("TissueJournalDialog", "Назначивший", None))
        self.chkResultActionExecPerson.setText(_translate("TissueJournalDialog", "Исполнитель", None))
        self.chkResultClientId.setText(_translate("TissueJournalDialog", "Код пациента", None))
        self.chkResultActionAssistant.setText(_translate("TissueJournalDialog", "Ассистент", None))
        self.tabWidgetResultActionsFilter.setTabText(self.tabWidgetResultActionsFilter.indexOf(self.tabResultActionsFilterExtension), _translate("TissueJournalDialog", "Расширенный", None))
        self.lblResultActionsCount.setText(_translate("TissueJournalDialog", "Количество действий: ", None))
        self.lblResultPropertiesCount.setText(_translate("TissueJournalDialog", "Количество свойств: ", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tabResult), _translate("TissueJournalDialog", "&Результаты", None))
        self.statusBar.setToolTip(_translate("TissueJournalDialog", "A status bar", None))
        self.statusBar.setWhatsThis(_translate("TissueJournalDialog", "A status bar.", None))
        self.btnSend.setText(_translate("TissueJournalDialog", "Отправить", None))

from Orgs.OrgComboBox import COrgComboBox, CPolyclinicComboBox
from Events.ActionTypeComboBox import CActionTypePopupView, CActionTypeComboBox
from library.crbcombobox import CRBComboBox
from TissueJournal.ProbeWorkListPage import CProbeWorkListPage
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DialogButtonBox import CApplyResetDialogButtonBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.TextBrowser import CTextBrowser
from library.TableView import CTableView
from library.DateEdit import CDateEdit
from library.crbservicecombobox import CRBServiceComboBox
from library.calendar import CCalendarWidget
